import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { ALGO_QUANT_SOURCES } from './algoQuantSources';

const overfitting = createFoundationLesson({
  id: 'lesson.quant.overfitting.001', slug: 'overfitting-nedir', conceptKey: 'quant.overfitting', skillId: 'skill.algo-quant', competencyId: 'competency.overfitting.foundation',
  title: 'Overfitting neden backtesti güzelleştirir ama sistemi bozabilir?', titleEn: 'Why can overfitting improve a backtest but weaken the system?',
  objective: 'Overfittingi geçmiş verinin gürültüsüne aşırı uyum olarak açıklar ve parametre arttıkça seçim riskinin büyüyebileceğini ayırt eder.', objectiveEn: 'Explain overfitting as excessive adaptation to historical noise and distinguish how more parameters can increase selection risk.', minutes: 5,
  hook: 'Backtesti her ay daha güzel hale getiriyorsan gerçekten sistemi mi geliştiriyorsun, geçmişi mi ezberletiyorsun?', hookEn: 'If every tweak makes the backtest prettier, are you improving the system or teaching it to memorize history?',
  explanation: 'Overfitting, bir model veya stratejinin temel ilişkiyi öğrenmek yerine geçmiş verideki tesadüfi ayrıntılara uyum sağlamasıdır. Çok sayıda kural, filtre ve parametre denenirse geçmişte çok iyi görünen ama yeni veride zayıflayan kombinasyon bulmak kolaylaşır.', explanationEn: 'Overfitting occurs when a model or strategy adapts to accidental details in historical data instead of a durable relationship. Trying many rules, filters, and parameters makes it easier to find combinations that look excellent in-sample but weaken on new data.',
  proExplanation: 'Model complexity, multiple testing, parameter search breadth, weak economic rationale, and repeated holdout inspection increase overfitting risk. Simplicity alone does not prove robustness, but complexity raises the burden of evidence.', proExplanationEn: 'Model complexity, multiple testing, broad parameter searches, weak economic rationale, and repeated holdout inspection increase overfitting risk. Simplicity alone does not prove robustness, but complexity raises the burden of evidence.',
  misconception: 'Yaygın hata: Backtest sonucu iyileştikçe modelin otomatik olarak daha iyi olduğuna inanmak.', misconceptionEn: 'Common mistake: assuming every improvement in historical fit makes the model better.',
  takeaway: 'Geçmişe daha iyi uyum, geleceğe daha iyi genelleme demek değildir.', takeawayEn: 'Better historical fit does not automatically mean better generalization.',
  prerequisiteConceptKeys: ['quant.backtest', 'quant.out_of_sample'], relatedConceptKeys: ['market.technical.indicator_limits', 'strategy.hypothesis', 'quant.robustness'],
  visualAlt: 'Basit modelin ana örüntüyü izlemesi ile aşırı karmaşık modelin her tarihsel gürültü noktasına kıvrılmasını karşılaştıran görsel', visualAltEn: 'Visual comparing a simple model following the main pattern with an overfit model bending around every historical noise point',
  taskPrompt: 'Hangisi overfitting riskini artırır?', taskPromptEn: 'What increases overfitting risk?',
  taskChoices: [{ id: 'many', label: 'Çok sayıda parametre ve kombinasyon denemek', labelEn: 'Trying many parameters and combinations' }, { id: 'holdout', label: 'Bağımsız doğrulama kullanmak', labelEn: 'Using independent validation' }, { id: 'simple', label: 'Hipotezi önceden yazmak', labelEn: 'Writing the hypothesis in advance' }], taskCorrectIds: ['many'],
  questions: [
    { prompt: 'Overfitting neye aşırı uyumdur?', promptEn: 'What does overfitting adapt too closely to?', choices: [{ id: 'a', label: 'Geçmiş verideki gürültü ve tesadüfi ayrıntılara', labelEn: 'Noise and accidental details in historical data' }, { id: 'b', label: 'Geleceğe', labelEn: 'The future' }, { id: 'c', label: 'Sadece spread’e', labelEn: 'Only the spread' }], correctId: 'a', explanation: 'Model gerçek ilişki yerine gürültüyü öğrenebilir.', explanationEn: 'The model can learn noise instead of durable structure.' },
    { prompt: 'Daha fazla parametre her zaman daha iyi midir?', promptEn: 'Are more parameters always better?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız kısa vadede', labelEn: 'Only short term' }], correctId: 'a', explanation: 'Karmaşıklık seçim ve genelleme riskini artırabilir.', explanationEn: 'Complexity can increase selection and generalization risk.' },
    { prompt: 'Out-of-sample test overfitting riskini tamamen yok eder mi?', promptEn: 'Does out-of-sample testing eliminate overfitting completely?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece bir kez bakılırsa kesin', labelEn: 'Yes if checked once' }], correctId: 'a', explanation: 'Seçim süreci ve tekrar tekrar test etme riski devam edebilir.', explanationEn: 'Selection and repeated testing risks can remain.' },
  ], sources: [ALGO_QUANT_SOURCES.validation],
});

const lookahead = createFoundationLesson({
  id: 'lesson.quant.lookahead-bias.001', slug: 'look-ahead-bias-nedir', conceptKey: 'quant.lookahead_bias', skillId: 'skill.algo-quant', competencyId: 'competency.lookahead.foundation',
  title: 'Backtest geleceği yanlışlıkla biliyor olabilir mi?', titleEn: 'Can a backtest accidentally know the future?',
  objective: 'Look-ahead biası karar anında henüz mevcut olmayan bilginin geçmiş simülasyonda kullanılması olarak açıklar.', objectiveEn: 'Explain look-ahead bias as using information in a historical simulation that was not yet available at the decision time.', minutes: 5,
  hook: 'Bugünün kapanış fiyatını kullanıp yine bugünün kapanışında işlem yaptığını varsayarsan hangi bilgi ne zaman biliniyordu?', hookEn: 'If you use today’s closing price and assume you traded at that same close, when was the information actually known?',
  explanation: 'Look-ahead bias, backtestin karar verdiği anda gerçekte henüz bilinmeyen veriyi kullanmasıdır. Örneğin gün sonu verisini gün sonu gerçekleşme fiyatından önce biliniyormuş gibi kullanmak, revize edilmiş ekonomik veriyi ilk açıklama tarihinde mevcut sanmak veya sonraki dönem bilgisiyle geçmiş evren oluşturmak sonucu yapay biçimde iyileştirebilir.', explanationEn: 'Look-ahead bias occurs when a backtest uses information that was not actually available at the decision time. Examples include using end-of-day data as if known before an end-of-day fill, using revised economic data at the original release date, or constructing past universes with future information.',
  proExplanation: 'Point-in-time timestamps, publication delays, corporate-action effective dates, signal calculation cutoffs, and execution lags must align. Even a one-bar timing error can create material bias in fast strategies.', proExplanationEn: 'Point-in-time timestamps, publication delays, corporate-action effective dates, signal calculation cutoffs, and execution lags must align. Even a one-bar timing error can create material bias in fast strategies.',
  misconception: 'Yaygın hata: Veri tarihini görmekle verinin o anda gerçekten erişilebilir olduğunu aynı şey sanmak.', misconceptionEn: 'Common mistake: assuming a data timestamp proves the information was actually available at that moment.',
  takeaway: 'Backtestte her bilginin “ne zaman biliniyordu?” sorusunu cevapla.', takeawayEn: 'For every input in a backtest, ask: “When was this actually known?”',
  prerequisiteConceptKeys: ['quant.backtest'], relatedConceptKeys: ['evidence.freshness', 'quant.data_leakage', 'quant.survivorship_bias'],
  visualAlt: 'Karar zamanı çizgisinde henüz yayınlanmamış gelecekteki verinin geriye sızmasını kırmızı uyarıyla gösteren zamanlama görseli', visualAltEn: 'Timing visual showing future data leaking backward into a decision point with a warning',
  taskPrompt: 'Hangisi look-ahead bias örneğidir?', taskPromptEn: 'Which is an example of look-ahead bias?',
  taskChoices: [{ id: 'future', label: 'Karar anında henüz açıklanmamış veriyi kullanmak', labelEn: 'Using data not yet published at the decision time' }, { id: 'cost', label: 'Komisyon eklemek', labelEn: 'Adding commissions' }, { id: 'split', label: 'Out-of-sample ayırmak', labelEn: 'Creating an out-of-sample split' }], taskCorrectIds: ['future'],
  questions: [
    { prompt: 'Look-ahead bias nedir?', promptEn: 'What is look-ahead bias?', choices: [{ id: 'a', label: 'Gelecekte bilinecek bilgiyi geçmiş kararda kullanmak', labelEn: 'Using future-known information in a past decision' }, { id: 'b', label: 'Spreadi ölçmek', labelEn: 'Measuring spread' }, { id: 'c', label: 'Volatilite hesaplamak', labelEn: 'Calculating volatility' }], correctId: 'a', explanation: 'Karar zamanı ile bilgi erişim zamanı karışır.', explanationEn: 'Decision time and information availability become misaligned.' },
    { prompt: 'Revize edilmiş veri risk yaratabilir mi?', promptEn: 'Can revised data create look-ahead risk?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız fiyat verisinde', labelEn: 'Only in price data' }], correctId: 'a', explanation: 'Revizyon ilk karar tarihinde mevcut olmayabilir.', explanationEn: 'The revision may not have existed at the original decision time.' },
    { prompt: 'Signal ve execution zamanı eşleşmeli mi?', promptEn: 'Should signal and execution timing be aligned?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Önemsizdir', labelEn: 'It does not matter' }], correctId: 'a', explanation: 'Gerçekçi uygulanabilirlik için zamanlama gerekir.', explanationEn: 'Timing alignment is required for realistic implementation.' },
  ], sources: [ALGO_QUANT_SOURCES.validation],
});

const survivorship = createFoundationLesson({
  id: 'lesson.quant.survivorship-bias.001', slug: 'survivorship-bias-nedir', conceptKey: 'quant.survivorship_bias', skillId: 'skill.algo-quant', competencyId: 'competency.survivorship.foundation',
  title: 'Sadece bugün hayatta kalanlara bakmak neden yanıltır?', titleEn: 'Why is testing only today’s survivors misleading?',
  objective: 'Survivorship biası geçmişte elenen, kapanan veya endeksten çıkan varlıkların örneklemden kaybolması olarak açıklar.', objectiveEn: 'Explain survivorship bias as the omission of assets that failed, delisted, closed, or exited an index from historical samples.', minutes: 5,
  hook: 'Bugünün güçlü şirket listesini 10 yıl geriye götürüp test etmek adil midir?', hookEn: 'Is it fair to take today’s strong-company list and test it ten years back?',
  explanation: 'Survivorship bias, yalnız bugün varlığını sürdüren veya seçilmiş evrende kalan varlıklarla geçmişi test ettiğinde oluşur. Başarısız, delist olmuş, birleşmiş veya endeksten çıkmış varlıklar kaybolursa geçmiş performans olduğundan daha güçlü görünebilir.', explanationEn: 'Survivorship bias appears when historical testing includes only assets that still exist or remain in today’s selected universe. Failed, delisted, merged, or removed assets disappear, which can make historical performance look stronger than it really was.',
  proExplanation: 'Point-in-time constituents, delisting returns, corporate events, and historical universe membership matter. Current index membership should not be backfilled into periods before those constituents entered.', proExplanationEn: 'Point-in-time constituents, delisting returns, corporate events, and historical universe membership matter. Current index membership should not be backfilled into periods before those constituents entered.',
  misconception: 'Yaygın hata: “Veri eksiksiz” olduğu için örneklemin de tarafsız olduğunu düşünmek.', misconceptionEn: 'Common mistake: assuming a complete dataset is automatically an unbiased universe.',
  takeaway: 'Geçmiş evreni, o dönemde gerçekten var olan katılımcılarla kur.', takeawayEn: 'Build historical universes from participants that actually existed at that time.',
  prerequisiteConceptKeys: ['quant.backtest'], relatedConceptKeys: ['quant.lookahead_bias', 'evidence.data_quality', 'quant.robustness'],
  visualAlt: 'Başlangıçta çok sayıda varlık varken zamanla elenenlerin griye düştüğü, yalnız hayatta kalanları seçmenin yanlılık yarattığını gösteren görsel', visualAltEn: 'Visual showing many starting assets with failures dropping out and the bias from retaining only survivors',
  taskPrompt: 'Hangisi survivorship bias yaratır?', taskPromptEn: 'What creates survivorship bias?',
  taskChoices: [{ id: 'current', label: 'Bugünkü endeks üyelerini geçmişin tamamında varmış gibi test etmek', labelEn: 'Testing today’s index members as if they existed throughout the past' }, { id: 'point', label: 'Tarihsel üyeliği dönem dönem kullanmak', labelEn: 'Using point-in-time membership' }, { id: 'delist', label: 'Delist olanları dahil etmek', labelEn: 'Including delisted assets' }], taskCorrectIds: ['current'],
  questions: [
    { prompt: 'Survivorship bias hangi varlıkları görünmez yapabilir?', promptEn: 'Which assets can survivorship bias make invisible?', choices: [{ id: 'a', label: 'Başarısız veya evrenden çıkmış varlıkları', labelEn: 'Failed or removed assets' }, { id: 'b', label: 'Sadece kazananları', labelEn: 'Only winners' }, { id: 'c', label: 'Yalnız ETFleri', labelEn: 'Only ETFs' }], correctId: 'a', explanation: 'Örneklem yalnız hayatta kalanlara kayabilir.', explanationEn: 'The sample can become tilted toward survivors.' },
    { prompt: 'Bugünkü endeks üyeliğini geçmişe taşımak riskli midir?', promptEn: 'Is backfilling today’s index membership risky?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece küçük endekste', labelEn: 'Only in small indices' }], correctId: 'a', explanation: 'Gelecekte kimlerin kalacağını geçmişe taşır.', explanationEn: 'It imports knowledge of future survivors into the past.' },
    { prompt: 'Delisting olayları veri kalitesinin parçası mıdır?', promptEn: 'Are delisting events part of data quality?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Önemsizdir', labelEn: 'They do not matter' }], correctId: 'a', explanation: 'Evren ve sonuçların gerçekçi tutulmasına yardım eder.', explanationEn: 'They help preserve a realistic historical universe and outcomes.' },
  ], sources: [ALGO_QUANT_SOURCES.validation],
});

const dataLeakage = createFoundationLesson({
  id: 'lesson.quant.data-leakage.001', slug: 'data-leakage-nedir', conceptKey: 'quant.data_leakage', skillId: 'skill.algo-quant', competencyId: 'competency.data-leakage.foundation',
  title: 'Model test bilgisini eğitim sırasında görürse ne olur?', titleEn: 'What happens if a model sees test information during training?',
  objective: 'Data leakageı eğitim veya özellik üretim sürecine değerlendirme dönemine ait bilginin sızması olarak açıklar.', objectiveEn: 'Explain data leakage as evaluation-period information entering training or feature construction.', minutes: 5,
  hook: 'Test sorularının cevaplarını çalışırken görürsen sınav sonucu hâlâ adil bir ölçüm müdür?', hookEn: 'If you see test answers while studying, is the exam still a fair measurement?',
  explanation: 'Data leakage, modelin veya araştırma sürecinin değerlendirme sırasında bilinmemesi gereken bilgiyi eğitim, normalizasyon, özellik üretimi veya seçim adımında kullanmasıdır. Bu, gerçek sinyal varmış gibi görünen ama canlıda kaybolan performans yaratabilir.', explanationEn: 'Data leakage occurs when training, normalization, feature construction, or selection uses information that should remain unknown during evaluation. It can create apparent signal that disappears in live use.',
  proExplanation: 'Leakage can arise through global normalization, target-derived features, future-aware preprocessing, cross-sectional contamination, duplicate records, or entity overlap between train and test. Pipelines must preserve temporal and entity boundaries.', proExplanationEn: 'Leakage can arise through global normalization, target-derived features, future-aware preprocessing, cross-sectional contamination, duplicate records, or entity overlap between train and test. Pipelines must preserve temporal and entity boundaries.',
  misconception: 'Yaygın hata: Sadece doğrudan hedef sütununu modele vermediğin sürece leakage olamayacağını sanmak.', misconceptionEn: 'Common mistake: assuming leakage only means directly feeding the target column into the model.',
  takeaway: 'Test bilgisini yalnız sonuç ölçerken kullan; eğitim ve feature üretiminden uzak tut.', takeawayEn: 'Use test information only for evaluation; keep it out of training and feature construction.',
  prerequisiteConceptKeys: ['quant.out_of_sample'], relatedConceptKeys: ['quant.lookahead_bias', 'evidence.data_quality', 'quant.robustness'],
  visualAlt: 'Train ve test kutuları arasında testten train tarafına yasak bilgi akışını kırmızı okla gösteren veri sızıntısı diyagramı', visualAltEn: 'Data-leakage diagram showing a forbidden red arrow from test data into training',
  taskPrompt: 'Hangisi data leakage örneğidir?', taskPromptEn: 'Which is an example of data leakage?',
  taskChoices: [{ id: 'global', label: 'Tüm veriyle normalizasyon yapıp sonra train/test ayırmak', labelEn: 'Normalizing on the full dataset before splitting train/test' }, { id: 'train', label: 'Normalizerı yalnız train verisine fit etmek', labelEn: 'Fitting the normalizer only on training data' }, { id: 'holdout', label: 'Test setini değerlendirmeye kadar saklamak', labelEn: 'Keeping the test set untouched until evaluation' }], taskCorrectIds: ['global'],
  questions: [
    { prompt: 'Data leakage ne yapar?', promptEn: 'What does data leakage do?', choices: [{ id: 'a', label: 'Değerlendirme bilgisini eğitim sürecine sızdırır', labelEn: 'Leaks evaluation information into training' }, { id: 'b', label: 'Komisyonu artırır', labelEn: 'Raises commissions' }, { id: 'c', label: 'Likiditeyi ölçer', labelEn: 'Measures liquidity' }], correctId: 'a', explanation: 'Test bağımsızlığı bozulur.', explanationEn: 'Evaluation independence is broken.' },
    { prompt: 'Global normalization leakage yaratabilir mi?', promptEn: 'Can global normalization create leakage?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız görüntü verisinde', labelEn: 'Only in image data' }], correctId: 'a', explanation: 'Test dağılımı train dönüşümüne bilgi taşıyabilir.', explanationEn: 'Test-distribution information can enter the training transformation.' },
    { prompt: 'Leakage canlı performansı neden bozabilir?', promptEn: 'Why can leakage hurt live performance?', choices: [{ id: 'a', label: 'Canlıda erişilemeyen bilgiyi testte kullanmıştır', labelEn: 'The test relied on information unavailable live' }, { id: 'b', label: 'Win rate’i otomatik düşürür', labelEn: 'It automatically lowers win rate' }, { id: 'c', label: 'Her zaman spreadi büyütür', labelEn: 'It always widens spread' }], correctId: 'a', explanation: 'Simülasyon gerçek bilgi setini taklit etmez.', explanationEn: 'The simulation no longer matches the real information set.' },
  ], sources: [ALGO_QUANT_SOURCES.validation],
});

const robustness = createFoundationLesson({
  id: 'lesson.quant.robustness.001', slug: 'robustness-nasil-test-edilir', conceptKey: 'quant.robustness', skillId: 'skill.algo-quant', competencyId: 'competency.robustness.foundation',
  title: 'Bir strateji tek ayarda değil, çevresinde de ayakta kalıyor mu?', titleEn: 'Does a strategy survive around its chosen settings?',
  objective: 'Robustnessı sonuçların küçük parametre, dönem, maliyet ve örneklem değişimlerinde tamamen dağılmaması olarak açıklar.', objectiveEn: 'Explain robustness as performance not collapsing under small changes in parameters, periods, costs, or samples.', minutes: 5,
  hook: 'Parametre 20 iken harika, 19 ve 21 iken kötü olan sistem sana ne söyler?', hookEn: 'What does it tell you if a system is excellent at parameter 20 but poor at 19 and 21?',
  explanation: 'Robustness, bir yöntemin yalnız tek seçilmiş ayarda değil, makul komşu varsayımlarda ve farklı dönemlerde de benzer davranış göstermesidir. Küçük değişiklik sonucu tamamen tersine çeviriyorsa strateji gürültüye hassas olabilir.', explanationEn: 'Robustness means a method behaves reasonably not only at one chosen setting but across nearby assumptions and different periods. If tiny changes reverse the result, the strategy may be noise-sensitive.',
  proExplanation: 'Parameter perturbation, subperiod tests, alternative cost assumptions, bootstrap/resampling, walk-forward checks, and stress scenarios can reveal fragility. Robustness does not guarantee persistence; it raises the quality of evidence.', proExplanationEn: 'Parameter perturbation, subperiod tests, alternative cost assumptions, bootstrap/resampling, walk-forward checks, and stress scenarios can reveal fragility. Robustness does not guarantee persistence; it raises the quality of evidence.',
  misconception: 'Yaygın hata: Tek bir en iyi parametreyi bulmayı araştırmanın amacı sanmak.', misconceptionEn: 'Common mistake: treating the single best parameter as the goal of research.',
  takeaway: 'Tek zirve yerine geniş ve dayanıklı bir davranış bölgesi ara.', takeawayEn: 'Look for a broad stable region, not one perfect peak.',
  prerequisiteConceptKeys: ['quant.overfitting', 'quant.out_of_sample'], relatedConceptKeys: ['portfolio.stress_testing', 'strategy.regime_fit', 'quant.transaction_costs'],
  visualAlt: 'Tek sivri performans zirvesi ile geniş ve daha istikrarlı performans platosunu karşılaştıran robustness görseli', visualAltEn: 'Robustness visual comparing one sharp performance peak with a broad stable plateau',
  taskPrompt: 'Hangisi daha robust görünür?', taskPromptEn: 'Which looks more robust?',
  taskChoices: [{ id: 'plateau', label: 'Yakın parametrelerde benzer sonuç veren geniş plato', labelEn: 'A broad plateau with similar nearby results' }, { id: 'spike', label: 'Tek parametrede aşırı iyi sivri tepe', labelEn: 'One extreme spike at a single parameter' }, { id: 'best', label: 'En yüksek tek sayı', labelEn: 'The single highest number' }], taskCorrectIds: ['plateau'],
  questions: [
    { prompt: 'Robustness neyi arar?', promptEn: 'What does robustness look for?', choices: [{ id: 'a', label: 'Makul değişikliklerde sonuçların tamamen dağılmamasını', labelEn: 'Results not collapsing under reasonable changes' }, { id: 'b', label: 'Tek en iyi parametreyi', labelEn: 'One best parameter' }, { id: 'c', label: '%100 win rate’i', labelEn: 'A 100% win rate' }], correctId: 'a', explanation: 'Dayanıklılık komşu varsayımlarda da gözlenmelidir.', explanationEn: 'Stability should appear across nearby assumptions.' },
    { prompt: 'Küçük parametre değişimi sonucu ters çeviriyorsa ne düşünülür?', promptEn: 'What if a tiny parameter change reverses results?', choices: [{ id: 'a', label: 'Kırılganlık olabilir', labelEn: 'The strategy may be fragile' }, { id: 'b', label: 'Kesin güçlüdür', labelEn: 'It is certainly strong' }, { id: 'c', label: 'Önemsizdir', labelEn: 'It does not matter' }], correctId: 'a', explanation: 'Aşırı hassasiyet overfitting işareti olabilir.', explanationEn: 'Extreme sensitivity can be a sign of overfitting.' },
    { prompt: 'Robustness gelecek garantisi midir?', promptEn: 'Does robustness guarantee the future?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece uzun backtestte', labelEn: 'Only with a long backtest' }], correctId: 'a', explanation: 'Sadece kanıt kalitesini yükseltir.', explanationEn: 'It improves evidence quality, not certainty.' },
  ], sources: [ALGO_QUANT_SOURCES.validation],
});

const automationLimits = createFoundationLesson({
  id: 'lesson.quant.automation-limits.001', slug: 'otomasyonun-sinirlari', conceptKey: 'quant.automation_limits', skillId: 'skill.algo-quant', competencyId: 'competency.automation-limits.foundation',
  title: 'Algoritma kuralları uygular; peki neyi anlayamaz?', titleEn: 'An algorithm can execute rules—but what can it miss?',
  objective: 'Otomasyonun tutarlılık sağlarken veri, model, altyapı, rejim ve operasyon hatalarını ortadan kaldırmadığını açıklar.', objectiveEn: 'Explain that automation improves consistency but does not eliminate data, model, infrastructure, regime, or operational risk.', minutes: 5,
  hook: 'Bir sistemi otomatikleştirmek onu otomatik olarak daha doğru yapar mı?', hookEn: 'Does automating a system automatically make it more correct?',
  explanation: 'Algoritmik sistem, tanımlanan kuralları hızlı ve tutarlı uygulayabilir. Ancak yanlış veri, hatalı kod, kötü maliyet modeli, değişen piyasa rejimi, bağlantı kesintisi veya beklenmeyen ürün davranışı varsa otomasyon bu hataları da hızlı ve tutarlı biçimde uygulayabilir. Otomasyon karar kalitesinin yerine geçmez.', explanationEn: 'An algorithm can apply defined rules quickly and consistently. But if the data, code, cost model, regime assumptions, connectivity, or instrument behavior are wrong, automation can apply those errors just as quickly and consistently. Automation does not replace decision quality.',
  proExplanation: 'Production systems need monitoring, kill switches, position/exposure limits, stale-data detection, idempotent order handling, reconciliation, versioned models, and rollback procedures. Research success and operational safety are separate gates.', proExplanationEn: 'Production systems need monitoring, kill switches, position/exposure limits, stale-data detection, idempotent order handling, reconciliation, versioned models, and rollback procedures. Research success and operational safety are separate gates.',
  misconception: 'Yaygın hata: “İnsan duygusu yoksa sistem objektiftir ve güvenlidir” sonucuna atlamak.', misconceptionEn: 'Common mistake: assuming removing human emotion automatically makes a system objective and safe.',
  takeaway: 'Otomasyon disiplini artırabilir; model ve operasyon riskini yok etmez.', takeawayEn: 'Automation can improve discipline; it does not remove model or operational risk.',
  prerequisiteConceptKeys: ['strategy.rules', 'quant.robustness'], relatedConceptKeys: ['evidence.freshness', 'risk.tail_risk', 'behavior.precommitment'],
  visualAlt: 'Veri, model, kural motoru, emir sistemi ve risk kill-switch katmanlarını gösteren otomasyon güvenlik zinciri', visualAltEn: 'Automation safety chain showing data, model, rule engine, execution, and risk kill-switch layers',
  taskPrompt: 'Otomatik sistem için hangisi hâlâ gereklidir?', taskPromptEn: 'What is still required for an automated system?',
  taskChoices: [{ id: 'controls', label: 'Monitoring, limitler ve kill-switch gibi operasyon kontrolleri', labelEn: 'Operational controls such as monitoring, limits, and kill switches' }, { id: 'none', label: 'Hiçbir kontrol gerekmez', labelEn: 'No controls are needed' }, { id: 'profit', label: 'Sadece kâr hedefi', labelEn: 'Only a profit target' }], taskCorrectIds: ['controls'],
  questions: [
    { prompt: 'Otomasyon hatalı kuralı düzeltebilir mi?', promptEn: 'Does automation automatically correct a bad rule?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Yanlış kuralı da tutarlı biçimde uygulayabilir.', explanationEn: 'It can execute a bad rule consistently.' },
    { prompt: 'Stale data otomatik sistem için risk midir?', promptEn: 'Is stale data a risk for automated systems?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece manuel sistemde', labelEn: 'Only in manual systems' }], correctId: 'a', explanation: 'Sistem yanlış veya eski bilgiyle hareket edebilir.', explanationEn: 'The system can act on incorrect or stale information.' },
    { prompt: 'Research başarısı production güvenliğine eşit midir?', promptEn: 'Is research success the same as production safety?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Backtest iyiyse evet', labelEn: 'Yes if the backtest is good' }], correctId: 'a', explanation: 'Operasyonel risk ayrı kontroller gerektirir.', explanationEn: 'Operational risk requires separate controls.' },
  ], sources: [ALGO_QUANT_SOURCES.methodology, ALGO_QUANT_SOURCES.validation],
});

export const ALGO_QUANT_EXPANSION_LESSONS = [overfitting, lookahead, survivorship, dataLeakage, robustness, automationLimits] as const;
