import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { ALGO_QUANT_SOURCES } from './algoQuantSources';

const probability = createFoundationLesson({
  id: 'lesson.quant.probability.001', slug: 'olaslikla-dusunmek', conceptKey: 'quant.probability', skillId: 'skill.algo-quant', competencyId: 'competency.probability.foundation',
  title: 'Tek sonuç yerine olasılıkla nasıl düşünülür?', titleEn: 'How do you think in probabilities instead of single outcomes?',
  objective: 'Bir kararı tek sonuca değil, mümkün sonuçların dağılımına göre değerlendirmeyi öğren.', objectiveEn: 'Explain why a decision should be evaluated across a distribution of possible outcomes rather than one result.', minutes: 5,
  hook: 'Bir işlem kazandıysa, kararın doğru olduğu kesin midir?', hookEn: 'If a trade won, was the decision necessarily correct?',
  explanation: 'Piyasada tek bir sonuç kesin değildir. Olasılıksal düşünme, “ne olacak?” yerine “hangi sonuçlar mümkün ve yaklaşık ne sıklıkta görülebilir?” diye sorar. Tek kazanç veya tek kayıp, yöntemin kalitesini kanıtlamaz.', explanationEn: 'Market outcomes are uncertain. Probabilistic thinking asks not “what will happen?” but “which outcomes are possible and how often might they occur?” One win or loss does not prove a method’s quality.',
  proExplanation: 'Probability estimates depend on the process, sample, regime, and data-generating assumptions. A probability is not a promise; calibration and uncertainty around the estimate matter.', proExplanationEn: 'Probability estimates depend on the process, sample, regime, and data-generating assumptions. A probability is not a promise; calibration and estimation uncertainty matter.',
  misconception: 'Yüksek olasılığı kesin, düşük olasılığı imkânsız sanma.', misconceptionEn: 'Common mistake: treating high probability as certainty and low probability as impossibility.',
  takeaway: 'İyi karar, tek sonuçtan çok olası sonuçların bütünüyle değerlendirilir.', takeawayEn: 'A good decision is judged across possible outcomes, not one realization.',
  prerequisiteConceptKeys: ['risk.basics'], relatedConceptKeys: ['quant.expectancy', 'behavior.outcome_bias', 'portfolio.stress_testing'],
  visualAlt: 'Tek bir sonuç yerine farklı olası sonuçları ve olasılık ağırlıklarını gösteren sade dağılım görseli', visualAltEn: 'Simple distribution visual showing multiple possible outcomes and probability weights',
  taskPrompt: 'Hangi ifade olasılıksal düşünmeye daha uygundur?', taskPromptEn: 'Which statement better reflects probabilistic thinking?',
  taskChoices: [{ id: 'distribution', label: 'Birden fazla sonucu ve olasılıklarını birlikte değerlendirmek', labelEn: 'Evaluate multiple outcomes and their probabilities together' }, { id: 'certain', label: 'En olası sonucu kesin kabul etmek', labelEn: 'Treat the most likely outcome as certain' }, { id: 'one', label: 'Son tek işlemi bütün sistemin kanıtı saymak', labelEn: 'Treat the last trade as proof of the whole system' }], taskCorrectIds: ['distribution'],
  questions: [
    { prompt: 'Olasılık neyi garanti eder?', promptEn: 'What does probability guarantee?', choices: [{ id: 'a', label: 'Hiçbir tek sonucu garanti etmez', labelEn: 'It guarantees no single outcome' }, { id: 'b', label: 'En yüksek olasılıklı sonucu', labelEn: 'The most probable outcome' }, { id: 'c', label: 'Kazancı', labelEn: 'A profit' }], correctId: 'a', explanation: 'Olasılık tek gerçekleşmeyi garanti etmez.', explanationEn: 'Probability does not guarantee one realization.' },
    { prompt: 'Tek kazanç iyi yöntemi kanıtlar mı?', promptEn: 'Does one win prove a good method?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız büyük kazançta', labelEn: 'Only if the win is large' }], correctId: 'a', explanation: 'Tek sonuç süreç kalitesini göstermez.', explanationEn: 'One outcome does not establish process quality.' },
    { prompt: 'Düşük olasılıklı olay mümkün müdür?', promptEn: 'Can a low-probability event still occur?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece teoride', labelEn: 'Only in theory' }], correctId: 'a', explanation: 'Düşük olasılık imkânsızlık değildir.', explanationEn: 'Low probability is not impossibility.' },
  ], sources: [ALGO_QUANT_SOURCES.methodology],
});

const expectancy = createFoundationLesson({
  id: 'lesson.quant.expectancy.001', slug: 'expectancy-nedir', conceptKey: 'quant.expectancy', skillId: 'skill.algo-quant', competencyId: 'competency.expectancy.foundation',
  title: 'Expectancy neden tek işlemden daha önemlidir?', titleEn: 'Why does expectancy matter more than one trade?',
  objective: 'Expectancy’nin kazanma oranı ile kazanç/kayıp büyüklüğünü birlikte nasıl özetlediğini öğren.', objectiveEn: 'Explain expectancy as the combined effect of win probability, average win, loss probability, and average loss.', minutes: 5,
  hook: 'Bir sistem işlemlerin yarısından azını kazanıp yine de pozitif olabilir mi?', hookEn: 'Can a system win less than half its trades and still have positive expectancy?',
  explanation: 'Expectancy, benzer işlemler çok kez tekrarlandığında ortalama ekonomik sonucun hangi yönde olabileceğini özetler. Basitçe kazanma olasılığı × ortalama kazançtan kaybetme olasılığı × ortalama kayıp çıkarılır. Geleceği garanti etmez.', explanationEn: 'Expectancy summarizes the average outcome per decision across many comparable repetitions. In simple form: win probability × average win minus loss probability × average loss. It does not guarantee the future; it summarizes an observed or assumed distribution.',
  proExplanation: 'Expectancy estimates are unstable with small samples, fat tails, regime changes, and non-stationary payoffs. Confidence around the estimate matters as much as the point estimate.', proExplanationEn: 'Expectancy estimates can be unstable with small samples, fat tails, regime changes, and non-stationary payoffs. Uncertainty around the estimate matters as much as the point estimate.',
  misconception: 'Pozitif expectancy gördün diye sıradaki işlemin kesin kazanacağını düşünme.', misconceptionEn: 'Common mistake: assuming positive expectancy means the next trade must be profitable.',
  takeaway: 'Expectancy tek işlemi değil, sonuç dağılımının ortalama etkisini anlatır.', takeawayEn: 'Expectancy describes the average economic effect of a distribution, not the next outcome.',
  prerequisiteConceptKeys: ['quant.probability', 'risk.risk_reward'], relatedConceptKeys: ['quant.winrate_payoff', 'strategy.hypothesis', 'portfolio.drawdown'],
  visualAlt: 'Kazanma olasılığı ve ortalama kazanç ile kaybetme olasılığı ve ortalama kaybı iki tarafta birleştiren expectancy görseli', visualAltEn: 'Expectancy visual combining win probability and average win against loss probability and average loss',
  taskPrompt: 'Pozitif expectancy için hangisi birlikte değerlendirilmelidir?', taskPromptEn: 'What must be evaluated together for positive expectancy?',
  taskChoices: [{ id: 'distribution', label: 'Win rate ile ortalama kazanç/kayıp büyüklüğü', labelEn: 'Win rate with average win/loss size' }, { id: 'winrate', label: 'Sadece win rate', labelEn: 'Win rate alone' }, { id: 'last', label: 'Sadece son işlem', labelEn: 'Only the last trade' }], taskCorrectIds: ['distribution'],
  questions: [
    { prompt: 'Expectancy yalnız win rate midir?', promptEn: 'Is expectancy just win rate?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece günlük sistemlerde', labelEn: 'Only for daily systems' }], correctId: 'a', explanation: 'Payoff büyüklüğü de gerekir.', explanationEn: 'Payoff size also matters.' },
    { prompt: 'Pozitif expectancy sonraki işlemi garanti eder mi?', promptEn: 'Does positive expectancy guarantee the next trade?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece yüksek win rate ile', labelEn: 'Only with high win rate' }], correctId: 'a', explanation: 'Beklenen değer uzun dönem dağılım özetidir.', explanationEn: 'Expectancy summarizes a distribution over repeated decisions.' },
    { prompt: 'Küçük örneklem expectancy tahminini etkiler mi?', promptEn: 'Can a small sample distort expectancy estimates?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece kriptoda', labelEn: 'Only in crypto' }], correctId: 'a', explanation: 'Az gözlem tahmini oynak yapabilir.', explanationEn: 'Few observations can make the estimate unstable.' },
  ], sources: [ALGO_QUANT_SOURCES.methodology],
});

const winratePayoff = createFoundationLesson({
  id: 'lesson.quant.winrate-payoff.001', slug: 'win-rate-payoff-dengesi', conceptKey: 'quant.winrate_payoff', skillId: 'skill.algo-quant', competencyId: 'competency.winrate-payoff.foundation',
  title: 'Yüksek win rate neden tek başına yeterli değildir?', titleEn: 'Why is a high win rate not enough?',
  objective: 'Win rate ile ortalama kazanç/kayıp büyüklüğünün neden birlikte okunması gerektiğini öğren.', objectiveEn: 'Distinguish why hit rate and win/loss magnitude must be evaluated together.', minutes: 5,
  hook: 'Yüzde 80 kazanan bir sistem yine de para kaybedebilir mi?', hookEn: 'Can a system that wins 80% of the time still lose money?',
  explanation: 'Win rate yalnız kaç işlemin kazandığını söyler; kazanç ve kayıpların büyüklüğünü söylemez. Çok sayıda küçük kazanç, az sayıda büyük kayıpla silinebilir. Tersi de mümkündür: daha düşük win rate, daha büyük ortalama kazançlarla yine pozitif olabilir.', explanationEn: 'Win rate tells how often trades win, not how much they win or lose. Small gains combined with rare but very large losses can overwhelm a high hit rate. The reverse can also be true: a lower win rate can coexist with positive expectancy when average wins are larger.',
  proExplanation: 'Payoff distribution can be skewed and tail-sensitive. Average payoff, median payoff, tail losses, and serial dependence can all matter beyond a simple hit-rate statistic.', proExplanationEn: 'Payoff distributions can be skewed and tail-sensitive. Average payoff, median payoff, tail losses, and serial dependence can matter beyond a simple hit-rate statistic.',
  misconception: 'Yüksek win rate’i otomatik olarak güçlü strateji sanma.', misconceptionEn: 'Common mistake: assuming a 70% win rate automatically means a strong strategy.',
  takeaway: 'Win rate’i ortalama kazanç ve kayıpla birlikte oku.', takeawayEn: 'Win rate alone is not a quality metric; read it with payoff.',
  prerequisiteConceptKeys: ['quant.expectancy'], relatedConceptKeys: ['risk.risk_reward', 'risk.tail_risk', 'strategy.trend_following'],
  visualAlt: 'Yüksek win rate küçük kazanç büyük kayıp ile düşük win rate büyük kazanç küçük kaybı karşılaştıran iki sistem görseli', visualAltEn: 'Two-system visual comparing high hit rate with poor payoff versus lower hit rate with stronger payoff',
  taskPrompt: 'Hangi bilgi win rate’i anlamlı hale getirir?', taskPromptEn: 'What makes win rate meaningful?',
  taskChoices: [{ id: 'payoff', label: 'Ortalama kazanç ve ortalama kayıp büyüklüğü', labelEn: 'Average win and average loss size' }, { id: 'color', label: 'Grafik rengi', labelEn: 'Chart color' }, { id: 'count', label: 'Sadece kazanan işlem sayısı', labelEn: 'Only the count of winning trades' }], taskCorrectIds: ['payoff'],
  questions: [
    { prompt: '%80 win rate her zaman kârlı mıdır?', promptEn: 'Is an 80% win rate always profitable?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece hissede', labelEn: 'Only in equities' }], correctId: 'a', explanation: 'Kayıplar çok büyük olabilir.', explanationEn: 'Losses may be much larger.' },
    { prompt: 'Düşük win rate pozitif expectancy ile birlikte olabilir mi?', promptEn: 'Can a low win rate coexist with positive expectancy?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız %50 üzerinde', labelEn: 'Only above 50%' }], correctId: 'a', explanation: 'Ortalama kazançlar kayıplardan yeterince büyük olabilir.', explanationEn: 'Average wins can be sufficiently larger than losses.' },
    { prompt: 'Tail loss neden önemlidir?', promptEn: 'Why do tail losses matter?', choices: [{ id: 'a', label: 'Seyrek büyük kayıp çok sayıda küçük kazancı silebilir', labelEn: 'A rare large loss can erase many small wins' }, { id: 'b', label: 'Win rate’i otomatik artırır', labelEn: 'It automatically raises win rate' }, { id: 'c', label: 'Önemsizdir', labelEn: 'It does not matter' }], correctId: 'a', explanation: 'Dağılımın uçları ekonomik sonucu belirleyebilir.', explanationEn: 'Distribution tails can dominate economic outcomes.' },
  ], sources: [ALGO_QUANT_SOURCES.methodology],
});

const backtest = createFoundationLesson({
  id: 'lesson.quant.backtest.001', slug: 'backtest-ne-soyler', conceptKey: 'quant.backtest', skillId: 'skill.algo-quant', competencyId: 'competency.backtest.foundation',
  title: 'Backtest ne söyler, neyi kanıtlamaz?', titleEn: 'What does a backtest tell you—and what does it not prove?',
  objective: 'Backtestin neyi test ettiğini ve neden gelecek garantisi vermediğini öğren.', objectiveEn: 'Explain a backtest as a historical simulation of rules and distinguish historical fit from future proof.', minutes: 5,
  hook: 'Geçmişte çok iyi görünen bir sistem neden gerçek piyasada başarısız olabilir?', hookEn: 'Why can a system that looks excellent in history fail in live markets?',
  explanation: 'Backtest, önceden tanımlanmış kurallar geçmişte uygulansaydı ne olabileceğini simüle eder. Araştırma için faydalıdır ama veri kalitesi, işlem maliyetleri, parametre seçimi ve yanlışlıkla geleceğe ait bilgi kullanılması sonucu olduğundan iyi gösterebilir.', explanationEn: 'A backtest simulates how predefined rules might have behaved on historical data. It is useful for research, but data quality, cost assumptions, parameter choices, and accidental use of future information can easily inflate results.',
  proExplanation: 'A credible backtest requires point-in-time data, executable assumptions, corporate-action handling where relevant, explicit costs, stable rule definitions, and separation between research and validation samples.', proExplanationEn: 'A credible backtest requires point-in-time data, executable assumptions, corporate-action handling where relevant, explicit costs, stable rule definitions, and separation between research and validation samples.',
  misconception: 'Güzel equity curve’ü gelecek başarısının kanıtı sayma.', misconceptionEn: 'Common mistake: treating a smooth historical equity curve as proof the strategy will work in the future.',
  takeaway: 'Backtest geçmişi test eder; geleceği kanıtlamaz.', takeawayEn: 'A backtest is not proof; it is a controlled historical test.',
  prerequisiteConceptKeys: ['strategy.rules', 'quant.expectancy'], relatedConceptKeys: ['quant.out_of_sample', 'quant.overfitting', 'quant.lookahead_bias'],
  visualAlt: 'Geçmiş veri, kural motoru, simüle işlemler ve sonuç raporu akışını gösteren backtest diyagramı', visualAltEn: 'Backtest flow showing historical data, rule engine, simulated trades, and result report',
  taskPrompt: 'Backtest sonucunu en doğru nasıl yorumlarsın?', taskPromptEn: 'How should a backtest result be interpreted?',
  taskChoices: [{ id: 'evidence', label: 'Varsayımlara bağlı tarihsel test kanıtı olarak', labelEn: 'As historical evidence conditional on assumptions' }, { id: 'guarantee', label: 'Gelecek getirisinin garantisi olarak', labelEn: 'As a guarantee of future returns' }, { id: 'irrelevant', label: 'Hiçbir işe yaramayan sayı olarak', labelEn: 'As a useless number' }], taskCorrectIds: ['evidence'],
  questions: [
    { prompt: 'Backtest ne yapar?', promptEn: 'What does a backtest do?', choices: [{ id: 'a', label: 'Kuralları geçmiş veride simüle eder', labelEn: 'Simulates rules on historical data' }, { id: 'b', label: 'Geleceği kesin bilir', labelEn: 'Predicts the future with certainty' }, { id: 'c', label: 'Canlı emir gönderir', labelEn: 'Sends live orders' }], correctId: 'a', explanation: 'Backtest tarihsel simülasyondur.', explanationEn: 'A backtest is a historical simulation.' },
    { prompt: 'Güzel backtest gelecek garantisi midir?', promptEn: 'Is a strong backtest a future guarantee?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece uzun veriyle', labelEn: 'Only with long data' }], correctId: 'a', explanation: 'Rejim ve varsayımlar değişebilir.', explanationEn: 'Regimes and assumptions can change.' },
    { prompt: 'Backtestte maliyetler önemli midir?', promptEn: 'Do costs matter in a backtest?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız kriptoda', labelEn: 'Only in crypto' }], correctId: 'a', explanation: 'Brüt sonuç ile uygulanabilir net sonuç farklı olabilir.', explanationEn: 'Gross and implementable net outcomes can differ.' },
  ], sources: [ALGO_QUANT_SOURCES.validation],
});

const outOfSample = createFoundationLesson({
  id: 'lesson.quant.out-of-sample.001', slug: 'orneklem-ve-out-of-sample', conceptKey: 'quant.out_of_sample', skillId: 'skill.algo-quant', competencyId: 'competency.out-of-sample.foundation',
  title: 'Neden bütün veriyi aynı amaçla kullanmamalısın?', titleEn: 'Why should you not use all data for the same purpose?',
  objective: 'Kuralı geliştirdiğin veri ile doğruladığın veriyi neden ayırman gerektiğini öğren.', objectiveEn: 'Explain why research samples should be separated from more independent validation samples.', minutes: 5,
  hook: 'Kuralları aynı veri üzerinde seçip yine aynı veriyle test edersen gerçekten test etmiş olur musun?', hookEn: 'If you choose rules on a dataset and then test on the same data, did you truly test them?',
  explanation: 'Aynı veriyle stratejiyi tasarlayıp ayarlayıp yine aynı veriyle ölçersen sonuç gereğinden iyi görünebilir. Out-of-sample yaklaşımı, kurallar seçildikten sonra daha önce ayar için kullanılmamış bir veri bölümünde performansı kontrol eder.', explanationEn: 'If a strategy is designed, tuned, and evaluated on the same data, results can be optimistic. Out-of-sample testing evaluates the chosen rules on data that was not used for tuning.',
  proExplanation: 'Train/validation/test or rolling walk-forward structures reduce but do not eliminate selection bias. Repeated peeking at the holdout set can turn it into another training set.', proExplanationEn: 'Train/validation/test or rolling walk-forward structures reduce but do not eliminate selection bias. Repeated peeking at the holdout set can turn it into another training set.',
  misconception: 'Veriyi ikiye bölmenin bütün overfitting sorununu çözdüğünü sanma.', misconceptionEn: 'Common mistake: assuming one train/test split solves all overfitting problems.',
  takeaway: 'Kuralı geliştirdiğin veri ile doğruladığın veriyi ayır.', takeawayEn: 'Keep rule-selection data separate from validation data as much as possible.',
  prerequisiteConceptKeys: ['quant.backtest'], relatedConceptKeys: ['quant.overfitting', 'quant.data_leakage', 'quant.robustness'],
  visualAlt: 'Veriyi araştırma bölümü ve dokunulmamış out-of-sample bölümü olarak ikiye ayıran zaman çizgisi', visualAltEn: 'Timeline splitting data into a research section and untouched out-of-sample section',
  taskPrompt: 'Out-of-sample bölümün temel amacı nedir?', taskPromptEn: 'What is the main purpose of an out-of-sample segment?',
  taskChoices: [{ id: 'validation', label: 'Ayarlanmış kuralları daha bağımsız veride sınamak', labelEn: 'Test tuned rules on more independent data' }, { id: 'tune', label: 'Kuralları sürekli yeniden ayarlamak', labelEn: 'Continuously retune the rules' }, { id: 'hide', label: 'Kötü sonuçları saklamak', labelEn: 'Hide poor results' }], taskCorrectIds: ['validation'],
  questions: [
    { prompt: 'Aynı veri üzerinde hem seçim hem değerlendirme riskli midir?', promptEn: 'Is using the same data for selection and evaluation risky?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece küçük veride', labelEn: 'Only with small datasets' }], correctId: 'a', explanation: 'Sonuç aynı veriye aşırı uyabilir.', explanationEn: 'Results may be overfit to the same data.' },
    { prompt: 'Out-of-sample veri ne için kullanılır?', promptEn: 'What is out-of-sample data for?', choices: [{ id: 'a', label: 'Daha bağımsız doğrulama', labelEn: 'More independent validation' }, { id: 'b', label: 'Sadece görselleştirme', labelEn: 'Only visualization' }, { id: 'c', label: 'Canlı emir', labelEn: 'Live orders' }], correctId: 'a', explanation: 'Amaç seçimden daha bağımsız testtir.', explanationEn: 'The goal is testing more independently from selection.' },
    { prompt: 'Holdout veriye sürekli bakmak sorun olabilir mi?', promptEn: 'Can repeatedly checking holdout data become a problem?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız haftalık veride', labelEn: 'Only with weekly data' }], correctId: 'a', explanation: 'Sürekli bakış dolaylı ayar yapmaya dönüşebilir.', explanationEn: 'Repeated checking can become indirect tuning.' },
  ], sources: [ALGO_QUANT_SOURCES.validation],
});

const transactionCosts = createFoundationLesson({
  id: 'lesson.quant.transaction-costs.001', slug: 'backtestte-islem-maliyetleri', conceptKey: 'quant.transaction_costs', skillId: 'skill.algo-quant', competencyId: 'competency.transaction-costs.foundation',
  title: 'Kağıt üzerindeki avantaj maliyetten sonra kalıyor mu?', titleEn: 'Does the paper edge survive transaction costs?',
  objective: 'İşlem maliyetlerinin kağıt üzerindeki avantajı nasıl azaltabildiğini öğren.', objectiveEn: 'Explain how fees, spread, slippage, and market impact separate gross backtest performance from implementable net performance.', minutes: 5,
  hook: 'Her işlemde küçük bir avantaj varsa, çok sık işlem yapmak neden sonucu bozabilir?', hookEn: 'If each trade has a small edge, why can trading very frequently destroy it?',
  explanation: 'Backtestte brüt getiri görmek yetmez. Gerçek uygulamada komisyon, spread, slippage ve büyük emirlerde piyasa etkisi vardır. Strateji sık işlem yapıyorsa küçük maliyetler tekrar tekrar birikerek görünen avantajı silebilir.', explanationEn: 'Gross backtest return is not enough. Real implementation includes fees, bid-ask spread, slippage, and market impact for larger orders. High turnover can compound small costs until the apparent edge disappears.',
  proExplanation: 'Cost models should reflect instrument, venue, order type, liquidity, volatility, participation rate, and time period. A constant low slippage assumption can materially understate implementation risk.', proExplanationEn: 'Cost models should reflect instrument, venue, order type, liquidity, volatility, participation rate, and time period. A constant low slippage assumption can materially understate implementation risk.',
  misconception: 'Komisyon düşük diye spread ve slippage’ı yok sayma.', misconceptionEn: 'Common mistake: ignoring spread and slippage because commissions are low.',
  takeaway: 'Gerçek avantaj, işlem maliyetlerinden sonra kalandır.', takeawayEn: 'Real edge is the edge that remains after implementable costs.',
  prerequisiteConceptKeys: ['quant.backtest', 'market.execution.slippage'], relatedConceptKeys: ['strategy.costs_turnover', 'risk.liquidity', 'market.microstructure.bid_ask'],
  visualAlt: 'Brüt strateji avantajından komisyon, spread, slippage ve piyasa etkisini düşerek net avantajı gösteren katmanlı görsel', visualAltEn: 'Layered visual subtracting fees, spread, slippage, and market impact from gross strategy edge',
  taskPrompt: 'Hangi backtest daha gerçekçidir?', taskPromptEn: 'Which backtest is more realistic?',
  taskChoices: [{ id: 'net', label: 'Komisyon, spread ve makul slippage varsayımı içeren', labelEn: 'One including fees, spread, and reasonable slippage' }, { id: 'zero', label: 'Tüm işlemleri sıfır maliyetli sayan', labelEn: 'One assuming every trade is costless' }, { id: 'gross', label: 'Sadece brüt getiriyi gösteren', labelEn: 'One showing only gross return' }], taskCorrectIds: ['net'],
  questions: [
    { prompt: 'İşlem maliyeti sadece komisyondan mı oluşur?', promptEn: 'Are transaction costs only commissions?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece hissede', labelEn: 'Only in equities' }], correctId: 'a', explanation: 'Spread, slippage ve piyasa etkisi de olabilir.', explanationEn: 'Spread, slippage, and market impact can also matter.' },
    { prompt: 'Yüksek turnover maliyet etkisini artırabilir mi?', promptEn: 'Can high turnover amplify cost drag?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Maliyetle ilgisizdir', labelEn: 'It is unrelated to costs' }], correctId: 'a', explanation: 'Maliyet daha sık tekrar eder.', explanationEn: 'Costs are incurred more frequently.' },
    { prompt: 'Brüt avantaj net avantajla aynı mıdır?', promptEn: 'Is gross edge the same as net edge?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Uygulama maliyetleri fark yaratır.', explanationEn: 'Implementation costs create the difference.' },
  ], sources: [ALGO_QUANT_SOURCES.methodology, ALGO_QUANT_SOURCES.validation],
});

export const ALGO_QUANT_FOUNDATION_LESSONS = [probability, expectancy, winratePayoff, backtest, outOfSample, transactionCosts] as const;
