import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { ASSET_SCHOOL_SOURCES } from './assetSchoolSources';

const fxSessionEvent = createFoundationLesson({
  id: 'lesson.asset.fx.session-event.001', slug: 'fx-seans-ve-makro-olay-riski', conceptKey: 'asset.fx.session_event', skillId: 'skill.asset-schools', competencyId: 'competency.fx-session-event.foundation',
  title: 'FX “24 saat açık” olsa da neden her saat aynı değildir?', titleEn: 'Why are FX market conditions not the same all day?',
  objective: 'FX likiditesi, spreadi ve volatilitesinin seans örtüşmeleri, tatiller ve makro veri saatleriyle değişebileceğini açıklar.', objectiveEn: 'Explain how FX liquidity, spread, and volatility can change across session overlaps, holidays, and macro-event windows.', minutes: 5,
  hook: 'Aynı EUR/USD emri Londra-New York örtüşmesinde ve sakin Asya saatinde aynı şekilde gerçekleşir mi?', hookEn: 'Will the same EUR/USD order execute the same way during London-New York overlap and a quiet Asian session?',
  explanation: 'FX haftanın büyük bölümünde kesintisiz işlem görse de piyasa kalitesi gün boyunca sabit değildir. Büyük merkezlerin açılışları ve seans örtüşmeleri likiditeyi artırabilir; sakin saatlerde veya tatillerde spread genişleyebilir. Merkez bankası kararları ve önemli makro veriler kısa sürede volatilite ve slippage yaratabilir.', explanationEn: 'FX trades through much of the week, but market quality is not constant throughout the day. Major-center opens and session overlaps can increase liquidity; quieter hours and holidays can widen spreads. Central-bank decisions and major macro releases can rapidly increase volatility and slippage.',
  proExplanation: 'Session effects depend on the currency pair. Event windows can combine spread widening, order-book thinning, price jumps, and latency sensitivity. Weekend reopen risk also breaks the idea of perfectly continuous pricing.', proExplanationEn: 'Session effects depend on the currency pair. Event windows can combine spread widening, order-book thinning, price jumps, and latency sensitivity. Weekend reopen risk also breaks the idea of perfectly continuous pricing.',
  misconception: 'Yaygın hata: “FX 24/5 açık” ifadesini her saat aynı likidite ve aynı execution kalitesi var şeklinde yorumlamak.', misconceptionEn: 'Common mistake: interpreting “FX trades 24/5” as identical liquidity and execution quality every hour.',
  takeaway: 'FX’te saat, seans ve makro takvim execution riskinin parçasıdır.', takeawayEn: 'In FX, time of day, session, and the macro calendar are part of execution risk.',
  prerequisiteConceptKeys: ['market.forex.basics', 'asset.fx.carry_rollover'], relatedConceptKeys: ['market.sessions.basics', 'market.execution.slippage', 'economy.central_banks'],
  visualAlt: 'Asya, Londra ve New York seans şeritlerini; örtüşme ile makro veri anındaki spread/volatilite değişimini gösteren zaman çizelgesi', visualAltEn: 'Timeline showing Asia, London, and New York sessions plus spread/volatility changes during overlap and macro releases',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/asset-schools/fx-session-event-001', taskPrompt: '“24/5 açık” ifadesi neyi garanti etmez?', taskPromptEn: 'What does “open 24/5” not guarantee?',
  taskChoices: [{ id: 'quality', label: 'Her saatte aynı likidite ve execution kalitesini', labelEn: 'Identical liquidity and execution quality every hour' }, { id: 'access', label: 'Haftanın büyük bölümünde işlem erişimini', labelEn: 'Trading access through much of the week' }, { id: 'pairs', label: 'Birden fazla parite bulunmasını', labelEn: 'The existence of multiple currency pairs' }], taskCorrectIds: ['quality'],
  questions: [
    { prompt: 'FX spreadi gün içinde değişebilir mi?', promptEn: 'Can FX spreads change during the day?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Her zaman sabittir', labelEn: 'It is always fixed' }], correctId: 'a', explanation: 'Likidite ve olay koşulları değişir.', explanationEn: 'Liquidity and event conditions change.' },
    { prompt: 'Makro veri slippage riskini artırabilir mi?', promptEn: 'Can macro releases increase slippage risk?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece hissede', labelEn: 'Only in equities' }], correctId: 'a', explanation: 'Hızlı fiyatlama ve ince likidite görülebilir.', explanationEn: 'Rapid repricing and thinner liquidity can occur.' },
    { prompt: 'Seans etkisi tüm paritelerde aynı mıdır?', promptEn: 'Are session effects identical across all currency pairs?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'İlgili para merkezleri ve katılımcılar farklıdır.', explanationEn: 'Relevant financial centers and participants differ.' },
  ], sources: [ASSET_SCHOOL_SOURCES.forex],
});

const commoditySpotFutures = createFoundationLesson({
  id: 'lesson.asset.commodity.spot-futures.001', slug: 'emtiada-spot-ve-vadeli-fiyat', conceptKey: 'asset.commodity.spot_futures', skillId: 'skill.asset-schools', competencyId: 'competency.commodity-spot-futures.foundation',
  title: 'Altın/petrol fiyatı derken hangi fiyatı kastediyoruz?', titleEn: 'When we say “gold” or “oil price,” which price do we mean?',
  objective: 'Emtialarda spot, vadeli kontrat ve farklı vade fiyatlarının aynı anda farklı seviyelerde bulunabileceğini açıklar.', objectiveEn: 'Explain how commodity spot prices and futures contracts with different maturities can trade at different levels at the same time.', minutes: 5,
  hook: 'Petrol spot fiyatı 70 iken üç ay vadeli kontrat neden 73 olabilir?', hookEn: 'Why might spot oil be 70 while a three-month futures contract trades at 73?',
  explanation: 'Emtiada “fiyat” tek bir sayı olmayabilir. Fiziksel teslimata yakın spot fiyat ile gelecekte teslimi temsil eden vadeli kontrat fiyatı; finansman, depolama, sigorta, stok durumu, convenience yield ve beklentiler nedeniyle farklılaşabilir. Bu yüzden hangi kontratın veya referansın grafiğine baktığını bilmek gerekir.', explanationEn: 'A commodity does not necessarily have one single “price.” Spot price near physical delivery and futures prices for later delivery can differ because of financing, storage, insurance, inventories, convenience yield, and expectations. You need to know which contract or benchmark your chart represents.',
  proExplanation: 'Futures converge toward spot near expiry under normal delivery/arbitrage mechanics, but basis behavior varies by commodity, deliverability, storage constraints, location, grade, and market stress.', proExplanationEn: 'Futures tend to converge toward spot near expiry under normal delivery/arbitrage mechanics, but basis behavior varies by commodity, deliverability, storage constraints, location, grade, and market stress.',
  misconception: 'Yaygın hata: Haberlerde görülen spot fiyat ile yatırım aracındaki vadeli kontratın aynı anda birebir aynı olması gerektiğini düşünmek.', misconceptionEn: 'Common mistake: assuming a reported spot price and a futures-based investment exposure must match exactly at the same time.',
  takeaway: 'Emtiada önce referansı sor: spot mu, hangi vade kontratı mı, yoksa vadeli kontrat kullanan fon mu?', takeawayEn: 'For commodities, first ask the reference: spot, which futures maturity, or a fund using futures?',
  prerequisiteConceptKeys: ['market.commodities.basics', 'market.derivatives.basics'], relatedConceptKeys: ['asset.commodity.term_structure', 'asset.etf.nav_tracking', 'quant.transaction_costs'],
  visualAlt: 'Spot fiyat ve 1, 3, 6 ay vadeli kontrat fiyatlarını ayrı noktalar halinde gösteren emtia vade eğrisi başlangıç görseli', visualAltEn: 'Intro commodity curve visual showing spot and 1-, 3-, and 6-month futures as separate price points',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/asset-schools/commodity-spot-futures-001', taskPrompt: 'Emtia grafiğine bakarken ilk neyi bilmelisin?', taskPromptEn: 'What should you know first when viewing a commodity chart?',
  taskChoices: [{ id: 'reference', label: 'Spot mu, hangi vadeli kontrat mı veya hangi fon referansı mı olduğunu', labelEn: 'Whether it is spot, which futures contract, or which fund reference' }, { id: 'same', label: 'Tüm fiyatların aynı olması gerektiğini', labelEn: 'Assume all prices must be identical' }, { id: 'color', label: 'Grafik rengini', labelEn: 'The chart color' }], taskCorrectIds: ['reference'],
  questions: [
    { prompt: 'Spot ve vadeli emtia fiyatı aynı anda farklı olabilir mi?', promptEn: 'Can commodity spot and futures prices differ at the same time?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece altında', labelEn: 'Only in gold' }], correctId: 'a', explanation: 'Taşıma ve vade koşulları fiyatları ayırabilir.', explanationEn: 'Carry and maturity conditions can separate prices.' },
    { prompt: 'Farklı vadeli kontratlar farklı fiyatlanabilir mi?', promptEn: 'Can different futures maturities trade at different prices?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Her zaman eşittir', labelEn: 'They are always equal' }], correctId: 'a', explanation: 'Term structure bunu gösterir.', explanationEn: 'The term structure captures these differences.' },
    { prompt: 'Fiziksel özellikler emtia fiyatlamasını etkileyebilir mi?', promptEn: 'Can physical characteristics affect commodity pricing?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'İlgisizdir', labelEn: 'They are unrelated' }], correctId: 'a', explanation: 'Depolama, teslimat ve stok koşulları önemlidir.', explanationEn: 'Storage, delivery, and inventory conditions matter.' },
  ], sources: [ASSET_SCHOOL_SOURCES.commodities],
});

const termStructure = createFoundationLesson({
  id: 'lesson.asset.commodity.term-structure.001', slug: 'contango-backwardation-ve-roll', conceptKey: 'asset.commodity.term_structure', skillId: 'skill.asset-schools', competencyId: 'competency.commodity-term-structure.foundation',
  title: 'Contango ve backwardation yatırım sonucunu neden etkileyebilir?', titleEn: 'Why can contango and backwardation affect investment results?',
  objective: 'Vadeli fiyat eğrisinin contango/backwardation yapısını ve kontrat yenilemenin roll etkisini açıklar.', objectiveEn: 'Explain contango/backwardation in the futures curve and how rolling contracts can affect returns.', minutes: 5,
  hook: 'Petrol spot fiyatı yıl sonunda aynı kalsa bile futures kullanan bir ürün neden farklı getiri üretebilir?', hookEn: 'If oil spot price ends the year unchanged, why can a futures-based product still have a different return?',
  explanation: 'Yakın vadeli kontratlar uzak vadelilerden daha ucuzsa eğri genellikle contango, daha pahalıysa backwardation olarak adlandırılır. Süresi dolan kontrattan çıkıp yeni kontrata geçmek “roll” işlemidir. Yeni kontratın fiyat seviyesi ve eğrinin zaman içindeki değişimi, spot fiyat hareketinden ayrı bir getiri/maliyet bileşeni yaratabilir.', explanationEn: 'When near-dated contracts are cheaper than later contracts the curve is commonly called contango; when near contracts are more expensive it is backwardation. Moving from an expiring contract into a later one is a roll. The new contract’s level and evolution of the curve can create a return/cost component separate from spot-price movement.',
  proExplanation: 'Roll yield is not a guaranteed static return from curve slope; futures prices converge, the curve evolves, contract selection rules differ, and collateral/financing returns also contribute to futures-based product performance.', proExplanationEn: 'Roll yield is not a guaranteed static return from curve slope; futures prices converge, the curve evolves, contract selection rules differ, and collateral/financing returns also contribute to futures-based product performance.',
  misconception: 'Yaygın hata: Spot emtia fiyatının hareketini futures tabanlı fon getirisinin birebir aynısı sanmak.', misconceptionEn: 'Common mistake: assuming spot commodity price movement must equal the return of a futures-based fund.',
  takeaway: 'Emtia exposure’unda spot yönü + vade eğrisi + roll kuralı birlikte sonucu oluşturur.', takeawayEn: 'For commodity exposure, spot direction + futures curve + roll rule shape the result together.',
  prerequisiteConceptKeys: ['asset.commodity.spot_futures'], relatedConceptKeys: ['asset.etf.nav_tracking', 'quant.transaction_costs', 'strategy.horizon_objective'],
  visualAlt: 'Yukarı eğimli contango ve aşağı eğimli backwardation vadeli eğrilerini ve yakın kontrattan sonraki kontrata roll okunu gösteren görsel', visualAltEn: 'Visual showing upward-sloping contango and downward-sloping backwardation curves with a roll arrow from near to next contract',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/asset-schools/commodity-term-structure-001', taskPrompt: 'Futures tabanlı emtia ürününde spot dışında neyi izlemelisin?', taskPromptEn: 'What should you monitor besides spot in a futures-based commodity product?',
  taskChoices: [{ id: 'curve', label: 'Vade eğrisi ve roll metodunu', labelEn: 'The futures curve and roll methodology' }, { id: 'onlyspot', label: 'Yalnız spot grafiğini', labelEn: 'Only the spot chart' }, { id: 'earnings', label: 'Şirket EPS’ini', labelEn: 'Company EPS' }], taskCorrectIds: ['curve'],
  questions: [
    { prompt: 'Contango neyi tarif eder?', promptEn: 'What does contango describe?', choices: [{ id: 'a', label: 'Uzak vadelerin yakın vadelerden daha yüksek fiyatlı olduğu eğriyi', labelEn: 'A curve where later maturities are priced above nearer ones' }, { id: 'b', label: 'Hisse splitini', labelEn: 'A stock split' }, { id: 'c', label: 'FX rolloverını', labelEn: 'FX rollover' }], correctId: 'a', explanation: 'Bu vadeli fiyatların vade yapısıdır.', explanationEn: 'It is a futures term-structure shape.' },
    { prompt: 'Roll işlemi ne yapar?', promptEn: 'What does rolling a futures position do?', choices: [{ id: 'a', label: 'Süresi dolan kontrattan daha ileri vadeye geçer', labelEn: 'Moves from an expiring contract to a later one' }, { id: 'b', label: 'Şirket hissesi böler', labelEn: 'Splits company shares' }, { id: 'c', label: 'Spot fiyatı sabitler', labelEn: 'Fixes spot price' }], correctId: 'a', explanation: 'Vadeli exposure devam ettirilir.', explanationEn: 'It maintains futures exposure across expiries.' },
    { prompt: 'Spot getiri ile futures ürün getirisi farklı olabilir mi?', promptEn: 'Can spot return and a futures-product return differ?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Her zaman aynıdır', labelEn: 'They are always identical' }], correctId: 'a', explanation: 'Roll, collateral, fee ve eğri etkileri vardır.', explanationEn: 'Roll, collateral, fees, and curve effects can matter.' },
  ], sources: [ASSET_SCHOOL_SOURCES.commodities],
});

const perpetualFunding = createFoundationLesson({
  id: 'lesson.asset.crypto.perpetual-funding.001', slug: 'kripto-perpetual-ve-funding', conceptKey: 'asset.crypto.perpetual_funding', skillId: 'skill.asset-schools', competencyId: 'competency.crypto-perpetual-funding.foundation',
  title: 'Perpetual kontrat spot fiyat değildir: funding ne yapar?', titleEn: 'A perpetual contract is not spot: what does funding do?',
  objective: 'Kripto perpetual sözleşmenin vadesiz türev olduğunu ve funding mekanizmasının long/short taraflar arasında dönemsel ödeme yaratabileceğini açıklar.', objectiveEn: 'Explain that a crypto perpetual is a non-expiring derivative and that funding can create periodic payments between long and short sides.', minutes: 5,
  hook: 'BTC spot fiyatı değişmese bile perpetual pozisyonun neden para kazanıp kaybedebilir?', hookEn: 'Why can a BTC perpetual position gain or lose money even if spot barely moves?',
  explanation: 'Perpetual futures, vade tarihi olmayan türev kontratlardır. Fiyatın spot piyasadan çok uzaklaşmasını sınırlamaya yardımcı olmak için birçok venue funding mekanizması kullanır. Funding oranına göre belirli zamanlarda long taraf short’a veya short taraf long’a ödeme yapabilir. Bu nedenle perpetual getirisi yalnız fiyat yönünden oluşmaz.', explanationEn: 'Perpetual futures are derivatives without a fixed expiry. Many venues use funding to help keep the contract price near spot. Depending on the funding rate, longs may periodically pay shorts or vice versa. Perpetual P&L therefore includes more than price direction alone.',
  proExplanation: 'Funding formulas, intervals, caps, index construction, mark price, liquidation rules, collateral type, and venue-specific risk differ. Funding is not a risk-free yield and can change sign quickly.', proExplanationEn: 'Funding formulas, intervals, caps, index construction, mark price, liquidation rules, collateral type, and venue-specific risk differ. Funding is not a risk-free yield and can change sign quickly.',
  misconception: 'Yaygın hata: Perpetual fiyat grafiğini spotla aynı ürün sanmak veya yüksek funding’i garanti getiri gibi görmek.', misconceptionEn: 'Common mistake: treating a perpetual chart as the same product as spot or viewing high funding as guaranteed yield.',
  takeaway: 'Perpetual = fiyat yönü + funding + kaldıraç/liquidation + venue kuralları.', takeawayEn: 'Perpetual exposure = price direction + funding + leverage/liquidation + venue rules.',
  prerequisiteConceptKeys: ['market.crypto.basics', 'market.derivatives.basics'], relatedConceptKeys: ['risk.leverage', 'asset.crypto.venue_custody', 'quant.transaction_costs'],
  visualAlt: 'Spot fiyat çizgisi ile perpetual fiyat çizgisini ve long-short arasında dönemsel funding ödeme oklarını gösteren kripto türev görseli', visualAltEn: 'Crypto derivative visual showing spot versus perpetual price plus periodic funding arrows between longs and shorts',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/asset-schools/crypto-perpetual-funding-001', taskPrompt: 'Perpetual pozisyon sonucunda spot yönüne ek hangi bileşen olabilir?', taskPromptEn: 'What component can affect a perpetual position besides spot direction?',
  taskChoices: [{ id: 'funding', label: 'Funding ödemesi', labelEn: 'Funding payments' }, { id: 'dividend', label: 'Hisse temettüsü', labelEn: 'Equity dividend' }, { id: 'split', label: 'Stock split', labelEn: 'Stock split' }], taskCorrectIds: ['funding'],
  questions: [
    { prompt: 'Perpetual kontratın sabit vadesi var mıdır?', promptEn: 'Does a perpetual contract have a fixed expiry?', choices: [{ id: 'a', label: 'Genellikle hayır', labelEn: 'Generally no' }, { id: 'b', label: 'Her zaman 3 ay', labelEn: 'Always three months' }, { id: 'c', label: 'Her zaman 1 yıl', labelEn: 'Always one year' }], correctId: 'a', explanation: 'Perpetual adı vadesiz yapıyı ifade eder.', explanationEn: '“Perpetual” refers to the non-expiring structure.' },
    { prompt: 'Funding oranı değişebilir mi?', promptEn: 'Can funding rates change?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sabit getiridir', labelEn: 'It is fixed income' }], correctId: 'a', explanation: 'Piyasa ve venue koşullarına göre değişebilir.', explanationEn: 'It can change with market and venue conditions.' },
    { prompt: 'Funding risk-free getiri midir?', promptEn: 'Is funding a risk-free yield?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Fiyat, kaldıraç, liquidation ve venue riskleri devam eder.', explanationEn: 'Price, leverage, liquidation, and venue risks remain.' },
  ], sources: [ASSET_SCHOOL_SOURCES.crypto],
});

const venueCustody = createFoundationLesson({
  id: 'lesson.asset.crypto.venue-custody.001', slug: 'kripto-venue-custody-ve-karsi-taraf-riski', conceptKey: 'asset.crypto.venue_custody', skillId: 'skill.asset-schools', competencyId: 'competency.crypto-venue-custody.foundation',
  title: 'Kriptoda doğru fiyat yetmez: venue ve custody riski nedir?', titleEn: 'In crypto, price analysis is not enough: what are venue and custody risks?',
  objective: 'Kripto exposure’da işlem platformu, saklama, karşı taraf, stablecoin/teminat ve operasyon risklerini fiyat riskinden ayırır.', objectiveEn: 'Separate trading-venue, custody, counterparty, collateral/stablecoin, and operational risks from price risk in crypto exposure.', minutes: 5,
  hook: 'BTC analizinde haklı olup yine de platform problemi yüzünden zarar edebilir misin?', hookEn: 'Can you be right about BTC direction and still lose because of a platform problem?',
  explanation: 'Kriptoda exposure çoğu zaman merkezi borsa, saklama sağlayıcısı, cüzdan veya akıllı kontrat gibi ek altyapılara dayanır. Fiyat doğru yönde gitse bile para çekme durması, karşı taraf sorunu, hack, yanlış ağ/transfer, teminat problemi veya stablecoin riski sonucu etkileyebilir. “Asset risk” ile “nerede ve nasıl tuttuğun” riski ayrıdır.', explanationEn: 'Crypto exposure often depends on extra infrastructure such as centralized exchanges, custodians, wallets, or smart contracts. Even if price moves in the expected direction, withdrawal freezes, counterparty failures, hacks, transfer mistakes, collateral problems, or stablecoin risk can affect outcomes. Asset risk and the risk of where/how it is held are distinct.',
  proExplanation: 'Segregation of assets, bankruptcy treatment, proof-of-reserves limits, hot/cold wallet design, key management, chain finality, smart-contract risk, collateral quality, jurisdiction, and operational controls all affect custody/venue exposure.', proExplanationEn: 'Asset segregation, bankruptcy treatment, proof-of-reserves limits, hot/cold wallet design, key management, chain finality, smart-contract risk, collateral quality, jurisdiction, and operational controls all affect custody/venue exposure.',
  misconception: 'Yaygın hata: “BTC aynı BTC” diyerek tüm borsa, saklama ve teminat yollarının aynı riske sahip olduğunu varsaymak.', misconceptionEn: 'Common mistake: assuming all venues, custody methods, and collateral paths have the same risk because “BTC is BTC.”',
  takeaway: 'Kriptoda **neye** sahip olduğun kadar **nerede, nasıl ve hangi karşı tarafla** tuttuğun da önemlidir.', takeawayEn: 'In crypto, **where, how, and with whom** you hold exposure matters alongside what you hold.',
  prerequisiteConceptKeys: ['market.crypto.basics'], relatedConceptKeys: ['asset.crypto.perpetual_funding', 'risk.liquidity', 'risk.tail_risk'],
  visualAlt: 'Kripto varlığı merkezde; çevresinde exchange, custodian, wallet, collateral ve network risk katmanlarını ayrı halkalarla gösteren görsel', visualAltEn: 'Visual with a crypto asset at center surrounded by separate exchange, custodian, wallet, collateral, and network risk layers',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/asset-schools/crypto-venue-custody-001', taskPrompt: 'Hangisi fiyat riskinden ayrı bir kripto riski örneğidir?', taskPromptEn: 'Which is a crypto risk separate from price direction?',
  taskChoices: [{ id: 'custody', label: 'Venue/custody karşı tarafının varlıklara erişimi kısıtlaması', labelEn: 'A venue/custody counterparty restricting access to assets' }, { id: 'candle', label: 'Mumun yeşil olması', labelEn: 'A green candle' }, { id: 'trend', label: 'Trend çizgisi', labelEn: 'A trendline' }], taskCorrectIds: ['custody'],
  questions: [
    { prompt: 'Fiyat tahmini doğru olsa bile venue riski zarar yaratabilir mi?', promptEn: 'Can venue risk create losses even when the price thesis is right?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'İmkânsızdır', labelEn: 'Impossible' }], correctId: 'a', explanation: 'Erişim ve karşı taraf sorunu fiyat yönünden bağımsızdır.', explanationEn: 'Access and counterparty problems are separate from direction.' },
    { prompt: 'Custody yöntemi risk profilini değiştirir mi?', promptEn: 'Can custody method change the risk profile?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Her yöntem aynıdır', labelEn: 'Every method is identical' }], correctId: 'a', explanation: 'Anahtar, karşı taraf ve operasyon sorumluluğu değişir.', explanationEn: 'Key, counterparty, and operational responsibilities differ.' },
    { prompt: 'Proof-of-reserves tüm yükümlülükleri tek başına kanıtlar mı?', promptEn: 'Does proof-of-reserves alone prove all liabilities and safety?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Rezerv görünümü tüm bilanço/operasyon riskini kapsamayabilir.', explanationEn: 'Reserve visibility may not cover all liabilities or operational risk.' },
  ], sources: [ASSET_SCHOOL_SOURCES.crypto],
});

const onchainLimits = createFoundationLesson({
  id: 'lesson.asset.crypto.onchain-limits.001', slug: 'onchain-veri-ne-soyler-ne-soylemez', conceptKey: 'asset.crypto.onchain_limits', skillId: 'skill.asset-schools', competencyId: 'competency.crypto-onchain-limits.foundation',
  title: 'On-chain veri ne söyler, neyi söylemez?', titleEn: 'What does on-chain data tell you—and what does it not tell you?',
  objective: 'Blockchain üzerindeki işlemlerin gözlenebilirliğini adres sahipliği, borsa içi/off-chain faaliyet ve niyet belirsizliğinden ayırır.', objectiveEn: 'Distinguish observable blockchain activity from uncertainty about address ownership, off-chain activity, and intent.', minutes: 5,
  hook: 'Bir adresten borsaya büyük transfer gördüğünde bunun kesin satış hazırlığı olduğunu söyleyebilir misin?', hookEn: 'If you see a large transfer to an exchange, can you say with certainty that it is preparation to sell?',
  explanation: 'On-chain veri, halka açık blockchain üzerindeki transfer, bakiye ve sözleşme etkileşimlerini gözlemlemeye yardım eder. Fakat bir adresin gerçek sahibi, transferin ekonomik amacı, borsa içindeki sonraki işlem, custodian’ın iç muhasebesi veya off-chain türev pozisyonları her zaman doğrudan görülemez. Gözlem ile yorum ayrılmalıdır.', explanationEn: 'On-chain data helps observe transfers, balances, and contract interactions on public blockchains. But the real owner of an address, economic purpose of a transfer, subsequent trades inside an exchange, custodian internal accounting, or off-chain derivatives positions may not be directly visible. Observation must be separated from interpretation.',
  proExplanation: 'Entity clustering, exchange-label databases, bridge activity, UTXO/account-model differences, internal transactions, mixers, smart-contract abstractions, chain reorganizations, and data-provider heuristics can affect attribution quality.', proExplanationEn: 'Entity clustering, exchange-label databases, bridge activity, UTXO/account-model differences, internal transactions, mixers, smart-contract abstractions, chain reorganizations, and data-provider heuristics can affect attribution quality.',
  misconception: 'Yaygın hata: Büyük transferi otomatik “whale satıyor/alıyor” diye yorumlamak veya adres etiketini kesin kimlik bilgisi saymak.', misconceptionEn: 'Common mistake: automatically interpreting a large transfer as “a whale is selling/buying” or treating an address label as certain identity.',
  takeaway: 'On-chain güçlü bir gözlem katmanıdır; sahiplik, niyet ve off-chain aktivite için belirsizlik payını koru.', takeawayEn: 'On-chain data is a powerful observation layer; preserve uncertainty around ownership, intent, and off-chain activity.',
  prerequisiteConceptKeys: ['market.crypto.basics', 'evidence.data_quality'], relatedConceptKeys: ['onchain.basics', 'behavior.confirmation_bias', 'asset.crypto.venue_custody'],
  visualAlt: 'Blockchain üzerinde görünen transferi net, adres sahibi/niyet/off-chain işlem katmanlarını soru işaretli olarak ayıran kanıt diyagramı', visualAltEn: 'Evidence diagram showing an observable blockchain transfer clearly while marking ownership, intent, and off-chain activity as uncertain',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/asset-schools/crypto-onchain-limits-001', taskPrompt: 'Borsaya büyük transfer gördüğünde en güvenli ifade hangisidir?', taskPromptEn: 'What is the safest statement after seeing a large transfer to an exchange?',
  taskChoices: [{ id: 'observed', label: 'Borsa olarak etiketlenen adrese transfer gözlendi; ekonomik niyet kesin değil', labelEn: 'A transfer to an exchange-labeled address was observed; economic intent is uncertain' }, { id: 'sell', label: 'Kesin satış geliyor', labelEn: 'A sale is definitely coming' }, { id: 'owner', label: 'Adres sahibinin kimliği kesin biliniyor', labelEn: 'The address owner is certainly known' }], taskCorrectIds: ['observed'],
  questions: [
    { prompt: 'On-chain transfer niyeti doğrudan gösterir mi?', promptEn: 'Does an on-chain transfer directly reveal intent?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Transfer gözlenir, ekonomik amaç ayrıca yorumlanır.', explanationEn: 'The transfer is observed; its economic purpose is inferred separately.' },
    { prompt: 'Borsa içi işlemler her zaman chain üzerinde görünür mü?', promptEn: 'Are internal exchange trades always visible on-chain?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her emir görünür', labelEn: 'Every order is visible' }], correctId: 'a', explanation: 'Merkezi venue iç muhasebesi off-chain olabilir.', explanationEn: 'Centralized-venue internal accounting can be off-chain.' },
    { prompt: 'Adres etiketleri hata içerebilir mi?', promptEn: 'Can address labels contain errors?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Kimlik garantisidir', labelEn: 'They guarantee identity' }], correctId: 'a', explanation: 'Attribution çoğu zaman heuristic ve veri sağlayıcı bilgisine dayanır.', explanationEn: 'Attribution often relies on heuristics and provider knowledge.' },
  ], sources: [ASSET_SCHOOL_SOURCES.crypto, ASSET_SCHOOL_SOURCES.onchain],
});

export const ASSET_SCHOOL_EXPANSION_LESSONS = [fxSessionEvent, commoditySpotFutures, termStructure, perpetualFunding, venueCustody, onchainLimits] as const;
