import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { ASSET_SCHOOL_SOURCES } from './assetSchoolSources';

const crossMarket = createFoundationLesson({
  id: 'lesson.asset.cross-market.001', slug: 'ayni-grafik-farkli-piyasa', conceptKey: 'asset.cross_market.plumbing', skillId: 'skill.asset-schools', competencyId: 'competency.cross-market.foundation',
  title: 'Aynı grafik, farklı piyasa: neden aynı şey değildir?', titleEn: 'Same chart, different market: why are they not the same?',
  objective: 'Aynı grafik şeklinin farklı piyasalarda neden farklı risk anlamına gelebileceğini öğren.', objectiveEn: 'Explain how equities, ETFs, FX, commodities, and crypto differ in trading hours, price formation, carrying costs, counterparty exposure, and product structure.', minutes: 5,
  hook: 'İki grafikte aynı breakout görünüyorsa, hisse ile perpetual futures için risk de aynı mıdır?', hookEn: 'If two charts show the same breakout, is the risk the same for an equity and a perpetual future?',
  explanation: 'Grafik aynı görünebilir ama ürünün altında çalışan mekanizma farklıdır. Hissede şirket haberi ve gap, ETF’de fon yapısı, FX’te iki para ve carry, emtiada vadeli kontrat, kriptoda ise 24/7 işlem ve saklama gibi ek riskler vardır. Grafiğe bakarken ürünü de bilmek gerekir.', explanationEn: 'Chart shapes can look similar while the market mechanism underneath differs. Equities carry company-event and session-gap risk; ETFs add fund structure and tracking; FX involves two currencies and carry; commodities add futures-contract structure; crypto adds venue, custody, and 24/7-market risks. Asset literacy adds this product layer to chart reading.',
  proExplanation: 'Execution venue, settlement, financing, benchmark construction, contract expiry, corporate actions, custody, and market-hour conventions can alter realized returns even when the directional price thesis looks similar.', proExplanationEn: 'Execution venue, settlement, financing, benchmark construction, contract expiry, corporate actions, custody, and market-hour conventions can alter realized returns even when the directional price thesis looks similar.',
  misconception: 'Grafik benzer diye bütün varlıklarda aynı risk varsayımını kullanma.', misconceptionEn: 'Common mistake: using identical risk and implementation assumptions across asset classes because the charts look similar.',
  takeaway: 'Grafiği ürün yapısından ayrı okuma.', takeawayEn: 'Charts can be a shared language; product structure and market plumbing are the second language of risk.',
  prerequisiteConceptKeys: ['market.basics.instruments'], relatedConceptKeys: ['market.venues.exchanges', 'risk.liquidity', 'market.execution.slippage'],
  visualAlt: 'Aynı fiyat grafiğinin altında hisse, ETF, FX, emtia ve kripto için farklı piyasa mekanizması katmanlarını gösteren karşılaştırma', visualAltEn: 'Comparison showing the same price chart above different market-mechanics layers for equities, ETFs, FX, commodities, and crypto',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/asset-schools/cross-market-001', taskPrompt: 'Aynı teknik görünümde neden varlık türünü ayrıca bilmelisin?', taskPromptEn: 'Why should you still know the asset type when the technical setup looks the same?',
  taskChoices: [{ id: 'mechanics', label: 'İşlem saatleri, taşıma, kontrat ve karşı taraf riskleri farklı olabilir', labelEn: 'Hours, carry, contract, and counterparty risks can differ' }, { id: 'same', label: 'Grafik aynıysa tüm riskler aynıdır', labelEn: 'If the chart is the same, all risks are the same' }, { id: 'color', label: 'Sadece grafik rengi değişir', labelEn: 'Only the chart color changes' }], taskCorrectIds: ['mechanics'],
  questions: [
    { prompt: 'Aynı grafik formasyonu farklı varlıklarda aynı uygulama riskini garanti eder mi?', promptEn: 'Does the same chart pattern guarantee the same implementation risk across assets?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Ürün ve piyasa yapısı farklıdır.', explanationEn: 'Product and market structures differ.' },
    { prompt: 'Piyasa plumbing’i neyi kapsayabilir?', promptEn: 'What can market plumbing include?', choices: [{ id: 'a', label: 'Venue, settlement, finansman ve ürün yapısını', labelEn: 'Venue, settlement, financing, and product structure' }, { id: 'b', label: 'Sadece mum rengini', labelEn: 'Only candle color' }, { id: 'c', label: 'Sadece trendi', labelEn: 'Only trend' }], correctId: 'a', explanation: 'Fiyatın nasıl işlem gördüğünü ve taşındığını belirler.', explanationEn: 'It shapes how exposure trades and is carried.' },
    { prompt: 'Varlık okuryazarlığı teknik analizi tamamen değiştirir mi?', promptEn: 'Does asset literacy replace technical analysis entirely?', choices: [{ id: 'a', label: 'Hayır, ürün bağlamı ekler', labelEn: 'No, it adds product context' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Grafiği gereksiz yapar', labelEn: 'It makes charts unnecessary' }], correctId: 'a', explanation: 'Amaç ortak analize varlığa özgü risk katmanı eklemektir.', explanationEn: 'The goal is to add asset-specific risk to shared analysis.' },
  ], sources: [ASSET_SCHOOL_SOURCES.crossMarket],
});

const corporateActions = createFoundationLesson({
  id: 'lesson.asset.equity.corporate-actions.001', slug: 'hisselerde-corporate-actions', conceptKey: 'asset.equity.corporate_actions', skillId: 'skill.asset-schools', competencyId: 'competency.equity-corporate-actions.foundation',
  title: 'Hissede fiyat neden şirket olayıyla “mekanik” değişebilir?', titleEn: 'Why can an equity price change mechanically after a corporate action?',
  objective: 'Şirket işlemlerinin hisse fiyatını ekonomik bozulma olmadan neden mekanik değiştirebildiğini öğren.', objectiveEn: 'Explain how dividends, splits, reverse splits, capital actions, and similar corporate actions can affect price series and per-share metrics.', minutes: 5,
  hook: 'Bir hisse bir gecede fiyatının yarısına düştüyse şirket değeri de mutlaka yarıya mı indi?', hookEn: 'If a stock price halves overnight, did the company necessarily lose half its value?',
  explanation: 'Split, temettü ve yeni hisse ihracı gibi şirket işlemleri fiyat serisini mekanik olarak değiştirebilir. Örneğin split fiyatı bölebilir, temettü günü fiyat ayarlanabilir, yeni hisse ihracı pay başına değeri seyreltebilir. Ham fiyat hareketini şirket değerindeki gerçek değişimden ayırmak gerekir.', explanationEn: 'Corporate actions change share structure or distributions to investors. A split can mechanically divide the share price, a dividend can create an ex-date adjustment, and new share issuance can dilute per-share ownership. Raw price movement must therefore be separated from economic-value change.',
  proExplanation: 'Adjusted versus unadjusted prices, split factors, dividends, spin-offs, rights issues, buybacks, mergers, and share-count changes matter for historical returns, indicators, backtests, and per-share fundamental metrics.', proExplanationEn: 'Adjusted versus unadjusted prices, split factors, dividends, spin-offs, rights issues, buybacks, mergers, and share-count changes matter for historical returns, indicators, backtests, and per-share fundamental metrics.',
  misconception: 'Split veya temettü sonrası mekanik fiyat değişimini doğrudan kötü haber sanma.', misconceptionEn: 'Common mistake: treating a post-split price drop as an economic collapse or an ex-dividend adjustment as a standalone negative signal.',
  takeaway: 'Hisse fiyatı değiştiğinde önce şirket işlemi var mı diye kontrol et.', takeawayEn: 'For equities, add a corporate-action check before interpreting why price changed.',
  prerequisiteConceptKeys: ['market.basics.instruments', 'fundamental.per_share'], relatedConceptKeys: ['evidence.data_quality', 'quant.backtest', 'fundamental.analysis_limits'],
  visualAlt: 'Split, temettü ve yeni hisse ihracının ham fiyat, düzeltilmiş fiyat ve hisse sayısı üzerindeki farklı etkilerini gösteren görsel', visualAltEn: 'Visual comparing how splits, dividends, and share issuance affect raw price, adjusted price, and share count',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/asset-schools/equity-corporate-actions-001', taskPrompt: 'Bir hissenin fiyatı split nedeniyle yarıya düşerse ilk neyi kontrol edersin?', taskPromptEn: 'If a stock price halves due to a split, what should you check first?',
  taskChoices: [{ id: 'action', label: 'Corporate action ve adjusted price bilgisini', labelEn: 'Corporate-action and adjusted-price information' }, { id: 'crash', label: 'Şirket değerinin kesin yarıya indiğini', labelEn: 'Assume company value certainly halved' }, { id: 'sell', label: 'Otomatik satış sinyalini', labelEn: 'Treat it as an automatic sell signal' }], taskCorrectIds: ['action'],
  questions: [
    { prompt: 'Split şirket değerini otomatik yarıya indirir mi?', promptEn: 'Does a split automatically halve company value?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Pay sayısı ve birim fiyat mekanik olarak değişebilir.', explanationEn: 'Share count and unit price can change mechanically.' },
    { prompt: 'Adjusted fiyat backtest için önemli olabilir mi?', promptEn: 'Can adjusted prices matter for backtests?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece kriptoda', labelEn: 'Only in crypto' }], correctId: 'a', explanation: 'Corporate action etkileri tarihsel seriyi bozabilir.', explanationEn: 'Corporate actions can distort historical series.' },
    { prompt: 'Yeni hisse ihracı neyi etkileyebilir?', promptEn: 'What can new share issuance affect?', choices: [{ id: 'a', label: 'Hisse başına sahiplik ve metrikleri', labelEn: 'Per-share ownership and metrics' }, { id: 'b', label: 'Sadece mum rengini', labelEn: 'Only candle color' }, { id: 'c', label: 'FX carry’yi', labelEn: 'FX carry' }], correctId: 'a', explanation: 'Pay sayısı değiştiğinde hisse başına değerler etkilenebilir.', explanationEn: 'Per-share values can change when share count changes.' },
  ], sources: [ASSET_SCHOOL_SOURCES.equities],
});

const earningsGaps = createFoundationLesson({
  id: 'lesson.asset.equity.earnings-gaps.001', slug: 'hisselerde-earnings-gap-riski', conceptKey: 'asset.equity.earnings_gaps', skillId: 'skill.asset-schools', competencyId: 'competency.equity-earnings-gap.foundation',
  title: 'Bilanço açıklaması stop riskini neden değiştirebilir?', titleEn: 'Why can an earnings release change stop risk?',
  objective: 'Şirket haberlarının gap oluşturup stop fiyatını neden garanti olmaktan çıkarabildiğini öğren.', objectiveEn: 'Explain how company events can create after-hours repricing, gaps, and execution risk in equities.', minutes: 5,
  hook: 'Stop emrin 100’deyse hisse bilanço sonrası 90’dan açılırsa 100’den çıkabilir misin?', hookEn: 'If your stop is at 100 but the stock opens at 90 after earnings, can you necessarily exit at 100?',
  explanation: 'Bilanço, kâr uyarısı veya önemli şirket haberi seans dışında fiyat beklentisini değiştirebilir. Hisse ertesi gün gap ile açılırsa stop emri tetiklense bile seçtiğin seviyeden işlem görmeyebilir.', explanationEn: 'Equities are sensitive to company-specific events. Earnings, guidance changes, regulatory decisions, or major company news can reprice expectations outside regular hours. If the next session opens with a gap, a stop may trigger but fill far from the expected level.',
  proExplanation: 'Event risk interacts with extended-hours liquidity, auction mechanics, halt rules, options-implied moves, and position sizing. A continuous-price assumption is weakest exactly when discrete information arrives.', proExplanationEn: 'Event risk interacts with extended-hours liquidity, auction mechanics, halt rules, options-implied moves, and position sizing. A continuous-price assumption is weakest exactly when discrete information arrives.',
  misconception: 'Stop seviyesini maksimum kayıp garantisi sanma; gap riskini hesaba kat.', misconceptionEn: 'Common mistake: treating a stop level as a maximum-loss guarantee and ignoring earnings/event-gap risk.',
  takeaway: 'Hissede event takvimi, gap ve pozisyon büyüklüğünü birlikte düşün.', takeawayEn: 'In equities, the event calendar, gap risk, and position size belong to the same risk decision.',
  prerequisiteConceptKeys: ['risk.stop_orders', 'asset.equity.corporate_actions'], relatedConceptKeys: ['market.sessions.basics', 'market.execution.slippage', 'risk.position_sizing'],
  visualAlt: 'Kapanış 100, stop 97 ve bilanço sonrası 90 açılış senaryosuyla gap ve gerçekleşme farkını gösteren fiyat çizelgesi', visualAltEn: 'Price timeline showing close at 100, stop at 97, and a post-earnings open at 90 to illustrate gap and fill risk',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/asset-schools/equity-earnings-gap-001', taskPrompt: 'Bilanço öncesi risk değerlendirmesinde hangisi önemlidir?', taskPromptEn: 'What matters in risk assessment before earnings?',
  taskChoices: [{ id: 'gap', label: 'Seans dışı gap ve stop gerçekleşme riski', labelEn: 'After-hours gap and stop execution risk' }, { id: 'guarantee', label: 'Stop fiyatının maksimum kaybı garanti etmesi', labelEn: 'A stop price guarantees the maximum loss' }, { id: 'none', label: 'Şirket olaylarının fiyatı etkileyememesi', labelEn: 'Company events cannot affect price' }], taskCorrectIds: ['gap'],
  questions: [
    { prompt: 'Stop emri gap durumunda belirlenen fiyattan gerçekleşmeyi garanti eder mi?', promptEn: 'Does a stop guarantee the specified fill price through a gap?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her bilanço gününde', labelEn: 'On every earnings day' }], correctId: 'a', explanation: 'Piyasa sonraki uygun fiyattan işlem görebilir.', explanationEn: 'The market may next trade at a different available price.' },
    { prompt: 'Şirket haberi seans dışında fiyatlamayı değiştirebilir mi?', promptEn: 'Can company news reprice an equity outside regular hours?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece ETFlerde', labelEn: 'Only in ETFs' }], correctId: 'a', explanation: 'Yeni bilgi beklentileri seanslar arasında değiştirebilir.', explanationEn: 'New information can change expectations between sessions.' },
    { prompt: 'Event risk pozisyon büyüklüğüyle ilişkili midir?', promptEn: 'Is event risk related to position sizing?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'İlgisizdir', labelEn: 'It is unrelated' }], correctId: 'a', explanation: 'Gap halinde kayıp etkisini pozisyon büyüklüğü belirler.', explanationEn: 'Position size shapes account impact when gaps occur.' },
  ], sources: [ASSET_SCHOOL_SOURCES.equities],
});

const etfNav = createFoundationLesson({
  id: 'lesson.asset.etf.nav-tracking.001', slug: 'etf-nav-ve-tracking-farki', conceptKey: 'asset.etf.nav_tracking', skillId: 'skill.asset-schools', competencyId: 'competency.etf-nav-tracking.foundation',
  title: 'ETF fiyatı neden endeksle birebir aynı hareket etmeyebilir?', titleEn: 'Why can an ETF deviate from its index?',
  objective: 'ETF fiyatı ile NAV’ın neden aynı şey olmadığını ve tracking farkını öğren.', objectiveEn: 'Distinguish ETF market price, NAV, premium/discount, and tracking difference.', minutes: 5,
  hook: 'ETF aynı endeksi takip ediyorsa getirisi neden endeks getirisinden birkaç ondalık farklı çıkabilir?', hookEn: 'If an ETF tracks an index, why can its return differ by a few tenths from the index?',
  explanation: 'ETF borsada piyasa fiyatıyla işlem görür; içindeki varlıkların net değeri NAV ile ölçülür. Piyasa fiyatı kısa süre NAV’ın üstünde veya altında olabilir. Ücretler, vergiler ve uygulama farkları da fonun endeksten biraz farklı getiri üretmesine yol açabilir.', explanationEn: 'An ETF trades at a market price while the value of its underlying holdings is represented by NAV. Supply and demand can move market price temporarily above or below NAV. Fees, taxes, cash holdings, rebalancing, and implementation can also make long-run fund returns differ from the benchmark; this is tracking difference.',
  proExplanation: 'Creation/redemption and authorized participants can help arbitrage large price/NAV deviations, but stressed or illiquid underlying markets can weaken that linkage. Tracking error and tracking difference are related but distinct concepts.', proExplanationEn: 'Creation/redemption and authorized participants can help arbitrage large price/NAV deviations, but stressed or illiquid underlying markets can weaken that linkage. Tracking error and tracking difference are related but distinct concepts.',
  misconception: '“Endeksi takip ediyor” diye ETF’nin her an endeksle birebir aynı gideceğini sanma.', misconceptionEn: 'Common mistake: assuming “tracks the index” means the ETF must match it perfectly at every moment.',
  takeaway: 'ETF’de endeks, NAV, piyasa fiyatı ve maliyeti ayrı oku.', takeawayEn: 'For ETFs, separate the benchmark, NAV, market price, and costs.',
  prerequisiteConceptKeys: ['market.etf.basics'], relatedConceptKeys: ['market.indices.basics', 'market.microstructure.bid_ask', 'quant.transaction_costs'],
  visualAlt: 'Benchmark çizgisi, NAV çizgisi ve ETF piyasa fiyatını küçük premium/discount sapmalarıyla üst üste gösteren görsel', visualAltEn: 'Visual overlaying benchmark, NAV, and ETF market price with small premium/discount deviations',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/asset-schools/etf-nav-tracking-001', taskPrompt: 'ETF piyasa fiyatı NAV’ın üzerindeyse ne denir?', taskPromptEn: 'What is it called when ETF market price is above NAV?',
  taskChoices: [{ id: 'premium', label: 'NAV’a göre premium', labelEn: 'A premium to NAV' }, { id: 'guarantee', label: 'Kesin yüksek getiri', labelEn: 'Guaranteed higher return' }, { id: 'split', label: 'Stock split', labelEn: 'A stock split' }], taskCorrectIds: ['premium'],
  questions: [
    { prompt: 'ETF piyasa fiyatı NAV’dan kısa süre sapabilir mi?', promptEn: 'Can ETF market price temporarily deviate from NAV?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece kripto ETFlerinde', labelEn: 'Only crypto ETFs' }], correctId: 'a', explanation: 'Piyasa fiyatı arz-talep ile oluşur.', explanationEn: 'Market price is formed through supply and demand.' },
    { prompt: 'Tracking difference neyi anlatır?', promptEn: 'What does tracking difference describe?', choices: [{ id: 'a', label: 'Fon getirisi ile benchmark getirisi arasındaki farkı', labelEn: 'The return difference between the fund and its benchmark' }, { id: 'b', label: 'Sadece spreadi', labelEn: 'Only the spread' }, { id: 'c', label: 'Şirket kârını', labelEn: 'Company earnings' }], correctId: 'a', explanation: 'Fon uygulaması benchmark’tan sapabilir.', explanationEn: 'Fund implementation can differ from the benchmark.' },
    { prompt: 'ETF ücretleri tracking’i etkileyebilir mi?', promptEn: 'Can ETF fees affect tracking?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'İlgisizdir', labelEn: 'They are unrelated' }], correctId: 'a', explanation: 'Maliyetler fon getirisini aşağı çekebilir.', explanationEn: 'Costs can reduce fund returns.' },
  ], sources: [ASSET_SCHOOL_SOURCES.etf],
});

const leveragedEtf = createFoundationLesson({
  id: 'lesson.asset.etf.leveraged-inverse.001', slug: 'kaldiracli-ve-ters-etf-gunluk-reset', conceptKey: 'asset.etf.leveraged_inverse', skillId: 'skill.asset-schools', competencyId: 'competency.etf-leveraged-inverse.foundation',
  title: '2× ETF neden uzun vadede endeksin tam 2 katı olmayabilir?', titleEn: 'Why may a 2× ETF not deliver exactly twice the index over long periods?',
  objective: 'Kaldıraçlı ETF’nin neden uzun vadede endeksin basit katı gibi davranmayabildiğini öğren.', objectiveEn: 'Explain how daily reset objectives in leveraged and inverse ETFs can make multi-day compounded results differ from a simple multiple.', minutes: 5,
  hook: 'Endeks iki günde başladığı yere dönerse 2× ETF de mutlaka başladığı yere döner mi?', hookEn: 'If an index returns to its starting point after two days, must a 2× ETF do the same?',
  explanation: 'Birçok kaldıraçlı veya ters ETF günlük hareketin belirli katını hedefler. Hedef her gün yeniden kurulduğu için getiriler bileşiklenir. Dalgalı piyasada birkaç günlük sonuç, endeksin toplam hareketinin basit 2× veya −1× çarpımı olmayabilir.', explanationEn: 'Many leveraged or inverse ETFs target a multiple of the benchmark’s daily move. Because exposure resets daily, sequential percentage moves compound. In volatile markets, multi-day performance can differ materially from simply multiplying the benchmark’s total return by 2× or −1×.',
  proExplanation: 'Path dependency, volatility drag, financing, derivatives costs, rebalance timing, and fund expenses matter. The stated multiple usually describes a daily objective, not a guaranteed holding-period multiple.', proExplanationEn: 'Path dependency, volatility drag, financing, derivatives costs, rebalance timing, and fund expenses matter. The stated multiple usually describes a daily objective, not a guaranteed holding-period multiple.',
  misconception: '“2×” etiketini her süre için endeks getirisinin tam iki katı sanma.', misconceptionEn: 'Common mistake: reading “2×” as exactly twice the index return over every holding period.',
  takeaway: 'Kaldıraçlı ETF’de önce hedef süresini oku.', takeawayEn: 'For leveraged ETFs, read the target horizon before the multiple.',
  prerequisiteConceptKeys: ['asset.etf.nav_tracking', 'risk.leverage'], relatedConceptKeys: ['portfolio.drawdown', 'risk.volatility', 'quant.expectancy'],
  visualAlt: 'Endeksin +10% ve ardından −9,09% ile başa döndüğü, günlük 2× ETF’nin ise bileşik etkiyle farklı sonuç verdiği iki günlük örnek', visualAltEn: 'Two-day example where an index rises 10% then falls 9.09% back to start while a daily 2× ETF ends elsewhere due to compounding',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/asset-schools/leveraged-etf-001', taskPrompt: '2× ETF etiketinde ilk hangi ayrıntıya bakmalısın?', taskPromptEn: 'What should you check first when seeing a 2× ETF label?',
  taskChoices: [{ id: 'horizon', label: 'Çarpanın günlük mı başka bir hedef ufkuna mı ait olduğuna', labelEn: 'Whether the multiple targets daily or another horizon' }, { id: 'forever', label: 'Her sürede kesin 2× olduğuna', labelEn: 'Assume it is exactly 2× over every horizon' }, { id: 'none', label: 'Volatilitenin etkisiz olduğuna', labelEn: 'Assume volatility has no effect' }], taskCorrectIds: ['horizon'],
  questions: [
    { prompt: 'Günlük reset çok günlük sonucu etkileyebilir mi?', promptEn: 'Can daily reset affect multi-day results?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece düşüşte', labelEn: 'Only in declines' }], correctId: 'a', explanation: 'Yüzdesel getiriler günlük bileşiklenir.', explanationEn: 'Percentage returns compound day by day.' },
    { prompt: '2× etiketi her holding period için garanti midir?', promptEn: 'Is the 2× label guaranteed for every holding period?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Çoğu ürün günlük hedef tanımlar.', explanationEn: 'Many products define a daily objective.' },
    { prompt: 'Volatilite ve path dependency önemli midir?', promptEn: 'Do volatility and path dependency matter?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'İlgisizdir', labelEn: 'They are unrelated' }], correctId: 'a', explanation: 'Getiri yolu bileşik sonucu değiştirir.', explanationEn: 'The return path changes compounded outcomes.' },
  ], sources: [ASSET_SCHOOL_SOURCES.etf],
});

const fxCarry = createFoundationLesson({
  id: 'lesson.asset.fx.carry-rollover.001', slug: 'fx-carry-ve-rollover', conceptKey: 'asset.fx.carry_rollover', skillId: 'skill.asset-schools', competencyId: 'competency.fx-carry.foundation',
  title: 'FX pozisyonunda fiyat değişmese bile neden maliyet/getiri oluşabilir?', titleEn: 'Why can an FX position gain or lose carry even if spot price barely moves?',
  objective: 'FX pozisyonunda fiyat değişmese bile carry veya rollover etkisinin neden oluşabildiğini öğren.', objectiveEn: 'Explain how interest-rate differentials, financing, and broker conventions can create rollover/carry effects in FX.', minutes: 5,
  hook: 'Kur aynı yerde kalırsa gecelik taşınan FX pozisyonunun sonucu da sıfır mı olur?', hookEn: 'If the exchange rate is unchanged, must an overnight FX position have zero result?',
  explanation: 'FX işlemi iki paranın göreli fiyatıdır. Pozisyon gece taşınırsa faiz farkı, finansman koşulları ve broker’ın swap/rollover uygulaması pozitif veya negatif taşıma etkisi yaratabilir. Bu etki kur hareketinden ayrı bir sonuç bileşenidir.', explanationEn: 'FX is the relative price of two currencies. When a position is held overnight, interest-rate differentials, financing conditions, and the broker’s rollover/swap convention can create positive or negative carry. This is a separate return component from spot direction.',
  proExplanation: 'Carry is not simply the policy-rate spread. Forward points, funding basis, broker markup, settlement conventions, holiday/weekend rolls, and changing rate expectations can affect realized financing.', proExplanationEn: 'Carry is not simply the policy-rate spread. Forward points, funding basis, broker markup, settlement conventions, holiday/weekend rolls, and changing rate expectations can affect realized financing.',
  misconception: 'FX sonucunu yalnız giriş ve çıkış kuru farkı sanma.', misconceptionEn: 'Common mistake: assuming FX P&L consists only of the entry-to-exit spot-price difference.',
  takeaway: 'FX sonucunda yön, carry ve işlem maliyetini birlikte düşün.', takeawayEn: 'In FX, direction + carry + trading costs together shape realized results.',
  prerequisiteConceptKeys: ['market.forex.basics', 'economy.interest_rates'], relatedConceptKeys: ['quant.transaction_costs', 'market.microstructure.bid_ask', 'asset.fx.session_event'],
  visualAlt: 'Bir FX paritesinde spot fiyat değişimini ayrı, gecelik carry/rollover akışını ayrı gösteren iki katmanlı sonuç görseli', visualAltEn: 'Two-layer P&L visual separating spot-price movement from overnight carry/rollover in an FX pair',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/asset-schools/fx-carry-001', taskPrompt: 'FX pozisyonu gece taşınırsa hangi ek bileşen oluşabilir?', taskPromptEn: 'What additional component can appear when an FX position is held overnight?',
  taskChoices: [{ id: 'carry', label: 'Carry / rollover finansman etkisi', labelEn: 'Carry / rollover financing effect' }, { id: 'none', label: 'Hiçbir şey; yalnız spot değişir', labelEn: 'Nothing; only spot can matter' }, { id: 'dividend', label: 'Hisse temettüsü', labelEn: 'An equity dividend' }], taskCorrectIds: ['carry'],
  questions: [
    { prompt: 'Kur değişmese bile carry sonucu etkileyebilir mi?', promptEn: 'Can carry affect P&L even if spot barely changes?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece hissede', labelEn: 'Only in equities' }], correctId: 'a', explanation: 'Finansman ayrı getiri/maliyet bileşenidir.', explanationEn: 'Financing is a separate return/cost component.' },
    { prompt: 'Carry yalnız politika faizi farkı mıdır?', promptEn: 'Is carry just the policy-rate difference?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Forward/funding ve broker koşulları da etkiler.', explanationEn: 'Forward/funding and broker conventions also matter.' },
    { prompt: 'FX gerçek sonucu hangi üç katman oluşturabilir?', promptEn: 'Which three layers can shape realized FX results?', choices: [{ id: 'a', label: 'Spot yönü, carry ve işlem maliyeti', labelEn: 'Spot direction, carry, and trading costs' }, { id: 'b', label: 'Sadece win rate', labelEn: 'Only win rate' }, { id: 'c', label: 'Sadece grafik formasyonu', labelEn: 'Only chart pattern' }], correctId: 'a', explanation: 'Pozisyon getirisi tek fiyat değişiminden daha geniştir.', explanationEn: 'Position returns can include more than spot movement.' },
  ], sources: [ASSET_SCHOOL_SOURCES.forex],
});

export const ASSET_SCHOOL_FOUNDATION_LESSONS = [crossMarket, corporateActions, earningsGaps, etfNav, leveragedEtf, fxCarry] as const;
