import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { ECONOMY_SOURCES } from './economySources';

const inflation = createFoundationLesson({
  id: 'lesson.economy.inflation.001',
  slug: 'enflasyon-satin-alma-gucu',
  conceptKey: 'economy.inflation',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.explain-inflation.foundation',
  title: 'Aynı para neden zamanla daha az şey alır?',
  titleEn: 'Why can the same money buy less over time?',
  objective: 'Fiyatlar yükselince aynı paranın neden daha az şey alabildiğini öğren.',
  objectiveEn: 'Explain why the same amount of money can buy fewer goods when prices broadly rise.',
  minutes: 4,
  hook: 'Aynı 100 TL neden artık aynı sepeti doldurmuyor?',
  hookEn: 'Why might the same TRY 100 no longer fill the same basket a few years later?',
  explanation: 'Birçok ürünün fiyatı yükselirse 100 TL ile eskisinden daha az şey alırsın. Paranın alabildiği miktara satın alma gücü denir.',
  explanationEn: 'If many goods and services become more expensive, the same money buys less. The amount your money can buy is called purchasing power, and it can fall.',
  misconception: 'Tek bir ürünün pahalanması, her şeyin pahalandığı anlamına gelmez.',
  misconceptionEn: 'One product becoming more expensive does not mean everything became more expensive. Broad price movement is judged across a wider group of goods.',
  takeaway: 'Fiyatlar yükselirse aynı paranın alım gücü azalabilir.',
  takeawayEn: 'If prices broadly rise while your money stays the same, your purchasing power can fall.',
  prerequisiteConceptKeys: [],
  relatedConceptKeys: ['economy.interest_rates', 'economy.monetary_policy'],
  visualAlt: 'Aynı bütçeyle farklı zamanlarda alınabilen ürün miktarını karşılaştıran sade market sepeti görseli',
  visualAltEn: 'Simple shopping-basket visual comparing how much the same budget can buy at different times',
  taskPrompt: 'Aynı 100 TL ile eskiden beş ürün, şimdi üç ürün alabiliyorsan ne değişmiştir?',
  taskPromptEn: 'If TRY 100 used to buy five items and now buys three, what changed?',
  taskChoices: [
    { id: 'less', label: 'Paranın satın alma gücü azalmıştır', labelEn: 'The money has lost purchasing power' },
    { id: 'more', label: 'Paranın satın alma gücü artmıştır', labelEn: 'The money has gained purchasing power' },
    { id: 'same', label: 'Alabildiğin miktar değişmediği için hiçbir şey değişmemiştir', labelEn: 'Nothing changed because the amount you can buy stayed the same' },
  ],
  taskCorrectIds: ['less'],
  questions: [
    { prompt: 'Satın alma gücü en basit hâliyle neyi anlatır?', promptEn: 'What does purchasing power describe most simply?', choices: [{ id: 'a', label: 'Paranla ne kadar ürün ve hizmet alabildiğini', labelEn: 'How many goods and services your money can buy' }, { id: 'b', label: 'Paranın kâğıt üzerindeki boyutunu', labelEn: 'The physical size of a banknote' }, { id: 'c', label: 'Sadece borsadaki fiyatları', labelEn: 'Only stock-market prices' }], correctId: 'a', explanation: 'Satın alma gücü, aynı para miktarının gerçekte ne kadar şey alabildiğini anlatır.', explanationEn: 'Purchasing power describes how much a given amount of money can actually buy.' },
    { prompt: 'Birçok ürünün fiyatı yükselirken gelirin aynı kalırsa ne olabilir?', promptEn: 'What can happen if many prices rise while your income stays the same?', choices: [{ id: 'a', label: 'Aynı parayla daha az ürün alabilirsin', labelEn: 'You may buy fewer goods with the same money' }, { id: 'b', label: 'Aynı parayla otomatik olarak daha fazla ürün alırsın', labelEn: 'You automatically buy more goods with the same money' }, { id: 'c', label: 'Fiyatların değişmesi alım gücünü hiçbir şekilde etkilemez', labelEn: 'Price changes never affect purchasing power' }], correctId: 'a', explanation: 'Fiyatlar geniş biçimde yükseldiğinde aynı bütçe daha az ürün ve hizmete yetebilir.', explanationEn: 'When prices rise broadly, the same budget may cover fewer goods and services.' },
    { prompt: 'Sadece domatesin pahalanması genel enflasyonu tek başına gösterir mi?', promptEn: 'Does only tomatoes becoming more expensive prove broad inflation by itself?', choices: [{ id: 'a', label: 'Hayır; daha geniş bir ürün grubuna bakmak gerekir', labelEn: 'No; a broader group of goods needs to be considered' }, { id: 'b', label: 'Evet; tek bir ürün her zaman bütün ekonomiyi temsil eder', labelEn: 'Yes; one product always represents the whole economy' }, { id: 'c', label: 'Yalnız ürün markette satılıyorsa genel enflasyonu gösterir', labelEn: 'Only if the product is sold in a supermarket' }], correctId: 'a', explanation: 'Genel enflasyon tek bir üründen değil, daha geniş fiyat hareketinden anlaşılır.', explanationEn: 'Broad inflation is understood from wider price movement, not one product alone.' },
  ],
  sources: [ECONOMY_SOURCES.inflation],
});

const interestRates = createFoundationLesson({
  id: 'lesson.economy.interest-rates.001',
  slug: 'faiz-orani-ne-anlatir',
  conceptKey: 'economy.interest_rates',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.explain-interest-rates.foundation',
  title: 'Faiz neyi etkiler?',
  titleEn: 'What does interest affect?',
  objective: 'Faiz değişince kredi maliyetinin ve harcamaların nasıl etkilenebildiğini öğren.',
  objectiveEn: 'Explain how interest can affect borrowing costs, spending, and saving.',
  minutes: 4,
  hook: 'Faiz yükselince kredi neden daha pahalı olabilir?',
  hookEn: 'Why can borrowing feel harder when interest rates rise?',
  explanation: 'Faiz, borç aldığın paranın maliyetini etkiler. Faiz yükselirse yeni kredi ve taksitler pahalılaşabilir; bazı harcamalar ertelenebilir.',
  explanationEn: 'Interest affects the cost of using borrowed money. When rates rise, new loans can become more expensive, which can lead some people and businesses to spend less.',
  misconception: 'Bütün krediler aynı faiz oranıyla verilmez. Vade ve risk gibi koşullar oranı değiştirebilir.',
  misconceptionEn: 'There is not one identical interest rate for every loan. Product type, maturity, and risk can change the actual rate.',
  takeaway: 'Faiz yükselirse borçlanma genellikle pahalılaşır.',
  takeawayEn: 'When interest rises, borrowing generally becomes more expensive, which can affect spending and investment decisions.',
  prerequisiteConceptKeys: ['economy.inflation'],
  relatedConceptKeys: ['economy.central_banks', 'economy.monetary_policy'],
  visualAlt: 'Düşük ve yüksek faiz ortamında aynı kredinin maliyet farkını gösteren sade görsel',
  visualAltEn: 'Simple visual showing how the cost of the same loan can differ in low- and high-rate environments',
  taskPrompt: 'Diğer koşullar aynıysa faiz yükseldiğinde yeni bir kredi için en olası genel değişim nedir?',
  taskPromptEn: 'If other conditions are unchanged, what is the most likely general change for a new loan when rates rise?',
  taskChoices: [
    { id: 'costlier', label: 'Borçlanma maliyeti artabilir', labelEn: 'Borrowing cost can increase' },
    { id: 'cheaper', label: 'Borçlanma maliyeti otomatik olarak düşer', labelEn: 'Borrowing cost automatically falls' },
    { id: 'unrelated', label: 'Faiz ile kredi maliyeti arasında ilişki yoktur', labelEn: 'Interest and borrowing cost are unrelated' },
  ],
  taskCorrectIds: ['costlier'],
  questions: [
    { prompt: 'Faiz borç alan kişi için en basit hâliyle neyi etkiler?', promptEn: 'For a borrower, what does interest most simply affect?', choices: [{ id: 'a', label: 'Borçlanmanın maliyetini', labelEn: 'The cost of borrowing' }, { id: 'b', label: 'Marketteki ürünlerin ağırlığını', labelEn: 'The weight of goods in a store' }, { id: 'c', label: 'Bir şirketin adını', labelEn: 'A company name' }], correctId: 'a', explanation: 'Faiz, ödünç alınan parayı kullanmanın toplam maliyetinin önemli bir parçasıdır.', explanationEn: 'Interest is an important part of the total cost of using borrowed money.' },
    { prompt: 'Faiz yükseldiğinde bazı insanlar neden harcamayı azaltabilir?', promptEn: 'Why might some people reduce spending when interest rises?', choices: [{ id: 'a', label: 'Kredi ve taksit maliyeti artabileceği için', labelEn: 'Because loan and installment costs can rise' }, { id: 'b', label: 'Bütün ürünler ücretsiz olduğu için', labelEn: 'Because all goods become free' }, { id: 'c', label: 'Paranın kullanım maliyeti tamamen ortadan kalktığı için', labelEn: 'Because the cost of using money disappears' }], correctId: 'a', explanation: 'Borçlanma pahalılaştığında bazı harcama ve yatırım kararları ertelenebilir.', explanationEn: 'When borrowing becomes more expensive, some spending and investment decisions may be delayed.' },
    { prompt: 'Bütün kredi faizleri aynı olmak zorunda mıdır?', promptEn: 'Must all loan interest rates be identical?', choices: [{ id: 'a', label: 'Hayır; kredi türü, vade ve risk oranı değiştirebilir', labelEn: 'No; product type, maturity, and risk can change the rate' }, { id: 'b', label: 'Evet; ekonomide yalnız tek faiz olabilir', labelEn: 'Yes; there can only be one interest rate in an economy' }, { id: 'c', label: 'Yalnız kredi küçükse hepsi aynı olur', labelEn: 'Only small loans must have the same rate' }], correctId: 'a', explanation: 'Gerçek kredi oranları ürünün özelliklerine ve borçlunun riskine göre farklılaşabilir.', explanationEn: 'Actual loan rates can differ according to product features and borrower risk.' },
  ],
  sources: [ECONOMY_SOURCES.rates],
});

const centralBanks = createFoundationLesson({
  id: 'lesson.economy.central-banks.001',
  slug: 'merkez-bankasi-ne-yapar',
  conceptKey: 'economy.central_banks',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.explain-central-bank-role.foundation',
  title: 'Merkez bankası neden önemlidir?',
  titleEn: 'Why does a central bank matter?',
  objective: 'Merkez bankasının faiz ve para koşulları üzerinden ekonomiyi nasıl etkilediğini öğren.',
  objectiveEn: 'Explain the basic role of a central bank in money and financial conditions.',
  minutes: 4,
  hook: 'Merkez bankasının faiz kararı neden bu kadar önemsenir?',
  hookEn: 'Why do central-bank rate decisions appear in the news so often?',
  explanation: 'Merkez bankası faiz gibi araçlarla kredi ve para koşullarını etkileyebilir. Böylece enflasyon ve ekonomik hareket üzerinde etkisi olabilir.',
  explanationEn: 'A central bank is an important institution in a country’s monetary and financial system. It can use tools such as interest rates to help limit rapid price increases and influence financial conditions.',
  misconception: 'Merkez bankası marketteki veya borsadaki fiyatları tek tek belirlemez.',
  misconceptionEn: 'A central bank does not set every supermarket or stock-market price one by one. Its decisions influence conditions, while prices form through many other factors too.',
  takeaway: 'Merkez bankası fiyatları değil, ekonomik koşulları etkiler.',
  takeawayEn: 'A central bank does not set every price, but it can influence the economy through interest rates and monetary conditions.',
  prerequisiteConceptKeys: ['economy.interest_rates'],
  relatedConceptKeys: ['economy.monetary_policy', 'economy.inflation'],
  visualAlt: 'Merkez bankası binasından faiz ve kredi koşullarına uzanan sade etki görseli',
  visualAltEn: 'Simple visual linking a central-bank building with interest and borrowing conditions',
  taskPrompt: 'Merkez bankasının rolünü hangisi daha doğru anlatır?',
  taskPromptEn: 'Which statement better describes the role of a central bank?',
  taskChoices: [
    { id: 'influence', label: 'Faiz ve para koşullarını etkileyerek ekonomiyi dengelemeye çalışabilir', labelEn: 'It can influence rates and monetary conditions to help stabilize the economy' },
    { id: 'all-prices', label: 'Bütün ürün ve hisse fiyatlarını tek tek belirler', labelEn: 'It sets every product and stock price one by one' },
    { id: 'none', label: 'Para ve kredi koşullarıyla hiçbir ilişkisi yoktur', labelEn: 'It has no relationship with money or credit conditions' },
  ],
  taskCorrectIds: ['influence'],
  questions: [
    { prompt: 'Merkez bankası hangi alanı doğrudan etkileyebilen araçlar kullanır?', promptEn: 'What area can central-bank tools directly influence?', choices: [{ id: 'a', label: 'Faiz ve para koşullarını', labelEn: 'Interest and monetary conditions' }, { id: 'b', label: 'Her market ürününün tek tek fiyat etiketini', labelEn: 'Every supermarket price tag individually' }, { id: 'c', label: 'Her şirketin günlük satış miktarını', labelEn: 'Every company’s daily sales volume' }], correctId: 'a', explanation: 'Merkez bankası araçları finansal koşulları etkileyebilir, fakat her fiyatı doğrudan belirlemez.', explanationEn: 'Central-bank tools can influence financial conditions, but they do not directly set every price.' },
    { prompt: 'Merkez bankası neden faiz kararını değiştirebilir?', promptEn: 'Why might a central bank change its policy rate?', choices: [{ id: 'a', label: 'Ekonomideki fiyat ve finansal koşulları etkilemek için', labelEn: 'To influence price and financial conditions in the economy' }, { id: 'b', label: 'Borsada belirli bir hisseyi yükseltmek için', labelEn: 'To raise one specific stock price' }, { id: 'c', label: 'Marketlerdeki bütün ürünleri aynı fiyata getirmek için', labelEn: 'To make every supermarket item the same price' }], correctId: 'a', explanation: 'Faiz kararı, para politikasının ekonomi üzerindeki temel araçlarından biridir.', explanationEn: 'The policy rate is one of the main tools through which monetary policy influences the economy.' },
    { prompt: 'Merkez bankası borsadaki her fiyatı doğrudan belirler mi?', promptEn: 'Does a central bank directly set every stock-market price?', choices: [{ id: 'a', label: 'Hayır; piyasa fiyatları birçok etken ve işlemle oluşur', labelEn: 'No; market prices form through many factors and transactions' }, { id: 'b', label: 'Evet; bütün fiyatlar tek kurum tarafından belirlenir', labelEn: 'Yes; all prices are set by one institution' }, { id: 'c', label: 'Sadece büyük şirketlerin fiyatlarını doğrudan belirler', labelEn: 'It directly sets only large-company prices' }], correctId: 'a', explanation: 'Politika piyasayı etkileyebilir, ancak alıcılar, satıcılar ve birçok başka etken fiyat oluşumunda rol oynar.', explanationEn: 'Policy can influence markets, but buyers, sellers, and many other factors shape prices.' },
  ],
  sources: [ECONOMY_SOURCES.centralBanks],
});

const monetaryPolicy = createFoundationLesson({
  id: 'lesson.economy.monetary-policy.001',
  slug: 'faiz-karari-ekonomiye-nasil-yansir',
  conceptKey: 'economy.monetary_policy',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.trace-monetary-policy.foundation',
  title: 'Faiz değişince ekonomi nasıl etkilenir?',
  titleEn: 'How can the economy react when interest changes?',
  objective: 'Faiz kararının kredi ve harcama üzerinden ekonomiye nasıl yayıldığını öğren.',
  objectiveEn: 'Explain how a rate decision can spread through borrowing, spending, and investment.',
  minutes: 4,
  hook: 'Faiz değişince neden her şey aynı gün değişmez?',
  hookEn: 'Why does one rate decision not change everything overnight?',
  explanation: 'Faiz değişince önce kredi koşulları etkilenebilir. Sonra insanlar ve şirketler harcama veya yatırım kararlarını değiştirebilir. Bu yüzden etki zamanla yayılır.',
  explanationEn: 'When interest changes, borrowing and saving conditions may react first. People and businesses may then change spending, borrowing, and investment decisions, so the effect spreads over time.',
  misconception: 'Faiz kararı bir aç-kapa düğmesi gibi anında sonuç vermez.',
  misconceptionEn: 'A rate decision does not work like an instant switch. The same decision can have different speed and strength in different economic conditions.',
  takeaway: 'Faiz kararının etkisi ekonomiye zamanla yayılır.',
  takeawayEn: 'A rate decision spreads through the economy over time and through a chain of effects; its impact is not instant or certain.',
  prerequisiteConceptKeys: ['economy.central_banks', 'economy.interest_rates'],
  relatedConceptKeys: ['economy.inflation', 'economy.growth'],
  visualAlt: 'Faizden kredi koşullarına, harcamaya ve yatırıma uzanan sade etki zinciri',
  visualAltEn: 'Simple chain showing interest affecting borrowing conditions, spending, and investment',
  taskPrompt: 'Faiz yükseldiğinde ekonomi üzerindeki etki için en doğru basit zincir hangisidir?',
  taskPromptEn: 'Which simple chain best describes a possible effect when interest rises?',
  taskChoices: [
    { id: 'chain', label: 'Kredi pahalılaşabilir, bazı harcama ve yatırımlar yavaşlayabilir', labelEn: 'Borrowing can become more expensive and some spending and investment can slow' },
    { id: 'instant', label: 'Bütün fiyatlar aynı gün aynı oranda değişmek zorundadır', labelEn: 'Every price must change by the same amount on the same day' },
    { id: 'none', label: 'Faiz değişimi hiçbir ekonomik kararı etkileyemez', labelEn: 'Interest changes cannot affect any economic decision' },
  ],
  taskCorrectIds: ['chain'],
  questions: [
    { prompt: 'Faiz kararı ekonomiye neden zaman içinde yayılır?', promptEn: 'Why can a rate decision spread through the economy over time?', choices: [{ id: 'a', label: 'İnsanların ve şirketlerin kararlarının değişmesi zaman aldığı için', labelEn: 'Because people and businesses take time to change decisions' }, { id: 'b', label: 'Faiz sadece takvim üzerinde görünen bir sayı olduğu için', labelEn: 'Because interest is only a number on a calendar' }, { id: 'c', label: 'Bütün ekonomik kararlar aynı anda verildiği için', labelEn: 'Because every economic decision happens at once' }], correctId: 'a', explanation: 'Kredi, harcama ve yatırım kararları farklı zamanlarda değiştiği için etki aşamalar hâlinde yayılabilir.', explanationEn: 'Borrowing, spending, and investment decisions change at different times, so the effect can spread in stages.' },
    { prompt: 'Faiz yükseldiğinde kredi maliyeti için ne söylenebilir?', promptEn: 'What can be said about borrowing cost when rates rise?', choices: [{ id: 'a', label: 'Diğer koşullar aynıysa artabilir', labelEn: 'It can rise if other conditions stay the same' }, { id: 'b', label: 'Her durumda sıfıra iner', labelEn: 'It falls to zero in every case' }, { id: 'c', label: 'Faiz ile kredi maliyeti arasında hiçbir bağ yoktur', labelEn: 'There is no link between rates and borrowing costs' }], correctId: 'a', explanation: 'Daha yüksek faiz yeni borçlanmanın maliyetini artırabilen temel etkenlerden biridir.', explanationEn: 'Higher interest is one of the main factors that can increase the cost of new borrowing.' },
    { prompt: 'Aynı faiz kararı her dönemde aynı sonucu verir mi?', promptEn: 'Does the same rate decision produce the same result in every period?', choices: [{ id: 'a', label: 'Hayır; ekonomik koşullar etkiyi değiştirebilir', labelEn: 'No; economic conditions can change the effect' }, { id: 'b', label: 'Evet; sonuç her zaman aynı hız ve büyüklükte olur', labelEn: 'Yes; the result always has the same speed and size' }, { id: 'c', label: 'Sadece borsa kapalıysa farklı sonuç verir', labelEn: 'Only when the stock market is closed' }], correctId: 'a', explanation: 'Borçluluk, beklentiler ve ekonomik koşullar politika etkisinin gücünü değiştirebilir.', explanationEn: 'Debt levels, expectations, and economic conditions can change the strength of policy effects.' },
  ],
  sources: [ECONOMY_SOURCES.monetaryPolicy],
});

const growth = createFoundationLesson({
  id: 'lesson.economy.growth.001',
  slug: 'gsyh-buyume-ne-anlatir',
  conceptKey: 'economy.growth',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.explain-gdp-growth.foundation',
  title: 'Ekonomi büyüyor demek ne demek?',
  titleEn: 'What does it mean when the economy grows?',
  objective: 'Ekonomik büyümenin toplam mal ve hizmet üretimiyle ne ilgisi olduğunu öğren.',
  objectiveEn: 'Connect economic growth with the idea of producing more goods and services.',
  minutes: 4,
  hook: '“Ekonomi büyüdü” denince aslında ne arttı?',
  hookEn: 'When we say an economy grew, what actually increased?',
  explanation: 'Ekonomik büyüme, ülkede üretilen mal ve hizmetlerin toplamının artmasıdır. GSYH bu toplam üretimi ölçmek için kullanılan göstergelerden biridir.',
  explanationEn: 'Economic growth means an economy produces more goods and services over time. GDP is one of the main measures used to track that total production.',
  misconception: 'Ekonomi büyüdü diye herkesin geliri aynı oranda artmış olmaz.',
  misconceptionEn: 'Economic growth does not mean everyone’s income rose by the same amount. Total production can rise while the effects differ across people and sectors.',
  takeaway: 'Büyüme, ekonominin toplam üretimindeki artıştır.',
  takeawayEn: 'Economic growth describes an increase in total production; it does not show that everyone’s life improved by the same amount.',
  prerequisiteConceptKeys: ['economy.monetary_policy'],
  relatedConceptKeys: ['economy.business_cycle', 'economy.inflation'],
  visualAlt: 'Mağaza, üretim ve hizmet faaliyetlerinin toplam ekonomik üretimi oluşturduğunu gösteren sade görsel',
  visualAltEn: 'Simple visual showing shops, production, and services contributing to total economic output',
  taskPrompt: 'Bir ekonomide daha fazla mal ve hizmet üretiliyorsa en basit ifadeyle ne söylenebilir?',
  taskPromptEn: 'If an economy is producing more goods and services, what can be said most simply?',
  taskChoices: [
    { id: 'growth', label: 'Toplam ekonomik üretim artıyor olabilir', labelEn: 'Total economic output may be increasing' },
    { id: 'everyone', label: 'Herkesin geliri aynı oranda artmak zorundadır', labelEn: 'Everyone’s income must rise by the same amount' },
    { id: 'prices', label: 'Sadece fiyat etiketleri büyümüş demektir', labelEn: 'It means only price tags became larger' },
  ],
  taskCorrectIds: ['growth'],
  questions: [
    { prompt: 'Ekonomik büyüme en basit hâliyle neyi anlatır?', promptEn: 'What does economic growth describe most simply?', choices: [{ id: 'a', label: 'Toplam mal ve hizmet üretiminin artmasını', labelEn: 'An increase in total production of goods and services' }, { id: 'b', label: 'Sadece borsa fiyatlarının yükselmesini', labelEn: 'Only stock prices rising' }, { id: 'c', label: 'Bütün ürünlerin aynı fiyata gelmesini', labelEn: 'All goods reaching the same price' }], correctId: 'a', explanation: 'Ekonomik büyüme, ekonominin toplam üretim faaliyetindeki artışla ilgilidir.', explanationEn: 'Economic growth is about an increase in the economy’s total production activity.' },
    { prompt: 'GSYH neden izlenir?', promptEn: 'Why is GDP watched?', choices: [{ id: 'a', label: 'Ekonomideki toplam üretimi ölçmeye yardım ettiği için', labelEn: 'Because it helps measure total production in the economy' }, { id: 'b', label: 'Her insanın mutluluğunu doğrudan ölçtüğü için', labelEn: 'Because it directly measures every person’s happiness' }, { id: 'c', label: 'Yalnızca tek bir şirketin satışını gösterdiği için', labelEn: 'Because it shows the sales of only one company' }], correctId: 'a', explanation: 'GSYH, belirli bir dönemde üretilen nihai mal ve hizmetlerin toplam değerini ölçmeye çalışır.', explanationEn: 'GDP seeks to measure the total value of final goods and services produced over a period.' },
    { prompt: 'Ekonomi büyüdüyse herkesin geliri aynı oranda artmış mıdır?', promptEn: 'If the economy grew, did everyone’s income rise by the same amount?', choices: [{ id: 'a', label: 'Hayır; toplam büyümenin etkisi farklı dağılabilir', labelEn: 'No; the effects of total growth can be distributed differently' }, { id: 'b', label: 'Evet; ekonomik büyüme bunu otomatik olarak garanti eder', labelEn: 'Yes; economic growth automatically guarantees this' }, { id: 'c', label: 'Sadece büyük şehirlerde herkesin geliri eşit artar', labelEn: 'Only in large cities does everyone’s income rise equally' }], correctId: 'a', explanation: 'Toplam üretim artışı, gelir ve refahın insanlar arasında nasıl dağıldığını tek başına göstermez.', explanationEn: 'Higher total production does not by itself show how income and well-being are distributed among people.' },
  ],
  sources: [ECONOMY_SOURCES.gdp],
});

const businessCycle = createFoundationLesson({
  id: 'lesson.economy.business-cycle.001',
  slug: 'ekonomik-dongu-resesyon',
  conceptKey: 'economy.business_cycle',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.explain-business-cycle.foundation',
  title: 'Ekonomi neden bazen yavaşlar?',
  titleEn: 'Why does the economy sometimes slow down?',
  objective: 'Ekonomik yavaşlamanın harcama, üretim ve işe alımda nasıl görülebildiğini öğren.',
  objectiveEn: 'Connect an economic slowdown with weaker spending, production, and hiring.',
  minutes: 4,
  hook: 'Satış, üretim ve işe alım birlikte azalırsa ne olur?',
  hookEn: 'If stores sell less and companies begin producing less, what can happen to the economy?',
  explanation: 'İnsanlar ve şirketler daha az harcarsa satışlar düşebilir. Şirketler üretimi ve yeni işe alımları azaltabilir. Ekonomik faaliyet böylece yavaşlayabilir.',
  explanationEn: 'When people and businesses spend and invest less, company sales and production can slow. Hiring may also weaken, and economic activity can soften for a period.',
  misconception: 'Tek bir kötü ay veya tek bir zayıf veri tek başına resesyon demek değildir.',
  misconceptionEn: 'One bad month or one weak data point does not automatically mean recession. The breadth and duration of weakness across the economy also matter.',
  takeaway: 'Ekonomik yavaşlama birden fazla alanda birlikte görülür.',
  takeawayEn: 'The economy can speed up or slow down; what matters is not one number but how overall economic activity changes together.',
  prerequisiteConceptKeys: ['economy.growth'],
  relatedConceptKeys: ['economy.monetary_policy', 'economy.inflation'],
  visualAlt: 'Daha az alışveriş, daha düşük üretim ve daha az işe alımı aynı ekonomik yavaşlama zincirinde gösteren sade görsel',
  visualAltEn: 'Simple visual connecting lower shopping, lower production, and weaker hiring in an economic slowdown',
  taskPrompt: 'Harcamalar, üretim ve işe alımlar birlikte zayıflıyorsa ekonomi için en doğru genel ifade hangisidir?',
  taskPromptEn: 'If spending, production, and hiring are all weakening, which general statement is most accurate?',
  taskChoices: [
    { id: 'slower', label: 'Ekonomik faaliyet yavaşlıyor olabilir', labelEn: 'Economic activity may be slowing' },
    { id: 'faster', label: 'Ekonomi otomatik olarak hızlanıyor demektir', labelEn: 'It automatically means the economy is accelerating' },
    { id: 'unrelated', label: 'Bu göstergelerin ekonomik faaliyetle hiçbir ilişkisi yoktur', labelEn: 'These indicators have no relationship with economic activity' },
  ],
  taskCorrectIds: ['slower'],
  questions: [
    { prompt: 'Ekonomik yavaşlamada hangi durum birlikte görülebilir?', promptEn: 'Which situation can appear during an economic slowdown?', choices: [{ id: 'a', label: 'Daha az harcama, daha düşük üretim ve daha zayıf işe alım', labelEn: 'Less spending, lower production, and weaker hiring' }, { id: 'b', label: 'Her işletmenin satışının aynı anda rekor kırması', labelEn: 'Every business hitting record sales at the same time' }, { id: 'c', label: 'Bütün ürün fiyatlarının aynı değere gelmesi', labelEn: 'All product prices becoming identical' }], correctId: 'a', explanation: 'Ekonomik faaliyet zayıfladığında harcama, üretim ve istihdam göstergeleri birlikte yavaşlayabilir.', explanationEn: 'When economic activity weakens, spending, production, and employment indicators can slow together.' },
    { prompt: 'Tek bir zayıf veri resesyonu kesin olarak kanıtlar mı?', promptEn: 'Does one weak data point prove a recession with certainty?', choices: [{ id: 'a', label: 'Hayır; daha geniş ve daha uzun süreli ekonomik zayıflığa bakılır', labelEn: 'No; broader and more persistent economic weakness is considered' }, { id: 'b', label: 'Evet; tek veri bütün ekonomiyi her zaman açıklar', labelEn: 'Yes; one data point always explains the entire economy' }, { id: 'c', label: 'Sadece veri hafta başında açıklanırsa kesinleşir', labelEn: 'Only if the data is released at the start of the week' }], correctId: 'a', explanation: 'Resesyon değerlendirmesi süre, yaygınlık ve ekonomik faaliyetin genel durumunu birlikte dikkate alır.', explanationEn: 'Recession assessment considers duration, breadth, and the overall state of economic activity together.' },
    { prompt: 'Ekonomi yavaşladığında şirketlerin işe alımı nasıl etkilenebilir?', promptEn: 'How can company hiring be affected when the economy slows?', choices: [{ id: 'a', label: 'Bazı şirketler yeni işe alımları azaltabilir', labelEn: 'Some companies may reduce new hiring' }, { id: 'b', label: 'Bütün şirketler sınırsız işe alım yapmak zorunda kalır', labelEn: 'Every company must hire without limit' }, { id: 'c', label: 'Ekonomik yavaşlamanın işe alımla hiçbir ilişkisi olamaz', labelEn: 'An economic slowdown can never affect hiring' }], correctId: 'a', explanation: 'Satış ve üretim beklentileri zayıfladığında şirketler yeni işe alım kararlarını erteleyebilir.', explanationEn: 'When sales and production expectations weaken, companies may delay new hiring decisions.' },
  ],
  sources: [ECONOMY_SOURCES.businessCycle],
});

export const ECONOMY_FOUNDATION_LESSONS = [
  inflation,
  interestRates,
  centralBanks,
  monetaryPolicy,
  growth,
  businessCycle,
] as const;
