import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { ECONOMY_SOURCES } from './economySources';

const inflation = createFoundationLesson({
  id: 'lesson.economy.inflation.001',
  slug: 'enflasyon-satin-alma-gucu',
  conceptKey: 'economy.inflation',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.explain-inflation.foundation',
  title: 'Enflasyon neden satın alma gücünü azaltır?',
  titleEn: 'Why does inflation reduce purchasing power?',
  objective: 'Genel fiyat düzeyindeki artış ile paranın satın alma gücü arasındaki ilişkiyi açıklar.',
  objectiveEn: 'Explain the relationship between a rise in the general price level and purchasing power.',
  minutes: 4,
  hook: 'Aynı 100 TL ile zaman içinde neden daha az ürün alabilirsin?',
  hookEn: 'Why can the same TRY 100 buy fewer goods over time?',
  explanation: 'Enflasyon, ekonomide mal ve hizmetlerin genel fiyat düzeyinin zaman içinde artmasıdır. Gelirin aynı hızda artmıyorsa aynı para miktarıyla daha az şey satın alabilirsin. Tek bir ürünün pahalanması tek başına genel enflasyon anlamına gelmez; geniş bir fiyat sepetindeki değişim önemlidir.',
  explanationEn: 'Inflation is a sustained rise in the general price level of goods and services. If income does not rise at the same pace, the same amount of money buys less. One product becoming more expensive does not by itself mean broad inflation; changes across a wider basket matter.',
  proExplanation: 'Enflasyon ölçümleri kullanılan sepet, ağırlıklar ve yöntem nedeniyle farklılaşabilir. Manşet ve çekirdek göstergeler farklı amaçlarla izlenir; tek veri noktası kalıcı trend kanıtı değildir.',
  proExplanationEn: 'Inflation measures can differ because of baskets, weights, and methodology. Headline and core measures serve different purposes; one data point does not prove a persistent trend.',
  misconception: 'Yaygın hata: Tek bir ürünün fiyat artışını ekonominin tamamındaki enflasyonla aynı şey sanmak.',
  misconceptionEn: 'Common mistake: treating one product price increase as the same thing as economy-wide inflation.',
  takeaway: 'Enflasyon genel fiyat düzeyini, satın alma gücü ise paranla ne kadar ürün ve hizmet alabildiğini anlatır.',
  takeawayEn: 'Inflation describes the general price level; purchasing power describes how much your money can buy.',
  prerequisiteConceptKeys: [],
  relatedConceptKeys: ['economy.interest_rates', 'economy.monetary_policy'],
  visualAlt: 'Aynı para miktarıyla zaman içinde daha az ürün alınabildiğini gösteren sade satın alma gücü şeması',
  visualAltEn: 'Simple purchasing-power diagram showing the same amount of money buying fewer goods over time',
  taskPrompt: 'Hangisi genel enflasyonu tek bir ürün fiyat artışından daha iyi anlatır?',
  taskPromptEn: 'Which better describes broad inflation than a single product price increase?',
  taskChoices: [
    { id: 'basket', label: 'Geniş bir mal ve hizmet sepetinde genel fiyat artışı', labelEn: 'A broad rise across a basket of goods and services' },
    { id: 'single', label: 'Yalnız bir ürünün geçici olarak pahalanması', labelEn: 'Only one product becoming temporarily more expensive' },
    { id: 'stock', label: 'Tek bir hissenin fiyatının yükselmesi', labelEn: 'One stock price rising' },
  ],
  taskCorrectIds: ['basket'],
  questions: [
    { prompt: 'Enflasyon en temel olarak neyi anlatır?', promptEn: 'At its core, what does inflation describe?', choices: [{ id: 'a', label: 'Genel fiyat düzeyinin zaman içinde artmasını', labelEn: 'A rise in the general price level over time' }, { id: 'b', label: 'Her ürünün aynı oranda pahalanmasını', labelEn: 'Every product rising by the same amount' }, { id: 'c', label: 'Yalnız finansal varlık fiyatlarını', labelEn: 'Only financial asset prices' }], correctId: 'a', explanation: 'Enflasyon geniş bir mal ve hizmet grubundaki genel fiyat hareketiyle ilgilidir.', explanationEn: 'Inflation concerns broad price movement across goods and services.' },
    { prompt: 'Gelir aynı kalırken fiyatlar genel olarak artarsa ne olur?', promptEn: 'What happens if income stays unchanged while prices broadly rise?', choices: [{ id: 'a', label: 'Satın alma gücü azalabilir', labelEn: 'Purchasing power can fall' }, { id: 'b', label: 'Satın alma gücü otomatik artar', labelEn: 'Purchasing power automatically rises' }, { id: 'c', label: 'Fiyatlarla ilgisi yoktur', labelEn: 'It is unrelated to prices' }], correctId: 'a', explanation: 'Aynı gelirle daha az mal ve hizmet alınabilir.', explanationEn: 'The same income may buy fewer goods and services.' },
    { prompt: 'Tek bir ürünün fiyatının artması tek başına genel enflasyonu kanıtlar mı?', promptEn: 'Does one product price increase prove broad inflation by itself?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Her zaman evet', labelEn: 'Always yes' }, { id: 'c', label: 'Yalnız ürün ithalse', labelEn: 'Only if the product is imported' }], correctId: 'a', explanation: 'Genel enflasyon için daha geniş fiyat sepeti ve dönemsel değişim değerlendirilir.', explanationEn: 'Broad inflation is assessed using a wider basket and changes over time.' },
  ],
  sources: [ECONOMY_SOURCES.inflation],
});

const interestRates = createFoundationLesson({
  id: 'lesson.economy.interest-rates.001',
  slug: 'faiz-orani-ne-anlatir',
  conceptKey: 'economy.interest_rates',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.explain-interest-rates.foundation',
  title: 'Faiz oranı neyi anlatır?',
  titleEn: 'What does an interest rate tell us?',
  objective: 'Faizi borçlanmanın maliyeti ve tasarrufun getirisi bağlamında açıklar.',
  objectiveEn: 'Explain interest rates as a borrowing cost and a return on saving.',
  minutes: 4,
  hook: 'Parayı bugün kullanmanın veya başkasına vermenin neden bir bedeli vardır?',
  hookEn: 'Why can using money today—or lending it to someone else—have a price?',
  explanation: 'Faiz, en basit hâliyle parayı belirli bir süre kullanmanın bedelidir. Borç alan için maliyet, tasarruf eden veya borç veren için getiri olabilir. Faiz oranı yükseldiğinde yeni borçlanma genellikle daha pahalı; düştüğünde daha ucuz hâle gelebilir, ancak gerçek koşullar ürün ve risk düzeyine göre değişir.',
  explanationEn: 'At its simplest, interest is the price of using money for a period of time. It can be a cost for a borrower and a return for a saver or lender. Higher rates generally make new borrowing more expensive and lower rates can make it cheaper, although actual terms vary by product and risk.',
  proExplanation: 'Nominal faiz tek başına ekonomik teşviki tam göstermez; beklenen enflasyon, vade, kredi riski ve likidite gibi unsurlar gerçek ve piyasa faizlerini etkiler.',
  proExplanationEn: 'A nominal rate alone does not fully describe economic incentives; expected inflation, maturity, credit risk, and liquidity affect real and market rates.',
  misconception: 'Yaygın hata: Ekonomide tek bir faiz oranı olduğunu ve bütün kredilerin aynı orandan fiyatlandığını düşünmek.',
  misconceptionEn: 'Common mistake: assuming there is one interest rate in the economy and every loan is priced at that same rate.',
  takeaway: 'Faiz paranın zaman içindeki kullanım bedelidir; borçlanma, tasarruf ve yatırım kararlarını etkiler.',
  takeawayEn: 'Interest is the price of using money over time and affects borrowing, saving, and investment decisions.',
  prerequisiteConceptKeys: ['economy.inflation'],
  relatedConceptKeys: ['economy.central_banks', 'economy.monetary_policy'],
  visualAlt: 'Borç alan için maliyet ve tasarruf eden için getiri olarak faizi karşılaştıran sade şema',
  visualAltEn: 'Simple diagram comparing interest as a borrowing cost and a return on saving',
  taskPrompt: 'Faiz yükseldiğinde yeni bir kredinin maliyeti için en doğru genel ifade hangisidir?',
  taskPromptEn: 'What is the most accurate general statement about a new loan when interest rates rise?',
  taskChoices: [
    { id: 'costlier', label: 'Diğer koşullar aynıysa daha pahalı olabilir', labelEn: 'It can be more expensive if other conditions are unchanged' },
    { id: 'free', label: 'Otomatik olarak ücretsiz olur', labelEn: 'It automatically becomes free' },
    { id: 'none', label: 'Faiz borç maliyetini etkilemez', labelEn: 'Interest does not affect borrowing cost' },
  ],
  taskCorrectIds: ['costlier'],
  questions: [
    { prompt: 'Faiz borç alan açısından en temel olarak nedir?', promptEn: 'What is interest most basically for a borrower?', choices: [{ id: 'a', label: 'Parayı kullanmanın maliyeti', labelEn: 'The cost of using money' }, { id: 'b', label: 'Kesin yatırım kazancı', labelEn: 'Guaranteed investment profit' }, { id: 'c', label: 'Bir vergi türü', labelEn: 'A type of tax' }], correctId: 'a', explanation: 'Borç alan, parayı belirli süre kullanmak için faiz ödeyebilir.', explanationEn: 'A borrower may pay interest to use money for a period of time.' },
    { prompt: 'Faiz oranı yükseldiğinde borçlanma genellikle nasıl etkilenir?', promptEn: 'How is borrowing generally affected when interest rates rise?', choices: [{ id: 'a', label: 'Daha pahalı hâle gelebilir', labelEn: 'It can become more expensive' }, { id: 'b', label: 'Her zaman ucuzlar', labelEn: 'It always becomes cheaper' }, { id: 'c', label: 'Hiçbir zaman etkilenmez', labelEn: 'It is never affected' }], correctId: 'a', explanation: 'Yüksek faiz yeni borcun finansman maliyetini artırabilir.', explanationEn: 'Higher rates can increase the financing cost of new borrowing.' },
    { prompt: 'Ekonomide bütün faiz oranları aynı mıdır?', promptEn: 'Are all interest rates in an economy identical?', choices: [{ id: 'a', label: 'Hayır; vade ve risk gibi özelliklere göre değişebilir', labelEn: 'No; they can differ by maturity, risk, and other features' }, { id: 'b', label: 'Evet, hepsi tek oran olmak zorundadır', labelEn: 'Yes, all must be one rate' }, { id: 'c', label: 'Yalnız borsada farklıdır', labelEn: 'Only in stock markets' }], correctId: 'a', explanation: 'Piyasa faizleri ürün, vade, kredi riski ve likidite gibi unsurlarla farklılaşabilir.', explanationEn: 'Market rates can differ with product, maturity, credit risk, and liquidity.' },
  ],
  sources: [ECONOMY_SOURCES.rates],
});

const centralBanks = createFoundationLesson({
  id: 'lesson.economy.central-banks.001',
  slug: 'merkez-bankasi-ne-yapar',
  conceptKey: 'economy.central_banks',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.explain-central-bank-role.foundation',
  title: 'Merkez bankası ne yapar?',
  titleEn: 'What does a central bank do?',
  objective: 'Merkez bankalarının para politikası ve fiyat istikrarı bağlamındaki temel rolünü açıklar.',
  objectiveEn: 'Explain the basic role of central banks in monetary policy and price stability.',
  minutes: 5,
  hook: 'Merkez bankası neden faiz kararı alır ve piyasalar bunu neden izler?',
  hookEn: 'Why does a central bank make rate decisions, and why do markets watch them?',
  explanation: 'Merkez bankaları ülkelerin para ve finans sistemlerinde temel kurumlardır. Birçok merkez bankası fiyat istikrarını desteklemek için para politikası araçlarını kullanır; bazıları ayrıca istihdam veya finansal istikrar gibi görevler taşır. Görevler ve araçlar ülkeye göre değişebilir.',
  explanationEn: 'Central banks are core institutions in monetary and financial systems. Many use monetary-policy tools to support price stability; some also have employment or financial-stability mandates. Mandates and tools vary across countries.',
  proExplanation: 'Politika faizi önemli bir araçtır ancak tek araç değildir. Rezerv düzenlemeleri, bilanço politikaları, likidite imkanları ve iletişim de finansal koşulları etkileyebilir.',
  proExplanationEn: 'The policy rate is important but not the only tool. Reserve frameworks, balance-sheet policies, liquidity facilities, and communication can also affect financial conditions.',
  misconception: 'Yaygın hata: Merkez bankasının doğrudan borsa fiyatlarını veya her kredi faizini tek tek belirlediğini düşünmek.',
  misconceptionEn: 'Common mistake: assuming a central bank directly sets stock prices or every individual loan rate.',
  takeaway: 'Merkez bankası finansal koşulları etkiler; ancak piyasalardaki her fiyatı doğrudan belirlemez.',
  takeawayEn: 'A central bank influences financial conditions but does not directly set every market price.',
  prerequisiteConceptKeys: ['economy.interest_rates'],
  relatedConceptKeys: ['economy.monetary_policy', 'economy.inflation'],
  visualAlt: 'Merkez bankası araçlarından faiz ve finansal koşullara uzanan sade etki şeması',
  visualAltEn: 'Simple diagram linking central-bank tools to interest rates and broader financial conditions',
  taskPrompt: 'Hangisi merkez bankasının rolünü daha doğru anlatır?',
  taskPromptEn: 'Which statement better describes the role of a central bank?',
  taskChoices: [
    { id: 'conditions', label: 'Para politikasıyla finansal koşulları ve fiyat istikrarını etkilemeye çalışır', labelEn: 'It uses monetary policy to influence financial conditions and price stability' },
    { id: 'stocks', label: 'Borsadaki her hisse fiyatını doğrudan belirler', labelEn: 'It directly sets every stock price' },
    { id: 'profits', label: 'Şirketlerin kârını garanti eder', labelEn: 'It guarantees company profits' },
  ],
  taskCorrectIds: ['conditions'],
  questions: [
    { prompt: 'Birçok merkez bankasının temel hedeflerinden biri nedir?', promptEn: 'What is one common objective of many central banks?', choices: [{ id: 'a', label: 'Fiyat istikrarını desteklemek', labelEn: 'Support price stability' }, { id: 'b', label: 'Her yatırımın getirisini sabitlemek', labelEn: 'Fix every investment return' }, { id: 'c', label: 'Tüm şirketleri yönetmek', labelEn: 'Manage every company' }], correctId: 'a', explanation: 'Fiyat istikrarı birçok merkez bankasının temel görevleri arasındadır.', explanationEn: 'Price stability is a core mandate for many central banks.' },
    { prompt: 'Merkez bankalarının görevleri her ülkede tamamen aynı mıdır?', promptEn: 'Are central-bank mandates identical in every country?', choices: [{ id: 'a', label: 'Hayır, görev ve araçlar değişebilir', labelEn: 'No, mandates and tools can differ' }, { id: 'b', label: 'Evet, zorunlu olarak aynıdır', labelEn: 'Yes, they must be identical' }, { id: 'c', label: 'Yalnız para biriminin rengi değişir', labelEn: 'Only the currency color changes' }], correctId: 'a', explanation: 'Kurumsal görevler ve politika çerçeveleri ülkeye göre farklılaşabilir.', explanationEn: 'Institutional mandates and policy frameworks can vary by country.' },
    { prompt: 'Merkez bankası borsadaki her fiyatı doğrudan belirler mi?', promptEn: 'Does a central bank directly set every stock-market price?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız büyük şirketlerde', labelEn: 'Only for large companies' }], correctId: 'a', explanation: 'Politika finansal koşulları etkileyebilir; piyasa fiyatları ise çok sayıda etken ve işlemle oluşur.', explanationEn: 'Policy can influence financial conditions, while market prices form through many factors and transactions.' },
  ],
  sources: [ECONOMY_SOURCES.centralBanks],
});

const monetaryPolicy = createFoundationLesson({
  id: 'lesson.economy.monetary-policy.001',
  slug: 'faiz-karari-ekonomiye-nasil-yansir',
  conceptKey: 'economy.monetary_policy',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.trace-monetary-policy.foundation',
  title: 'Faiz kararı ekonomiye nasıl yansır?',
  titleEn: 'How can a rate decision affect the economy?',
  objective: 'Politika faizinden finansal koşullar, talep ve enflasyona uzanan temel aktarım zincirini açıklar.',
  objectiveEn: 'Explain the basic transmission chain from policy rates to financial conditions, demand, and inflation.',
  minutes: 5,
  hook: 'Merkez bankası faizi değiştirdiğinde neden etkisi aynı gün her yerde görülmez?',
  hookEn: 'Why is a central-bank rate change not felt everywhere on the same day?',
  explanation: 'Para politikası ekonomiye bir zincir üzerinden yayılır. Politika faizi finansman koşullarını, kredi ve mevduat faizlerini, harcama ve tasarruf kararlarını etkileyebilir. Bunlar toplam talep ve zamanla fiyat baskıları üzerinde etkili olabilir. Etki gecikmeli, değişken ve koşullara bağlıdır.',
  explanationEn: 'Monetary policy spreads through the economy through a chain. The policy rate can affect financing conditions, lending and deposit rates, and spending and saving decisions. These can influence aggregate demand and, over time, price pressures. The effect is delayed, variable, and context-dependent.',
  proExplanation: 'Aktarım; bankacılık sistemi, borçluluk, kur, beklentiler, varlık fiyatları ve finansal koşullara göre güçlenebilir veya zayıflayabilir. Politika kararı tek başına mekanik sonuç üretmez.',
  proExplanationEn: 'Transmission can strengthen or weaken depending on banking conditions, leverage, exchange rates, expectations, asset prices, and broader financial conditions. A policy decision does not produce a mechanical guaranteed outcome.',
  misconception: 'Yaygın hata: Faiz artınca enflasyonun veya piyasa fiyatlarının ertesi gün kesin ve aynı yönde hareket edeceğini düşünmek.',
  misconceptionEn: 'Common mistake: assuming a rate increase makes inflation or market prices move with certainty in one direction the next day.',
  takeaway: 'Para politikası bir düğme değil, zaman içinde çalışan ve koşullara bağlı bir aktarım zinciridir.',
  takeawayEn: 'Monetary policy is not a switch; it is a context-dependent transmission chain that works over time.',
  prerequisiteConceptKeys: ['economy.central_banks', 'economy.interest_rates'],
  relatedConceptKeys: ['economy.inflation', 'economy.growth'],
  visualAlt: 'Politika faizinden kredi koşulları, harcama, talep ve enflasyona uzanan sade aktarım zinciri',
  visualAltEn: 'Simple transmission chain from policy rates to credit conditions, spending, demand, and inflation',
  taskPrompt: 'Para politikasının etkisini en doğru hangi zincir anlatır?',
  taskPromptEn: 'Which chain best describes monetary-policy transmission?',
  taskChoices: [
    { id: 'chain', label: 'Politika faizi → finansal koşullar → harcama/tasarruf → talep → fiyat baskıları', labelEn: 'Policy rate → financial conditions → spending/saving → demand → price pressures' },
    { id: 'instant', label: 'Politika faizi → ertesi gün kesin piyasa yönü', labelEn: 'Policy rate → guaranteed market direction the next day' },
    { id: 'none', label: 'Politika faizi → ekonomide hiçbir kanal yok', labelEn: 'Policy rate → no channel into the economy' },
  ],
  taskCorrectIds: ['chain'],
  questions: [
    { prompt: 'Para politikası neden gecikmeli etkiler gösterebilir?', promptEn: 'Why can monetary policy have delayed effects?', choices: [{ id: 'a', label: 'Finansal koşullar ve kararlar üzerinden zamanla yayıldığı için', labelEn: 'Because it spreads over time through financial conditions and decisions' }, { id: 'b', label: 'Hiçbir ekonomik kanal olmadığı için', labelEn: 'Because there are no economic channels' }, { id: 'c', label: 'Faiz verisi yalnız yılda bir açıklandığı için', labelEn: 'Because rate data is published only once a year' }], correctId: 'a', explanation: 'Kredi, tasarruf, harcama ve beklenti kanallarının ekonomiye yansıması zaman alabilir.', explanationEn: 'Credit, saving, spending, and expectation channels can take time to affect the economy.' },
    { prompt: 'Faiz artışı her piyasada aynı gün aynı sonucu garanti eder mi?', promptEn: 'Does a rate increase guarantee the same result in every market on the same day?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız hisse piyasasında', labelEn: 'Only in equities' }], correctId: 'a', explanation: 'Beklentiler ve mevcut koşullar sonucu değiştirebilir.', explanationEn: 'Expectations and prevailing conditions can change the outcome.' },
    { prompt: 'Para politikası hangi kararları etkileyebilir?', promptEn: 'Which decisions can monetary policy influence?', choices: [{ id: 'a', label: 'Borçlanma, tasarruf ve harcama kararlarını', labelEn: 'Borrowing, saving, and spending decisions' }, { id: 'b', label: 'Yalnız şirket logosunu', labelEn: 'Only company logos' }, { id: 'c', label: 'Yalnız borsa işlem saatini', labelEn: 'Only stock-market trading hours' }], correctId: 'a', explanation: 'Faiz ve finansman koşulları ekonomik kararların maliyetini ve teşviklerini etkileyebilir.', explanationEn: 'Interest and financing conditions can affect the costs and incentives behind economic decisions.' },
  ],
  sources: [ECONOMY_SOURCES.monetaryPolicy],
});

const growth = createFoundationLesson({
  id: 'lesson.economy.growth.001',
  slug: 'gsyh-buyume-ne-anlatir',
  conceptKey: 'economy.growth',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.explain-gdp-growth.foundation',
  title: 'GSYH ve ekonomik büyüme ne anlatır?',
  titleEn: 'What do GDP and economic growth tell us?',
  objective: 'GSYH ile ekonomide üretilen mal ve hizmetlerin toplam değeri arasındaki ilişkiyi açıklar.',
  objectiveEn: 'Explain how GDP relates to the value of goods and services produced in an economy.',
  minutes: 4,
  hook: 'Bir ekonominin “büyüdüğünü” söylediğimizde tam olarak ne büyüyor?',
  hookEn: 'When we say an economy is “growing,” what exactly is growing?',
  explanation: 'GSYH, belirli bir dönemde ekonomi içinde üretilen nihai mal ve hizmetlerin toplam değerini ölçmeye çalışır. Reel GSYH büyümesi, fiyat değişimlerinin etkisini ayırarak üretim miktarındaki değişimi anlamaya yardım eder. GSYH önemli bir göstergedir ancak gelir dağılımı, yaşam kalitesi veya her sektörün durumunu tek başına anlatmaz.',
  explanationEn: 'GDP seeks to measure the total value of final goods and services produced within an economy over a period. Real GDP growth helps isolate changes in production from price changes. GDP is important, but it does not by itself describe income distribution, quality of life, or every sector.',
  proExplanation: 'Nominal ve reel büyüme ayrımı, baz etkileri, stok değişimleri ve revizyonlar yorumda önemlidir. Tek çeyreklik veri yapısal trend yerine geçmez.',
  proExplanationEn: 'The distinction between nominal and real growth, base effects, inventory changes, and revisions matters. A single quarter does not establish a structural trend.',
  misconception: 'Yaygın hata: GSYH büyümesini toplumdaki herkesin gelirinin aynı oranda arttığı şeklinde yorumlamak.',
  misconceptionEn: 'Common mistake: interpreting GDP growth as everyone’s income rising by the same amount.',
  takeaway: 'GSYH ekonomideki toplam üretim faaliyetini ölçmeye yardım eder; refahın bütün boyutlarını tek başına açıklamaz.',
  takeawayEn: 'GDP helps measure aggregate production activity; it does not capture every dimension of well-being.',
  prerequisiteConceptKeys: ['economy.monetary_policy'],
  relatedConceptKeys: ['economy.business_cycle', 'economy.inflation'],
  visualAlt: 'Ekonomideki hane, şirket ve hizmet üretimini tek toplam üretim göstergesinde birleştiren sade GSYH şeması',
  visualAltEn: 'Simple GDP diagram combining household, business, and service production into aggregate economic output',
  taskPrompt: 'Reel GSYH büyümesi neyi anlamaya özellikle yardım eder?',
  taskPromptEn: 'What does real GDP growth especially help us understand?',
  taskChoices: [
    { id: 'real', label: 'Fiyat etkisini ayırarak üretim miktarındaki değişimi', labelEn: 'Changes in production after separating price effects' },
    { id: 'everyone', label: 'Herkesin gelirinin aynı oranda değiştiğini', labelEn: 'Everyone’s income changing by the same amount' },
    { id: 'stocks', label: 'Borsanın ertesi günkü kesin yönünü', labelEn: 'The stock market’s guaranteed direction tomorrow' },
  ],
  taskCorrectIds: ['real'],
  questions: [
    { prompt: 'GSYH en temel olarak neyi ölçmeye çalışır?', promptEn: 'What does GDP fundamentally seek to measure?', choices: [{ id: 'a', label: 'Ekonomide üretilen nihai mal ve hizmetlerin toplam değerini', labelEn: 'The total value of final goods and services produced in the economy' }, { id: 'b', label: 'Yalnız borsa değerini', labelEn: 'Only stock-market value' }, { id: 'c', label: 'Yalnız devlet harcamalarını', labelEn: 'Only government spending' }], correctId: 'a', explanation: 'GSYH ekonomideki toplam üretim faaliyetini ölçmek için kullanılan temel göstergelerden biridir.', explanationEn: 'GDP is a core measure of aggregate production activity.' },
    { prompt: 'Reel büyüme neden kullanılır?', promptEn: 'Why is real growth used?', choices: [{ id: 'a', label: 'Fiyat değişimlerinin etkisini ayırmaya yardım etmek için', labelEn: 'To help separate the effect of price changes' }, { id: 'b', label: 'Enflasyonu tamamen yok saymak için', labelEn: 'To pretend inflation does not exist' }, { id: 'c', label: 'Her şirketin kârını eşitlemek için', labelEn: 'To equalize every company’s profit' }], correctId: 'a', explanation: 'Reel ölçümler üretim miktarındaki değişimi daha iyi ayırmayı amaçlar.', explanationEn: 'Real measures aim to better isolate changes in production volume.' },
    { prompt: 'GSYH büyümesi herkesin gelirinin eşit arttığını gösterir mi?', promptEn: 'Does GDP growth show that everyone’s income rose equally?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız resesyonda', labelEn: 'Only in recessions' }], correctId: 'a', explanation: 'Toplam üretim büyümesi dağılım hakkında tek başına yeterli bilgi vermez.', explanationEn: 'Aggregate production growth does not by itself describe distribution.' },
  ],
  sources: [ECONOMY_SOURCES.gdp],
});

const businessCycle = createFoundationLesson({
  id: 'lesson.economy.business-cycle.001',
  slug: 'ekonomik-dongu-resesyon',
  conceptKey: 'economy.business_cycle',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.explain-business-cycle.foundation',
  title: 'Ekonomik döngü ve resesyon nedir?',
  titleEn: 'What are business cycles and recessions?',
  objective: 'Ekonomik genişleme ve daralma dönemlerini tek bir veri noktasından ayırarak açıklar.',
  objectiveEn: 'Explain economic expansions and contractions without reducing them to a single data point.',
  minutes: 5,
  hook: 'Ekonomi bir çeyrek zayıfladı diye otomatik olarak resesyon mu olur?',
  hookEn: 'Does one weak quarter automatically mean a recession?',
  explanation: 'Ekonomik faaliyet zaman içinde hızlanıp yavaşlayabilir. Genişleme dönemlerinde üretim ve istihdam genellikle güçlenir; daralma dönemlerinde ekonomik faaliyet yaygın biçimde zayıflayabilir. Resesyonu değerlendirmek için süre, yaygınlık ve derinlik gibi birden fazla göstergeye bakılır; tek bir sayı her durumda yeterli değildir.',
  explanationEn: 'Economic activity can accelerate and slow over time. During expansions, production and employment often strengthen; during contractions, activity can weaken broadly. Recession assessment considers multiple dimensions such as duration, breadth, and depth; one number is not always sufficient.',
  proExplanation: 'İş döngüsü tarihlemesi geriye dönük revizyonlar, gelir ve üretim göstergeleri, istihdam ve satış verileriyle birlikte değerlendirilebilir. Basit “iki negatif çeyrek” kuralı her kurumsal tanımın yerini tutmaz.',
  proExplanationEn: 'Business-cycle dating can consider revisions plus income, production, employment, and sales indicators. A simple “two negative quarters” rule does not replace every institutional recession definition.',
  misconception: 'Yaygın hata: Resesyonu her durumda yalnız iki negatif GSYH çeyreğiyle tanımlamak.',
  misconceptionEn: 'Common mistake: defining every recession only as two negative GDP quarters.',
  takeaway: 'Ekonomik döngü genişleme ve daralma dönemlerinden oluşur; resesyon değerlendirmesi tek veriden daha geniştir.',
  takeawayEn: 'Business cycles include expansions and contractions; recession assessment is broader than one data point.',
  prerequisiteConceptKeys: ['economy.growth'],
  relatedConceptKeys: ['economy.monetary_policy', 'economy.inflation'],
  visualAlt: 'Ekonomik genişleme, tepe, daralma ve toparlanma evrelerini gösteren sade döngü şeması',
  visualAltEn: 'Simple cycle diagram showing expansion, peak, contraction, and recovery phases',
  taskPrompt: 'Bir resesyon değerlendirmesinde daha sağlıklı yaklaşım hangisidir?',
  taskPromptEn: 'Which is a healthier approach when assessing a recession?',
  taskChoices: [
    { id: 'broad', label: 'Süre, yaygınlık ve farklı ekonomik göstergeleri birlikte değerlendirmek', labelEn: 'Assess duration, breadth, and multiple economic indicators together' },
    { id: 'single', label: 'Tek bir günlük piyasa hareketine bakmak', labelEn: 'Use one day of market movement' },
    { id: 'automatic', label: 'Tek bir zayıf veriyi otomatik resesyon saymak', labelEn: 'Automatically call one weak data point a recession' },
  ],
  taskCorrectIds: ['broad'],
  questions: [
    { prompt: 'Ekonomik genişleme döneminde ne genellikle güçlenebilir?', promptEn: 'What can generally strengthen during an economic expansion?', choices: [{ id: 'a', label: 'Üretim ve ekonomik faaliyet', labelEn: 'Production and economic activity' }, { id: 'b', label: 'Her zaman bütün fiyatlar düşer', labelEn: 'All prices always fall' }, { id: 'c', label: 'Ekonomik veri yayınları durur', labelEn: 'Economic data releases stop' }], correctId: 'a', explanation: 'Genişleme, ekonomik faaliyetin genel olarak güçlendiği dönemi ifade eder.', explanationEn: 'Expansion refers to a period when economic activity generally strengthens.' },
    { prompt: 'Resesyon her durumda tek bir veriyle belirlenir mi?', promptEn: 'Is a recession always determined by one single data point?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız borsa verisiyle', labelEn: 'Only with stock-market data' }], correctId: 'a', explanation: 'Değerlendirmede ekonomik zayıflığın süresi, yaygınlığı ve derinliği gibi boyutlar kullanılabilir.', explanationEn: 'Assessment can consider dimensions such as duration, breadth, and depth of economic weakness.' },
    { prompt: '“İki negatif çeyrek” kuralı her resmî tanımın yerini tutar mı?', promptEn: 'Does the “two negative quarters” rule replace every official recession definition?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız enflasyon yüksekse', labelEn: 'Only when inflation is high' }], correctId: 'a', explanation: 'Bazı kurumlar daha geniş bir ekonomik gösterge seti ve farklı ölçütler kullanır.', explanationEn: 'Some institutions use broader sets of economic indicators and different criteria.' },
  ],
  sources: [ECONOMY_SOURCES.businessCycle],
});

export const ECONOMY_FOUNDATION_LESSONS = [
  inflation,
  interestRates,
  centralBanks,
  monetaryPolicy,
  growth,
  businessCycle,
] as const;
