import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { ECONOMY_EXPANSION_SOURCES } from './economyExpansionSources';

const laborMarket = createFoundationLesson({
  id: 'lesson.economy.labor-market.001',
  slug: 'issizlik-verisi-ne-anlatir',
  conceptKey: 'economy.labor_market',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.read-labor-market.foundation',
  title: 'İşsizlik verisi ne anlatır?',
  titleEn: 'What does unemployment data tell us?',
  objective: 'İşsizlik oranı ile işgücüne katılım ve istihdamın aynı kavram olmadığını açıklar.',
  objectiveEn: 'Explain why unemployment, labor-force participation, and employment are different concepts.',
  minutes: 5,
  hook: 'İşsizlik oranı düştüğünde herkesin iş bulduğu sonucuna varabilir miyiz?',
  hookEn: 'If unemployment falls, can we conclude that everyone found a job?',
  explanation: 'İşsizlik oranı, işgücünde olup işi olmayan ve aktif olarak iş arayan kişilerin oranını ölçmeye çalışır. İşgücüne katılım ise çalışma çağındaki insanların ne kadarının çalıştığını veya iş aradığını gösterir. Bu nedenle işsizlik oranındaki düşüş bazen daha fazla istihdamı, bazen de işgücünden çıkışı yansıtabilir; tek gösterge yeterli değildir.',
  explanationEn: 'The unemployment rate seeks to measure the share of the labor force that has no job and is actively seeking work. Labor-force participation shows how many working-age people are working or looking for work. A lower unemployment rate can reflect more employment or people leaving the labor force, so one measure alone is not enough.',
  proExplanation: 'İşgücü verileri örneklem, tanım ve revizyonlara tabidir. Bordro istihdamı, çalışma saatleri, ücretler, iş ilanları ve katılım oranı birlikte daha güçlü bağlam sağlar.',
  proExplanationEn: 'Labor-market data is subject to sampling, definitions, and revisions. Payrolls, hours worked, wages, vacancies, and participation can provide stronger context together.',
  misconception: 'Yaygın hata: İşsizlik oranı düştüğünde otomatik olarak istihdamın aynı ölçüde arttığını varsaymak.',
  misconceptionEn: 'Common mistake: assuming a lower unemployment rate automatically means employment rose by the same amount.',
  takeaway: 'İşgücü piyasasını tek oranla değil; işsizlik, istihdam ve katılımı birlikte okuyarak değerlendir.',
  takeawayEn: 'Read unemployment, employment, and participation together rather than relying on one labor-market rate.',
  prerequisiteConceptKeys: ['economy.business_cycle'],
  relatedConceptKeys: ['economy.growth', 'economy.indicators'],
  visualAlt: 'İstihdam, işsiz ve işgücü dışında kalan grupları ayıran sade işgücü şeması',
  visualAltEn: 'Simple labor-force diagram separating employed, unemployed, and people outside the labor force',
  taskPrompt: 'İşsizlik oranı düşerken istihdam da düşüyorsa hangi ek veri özellikle önemlidir?',
  taskPromptEn: 'If unemployment falls while employment also falls, which extra measure is especially useful?',
  taskChoices: [
    { id: 'participation', label: 'İşgücüne katılım oranı', labelEn: 'Labor-force participation rate' },
    { id: 'logo', label: 'Şirket logolarının sayısı', labelEn: 'The number of company logos' },
    { id: 'spread', label: 'Tek bir hissenin spreadi', labelEn: 'The spread of one stock' },
  ],
  taskCorrectIds: ['participation'],
  questions: [
    { prompt: 'İşsiz sayılmak için temel olarak hangi durum gerekir?', promptEn: 'What condition is generally required to be counted as unemployed?', choices: [{ id: 'a', label: 'İşi olmamak ve aktif olarak iş aramak', labelEn: 'Having no job and actively seeking work' }, { id: 'b', label: 'Çalışma çağında olmak yeterlidir', labelEn: 'Being working age is enough' }, { id: 'c', label: 'Borsada işlem yapmamak', labelEn: 'Not trading stocks' }], correctId: 'a', explanation: 'İşsizlik ölçümü işgücü içinde olup iş arayan kişilere odaklanır.', explanationEn: 'Unemployment measures focus on people in the labor force who are seeking work.' },
    { prompt: 'İşsizlik oranı tek başına işgücü piyasasının tamamını anlatır mı?', promptEn: 'Does the unemployment rate alone describe the whole labor market?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız resesyonda', labelEn: 'Only in recessions' }], correctId: 'a', explanation: 'İstihdam ve katılım gibi diğer göstergeler ek bağlam sağlar.', explanationEn: 'Employment and participation provide additional context.' },
    { prompt: 'İşgücüne katılım neyi anlamaya yardım eder?', promptEn: 'What does labor-force participation help us understand?', choices: [{ id: 'a', label: 'Çalışan veya iş arayan nüfusun payını', labelEn: 'The share of people working or seeking work' }, { id: 'b', label: 'Yalnız ücret seviyesini', labelEn: 'Only wage levels' }, { id: 'c', label: 'Borsa hacmini', labelEn: 'Stock-market volume' }], correctId: 'a', explanation: 'Katılım oranı insanların işgücüne dahil olup olmadığını gösterir.', explanationEn: 'Participation shows whether people are part of the labor force.' },
  ],
  sources: [ECONOMY_EXPANSION_SOURCES.labor],
});

const fiscalPolicy = createFoundationLesson({
  id: 'lesson.economy.fiscal-policy.001',
  slug: 'maliye-politikasi-nedir',
  conceptKey: 'economy.fiscal_policy',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.explain-fiscal-policy.foundation',
  title: 'Maliye politikası nedir?',
  titleEn: 'What is fiscal policy?',
  objective: 'Kamu harcamaları ve vergilerin ekonomik faaliyet üzerindeki temel rolünü açıklar.',
  objectiveEn: 'Explain the basic role of government spending and taxes in economic activity.',
  minutes: 5,
  hook: 'Ekonomiyi yalnız merkez bankası mı etkiler?',
  hookEn: 'Is the central bank the only institution that influences the economy?',
  explanation: 'Maliye politikası, hükümetin kamu harcamaları ve vergiler yoluyla ekonomi üzerindeki etkisini anlatır. Harcamaların artırılması veya vergilerin azaltılması bazı koşullarda talebi destekleyebilir; ters yöndeki adımlar talebi yavaşlatabilir. Etki büyüklüğü ekonominin durumu, finansman yöntemi ve uygulamanın hedefi gibi faktörlere bağlıdır.',
  explanationEn: 'Fiscal policy describes how government spending and taxation affect the economy. Higher spending or lower taxes can support demand in some conditions, while the opposite can restrain it. The size of the effect depends on the economic environment, financing, and policy design.',
  proExplanation: 'Mali çarpanlar sabit değildir. Ekonomik boşluk, para politikası, ithalat eğilimi, borç sürdürülebilirliği ve harcama kompozisyonu etkinin yönünü ve gücünü değiştirebilir.',
  proExplanationEn: 'Fiscal multipliers are not fixed. Economic slack, monetary policy, import propensity, debt sustainability, and spending composition can change the strength and direction of effects.',
  misconception: 'Yaygın hata: Her kamu harcamasının ekonomiyi aynı miktarda büyüttüğünü veya her vergi indiriminin aynı etkiyi yarattığını düşünmek.',
  misconceptionEn: 'Common mistake: assuming every unit of public spending or every tax cut has the same economic effect.',
  takeaway: 'Maliye politikası kamu harcamaları ve vergiler üzerinden çalışır; etkisi koşullara ve tasarıma bağlıdır.',
  takeawayEn: 'Fiscal policy works through public spending and taxes, with effects that depend on design and economic conditions.',
  prerequisiteConceptKeys: ['economy.growth'],
  relatedConceptKeys: ['economy.business_cycle', 'economy.monetary_policy'],
  visualAlt: 'Vergi ve kamu harcamasından hane, şirket ve toplam talebe uzanan sade maliye politikası akışı',
  visualAltEn: 'Simple fiscal-policy flow linking taxes and government spending to households, firms, and aggregate demand',
  taskPrompt: 'Hangisi maliye politikasının temel araçlarından biridir?',
  taskPromptEn: 'Which is a basic fiscal-policy tool?',
  taskChoices: [
    { id: 'tax', label: 'Vergiler ve kamu harcamaları', labelEn: 'Taxes and government spending' },
    { id: 'candle', label: 'Mum grafik renkleri', labelEn: 'Candlestick colors' },
    { id: 'spread', label: 'Tek bir piyasanın bid-ask spreadi', labelEn: 'One market’s bid-ask spread' },
  ],
  taskCorrectIds: ['tax'],
  questions: [
    { prompt: 'Maliye politikası hangi iki ana kanal üzerinden çalışır?', promptEn: 'Through which two main channels does fiscal policy work?', choices: [{ id: 'a', label: 'Vergiler ve kamu harcamaları', labelEn: 'Taxes and government spending' }, { id: 'b', label: 'Bid ve ask', labelEn: 'Bid and ask' }, { id: 'c', label: 'Mum ve trend', labelEn: 'Candles and trend' }], correctId: 'a', explanation: 'Maliye politikası kamu bütçesinin gelir ve harcama taraflarını kullanır.', explanationEn: 'Fiscal policy uses the revenue and spending sides of the public budget.' },
    { prompt: 'Her kamu harcamasının ekonomik etkisi aynı mıdır?', promptEn: 'Does every type of government spending have the same economic effect?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız büyüme yüksekse', labelEn: 'Only when growth is high' }], correctId: 'a', explanation: 'Harcamanın türü ve ekonomik koşullar etkinin gücünü değiştirebilir.', explanationEn: 'Spending composition and economic conditions can change the effect.' },
    { prompt: 'Maliye politikası ile para politikası aynı şey midir?', promptEn: 'Are fiscal policy and monetary policy the same thing?', choices: [{ id: 'a', label: 'Hayır; kurumları ve araçları farklıdır', labelEn: 'No; their institutions and tools differ' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece adları farklıdır', labelEn: 'Only their names differ' }], correctId: 'a', explanation: 'Maliye politikası bütçe araçlarını; para politikası merkez bankası araçlarını kullanır.', explanationEn: 'Fiscal policy uses budget tools, while monetary policy uses central-bank tools.' },
  ],
  sources: [ECONOMY_EXPANSION_SOURCES.fiscal],
});

const exchangeRates = createFoundationLesson({
  id: 'lesson.economy.exchange-rates.001',
  slug: 'doviz-kuru-neden-degisir',
  conceptKey: 'economy.exchange_rates',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.explain-exchange-rates.foundation',
  title: 'Döviz kuru neden değişir?',
  titleEn: 'Why do exchange rates change?',
  objective: 'Döviz kurunu iki para biriminin göreli fiyatı olarak açıklar.',
  objectiveEn: 'Explain an exchange rate as the relative price between two currencies.',
  minutes: 5,
  hook: 'Bir para birimi “güçlendi” dediğimizde neye göre güçlenmiştir?',
  hookEn: 'When we say a currency strengthened, strengthened relative to what?',
  explanation: 'Döviz kuru, bir para biriminin diğerine göre fiyatıdır. Faiz farkları, enflasyon beklentileri, ticaret ve sermaye akımları, risk algısı ve politika beklentileri talep ile arzı etkileyebilir. Bir para biriminin değer kazanması her ekonomik kesim için aynı sonucu yaratmaz; ithalatçı, ihracatçı ve borçlu üzerindeki etkiler farklı olabilir.',
  explanationEn: 'An exchange rate is the price of one currency relative to another. Interest differentials, inflation expectations, trade and capital flows, risk sentiment, and policy expectations can affect supply and demand. Currency appreciation does not affect every part of the economy in the same way; importers, exporters, and borrowers can be affected differently.',
  proExplanation: 'Kur hareketleri nominal ve reel efektif kur, faiz paritesi, risk primi, rezerv politikası ve sermaye kontrolleri gibi çerçevelerle daha ayrıntılı incelenebilir. Tek bir faktör tüm dönemleri açıklamaz.',
  proExplanationEn: 'Exchange-rate moves can be studied through nominal and real effective rates, interest parity, risk premia, reserve policy, and capital controls. No single factor explains every period.',
  misconception: 'Yaygın hata: Döviz kurunun yalnız bir ekonomik veri veya yalnız merkez bankası kararıyla belirlendiğini düşünmek.',
  misconceptionEn: 'Common mistake: assuming an exchange rate is determined by one data release or one central-bank decision alone.',
  takeaway: 'Kur iki paranın göreli fiyatıdır; çok sayıda ekonomik beklenti ve akış birlikte etkiler.',
  takeawayEn: 'An exchange rate is a relative price shaped by multiple economic expectations and flows.',
  prerequisiteConceptKeys: ['economy.interest_rates', 'economy.inflation'],
  relatedConceptKeys: ['economy.monetary_policy', 'economy.indicators'],
  visualAlt: 'İki para birimi arasındaki göreli fiyatı ve onu etkileyen faiz, enflasyon ve sermaye akımlarını gösteren sade şema',
  visualAltEn: 'Simple diagram showing the relative price of two currencies and influences from rates, inflation, and capital flows',
  taskPrompt: 'EUR/USD kuru yükseliyorsa en temel yorum hangisidir?',
  taskPromptEn: 'If EUR/USD rises, what is the most basic interpretation?',
  taskChoices: [
    { id: 'relative', label: 'Euro dolar karşısında göreli olarak değer kazanmıştır', labelEn: 'The euro has appreciated relative to the dollar' },
    { id: 'all', label: 'Euro bütün varlıklara karşı kesin değer kazanmıştır', labelEn: 'The euro has certainly appreciated against every asset' },
    { id: 'inflation', label: 'Enflasyon kesin sıfırlanmıştır', labelEn: 'Inflation has certainly fallen to zero' },
  ],
  taskCorrectIds: ['relative'],
  questions: [
    { prompt: 'Döviz kuru en temel olarak nedir?', promptEn: 'What is an exchange rate at its core?', choices: [{ id: 'a', label: 'Bir para biriminin diğerine göre fiyatı', labelEn: 'The price of one currency relative to another' }, { id: 'b', label: 'Bir şirketin kârı', labelEn: 'A company’s profit' }, { id: 'c', label: 'Bir tahvilin vadesi', labelEn: 'A bond’s maturity' }], correctId: 'a', explanation: 'Kur her zaman iki para birimi arasındaki göreli değeri ifade eder.', explanationEn: 'An exchange rate always expresses relative value between currencies.' },
    { prompt: 'Döviz kurunu yalnız tek bir faktör mü belirler?', promptEn: 'Is an exchange rate determined by only one factor?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız hafta sonları', labelEn: 'Only on weekends' }], correctId: 'a', explanation: 'Faiz, enflasyon, risk algısı ve sermaye akımları gibi birçok etken rol oynayabilir.', explanationEn: 'Rates, inflation, risk sentiment, and capital flows can all matter.' },
    { prompt: 'Bir para biriminin güçlenmesi ekonomide herkesi aynı şekilde etkiler mi?', promptEn: 'Does a stronger currency affect everyone in the economy in the same way?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız ihracatçılar etkilenir', labelEn: 'Only exporters are affected' }], correctId: 'a', explanation: 'İthalat, ihracat ve borç yapısına göre etkiler farklılaşabilir.', explanationEn: 'Effects can differ across imports, exports, and debt structures.' },
  ],
  sources: [ECONOMY_EXPANSION_SOURCES.exchangeRates],
});

const productivity = createFoundationLesson({
  id: 'lesson.economy.productivity.001',
  slug: 'verimlilik-neden-onemlidir',
  conceptKey: 'economy.productivity',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.explain-productivity.foundation',
  title: 'Verimlilik neden uzun vadede önemlidir?',
  titleEn: 'Why does productivity matter in the long run?',
  objective: 'Verimliliği kullanılan kaynak başına üretilen çıktı ile ilişkilendirir.',
  objectiveEn: 'Relate productivity to output produced per unit of input.',
  minutes: 4,
  hook: 'Aynı çalışan ve aynı süreyle daha fazla üretmek ekonomiyi nasıl değiştirir?',
  hookEn: 'How does producing more with the same workers and time change an economy?',
  explanation: 'Verimlilik, belirli miktarda emek, zaman veya sermaye ile ne kadar çıktı üretilebildiğini anlatır. Teknoloji, beceri, altyapı ve daha iyi süreçler verimliliği artırabilir. Uzun vadede verimlilik artışı, kişi başına gelir ve yaşam standardının sürdürülebilir yükselişi için önemli kaynaklardan biridir.',
  explanationEn: 'Productivity describes how much output can be produced with a given amount of labor, time, or capital. Technology, skills, infrastructure, and better processes can raise productivity. Over the long run, productivity growth is an important source of sustainable gains in income per person and living standards.',
  proExplanation: 'İşgücü verimliliği ile toplam faktör verimliliği aynı ölçüm değildir. Döngüsel kapasite kullanımı ve sektör kompozisyonu kısa dönem ölçümleri etkileyebilir.',
  proExplanationEn: 'Labor productivity and total factor productivity are not the same measure. Cyclical capacity utilization and sector composition can affect short-term readings.',
  misconception: 'Yaygın hata: Verimliliği yalnız daha uzun saat çalışmak veya çalışan sayısını artırmak sanmak.',
  misconceptionEn: 'Common mistake: treating productivity as simply working longer hours or adding more workers.',
  takeaway: 'Verimlilik, daha fazla kaynak kullanmaktan çok mevcut kaynaklarla daha fazla değer üretme kapasitesidir.',
  takeawayEn: 'Productivity is about producing more value with available resources, not simply using more resources.',
  prerequisiteConceptKeys: ['economy.growth'],
  relatedConceptKeys: ['economy.labor_market', 'economy.real_nominal'],
  visualAlt: 'Aynı emek ve zaman girdisiyle daha fazla çıktı üreten iki sistemi karşılaştıran sade verimlilik şeması',
  visualAltEn: 'Simple productivity diagram comparing two systems that use the same labor and time but produce different output',
  taskPrompt: 'Hangisi verimlilik artışını daha iyi anlatır?',
  taskPromptEn: 'Which better describes a productivity gain?',
  taskChoices: [
    { id: 'more-output', label: 'Aynı kaynaklarla daha fazla çıktı üretmek', labelEn: 'Producing more output with the same resources' },
    { id: 'more-hours', label: 'Yalnız çalışma saatlerini iki katına çıkarmak', labelEn: 'Only doubling working hours' },
    { id: 'more-price', label: 'Ürünün etiket fiyatını artırmak', labelEn: 'Raising the product’s sticker price' },
  ],
  taskCorrectIds: ['more-output'],
  questions: [
    { prompt: 'Verimlilik neyi karşılaştırır?', promptEn: 'What does productivity compare?', choices: [{ id: 'a', label: 'Üretilen çıktı ile kullanılan kaynakları', labelEn: 'Output produced relative to inputs used' }, { id: 'b', label: 'Yalnız ürün fiyatlarını', labelEn: 'Only product prices' }, { id: 'c', label: 'Yalnız çalışan sayısını', labelEn: 'Only employee count' }], correctId: 'a', explanation: 'Verimlilik, kaynak başına çıktı üretme kapasitesiyle ilgilidir.', explanationEn: 'Productivity concerns the ability to produce output per unit of input.' },
    { prompt: 'Teknoloji verimliliği nasıl etkileyebilir?', promptEn: 'How can technology affect productivity?', choices: [{ id: 'a', label: 'Aynı kaynaklarla daha fazla veya daha kaliteli çıktı sağlayabilir', labelEn: 'It can enable more or better output with the same resources' }, { id: 'b', label: 'Verimlilikle ilgisi yoktur', labelEn: 'It is unrelated to productivity' }, { id: 'c', label: 'Yalnız fiyatları değiştirir', labelEn: 'It only changes prices' }], correctId: 'a', explanation: 'Teknoloji üretim süreçlerinin etkinliğini artırabilir.', explanationEn: 'Technology can improve the efficiency of production processes.' },
    { prompt: 'Daha uzun çalışmak tek başına verimlilik artışı mıdır?', promptEn: 'Is working longer by itself necessarily a productivity gain?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Her zaman evet', labelEn: 'Always yes' }, { id: 'c', label: 'Yalnız enflasyon düşükse', labelEn: 'Only when inflation is low' }], correctId: 'a', explanation: 'Daha fazla girdi kullanmak, girdi başına üretimin arttığı anlamına gelmez.', explanationEn: 'Using more input does not mean output per unit of input improved.' },
  ],
  sources: [ECONOMY_EXPANSION_SOURCES.productivity],
});

const indicators = createFoundationLesson({
  id: 'lesson.economy.indicators.001',
  slug: 'ekonomik-veri-nasil-okunur',
  conceptKey: 'economy.indicators',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.read-economic-data.foundation',
  title: 'Ekonomik veri nasıl doğru okunur?',
  titleEn: 'How should economic data be read?',
  objective: 'Bir ekonomik veriyi seviye, değişim, beklenti, önceki değer ve revizyon bağlamında okur.',
  objectiveEn: 'Read an economic release using level, change, expectations, prior values, and revisions.',
  minutes: 5,
  hook: 'Bir veri “iyi” geldiğinde piyasa neden bazen ters yönde hareket eder?',
  hookEn: 'Why can markets move the “wrong” way after a seemingly good data release?',
  explanation: 'Ekonomik veri yalnız açıklanan sayı değildir. Piyasalar çoğu zaman gerçekleşen değeri beklenti, önceki veri ve önceki verideki revizyonlarla birlikte değerlendirir. Ayrıca aylık değişim ile yıllık değişim veya nominal ile reel ölçüm aynı şey değildir. Bu nedenle başlığı değil, ölçümün neyi ve hangi dönemi anlattığını okumak gerekir.',
  explanationEn: 'An economic release is more than the headline number. Markets often compare the actual value with expectations, the previous reading, and revisions to prior data. Monthly and annual changes, or nominal and real measures, are not the same. Read what the measure represents and which period it covers.',
  proExplanation: 'Sürpriz büyüklüğü, dağılım içindeki konum, baz etkisi, mevsimsellik, revizyon riski ve eşzamanlı diğer veriler piyasa yorumunu değiştirebilir. Veri açıklaması tek başına işlem sinyali değildir.',
  proExplanationEn: 'Surprise size, distributional context, base effects, seasonality, revision risk, and simultaneous releases can change interpretation. A data release is not a standalone trade signal.',
  misconception: 'Yaygın hata: Gerçekleşen sayının yönünü tek başına “iyi” veya “kötü” diye etiketlemek.',
  misconceptionEn: 'Common mistake: labeling the direction of one headline number as simply “good” or “bad.”',
  takeaway: 'Ekonomik veriyi gerçekleşen, beklenti, önceki değer, revizyon ve ölçüm dönemiyle birlikte oku.',
  takeawayEn: 'Read economic data together with actual, expected, prior, revised, and time-period context.',
  prerequisiteConceptKeys: ['economy.growth', 'economy.inflation'],
  relatedConceptKeys: ['evidence.data_quality', 'evidence.freshness'],
  visualAlt: 'Gerçekleşen, beklenti, önceki ve revize değerleri yan yana karşılaştıran sade ekonomik veri kartı',
  visualAltEn: 'Simple economic-release card comparing actual, expected, previous, and revised values',
  taskPrompt: 'Bir ekonomik veri açıklamasında hangi karşılaştırma daha sağlıklıdır?',
  taskPromptEn: 'Which comparison is healthier when reading an economic release?',
  taskChoices: [
    { id: 'context', label: 'Gerçekleşen + beklenti + önceki/revize değer', labelEn: 'Actual + expected + previous/revised value' },
    { id: 'headline', label: 'Yalnız başlıktaki tek sayı', labelEn: 'Only the single headline number' },
    { id: 'color', label: 'Grafik ekranının rengi', labelEn: 'The color of the chart screen' },
  ],
  taskCorrectIds: ['context'],
  questions: [
    { prompt: 'Piyasalar ekonomik veriyi çoğu zaman neyle karşılaştırır?', promptEn: 'What do markets often compare an economic release with?', choices: [{ id: 'a', label: 'Beklenti ve önceki değerlerle', labelEn: 'Expectations and prior readings' }, { id: 'b', label: 'Yalnız şirket logosuyla', labelEn: 'Only company logos' }, { id: 'c', label: 'Yalnız haftanın günüyle', labelEn: 'Only the day of the week' }], correctId: 'a', explanation: 'Beklentiden sapma ve önceki verinin bağlamı sürprizi anlamaya yardım eder.', explanationEn: 'Deviation from expectations and prior context help interpret the surprise.' },
    { prompt: 'Önceki veride revizyon önemli olabilir mi?', promptEn: 'Can revisions to prior data matter?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır, hiçbir zaman', labelEn: 'Never' }, { id: 'c', label: 'Yalnız borsada', labelEn: 'Only in stock markets' }], correctId: 'a', explanation: 'Revizyon geçmiş ekonomik durum hakkındaki resmi değiştirebilir.', explanationEn: 'Revisions can change the picture of prior economic conditions.' },
    { prompt: 'Tek ekonomik veri açıklaması otomatik işlem sinyali midir?', promptEn: 'Is one economic release automatically a trade signal?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Her zaman evet', labelEn: 'Always yes' }, { id: 'c', label: 'Beklentiden farklıysa kesin evet', labelEn: 'Definitely yes if it differs from expectations' }], correctId: 'a', explanation: 'Piyasa tepkisi beklenti, konumlanma ve diğer bağlama bağlıdır.', explanationEn: 'Market reaction depends on expectations, positioning, and broader context.' },
  ],
  sources: [ECONOMY_EXPANSION_SOURCES.indicators],
});

const realNominal = createFoundationLesson({
  id: 'lesson.economy.real-nominal.001',
  slug: 'reel-ve-nominal-farki',
  conceptKey: 'economy.real_nominal',
  skillId: 'skill.economy-foundations',
  competencyId: 'competency.distinguish-real-nominal.foundation',
  title: 'Reel ve nominal farkı nedir?',
  titleEn: 'What is the difference between real and nominal?',
  objective: 'Nominal değer ile fiyat değişiminden arındırılmış reel değeri ayırt eder.',
  objectiveEn: 'Distinguish nominal values from real values adjusted for price changes.',
  minutes: 4,
  hook: 'Maaşın %10 arttı ama fiyatlar %15 yükseldiyse gerçekten daha mı zenginsin?',
  hookEn: 'If your salary rises 10% but prices rise 15%, are you really better off?',
  explanation: 'Nominal değer, ölçülen para miktarını cari fiyatlarla gösterir. Reel değer ise fiyat düzeyindeki değişimin etkisini ayırmaya çalışır. Bu ayrım ücret, faiz, GSYH ve yatırım getirisi gibi birçok alanda önemlidir; nominal artış satın alma gücünün de arttığı anlamına gelmeyebilir.',
  explanationEn: 'A nominal value reports a money amount at current prices. A real value seeks to remove the effect of changes in the price level. This distinction matters for wages, interest rates, GDP, and investment returns; a nominal increase does not necessarily mean purchasing power increased.',
  proExplanation: 'Reel hesaplama kullanılan deflatör veya enflasyon ölçüsüne bağlıdır. Ex-post reel değer ile beklenen enflasyona dayalı ex-ante reel değer aynı değildir.',
  proExplanationEn: 'Real calculations depend on the deflator or inflation measure used. Ex-post real values and ex-ante values based on expected inflation are different concepts.',
  misconception: 'Yaygın hata: Para cinsinden artışı otomatik olarak gerçek satın alma gücü artışı saymak.',
  misconceptionEn: 'Common mistake: treating a rise in money terms as an automatic increase in real purchasing power.',
  takeaway: 'Nominal sayı cebindeki para miktarını; reel sayı fiyat değişimini dikkate aldıktan sonraki ekonomik gücü anlamaya yardım eder.',
  takeawayEn: 'Nominal values show money amounts; real values help interpret economic power after accounting for price changes.',
  prerequisiteConceptKeys: ['economy.inflation'],
  relatedConceptKeys: ['economy.interest_rates', 'economy.growth', 'economy.productivity'],
  visualAlt: 'Nominal yüzde artışı ile enflasyon sonrası reel satın alma gücünü karşılaştıran sade şema',
  visualAltEn: 'Simple diagram comparing nominal percentage growth with real purchasing power after inflation',
  taskPrompt: 'Maaş %8 artarken fiyatlar yaklaşık %10 artıyorsa en doğru genel yorum hangisidir?',
  taskPromptEn: 'If salary rises about 8% while prices rise about 10%, what is the best general interpretation?',
  taskChoices: [
    { id: 'real-down', label: 'Nominal maaş artmıştır ama reel satın alma gücü gerilemiş olabilir', labelEn: 'Nominal salary rose, but real purchasing power may have fallen' },
    { id: 'richer', label: 'Kesin olarak %8 daha zenginsin', labelEn: 'You are definitely 8% richer' },
    { id: 'none', label: 'Enflasyon maaşın reel değerini etkilemez', labelEn: 'Inflation does not affect the real value of salary' },
  ],
  taskCorrectIds: ['real-down'],
  questions: [
    { prompt: 'Nominal değer neyi gösterir?', promptEn: 'What does a nominal value show?', choices: [{ id: 'a', label: 'Cari fiyatlarla para cinsinden değeri', labelEn: 'The money value at current prices' }, { id: 'b', label: 'Her zaman enflasyondan arındırılmış değeri', labelEn: 'A value always adjusted for inflation' }, { id: 'c', label: 'Yalnız fiziksel üretim miktarını', labelEn: 'Only physical output volume' }], correctId: 'a', explanation: 'Nominal ölçüm doğrudan para miktarını cari fiyatlarla ifade eder.', explanationEn: 'Nominal measurement expresses the money amount at current prices.' },
    { prompt: 'Reel değer neden kullanılır?', promptEn: 'Why are real values used?', choices: [{ id: 'a', label: 'Fiyat düzeyi değişiminin etkisini ayırmaya yardım etmek için', labelEn: 'To help separate the effect of price-level changes' }, { id: 'b', label: 'Bütün riskleri yok etmek için', labelEn: 'To remove all risks' }, { id: 'c', label: 'Nominal veriyi gizlemek için', labelEn: 'To hide nominal data' }], correctId: 'a', explanation: 'Reel ölçüm satın alma gücü veya üretim miktarındaki gerçek değişimi anlamayı kolaylaştırabilir.', explanationEn: 'Real measurement can make it easier to interpret changes in purchasing power or output volume.' },
    { prompt: 'Nominal getiri pozitifken reel getiri negatif olabilir mi?', promptEn: 'Can nominal return be positive while real return is negative?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız dövizde', labelEn: 'Only in FX' }], correctId: 'a', explanation: 'Enflasyon nominal artıştan daha yüksekse reel sonuç negatif olabilir.', explanationEn: 'If inflation exceeds the nominal gain, the real outcome can be negative.' },
  ],
  sources: [ECONOMY_EXPANSION_SOURCES.realNominal],
});

export const ECONOMY_EXPANSION_LESSONS = [
  laborMarket,
  fiscalPolicy,
  exchangeRates,
  productivity,
  indicators,
  realNominal,
] as const;
