import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { FINANCIAL_MARKETS_EXPANSION_SOURCES } from './financialMarketsExpansionSources';

const cryptoMarkets = createFoundationLesson({
  id: 'lesson.markets.crypto.001',
  slug: 'kripto-piyasasi-nasil-farklidir',
  conceptKey: 'market.crypto.basics',
  skillId: 'skill.financial-markets',
  competencyId: 'competency.explain-crypto-market.foundation',
  title: 'Kripto piyasası diğer piyasalardan nasıl ayrılır?',
  titleEn: 'How does the crypto market differ from other markets?',
  objective: 'Kriptonun 7/24 işlem, farklı platformlar ve saklama yapısı nedeniyle nasıl ayrıştığını öğren.',
  objectiveEn: 'Explain core crypto-market differences such as 24/7 trading, fragmented venues, custody, and token structure.',
  minutes: 5,
  hook: 'Kripto 7/24 işlem görüyor diye her an aynı likidite ve aynı fiyat mı vardır?',
  hookEn: 'Because crypto trades 24/7, does it have identical liquidity and price everywhere at every moment?',
  explanation: 'Kripto birçok merkezi ve merkeziyetsiz platformda 7/24 işlem görebilir. Ama bütün platformlarda fiyat ve likidite aynı değildir. Saklama biçimi, ağ, token arzı ve karşı taraf gibi riskler ürünün sonucunu ayrıca etkileyebilir.',
  explanationEn: 'Crypto assets can trade around the clock across many centralized and decentralized venues. That does not mean price and liquidity are identical everywhere. Custody, network risk, token supply design, counterparty risk, and venue risk can create additional differences from traditional markets.',
  proExplanation: 'Spot, perpetual futures, dated futures ve tokenized products farklı finansman ve tasfiye mekaniklerine sahiptir. Fragmented liquidity, oracle design, funding rates ve collateral rules gerçekleşme ve risk profilini değiştirebilir.',
  proExplanationEn: 'Spot, perpetual futures, dated futures, and tokenized products have different financing and liquidation mechanics. Fragmented liquidity, oracle design, funding rates, and collateral rules can change execution and risk.',
  misconception: 'Kripto 7/24 açık diye her saatte aynı likidite olduğunu sanma.',
  misconceptionEn: 'Common mistake: assuming 24/7 trading means identical depth and execution quality at every hour.',
  takeaway: 'Kriptoda işlem yeri, ürün yapısı, saklama ve likiditeyi birlikte değerlendir.',
  takeawayEn: 'Crypto is not one uniform market; venue, product structure, custody, and liquidity conditions all matter.',
  prerequisiteConceptKeys: ['market.basics.instruments', 'market.structure.liquidity'],
  relatedConceptKeys: ['onchain.basics', 'market.derivatives.basics', 'risk.volatility'],
  visualAlt: 'Birden fazla kripto işlem yerinin farklı fiyat ve likidite koşullarını gösteren sade piyasa şeması',
  visualAltEn: 'Simple crypto-market diagram showing multiple venues with different price and liquidity conditions',
  taskPrompt: 'Kripto piyasasını değerlendirirken hangisi özellikle önemlidir?',
  taskPromptEn: 'What is especially important when assessing a crypto market?',
  taskChoices: [
    { id: 'venue', label: 'Hangi işlem yeri ve ürün yapısının kullanıldığını bilmek', labelEn: 'Know which venue and product structure are being used' },
    { id: 'always', label: '7/24 açık olduğu için likiditeyi kontrol etmemek', labelEn: 'Ignore liquidity because the market is open 24/7' },
    { id: 'same', label: 'Bütün platformların fiyat ve riskinin aynı olduğunu varsaymak', labelEn: 'Assume every platform has identical price and risk' },
  ],
  taskCorrectIds: ['venue'],
  questions: [
    { prompt: 'Kripto piyasalarında likidite her platformda aynı mıdır?', promptEn: 'Is crypto liquidity identical across all venues?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız hafta sonu aynıdır', labelEn: 'Only on weekends' }], correctId: 'a', explanation: 'Katılımcı, emir derinliği ve ürün yapısı platformlar arasında farklılaşabilir.', explanationEn: 'Participants, order-book depth, and product structures can differ by venue.' },
    { prompt: 'Kripto piyasalarında hangisi ek risk kaynağı olabilir?', promptEn: 'What can be an additional crypto-market risk?', choices: [{ id: 'a', label: 'Saklama ve platform riski', labelEn: 'Custody and venue risk' }, { id: 'b', label: 'Yalnız mum rengi', labelEn: 'Only candle color' }, { id: 'c', label: 'Sembolün uzunluğu', labelEn: 'Ticker length' }], correctId: 'a', explanation: 'Varlığın nerede ve nasıl tutulduğu ile işlem yerinin yapısı önemlidir.', explanationEn: 'Where and how assets are held, plus venue structure, matter.' },
    { prompt: 'Spot ve perpetual futures aynı ürün müdür?', promptEn: 'Are spot crypto and perpetual futures the same product?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız fiyat aynıysa', labelEn: 'Only when prices match' }], correctId: 'a', explanation: 'Finansman, kaldıraç ve tasfiye mekanikleri farklıdır.', explanationEn: 'Financing, leverage, and liquidation mechanics differ.' },
  ],
  sources: [FINANCIAL_MARKETS_EXPANSION_SOURCES.crypto],
});

const marketSessions = createFoundationLesson({
  id: 'lesson.markets.sessions.001',
  slug: 'piyasa-seanslari-neden-onemlidir',
  conceptKey: 'market.sessions.basics',
  skillId: 'skill.financial-markets',
  competencyId: 'competency.explain-market-sessions.foundation',
  title: 'Piyasa seansları neden önemlidir?',
  titleEn: 'Why do market sessions matter?',
  objective: 'Piyasa saatlerinin likidite, spread ve gerçekleşme kalitesini nasıl etkilediğini öğren.',
  objectiveEn: 'Explain how trading hours can affect participation, liquidity, spreads, and price behavior.',
  minutes: 4,
  hook: 'Aynı varlık günün her saatinde aynı işlem koşullarına sahip midir?',
  hookEn: 'Does the same asset trade under identical conditions at every hour?',
  explanation: 'Piyasalarda katılımcı sayısı ve emir derinliği saate göre değişebilir. Bu da spread, volatilite ve gerçekleşme kalitesini etkiler. Forex ve kripto uzun süre açık olsa bile aktivite gün boyunca eşit dağılmaz.',
  explanationEn: 'Many markets have defined regular trading hours, sometimes with pre- or post-market sessions. When participation and order depth change by time of day, spreads, volatility, and execution quality can also change. Even forex and crypto activity is not evenly distributed through the day.',
  proExplanation: 'Açılış/kapanış auction yapıları, seans overlap’leri, fixing saatleri ve tatil takvimleri mikro yapıyı etkileyebilir. Seans dışı fiyat oluşumu ana seans derinliğiyle aynı kabul edilmemelidir.',
  proExplanationEn: 'Opening and closing auctions, session overlaps, fixing windows, and holiday calendars can affect microstructure. Off-hours price formation should not be assumed to have regular-session depth.',
  misconception: 'Piyasa açık diye likidite ve spreadin gün boyu aynı kaldığını sanma.',
  misconceptionEn: 'Common mistake: assuming liquidity and spreads stay constant whenever the market is open.',
  takeaway: 'Piyasa saati, likidite ve gerçekleşme koşullarının parçasıdır.',
  takeawayEn: 'Time of day is not just a calendar detail; it is part of market participation and execution conditions.',
  prerequisiteConceptKeys: ['market.structure.liquidity', 'market.microstructure.bid_ask'],
  relatedConceptKeys: ['market.forex.basics', 'market.crypto.basics', 'market.volume.basics'],
  visualAlt: 'Günün farklı seanslarında katılım, spread ve likiditenin değişebildiğini gösteren sade zaman şeridi',
  visualAltEn: 'Simple session timeline showing participation, spread, and liquidity changing through the day',
  taskPrompt: 'Düşük katılımlı bir seans dışında hangisi görülebilir?',
  taskPromptEn: 'What can occur in a lower-participation session?',
  taskChoices: [
    { id: 'wider', label: 'Spreadin genişlemesi ve derinliğin azalması', labelEn: 'Wider spreads and lower depth' },
    { id: 'same', label: 'Her zaman ana seansla aynı likidite', labelEn: 'Always identical liquidity to the main session' },
    { id: 'guarantee', label: 'Kesin fiyat yönü', labelEn: 'Guaranteed price direction' },
  ],
  taskCorrectIds: ['wider'],
  questions: [
    { prompt: 'İşlem saatleri likiditeyi etkileyebilir mi?', promptEn: 'Can trading hours affect liquidity?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız tahvillerde', labelEn: 'Only in bonds' }], correctId: 'a', explanation: 'Katılım ve emir derinliği zaman dilimlerine göre değişebilir.', explanationEn: 'Participation and order depth can vary by session.' },
    { prompt: 'Piyasa açık olması her saat aynı spread anlamına gelir mi?', promptEn: 'Does an open market imply the same spread at every hour?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız hafta içi', labelEn: 'Only on weekdays' }], correctId: 'a', explanation: 'Likidite koşulları spreadi değiştirebilir.', explanationEn: 'Liquidity conditions can change spreads.' },
    { prompt: 'Forex gün boyunca tamamen eşit aktiviteye sahip midir?', promptEn: 'Does forex have perfectly even activity all day?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız dolar çiftlerinde', labelEn: 'Only for dollar pairs' }], correctId: 'a', explanation: 'Bölgesel seanslar ve örtüşmeler aktiviteyi etkiler.', explanationEn: 'Regional sessions and overlaps affect activity.' },
  ],
  sources: [FINANCIAL_MARKETS_EXPANSION_SOURCES.sessions],
});

const volume = createFoundationLesson({
  id: 'lesson.markets.volume.001',
  slug: 'islem-hacmi-ne-anlatir',
  conceptKey: 'market.volume.basics',
  skillId: 'skill.financial-markets',
  competencyId: 'competency.explain-volume.foundation',
  title: 'İşlem hacmi ne anlatır, ne anlatmaz?',
  titleEn: 'What does trading volume tell us—and what does it not?',
  objective: 'Hacmin aktiviteyi gösterdiğini ama yön veya likidite garantisi vermediğini öğren.',
  objectiveEn: 'Explain trading volume as market activity and distinguish it from liquidity or direction.',
  minutes: 4,
  hook: 'Hacim yükseldi diye fiyatın hangi yöne gideceğini biliyor musun?',
  hookEn: 'If volume rises, do you know which direction price will move?',
  explanation: 'Hacim belirli sürede el değiştiren miktarı ölçer. Yüksek hacim daha fazla aktiviteyi gösterebilir ama tek başına yönü, trend kalitesini veya anlık likiditeyi garanti etmez. Aynı hacim farklı spread ve emir derinliğinde oluşabilir.',
  explanationEn: 'Trading volume measures the amount or number of contracts changing hands over a period. High volume can indicate more activity, but it does not by itself guarantee direction, trend quality, or current liquidity. The same volume can occur under different depth and spread conditions.',
  proExplanation: 'Volume tanımı venue ve ürün yapısına göre değişebilir. Consolidated volume, tick volume, open interest ve turnover farklı ölçümlerdir ve birbirinin yerine kullanılmamalıdır.',
  proExplanationEn: 'Volume definitions can vary by venue and product. Consolidated volume, tick volume, open interest, and turnover are different measures and should not be treated interchangeably.',
  misconception: 'Yüksek hacmi otomatik yükseliş veya yüksek likidite kanıtı sayma.',
  misconceptionEn: 'Common mistake: treating high volume as an automatic bullish signal or proof of high liquidity.',
  takeaway: 'Hacim aktiviteyi gösterir; yön ve likidite için ek bağlam gerekir.',
  takeawayEn: 'Volume measures activity; direction and liquidity require additional context.',
  prerequisiteConceptKeys: ['market.structure.liquidity'],
  relatedConceptKeys: ['market.sessions.basics', 'market.trend.basics', 'market.microstructure.bid_ask'],
  visualAlt: 'Aynı yüksek hacmin farklı fiyat yönü ve likidite koşullarında görülebileceğini gösteren sade karşılaştırma',
  visualAltEn: 'Simple comparison showing high volume occurring under different price directions and liquidity conditions',
  taskPrompt: 'Hacim yükseldiğinde tek başına hangi sonuç çıkarılamaz?',
  taskPromptEn: 'What cannot be concluded from higher volume alone?',
  taskChoices: [
    { id: 'direction', label: 'Fiyatın kesin yükseleceği', labelEn: 'That price will definitely rise' },
    { id: 'activity', label: 'İşlem aktivitesinin arttığı', labelEn: 'That trading activity increased' },
    { id: 'traded', label: 'Daha fazla miktarın el değiştirdiği', labelEn: 'That more quantity changed hands' },
  ],
  taskCorrectIds: ['direction'],
  questions: [
    { prompt: 'İşlem hacmi en temel olarak neyi ölçer?', promptEn: 'What does trading volume fundamentally measure?', choices: [{ id: 'a', label: 'Belirli dönemde el değiştiren miktarı', labelEn: 'The quantity changing hands during a period' }, { id: 'b', label: 'Kesin gelecek yönünü', labelEn: 'Certain future direction' }, { id: 'c', label: 'Şirketin gerçek değerini', labelEn: 'A company’s true value' }], correctId: 'a', explanation: 'Hacim işlem aktivitesinin miktar boyutunu ölçer.', explanationEn: 'Volume measures the quantity dimension of trading activity.' },
    { prompt: 'Yüksek hacim her zaman yüksek likidite midir?', promptEn: 'Does high volume always mean high liquidity?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız endekslerde', labelEn: 'Only for indexes' }], correctId: 'a', explanation: 'Likidite spread, derinlik ve emir büyüklüğüne göre ayrıca değerlendirilir.', explanationEn: 'Liquidity also depends on spreads, depth, and order size.' },
    { prompt: 'Hacim yönü tek başına garanti eder mi?', promptEn: 'Does volume alone guarantee direction?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız hacim iki katına çıkarsa', labelEn: 'Only if volume doubles' }], correctId: 'a', explanation: 'Hacim aktiviteyi gösterir; alıcı ve satıcı baskısının sonucu fiyat bağlamında değerlendirilir.', explanationEn: 'Volume shows activity; price context is needed to interpret the outcome of buying and selling pressure.' },
  ],
  sources: [FINANCIAL_MARKETS_EXPANSION_SOURCES.volume],
});

const liquidityProviders = createFoundationLesson({
  id: 'lesson.markets.liquidity-providers.001',
  slug: 'market-maker-ne-yapar',
  conceptKey: 'market.liquidity_providers',
  skillId: 'skill.financial-markets',
  competencyId: 'competency.explain-liquidity-providers.foundation',
  title: 'Market maker ve likidite sağlayıcı ne yapar?',
  titleEn: 'What do market makers and liquidity providers do?',
  objective: 'Market maker ve likidite sağlayıcının piyasada ne yaptığını öğren.',
  objectiveEn: 'Explain the role of liquidity providers in quoting two-sided prices and supporting executability.',
  minutes: 5,
  hook: 'Ekranda sürekli bid ve ask görmek için karşı tarafta kim emir bırakıyor olabilir?',
  hookEn: 'Who may be posting orders so bid and ask quotes remain available on screen?',
  explanation: 'Market maker veya likidite sağlayıcı alış ve satış tarafında fiyat sunarak işlem yapılmasını kolaylaştırabilir. Geliri spread, ücret veya farklı piyasa teşviklerinden gelebilir. Bu rol, piyasa yönünü tek başına kontrol ettiği anlamına gelmez.',
  explanationEn: 'A market maker or other liquidity provider can post buy and sell quotes or orders under defined conditions to support trading. Revenue can come through spreads, fees, rebates, or risk management. This does not mean the provider controls market direction or can freely set price.',
  proExplanation: 'Inventory risk, adverse selection, hedging cost, quote obligations, latency and venue incentive structures likidite sağlama davranışını etkiler. Stres dönemlerinde quote genişliği veya derinlik değişebilir.',
  proExplanationEn: 'Inventory risk, adverse selection, hedging costs, quote obligations, latency, and venue incentives affect liquidity provision. During stress, quote width and depth can change.',
  misconception: 'Market maker’ın fiyatı tek başına belirlediğini sanma.',
  misconceptionEn: 'Common mistake: assuming a market maker alone sets market prices or that one actor drives every move.',
  takeaway: 'Likidite sağlayıcı işlem yapılabilirliği destekler; yönü tek başına belirlemez.',
  takeawayEn: 'A liquidity provider supports executability; it does not guarantee or single-handedly determine market direction.',
  prerequisiteConceptKeys: ['market.microstructure.bid_ask', 'market.structure.liquidity'],
  relatedConceptKeys: ['market.venues.exchanges', 'market.execution.slippage'],
  visualAlt: 'Likidite sağlayıcının alış ve satış tarafına iki yönlü fiyat sunduğunu gösteren sade emir defteri şeması',
  visualAltEn: 'Simple order-book diagram showing a liquidity provider posting two-sided buy and sell quotes',
  taskPrompt: 'Market maker’ın temel rollerinden biri hangisidir?',
  taskPromptEn: 'What is one basic role of a market maker?',
  taskChoices: [
    { id: 'quotes', label: 'Alış ve satış tarafında fiyat sunarak gerçekleşebilirliği desteklemek', labelEn: 'Support executability by quoting buy and sell prices' },
    { id: 'direction', label: 'Piyasanın gelecek yönünü garanti etmek', labelEn: 'Guarantee the market’s future direction' },
    { id: 'profits', label: 'Bütün yatırımcıların kârını sağlamak', labelEn: 'Ensure profits for all investors' },
  ],
  taskCorrectIds: ['quotes'],
  questions: [
    { prompt: 'Likidite sağlayıcı neden iki yönlü fiyat sunabilir?', promptEn: 'Why can a liquidity provider quote two sides?', choices: [{ id: 'a', label: 'Alış ve satış işlemlerinin yapılabilirliğini desteklemek için', labelEn: 'To support the ability to trade on both buy and sell sides' }, { id: 'b', label: 'Kesin piyasa yönü yaratmak için', labelEn: 'To create a guaranteed market direction' }, { id: 'c', label: 'Hacmi sıfırlamak için', labelEn: 'To reduce volume to zero' }], correctId: 'a', explanation: 'İki taraflı quote piyasa katılımcılarına işlem karşılığı sağlar.', explanationEn: 'Two-sided quotes provide potential counterparties for trading.' },
    { prompt: 'Market maker tek başına piyasa fiyatını kontrol eder mi?', promptEn: 'Does a market maker single-handedly control market price?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız açılışta', labelEn: 'Only at the open' }], correctId: 'a', explanation: 'Fiyat çok sayıda katılımcı, emir ve piyasa koşulunun etkileşimiyle oluşur.', explanationEn: 'Price forms through interaction among many participants, orders, and market conditions.' },
    { prompt: 'Stresli piyasada market maker quote’ları değişebilir mi?', promptEn: 'Can market-maker quotes change during stressed markets?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız fiyat düşerken', labelEn: 'Only when price falls' }], correctId: 'a', explanation: 'Envanter ve adverse-selection riski spread ve derinliği etkileyebilir.', explanationEn: 'Inventory and adverse-selection risk can affect spreads and depth.' },
  ],
  sources: [FINANCIAL_MARKETS_EXPANSION_SOURCES.liquidityProviders],
});

const primarySecondary = createFoundationLesson({
  id: 'lesson.markets.primary-secondary.001',
  slug: 'birincil-ve-ikincil-piyasa',
  conceptKey: 'market.primary_secondary',
  skillId: 'skill.financial-markets',
  competencyId: 'competency.distinguish-primary-secondary.foundation',
  title: 'Birincil ve ikincil piyasa farkı nedir?',
  titleEn: 'What is the difference between primary and secondary markets?',
  objective: 'Birincil piyasa ile ikincil piyasanın farkını öğren.',
  objectiveEn: 'Distinguish new securities issuance from later trading among investors.',
  minutes: 4,
  hook: 'IPO’da şirkete giden para ile borsada iki yatırımcı arasındaki işlem aynı şey midir?',
  hookEn: 'Is money raised in an IPO the same as a later stock trade between two investors?',
  explanation: 'Birincil piyasada yeni menkul kıymet çıkarılır ve para ihraççıya gider. İkincil piyasada mevcut menkul kıymetler yatırımcılar arasında el değiştirir. Borsada hisse alırken ödediğin para çoğu zaman doğrudan şirkete gitmez.',
  explanationEn: 'In the primary market, new securities are issued and capital goes to the issuer. In the secondary market, previously issued securities trade among investors. Secondary-market liquidity and price discovery can indirectly affect primary-market access to capital, but the two processes are not the same.',
  proExplanation: 'IPO, follow-on offering, rights issue ve debt issuance birincil piyasa örnekleridir. Settlement, underwriting ve allocation süreçleri ikincil piyasa matching mekanizmasından farklıdır.',
  proExplanationEn: 'IPOs, follow-on offerings, rights issues, and debt issuance are primary-market examples. Settlement, underwriting, and allocation differ from secondary-market matching.',
  misconception: 'Borsada her hisse alışında paranın doğrudan şirkete gittiğini sanma.',
  misconceptionEn: 'Common mistake: assuming every stock purchase on an exchange sends the money directly to the company.',
  takeaway: 'Birincil piyasa ihraç, ikincil piyasa yatırımcılar arası alım-satımdır.',
  takeawayEn: 'Primary markets raise capital; secondary markets let existing securities change hands among investors.',
  prerequisiteConceptKeys: ['market.venues.exchanges'],
  relatedConceptKeys: ['market.indices.basics', 'market.etf.basics'],
  visualAlt: 'Şirketten ilk yatırımcıya ihraç ve ardından yatırımcılar arasındaki ikincil piyasa işlemini ayıran sade akış',
  visualAltEn: 'Simple flow separating issuance from the company to first investors and later secondary-market trading among investors',
  taskPrompt: 'Bir yatırımcı borsada başka bir yatırımcıdan mevcut hisse aldığında hangi piyasadadır?',
  taskPromptEn: 'When one investor buys an existing share from another investor on an exchange, which market is it?',
  taskChoices: [
    { id: 'secondary', label: 'İkincil piyasa', labelEn: 'Secondary market' },
    { id: 'primary', label: 'Birincil piyasa', labelEn: 'Primary market' },
    { id: 'none', label: 'Hiçbir piyasa değildir', labelEn: 'Neither market' },
  ],
  taskCorrectIds: ['secondary'],
  questions: [
    { prompt: 'Birincil piyasada temel olarak ne olur?', promptEn: 'What fundamentally happens in a primary market?', choices: [{ id: 'a', label: 'Yeni menkul kıymet ihraç edilir', labelEn: 'New securities are issued' }, { id: 'b', label: 'Yalnız mevcut hisseler yatırımcılar arasında el değiştirir', labelEn: 'Only existing shares trade between investors' }, { id: 'c', label: 'Piyasa tamamen kapanır', labelEn: 'The market closes entirely' }], correctId: 'a', explanation: 'Birincil piyasa yeni sermaye veya borçlanma aracının ihracıyla ilgilidir.', explanationEn: 'Primary markets concern the issuance of new equity or debt securities.' },
    { prompt: 'Borsada mevcut hisseyi başka yatırımcıdan almak genellikle hangi piyasadır?', promptEn: 'Buying an existing share from another investor on an exchange is generally which market?', choices: [{ id: 'a', label: 'İkincil piyasa', labelEn: 'Secondary market' }, { id: 'b', label: 'Birincil piyasa', labelEn: 'Primary market' }, { id: 'c', label: 'Para piyasası olmak zorunda', labelEn: 'Always a money market' }], correctId: 'a', explanation: 'Daha önce ihraç edilmiş menkul kıymet yatırımcılar arasında el değiştirir.', explanationEn: 'A previously issued security changes hands among investors.' },
    { prompt: 'Her ikincil piyasa işleminde para doğrudan şirkete gider mi?', promptEn: 'Does money from every secondary-market trade go directly to the company?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız fiyat yükselirse', labelEn: 'Only if price rises' }], correctId: 'a', explanation: 'İkincil işlem çoğunlukla yatırımcılar arasındadır.', explanationEn: 'Secondary-market transactions are generally between investors.' },
  ],
  sources: [FINANCIAL_MARKETS_EXPANSION_SOURCES.primarySecondary],
});

const derivatives = createFoundationLesson({
  id: 'lesson.markets.derivatives.001',
  slug: 'turev-urun-nedir',
  conceptKey: 'market.derivatives.basics',
  skillId: 'skill.financial-markets',
  competencyId: 'competency.explain-derivatives.foundation',
  title: 'Türev ürün nedir?',
  titleEn: 'What is a derivative?',
  objective: 'Türev ürünün dayanak varlığı referans alan ayrı bir sözleşme olduğunu öğren.',
  objectiveEn: 'Explain how a derivative contract derives value from an underlying asset or reference measure.',
  minutes: 5,
  hook: 'Futures veya opsiyon almak, dayanak varlığın kendisini almakla aynı şey midir?',
  hookEn: 'Is buying a future or option the same as buying the underlying asset itself?',
  explanation: 'Türev ürün, değeri başka bir varlık veya ölçütten türeyen sözleşmedir. Futures belirli koşullarda yükümlülük, opsiyon ise alıcıya hak verebilir. Vade, kaldıraç ve teminat yapısı nedeniyle dayanak varlıktan farklı risk taşır.',
  explanationEn: 'A derivative is a contract whose value is linked to an underlying asset, rate, index, commodity, or other reference. Futures can create obligations to transact under defined future terms, while options give the buyer a right under specified conditions. Contract structure, maturity, leverage, and margin risk can differ from the underlying asset.',
  proExplanation: 'Delta, gamma, theta, basis, margin, variation settlement, counterparty and clearing structure gibi unsurlar ürün türüne göre önem kazanır. Türevler hedge amacıyla da spekülasyon amacıyla da kullanılabilir.',
  proExplanationEn: 'Delta, gamma, theta, basis, margin, variation settlement, counterparty, and clearing structure matter depending on product type. Derivatives can be used for hedging or speculation.',
  misconception: 'Türev ürünü dayanak varlıkla aynı ürün sanma.',
  misconceptionEn: 'Common mistake: treating a derivative as having the same risk and cash-flow structure as the underlying asset.',
  takeaway: 'Türev, dayanağı referans alan ayrı bir sözleşmedir.',
  takeawayEn: 'A derivative is a contract linked to an underlying reference; it is not the same product as the underlying.',
  prerequisiteConceptKeys: ['market.basics.instruments'],
  relatedConceptKeys: ['market.commodities.basics', 'market.crypto.basics', 'risk.position_sizing'],
  visualAlt: 'Dayanak varlıktan futures ve opsiyon sözleşmelerine ayrılan sade türev ürün ağacı',
  visualAltEn: 'Simple derivative tree branching from an underlying asset into futures and options contracts',
  taskPrompt: 'Hangisi türev ürünün en temel özelliğidir?',
  taskPromptEn: 'What is the most fundamental feature of a derivative?',
  taskChoices: [
    { id: 'derived', label: 'Değerinin bir dayanak veya referans ölçütten türemesi', labelEn: 'Its value is linked to an underlying asset or reference' },
    { id: 'same', label: 'Her zaman dayanak varlığın aynısı olması', labelEn: 'It is always identical to the underlying asset' },
    { id: 'riskless', label: 'Risk taşımaması', labelEn: 'It carries no risk' },
  ],
  taskCorrectIds: ['derived'],
  questions: [
    { prompt: 'Türev ürün neye bağlı değer taşıyabilir?', promptEn: 'What can a derivative derive value from?', choices: [{ id: 'a', label: 'Dayanak varlık veya referans ölçütten', labelEn: 'An underlying asset or reference measure' }, { id: 'b', label: 'Yalnız şirket logosundan', labelEn: 'Only a company logo' }, { id: 'c', label: 'Yalnız işlem saatinden', labelEn: 'Only trading hours' }], correctId: 'a', explanation: 'Türev değeri başka bir varlık veya ölçüte bağlı sözleşmedir.', explanationEn: 'A derivative is a contract linked to another asset or reference.' },
    { prompt: 'Futures ile dayanak varlık aynı ürün müdür?', promptEn: 'Is a futures contract the same product as its underlying asset?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız vade sonunda', labelEn: 'Only at expiry' }], correctId: 'a', explanation: 'Futures ayrı vade, teminat ve sözleşme kurallarına sahiptir.', explanationEn: 'Futures have separate maturity, margin, and contract rules.' },
    { prompt: 'Türevler yalnız spekülasyon için mi kullanılır?', promptEn: 'Are derivatives used only for speculation?', choices: [{ id: 'a', label: 'Hayır; hedge amacıyla da kullanılabilir', labelEn: 'No; they can also be used for hedging' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız bankalar kullanabilir', labelEn: 'Only banks can use them' }], correctId: 'a', explanation: 'Türevler risk transferi ve korunma amacıyla da kullanılabilir.', explanationEn: 'Derivatives can also be used to transfer or hedge risk.' },
  ],
  sources: [FINANCIAL_MARKETS_EXPANSION_SOURCES.derivatives],
});

export const FINANCIAL_MARKETS_EXPANSION_LESSONS = [
  cryptoMarkets,
  marketSessions,
  volume,
  liquidityProviders,
  primarySecondary,
  derivatives,
] as const;
