import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { FINANCIAL_MARKETS_SOURCES } from './financialMarketsSources';

const exchanges = createFoundationLesson({
  id: 'lesson.markets.exchanges.001',
  slug: 'borsa-ve-islem-yeri-nedir',
  conceptKey: 'market.venues.exchanges',
  skillId: 'skill.financial-markets',
  competencyId: 'competency.explain-trading-venues.foundation',
  title: 'Borsa ve işlem yeri ne işe yarar?',
  titleEn: 'What do exchanges and trading venues do?',
  objective: 'İşlem yerlerinin emirleri hangi rol ve kurallarla buluşturduğunu öğren.',
  objectiveEn: 'Explain how trading venues bring buyer and seller orders together under defined rules.',
  minutes: 5,
  hook: 'Bir hisseyi aldığında gerçekten kiminle ve nerede işlem yapıyorsun?',
  hookEn: 'When you buy a stock, where and with whom does the trade actually happen?',
  explanation: 'Borsa, alıcı ve satıcı emirlerinin belirli kurallarla buluştuğu işlem ortamıdır. Fiyatı borsa seçmez; uygun emirler eşleştiğinde fiyat oluşur. İşlem saatleri ve emir kuralları piyasaya göre değişebilir.',
  explanationEn: 'An exchange or other trading venue provides rules and infrastructure for buyer and seller orders to meet. The venue does not simply choose the price; prices form as orders match. Trading hours, order rules, participants, and transparency can differ across markets.',
  proExplanation: 'Piyasa yapısı merkezi borsa, dealer market, OTC ve alternatif işlem sistemleri gibi farklı modeller içerebilir. Yönlendirme, erişim ve en iyi gerçekleşme kuralları ülke ve varlık sınıfına göre değişir.',
  proExplanationEn: 'Market structure can include centralized exchanges, dealer markets, OTC markets, and alternative trading systems. Routing, access, and best-execution rules vary by jurisdiction and asset class.',
  misconception: 'Borsa fiyat etiketi yazmaz; emirlerin buluşacağı kurallı ortamı sağlar.',
  misconceptionEn: 'Common mistake: thinking the exchange centrally sets every asset price.',
  takeaway: 'Borsa fiyatı seçmez; emirlerin eşleşmesini sağlar.',
  takeawayEn: 'A trading venue does not choose the price; it provides the infrastructure where orders meet under rules.',
  prerequisiteConceptKeys: ['market.basics.price_formation', 'market.execution.order_types'],
  relatedConceptKeys: ['market.microstructure.bid_ask', 'market.structure.liquidity'],
  visualAlt: 'Alıcı ve satıcı emirlerinin bir işlem yeri üzerinden eşleştiğini gösteren sade piyasa altyapısı şeması',
  visualAltEn: 'Simple market-infrastructure diagram showing buyer and seller orders matching through a trading venue',
  taskPrompt: 'Bir işlem yerinin en temel rolü hangisidir?',
  taskPromptEn: 'What is a trading venue’s most basic role?',
  taskChoices: [
    { id: 'match', label: 'Emirlerin kurallar altında buluşup eşleşmesini sağlamak', labelEn: 'Provide rules and infrastructure for orders to meet and match' },
    { id: 'price', label: 'Her varlığın fiyatını tek başına belirlemek', labelEn: 'Set every asset price by itself' },
    { id: 'profit', label: 'Yatırımcıların kârını garanti etmek', labelEn: 'Guarantee investor profits' },
  ],
  taskCorrectIds: ['match'],
  questions: [
    { prompt: 'Borsa fiyatı tek başına belirler mi?', promptEn: 'Does an exchange set the price by itself?', choices: [{ id: 'a', label: 'Hayır; fiyat emirlerin eşleşmesiyle oluşur', labelEn: 'No; price forms as orders match' }, { id: 'b', label: 'Evet, her fiyatı merkezden seçer', labelEn: 'Yes, it centrally chooses every price' }, { id: 'c', label: 'Yalnız kapanış fiyatını belirler', labelEn: 'It only sets the closing price' }], correctId: 'a', explanation: 'İşlem yeri kuralları ve altyapıyı sağlar; fiyat keşfi katılımcı emirleriyle oluşur.', explanationEn: 'The venue provides rules and infrastructure; price discovery comes from participant orders.' },
    { prompt: 'Bütün piyasaların işlem kuralları aynı mıdır?', promptEn: 'Do all markets have identical trading rules?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız kriptoda farklıdır', labelEn: 'Only crypto differs' }], correctId: 'a', explanation: 'Saatler, katılımcılar ve emir kuralları piyasa ve varlığa göre değişebilir.', explanationEn: 'Hours, participants, and order rules can vary by market and asset.' },
    { prompt: 'İşlem yeri ne sağlar?', promptEn: 'What does a trading venue provide?', choices: [{ id: 'a', label: 'Emirlerin buluşması için kurallı altyapı', labelEn: 'Rule-based infrastructure for orders to meet' }, { id: 'b', label: 'Kesin getiri', labelEn: 'Guaranteed returns' }, { id: 'c', label: 'Sabit piyasa yönü', labelEn: 'A fixed market direction' }], correctId: 'a', explanation: 'Temel işlev düzenli işlem ve eşleşme ortamıdır.', explanationEn: 'Its core function is an organized environment for trading and matching.' },
  ],
  sources: [FINANCIAL_MARKETS_SOURCES.exchanges],
});

const indices = createFoundationLesson({
  id: 'lesson.markets.indices.001',
  slug: 'borsa-endeksi-ne-anlatir',
  conceptKey: 'market.indices.basics',
  skillId: 'skill.financial-markets',
  competencyId: 'competency.explain-index.foundation',
  title: 'Borsa endeksi ne anlatır?',
  titleEn: 'What does a market index tell us?',
  objective: 'Endeksin bir varlık grubunu nasıl tek ölçüde özetlediğini öğren.',
  objectiveEn: 'Explain how an index summarizes the performance of a selected group of assets using defined rules.',
  minutes: 4,
  hook: 'Bir endeks yükseldiğinde içindeki bütün şirketler yükselmiş midir?',
  hookEn: 'If an index rises, did every company inside it rise?',
  explanation: 'Endeks, seçilmiş varlıkların performansını tek ölçüde özetler. Her bileşenin etkisi aynı olmak zorunda değildir; ağırlığı yüksek olanlar sonucu daha fazla etkileyebilir. Bu yüzden endeks yükselirken bazı hisseler düşebilir.',
  explanationEn: 'An index summarizes a selected group of assets using defined inclusion and weighting rules. Some constituents can fall even when the index rises. Price-weighted, market-cap-weighted, and equal-weighted methods can produce different results.',
  proExplanation: 'Endeks getirisi metodoloji, yeniden dengeleme, serbest dolaşım ayarı, temettü yaklaşımı ve bileşen değişikliklerinden etkilenir. Price return ile total return aynı değildir.',
  proExplanationEn: 'Index returns depend on methodology, rebalancing, free-float adjustments, dividend treatment, and constituent changes. Price return and total return are different.',
  misconception: 'Endeks yükseliyorsa içindeki her hissenin yükseldiğini varsayma.',
  misconceptionEn: 'Common mistake: reading an index move as every constituent moving in the same direction.',
  takeaway: 'Endeks grubun özetidir; her üye aynı yönde gitmez.',
  takeawayEn: 'An index summarizes a market group; its constituents do not need to move identically.',
  prerequisiteConceptKeys: ['market.basics.instruments'],
  relatedConceptKeys: ['market.etf.basics', 'portfolio.diversification'],
  visualAlt: 'Farklı yönlerde hareket eden şirketlerin ağırlıklarıyla tek bir endeks değerinde birleşmesini gösteren sade şema',
  visualAltEn: 'Simple diagram showing differently moving companies combining into one index value through weights',
  taskPrompt: 'Bir endeks %1 yükselirken içindeki bazı hisseler düşebilir mi?',
  taskPromptEn: 'Can some stocks fall while an index rises 1%?',
  taskChoices: [
    { id: 'yes', label: 'Evet; ağırlıklar ve farklı bileşen hareketleri nedeniyle', labelEn: 'Yes; because weights and constituent moves differ' },
    { id: 'no', label: 'Hayır; bütün bileşenler aynı yönde olmak zorundadır', labelEn: 'No; every constituent must move in the same direction' },
    { id: 'only', label: 'Yalnız endeks yeni kurulmuşsa', labelEn: 'Only if the index is new' },
  ],
  taskCorrectIds: ['yes'],
  questions: [
    { prompt: 'Endeks en temel olarak ne yapar?', promptEn: 'What does an index fundamentally do?', choices: [{ id: 'a', label: 'Seçilmiş varlık grubunun performansını özetler', labelEn: 'Summarizes the performance of a selected group of assets' }, { id: 'b', label: 'Her hisseye aynı fiyatı verir', labelEn: 'Gives every stock the same price' }, { id: 'c', label: 'Gelecekteki getiriyi garanti eder', labelEn: 'Guarantees future returns' }], correctId: 'a', explanation: 'Endeks belirli bir evreni ve metodolojiyi tek ölçüde temsil etmeye çalışır.', explanationEn: 'An index seeks to represent a defined universe and methodology in one measure.' },
    { prompt: 'Endekslerde ağırlıklandırma yöntemi önemli midir?', promptEn: 'Does index weighting methodology matter?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız döviz endekslerinde', labelEn: 'Only for currency indexes' }], correctId: 'a', explanation: 'Farklı ağırlıklandırmalar bileşenlerin endekse katkısını değiştirir.', explanationEn: 'Different weighting methods change constituent contributions.' },
    { prompt: 'Endeks yükselince tüm bileşenler yükselmek zorunda mıdır?', promptEn: 'Must all constituents rise when the index rises?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız büyük şirketler', labelEn: 'Only large companies' }], correctId: 'a', explanation: 'Ağırlığı yüksek bileşenlerin hareketi toplam sonucu baskınlaştırabilir.', explanationEn: 'Moves in heavily weighted constituents can dominate the total result.' },
  ],
  sources: [FINANCIAL_MARKETS_SOURCES.indices],
});

const etf = createFoundationLesson({
  id: 'lesson.markets.etf.001',
  slug: 'etf-nedir-nasil-calisir',
  conceptKey: 'market.etf.basics',
  skillId: 'skill.financial-markets',
  competencyId: 'competency.explain-etf.foundation',
  title: 'ETF nedir ve nasıl çalışır?',
  titleEn: 'What is an ETF and how does it work?',
  objective: 'ETF payı ile arkasındaki varlık sepetini ayırt etmeyi öğren.',
  objectiveEn: 'Distinguish an ETF share from the basket of assets the fund holds or tracks.',
  minutes: 5,
  hook: 'Tek bir işlemle onlarca veya yüzlerce varlığa maruz kalmak mümkün mü?',
  hookEn: 'Can one trade give exposure to dozens or hundreds of assets?',
  explanation: 'ETF, borsada alınıp satılan bir fon payıdır. Arkasında bir endeks, sektör, tahvil sepeti, emtia veya başka bir strateji olabilir. ETF’nin riski adıyla değil, içeride ne taşıdığı ve nasıl yapılandırıldığıyla anlaşılır.',
  explanationEn: 'An ETF is an investment fund whose shares trade on an exchange. It can seek to track an index, sector, bond basket, commodity, or another strategy. ETF shares trade intraday; market price does not have to equal net asset value, although creation/redemption mechanisms can help limit gaps in many products.',
  proExplanation: 'Tracking difference, tracking error, likidite, spread, fon masrafı, vergi ve sentetik/fiziksel replikasyon yapısı performansı etkileyebilir. ETF etiketi tek başına düşük risk anlamına gelmez.',
  proExplanationEn: 'Tracking difference, tracking error, liquidity, spreads, expenses, taxes, and synthetic versus physical replication can affect outcomes. The ETF label alone does not imply low risk.',
  misconception: 'ETF yazması ürünün otomatik olarak geniş çeşitlendirilmiş veya düşük riskli olduğu anlamına gelmez.',
  misconceptionEn: 'Common mistake: assuming every ETF is automatically highly diversified and low risk.',
  takeaway: 'Önce ETF’nin ne taşıdığına bak; risk oradan gelir.',
  takeawayEn: 'An ETF is an access vehicle; its risk depends on the assets and structure it provides exposure to.',
  prerequisiteConceptKeys: ['market.indices.basics'],
  relatedConceptKeys: ['portfolio.diversification', 'market.structure.liquidity'],
  visualAlt: 'Tek ETF payının altında birden fazla varlık veya tahvil sepeti bulunduğunu gösteren sade katman şeması',
  visualAltEn: 'Simple layered diagram showing one ETF share linked to a basket of multiple assets or bonds',
  taskPrompt: 'Bir ETF’nin riskini anlamak için ilk olarak neye bakmalısın?',
  taskPromptEn: 'What should you first examine to understand an ETF’s risk?',
  taskChoices: [
    { id: 'exposure', label: 'ETF’nin hangi varlıkları veya stratejiyi izlediğine', labelEn: 'The assets or strategy the ETF tracks' },
    { id: 'ticker', label: 'Yalnız sembolünün kaç harf olduğuna', labelEn: 'Only how many letters are in its ticker' },
    { id: 'label', label: 'ETF yazdığı için otomatik düşük risk saymaya', labelEn: 'Assume low risk simply because it is an ETF' },
  ],
  taskCorrectIds: ['exposure'],
  questions: [
    { prompt: 'ETF payları nerede işlem görebilir?', promptEn: 'Where can ETF shares trade?', choices: [{ id: 'a', label: 'Borsada gün içinde', labelEn: 'On an exchange during the trading day' }, { id: 'b', label: 'Yalnız yılda bir', labelEn: 'Only once a year' }, { id: 'c', label: 'Hiç işlem görmez', labelEn: 'They do not trade' }], correctId: 'a', explanation: 'ETF payları hisse benzeri biçimde işlem saatlerinde alınıp satılabilir.', explanationEn: 'ETF shares can trade during market hours in a stock-like manner.' },
    { prompt: 'Her ETF düşük riskli midir?', promptEn: 'Is every ETF low risk?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız adı uzunsa', labelEn: 'Only if its name is long' }], correctId: 'a', explanation: 'Risk, fonun maruz kaldığı varlıklar ve ürün yapısına göre değişir.', explanationEn: 'Risk varies with the underlying exposure and product structure.' },
    { prompt: 'ETF piyasa fiyatı her an net varlık değerine tam eşit olmak zorunda mıdır?', promptEn: 'Must an ETF’s market price equal NAV exactly at every moment?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız endeks düşerken', labelEn: 'Only when the index falls' }], correctId: 'a', explanation: 'Piyasa fiyatı arz-talep ile oluşabilir ve NAV’dan geçici olarak ayrışabilir.', explanationEn: 'Market price can be driven by supply and demand and temporarily differ from NAV.' },
  ],
  sources: [FINANCIAL_MARKETS_SOURCES.etf],
});

const bonds = createFoundationLesson({
  id: 'lesson.markets.bonds.001',
  slug: 'tahvil-fiyati-ve-getirisi',
  conceptKey: 'market.fixed_income.bonds',
  skillId: 'skill.financial-markets',
  competencyId: 'competency.explain-bond-yield.foundation',
  title: 'Tahvil fiyatı ve getirisi neden ters hareket edebilir?',
  titleEn: 'Why can bond prices and yields move in opposite directions?',
  objective: 'Sabit kuponlu tahvilde fiyat ile piyasa getirisi arasındaki ters ilişkiyi öğren.',
  objectiveEn: 'Explain the basic inverse relationship between market price and yield for a fixed-coupon bond.',
  minutes: 5,
  hook: 'Tahvilin fiyatı düşerken neden yeni alıcı için getiri yükselebilir?',
  hookEn: 'Why can a bond’s yield rise for a new buyer when its price falls?',
  explanation: 'Tahvil, bir devlete veya şirkete borç verme ilişkisidir. Sabit ödemeler değişmiyorsa tahvil daha düşük fiyattan alındığında yeni alıcının getirisi yükselir; fiyat yükseldiğinde getiri düşer. Vade ve kredi riski de fiyatı etkiler.',
  explanationEn: 'A bond represents lending to an issuer. If a fixed-coupon bond’s future cash flows are unchanged, a lower market price means a new buyer acquires those cash flows more cheaply, raising yield; when price rises, yield falls. Maturity, credit risk, and the rate environment affect bond prices.',
  proExplanation: 'Yield to maturity varsayımlar içerir ve gerçekleşen getiriyi garanti etmez. Duration ve convexity faiz duyarlılığını; spread ise kredi ve likidite risk primini anlamaya yardım eder.',
  proExplanationEn: 'Yield to maturity relies on assumptions and does not guarantee realized return. Duration and convexity help describe rate sensitivity; spreads reflect credit and liquidity risk premia.',
  misconception: '“Sabit getirili” ifadesi tahvilin piyasa fiyatının sabit olduğu anlamına gelmez.',
  misconceptionEn: 'Common mistake: assuming “fixed income” means the market price or realized investment outcome is always fixed.',
  takeaway: 'Sabit kuponlu tahvilde fiyat ↑ ise getiri genellikle ↓; fiyat ↓ ise getiri ↑.',
  takeawayEn: 'For fixed-coupon bonds, price and market yield generally move inversely, while credit and maturity risks still matter.',
  prerequisiteConceptKeys: ['market.basics.instruments', 'economy.interest_rates'],
  relatedConceptKeys: ['risk.basics', 'economy.inflation'],
  visualAlt: 'Tahvil fiyatı aşağı inerken getiri göstergesinin yükseldiğini gösteren sade ters ilişki şeması',
  visualAltEn: 'Simple inverse-relationship diagram showing bond price falling while yield rises',
  taskPrompt: 'Sabit kuponlu bir tahvilin fiyatı düşerse, diğer koşullar aynıyken yeni alıcının getirisi genel olarak ne olur?',
  taskPromptEn: 'If a fixed-coupon bond’s price falls, what generally happens to a new buyer’s yield, all else equal?',
  taskChoices: [
    { id: 'yield-up', label: 'Yükselir', labelEn: 'It rises' },
    { id: 'same', label: 'Her zaman aynı kalır', labelEn: 'It always stays the same' },
    { id: 'zero', label: 'Otomatik olarak sıfırlanır', labelEn: 'It automatically falls to zero' },
  ],
  taskCorrectIds: ['yield-up'],
  questions: [
    { prompt: 'Tahvil en temel olarak neyi temsil eder?', promptEn: 'What does a bond fundamentally represent?', choices: [{ id: 'a', label: 'İhraççıya borç verme ilişkisini', labelEn: 'A lending relationship with the issuer' }, { id: 'b', label: 'Şirkete ortaklığı', labelEn: 'Equity ownership' }, { id: 'c', label: 'Bir döviz çiftini', labelEn: 'A currency pair' }], correctId: 'a', explanation: 'Tahvil yatırımcısı ihraççıya borç verir ve sözleşmeye bağlı nakit akış hakkı taşır.', explanationEn: 'A bond investor lends to the issuer and has contractual cash-flow claims.' },
    { prompt: 'Sabit kuponlu tahvilde fiyat yükselirken piyasa getirisi genellikle ne yapar?', promptEn: 'For a fixed-coupon bond, what generally happens to market yield when price rises?', choices: [{ id: 'a', label: 'Düşer', labelEn: 'It falls' }, { id: 'b', label: 'Aynı oranda yükselir', labelEn: 'It rises by the same amount' }, { id: 'c', label: 'Her zaman sıfır olur', labelEn: 'It always becomes zero' }], correctId: 'a', explanation: 'Aynı nakit akışını daha yüksek fiyattan almak getiriyi düşürür.', explanationEn: 'Paying more for the same cash flows lowers the yield.' },
    { prompt: 'Tahvilde kredi riski önemli midir?', promptEn: 'Does credit risk matter for bonds?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız kupon sıfırsa', labelEn: 'Only for zero-coupon bonds' }], correctId: 'a', explanation: 'İhraççının ödeme kapasitesi tahvil değerlemesi ve riskinde önemlidir.', explanationEn: 'The issuer’s ability to pay matters for bond valuation and risk.' },
  ],
  sources: [FINANCIAL_MARKETS_SOURCES.bonds],
});

const forex = createFoundationLesson({
  id: 'lesson.markets.forex.001',
  slug: 'forex-piyasasi-nasil-calisir',
  conceptKey: 'market.forex.basics',
  skillId: 'skill.financial-markets',
  competencyId: 'competency.explain-forex.foundation',
  title: 'Forex piyasası nasıl çalışır?',
  titleEn: 'How does the forex market work?',
  objective: 'Forexte her kurun iki para birimi arasındaki göreli fiyat olduğunu öğren.',
  objectiveEn: 'Explain how every forex position expresses one currency relative to another.',
  minutes: 5,
  hook: 'EUR/USD aldığında aslında neyi alıp neyi satmış olursun?',
  hookEn: 'When you buy EUR/USD, what are you effectively buying and selling?',
  explanation: 'Forexte para birimleri çift hâlinde fiyatlanır. EUR/USD yükselirse euro, dolar karşısında güçlenmiştir. Kurun hareketi faiz farkları, ekonomik veriler ve risk algısından etkilenebilir; likidite ve spread gün içinde değişebilir.',
  explanationEn: 'In forex, currencies are quoted in pairs. If EUR/USD rises, the euro has appreciated relative to the dollar. The market is global and trades across major centers through much of the day, but liquidity and spreads can vary by session. Rate differentials, macro data, and risk sentiment can matter.',
  proExplanation: 'Spot, forward, swap ve futures yapıları aynı şey değildir. Kaldıraç, rollover/finansman maliyeti, venue ve karşı taraf riski ürün türüne göre değişebilir.',
  proExplanationEn: 'Spot, forwards, swaps, and futures are different structures. Leverage, rollover/financing costs, venue, and counterparty risk vary by product.',
  misconception: 'Bir para birimi tek başına “yükselmez”; hangi para birimine karşı değiştiğini söylemek gerekir.',
  misconceptionEn: 'Common mistake: saying a currency “rose” without specifying relative to which other currency.',
  takeaway: 'Kur, bir paranın diğerine göre fiyatıdır.',
  takeawayEn: 'Forex is a relative-price market; every exchange rate compares two currencies.',
  prerequisiteConceptKeys: ['economy.exchange_rates', 'market.microstructure.bid_ask'],
  relatedConceptKeys: ['economy.interest_rates', 'market.structure.liquidity'],
  visualAlt: 'Bir döviz çiftinde baz ve karşıt para birimini ve göreli fiyat hareketini gösteren sade forex şeması',
  visualAltEn: 'Simple forex diagram showing base and quote currencies and relative price movement',
  taskPrompt: 'EUR/USD yükseldiğinde en temel olarak ne olmuştur?',
  taskPromptEn: 'What has fundamentally happened when EUR/USD rises?',
  taskChoices: [
    { id: 'eur-up', label: 'Euro dolar karşısında göreli değer kazanmıştır', labelEn: 'The euro has appreciated relative to the dollar' },
    { id: 'all', label: 'Euro dünyadaki her varlığa karşı kesin değer kazanmıştır', labelEn: 'The euro has certainly appreciated against every asset' },
    { id: 'usd-gone', label: 'Doların değeri sıfırlanmıştır', labelEn: 'The dollar’s value has fallen to zero' },
  ],
  taskCorrectIds: ['eur-up'],
  questions: [
    { prompt: 'Forex fiyatları neden çift olarak yazılır?', promptEn: 'Why are forex prices quoted as pairs?', choices: [{ id: 'a', label: 'Bir paranın değerini diğerine göre gösterdiği için', labelEn: 'Because they show one currency’s value relative to another' }, { id: 'b', label: 'Her işlemde iki şirket olduğu için', labelEn: 'Because every trade involves two companies' }, { id: 'c', label: 'Grafikte iki mum olduğu için', labelEn: 'Because charts use two candles' }], correctId: 'a', explanation: 'Döviz kuru iki para arasındaki göreli fiyattır.', explanationEn: 'An exchange rate is the relative price between two currencies.' },
    { prompt: 'Forex likiditesi günün her saatinde tamamen aynı mıdır?', promptEn: 'Is forex liquidity identical at every hour?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız pazartesi değişir', labelEn: 'It changes only on Mondays' }], correctId: 'a', explanation: 'Seans örtüşmeleri ve piyasa katılımı likiditeyi değiştirebilir.', explanationEn: 'Session overlaps and participation can change liquidity.' },
    { prompt: 'Spot forex ile futures aynı ürün müdür?', promptEn: 'Are spot forex and futures the same product?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız fiyatları eşitse', labelEn: 'Only if their prices match' }], correctId: 'a', explanation: 'Sözleşme, işlem yeri ve finansman yapıları farklı olabilir.', explanationEn: 'Contract, venue, and financing structures can differ.' },
  ],
  sources: [FINANCIAL_MARKETS_SOURCES.forex],
});

const commodities = createFoundationLesson({
  id: 'lesson.markets.commodities.001',
  slug: 'emtia-piyasalari-nasil-calisir',
  conceptKey: 'market.commodities.basics',
  skillId: 'skill.financial-markets',
  competencyId: 'competency.explain-commodities.foundation',
  title: 'Emtia piyasaları nasıl çalışır?',
  titleEn: 'How do commodity markets work?',
  objective: 'Fiziksel emtia ile onu izleyen finansal sözleşmeleri ayırt etmeyi öğren.',
  objectiveEn: 'Explain why a physical commodity and a commodity futures contract are not the same thing.',
  minutes: 5,
  hook: 'Petrol fiyatını takip etmek, fiziksel petrol variline sahip olmak anlamına mı gelir?',
  hookEn: 'Does tracking oil prices mean you own a physical barrel of oil?',
  explanation: 'Emtia; altın, petrol ve buğday gibi temel ürünleri kapsar. Ekrandaki fiyat fiziksel spot piyasadan, vadeli sözleşmeden veya bu fiyatı izleyen bir fondan gelebilir. Vadeli sözleşme, fiziksel ürüne sahip olmakla aynı şey değildir.',
  explanationEn: 'Commodity markets cover physical goods such as energy, metals, and agricultural products. Prices investors see can come from spot markets, futures contracts, or financial products tracking them. Futures have maturities, delivery terms, and contract sizes; they are not the same as owning the physical commodity.',
  proExplanation: 'Depolama maliyeti, finansman, convenience yield, mevsimsellik ve stok koşulları futures eğrisini etkileyebilir. Contango ve backwardation spot yön tahmini olarak tek başına kullanılmamalıdır.',
  proExplanationEn: 'Storage costs, financing, convenience yield, seasonality, and inventories can shape the futures curve. Contango and backwardation should not be treated as standalone spot-direction forecasts.',
  misconception: 'Grafikte gördüğün her emtia fiyatını fiziksel ürünün anlık spot fiyatı sanma.',
  misconceptionEn: 'Common mistake: assuming every commodity chart price is the immediate cash price of the physical good.',
  takeaway: 'Önce hangi ürün veya sözleşmeyi izlediğini bil.',
  takeawayEn: 'Know which market or contract provides the commodity exposure; spot, futures, and fund structures differ.',
  prerequisiteConceptKeys: ['market.basics.instruments'],
  relatedConceptKeys: ['risk.volatility', 'market.execution.slippage'],
  visualAlt: 'Fiziksel emtia, spot fiyat ve vadeli işlem sözleşmesini ayrı katmanlarda gösteren sade emtia piyasası şeması',
  visualAltEn: 'Simple commodity-market diagram separating physical goods, spot prices, and futures contracts',
  taskPrompt: 'Petrol futures sözleşmesi almak ne anlama gelir?',
  taskPromptEn: 'What does buying an oil futures contract mean?',
  taskChoices: [
    { id: 'contract', label: 'Belirli vade ve koşulları olan finansal sözleşmeye taraf olmak', labelEn: 'Enter a financial contract with defined maturity and terms' },
    { id: 'barrel', label: 'Her durumda hemen fiziksel petrol varili teslim almak', labelEn: 'Always take immediate delivery of a physical oil barrel' },
    { id: 'stock', label: 'Otomatik olarak petrol şirketine ortak olmak', labelEn: 'Automatically own shares in an oil company' },
  ],
  taskCorrectIds: ['contract'],
  questions: [
    { prompt: 'Emtia futures sözleşmesi fiziksel mala sahip olmakla aynı mıdır?', promptEn: 'Is a commodity futures contract the same as owning the physical commodity?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Her zaman evet', labelEn: 'Always yes' }, { id: 'c', label: 'Yalnız altın için', labelEn: 'Only for gold' }], correctId: 'a', explanation: 'Futures belirli vade ve sözleşme koşullarına sahip türev üründür.', explanationEn: 'A futures contract is a derivative with defined maturity and contract terms.' },
    { prompt: 'Emtia futures fiyatlarını hangisi etkileyebilir?', promptEn: 'What can affect commodity futures prices?', choices: [{ id: 'a', label: 'Depolama, stok, finansman ve mevsimsellik', labelEn: 'Storage, inventories, financing, and seasonality' }, { id: 'b', label: 'Yalnız şirket logosu', labelEn: 'Only company logos' }, { id: 'c', label: 'Yalnız mum rengi', labelEn: 'Only candle color' }], correctId: 'a', explanation: 'Fiziksel piyasa koşulları ve taşıma maliyetleri vadeli fiyat yapısında önemlidir.', explanationEn: 'Physical-market conditions and carrying costs matter for futures pricing.' },
    { prompt: 'Spot ve futures fiyatları her zaman tamamen aynı mıdır?', promptEn: 'Are spot and futures prices always exactly the same?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız piyasa kapalıyken', labelEn: 'Only when markets are closed' }], correctId: 'a', explanation: 'Vade ve taşıma koşulları fiyatların ayrışmasına yol açabilir.', explanationEn: 'Maturity and carrying conditions can create differences.' },
  ],
  sources: [FINANCIAL_MARKETS_SOURCES.commodities],
});

export const FINANCIAL_MARKETS_FOUNDATION_LESSONS = [
  exchanges,
  indices,
  etf,
  bonds,
  forex,
  commodities,
] as const;
