import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { FUNDAMENTAL_ANALYSIS_SOURCES } from './fundamentalAnalysisSources';

const growthQuality = createFoundationLesson({
  id: 'lesson.fundamental.growth-quality.001',
  slug: 'buyume-kalitesi-nasil-okunur',
  conceptKey: 'fundamental.growth_quality',
  skillId: 'skill.fundamental-analysis',
  competencyId: 'competency.assess-growth-quality.foundation',
  title: 'Büyüme kalitesi nasıl okunur?',
  titleEn: 'How do you assess growth quality?',
  objective: 'Büyümenin yalnız oranını değil, kaynağını ve nakde dönüşümünü nasıl okuyacağını öğren.',
  objectiveEn: 'Evaluate revenue growth together with price, volume, acquisitions, margins, and cash generation.',
  minutes: 5,
  hook: 'İki şirket de %25 büyüyorsa büyümelerinin kalitesi aynı mıdır?',
  hookEn: 'If two companies both grow 25%, is the quality of that growth the same?',
  explanation: 'Büyüme oranı tek başına büyümenin kalitesini göstermez. Gelir; daha fazla satış, fiyat artışı, satın alma, kur etkisi veya geçici faktörlerle büyüyebilir. Marj ve işletme nakit akışı da güçleniyorsa tablo daha farklıdır; büyüme yüksekken ikisi zayıflıyorsa nedenini araştırmak gerekir.',
  explanationEn: 'A growth rate alone does not reveal the source or durability of growth. Revenue can rise through higher unit volume, pricing, new customers, acquisitions, FX effects, or temporary factors. Growth may have different financial quality when margins and operating cash flow strengthen at the same time; if growth is high while margins and cash keep weakening, the cause deserves separate review.',
  proExplanation: 'Organic vs acquired growth, constant-currency growth, cohort/retention metrics, unit economics ve capital intensity büyümenin kalitesini daha ayrıntılı ayırabilir. Her metrik iş modeline göre yorumlanmalıdır.',
  proExplanationEn: 'Organic versus acquired growth, constant-currency growth, cohort/retention metrics, unit economics, and capital intensity can help separate growth quality. Each metric depends on the business model.',
  misconception: 'En yüksek büyüme oranını otomatik olarak en yüksek kalite sanma.',
  misconceptionEn: 'Common mistake: automatically treating the company with the highest growth rate as the highest-quality company.',
  takeaway: 'Büyümenin kaynağını, marjını ve nakde dönüşümünü birlikte oku.',
  takeawayEn: 'Read not only the growth rate but also its source, margin profile, and cash conversion.',
  prerequisiteConceptKeys: ['fundamental.income_statement', 'fundamental.cash_flow', 'fundamental.profitability'],
  relatedConceptKeys: ['fundamental.valuation_multiples', 'fundamental.peer_comparison'],
  visualAlt: 'Aynı yüzde büyümeye ulaşan iki şirketin hacim, fiyat, marj ve nakit bileşenlerinin farklı olduğunu gösteren sade büyüme ağacı',
  visualAltEn: 'Simple growth tree showing two companies reaching the same growth rate through different volume, price, margin, and cash components',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/fundamental/growth-quality-001',
  taskPrompt: 'Hangisi büyüme kalitesini daha iyi sorgular?',
  taskPromptEn: 'Which question better assesses growth quality?',
  taskChoices: [
    { id: 'source', label: 'Büyümenin kaynağı ne ve marj/nakit bu büyümeyi destekliyor mu?', labelEn: 'What is driving growth, and do margins/cash support it?' },
    { id: 'rate', label: 'Yalnız yüzde kaç büyüdü?', labelEn: 'Only: what was the growth percentage?' },
    { id: 'price', label: 'Hisse bugün yeşil mi?', labelEn: 'Is the stock green today?' },
  ],
  taskCorrectIds: ['source'],
  questions: [
    { prompt: 'Gelir büyümesi hangi kaynaktan gelebilir?', promptEn: 'What can drive revenue growth?', choices: [{ id: 'a', label: 'Hacim, fiyat, satın alma veya kur etkisinden', labelEn: 'Volume, pricing, acquisitions, or FX effects' }, { id: 'b', label: 'Yalnız hisse fiyatından', labelEn: 'Only share price' }, { id: 'c', label: 'Yalnız borçtan', labelEn: 'Only debt' }], correctId: 'a', explanation: 'Aynı büyüme oranının arkasında farklı ekonomik mekanizmalar olabilir.', explanationEn: 'Different economic mechanisms can sit behind the same growth rate.' },
    { prompt: 'Yüksek büyüme tek başına kaliteyi garanti eder mi?', promptEn: 'Does high growth alone guarantee quality?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Marj, nakit ve sürdürülebilirlik ayrıca değerlendirilir.', explanationEn: 'Margins, cash, and sustainability require separate assessment.' },
    { prompt: 'Organik büyüme neyi ayırmaya yardım eder?', promptEn: 'What does organic growth help distinguish?', choices: [{ id: 'a', label: 'Mevcut işin kendi büyümesini satın alma kaynaklı büyümeden', labelEn: 'Growth from the existing business versus acquisition-driven growth' }, { id: 'b', label: 'RSI ile MACD’yi', labelEn: 'RSI from MACD' }, { id: 'c', label: 'Borcu nakitten', labelEn: 'Debt from cash' }], correctId: 'a', explanation: 'Satın almalar toplam büyümeyi artırabilir; organik ölçüm mevcut işin gelişimini ayırır.', explanationEn: 'Acquisitions can lift total growth; organic measures isolate development of the existing business.' },
  ],
  sources: [FUNDAMENTAL_ANALYSIS_SOURCES.accounting, FUNDAMENTAL_ANALYSIS_SOURCES.methodology],
});

const perShare = createFoundationLesson({
  id: 'lesson.fundamental.per-share.001',
  slug: 'hisse-basina-metrikler-neden-onemlidir',
  conceptKey: 'fundamental.per_share',
  skillId: 'skill.fundamental-analysis',
  competencyId: 'competency.interpret-per-share.foundation',
  title: 'Hisse başına metrikler neden önemlidir?',
  titleEn: 'Why do per-share metrics matter?',
  objective: 'Toplam kâr ile hisse başına kârın neden farklı hareket edebildiğini öğren.',
  objectiveEn: 'Distinguish total company earnings from earnings per share and explain how changes in share count can affect per-share outcomes.',
  minutes: 5,
  hook: 'Şirketin toplam kârı artarken EPS düşebilir mi?',
  hookEn: 'Can EPS fall while total company profit rises?',
  explanation: 'Yatırımcı şirketin tamamına değil belirli sayıda hisseye sahiptir. Bu yüzden toplam kâr kadar, kârın kaç hisseye bölündüğü de önemlidir. Yeni hisse ihracı pay başına kârı seyreltebilir; geri alım ise diğer koşullar aynıysa pay başına sonucu artırabilir.',
  explanationEn: 'An investor economically owns a number of shares rather than the whole company. So the number of shares over which earnings are spread matters alongside total profit. EPS can be thought of as earnings attributable to shareholders divided by weighted average shares. New issuance can dilute per-share results; buybacks can lift them if other conditions are unchanged. The financing and valuation of buybacks still require separate assessment.',
  proExplanation: 'Basic vs diluted EPS, options/convertibles, stock-based compensation ve treasury-stock method gibi unsurlar fully diluted share count analizinde önem kazanabilir.',
  proExplanationEn: 'Basic versus diluted EPS, options/convertibles, stock-based compensation, and the treasury-stock method can matter when analyzing fully diluted share count.',
  misconception: 'Toplam kâr arttı diye hisse başına kârın da aynı oranda arttığını varsayma.',
  misconceptionEn: 'Common mistake: assuming that if total profit grows, the economic claim of each share grows at the same rate.',
  takeaway: 'Toplam kârla birlikte hisse sayısını ve pay başına sonucu izle.',
  takeawayEn: 'Track not only company totals but also per-share economics and share count.',
  prerequisiteConceptKeys: ['fundamental.income_statement'],
  relatedConceptKeys: ['fundamental.valuation_multiples', 'fundamental.growth_quality'],
  visualAlt: 'Aynı toplam kârın farklı hisse sayılarına bölündüğünde farklı EPS ürettiğini gösteren sade paylaştırma görseli',
  visualAltEn: 'Simple allocation visual showing the same total earnings producing different EPS under different share counts',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/fundamental/per-share-001',
  taskPrompt: 'Net kâr %10 artarken hisse sayısı %20 arttı. Hangisini ayrıca kontrol etmelisin?',
  taskPromptEn: 'Net income rose 10% while share count rose 20%. What should you check separately?',
  taskChoices: [
    { id: 'eps', label: 'EPS ve seyrelme etkisini', labelEn: 'EPS and dilution' },
    { id: 'ignore', label: 'Hisse sayısını tamamen yok saymak', labelEn: 'Ignore share count completely' },
    { id: 'chart', label: 'Yalnız mum rengini', labelEn: 'Only candle color' },
  ],
  taskCorrectIds: ['eps'],
  questions: [
    { prompt: 'EPS neyi ilişkilendirir?', promptEn: 'What does EPS relate?', choices: [{ id: 'a', label: 'Kârı hisse sayısına', labelEn: 'Earnings to share count' }, { id: 'b', label: 'Borcu RSI’a', labelEn: 'Debt to RSI' }, { id: 'c', label: 'Geliri yalnız nakde', labelEn: 'Revenue only to cash' }], correctId: 'a', explanation: 'EPS pay başına düşen kârı ölçmeye çalışır.', explanationEn: 'EPS seeks to measure earnings per share.' },
    { prompt: 'Yeni hisse ihracı ne yaratabilir?', promptEn: 'What can new share issuance create?', choices: [{ id: 'a', label: 'Seyrelme', labelEn: 'Dilution' }, { id: 'b', label: 'Kesin kâr artışı', labelEn: 'Certain profit growth' }, { id: 'c', label: 'Borçların otomatik silinmesi', labelEn: 'Automatic debt elimination' }], correctId: 'a', explanation: 'Daha fazla hisse aynı ekonomik sonucun daha fazla paya bölünmesine neden olabilir.', explanationEn: 'More shares can spread the same economic result across more units.' },
    { prompt: 'Toplam net kâr artışı EPS artışını garanti eder mi?', promptEn: 'Does growth in total net income guarantee EPS growth?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Hisse sayısı da değişebilir.', explanationEn: 'Share count can change too.' },
  ],
  sources: [FUNDAMENTAL_ANALYSIS_SOURCES.accounting, FUNDAMENTAL_ANALYSIS_SOURCES.methodology],
});

const multiples = createFoundationLesson({
  id: 'lesson.fundamental.valuation-multiples.001',
  slug: 'degerleme-carpanlari-nasil-okunur',
  conceptKey: 'fundamental.valuation_multiples',
  skillId: 'skill.fundamental-analysis',
  competencyId: 'competency.interpret-valuation-multiples.foundation',
  title: 'Değerleme çarpanları nasıl okunur?',
  titleEn: 'How do you read valuation multiples?',
  objective: 'Değerleme çarpanlarının neyi karşılaştırdığını ve neden tek başına ucuzluk kanıtı olmadığını öğren.',
  objectiveEn: 'Explain that P/E, EV/EBITDA, and similar multiples relate price/value to a financial performance measure and that a low or high multiple alone does not prove cheapness or expensiveness.',
  minutes: 5,
  hook: 'P/E’si 8 olan şirket, P/E’si 25 olan şirketten kesin daha ucuz mudur?',
  hookEn: 'Is a company at 8x P/E definitely cheaper than one at 25x?',
  explanation: 'Çarpanlar piyasanın bir finansal ölçünün her bir birimine ne kadar değer verdiğini özetler. P/E kârla, EV/EBITDA faaliyet bazlı kârla ilişki kurar. Ama büyüme, marj, borç ve sektör farklıysa aynı çarpan farklı anlama gelebilir. Düşük çarpan tek başına ucuzluk değildir.',
  explanationEn: 'A valuation multiple summarizes how much value the market assigns to each unit of a financial measure. P/E relates equity value to earnings; EV/EBITDA relates enterprise value to an operating earnings measure. But the same multiple can mean different things when growth, margins, capital needs, balance-sheet risk, cyclicality, and accounting quality differ. A low multiple may reflect risk or falling expected earnings, while a high multiple may reflect stronger expectations; neither is a certain conclusion.',
  proExplanation: 'Forward vs trailing metrics, normalized cycle earnings, negative denominators, lease treatment, stock compensation and capitalized costs can materially alter comparability. Multiple choice should match business economics.',
  proExplanationEn: 'Forward versus trailing metrics, normalized cycle earnings, negative denominators, lease treatment, stock compensation, and capitalized costs can materially alter comparability. The chosen multiple should fit business economics.',
  misconception: 'En düşük çarpanı otomatik olarak en ucuz ve en iyi fırsat sayma.',
  misconceptionEn: 'Common mistake: automatically treating the lowest multiple as the cheapest and best opportunity.',
  takeaway: 'Çarpanı büyüme, kalite, risk ve sektörle birlikte oku.',
  takeawayEn: 'A multiple is a comparison tool; it does not judge value without growth, quality, risk, and industry context.',
  prerequisiteConceptKeys: ['fundamental.profitability', 'fundamental.debt_liquidity', 'fundamental.per_share'],
  relatedConceptKeys: ['fundamental.peer_comparison', 'fundamental.dcf', 'fundamental.growth_quality'],
  visualAlt: 'P/E ve EV/EBITDA gibi çarpanların fiyat/değer ile kâr ölçülerini bağladığını gösteren sade oran kartları',
  visualAltEn: 'Simple ratio cards showing P/E and EV/EBITDA linking price/value to earnings measures',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/fundamental/multiples-001',
  taskPrompt: 'A şirketi 10x, B şirketi 22x P/E. İlk doğru yaklaşım hangisidir?',
  taskPromptEn: 'Company A trades at 10x and B at 22x P/E. What is the right first approach?',
  taskChoices: [
    { id: 'context', label: 'Büyüme, risk, marj, sektör ve kâr kalitesini karşılaştırmak', labelEn: 'Compare growth, risk, margins, industry, and earnings quality' },
    { id: 'cheap', label: '10x olduğu için A kesin ucuzdur', labelEn: 'A is certainly cheap because it is 10x' },
    { id: 'expensive', label: '22x olduğu için B kesin pahalıdır', labelEn: 'B is certainly expensive because it is 22x' },
  ],
  taskCorrectIds: ['context'],
  questions: [
    { prompt: 'P/E neyi ilişkilendirir?', promptEn: 'What does P/E relate?', choices: [{ id: 'a', label: 'Özkaynak değerini kâra', labelEn: 'Equity value to earnings' }, { id: 'b', label: 'Borcu hacme', labelEn: 'Debt to volume' }, { id: 'c', label: 'Nakit akışını RSI’a', labelEn: 'Cash flow to RSI' }], correctId: 'a', explanation: 'P/E piyasa fiyatı/değeri ile hisse başına veya toplam kârı ilişkilendirir.', explanationEn: 'P/E relates market price/value to per-share or total earnings.' },
    { prompt: 'Düşük P/E kesin ucuzluk mudur?', promptEn: 'Does a low P/E prove cheapness?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Düşük çarpan risk, düşük büyüme veya zayıf kâr beklentisini yansıtabilir.', explanationEn: 'A low multiple can reflect risk, low growth, or weak earnings expectations.' },
    { prompt: 'Çarpan karşılaştırmasında ne önemlidir?', promptEn: 'What matters when comparing multiples?', choices: [{ id: 'a', label: 'Benzer iş modeli ve finansal bağlam', labelEn: 'Comparable business model and financial context' }, { id: 'b', label: 'Yalnız şirket adı', labelEn: 'Only company name' }, { id: 'c', label: 'Yalnız günlük fiyat değişimi', labelEn: 'Only daily price change' }], correctId: 'a', explanation: 'Karşılaştırılabilirlik çarpan analizinin temel koşuludur.', explanationEn: 'Comparability is a core condition for multiple analysis.' },
  ],
  sources: [FUNDAMENTAL_ANALYSIS_SOURCES.accounting, FUNDAMENTAL_ANALYSIS_SOURCES.methodology],
});

const dcf = createFoundationLesson({
  id: 'lesson.fundamental.dcf.001',
  slug: 'dcf-mantigi-nedir',
  conceptKey: 'fundamental.dcf',
  skillId: 'skill.fundamental-analysis',
  competencyId: 'competency.explain-dcf.foundation',
  title: 'DCF mantığı nedir?',
  titleEn: 'What is the logic of DCF?',
  objective: 'DCF’nin gelecekteki nakitleri bugünkü değere nasıl çevirdiğini ve varsayım riskini öğren.',
  objectiveEn: 'Explain discounted cash flow as a framework for estimating the present value of future cash flows and emphasize assumption sensitivity.',
  minutes: 5,
  hook: '10 yıl sonra alınacak 100 lira bugün 100 lira ile aynı değerde midir?',
  hookEn: 'Is 100 received ten years from now worth the same as 100 today?',
  explanation: 'DCF, gelecekte beklenen nakit akışlarını iskonto oranıyla bugünkü değere çevirir. Büyüme, marj, terminal değer veya iskonto oranındaki küçük değişiklikler sonucu ciddi biçimde değiştirebilir. Bu yüzden DCF tek doğru fiyat değil, varsayımlara bağlı bir değer aralığı üretmeye daha uygundur.',
  explanationEn: 'DCF estimates cash flows a business may generate in the future and discounts them to present value using a rate intended to reflect risk and the time value of money. The logic is simple, but the output is highly assumption-sensitive. Small changes in growth, margins, reinvestment needs, terminal value, or discount rate can materially change the result. DCF therefore does not produce one certain “correct price”; it is better treated as a range conditional on assumptions.',
  proExplanation: 'FCFF vs FCFE, WACC, terminal growth, exit multiple, mid-year convention ve scenario analysis model tasarımına göre değişir. Terminal value birçok modelde toplam değerin büyük bölümünü oluşturduğu için ayrı hassasiyet kontrolü gerekir.',
  proExplanationEn: 'FCFF versus FCFE, WACC, terminal growth, exit multiples, mid-year conventions, and scenario analysis depend on model design. Terminal value often represents a large share of total value and deserves separate sensitivity testing.',
  misconception: 'DCF’de çıkan tek sayıyı kesin gerçek değer sanma.',
  misconceptionEn: 'Common mistake: treating one model output as an objective and certain “true value.”',
  takeaway: 'DCF tek fiyat değil, varsayımlara bağlı değer aralığı üretir.',
  takeawayEn: 'DCF is an assumption engine: it helps reason about a value range through cash, time, and risk.',
  prerequisiteConceptKeys: ['fundamental.cash_flow', 'fundamental.growth_quality', 'fundamental.debt_liquidity'],
  relatedConceptKeys: ['fundamental.valuation_multiples', 'risk.basics'],
  visualAlt: 'Gelecek yıllardaki nakit akışlarının iskonto oranıyla bugüne küçülerek geldiğini gösteren sade zaman çizgisi',
  visualAltEn: 'Simple timeline showing future cash flows shrinking back to present value through discounting',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/fundamental/dcf-001',
  taskPrompt: 'DCF’de iskonto oranı yükselirse, diğer her şey aynıyken bugünkü değer genellikle ne olur?',
  taskPromptEn: 'If the discount rate rises in a DCF, with everything else unchanged, what generally happens to present value?',
  taskChoices: [
    { id: 'down', label: 'Düşer', labelEn: 'Falls' },
    { id: 'up', label: 'Kesin yükselir', labelEn: 'Definitely rises' },
    { id: 'same', label: 'Her zaman aynı kalır', labelEn: 'Always stays the same' },
  ],
  taskCorrectIds: ['down'],
  questions: [
    { prompt: 'DCF neyi bugüne indirger?', promptEn: 'What does DCF discount to the present?', choices: [{ id: 'a', label: 'Tahmini gelecekteki nakit akışlarını', labelEn: 'Estimated future cash flows' }, { id: 'b', label: 'Yalnız geçmiş hisse fiyatını', labelEn: 'Only historical share price' }, { id: 'c', label: 'Yalnız işlem hacmini', labelEn: 'Only trading volume' }], correctId: 'a', explanation: 'DCF’nin merkezinde gelecekteki nakitlerin bugünkü değeri vardır.', explanationEn: 'DCF centers on the present value of future cash.' },
    { prompt: 'DCF sonucu varsayımlara duyarlı mıdır?', promptEn: 'Is a DCF output sensitive to assumptions?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız bankalarda', labelEn: 'Only for banks' }], correctId: 'a', explanation: 'Büyüme ve iskonto gibi küçük değişiklikler sonucu büyük ölçüde etkileyebilir.', explanationEn: 'Small changes in growth or discount assumptions can materially alter results.' },
    { prompt: 'DCF tek kesin doğru fiyat verir mi?', promptEn: 'Does DCF provide one certain correct price?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Model varsayımlara bağlı değer aralığı ve senaryo düşüncesi sunar.', explanationEn: 'The model supports assumption-dependent ranges and scenario thinking.' },
  ],
  sources: [FUNDAMENTAL_ANALYSIS_SOURCES.methodology],
});

const peers = createFoundationLesson({
  id: 'lesson.fundamental.peer-comparison.001',
  slug: 'benzer-sirket-karsilastirmasi-nasil-yapilir',
  conceptKey: 'fundamental.peer_comparison',
  skillId: 'skill.fundamental-analysis',
  competencyId: 'competency.compare-peers.foundation',
  title: 'Benzer şirket karşılaştırması nasıl yapılır?',
  titleEn: 'How do you compare peer companies?',
  objective: 'Benzer şirket seçerken yalnız sektör etiketinin neden yetmediğini öğren.',
  objectiveEn: 'Explain why business model, geography, growth, margins, capital structure, and accounting differences matter when selecting comparable companies.',
  minutes: 5,
  hook: 'İki şirket aynı sektördeyse otomatik olarak iyi karşılaştırılabilir mi?',
  hookEn: 'If two companies are in the same sector, are they automatically good comparables?',
  explanation: 'Peer analizi şirketi benzer işletmelerle kıyaslar. Ama aynı sektörde olmak yeterli değildir. Gelir modeli, coğrafya, büyüme, marj, borç ve ölçek farklıysa çarpanların doğrudan kıyası yanıltıcı olabilir. Önemli olan hangi farkların sonucu etkilediğini bilmektir.',
  explanationEn: 'Peer analysis creates financial and valuation context by comparing a company with similar businesses. But an industry label alone is not enough. If revenue model, customer type, geography, growth, margins, debt, capital intensity, or scale differ, direct multiple comparisons can mislead. A good peer set is not a perfect match; it is a comparison group where important differences are made explicit.',
  proExplanation: 'Conglomerates, segment mix, accounting policy, fiscal-year timing and cyclicality can require sum-of-the-parts or normalized comparisons rather than headline peer multiples.',
  proExplanationEn: 'Conglomerates, segment mix, accounting policy, fiscal-year timing, and cyclicality can require sum-of-the-parts or normalized comparisons instead of headline peer multiples.',
  misconception: 'Aynı sektördeki şirketleri otomatik olarak eşdeğer peer sayma.',
  misconceptionEn: 'Common mistake: treating companies with the same sector code as automatically equivalent peers.',
  takeaway: 'Peer karşılaştırmasında benzerlik kadar farkları da tanımla.',
  takeawayEn: 'Peer comparison requires making differences explicit as well as similarities.',
  prerequisiteConceptKeys: ['fundamental.valuation_multiples', 'fundamental.growth_quality', 'fundamental.profitability'],
  relatedConceptKeys: ['fundamental.analysis_limits'],
  visualAlt: 'Aynı sektör içindeki üç şirketin büyüme, marj, borç ve iş modeli özellikleriyle filtrelendiği sade peer matrisi',
  visualAltEn: 'Simple peer matrix filtering three same-sector companies by growth, margin, debt, and business-model characteristics',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/fundamental/peers-001',
  taskPrompt: 'Aynı sektörde iki şirketin P/E’sini kıyaslamadan önce neyi kontrol etmelisin?',
  taskPromptEn: 'Before comparing the P/E of two companies in the same sector, what should you check?',
  taskChoices: [
    { id: 'comparable', label: 'Büyüme, marj, borç ve iş modelinin ne kadar benzer olduğunu', labelEn: 'How similar their growth, margins, debt, and business models are' },
    { id: 'sector', label: 'Sektör adı aynıysa başka hiçbir şey gerekmez', labelEn: 'Nothing else matters if the sector name matches' },
    { id: 'color', label: 'Logo renklerini', labelEn: 'Logo colors' },
  ],
  taskCorrectIds: ['comparable'],
  questions: [
    { prompt: 'Peer seçerken sektör etiketi tek başına yeterli midir?', promptEn: 'Is an industry label alone enough for peer selection?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'İş modeli ve finansal yapı farklılıkları karşılaştırmayı etkiler.', explanationEn: 'Business-model and financial-structure differences affect comparability.' },
    { prompt: 'Peer analizinin amacı nedir?', promptEn: 'What is the purpose of peer analysis?', choices: [{ id: 'a', label: 'Bağlamlı karşılaştırma yapmak', labelEn: 'Create a contextual comparison' }, { id: 'b', label: 'Kesin hedef fiyat üretmek', labelEn: 'Produce a certain target price' }, { id: 'c', label: 'Grafik formasyonu bulmak', labelEn: 'Find chart patterns' }], correctId: 'a', explanation: 'Peer analizi göreli finansal/değerleme bağlamı sağlar.', explanationEn: 'Peer analysis provides relative financial and valuation context.' },
    { prompt: 'Aynı P/E iki farklı şirkette aynı anlamı taşır mı?', promptEn: 'Does the same P/E mean the same thing for two different companies?', choices: [{ id: 'a', label: 'Zorunlu olarak hayır; büyüme ve risk farklı olabilir', labelEn: 'Not necessarily; growth and risk can differ' }, { id: 'b', label: 'Her zaman evet', labelEn: 'Always yes' }, { id: 'c', label: 'Sadece fiyat aynıysa', labelEn: 'Only if price is the same' }], correctId: 'a', explanation: 'Çarpanın anlamı temel iş özelliklerine bağlıdır.', explanationEn: 'The meaning of a multiple depends on underlying business characteristics.' },
  ],
  sources: [FUNDAMENTAL_ANALYSIS_SOURCES.accounting, FUNDAMENTAL_ANALYSIS_SOURCES.methodology],
});

const limits = createFoundationLesson({
  id: 'lesson.fundamental.analysis-limits.001',
  slug: 'temel-analizin-sinirlari',
  conceptKey: 'fundamental.analysis_limits',
  skillId: 'skill.fundamental-analysis',
  competencyId: 'competency.explain-fundamental-limits.foundation',
  title: 'Temel analizin sınırları nelerdir?',
  titleEn: 'What are the limits of fundamental analysis?',
  objective: 'Temel analizin şirketi anlamaya yardım ettiğini ama fiyat yönünü garanti etmediğini öğren.',
  objectiveEn: 'Explain that financial statements are backward-looking, forecasts are uncertain, valuation is assumption-dependent, and a quality company is not the same concept as an attractive investment price.',
  minutes: 5,
  hook: 'Çok iyi bir şirketin hissesi her fiyattan iyi yatırım mıdır?',
  hookEn: 'Is a very good company a good investment at every price?',
  explanation: 'Temel analiz şirketin ekonomik yapısını ve olası değerini anlamaya yardım eder; geleceği kesinleştirmez. Tablolar geçmişi raporlar, tahminler değişebilir ve iyi şirket her fiyatta iyi yatırım olmayabilir. Ödenen fiyat ve beklentiler sonucu etkiler.',
  explanationEn: 'Fundamental analysis helps understand a company’s economics, financial performance, and possible value; it does not make the future certain. Financial statements report past periods, management forecasts can change, and competition or macro conditions can shift unexpectedly. A good company is also not the same thing as a good investment: the price paid and expectations matter. Valuation outputs depend on assumptions.',
  proExplanation: 'Accounting estimates, management incentives, disclosure quality, regime shifts, tail risks and reflexivity can limit model reliability. Scenario ranges and explicit uncertainty are preferable to single-point certainty.',
  proExplanationEn: 'Accounting estimates, management incentives, disclosure quality, regime shifts, tail risks, and reflexivity can limit model reliability. Scenario ranges and explicit uncertainty are preferable to single-point certainty.',
  misconception: 'Güçlü bilanço ve büyümeyi otomatik “hisse yükselecek” sonucuna çevirme.',
  misconceptionEn: 'Common mistake: converting a strong balance sheet and growth profile directly into “the stock will rise.”',
  takeaway: 'Temel analiz şirketi anlamaya yardım eder; fiyat yönünü garanti etmez.',
  takeawayEn: 'Fundamental analysis helps understand the company and the price; it does not guarantee future direction.',
  prerequisiteConceptKeys: ['fundamental.financial_statements', 'fundamental.valuation_multiples', 'fundamental.dcf'],
  relatedConceptKeys: ['risk.basics', 'evidence.data_quality', 'behavior.confirmation_bias'],
  visualAlt: 'Finansal tablolar, tahminler ve değerleme modelinden bir değer aralığına giden; belirsizlik bandı içeren sade analiz şeması',
  visualAltEn: 'Simple analysis diagram moving from financial statements, forecasts, and valuation models to a value range with an uncertainty band',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/fundamental/limits-001',
  taskPrompt: 'Şirket finansalları çok güçlü. En güvenli sonuç hangisidir?',
  taskPromptEn: 'A company has very strong financials. Which conclusion is safest?',
  taskChoices: [
    { id: 'quality', label: 'Finansal kalite güçlü olabilir; gelecekteki fiyat yönü ve uygun değer ayrıca değerlendirilir', labelEn: 'Financial quality may be strong; future price direction and appropriate value still require separate assessment' },
    { id: 'up', label: 'Hisse kesin yükselir', labelEn: 'The stock will definitely rise' },
    { id: 'anyprice', label: 'Her fiyattan iyi yatırımdır', labelEn: 'It is a good investment at any price' },
  ],
  taskCorrectIds: ['quality'],
  questions: [
    { prompt: 'Temel analiz geleceği kesinleştirir mi?', promptEn: 'Does fundamental analysis make the future certain?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız büyük şirketlerde', labelEn: 'Only for large companies' }], correctId: 'a', explanation: 'Analiz belirsizliği düzenler; ortadan kaldırmaz.', explanationEn: 'Analysis structures uncertainty; it does not eliminate it.' },
    { prompt: 'İyi şirket ve iyi yatırım aynı kavram mıdır?', promptEn: 'Are a good company and a good investment the same concept?', choices: [{ id: 'a', label: 'Hayır; fiyat ve beklenti de önemlidir', labelEn: 'No; price and expectations also matter' }, { id: 'b', label: 'Her zaman evet', labelEn: 'Always yes' }, { id: 'c', label: 'Yalnız P/E düşükse', labelEn: 'Only if P/E is low' }], correctId: 'a', explanation: 'Kalite ile ödenen değer/fiyat ayrı boyutlardır.', explanationEn: 'Business quality and the value/price paid are separate dimensions.' },
    { prompt: 'Tek değerleme sonucu neden kesin değildir?', promptEn: 'Why is one valuation output not certain?', choices: [{ id: 'a', label: 'Varsayımlara ve gelecekteki gerçekleşmelere bağlıdır', labelEn: 'It depends on assumptions and future outcomes' }, { id: 'b', label: 'Çünkü matematik çalışmaz', labelEn: 'Because mathematics does not work' }, { id: 'c', label: 'Yalnız grafik eksik olduğu için', labelEn: 'Only because a chart is missing' }], correctId: 'a', explanation: 'Model girdileri değiştikçe sonuç da değişir.', explanationEn: 'Outputs change when model inputs and future outcomes change.' },
  ],
  sources: [FUNDAMENTAL_ANALYSIS_SOURCES.methodology, FUNDAMENTAL_ANALYSIS_SOURCES.statements],
});

export const FUNDAMENTAL_ANALYSIS_EXPANSION_LESSONS = [
  growthQuality,
  perShare,
  multiples,
  dcf,
  peers,
  limits,
] as const;
