import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { FUNDAMENTAL_ANALYSIS_SOURCES } from './fundamentalAnalysisSources';

const statements = createFoundationLesson({
  id: 'lesson.fundamental.statements.001',
  slug: 'finansal-tablolar-birlikte-ne-anlatir',
  conceptKey: 'fundamental.financial_statements',
  skillId: 'skill.fundamental-analysis',
  competencyId: 'competency.connect-financial-statements.foundation',
  title: 'Finansal tablolar birlikte ne anlatır?',
  titleEn: 'What do financial statements tell us together?',
  objective: 'Üç temel finansal tablonun farklı sorulara cevap verdiğini ve birlikte okunması gerektiğini öğren.',
  objectiveEn: 'Explain that the income statement, balance sheet, and cash-flow statement answer different questions and should be read together.',
  minutes: 5,
  hook: 'Bir şirket kâr açıkladıysa kasasında mutlaka aynı miktarda para mı vardır?',
  hookEn: 'If a company reports profit, must it have the same amount of cash in the bank?',
  explanation: 'Üç temel tablo aynı şirketi farklı açıdan gösterir. Gelir tablosu dönem içindeki kârı, bilanço belirli tarihte varlık ve borçları, nakit akışı ise gerçek para hareketini gösterir. Kâr artarken nakit zayıflayabilir veya borç büyüyebilir; bu yüzden üçü birlikte okunur.',
  explanationEn: 'The three core financial statements show the same company from different angles. The income statement shows revenue, expenses, and profit over a period; the balance sheet shows assets, liabilities, and equity at a point in time; the cash-flow statement shows where cash actually came from and went. No single statement provides the full picture. Profit can rise while cash weakens or debt grows, so the statements should be connected.',
  proExplanation: 'Accrual accounting nedeniyle gelir ve giderlerin muhasebeleşme zamanı nakit hareketinden farklı olabilir. Bu yüzden earnings quality, working capital ve financing flows tablolar arası bağlantıda önem kazanır.',
  proExplanationEn: 'Under accrual accounting, revenue and expenses can be recognized at different times from cash movements. Earnings quality, working capital, and financing flows therefore matter when connecting the statements.',
  misconception: 'Yalnız net kâra bakıp şirketin tamamını anladığını düşünme.',
  misconceptionEn: 'Common mistake: looking only at net income and assuming it describes the entire financial condition.',
  takeaway: 'Kârı, finansal konumu ve gerçek nakdi birlikte oku.',
  takeawayEn: 'The income statement shows performance, the balance sheet financial position, and cash flow actual cash movement; read all three together.',
  prerequisiteConceptKeys: ['market.basics.instruments'],
  relatedConceptKeys: ['fundamental.income_statement', 'fundamental.balance_sheet', 'fundamental.cash_flow'],
  visualAlt: 'Gelir tablosu, bilanço ve nakit akış tablosunun aynı şirkete bağlandığını gösteren üç parçalı sade finansal tablo şeması',
  visualAltEn: 'Simple three-part diagram connecting the income statement, balance sheet, and cash-flow statement to the same company',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/fundamental/statements-001',
  taskPrompt: 'Şirket net kâr açıklıyor ama işletme nakit akışı sürekli negatif. En doğru ilk yaklaşım hangisidir?',
  taskPromptEn: 'A company reports net income but operating cash flow remains negative. What is the best first approach?',
  taskChoices: [
    { id: 'connect', label: 'Kârın nakde neden dönüşmediğini tablolar arasında incelemek', labelEn: 'Investigate across the statements why profit is not converting into cash' },
    { id: 'profit', label: 'Net kâr pozitif olduğu için diğer tabloları yok saymak', labelEn: 'Ignore the other statements because net income is positive' },
    { id: 'price', label: 'Yalnız hisse fiyatına bakmak', labelEn: 'Look only at the share price' },
  ],
  taskCorrectIds: ['connect'],
  questions: [
    { prompt: 'Bilanço neyi gösterir?', promptEn: 'What does a balance sheet show?', choices: [{ id: 'a', label: 'Belirli bir tarihte varlık, borç ve özkaynağı', labelEn: 'Assets, liabilities, and equity at a point in time' }, { id: 'b', label: 'Yalnız günlük hisse fiyatını', labelEn: 'Only the daily share price' }, { id: 'c', label: 'Gelecek yılın kesin kârını', labelEn: 'Certain profit next year' }], correctId: 'a', explanation: 'Bilanço şirketin belirli bir andaki finansal konumunu gösterir.', explanationEn: 'The balance sheet shows financial position at a specific point in time.' },
    { prompt: 'Net kâr ile nakit aynı şey midir?', promptEn: 'Are net income and cash the same thing?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Her zaman evet', labelEn: 'Always yes' }, { id: 'c', label: 'Yalnız bankalarda', labelEn: 'Only for banks' }], correctId: 'a', explanation: 'Tahakkuk muhasebesi nedeniyle kâr ile nakit hareketi farklılaşabilir.', explanationEn: 'Accrual accounting can make profit and cash movement differ.' },
    { prompt: 'Finansal tablolar neden birlikte okunur?', promptEn: 'Why read financial statements together?', choices: [{ id: 'a', label: 'Her biri şirketin farklı bir boyutunu gösterir', labelEn: 'Each shows a different dimension of the company' }, { id: 'b', label: 'Hepsi tamamen aynı bilgiyi tekrarlar', labelEn: 'They all repeat exactly the same information' }, { id: 'c', label: 'Sadece sayfa sayısı artsın diye', labelEn: 'Only to increase page count' }], correctId: 'a', explanation: 'Performans, finansal konum ve nakit hareketi farklı ama bağlantılıdır.', explanationEn: 'Performance, financial position, and cash movement are different but connected.' },
  ],
  sources: [FUNDAMENTAL_ANALYSIS_SOURCES.statements, FUNDAMENTAL_ANALYSIS_SOURCES.methodology],
});

const incomeStatement = createFoundationLesson({
  id: 'lesson.fundamental.income-statement.001',
  slug: 'gelir-tablosu-nasil-okunur',
  conceptKey: 'fundamental.income_statement',
  skillId: 'skill.fundamental-analysis',
  competencyId: 'competency.read-income-statement.foundation',
  title: 'Gelir tablosu nasıl okunur?',
  titleEn: 'How do you read an income statement?',
  objective: 'Satıştan net kâra giderken paranın hangi aşamalarda azaldığını öğren.',
  objectiveEn: 'Distinguish the basic flow from revenue to gross profit, operating profit, and net income.',
  minutes: 5,
  hook: 'Satışlar %20 arttıysa şirketin kârı da %20 artmak zorunda mıdır?',
  hookEn: 'If sales rise 20%, must company profit also rise 20%?',
  explanation: 'Gelir tablosu, satıştan sonra hangi maliyet ve giderlerin kârı azalttığını gösterir. Satış maliyeti sonrası brüt kâr, faaliyet giderleri sonrası faaliyet kârı, faiz ve vergi sonrası net kâr kalır. Satış artarken maliyetler daha hızlı büyürse net kâr düşebilir.',
  explanationEn: 'The income statement shows how much revenue a company generated during a period and the costs and expenses incurred to generate it. Revenue less cost of sales gives gross profit; after operating expenses comes operating profit; after interest, taxes, and other items comes net income. Revenue growth matters, but if costs rise faster, margins and net income can weaken.',
  proExplanation: 'Tek seferlik gelir/giderler, stock-based compensation, restructuring, impairment ve segment mix değişimleri raporlanan kârı etkileyebilir. Normalized earnings analizi bu kalemleri ayrıca değerlendirir.',
  proExplanationEn: 'One-off income or expenses, stock-based compensation, restructuring, impairments, and segment mix shifts can affect reported profit. Normalized earnings analysis evaluates these separately.',
  misconception: 'Satış büyümesini otomatik olarak daha yüksek kâr sanma.',
  misconceptionEn: 'Common mistake: treating revenue growth as automatic profit growth.',
  takeaway: 'Satıştan sonra ne kadar kaldığını ve neden kaldığını izle.',
  takeawayEn: 'On the income statement, look beyond sales to costs and where profit is created or lost.',
  prerequisiteConceptKeys: ['fundamental.financial_statements'],
  relatedConceptKeys: ['fundamental.profitability', 'fundamental.cash_flow'],
  visualAlt: 'Gelirden brüt kâr, faaliyet kârı ve net kâra inen sade gelir tablosu şelalesi',
  visualAltEn: 'Simple income-statement waterfall from revenue to gross profit, operating profit, and net income',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/fundamental/income-statement-001',
  taskPrompt: 'Gelir %15 artarken net kâr düşüyorsa ilk hangi soruyu sormalısın?',
  taskPromptEn: 'If revenue rises 15% while net income falls, what should you ask first?',
  taskChoices: [
    { id: 'costs', label: 'Maliyet ve giderler gelirden daha hızlı mı arttı?', labelEn: 'Did costs and expenses rise faster than revenue?' },
    { id: 'ignore', label: 'Gelir arttığı için kâr düşüşünü yok saymak', labelEn: 'Ignore lower profit because revenue rose' },
    { id: 'ticker', label: 'Hisse kodunun uzunluğu değişti mi?', labelEn: 'Did the ticker length change?' },
  ],
  taskCorrectIds: ['costs'],
  questions: [
    { prompt: 'Brüt kâr neyin ardından oluşur?', promptEn: 'What produces gross profit?', choices: [{ id: 'a', label: 'Gelirden satış maliyeti çıkarılınca', labelEn: 'Revenue minus cost of sales' }, { id: 'b', label: 'Hisse fiyatı yükselince', labelEn: 'When share price rises' }, { id: 'c', label: 'Borç tamamen sıfırlanınca', labelEn: 'When debt becomes zero' }], correctId: 'a', explanation: 'Brüt kâr ürün veya hizmetin doğrudan maliyeti sonrası kalan tutardır.', explanationEn: 'Gross profit is what remains after direct cost of sales.' },
    { prompt: 'Gelir artarken net kâr düşebilir mi?', promptEn: 'Can net income fall while revenue rises?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız teknoloji şirketlerinde', labelEn: 'Only in technology companies' }], correctId: 'a', explanation: 'Maliyetler, giderler, faiz veya vergi daha hızlı artabilir.', explanationEn: 'Costs, expenses, interest, or taxes can rise faster.' },
    { prompt: 'Net kâr gelir tablosunda neyi temsil eder?', promptEn: 'What does net income represent on the income statement?', choices: [{ id: 'a', label: 'Dönem sonunda kalan muhasebe kârını', labelEn: 'Accounting profit remaining for the period' }, { id: 'b', label: 'Kasadaki kesin nakdi', labelEn: 'Exact cash in the bank' }, { id: 'c', label: 'Şirketin piyasa değerini', labelEn: 'The company market value' }], correctId: 'a', explanation: 'Net kâr muhasebe sonucudur; nakit veya piyasa değeriyle aynı değildir.', explanationEn: 'Net income is an accounting result, not the same as cash or market value.' },
  ],
  sources: [FUNDAMENTAL_ANALYSIS_SOURCES.statements, FUNDAMENTAL_ANALYSIS_SOURCES.accounting],
});

const balanceSheet = createFoundationLesson({
  id: 'lesson.fundamental.balance-sheet.001',
  slug: 'bilanco-ne-anlatir',
  conceptKey: 'fundamental.balance_sheet',
  skillId: 'skill.fundamental-analysis',
  competencyId: 'competency.read-balance-sheet.foundation',
  title: 'Bilanço ne anlatır?',
  titleEn: 'What does a balance sheet tell you?',
  objective: 'Bilançoda şirketin neye sahip olduğunu ve bunları nasıl finanse ettiğini öğren.',
  objectiveEn: 'Explain the assets = liabilities + equity relationship and the basics of short- and long-term financial position.',
  minutes: 5,
  hook: 'Çok varlığı olan şirket otomatik olarak finansal açıdan güçlü müdür?',
  hookEn: 'Is a company with many assets automatically financially strong?',
  explanation: 'Bilanço, şirketin belirli bir tarihte neye sahip olduğunu ve bunları nasıl finanse ettiğini gösterir. Varlıklar nakit, alacak, stok ve ekipman gibi kaynaklardır. Borçlar yükümlülükleri, özkaynak ise sahiplerin muhasebe payını gösterir. Büyük varlık tek başına güçlü bilanço demek değildir.',
  explanationEn: 'A balance sheet shows what a company owns at a point in time and how those resources are financed. Assets include cash, receivables, inventory, property, and other resources. Liabilities are obligations, while equity is the accounting residual after liabilities are deducted from assets. Asset size alone is not enough; asset quality, maturity structure, and debt load should be considered together.',
  proExplanation: 'Working capital, goodwill/intangibles, lease liabilities, off-balance-sheet commitments ve debt maturity schedule bilanço riskini anlamada önem kazanabilir.',
  proExplanationEn: 'Working capital, goodwill/intangibles, lease liabilities, off-balance-sheet commitments, and debt maturity schedules can matter for balance-sheet risk.',
  misconception: 'Büyük toplam varlığı otomatik olarak güçlü veya düşük riskli sayma.',
  misconceptionEn: 'Common mistake: interpreting large total assets directly as high quality or low risk.',
  takeaway: 'Bilançoda ne var, nasıl finanse edildi ve ne zaman ödenecek birlikte bak.',
  takeawayEn: 'A balance sheet answers not only “what is there?” but also “how was it financed and when are obligations due?”',
  prerequisiteConceptKeys: ['fundamental.financial_statements'],
  relatedConceptKeys: ['fundamental.debt_liquidity', 'fundamental.cash_flow'],
  visualAlt: 'Varlıkların bir tarafta, borç ve özkaynağın diğer tarafta dengelendiği sade bilanço terazisi',
  visualAltEn: 'Simple balance-sheet scale with assets on one side and liabilities plus equity on the other',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/fundamental/balance-sheet-001',
  taskPrompt: 'Şirketin nakdi 20, kısa vadeli borcu 80. Hangi soru daha önemlidir?',
  taskPromptEn: 'A company has 20 in cash and 80 in short-term debt. Which question matters more?',
  taskChoices: [
    { id: 'liquidity', label: 'Yakın vadeli yükümlülükleri karşılayacak diğer likit kaynak ve nakit üretimi var mı?', labelEn: 'Are there other liquid resources and cash generation to meet near-term obligations?' },
    { id: 'assets', label: 'Toplam varlık sayfası uzun mu?', labelEn: 'Is the asset page long?' },
    { id: 'price', label: 'Hisse dün yükseldi mi?', labelEn: 'Did the stock rise yesterday?' },
  ],
  taskCorrectIds: ['liquidity'],
  questions: [
    { prompt: 'Temel bilanço eşitliği hangisidir?', promptEn: 'What is the basic balance-sheet equation?', choices: [{ id: 'a', label: 'Varlıklar = Borçlar + Özkaynak', labelEn: 'Assets = Liabilities + Equity' }, { id: 'b', label: 'Gelir = Hisse fiyatı', labelEn: 'Revenue = Share price' }, { id: 'c', label: 'Nakit = Net kâr', labelEn: 'Cash = Net income' }], correctId: 'a', explanation: 'Varlıklar borç ve özkaynakla finanse edilir.', explanationEn: 'Assets are financed by liabilities and equity.' },
    { prompt: 'Büyük varlık toplamı tek başına düşük risk gösterir mi?', promptEn: 'Do large total assets alone indicate low risk?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Varlık kalitesi ve finansman yapısı ayrıca önemlidir.', explanationEn: 'Asset quality and financing structure also matter.' },
    { prompt: 'Özkaynak muhasebe açısından neyi gösterir?', promptEn: 'What does equity represent in accounting terms?', choices: [{ id: 'a', label: 'Varlıklardan borçlar çıktıktan sonraki kalan payı', labelEn: 'The residual after liabilities are deducted from assets' }, { id: 'b', label: 'Gelecek yılın satışını', labelEn: 'Next year’s sales' }, { id: 'c', label: 'Yalnız kasadaki nakdi', labelEn: 'Only cash in the bank' }], correctId: 'a', explanation: 'Özkaynak bilanço denkliğinin kalan finansman bölümüdür.', explanationEn: 'Equity is the residual financing component of the balance sheet.' },
  ],
  sources: [FUNDAMENTAL_ANALYSIS_SOURCES.statements, FUNDAMENTAL_ANALYSIS_SOURCES.methodology],
});

const cashFlow = createFoundationLesson({
  id: 'lesson.fundamental.cash-flow.001',
  slug: 'nakit-akisi-neden-farklidir',
  conceptKey: 'fundamental.cash_flow',
  skillId: 'skill.fundamental-analysis',
  competencyId: 'competency.read-cash-flow.foundation',
  title: 'Nakit akışı neden kârdan farklıdır?',
  titleEn: 'Why is cash flow different from profit?',
  objective: 'Kâr ile gerçek nakit hareketinin neden farklı olabildiğini öğren.',
  objectiveEn: 'Distinguish operating, investing, and financing cash flows and explain why accounting profit can differ from actual cash movement.',
  minutes: 5,
  hook: 'Şirket kârlı olduğu halde neden nakit sıkıntısı yaşayabilir?',
  hookEn: 'Why can a profitable company still run short of cash?',
  explanation: 'Nakit akış tablosu gerçek para hareketini üç bölümde gösterir: işletme, yatırım ve finansman. Kâr muhasebe kurallarıyla hesaplanırken nakit gerçekten girip çıkmış parayı izler. Müşteri henüz ödeme yapmadıysa, stok arttıysa veya yatırım yapıldıysa kâr ile nakit ayrışabilir.',
  explanationEn: 'The cash-flow statement shows how money moves through a company in three sections. Operating cash flow covers cash generated or used by core operations; investing cash flow covers purchases or sales of equipment, property, and investments; financing cash flow covers borrowing, debt repayment, equity transactions, and similar financing. Because profit is based on accrual accounting, receivables, inventory, and non-cash expenses can create differences between profit and cash.',
  proExplanation: 'Free cash flow tanımı analiste göre değişebilir; yaygın yaklaşım operating cash flow minus capital expenditures’tır. Working-capital swings ve stock-based compensation gibi kalemler kalite değerlendirmesinde ayrıca incelenebilir.',
  proExplanationEn: 'Free-cash-flow definitions can vary; a common form is operating cash flow minus capital expenditures. Working-capital swings and stock-based compensation may require separate quality assessment.',
  misconception: 'Pozitif net kârı otomatik olarak güçlü nakit üretimi sanma.',
  misconceptionEn: 'Common mistake: treating positive net income as automatic strong cash generation.',
  takeaway: 'Kâr ile kasaya giren para aynı şey değildir.',
  takeawayEn: 'Profit is an accounting result; cash flow shows actual money movement.',
  prerequisiteConceptKeys: ['fundamental.financial_statements', 'fundamental.income_statement'],
  relatedConceptKeys: ['fundamental.balance_sheet', 'fundamental.debt_liquidity'],
  visualAlt: 'İşletme, yatırım ve finansman olmak üzere üç kanaldan şirkete giren ve çıkan nakdi gösteren sade akış diyagramı',
  visualAltEn: 'Simple flow diagram showing cash entering and leaving a company through operating, investing, and financing channels',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/fundamental/cash-flow-001',
  taskPrompt: 'Net kâr pozitif ama işletme nakit akışı negatif. Hangi açıklama mümkün olabilir?',
  taskPromptEn: 'Net income is positive but operating cash flow is negative. Which explanation is possible?',
  taskChoices: [
    { id: 'working', label: 'Alacak veya stok gibi işletme sermayesi kalemleri nakit kullanmış olabilir', labelEn: 'Working-capital items such as receivables or inventory may have used cash' },
    { id: 'impossible', label: 'Bu muhasebe açısından imkânsızdır', labelEn: 'This is impossible in accounting' },
    { id: 'price', label: 'Hisse fiyatı mutlaka düşmüştür', labelEn: 'The share price must have fallen' },
  ],
  taskCorrectIds: ['working'],
  questions: [
    { prompt: 'İşletme nakit akışı neyle ilgilidir?', promptEn: 'What is operating cash flow about?', choices: [{ id: 'a', label: 'Ana faaliyetlerden gelen ve kullanılan nakitle', labelEn: 'Cash generated and used by core operations' }, { id: 'b', label: 'Yalnız hisse fiyatıyla', labelEn: 'Only share price' }, { id: 'c', label: 'Yalnız borçlanmayla', labelEn: 'Only borrowing' }], correctId: 'a', explanation: 'İşletme bölümü ana operasyonların nakit etkisini gösterir.', explanationEn: 'The operating section shows the cash impact of core operations.' },
    { prompt: 'Kâr ve nakit neden farklı olabilir?', promptEn: 'Why can profit and cash differ?', choices: [{ id: 'a', label: 'Tahakkuk muhasebesi ve işletme sermayesi nedeniyle', labelEn: 'Because of accrual accounting and working capital' }, { id: 'b', label: 'Farklı olamaz', labelEn: 'They cannot differ' }, { id: 'c', label: 'Yalnız grafik zaman dilimi nedeniyle', labelEn: 'Only because of chart timeframe' }], correctId: 'a', explanation: 'Gelir/gider tanıma zamanı nakit hareketiyle aynı olmayabilir.', explanationEn: 'Recognition timing for revenue and expenses may differ from cash movement.' },
    { prompt: 'Yatırım nakit akışında hangi kalem görülebilir?', promptEn: 'What can appear in investing cash flow?', choices: [{ id: 'a', label: 'Tesis veya ekipman yatırımı', labelEn: 'Property or equipment investment' }, { id: 'b', label: 'Günlük hisse hacmi', labelEn: 'Daily stock volume' }, { id: 'c', label: 'RSI değeri', labelEn: 'RSI value' }], correctId: 'a', explanation: 'Uzun vadeli varlık yatırımları yatırım nakit akışında yer alabilir.', explanationEn: 'Investment in long-lived assets can appear in investing cash flow.' },
  ],
  sources: [FUNDAMENTAL_ANALYSIS_SOURCES.statements, FUNDAMENTAL_ANALYSIS_SOURCES.accounting],
});

const profitability = createFoundationLesson({
  id: 'lesson.fundamental.profitability.001',
  slug: 'marjlar-ne-anlatir',
  conceptKey: 'fundamental.profitability',
  skillId: 'skill.fundamental-analysis',
  competencyId: 'competency.interpret-profitability.foundation',
  title: 'Kârlılık ve marjlar ne anlatır?',
  titleEn: 'What do profitability and margins tell you?',
  objective: 'Marjların satışın hangi aşamasında ne kadar kâr kaldığını nasıl gösterdiğini öğren.',
  objectiveEn: 'Explain how gross, operating, and net margins show how much profit remains at different stages of revenue.',
  minutes: 5,
  hook: 'İki şirket aynı net kârı açıklıyorsa kârlılık kaliteleri aynı mıdır?',
  hookEn: 'If two companies report the same net income, is their profitability quality the same?',
  explanation: 'Marj, satışın yüzde kaçının belirli bir kâr aşamasında kaldığını gösterir. Brüt marj ürün maliyeti sonrası, faaliyet marjı operasyon giderleri sonrası, net marj ise faiz ve vergi sonrası kalan paydır. Marjı tek başına değil, geçmiş trendi ve sektörle birlikte okumak gerekir.',
  explanationEn: 'A margin is a profit measure divided by revenue and shows how much value a company retains from sales. Gross margin is after direct product/service costs; operating margin after operating expenses; net margin after interest, taxes, and other items. Direction and industry context matter as much as the absolute level. A high margin alone does not guarantee high quality.',
  proExplanation: 'Operating leverage, product mix, pricing power, cyclicality ve accounting classification marj davranışını etkileyebilir. Sektörler arası ham marj karşılaştırması yanıltıcı olabilir.',
  proExplanationEn: 'Operating leverage, product mix, pricing power, cyclicality, and accounting classification can affect margin behavior. Raw cross-industry margin comparisons can mislead.',
  misconception: 'Farklı sektörlerdeki şirketlerin marjlarını bağlam olmadan kıyaslama.',
  misconceptionEn: 'Common mistake: directly comparing margins across different industries without context.',
  takeaway: 'Marjı trendi ve sektör bağlamıyla birlikte oku.',
  takeawayEn: 'Margins show how much profit remains at different stages of revenue; read them with trend and industry context.',
  prerequisiteConceptKeys: ['fundamental.income_statement'],
  relatedConceptKeys: ['fundamental.cash_flow', 'fundamental.debt_liquidity'],
  visualAlt: '100 birim gelirden brüt, faaliyet ve net kâr aşamalarında kalan payı gösteren sade marj hunisi',
  visualAltEn: 'Simple margin funnel showing what remains from 100 units of revenue at gross, operating, and net profit stages',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/fundamental/profitability-001',
  taskPrompt: 'Gelir artıyor ama faaliyet marjı üç yıldır düşüyor. Hangi yorum daha dengelidir?',
  taskPromptEn: 'Revenue is rising but operating margin has fallen for three years. Which interpretation is more balanced?',
  taskChoices: [
    { id: 'pressure', label: 'Büyüme var ama maliyet/gider baskısının nedenini incelemek gerekir', labelEn: 'There is growth, but the source of cost/expense pressure needs investigation' },
    { id: 'great', label: 'Gelir arttığı için kârlılık kesin güçlenmiştir', labelEn: 'Profitability definitely improved because revenue rose' },
    { id: 'sell', label: 'Bu tek başına kesin işlem talimatıdır', labelEn: 'This alone is a certain trade instruction' },
  ],
  taskCorrectIds: ['pressure'],
  questions: [
    { prompt: 'Brüt marj neyi ilişkilendirir?', promptEn: 'What does gross margin relate?', choices: [{ id: 'a', label: 'Brüt kârı gelire', labelEn: 'Gross profit to revenue' }, { id: 'b', label: 'Borcu hisse fiyatına', labelEn: 'Debt to share price' }, { id: 'c', label: 'Nakit akışını RSI’a', labelEn: 'Cash flow to RSI' }], correctId: 'a', explanation: 'Brüt marj doğrudan maliyetler sonrası kalan kârın gelire oranıdır.', explanationEn: 'Gross margin is gross profit after direct costs divided by revenue.' },
    { prompt: 'Marj karşılaştırmasında sektör önemli midir?', promptEn: 'Does industry matter when comparing margins?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız kriptoda', labelEn: 'Only in crypto' }], correctId: 'a', explanation: 'İş modelleri ve maliyet yapıları sektörlere göre değişir.', explanationEn: 'Business models and cost structures differ by industry.' },
    { prompt: 'Yüksek net marj tek başına şirket kalitesini garanti eder mi?', promptEn: 'Does a high net margin alone guarantee company quality?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Sürdürülebilirlik, nakit, bilanço ve sektör bağlamı ayrıca gerekir.', explanationEn: 'Sustainability, cash, balance sheet, and industry context still matter.' },
  ],
  sources: [FUNDAMENTAL_ANALYSIS_SOURCES.accounting, FUNDAMENTAL_ANALYSIS_SOURCES.methodology],
});

const debtLiquidity = createFoundationLesson({
  id: 'lesson.fundamental.debt-liquidity.001',
  slug: 'borc-ve-likidite-nasil-okunur',
  conceptKey: 'fundamental.debt_liquidity',
  skillId: 'skill.fundamental-analysis',
  competencyId: 'competency.assess-debt-liquidity.foundation',
  title: 'Borç ve likidite nasıl okunur?',
  titleEn: 'How do you read debt and liquidity?',
  objective: 'Borcu yalnız miktarla değil, ödeme kapasitesiyle birlikte değerlendirmeyi öğren.',
  objectiveEn: 'Explain that debt amount should be considered with maturity, interest burden, cash, near-term obligations, and cash generation.',
  minutes: 5,
  hook: 'Borcu yüksek olan her şirket otomatik olarak kötü durumda mıdır?',
  hookEn: 'Is every company with high debt automatically in poor condition?',
  explanation: 'Borç tek başına iyi veya kötü değildir. Önemli olan şirketin ne kadar nakdi olduğu, borcun ne zaman ödeneceği, faiz yükü ve işletmenin ne kadar nakit üretebildiğidir. Aynı borç, güçlü nakit üreten şirket için daha yönetilebilir olabilir.',
  explanationEn: 'Debt is a financing tool; risk depends not only on the amount but on the company’s ability to carry it. Cash and liquid assets, near-term obligations, interest expense, debt maturities, and operating cash generation should be considered together. The same debt amount can carry different risk for a stable cash generator versus a volatile weak cash generator.',
  proExplanation: 'Net debt, interest coverage, current ratio, quick ratio, covenant headroom ve refinancing risk farklı açılardan borç taşıma kapasitesini ölçebilir. Hiçbiri tek başına yeterli değildir.',
  proExplanationEn: 'Net debt, interest coverage, current ratio, quick ratio, covenant headroom, and refinancing risk can measure debt capacity from different angles. None is sufficient alone.',
  misconception: '“Borç var = kötü” veya “nakit var = güvenli” gibi tek kalemli sonuç çıkarma.',
  misconceptionEn: 'Common mistake: drawing single-line conclusions such as “debt = bad” or “cash = safe.”',
  takeaway: 'Borç riskini ödeme zamanı ve nakit gücüyle birlikte değerlendir.',
  takeawayEn: 'Assess debt together with amount, maturity, interest burden, and cash generation.',
  prerequisiteConceptKeys: ['fundamental.balance_sheet', 'fundamental.cash_flow'],
  relatedConceptKeys: ['risk.basics', 'fundamental.profitability'],
  visualAlt: 'Nakit, kısa vadeli borç, uzun vadeli borç, faiz yükü ve işletme nakit akışını birlikte gösteren sade borç kapasitesi paneli',
  visualAltEn: 'Simple debt-capacity panel combining cash, short-term debt, long-term debt, interest burden, and operating cash flow',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/fundamental/debt-liquidity-001',
  taskPrompt: 'İki şirketin borcu aynı. Hangisinin borç riski genellikle daha dikkatle incelenmelidir?',
  taskPromptEn: 'Two companies have the same debt. Which generally deserves closer debt-risk review?',
  taskChoices: [
    { id: 'weak', label: 'Nakit üretimi zayıf, borç vadeleri yakın ve faiz yükü yüksek olan', labelEn: 'The one with weak cash generation, near maturities, and high interest burden' },
    { id: 'stable', label: 'Düzenli nakit üreten ve vadeleri dağılmış olan', labelEn: 'The one with stable cash generation and staggered maturities' },
    { id: 'same', label: 'Borç tutarı aynı olduğu için risk kesin aynıdır', labelEn: 'Risk is certainly identical because debt amount is the same' },
  ],
  taskCorrectIds: ['weak'],
  questions: [
    { prompt: 'Borç riskini değerlendirirken hangisi önemlidir?', promptEn: 'What matters when assessing debt risk?', choices: [{ id: 'a', label: 'Vade, faiz yükü ve nakit üretimi', labelEn: 'Maturity, interest burden, and cash generation' }, { id: 'b', label: 'Yalnız borç sayısının büyüklüğü', labelEn: 'Only the debt number' }, { id: 'c', label: 'Yalnız şirket logosu', labelEn: 'Only the company logo' }], correctId: 'a', explanation: 'Borcu taşıma kapasitesi çok boyutludur.', explanationEn: 'Debt capacity is multidimensional.' },
    { prompt: 'Yüksek borç her zaman kötü müdür?', promptEn: 'Is high debt always bad?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız bankalarda', labelEn: 'Only for banks' }], correctId: 'a', explanation: 'İş modeli, nakit üretimi, maliyet ve vade yapısı önemlidir.', explanationEn: 'Business model, cash generation, cost, and maturity structure matter.' },
    { prompt: 'Likidite en çok hangi soruyla ilgilidir?', promptEn: 'Liquidity most directly relates to which question?', choices: [{ id: 'a', label: 'Yakın vadeli yükümlülükler karşılanabilir mi?', labelEn: 'Can near-term obligations be met?' }, { id: 'b', label: 'RSI kaç?', labelEn: 'What is RSI?' }, { id: 'c', label: 'Hisse yarın yükselir mi?', labelEn: 'Will the stock rise tomorrow?' }], correctId: 'a', explanation: 'Likidite yakın vadeli ödeme kapasitesine odaklanır.', explanationEn: 'Liquidity focuses on near-term payment capacity.' },
  ],
  sources: [FUNDAMENTAL_ANALYSIS_SOURCES.statements, FUNDAMENTAL_ANALYSIS_SOURCES.methodology],
});

export const FUNDAMENTAL_ANALYSIS_FOUNDATION_LESSONS = [
  statements,
  incomeStatement,
  balanceSheet,
  cashFlow,
  profitability,
  debtLiquidity,
] as const;
