import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { BEHAVIOR_EVIDENCE_SOURCES } from '../wave1/behaviorEvidenceSources';

const dispositionEffect = createFoundationLesson({
  id: 'lesson.behavior.disposition-effect.001', slug: 'kazanan-erken-kaybeden-gec', conceptKey: 'behavior.disposition_effect', skillId: 'skill.market-psychology', competencyId: 'competency.recognize-disposition-effect.foundation',
  title: 'Kazananı erken, kaybedeni geç bırakmak neden olur?', titleEn: 'Why do people sell winners early and hold losers too long?',
  objective: 'Kazananı erken, kaybedeni geç kapatma eğiliminin neden oluştuğunu öğren.', objectiveEn: 'Identify the tendency to realize gains too early while holding losing positions too long.', minutes: 5,
  hook: 'Kârı hemen güvenceye almak isterken zarardaki pozisyona neden daha fazla zaman tanıyabilirsin?', hookEn: 'Why might you rush to lock in a gain while giving a losing position much more time?',
  explanation: 'Disposition effect, kazanan pozisyonları erken kapatıp kaybedenleri zararı kabul etmemek için uzun tutma eğilimidir. Karar güncel tez yerine pozisyonun yeşil veya kırmızı olmasına bağlanır.', explanationEn: 'The disposition effect is the tendency to realize gains too early while holding losers longer to avoid accepting a loss. It shifts attention from the current validity of the thesis to the sign of P&L.',
  proExplanation: 'Disposition effect, loss aversion ve reference dependence ile ilişkilidir. Çıkış kararı giriş fiyatından bağımsız, güncel beklenen değer ve geçersizlik koşullarıyla değerlendirilmelidir.', proExplanationEn: 'The disposition effect is related to loss aversion and reference dependence. Exit decisions should be based on current expected value and invalidation conditions, not the entry price.',
  misconception: 'Kârı hızlı almayı her zaman disiplin, zararı bekletmeyi her zaman sabır sanma.', misconceptionEn: 'Common mistake: assuming taking profits quickly is always discipline and holding losses is always patience.',
  takeaway: 'Çıkışı P&L rengi değil, güncel tez ve risk belirlemeli.', takeawayEn: 'The current thesis and risk conditions—not whether P&L is green or red—should drive exit decisions.',
  prerequisiteConceptKeys: ['behavior.loss_aversion'], relatedConceptKeys: ['behavior.anchoring', 'risk.stop_orders', 'behavior.precommitment'],
  visualAlt: 'Kazanan pozisyonun erken kesildiği ve kaybedenin uzatıldığı iki karşıt yolun yanında tez-temelli çıkış yolunu gösteren görsel', visualAltEn: 'Visual contrasting early winner exits and prolonged losers with a thesis-based exit path',
  taskPrompt: 'Hangisi disposition effect örneğidir?', taskPromptEn: 'Which is an example of the disposition effect?',
  taskChoices: [{ id: 'bias', label: 'Sırf kârda olduğu için güçlü tezi erken kapatıp, sırf zararda olduğu için geçersizleşmiş tezi tutmak', labelEn: 'Closing a valid winner just because it is profitable while holding an invalid loser just because it is down' }, { id: 'rule', label: 'Her iki pozisyonu da aynı önceden tanımlı kurallarla değerlendirmek', labelEn: 'Evaluate both positions using the same predefined rules' }, { id: 'evidence', label: 'Yeni kanıt geldiğinde tezi güncellemek', labelEn: 'Update the thesis when new evidence arrives' }], taskCorrectIds: ['bias'],
  questions: [
    { prompt: 'Disposition effect neyi anlatır?', promptEn: 'What does the disposition effect describe?', choices: [{ id: 'a', label: 'Kazananları erken satıp kaybedenleri uzun tutma eğilimini', labelEn: 'Selling winners early and holding losers too long' }, { id: 'b', label: 'Tüm pozisyonları aynı anda kapatmayı', labelEn: 'Closing all positions at once' }, { id: 'c', label: 'Sadece volatiliteyi', labelEn: 'Only volatility' }], correctId: 'a', explanation: 'Davranış P&L işaretine göre asimetrik çıkış yaratır.', explanationEn: 'The bias creates asymmetric exits based on the sign of P&L.' },
    { prompt: 'Çıkış kararı neye dayanmalı?', promptEn: 'What should an exit decision be based on?', choices: [{ id: 'a', label: 'Güncel tez, risk ve geçersizlik koşullarına', labelEn: 'Current thesis, risk, and invalidation conditions' }, { id: 'b', label: 'Yalnız giriş fiyatına', labelEn: 'Only the entry price' }, { id: 'c', label: 'Yalnız kârda olup olmamaya', labelEn: 'Only whether P&L is positive' }], correctId: 'a', explanation: 'Giriş fiyatı psikolojik referans olabilir; güncel kanıt daha önemlidir.', explanationEn: 'Entry price can become a psychological reference; current evidence matters more.' },
    { prompt: 'Disposition effect hangi başka eğilimle bağlantılıdır?', promptEn: 'Which other bias is closely related?', choices: [{ id: 'a', label: 'Kayıptan kaçınma', labelEn: 'Loss aversion' }, { id: 'b', label: 'Veri güncelliği', labelEn: 'Data freshness' }, { id: 'c', label: 'Likidite sağlayıcılığı', labelEn: 'Liquidity provision' }], correctId: 'a', explanation: 'Kaybı realize etmeme isteği kaybedeni gereğinden uzun tutmaya katkı sağlayabilir.', explanationEn: 'Avoiding realized losses can contribute to holding losers too long.' },
  ], sources: [BEHAVIOR_EVIDENCE_SOURCES.behavior],
});

const herdBehavior = createFoundationLesson({
  id: 'lesson.behavior.herd-behavior.001', slug: 'kalabalik-hakli-midir', conceptKey: 'behavior.herd_behavior', skillId: 'skill.market-psychology', competencyId: 'competency.recognize-herd-behavior.foundation',
  title: 'Kalabalık haklıysa sen de haklı mısın?', titleEn: 'If the crowd agrees, does that make you right?',
  objective: 'Kalabalığın davranışını bağımsız kanıt yerine kullanma eğilimini öğren.', objectiveEn: 'Distinguish using other people’s behavior as a substitute for independent evidence.', minutes: 5,
  hook: 'Herkes aynı varlığı konuşuyorsa, bu tek başına güçlü analiz midir?', hookEn: 'If everyone is talking about the same asset, is that strong analysis by itself?',
  explanation: 'Sürü davranışı, kendi kanıtını değerlendirmek yerine kalabalığı takip etmektir. Kalabalık bazen doğru olabilir; sorun “çoğu kişi böyle yapıyor” düşüncesinin bağımsız gerekçenin yerine geçmesidir.', explanationEn: 'Herd behavior occurs when someone follows the crowd instead of evaluating evidence independently. The crowd can sometimes be right; the problem is when “everyone is doing it” replaces an independent rationale.',
  proExplanation: 'Information cascades ve social proof, belirsizlikte bireysel değerlendirmeyi bastırabilir. Kalabalığın kendisi bir veri noktası olabilir ancak tez, risk ve invalidation ayrıca kurulmalıdır.', proExplanationEn: 'Information cascades and social proof can suppress independent judgment under uncertainty. Crowd behavior can be one data point, but thesis, risk, and invalidation still need separate justification.',
  misconception: 'Çok kişinin aynı yönde olmasıyla kararı otomatik doğru sayma.', misconceptionEn: 'Common mistake: treating widespread positioning as direct proof that a decision is correct.',
  takeaway: 'Kalabalık bilgi olabilir; tek başına gerekçe değildir.', takeawayEn: 'The crowd can be information, but it is not the whole rationale.',
  prerequisiteConceptKeys: ['behavior.fomo'], relatedConceptKeys: ['behavior.confirmation_bias', 'behavior.availability_bias', 'evidence.data_quality'],
  visualAlt: 'Aynı yöne giden kalabalık oklarının yanında bağımsız kanıt kontrolünden geçen tek karar yolunu gösteren sade görsel', visualAltEn: 'Visual showing a crowd moving one way beside an independent evidence-check path',
  taskPrompt: 'Hangi gerekçe sürü davranışına daha yakındır?', taskPromptEn: 'Which rationale is closer to herd behavior?',
  taskChoices: [{ id: 'crowd', label: '“Herkes alıyor; demek ki doğru.”', labelEn: '“Everyone is buying, so it must be right.”' }, { id: 'verify', label: '“Kalabalığın davranışını ayrı, kendi kanıtımı ayrı değerlendireceğim.”', labelEn: '“I will evaluate crowd behavior separately from my own evidence.”' }, { id: 'risk', label: '“Risk limitimi değiştirmeyeceğim.”', labelEn: '“I will not change my risk limit.”' }], taskCorrectIds: ['crowd'],
  questions: [
    { prompt: 'Sürü davranışının temel sorunu nedir?', promptEn: 'What is the core problem with herd behavior?', choices: [{ id: 'a', label: 'Kalabalığın bağımsız kanıtın yerini alması', labelEn: 'The crowd replacing independent evidence' }, { id: 'b', label: 'Her kalabalığın yanlış olması', labelEn: 'Every crowd being wrong' }, { id: 'c', label: 'Fiyatların hareket etmesi', labelEn: 'Prices moving' }], correctId: 'a', explanation: 'Sorun kalabalığın varlığı değil, gerekçenin yerine geçmesidir.', explanationEn: 'The issue is not the crowd itself, but using it as a substitute for rationale.' },
    { prompt: 'Kalabalık davranışı hiç bilgi taşımaz mı?', promptEn: 'Does crowd behavior carry no information at all?', choices: [{ id: 'a', label: 'Taşıyabilir ama tek başına yeterli değildir', labelEn: 'It can, but it is not sufficient by itself' }, { id: 'b', label: 'Asla taşımaz', labelEn: 'Never' }, { id: 'c', label: 'Her zaman kesin sinyaldir', labelEn: 'It is always a certain signal' }], correctId: 'a', explanation: 'Kalabalık bir veri noktası olabilir; bağımsız kanıt gerekir.', explanationEn: 'Crowd behavior can be a data point; independent evidence is still needed.' },
    { prompt: 'Sürü davranışını azaltmak için ne yararlıdır?', promptEn: 'What helps reduce herd behavior?', choices: [{ id: 'a', label: 'Kendi tezini ve karşı kanıtını yazmak', labelEn: 'Write your own thesis and disconfirming evidence' }, { id: 'b', label: 'Yalnız popüler hesapları takip etmek', labelEn: 'Follow only popular accounts' }, { id: 'c', label: 'Kalabalığa göre pozisyon büyütmek', labelEn: 'Increase size based on the crowd' }], correctId: 'a', explanation: 'Bağımsız gerekçe kalabalığın otomatik etkisini azaltır.', explanationEn: 'An independent rationale reduces automatic crowd influence.' },
  ], sources: [BEHAVIOR_EVIDENCE_SOURCES.behavior],
});

const sunkCost = createFoundationLesson({
  id: 'lesson.behavior.sunk-cost.001', slug: 'batik-maliyet-karari', conceptKey: 'behavior.sunk_cost', skillId: 'skill.market-psychology', competencyId: 'competency.recognize-sunk-cost.foundation',
  title: 'Geçmişte harcadığın şey bugünkü kararı belirlemeli mi?', titleEn: 'Should past costs determine today’s decision?',
  objective: 'Geçmişte harcadığın para veya zamanın bugünkü kararı neden yönetmemesi gerektiğini öğren.', objectiveEn: 'Identify when unrecoverable past costs exert too much influence on a new decision.', minutes: 5,
  hook: 'Bir pozisyona çok zaman ve para ayırdıysan, sırf bu yüzden devam etmek zorunda mısın?', hookEn: 'If you have spent a lot of time and money on a position, must you continue just because of that?',
  explanation: 'Batık maliyet yanılgısı, geri alınamayacak geçmiş maliyeti bugünkü kararın gerekçesi yapmaktır. “Bu kadar bekledim” veya “bu kadar zarar ettim” düşüncesi, bugünkü seçeneklerin değerini değiştirmez.', explanationEn: 'The sunk-cost fallacy is using unrecoverable past costs to justify a future decision. “I have waited this long” or “I have already lost this much” should not replace today’s expected-value assessment.',
  proExplanation: 'Rasyonel karar ileriye dönük marjinal fayda, risk ve alternatif maliyet üzerinden kurulmalıdır. Geçmiş yatırım yalnız öğrenme/veri olarak kullanılabilir; geleceği zorunlu kılmaz.', proExplanationEn: 'A rational decision should be based on forward-looking marginal benefit, risk, and opportunity cost. Past investment can inform learning, but it does not obligate continuation.',
  misconception: '“Bu kadar zarar ettim, artık çıkamam” düşüncesini ekonomik gerekçe sanma.', misconceptionEn: 'Common mistake: treating “I have lost too much to exit now” as an economic rationale.',
  takeaway: 'Geçmiş maliyet, bugünkü en iyi seçeneği belirlememeli.', takeawayEn: 'An unrecoverable past cost should not determine the best choice today.',
  prerequisiteConceptKeys: ['behavior.anchoring'], relatedConceptKeys: ['behavior.loss_aversion', 'behavior.disposition_effect', 'fundamental.analysis_limits'],
  visualAlt: 'Geçmiş maliyet kutusunun bugünkü karar yolundan ayrıldığı ve yalnız ileriye dönük risk-fayda akışının devam ettiği görsel', visualAltEn: 'Visual separating sunk past costs from a forward-looking risk-benefit decision path',
  taskPrompt: 'Hangi ifade sunk cost yanılgısıdır?', taskPromptEn: 'Which statement shows the sunk-cost fallacy?',
  taskChoices: [{ id: 'past', label: '“Bu kadar bekledim; artık ne olursa olsun devam etmeliyim.”', labelEn: '“I have waited this long, so I must continue no matter what.”' }, { id: 'forward', label: '“Bugünkü kararı mevcut risk ve beklenen değere göre vereceğim.”', labelEn: '“I will decide based on current risk and expected value.”' }, { id: 'review', label: '“Geçmişten ders çıkaracağım ama onu zorunluluk saymayacağım.”', labelEn: '“I will learn from the past without treating it as an obligation.”' }], taskCorrectIds: ['past'],
  questions: [
    { prompt: 'Batık maliyet nedir?', promptEn: 'What is a sunk cost?', choices: [{ id: 'a', label: 'Geri alınamayacak geçmiş maliyet', labelEn: 'An unrecoverable past cost' }, { id: 'b', label: 'Gelecekteki kesin getiri', labelEn: 'A certain future return' }, { id: 'c', label: 'Likidite primi', labelEn: 'A liquidity premium' }], correctId: 'a', explanation: 'Batık maliyet geçmişte kalmıştır ve geri alınamaz.', explanationEn: 'A sunk cost is already incurred and cannot be recovered.' },
    { prompt: 'Bugünkü karar neye dayanmalı?', promptEn: 'What should today’s decision be based on?', choices: [{ id: 'a', label: 'İleriye dönük risk, fayda ve alternatiflere', labelEn: 'Forward-looking risk, benefit, and alternatives' }, { id: 'b', label: 'Sadece geçmiş zarara', labelEn: 'Only the past loss' }, { id: 'c', label: 'Ne kadar zaman harcandığına', labelEn: 'How much time was already spent' }], correctId: 'a', explanation: 'Geleceğe dönük değerlendirme geçmiş maliyet zorunluluğunu ayırır.', explanationEn: 'Forward-looking evaluation separates the decision from sunk-cost pressure.' },
    { prompt: 'Geçmiş maliyet tamamen önemsiz midir?', promptEn: 'Is past cost completely irrelevant?', choices: [{ id: 'a', label: 'Öğrenme için veri olabilir ama devam zorunluluğu yaratmaz', labelEn: 'It can inform learning but does not create an obligation to continue' }, { id: 'b', label: 'Her zaman devam etmeyi zorunlu kılar', labelEn: 'It always requires continuing' }, { id: 'c', label: 'Kesin kâr üretir', labelEn: 'It creates certain profit' }], correctId: 'a', explanation: 'Geçmiş deneyim öğrenme sağlar; gelecekteki seçimi zorunlu kılmaz.', explanationEn: 'Past experience can teach, but it does not dictate the future choice.' },
  ], sources: [BEHAVIOR_EVIDENCE_SOURCES.behavior],
});

const availabilityBias = createFoundationLesson({
  id: 'lesson.behavior.availability-bias.001', slug: 'akla-gelen-en-onemli-mi', conceptKey: 'behavior.availability_bias', skillId: 'skill.market-psychology', competencyId: 'competency.recognize-availability.foundation',
  title: 'Aklına en kolay gelen bilgi en önemli bilgi midir?', titleEn: 'Is the easiest information to recall the most important?',
  objective: 'Aklına kolay gelen bilginin neden gereğinden önemli görünebildiğini öğren.', objectiveEn: 'Explain how vivid, memorable, or easily recalled information can receive too much weight.', minutes: 5,
  hook: 'Dün gördüğün sert çöküş videosu, benzer olayların gerçekte ne kadar sık olduğunu doğru gösterir mi?', hookEn: 'Does yesterday’s dramatic crash video tell you how often similar events really occur?',
  explanation: 'Availability bias, akla kolay gelen bilgi veya örneği gerçekte olduğundan daha sık veya önemli sanmaktır. Çarpıcı haber, viral içerik veya kişisel deneyim gerçek baz oranın önüne geçebilir.', explanationEn: 'Availability bias makes easily recalled examples feel more frequent or important than they really are. Dramatic headlines, viral content, or personal experiences can overshadow base rates.',
  proExplanation: 'Salience ile probability birbirinden ayrılmalıdır. Base-rate data, geniş örneklem ve kaynak çeşitliliği erişilebilirlik yanlılığını azaltır.', proExplanationEn: 'Salience should be separated from probability. Base-rate data, broader samples, and diverse sources help reduce availability bias.',
  misconception: 'Çarpıcı tek örneği normal sıklığın temsilcisi sanma.', misconceptionEn: 'Common mistake: treating one vivid example as representative of normal frequency.',
  takeaway: 'Kolay hatırlanması, daha olası olduğu anlamına gelmez.', takeawayEn: 'Memorability is not probability.',
  prerequisiteConceptKeys: ['evidence.data_quality'], relatedConceptKeys: ['behavior.recency_bias', 'behavior.herd_behavior', 'risk.tail_risk'],
  visualAlt: 'Büyük ve parlak tek manşetin yanında daha küçük ama çok sayıda baz-oran veri noktasını gösteren görsel', visualAltEn: 'Visual contrasting one vivid headline with many smaller base-rate observations',
  taskPrompt: 'Hangi düşünce availability bias örneğidir?', taskPromptEn: 'Which thought shows availability bias?',
  taskChoices: [{ id: 'vivid', label: '“Bu çöküş videosunu çok net hatırlıyorum; demek ki sürekli olur.”', labelEn: '“I vividly remember that crash video, so it must happen all the time.”' }, { id: 'base', label: '“Önce olayın baz oranına bakacağım.”', labelEn: '“I will check the base rate first.”' }, { id: 'sources', label: '“Birden fazla kaynakla sıklığı kontrol edeceğim.”', labelEn: '“I will check frequency using multiple sources.”' }], taskCorrectIds: ['vivid'],
  questions: [
    { prompt: 'Availability bias ne yapar?', promptEn: 'What does availability bias do?', choices: [{ id: 'a', label: 'Kolay hatırlanan örneklere fazla ağırlık verir', labelEn: 'Overweights easily recalled examples' }, { id: 'b', label: 'Tüm olasılıkları tam hesaplar', labelEn: 'Perfectly calculates all probabilities' }, { id: 'c', label: 'Likiditeyi artırır', labelEn: 'Increases liquidity' }], correctId: 'a', explanation: 'Zihinsel erişilebilirlik gerçek sıklıkla karışabilir.', explanationEn: 'Mental availability can be confused with actual frequency.' },
    { prompt: 'Çarpıcı bir haber olayın baz oranını gösterir mi?', promptEn: 'Does one dramatic headline show the base rate?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Baz oranı daha geniş veri gerektirir.', explanationEn: 'Base rates require broader data.' },
    { prompt: 'Yanlılığı azaltmak için ne yapılabilir?', promptEn: 'What can reduce the bias?', choices: [{ id: 'a', label: 'Baz oranlarını ve daha geniş örneklemi kontrol etmek', labelEn: 'Check base rates and a broader sample' }, { id: 'b', label: 'Yalnız en viral içeriği izlemek', labelEn: 'Watch only the most viral content' }, { id: 'c', label: 'İlk örneğe göre karar vermek', labelEn: 'Decide from the first example' }], correctId: 'a', explanation: 'Geniş örneklem çarpıcı tek örneğin etkisini dengeler.', explanationEn: 'A broader sample balances the impact of one vivid example.' },
  ], sources: [BEHAVIOR_EVIDENCE_SOURCES.behavior],
});

const actionBias = createFoundationLesson({
  id: 'lesson.behavior.action-bias.001', slug: 'bir-sey-yapmak-zorunda-misin', conceptKey: 'behavior.action_bias', skillId: 'skill.market-psychology', competencyId: 'competency.recognize-action-bias.foundation',
  title: 'Piyasada her zaman bir şey yapmak zorunda mısın?', titleEn: 'Do you always need to do something in the market?',
  objective: 'Piyasada bir şey yapma ihtiyacının neden gereksiz işleme dönüşebildiğini öğren.', objectiveEn: 'Identify the tendency to act unnecessarily because doing nothing feels wrong under uncertainty or pressure.', minutes: 5,
  hook: 'Ekranı açtığında işlem yapmadan kapatmak başarısızlık mıdır?', hookEn: 'Is closing the screen without trading a failure?',
  explanation: 'Action bias, bir şey yapmak hiçbir şey yapmamaktan daha iyiymiş gibi hissettirdiğinde ortaya çıkar. Uygun koşul yokken işlem açmak, sürekli ayar değiştirmek veya habere hemen tepki vermek şeklinde görülebilir.', explanationEn: 'Action bias appears when doing something feels inherently better than doing nothing. In markets it can show up as trading without a valid setup, constantly changing settings, or reacting immediately to news.',
  proExplanation: 'No-trade decision da aktif bir risk kararıdır. Opportunity set zayıfsa beklemek, işlem maliyetini ve davranışsal hata riskini azaltabilir.', proExplanationEn: 'A no-trade decision is still an active risk decision. When the opportunity set is weak, waiting can reduce trading costs and behavioral error risk.',
  misconception: '“Bugün mutlaka işlem yapmalıyım” düşüncesini disiplin sanma.', misconceptionEn: 'Common mistake: treating “I must trade today” as productivity or discipline.',
  takeaway: 'İşlem yapmamak da geçerli bir karar olabilir.', takeawayEn: 'Not trading can be a deliberate decision.',
  prerequisiteConceptKeys: ['behavior.overtrading'], relatedConceptKeys: ['behavior.revenge_trading', 'behavior.precommitment', 'risk.position_sizing'],
  visualAlt: 'İşlem yap, bekle ve veri topla seçeneklerinin eşit karar dalları olarak gösterildiği sade karar ağacı', visualAltEn: 'Decision tree showing trade, wait, and gather-data as equally valid branches',
  taskPrompt: 'Hangi davranış action bias’e daha yakındır?', taskPromptEn: 'Which behavior is closer to action bias?',
  taskChoices: [{ id: 'must', label: 'Geçerli setup yokken sırf gün boş geçmesin diye işlem açmak', labelEn: 'Taking a trade without a valid setup just so the day is not empty' }, { id: 'wait', label: 'Koşullar oluşmadığında beklemek', labelEn: 'Wait when conditions are absent' }, { id: 'review', label: 'İşlem yapmadan veriyi gözden geçirmek', labelEn: 'Review data without trading' }], taskCorrectIds: ['must'],
  questions: [
    { prompt: 'Action bias nedir?', promptEn: 'What is action bias?', choices: [{ id: 'a', label: 'Eylemde bulunmayı gereksiz yere pasif kalmaktan üstün görmek', labelEn: 'Unnecessarily preferring action over inaction' }, { id: 'b', label: 'Her fırsatı reddetmek', labelEn: 'Rejecting every opportunity' }, { id: 'c', label: 'Sadece uzun vadeli yatırım', labelEn: 'Only long-term investing' }], correctId: 'a', explanation: 'Eylem hissi, karar kalitesinin önüne geçebilir.', explanationEn: 'The feeling of doing something can override decision quality.' },
    { prompt: 'No-trade kararı gerçek bir karar mıdır?', promptEn: 'Is a no-trade decision a real decision?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız tatilde', labelEn: 'Only on holidays' }], correctId: 'a', explanation: 'Beklemek sermaye ve davranış riskini koruyan aktif bir seçim olabilir.', explanationEn: 'Waiting can be an active choice that protects capital and reduces behavioral risk.' },
    { prompt: 'Action bias hangi davranışla birleşebilir?', promptEn: 'Which behavior can combine with action bias?', choices: [{ id: 'a', label: 'Aşırı işlem', labelEn: 'Overtrading' }, { id: 'b', label: 'Portföy muhasebesi', labelEn: 'Portfolio accounting' }, { id: 'c', label: 'Enflasyon ölçümü', labelEn: 'Inflation measurement' }], correctId: 'a', explanation: 'Sürekli bir şey yapma ihtiyacı işlem sıklığını artırabilir.', explanationEn: 'The need to act can increase trading frequency.' },
  ], sources: [BEHAVIOR_EVIDENCE_SOURCES.behavior],
});

const precommitment = createFoundationLesson({
  id: 'lesson.behavior.precommitment.001', slug: 'karari-onceden-kurmak', conceptKey: 'behavior.precommitment', skillId: 'skill.market-psychology', competencyId: 'competency.apply-precommitment.foundation',
  title: 'Zor anda karar vermemek için neyi önceden belirleyebilirsin?', titleEn: 'What can you decide in advance so you do not improvise under pressure?',
  objective: 'Zor an gelmeden önce hangi kuralları belirlemenin karar kalitesini koruyabildiğini öğren.', objectiveEn: 'Explain how defining risk, pause rules, invalidation, and decision criteria before emotional pressure can reduce behavioral errors.', minutes: 5,
  hook: 'Kayıp yaşadıktan sonra mı risk limiti koymak kolaydır, yoksa sakin zamanda mı?', hookEn: 'Is it easier to set a risk limit after a loss or while calm?',
  explanation: 'Pre-commitment, baskı altında verilecek kararların sınırlarını önceden belirlemektir. Günlük risk limiti, ara verme süresi, giriş kriteri ve invalidation kuralı sakin zamanda yazılırsa duygusal anda doğaçlama azalır.', explanationEn: 'Pre-commitment means setting boundaries for future decisions before pressure arrives. Daily risk limits, cooling-off periods, entry criteria, and invalidation rules reduce improvisation when written in a calm state.',
  proExplanation: 'Implementation intentions (“Eğer X olursa Y yapacağım”) ve checklist kullanımı state-dependent decision drift’i azaltabilir. Kurallar değişmez değildir; fakat değişiklik sakin ve belgeli bir review sürecinde yapılmalıdır.', proExplanationEn: 'Implementation intentions (“If X happens, I will do Y”) and checklists can reduce state-dependent decision drift. Rules are not immutable, but changes should occur through a calm, documented review process.',
  misconception: 'Önceden kural koymayı esneksizlik, duygusal doğaçlamayı adaptasyon sanma.', misconceptionEn: 'Common mistake: treating predefined rules as rigidity and emotional improvisation as “adaptation.”',
  takeaway: 'Sakin zamanda yazılan kurallar, zor anda karar yükünü azaltır.', takeawayEn: 'Good rules written while calm reduce decision load under pressure.',
  prerequisiteConceptKeys: ['behavior.decision_journal'], relatedConceptKeys: ['behavior.revenge_trading', 'behavior.action_bias', 'risk.position_sizing'],
  visualAlt: 'Sakin zamanda yazılan risk, ara verme ve geçersizlik kurallarının stres anındaki karar kapısına bağlandığını gösteren görsel', visualAltEn: 'Visual connecting calm-state risk, pause, and invalidation rules to a later high-pressure decision gate',
  taskPrompt: 'Hangisi pre-commitment örneğidir?', taskPromptEn: 'Which is an example of pre-commitment?',
  taskChoices: [{ id: 'rule', label: '“İki ardışık kayıptan sonra 30 dakika ara vereceğim” kuralını önceden yazmak', labelEn: 'Writing in advance: “After two consecutive losses I will pause for 30 minutes”' }, { id: 'emotion', label: 'Kayıptan sonra o an nasıl hissediyorsam öyle karar vermek', labelEn: 'Deciding based on how I feel immediately after a loss' }, { id: 'remove', label: 'Risk limitlerini baskı anında kaldırmak', labelEn: 'Removing risk limits under pressure' }], taskCorrectIds: ['rule'],
  questions: [
    { prompt: 'Pre-commitment ne sağlar?', promptEn: 'What does pre-commitment provide?', choices: [{ id: 'a', label: 'Baskı anındaki karar sınırlarını önceden belirler', labelEn: 'Sets decision boundaries before pressure arrives' }, { id: 'b', label: 'Geleceği garanti eder', labelEn: 'Guarantees the future' }, { id: 'c', label: 'Zararı imkânsız kılar', labelEn: 'Makes losses impossible' }], correctId: 'a', explanation: 'Amaç geleceği bilmek değil, davranışsal doğaçlamayı azaltmaktır.', explanationEn: 'The goal is not predicting the future but reducing behavioral improvisation.' },
    { prompt: 'Kurallar hiç değiştirilemez mi?', promptEn: 'Can rules never be changed?', choices: [{ id: 'a', label: 'Değişebilir ama sakin ve belgeli review ile', labelEn: 'They can change, but through a calm, documented review' }, { id: 'b', label: 'Asla', labelEn: 'Never' }, { id: 'c', label: 'Her kayıptan hemen sonra', labelEn: 'Immediately after every loss' }], correctId: 'a', explanation: 'Adaptasyon ile duygusal kural bozmayı ayırmak gerekir.', explanationEn: 'Adaptation should be separated from emotional rule-breaking.' },
    { prompt: 'Hangi araç pre-commitment’i destekler?', promptEn: 'What supports pre-commitment?', choices: [{ id: 'a', label: 'Checklist ve if-then kuralları', labelEn: 'Checklists and if-then rules' }, { id: 'b', label: 'Anlık dürtü', labelEn: 'Impulse' }, { id: 'c', label: 'Sadece sosyal medya', labelEn: 'Only social media' }], correctId: 'a', explanation: 'Önceden yazılan koşul-eylem eşleşmesi uygulamayı kolaylaştırır.', explanationEn: 'Prewritten condition-action mappings make execution easier.' },
  ], sources: [BEHAVIOR_EVIDENCE_SOURCES.behavior],
});

export const MARKET_PSYCHOLOGY_EXPANSION_LESSONS = [dispositionEffect, herdBehavior, sunkCost, availabilityBias, actionBias, precommitment] as const;
