import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { RISK_PORTFOLIO_SOURCES } from './riskPortfolioSources';

const riskFactors = createFoundationLesson({
  id: 'lesson.portfolio.risk-factors.001',
  slug: 'portfoy-risk-faktorleri',
  conceptKey: 'portfolio.risk_factors',
  skillId: 'skill.risk-portfolio',
  competencyId: 'competency.identify-risk-factors.intermediate',
  title: 'Farklı varlıklar aynı risk faktörünü taşıyabilir mi?',
  titleEn: 'Can different assets carry the same risk factor?',
  objective: 'Portföy riskini ürün isimlerinden çok ortak risk faktörleriyle okumayı öğren.',
  objectiveEn: 'Teach portfolio risk through common drivers such as rates, growth, FX, and volatility rather than product labels alone.',
  minutes: 5,
  learningStage: 'intermediate',
  hook: 'Hisse, ETF ve tahvil farklı ürünler olsa da aynı faiz şokundan etkilenebilir mi?',
  hookEn: 'Can stocks, ETFs, and bonds all react to the same rate shock even though they are different products?',
  explanation: 'Risk faktörü, birden fazla pozisyonu aynı anda etkileyebilen ortak sürücüdür. Faiz, büyüme, enflasyon, kur veya volatilite buna örnek olabilir. Farklı ürün isimleri taşımak, farklı risk kaynaklarına sahip olduğun anlamına gelmez.',
  explanationEn: 'A risk factor is a common economic or market driver that can affect several positions at once. Rates, growth, inflation, FX, credit conditions, and volatility are examples. Different product labels do not automatically mean different underlying risks.',
  proExplanation: 'Factor exposure doğrudan veya dolaylı olabilir ve zamanla değişebilir. Basit korelasyonun yanında duration, beta, currency exposure ve stress sensitivity gibi ölçüler ortak risk kaynağını anlamaya yardım edebilir.',
  proExplanationEn: 'Factor exposure can be direct or indirect and may change over time. Alongside correlation, measures such as duration, beta, currency exposure, and stress sensitivity can help reveal common risk drivers.',
  misconception: 'Ürünler farklı diye risk kaynaklarının da farklı olduğunu varsayma.',
  misconceptionEn: 'Common mistake: assuming different product types automatically mean different risk sources.',
  takeaway: 'Portföyde isimlerden çok ortak risk faktörlerine bak.',
  takeawayEn: 'Look beyond labels and ask which common factors can affect positions at the same time.',
  prerequisiteConceptKeys: ['portfolio.correlation', 'portfolio.concentration'],
  relatedConceptKeys: ['portfolio.stress_testing', 'portfolio.risk_budget', 'economy.interest_rates'],
  visualAlt: 'Farklı varlık kutularının faiz, büyüme ve kur gibi ortak risk faktörlerine bağlandığını gösteren sade şema',
  visualAltEn: 'Simple diagram linking different assets to common risk factors such as rates, growth, and FX',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/risk-portfolio/risk-factors-001',
  taskPrompt: 'Hangisi ortak risk faktörü örneğidir?', taskPromptEn: 'Which is an example of a common risk factor?',
  taskChoices: [{ id: 'rates', label: 'Birçok pozisyonu aynı anda etkileyen faiz şoku', labelEn: 'A rate shock affecting many positions at once' }, { id: 'name', label: 'Sadece varlığın adı', labelEn: 'Only the asset name' }, { id: 'color', label: 'Uygulama rengi', labelEn: 'App color' }],
  taskCorrectIds: ['rates'],
  questions: [
    { prompt: 'Risk faktörü neyi anlatır?', promptEn: 'What does a risk factor describe?', choices: [{ id: 'a', label: 'Birden fazla pozisyonu etkileyebilen ortak sürücüyü', labelEn: 'A common driver that can affect multiple positions' }, { id: 'b', label: 'Kesin gelecek getiriyi', labelEn: 'Certain future return' }, { id: 'c', label: 'Yalnız ürün adını', labelEn: 'Only the product name' }], correctId: 'a', explanation: 'Risk faktörü ortak maruziyeti görünür kılar.', explanationEn: 'A risk factor makes common exposure visible.' },
    { prompt: 'Farklı ürünler aynı risk faktörünü taşıyabilir mi?', promptEn: 'Can different products carry the same risk factor?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız hisse ve ETF', labelEn: 'Only stocks and ETFs' }], correctId: 'a', explanation: 'Ekonomik sürücüler ürün sınırlarını aşabilir.', explanationEn: 'Economic drivers can cut across product categories.' },
    { prompt: 'Varlık sayısı risk faktörü çeşitliliğini garanti eder mi?', promptEn: 'Does holding count guarantee risk-factor diversity?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız 10’dan fazla varlıkta', labelEn: 'Only with more than 10 holdings' }], correctId: 'a', explanation: 'Birçok varlık aynı faktöre bağlı olabilir.', explanationEn: 'Many holdings can still depend on the same factor.' },
  ],
  sources: [RISK_PORTFOLIO_SOURCES.methodology],
});

const rebalancing = createFoundationLesson({
  id: 'lesson.portfolio.rebalancing.001',
  slug: 'yeniden-dengeleme-neden-yapilir',
  conceptKey: 'portfolio.rebalancing',
  skillId: 'skill.risk-portfolio',
  competencyId: 'competency.explain-rebalancing.intermediate',
  title: 'Yeniden dengeleme neden yapılır?',
  titleEn: 'Why rebalance a portfolio?',
  objective: 'Fiyat hareketleri portföy ağırlıklarını bozduğunda yeniden dengelemenin ne yaptığını öğren.',
  objectiveEn: 'Explain how market moves can shift portfolio weights and how rebalancing is used to manage that drift.',
  minutes: 5, learningStage: 'intermediate',
  hook: 'Başta yüzde 50–50 olan iki varlık bir yıl sonra hâlâ aynı riski taşır mı?',
  hookEn: 'If two assets start at 50/50, do they necessarily carry the same weights a year later?',
  explanation: 'Varlıklar farklı hızlarda hareket ettikçe portföy ağırlıkları hedef dağılımdan uzaklaşabilir. Yeniden dengeleme, ağırlıkları belirlenen risk çerçevesine geri yaklaştırır. Her küçük harekette işlem yapmak değildir; maliyet ve tolerans bantları önemlidir.',
  explanationEn: 'As prices move at different rates, portfolio weights can drift away from their intended allocation. Rebalancing adjusts weights back toward the chosen strategy or risk framework. It does not mean trading after every small move; costs, taxes, and tolerance bands matter.',
  proExplanation: 'Calendar-based, threshold-based ve hybrid rebalancing yaklaşımları farklı turnover ve tracking özellikleri yaratır. Yeniden dengeleme geleceği tahmin etmekten çok risk çerçevesini koruma işlemidir.',
  proExplanationEn: 'Calendar-based, threshold-based, and hybrid rebalancing approaches create different turnover and tracking characteristics. Rebalancing is primarily about maintaining a risk framework, not forecasting the future.',
  misconception: 'Yeniden dengelemeyi otomatik kâr stratejisi sanma.',
  misconceptionEn: 'Common mistake: treating rebalancing as an automatic profit strategy of buying losers and selling winners.',
  takeaway: 'Yeniden dengeleme hedef ağırlık ve risk sapmasını yönetir.',
  takeawayEn: 'Rebalancing manages drift in target weights and risk structure in a controlled way.',
  prerequisiteConceptKeys: ['portfolio.construction', 'portfolio.risk_budget'],
  relatedConceptKeys: ['portfolio.concentration', 'portfolio.risk_factors', 'market.execution.slippage'],
  visualAlt: 'Başlangıçtaki eşit ağırlıkların fiyat hareketiyle bozulup yeniden hedef dağılıma getirildiğini gösteren sade portföy şeması',
  visualAltEn: 'Simple portfolio diagram showing equal starting weights drifting and then being restored toward target weights',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/risk-portfolio/rebalancing-001',
  taskPrompt: 'Yeniden dengelemenin temel amacı hangisidir?', taskPromptEn: 'What is the main purpose of rebalancing?',
  taskChoices: [{ id: 'risk', label: 'Hedef ağırlık ve risk yapısına yaklaşmak', labelEn: 'Move back toward target weights and risk structure' }, { id: 'predict', label: 'Gelecek fiyatı kesin tahmin etmek', labelEn: 'Predict future prices with certainty' }, { id: 'trade', label: 'Her gün mutlaka işlem yapmak', labelEn: 'Trade every day' }],
  taskCorrectIds: ['risk'],
  questions: [
    { prompt: 'Portföy ağırlıkları neden zamanla değişir?', promptEn: 'Why do portfolio weights change over time?', choices: [{ id: 'a', label: 'Varlık fiyatları farklı hızlarda değiştiği için', labelEn: 'Because asset prices move at different rates' }, { id: 'b', label: 'Yalnız uygulama güncellendiği için', labelEn: 'Only because the app updates' }, { id: 'c', label: 'Hiç değişmez', labelEn: 'They never change' }], correctId: 'a', explanation: 'Farklı getiriler ağırlıkların sürüklenmesine yol açar.', explanationEn: 'Different returns cause weights to drift.' },
    { prompt: 'Yeniden dengeleme her küçük fiyat hareketinde yapılmalı mı?', promptEn: 'Should rebalancing happen after every small price move?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız sabahları', labelEn: 'Only in the morning' }], correctId: 'a', explanation: 'İşlem maliyeti ve tolerans bantları dikkate alınır.', explanationEn: 'Costs and tolerance bands matter.' },
    { prompt: 'Yeniden dengeleme gelecek fiyatı garanti eder mi?', promptEn: 'Does rebalancing guarantee future price outcomes?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız yılda bir', labelEn: 'Only annually' }], correctId: 'a', explanation: 'Amaç risk çerçevesini korumaktır, tahmin değil.', explanationEn: 'Its purpose is maintaining the risk framework, not prediction.' },
  ],
  sources: [RISK_PORTFOLIO_SOURCES.diversification, RISK_PORTFOLIO_SOURCES.methodology],
});

const liquidityRisk = createFoundationLesson({
  id: 'lesson.risk.liquidity.001',
  slug: 'likidite-riski-ne-zaman-buyur',
  conceptKey: 'risk.liquidity',
  skillId: 'skill.risk-portfolio', competencyId: 'competency.identify-liquidity-risk.intermediate',
  title: 'Likidite riski ne zaman büyür?', titleEn: 'When does liquidity risk grow?',
  objective: 'Likidite riskinin pozisyon büyüklüğüyle birlikte neden değiştiğini öğren.',
  objectiveEn: 'Explain portfolio liquidity risk as the risk of being unable to exit a position when needed without excessive price impact.',
  minutes: 5, learningStage: 'intermediate',
  hook: 'Ekranda fiyat görünmesi, büyük bir pozisyonu o fiyattan hemen kapatabileceğin anlamına gelir mi?', hookEn: 'Does seeing a quote mean you can immediately exit a large position at that price?',
  explanation: 'Likidite riski, istediğin büyüklükte pozisyonu makul fiyat etkisiyle kapatamama riskidir. Sığ order book, geniş spread, piyasa stresi veya büyük pozisyon boyutu çıkış maliyetini artırabilir. Bu yüzden likiditeyi pozisyon büyüklüğüyle birlikte okumak gerekir.',
  explanationEn: 'Liquidity risk is the risk that a position cannot be executed when needed, at the desired size, without excessive price impact. Thin order books, wider spreads, market stress, or large position size can raise exit costs. Liquidity should be assessed together with position size, not as a property of the asset alone.',
  proExplanation: 'Market depth, average daily volume, bid-ask spread, participation rate and liquidation horizon gibi ölçüler likidite riskini anlamaya yardım eder. Stres anında normal dönem ölçüleri bozulabilir.',
  proExplanationEn: 'Market depth, average daily volume, bid-ask spread, participation rate, and liquidation horizon can help assess liquidity risk. Normal-period measures may deteriorate during stress.',
  misconception: 'Günlük hacim yüksek diye her büyüklükte aynı maliyetle çıkabileceğini sanma.', misconceptionEn: 'Common mistake: assuming high daily volume means any position size can exit at the same cost.',
  takeaway: 'Likidite riskinde büyüklük ve fiyat etkisini birlikte düşün.', takeawayEn: 'Liquidity risk asks not only “can I exit?” but “at what size and with what price impact?”',
  prerequisiteConceptKeys: ['market.structure.liquidity', 'risk.position_sizing'],
  relatedConceptKeys: ['market.execution.slippage', 'portfolio.concentration', 'portfolio.stress_testing'],
  visualAlt: 'Aynı pozisyon büyüklüğünün derin ve sığ piyasada farklı fiyat etkisiyle çıkabildiğini gösteren sade karşılaştırma', visualAltEn: 'Simple comparison showing the same position size exiting with different price impact in deep and shallow markets',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/risk-portfolio/liquidity-risk-001',
  taskPrompt: 'Hangi durumda likidite riski daha yüksektir?', taskPromptEn: 'When is liquidity risk higher?',
  taskChoices: [{ id: 'thin', label: 'Büyük pozisyon + sığ piyasa + geniş spread', labelEn: 'Large position + shallow market + wide spread' }, { id: 'deep', label: 'Küçük pozisyon + derin piyasa', labelEn: 'Small position + deep market' }, { id: 'logo', label: 'Varlığın logosu değiştiğinde', labelEn: 'When the asset logo changes' }], taskCorrectIds: ['thin'],
  questions: [
    { prompt: 'Likidite riski neyi kapsar?', promptEn: 'What does liquidity risk include?', choices: [{ id: 'a', label: 'Pozisyonu zamanında ve makul fiyat etkisiyle gerçekleştirememe riskini', labelEn: 'Risk of being unable to execute in time without excessive price impact' }, { id: 'b', label: 'Yalnız fiyat yönünü', labelEn: 'Only price direction' }, { id: 'c', label: 'Yalnız şirket kârını', labelEn: 'Only company profit' }], correctId: 'a', explanation: 'Likidite gerçekleştirme kalitesiyle ilgilidir.', explanationEn: 'Liquidity concerns execution quality.' },
    { prompt: 'Pozisyon büyüklüğü likidite riskini etkiler mi?', promptEn: 'Does position size affect liquidity risk?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız tahvillerde', labelEn: 'Only in bonds' }], correctId: 'a', explanation: 'Büyük pozisyon daha fazla piyasa derinliği tüketebilir.', explanationEn: 'Larger positions can consume more market depth.' },
    { prompt: 'Normal dönemde likit görünen piyasa stres anında bozulabilir mi?', promptEn: 'Can a normally liquid market deteriorate during stress?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız gece', labelEn: 'Only at night' }], correctId: 'a', explanation: 'Spread ve derinlik stresle değişebilir.', explanationEn: 'Spreads and depth can change during stress.' },
  ],
  sources: [RISK_PORTFOLIO_SOURCES.diversification, RISK_PORTFOLIO_SOURCES.methodology],
});

const tailRisk = createFoundationLesson({
  id: 'lesson.risk.tail-risk.001', slug: 'tail-risk-nedir', conceptKey: 'risk.tail_risk',
  skillId: 'skill.risk-portfolio', competencyId: 'competency.explain-tail-risk.intermediate',
  title: 'Tail risk neden “nadir = önemsiz” değildir?', titleEn: 'Why does “rare” not mean “unimportant” for tail risk?',
  objective: 'Nadir ama büyük etkili olayların neden tail risk oluşturduğunu öğren.',
  objectiveEn: 'Explain tail risk as rare but high-impact market moves and show why normal-period volatility can understate it.',
  minutes: 5, learningStage: 'intermediate',
  hook: 'Bir olayın nadir olması, portföy için önemsiz olduğu anlamına gelir mi?', hookEn: 'Does a rare event automatically mean it is unimportant for a portfolio?',
  explanation: 'Tail risk, seyrek görülen ama büyük kayıp yaratabilen uç olayları ifade eder. Gap, likidite kuruması, korelasyonların aniden yükselmesi veya sistemik şoklar buna örnektir. Sakin geçmiş, bu riskin etkisini olduğundan küçük gösterebilir.',
  explanationEn: 'Tail risk refers to events in the extreme ends of a distribution that occur infrequently but can create large losses. Gaps, liquidity evaporation, sudden correlation spikes, or systemic shocks are examples. Calm historical periods can understate the probability or impact of extremes.',
  proExplanation: 'Fat tails, skewness, kurtosis, jump risk ve nonlinear payoff yapıları tail exposure analizinde önem kazanır. Tail risk ölçümü model ve veri varsayımlarına duyarlıdır.',
  proExplanationEn: 'Fat tails, skewness, kurtosis, jump risk, and nonlinear payoffs matter in tail exposure analysis. Tail-risk measurement remains sensitive to model and data assumptions.',
  misconception: 'Uzun süredir olmadı diye büyük uç hareketi imkânsız sanma.', misconceptionEn: 'Common mistake: assuming an extreme move is no longer possible because it has not occurred recently.',
  takeaway: 'Tail risk nadir olabilir; etkisi yine büyük olabilir.', takeawayEn: 'Tail risk is rare, not irrelevant. Low frequency is not the same as low impact.',
  prerequisiteConceptKeys: ['risk.volatility', 'portfolio.drawdown'],
  relatedConceptKeys: ['portfolio.stress_testing', 'risk.leverage', 'risk.liquidity'],
  visualAlt: 'Normal fiyat hareketlerinin dışında seyrek fakat büyük bir uç hareketi vurgulayan sade dağılım ve risk görseli', visualAltEn: 'Simple distribution visual highlighting a rare but large move outside normal price fluctuations',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/risk-portfolio/tail-risk-001',
  taskPrompt: 'Hangisi tail risk örneğine daha yakındır?', taskPromptEn: 'Which is closer to an example of tail risk?',
  taskChoices: [{ id: 'shock', label: 'Nadir fakat çok büyük fiyat ve likidite şoku', labelEn: 'A rare but very large price and liquidity shock' }, { id: 'noise', label: 'Normal günlük küçük hareket', labelEn: 'A normal small daily move' }, { id: 'flat', label: 'Fiyatın değişmemesi', labelEn: 'No price change' }], taskCorrectIds: ['shock'],
  questions: [
    { prompt: 'Tail risk hangi olayları anlatır?', promptEn: 'What events does tail risk describe?', choices: [{ id: 'a', label: 'Nadir ama büyük etkili uç olayları', labelEn: 'Rare but high-impact extreme events' }, { id: 'b', label: 'Yalnız günlük küçük hareketleri', labelEn: 'Only small daily moves' }, { id: 'c', label: 'Kesin kazançları', labelEn: 'Certain gains' }], correctId: 'a', explanation: 'Tail risk uç bölgelerdeki büyük etkili olaylara odaklanır.', explanationEn: 'Tail risk focuses on large-impact extreme events.' },
    { prompt: 'Sakin geçmiş dönem tail riski eksik gösterebilir mi?', promptEn: 'Can a calm historical period understate tail risk?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız haftalık grafikte', labelEn: 'Only on weekly charts' }], correctId: 'a', explanation: 'Uç olaylar kısa örneklemde görünmeyebilir.', explanationEn: 'Extreme events may not appear in short samples.' },
    { prompt: 'Nadir olay otomatik olarak önemsiz midir?', promptEn: 'Is a rare event automatically unimportant?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız kaldıraç yoksa', labelEn: 'Only without leverage' }], correctId: 'a', explanation: 'Etki büyüklüğü sıklıktan ayrı değerlendirilir.', explanationEn: 'Impact size is separate from frequency.' },
  ],
  sources: [RISK_PORTFOLIO_SOURCES.methodology],
});

const stressTesting = createFoundationLesson({
  id: 'lesson.portfolio.stress-testing.001', slug: 'stres-testi-ne-ise-yarar', conceptKey: 'portfolio.stress_testing',
  skillId: 'skill.risk-portfolio', competencyId: 'competency.explain-stress-testing.intermediate',
  title: 'Stres testi ne işe yarar?', titleEn: 'What is stress testing for?',
  objective: 'Stres testinin portföyün hangi koşullarda kırılabileceğini nasıl gösterdiğini öğren.',
  objectiveEn: 'Explain why portfolios should be examined under unusual but plausible scenarios before those events occur.',
  minutes: 5, learningStage: 'intermediate',
  hook: 'Geçmiş volatilite düşükse portföyün büyük bir faiz veya likidite şokuna hazır olduğunu söyleyebilir miyiz?', hookEn: 'If historical volatility is low, can we say a portfolio is ready for a major rate or liquidity shock?',
  explanation: 'Stres testi, portföyü sıra dışı ama anlamlı senaryolar altında inceler. Faiz şoku, korelasyon artışı veya likidite bozulması gibi koşullar uygulanabilir. Amaç geleceği tahmin etmek değil, portföyün nerede kırılgan olduğunu görmektir.',
  explanationEn: 'Stress testing examines a portfolio under unusual but plausible scenarios rather than normal expectations. Examples include rapid rate increases, correlations rising together, or deteriorating liquidity. The goal is not to predict the future but to reveal vulnerabilities and challenge risk assumptions.',
  proExplanation: 'Historical scenarios, hypothetical shocks, reverse stress tests and sensitivity analysis farklı kullanım alanlarına sahiptir. Sonuçlar seçilen senaryonun kapsamına ve model varsayımlarına bağlıdır.',
  proExplanationEn: 'Historical scenarios, hypothetical shocks, reverse stress tests, and sensitivity analysis serve different purposes. Results depend on scenario scope and model assumptions.',
  misconception: 'Stres testinden geçti diye portföyü kesin güvenli sayma.', misconceptionEn: 'Common mistake: assuming a portfolio that passes a stress test is guaranteed to be safe in reality.',
  takeaway: 'Stres testi, “bu varsayım bozulursa ne olur?” sorusudur.', takeawayEn: 'Stress testing is not prediction; it asks, “what happens if this assumption breaks?”',
  prerequisiteConceptKeys: ['portfolio.risk_factors', 'risk.tail_risk'],
  relatedConceptKeys: ['portfolio.drawdown', 'risk.liquidity', 'portfolio.construction'],
  visualAlt: 'Normal portföy durumundan faiz şoku, korelasyon artışı ve likidite bozulması gibi üç stres senaryosuna ayrılan sade şema', visualAltEn: 'Simple diagram branching from a normal portfolio into rate-shock, correlation-spike, and liquidity-stress scenarios',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/risk-portfolio/stress-test-001',
  taskPrompt: 'Stres testinin doğru amacı hangisidir?', taskPromptEn: 'What is the correct purpose of stress testing?',
  taskChoices: [{ id: 'vulnerability', label: 'Olağan dışı senaryolardaki kırılganlığı görmek', labelEn: 'Reveal vulnerabilities under unusual scenarios' }, { id: 'forecast', label: 'Gelecek haftayı kesin tahmin etmek', labelEn: 'Predict next week with certainty' }, { id: 'guarantee', label: 'Zararı tamamen ortadan kaldırmak', labelEn: 'Eliminate losses entirely' }], taskCorrectIds: ['vulnerability'],
  questions: [
    { prompt: 'Stres testi neyi sınar?', promptEn: 'What does stress testing challenge?', choices: [{ id: 'a', label: 'Portföyün olağan dışı koşullardaki dayanıklılığını', labelEn: 'Portfolio resilience under unusual conditions' }, { id: 'b', label: 'Yalnız şirket logosunu', labelEn: 'Only company logos' }, { id: 'c', label: 'Kesin gelecek fiyatı', labelEn: 'Certain future prices' }], correctId: 'a', explanation: 'Amaç kırılganlıkları görünür kılmaktır.', explanationEn: 'The purpose is to reveal vulnerabilities.' },
    { prompt: 'Stres testi gelecek olayı kesin bilir mi?', promptEn: 'Does stress testing know the future event with certainty?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız tarihi senaryoda', labelEn: 'Only in historical scenarios' }], correctId: 'a', explanation: 'Senaryolar olasılıkları değil hassasiyetleri sınar.', explanationEn: 'Scenarios test sensitivities, not certainty.' },
    { prompt: 'Tek bir stres senaryosu tüm riskleri kapsar mı?', promptEn: 'Does one stress scenario cover all risks?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız hisse portföyünde', labelEn: 'Only for equity portfolios' }], correctId: 'a', explanation: 'Farklı risk kaynakları farklı senaryolar gerektirir.', explanationEn: 'Different risk sources require different scenarios.' },
  ],
  sources: [RISK_PORTFOLIO_SOURCES.methodology],
});

const lossRecovery = createFoundationLesson({
  id: 'lesson.risk.loss-recovery.001', slug: 'buyuk-kayip-neden-zor-toparlanir', conceptKey: 'risk.loss_recovery',
  skillId: 'skill.risk-portfolio', competencyId: 'competency.explain-loss-recovery.intermediate',
  title: 'Büyük kayıptan toparlanmak neden daha zordur?', titleEn: 'Why is recovering from a large loss harder?',
  objective: 'Büyük kayıplardan toparlanmanın neden orantısız daha yüksek getiri gerektirdiğini öğren.',
  objectiveEn: 'Explain with simple math why a percentage loss and the return required to recover are not symmetric.',
  minutes: 4, learningStage: 'intermediate',
  hook: 'Yüzde 50 düşen bir portföy eski seviyesine dönmek için yüzde 50 yükselse yeter mi?', hookEn: 'If a portfolio falls 50%, is a 50% gain enough to return to the starting level?',
  explanation: 'Kayıp sonrası daha küçük bir sermaye tabanı kalır. 100’den 50’ye düşmek %50 kayıptır; 50’den tekrar 100’e dönmek için %100 artış gerekir. Bu yüzden büyük kayıpları sınırlamak uzun vadeli büyümede önemlidir.',
  explanationEn: 'A percentage loss leaves a smaller capital base. Falling from 100 to 50 is a 50% loss, but returning from 50 to 100 requires a 100% gain. This asymmetry shows why limiting large losses matters for long-run compounding.',
  proExplanation: 'Geometric compounding ve volatility drag nedeniyle büyük dalgalanmalar aritmetik ortalama getirinin ima ettiğinden daha düşük bileşik büyüme yaratabilir. Kayıp toparlanma matematiği tek başına risk politikası değildir ama drawdown etkisini sezgisel kılar.',
  proExplanationEn: 'Geometric compounding and volatility drag can make compounded growth lower than arithmetic average returns imply. Recovery math is not a complete risk policy, but it makes drawdown effects intuitive.',
  misconception: '%30 düşüşün %30 yükselişle tamamen telafi edildiğini sanma.', misconceptionEn: 'Common mistake: assuming a 30% loss is fully recovered by a 30% gain.',
  takeaway: 'Kayıp büyüdükçe toparlanmak için gereken getiri daha hızlı büyür.', takeawayEn: 'As losses grow, the percentage gain required to recover grows disproportionately.',
  prerequisiteConceptKeys: ['portfolio.drawdown', 'risk.basics'],
  relatedConceptKeys: ['risk.leverage', 'portfolio.risk_budget', 'portfolio.stress_testing'],
  visualAlt: '100’den 50’ye yüzde 50 düşüşün ardından tekrar 100’e çıkmak için yüzde 100 yükseliş gerektiğini gösteren sade matematik şeması', visualAltEn: 'Simple math diagram showing a 50% fall from 100 to 50 requires a 100% rise to return to 100',
  taskKind: 'scenario_choice', taskAssetRef: 'edu://academy/risk-portfolio/loss-recovery-001',
  taskPrompt: '100’den 50’ye düşen değer tekrar 100’e çıkmak için ne kadar artmalıdır?', taskPromptEn: 'How much must a value rise to recover from 50 back to 100?',
  taskChoices: [{ id: '100', label: '%100', labelEn: '100%' }, { id: '50', label: '%50', labelEn: '50%' }, { id: '25', label: '%25', labelEn: '25%' }], taskCorrectIds: ['100'],
  questions: [
    { prompt: '%50 kayıp sonrası eski seviyeye dönmek için gereken artış nedir?', promptEn: 'What gain is needed to recover from a 50% loss?', choices: [{ id: 'a', label: '%100', labelEn: '100%' }, { id: 'b', label: '%50', labelEn: '50%' }, { id: 'c', label: '%25', labelEn: '25%' }], correctId: 'a', explanation: '50’nin 100 olması için iki katına çıkması gerekir.', explanationEn: '50 must double to return to 100.' },
    { prompt: 'Kayıp ve toparlanma yüzdeleri simetrik midir?', promptEn: 'Are loss and recovery percentages symmetric?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız küçük kayıplarda tamamen aynıdır', labelEn: 'They are exactly equal for small losses' }], correctId: 'a', explanation: 'Toparlanma daha küçük sermaye tabanından başlar.', explanationEn: 'Recovery starts from a smaller capital base.' },
    { prompt: 'Bu matematik neden risk yönetiminde önemlidir?', promptEn: 'Why does this math matter in risk management?', choices: [{ id: 'a', label: 'Büyük drawdown’ların bileşik büyümeyi zorlaştırdığını gösterir', labelEn: 'It shows how large drawdowns make compounding harder' }, { id: 'b', label: 'Her kaybın kesin geri alınacağını kanıtlar', labelEn: 'It proves every loss will recover' }, { id: 'c', label: 'Gelecek fiyatı tahmin eder', labelEn: 'It predicts future prices' }], correctId: 'a', explanation: 'Büyük kayıp sonrası gereken toparlanma hızla artar.', explanationEn: 'Required recovery rises quickly after large losses.' },
  ],
  sources: [RISK_PORTFOLIO_SOURCES.methodology],
});

export const RISK_PORTFOLIO_EXPANSION_LESSONS = [
  riskFactors,
  rebalancing,
  liquidityRisk,
  tailRisk,
  stressTesting,
  lossRecovery,
] as const;
