import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { RISK_PORTFOLIO_SOURCES } from './riskPortfolioSources';

const correlation = createFoundationLesson({
  id: 'lesson.portfolio.correlation.001',
  slug: 'korelasyon-ne-anlatir',
  conceptKey: 'portfolio.correlation',
  skillId: 'skill.risk-portfolio',
  competencyId: 'competency.interpret-correlation.foundation',
  title: 'Korelasyon ne anlatır, ne anlatmaz?',
  titleEn: 'What does correlation tell you—and what does it not tell you?',
  objective: 'Varlıkların birlikte hareket etme eğilimini korelasyon olarak açıklar ve bunun sabit ya da nedensel bir ilişki olmadığını ayırt eder.',
  objectiveEn: 'Explain correlation as a tendency for assets to move together and distinguish it from a fixed or causal relationship.',
  minutes: 5,
  hook: 'İki varlık son aylarda birlikte yükseldiyse, her koşulda birlikte hareket edecekleri kesin midir?',
  hookEn: 'If two assets rose together in recent months, will they always move together?',
  explanation: 'Korelasyon, iki varlığın getirilerinin ne ölçüde aynı veya zıt yönde hareket ettiğini özetleyen istatistiksel bir ölçüdür. Yüksek pozitif korelasyon birlikte hareket eğilimini, negatif korelasyon ise zıt hareket eğilimini gösterir. Ancak korelasyon zamanla ve piyasa rejimiyle değişebilir; nedensellik kanıtı değildir.',
  explanationEn: 'Correlation is a statistical summary of how closely two assets’ returns move in the same or opposite direction. High positive correlation suggests co-movement, while negative correlation suggests opposite movement. Correlation can change over time and across market regimes, and it does not prove causation.',
  proExplanation: 'Korelasyon tahmini seçilen pencere, veri frekansı ve rejime duyarlıdır. Özellikle stres dönemlerinde daha önce düşük görünen korelasyonlar yükselebilir; bu nedenle tek bir geçmiş korelasyon sayısı kalıcı portföy özelliği gibi ele alınmamalıdır.',
  proExplanationEn: 'Correlation estimates depend on the chosen window, data frequency, and regime. During stress, previously low correlations can rise, so one historical estimate should not be treated as a permanent portfolio property.',
  misconception: 'Yaygın hata: Geçmişte düşük korelasyon görülen iki varlığın gelecekte de mutlaka birbirinden bağımsız davranacağını düşünmek.',
  misconceptionEn: 'Common mistake: assuming two assets with low historical correlation will remain independent in the future.',
  takeaway: 'Korelasyon çeşitlendirme kalitesini anlamaya yardım eder ama sabit değildir ve tek başına portföy kararı vermez.',
  takeawayEn: 'Correlation helps assess diversification quality, but it is not fixed and does not determine a portfolio decision by itself.',
  prerequisiteConceptKeys: ['portfolio.diversification'],
  relatedConceptKeys: ['portfolio.concentration', 'portfolio.risk_budget', 'risk.volatility'],
  visualAlt: 'İki varlığın bazı dönemlerde birlikte, bazı dönemlerde farklı hareket ettiğini karşılaştıran sade korelasyon görseli',
  visualAltEn: 'Simple correlation visual comparing periods when two assets move together and when they diverge',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://academy/risk-portfolio/correlation-001',
  taskPrompt: 'Hangi gözlem daha güçlü çeşitlendirme kanıtıdır?',
  taskPromptEn: 'Which observation is stronger evidence of diversification?',
  taskChoices: [
    { id: 'different', label: 'Varlıkların farklı koşullarda aynı anda aynı yönde hareket etmemesi', labelEn: 'Assets do not always move in the same direction under different conditions' },
    { id: 'same', label: 'Her gün neredeyse aynı yönde hareket etmeleri', labelEn: 'They move in nearly the same direction every day' },
    { id: 'names', label: 'Sadece isimlerinin farklı olması', labelEn: 'Only their names are different' },
  ],
  taskCorrectIds: ['different'],
  questions: [
    { prompt: 'Korelasyon en temel olarak neyi ölçer?', promptEn: 'What does correlation fundamentally measure?', choices: [{ id: 'a', label: 'Varlıkların birlikte hareket etme eğilimini', labelEn: 'The tendency of assets to move together' }, { id: 'b', label: 'Gelecekteki kesin getiriyi', labelEn: 'Certain future return' }, { id: 'c', label: 'Bir varlığın diğerine neden olduğunu', labelEn: 'That one asset causes the other' }], correctId: 'a', explanation: 'Korelasyon ortak hareketi özetler; kesin gelecek veya nedensellik söylemez.', explanationEn: 'Correlation summarizes co-movement; it does not prove future outcomes or causality.' },
    { prompt: 'Korelasyon zamanla değişebilir mi?', promptEn: 'Can correlation change over time?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır, sabittir', labelEn: 'No, it is fixed' }, { id: 'c', label: 'Yalnız hisse senetlerinde', labelEn: 'Only for stocks' }], correctId: 'a', explanation: 'Piyasa rejimi, pencere ve koşullar korelasyonu değiştirebilir.', explanationEn: 'Regime, window, and conditions can change correlation.' },
    { prompt: 'Düşük geçmiş korelasyon tek başına yeterli çeşitlendirme kanıtı mıdır?', promptEn: 'Is low historical correlation by itself enough evidence of diversification?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet, her zaman', labelEn: 'Yes, always' }, { id: 'c', label: 'Yalnız günlük veride', labelEn: 'Only with daily data' }], correctId: 'a', explanation: 'Ağırlıklar, risk faktörleri ve stres davranışı da değerlendirilir.', explanationEn: 'Weights, risk factors, and stress behavior also matter.' },
  ],
  sources: [RISK_PORTFOLIO_SOURCES.diversification, RISK_PORTFOLIO_SOURCES.methodology],
});

const drawdown = createFoundationLesson({
  id: 'lesson.portfolio.drawdown.001',
  slug: 'drawdown-nedir',
  conceptKey: 'portfolio.drawdown',
  skillId: 'skill.risk-portfolio',
  competencyId: 'competency.interpret-drawdown.foundation',
  title: 'Drawdown neden yalnız “zarar” değildir?',
  titleEn: 'Why is drawdown more than just “a loss”?',
  objective: 'Drawdown’u portföy değerinin önceki zirveden ne kadar gerilediğini gösteren yol-bağımlı risk ölçüsü olarak açıklar.',
  objectiveEn: 'Explain drawdown as a path-dependent risk measure showing how far portfolio value has fallen from a previous peak.',
  minutes: 5,
  hook: 'Portföy yıl sonunda başa başsa, yıl içinde yüzde 30 düşmüş olması önemsiz midir?',
  hookEn: 'If a portfolio ends the year flat, does a 30% decline during the year not matter?',
  explanation: 'Drawdown, portföy değerinin ulaştığı bir zirveden sonraki düşüşünü ölçer. Aynı dönem getirisine sahip iki portföy çok farklı düşüş yolları yaşamış olabilir. Büyük drawdown, yalnız sonuca değil süreçte taşınan riskin büyüklüğüne de ışık tutar.',
  explanationEn: 'Drawdown measures the decline in portfolio value from a prior peak. Two portfolios with the same ending return can experience very different paths. A large drawdown reveals the size of risk carried during the journey, not just the final result.',
  proExplanation: 'Maximum drawdown seçilen örnekleme periyoduna, başlangıç-bitiş tarihine ve path dependency’ye duyarlıdır. Tek başına yeterli risk ölçüsü değildir ancak volatiliteyle yakalanmayan kayıp deneyimini görünür kılar.',
  proExplanationEn: 'Maximum drawdown depends on sampling, start/end dates, and path dependency. It is not sufficient by itself, but it makes loss experience visible in a way volatility may not.',
  misconception: 'Yaygın hata: Son dönem getirisi iyi olduğu için aradaki büyük düşüşleri önemsiz saymak.',
  misconceptionEn: 'Common mistake: ignoring large interim declines because the ending return looks good.',
  takeaway: 'Drawdown, “zirveden ne kadar geri geldik?” sorusunu ölçer ve portföy yolundaki riski görünür kılar.',
  takeawayEn: 'Drawdown measures “how far did we fall from the peak?” and makes path risk visible.',
  prerequisiteConceptKeys: ['risk.basics', 'risk.volatility'],
  relatedConceptKeys: ['portfolio.risk_budget', 'risk.leverage', 'portfolio.construction'],
  visualAlt: 'Portföy değerinin zirveye çıkıp ardından düşmesini ve zirve ile dip arasındaki drawdown mesafesini gösteren sade grafik',
  visualAltEn: 'Simple chart showing portfolio value rising to a peak and then falling, with the peak-to-trough drawdown marked',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://academy/risk-portfolio/drawdown-001',
  taskPrompt: 'Hangi bölüm drawdown’u gösterir?',
  taskPromptEn: 'Which segment shows drawdown?',
  taskChoices: [
    { id: 'peaktrough', label: 'Önceki zirveden sonraki dip seviyesine düşüş', labelEn: 'The decline from the previous peak to a later trough' },
    { id: 'rise', label: 'Dipten yeni zirveye yükseliş', labelEn: 'The rise from a trough to a new peak' },
    { id: 'last', label: 'Yalnız son günün getirisi', labelEn: 'Only the final day’s return' },
  ],
  taskCorrectIds: ['peaktrough'],
  questions: [
    { prompt: 'Drawdown neye göre ölçülür?', promptEn: 'What is drawdown measured relative to?', choices: [{ id: 'a', label: 'Önceki zirveye göre', labelEn: 'A previous peak' }, { id: 'b', label: 'Yalnız ilk yatırılan tutara göre', labelEn: 'Only the original invested amount' }, { id: 'c', label: 'Yalnız piyasa hacmine göre', labelEn: 'Only market volume' }], correctId: 'a', explanation: 'Drawdown, bir zirveden sonraki gerilemeyi ölçer.', explanationEn: 'Drawdown measures a decline from a prior peak.' },
    { prompt: 'Aynı yıllık getiriye sahip iki portföyün drawdown’u farklı olabilir mi?', promptEn: 'Can two portfolios with the same annual return have different drawdowns?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız tahvillerde', labelEn: 'Only for bonds' }], correctId: 'a', explanation: 'Getirinin izlediği yol farklı olabilir.', explanationEn: 'The path of returns can differ.' },
    { prompt: 'Drawdown tek başına tüm riskleri ölçer mi?', promptEn: 'Does drawdown measure all risk by itself?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız uzun vadede', labelEn: 'Only over long horizons' }], correctId: 'a', explanation: 'Likidite, korelasyon, kaldıraç ve diğer riskler ayrıca değerlendirilir.', explanationEn: 'Liquidity, correlation, leverage, and other risks still matter.' },
  ],
  sources: [RISK_PORTFOLIO_SOURCES.methodology],
});

const leverage = createFoundationLesson({
  id: 'lesson.risk.leverage.001',
  slug: 'kaldirac-riski-nasil-buyutur',
  conceptKey: 'risk.leverage',
  skillId: 'skill.risk-portfolio',
  competencyId: 'competency.explain-leverage.foundation',
  title: 'Kaldıraç riski nasıl büyütür?',
  titleEn: 'How does leverage amplify risk?',
  objective: 'Kaldıracın sermayeye göre daha büyük piyasa maruziyeti yaratarak hem kazanç hem kayıp etkisini büyütebildiğini açıklar.',
  objectiveEn: 'Explain how leverage creates market exposure larger than the capital committed, amplifying both gains and losses.',
  minutes: 5,
  hook: 'Aynı yüzde 5 fiyat hareketi neden iki hesapta çok farklı sonuç yaratabilir?',
  hookEn: 'Why can the same 5% price move create very different outcomes in two accounts?',
  explanation: 'Kaldıraç, sahip olunan sermayeden daha büyük piyasa maruziyeti taşımayı sağlar. Fiyat hareketi aynı kalsa bile hesap üzerindeki yüzde etkisi daha büyük olabilir. Kaldıraç bu nedenle yalnız potansiyel getiriyi değil, kaybı, margin baskısını ve zorunlu pozisyon azaltma riskini de büyütür.',
  explanationEn: 'Leverage allows market exposure larger than the capital committed. Even if the price move is the same, its percentage effect on the account can be much larger. Leverage therefore amplifies not only potential return but also losses, margin pressure, and forced position reduction risk.',
  proExplanation: 'Gross exposure, net exposure, margin rules, liquidation thresholds and financing costs leverage riskini belirler. Nominal kaldıraç aynı olsa bile ürün yapısı ve gap riskleri gerçekleşen kayıp profilini değiştirebilir.',
  proExplanationEn: 'Gross exposure, net exposure, margin rules, liquidation thresholds, and financing costs shape leverage risk. The same nominal leverage can produce different loss profiles across products and gap conditions.',
  misconception: 'Yaygın hata: Kaldıracı yalnız daha fazla kazanç potansiyeli olarak görmek ve kayıp/likidasyon tarafını ayrı düşünmemek.',
  misconceptionEn: 'Common mistake: viewing leverage only as more upside and ignoring amplified losses and liquidation risk.',
  takeaway: 'Kaldıraç yönü tahmin etmez; mevcut fiyat hareketinin hesap üzerindeki etkisini büyütür.',
  takeawayEn: 'Leverage does not predict direction; it amplifies the account impact of price movement.',
  prerequisiteConceptKeys: ['risk.position_sizing', 'risk.volatility'],
  relatedConceptKeys: ['portfolio.drawdown', 'risk.stop_orders', 'portfolio.risk_budget'],
  visualAlt: 'Aynı fiyat düşüşünün kaldıraçsız ve kaldıraçlı hesapta farklı sermaye etkisini karşılaştıran sade görsel',
  visualAltEn: 'Simple visual comparing the capital impact of the same price decline in unlevered and leveraged accounts',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/risk-portfolio/leverage-001',
  taskPrompt: 'Aynı fiyat hareketinde hangi hesap daha büyük yüzdesel etki yaşar?',
  taskPromptEn: 'Which account experiences a larger percentage impact from the same price move?',
  taskChoices: [
    { id: 'leveraged', label: 'Sermayesine göre daha büyük maruziyet taşıyan hesap', labelEn: 'The account carrying exposure larger than its capital' },
    { id: 'cash', label: 'Kaldıraç kullanmayan daha küçük maruziyetli hesap', labelEn: 'The smaller unlevered account exposure' },
    { id: 'same', label: 'Her zaman ikisi de aynıdır', labelEn: 'They are always identical' },
  ],
  taskCorrectIds: ['leveraged'],
  questions: [
    { prompt: 'Kaldıraç en temel olarak neyi değiştirir?', promptEn: 'What does leverage fundamentally change?', choices: [{ id: 'a', label: 'Sermayeye göre taşınan maruziyeti', labelEn: 'Exposure relative to capital' }, { id: 'b', label: 'Piyasanın gelecekteki yönünü', labelEn: 'Future market direction' }, { id: 'c', label: 'Şirketin gelir tablosunu', labelEn: 'A company’s income statement' }], correctId: 'a', explanation: 'Kaldıraç, sermayeye göre daha büyük maruziyet yaratır.', explanationEn: 'Leverage creates larger exposure relative to capital.' },
    { prompt: 'Kaldıraç yalnız kazancı mı büyütür?', promptEn: 'Does leverage amplify only gains?', choices: [{ id: 'a', label: 'Hayır; kayıpları da büyütebilir', labelEn: 'No; it can amplify losses too' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız volatilite düşükse', labelEn: 'Only when volatility is low' }], correctId: 'a', explanation: 'Maruziyet büyüdüğü için iki yöndeki hareketin hesap etkisi büyür.', explanationEn: 'Larger exposure magnifies account impact in both directions.' },
    { prompt: 'Kaldıraç kullanırken hangi ek risk önemlidir?', promptEn: 'What additional risk matters when using leverage?', choices: [{ id: 'a', label: 'Margin ve zorunlu pozisyon azaltma riski', labelEn: 'Margin and forced-reduction risk' }, { id: 'b', label: 'Logo değişimi', labelEn: 'Logo changes' }, { id: 'c', label: 'Grafik arka planı', labelEn: 'Chart background' }], correctId: 'a', explanation: 'Margin koşulları kayıp sırasında pozisyonu zorla küçültebilir.', explanationEn: 'Margin conditions can force a position to be reduced during losses.' },
  ],
  sources: [RISK_PORTFOLIO_SOURCES.leverage, RISK_PORTFOLIO_SOURCES.methodology],
});

const concentration = createFoundationLesson({
  id: 'lesson.portfolio.concentration.001',
  slug: 'yogunlasma-riski-nedir',
  conceptKey: 'portfolio.concentration',
  skillId: 'skill.risk-portfolio',
  competencyId: 'competency.identify-concentration.foundation',
  title: 'Yoğunlaşma riski nasıl oluşur?',
  titleEn: 'How does concentration risk arise?',
  objective: 'Portföyün büyük bölümünün tek varlık, sektör veya ortak risk faktörüne bağlı olmasını yoğunlaşma riski olarak tanımlar.',
  objectiveEn: 'Define concentration risk as a large share of a portfolio depending on one asset, sector, or common risk factor.',
  minutes: 5,
  hook: 'Portföyde 10 farklı hisse varsa otomatik olarak iyi çeşitlendirilmiş sayılır mı?',
  hookEn: 'If a portfolio holds 10 different stocks, is it automatically well diversified?',
  explanation: 'Yoğunlaşma, portföy sonucunun küçük sayıdaki pozisyona veya aynı risk faktörüne aşırı bağlı olmasıdır. Varlık sayısı yüksek olsa bile aynı sektör, ülke, tema veya faiz duyarlılığı portföyü tek kaynağa bağımlı bırakabilir. Bu yüzden ağırlık ve ortak risk kaynağı birlikte değerlendirilir.',
  explanationEn: 'Concentration means portfolio outcomes depend too heavily on a small number of positions or the same risk factor. Even with many holdings, exposure to the same sector, country, theme, or rate sensitivity can leave the portfolio dependent on one source of risk. Weights and common risk drivers both matter.',
  proExplanation: 'Top-position weights, sector/factor exposures, marginal contribution to risk and stress scenarios concentration analizinde kullanılabilir. Nominal pozisyon sayısı ekonomik çeşitliliği garanti etmez.',
  proExplanationEn: 'Top-position weights, sector/factor exposures, marginal contribution to risk, and stress scenarios can be used to assess concentration. Nominal holding count does not guarantee economic diversification.',
  misconception: 'Yaygın hata: “Çok varlık var” bilgisini, ağırlıklar ve ortak faktörlere bakmadan gerçek çeşitlendirme saymak.',
  misconceptionEn: 'Common mistake: treating a high holding count as real diversification without checking weights and common factors.',
  takeaway: 'Yoğunlaşma riskinde soru yalnız “kaç varlık var?” değil, “sonucu aslında kaç risk kaynağı belirliyor?” sorusudur.',
  takeawayEn: 'Concentration is not just “how many assets?” but “how many risk sources actually drive the result?”',
  prerequisiteConceptKeys: ['portfolio.diversification', 'portfolio.correlation'],
  relatedConceptKeys: ['portfolio.risk_budget', 'portfolio.construction', 'risk.volatility'],
  visualAlt: 'On farklı varlığın çoğunun aynı sektör faktörüne bağlı olduğu yoğun portföy ile daha dengeli risk kaynaklarını karşılaştıran sade şema',
  visualAltEn: 'Simple diagram comparing a portfolio of many holdings tied to one sector factor with more balanced risk sources',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/risk-portfolio/concentration-001',
  taskPrompt: 'Hangi portföyde yoğunlaşma riski daha yüksektir?',
  taskPromptEn: 'Which portfolio has higher concentration risk?',
  taskChoices: [
    { id: 'sector', label: 'Pozisyonların çoğu aynı sektör ve aynı risk faktörüne bağlı', labelEn: 'Most positions depend on the same sector and risk factor' },
    { id: 'balanced', label: 'Ağırlıklar ve risk kaynakları daha dengeli dağılmış', labelEn: 'Weights and risk sources are more balanced' },
    { id: 'count', label: 'Sadece varlık sayısı yüksek olan', labelEn: 'The one with only a high holding count' },
  ],
  taskCorrectIds: ['sector'],
  questions: [
    { prompt: 'Yoğunlaşma riski yalnız tek hisse taşımakla mı oluşur?', promptEn: 'Does concentration risk arise only from holding one stock?', choices: [{ id: 'a', label: 'Hayır; ortak sektör veya faktörlerden de oluşabilir', labelEn: 'No; common sectors or factors can also create it' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız kriptoda', labelEn: 'Only in crypto' }], correctId: 'a', explanation: 'Birden fazla pozisyon aynı risk kaynağına bağlı olabilir.', explanationEn: 'Multiple positions can depend on the same risk source.' },
    { prompt: 'Varlık sayısının yüksek olması tek başına neyi garanti etmez?', promptEn: 'What does a high number of holdings not guarantee by itself?', choices: [{ id: 'a', label: 'Gerçek çeşitlendirmeyi', labelEn: 'True diversification' }, { id: 'b', label: 'Portföyde varlık bulunduğunu', labelEn: 'That the portfolio has holdings' }, { id: 'c', label: 'Fiyatların değiştiğini', labelEn: 'That prices change' }], correctId: 'a', explanation: 'Ağırlık ve ortak risk faktörleri ayrıca önemlidir.', explanationEn: 'Weights and common risk factors also matter.' },
    { prompt: 'Yoğunlaşma analizinde hangi bilgi önemlidir?', promptEn: 'What information matters for concentration analysis?', choices: [{ id: 'a', label: 'Pozisyon ağırlıkları ve ortak risk faktörleri', labelEn: 'Position weights and common risk factors' }, { id: 'b', label: 'Yalnız şirket isimleri', labelEn: 'Only company names' }, { id: 'c', label: 'Yalnız işlem uygulamasının rengi', labelEn: 'Only the app color' }], correctId: 'a', explanation: 'Gerçek yoğunlaşma ekonomik maruziyetle ilgilidir.', explanationEn: 'Real concentration is about economic exposure.' },
  ],
  sources: [RISK_PORTFOLIO_SOURCES.diversification, RISK_PORTFOLIO_SOURCES.methodology],
});

const riskBudget = createFoundationLesson({
  id: 'lesson.portfolio.risk-budget.001',
  slug: 'risk-butcesi-nedir',
  conceptKey: 'portfolio.risk_budget',
  skillId: 'skill.risk-portfolio',
  competencyId: 'competency.explain-risk-budget.foundation',
  title: 'Risk bütçesi neden para bütçesinden farklıdır?',
  titleEn: 'Why is a risk budget different from a money budget?',
  objective: 'Portföy sermayesinin dağılımı ile toplam riske katkının dağılımının aynı şey olmadığını açıklar.',
  objectiveEn: 'Explain why capital allocation and contribution to total portfolio risk are not the same thing.',
  minutes: 5,
  hook: 'İki varlığa yüzde 50–50 para ayırmak, riski de yüzde 50–50 paylaştırır mı?',
  hookEn: 'If capital is split 50/50 between two assets, is risk also split 50/50?',
  explanation: 'Risk bütçesi, portföyde hangi pozisyon veya risk kaynağının toplam riske ne kadar katkı yapmasına izin verildiğini düşünme biçimidir. Sermaye ağırlığı eşit olsa bile volatilite, korelasyon ve kaldıraç farklıysa risk katkıları eşit olmayabilir.',
  explanationEn: 'A risk budget is a way to think about how much each position or risk source is allowed to contribute to total portfolio risk. Equal capital weights do not imply equal risk contributions when volatility, correlation, or leverage differ.',
  proExplanation: 'Risk contribution, marginal contribution to risk ve volatility targeting gibi yöntemler daha ileri risk bütçelemesinde kullanılabilir. Tahmin hataları ve değişen korelasyonlar nedeniyle risk bütçesi de dinamik izleme gerektirir.',
  proExplanationEn: 'Risk contribution, marginal contribution to risk, and volatility targeting can be used in more advanced risk budgeting. Estimation errors and changing correlations mean the budget still requires monitoring.',
  misconception: 'Yaygın hata: Para ağırlığı eşitse risk ağırlığının da otomatik eşit olduğunu varsaymak.',
  misconceptionEn: 'Common mistake: assuming equal capital weights automatically mean equal risk weights.',
  takeaway: 'Portföyde “ne kadar para koyduk?” ile “toplam riski ne kadar etkiliyor?” farklı sorulardır.',
  takeawayEn: '“How much capital did we allocate?” and “how much does it drive total risk?” are different questions.',
  prerequisiteConceptKeys: ['risk.position_sizing', 'portfolio.correlation'],
  relatedConceptKeys: ['risk.volatility', 'risk.leverage', 'portfolio.construction'],
  visualAlt: 'Eşit sermaye ağırlıklı iki varlığın farklı volatilite nedeniyle toplam riske farklı katkı yaptığını gösteren sade karşılaştırma',
  visualAltEn: 'Simple comparison showing two equally funded assets contributing differently to total risk because of different volatility',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/risk-portfolio/risk-budget-001',
  taskPrompt: 'İki varlık sermayede eşit ağırlıklıysa risk katkısı neden farklı olabilir?',
  taskPromptEn: 'Why can risk contributions differ when two assets have equal capital weights?',
  taskChoices: [
    { id: 'risk', label: 'Volatilite ve korelasyonları farklı olduğu için', labelEn: 'Because their volatility and correlations differ' },
    { id: 'names', label: 'İsimleri farklı olduğu için', labelEn: 'Because their names differ' },
    { id: 'equal', label: 'Farklı olamaz; mutlaka eşittir', labelEn: 'They cannot differ; they must be equal' },
  ],
  taskCorrectIds: ['risk'],
  questions: [
    { prompt: 'Risk bütçesi neyi dağıtmaya odaklanır?', promptEn: 'What does risk budgeting focus on allocating?', choices: [{ id: 'a', label: 'Toplam riske katkıyı', labelEn: 'Contribution to total risk' }, { id: 'b', label: 'Yalnız şirket sayısını', labelEn: 'Only the number of companies' }, { id: 'c', label: 'Yalnız nakit bakiyesini', labelEn: 'Only cash balance' }], correctId: 'a', explanation: 'Amaç pozisyonların toplam risk üzerindeki etkisini düşünmektir.', explanationEn: 'The goal is to think about each position’s effect on total risk.' },
    { prompt: 'Eşit para ağırlığı eşit risk katkısı demek midir?', promptEn: 'Do equal capital weights imply equal risk contributions?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Her zaman evet', labelEn: 'Always yes' }, { id: 'c', label: 'Yalnız ETF’lerde', labelEn: 'Only in ETFs' }], correctId: 'a', explanation: 'Volatilite, korelasyon ve kaldıraç riski değiştirebilir.', explanationEn: 'Volatility, correlation, and leverage can change risk contribution.' },
    { prompt: 'Risk bütçesi zaman içinde yeniden değerlendirilir mi?', promptEn: 'Should a risk budget be reassessed over time?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır, bir kez yeter', labelEn: 'No, once is enough' }, { id: 'c', label: 'Yalnız fiyat yükselirse', labelEn: 'Only if price rises' }], correctId: 'a', explanation: 'Volatilite ve korelasyonlar değişebilir.', explanationEn: 'Volatility and correlations can change.' },
  ],
  sources: [RISK_PORTFOLIO_SOURCES.methodology],
});

const portfolioConstruction = createFoundationLesson({
  id: 'lesson.portfolio.construction.001',
  slug: 'portfoy-nasil-kurulur',
  conceptKey: 'portfolio.construction',
  skillId: 'skill.risk-portfolio',
  competencyId: 'competency.explain-portfolio-construction.foundation',
  title: 'Portföy oluşturmak neden varlık seçmekten fazlasıdır?',
  titleEn: 'Why is portfolio construction more than picking assets?',
  objective: 'Portföy oluşturmayı amaç, kısıt, risk kaynakları, ağırlıklar ve izleme kararlarının birlikte tasarlanması olarak açıklar.',
  objectiveEn: 'Explain portfolio construction as designing objectives, constraints, risk sources, weights, and monitoring together.',
  minutes: 5,
  hook: 'Beğendiğin beş varlığı yan yana koymak, otomatik olarak iyi bir portföy oluşturur mu?',
  hookEn: 'Does placing five assets you like side by side automatically create a good portfolio?',
  explanation: 'Portföy oluşturma, tek tek varlık seçmekten daha geniştir. Amaç ve zaman ufku, likidite ihtiyacı, risk bütçesi, çeşitlendirme, korelasyon, yoğunlaşma ve yeniden dengeleme kuralları birlikte düşünülür. İyi görünen varlıkların birleşimi, birlikte kötü bir risk profili yaratabilir.',
  explanationEn: 'Portfolio construction is broader than selecting individual assets. Objectives and horizon, liquidity needs, risk budget, diversification, correlation, concentration, and rebalancing rules are considered together. Assets that look attractive individually can combine into a poor risk profile.',
  proExplanation: 'Strategic asset allocation, tactical tilts, constraints, turnover, transaction costs and rebalancing bands daha ileri portföy tasarımının parçalarıdır. Optimal görünen çözüm varsayımlara ve tahmin hatalarına duyarlıdır.',
  proExplanationEn: 'Strategic asset allocation, tactical tilts, constraints, turnover, transaction costs, and rebalancing bands are parts of more advanced portfolio design. Any apparently optimal solution is sensitive to assumptions and estimation error.',
  misconception: 'Yaygın hata: Tek tek iyi görünen varlıkların toplamının otomatik olarak dengeli portföy oluşturacağını düşünmek.',
  misconceptionEn: 'Common mistake: assuming a collection of individually attractive assets automatically forms a balanced portfolio.',
  takeaway: 'Portföy kalitesi tek varlık seçiminden değil, varlıkların birlikte nasıl risk ürettiğinden doğar.',
  takeawayEn: 'Portfolio quality comes not from individual picks alone, but from how holdings create risk together.',
  prerequisiteConceptKeys: ['portfolio.diversification', 'portfolio.risk_budget'],
  relatedConceptKeys: ['portfolio.correlation', 'portfolio.concentration', 'portfolio.drawdown'],
  visualAlt: 'Amaç ve kısıtlardan varlık ağırlıkları, risk kontrolü ve izlemeye uzanan sade portföy oluşturma akış şeması',
  visualAltEn: 'Simple portfolio-construction flow from objectives and constraints to weights, risk control, and monitoring',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/risk-portfolio/construction-001',
  taskPrompt: 'Hangi yaklaşım portföy oluşturmayı daha doğru tarif eder?',
  taskPromptEn: 'Which approach better describes portfolio construction?',
  taskChoices: [
    { id: 'system', label: 'Amaç, kısıt, risk kaynakları ve ağırlıkları birlikte tasarlamak', labelEn: 'Design objectives, constraints, risk sources, and weights together' },
    { id: 'favorites', label: 'Sadece en sevilen varlıkları seçmek', labelEn: 'Only pick favorite assets' },
    { id: 'count', label: 'Varlık sayısını mümkün olduğunca artırmak', labelEn: 'Maximize the number of holdings' },
  ],
  taskCorrectIds: ['system'],
  questions: [
    { prompt: 'Portföy oluşturmanın ilk sorularından biri hangisidir?', promptEn: 'What is one of the first questions in portfolio construction?', choices: [{ id: 'a', label: 'Amaç, zaman ufku ve kısıtlar nedir?', labelEn: 'What are the objective, horizon, and constraints?' }, { id: 'b', label: 'En parlak grafik hangisi?', labelEn: 'Which chart looks brightest?' }, { id: 'c', label: 'En çok konuşulan varlık hangisi?', labelEn: 'Which asset is most discussed?' }], correctId: 'a', explanation: 'Portföy tasarımı amaç ve kısıtlarla başlar.', explanationEn: 'Portfolio design starts with objectives and constraints.' },
    { prompt: 'Tek tek iyi görünen varlıklar birlikte kötü portföy oluşturabilir mi?', promptEn: 'Can individually attractive assets form a poor portfolio together?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız kriptoda', labelEn: 'Only in crypto' }], correctId: 'a', explanation: 'Korelasyon, yoğunlaşma ve ağırlıklar birleşik riski bozabilir.', explanationEn: 'Correlation, concentration, and weights can create poor combined risk.' },
    { prompt: 'Portföy oluşturma yalnız ilk gün yapılan bir seçim midir?', promptEn: 'Is portfolio construction only a one-time choice on day one?', choices: [{ id: 'a', label: 'Hayır; izleme ve yeniden değerlendirme gerekir', labelEn: 'No; monitoring and reassessment are needed' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız fiyat düşerse', labelEn: 'Only if prices fall' }], correctId: 'a', explanation: 'Risk kaynakları ve ağırlıklar zamanla değişir.', explanationEn: 'Risk sources and weights change over time.' },
  ],
  sources: [RISK_PORTFOLIO_SOURCES.diversification, RISK_PORTFOLIO_SOURCES.methodology],
});

export const RISK_PORTFOLIO_FOUNDATION_LESSONS = [
  correlation,
  drawdown,
  leverage,
  concentration,
  riskBudget,
  portfolioConstruction,
] as const;
