import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { SMC_ICT_SOURCES } from './smcIctSources';

const methodology = createFoundationLesson({
  id: 'lesson.smc.methodology.001', slug: 'smc-ict-dili-neden-metodolojiye-bagli', conceptKey: 'smc.methodology', skillId: 'skill.smc-ict', competencyId: 'competency.smc-methodology.advanced',
  title: 'SMC / ICT dili neden metodolojiye bağlıdır?', titleEn: 'Why is SMC / ICT terminology methodology-dependent?',
  objective: 'SMC/ICT terimlerinin evrensel yasa değil, belirli yöntemlerde kullanılan yorum etiketleri olduğunu öğren.', objectiveEn: 'Explain that SMC/ICT terms are labels used within interpretive frameworks rather than universal market laws.', minutes: 5,
  hook: 'İki eğitimci aynı grafiğe farklı “order block” veya “MSS” etiketi koyuyorsa hangisi kesin gerçektir?', hookEn: 'If two educators label the same chart differently as an “order block” or “MSS,” which label is the absolute truth?',
  explanation: 'SMC/ICT terimlerinin anlamı kaynağa göre değişebilir. FINM8 bu kavramları fiyat yapısını tarif eden yöntem dili olarak ele alır; kurumsal niyet, manipülasyon veya gelecek yön kanıtı saymaz. Önce kullanılan tanımı ve bağlamı netleştirmek gerekir.', explanationEn: 'Many terms used under SMC and ICT vary by source and methodology. FINM8 teaches them as observational and structural language, not as proof of institutional intent, manipulation, or future price movement. First define the term, timeframe, and context being used.',
  proExplanation: 'Terminology such as sweep, grab, inducement, MSS, order block, and mitigation can overlap or differ across frameworks. Reproducible analysis requires an explicit operational definition rather than relying on the label alone.', proExplanationEn: 'Terms such as sweep, grab, inducement, MSS, order block, and mitigation can overlap or differ across frameworks. Reproducible analysis requires an explicit operational definition rather than relying on the label alone.',
  misconception: 'Bir metodoloji etiketini piyasanın tartışmasız gerçeği gibi sunma.', misconceptionEn: 'Common mistake: presenting one methodology label as a universal and undisputed market fact.',
  takeaway: 'Önce tanımı sabitle; etiketi tek başına sinyal sayma.', takeawayEn: 'Fix the definition first; do not treat the label alone as a signal or proof of intent.',
  prerequisiteConceptKeys: ['market.structure.bos', 'market.structure.choch'], relatedConceptKeys: ['market.structure.liquidity', 'market.structure.fvg', 'market.structure.order_block'],
  visualAlt: 'Aynı fiyat grafiğine iki farklı metodoloji etiketi konduğunu ve ortak gözlemin etiketten ayrıldığını gösteren karşılaştırma', visualAltEn: 'Comparison showing two methodology labels on the same price chart while separating the shared observation from the label',
  taskKind: 'chart_identification', taskAssetRef: 'edu://academy/smc-ict/smc-methodology-001', taskPrompt: 'Hangi yaklaşım daha sağlamdır?', taskPromptEn: 'Which approach is more robust?',
  taskChoices: [{ id: 'define', label: 'Etiketi kullanmadan önce operasyonel tanımı ve bağlamı belirtmek', labelEn: 'State the operational definition and context before using the label' }, { id: 'universal', label: 'Tek bir tanımı evrensel gerçek kabul etmek', labelEn: 'Treat one definition as universal truth' }, { id: 'intent', label: 'Grafikten piyasa katılımcılarının niyetini kesin çıkarmak', labelEn: 'Infer market participants’ intent with certainty from the chart' }], taskCorrectIds: ['define'],
  questions: [
    { prompt: 'SMC/ICT terimleri her kaynakta aynı mı tanımlanır?', promptEn: 'Are SMC/ICT terms defined identically by every source?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece kriptoda farklıdır', labelEn: 'Only in crypto' }], correctId: 'a', explanation: 'Tanımlar yöntem ve kaynağa göre değişebilir.', explanationEn: 'Definitions can vary by methodology and source.' },
    { prompt: 'Bir SMC etiketi tek başına işlem sinyali midir?', promptEn: 'Is an SMC label a standalone trade signal?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Bağlam ve risk ayrıca değerlendirilir.', explanationEn: 'Context and risk still need evaluation.' },
    { prompt: 'Grafik etiketi kurumsal niyeti kanıtlar mı?', promptEn: 'Does a chart label prove institutional intent?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız büyük mumda', labelEn: 'Only after a large candle' }], correctId: 'a', explanation: 'Fiyat davranışından niyet kesin olarak doğrulanamaz.', explanationEn: 'Intent cannot be established with certainty from price behavior alone.' },
  ], sources: [SMC_ICT_SOURCES.methodology],
});

const sweep = createFoundationLesson({
  id: 'lesson.smc.liquidity-sweep.001', slug: 'liquidity-sweep-nedir', conceptKey: 'smc.liquidity_sweep', skillId: 'skill.smc-ict', competencyId: 'competency.liquidity-sweep.advanced',
  title: 'Liquidity sweep neyi tarif eder?', titleEn: 'What does a liquidity sweep describe?',
  objective: 'Liquidity sweep etiketinin hangi fiyat davranışını tarif ettiğini ve neden tek başına sinyal olmadığını öğren.', objectiveEn: 'Define a liquidity sweep as trading beyond an obvious high/low followed by a return, while distinguishing it from a standalone directional signal.', minutes: 5,
  hook: 'Fiyat önceki tepenin biraz üstüne çıkıp hemen geri döndüğünde “likidite alındı” demek neyi gerçekten gözlemlediğimizi anlatır?', hookEn: 'When price trades just above a prior high and quickly returns, what are we actually observing when we say “liquidity was taken”?',
  explanation: 'Liquidity sweep genellikle fiyatın belirgin bir tepe veya dip seviyesini aşıp sonra eski alanın içine dönmesini tarif eder. Grafikten gördüğümüz şey seviyenin iki tarafında işlem olduğudur; bunu kimin ve hangi niyetle yaptığı kesin bilinmez.', explanationEn: 'In SMC/ICT language, a liquidity sweep commonly describes price trading beyond an obvious swing high/low or similar reference and then returning inside the prior area. The observable fact is trading on both sides of the level; who caused it and with what intent cannot be known with certainty from the chart.',
  proExplanation: 'Operational definitions should specify the reference swing, wick versus close criteria, return condition, timeframe, and maximum evaluation window. Without these, “sweep” can become an after-the-fact label.', proExplanationEn: 'Operational definitions should specify the reference swing, wick-versus-close criteria, return condition, timeframe, and maximum evaluation window. Otherwise “sweep” can become an after-the-fact label.',
  misconception: 'Her fitil taşmasını sweep sayma veya otomatik ters yön bekleme.', misconceptionEn: 'Common mistake: calling every wick overshoot a liquidity sweep or automatically expecting reversal after one.',
  takeaway: 'Sweep bir davranış etiketidir; dönüş garantisi değildir.', takeawayEn: 'A sweep is a price-behavior label, not a reversal guarantee or proof of manipulation.',
  prerequisiteConceptKeys: ['smc.methodology', 'market.structure.liquidity'], relatedConceptKeys: ['market.structure.support_resistance', 'smc.liquidity_grab', 'market.structure.choch'],
  visualAlt: 'Önceki tepenin üstüne kısa taşma ve tekrar seviye altına dönüşü gösteren sade liquidity sweep grafiği', visualAltEn: 'Simple chart showing a brief move above a prior high followed by a return below the level',
  taskKind: 'chart_identification', taskAssetRef: 'edu://academy/smc-ict/liquidity-sweep-001', taskPrompt: 'Hangi hareket sweep tanımına daha yakındır?', taskPromptEn: 'Which move better fits a sweep definition?',
  taskChoices: [{ id: 'return', label: 'Belirgin seviyenin ötesine geçip tekrar önceki alanın içine dönmek', labelEn: 'Trade beyond a clear level and return inside the prior area' }, { id: 'trend', label: 'Seviyeye hiç yaklaşmadan trend sürdürmek', labelEn: 'Continue a trend without approaching the level' }, { id: 'anywick', label: 'Grafikteki herhangi bir küçük fitil', labelEn: 'Any small wick on the chart' }], taskCorrectIds: ['return'],
  questions: [
    { prompt: 'Liquidity sweep tek başına dönüş garantisi midir?', promptEn: 'Does a liquidity sweep guarantee a reversal?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece günlük grafikte', labelEn: 'Only on daily charts' }], correctId: 'a', explanation: 'Sonraki yapı ve bağlam ayrıca değerlendirilir.', explanationEn: 'Subsequent structure and context still matter.' },
    { prompt: 'Sweep tanımında referans seviye önemli midir?', promptEn: 'Does the reference level matter when defining a sweep?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece hacimde', labelEn: 'Only for volume' }], correctId: 'a', explanation: 'Rastgele küçük seviyeler etiketi anlamsızlaştırabilir.', explanationEn: 'Random minor levels can make the label meaningless.' },
    { prompt: 'Sweep grafikten manipülasyonu kanıtlar mı?', promptEn: 'Does a sweep prove manipulation from the chart alone?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her fitilde', labelEn: 'On every wick' }], correctId: 'a', explanation: 'Niyet doğrudan gözlenmez.', explanationEn: 'Intent is not directly observable.' },
  ], sources: [SMC_ICT_SOURCES.methodology, SMC_ICT_SOURCES.structure],
});

const grab = createFoundationLesson({
  id: 'lesson.smc.liquidity-grab.001', slug: 'liquidity-grab-ve-sweep-farki', conceptKey: 'smc.liquidity_grab', skillId: 'skill.smc-ict', competencyId: 'competency.liquidity-grab.advanced',
  title: 'Liquidity grab ile sweep aynı şey midir?', titleEn: 'Are liquidity grab and sweep the same thing?',
  objective: 'Grab ile sweep ayrımının yönteme göre değişebildiğini ve kriter gerektirdiğini öğren.', objectiveEn: 'Explain that grab and sweep can overlap across sources and require measurable criteria if distinguished.', minutes: 5,
  hook: 'Aynı fitile birisi “grab”, diğeri “sweep” diyorsa grafik mi değişti, terminoloji mi?', hookEn: 'If one person calls the same wick a “grab” and another a “sweep,” did the chart change or the terminology?',
  explanation: 'Bazı kaynaklar grab’i daha kısa ve hızlı seviye aşımı, sweep’i daha geniş hareket olarak ayırır; bazıları iki terimi aynı anlamda kullanır. Bu yüzden ayrım yapılacaksa kullanılan yöntemin kriteri açık olmalıdır.', explanationEn: 'Some SMC/ICT frameworks distinguish a grab as a sharper, shorter breach and a sweep as a broader clearing move; other sources use the words interchangeably. FINM8 only uses the distinction when the methodology states explicit criteria.',
  proExplanation: 'Useful criteria can include penetration distance, time spent beyond the level, close location, return speed, and the structural importance of the reference. The label should follow the criteria—not be chosen after the outcome.', proExplanationEn: 'Useful criteria can include penetration distance, time beyond the level, close location, return speed, and structural importance of the reference. The label should follow the criteria, not be chosen after the outcome.',
  misconception: 'Grab ile sweep arasında evrensel tek sınır varmış gibi davranma.', misconceptionEn: 'Common mistake: assuming there is one universal technical boundary between grab and sweep.',
  takeaway: 'Grab/sweep ayrımı kullanıyorsan önce kriterini tanımla.', takeawayEn: 'If you distinguish grab from sweep, define the criteria first; otherwise the labels may describe the same observation.',
  prerequisiteConceptKeys: ['smc.liquidity_sweep'], relatedConceptKeys: ['market.structure.liquidity', 'smc.methodology', 'smc.inducement'],
  visualAlt: 'Aynı referans seviyesinde kısa keskin taşma ile daha geniş seviye ötesi hareketi yan yana karşılaştıran grab ve sweep görseli', visualAltEn: 'Side-by-side visual comparing a sharp brief breach with a broader move beyond the same reference level',
  taskKind: 'chart_identification', taskAssetRef: 'edu://academy/smc-ict/liquidity-grab-001', taskPrompt: 'Grab/sweep ayrımını en sağlam yapan nedir?', taskPromptEn: 'What makes a grab/sweep distinction most robust?',
  taskChoices: [{ id: 'criteria', label: 'Önceden tanımlanmış ölçülebilir kriterler', labelEn: 'Predefined measurable criteria' }, { id: 'outcome', label: 'Sonucu gördükten sonra etiketi seçmek', labelEn: 'Choose the label after seeing the outcome' }, { id: 'authority', label: 'Tek bir eğitmenin kelimesini evrensel kabul etmek', labelEn: 'Treat one educator’s wording as universal' }], taskCorrectIds: ['criteria'],
  questions: [
    { prompt: 'Grab ve sweep tanımı kaynaklara göre değişebilir mi?', promptEn: 'Can grab and sweep definitions vary by source?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece forexte', labelEn: 'Only in FX' }], correctId: 'a', explanation: 'Terminoloji metodolojiye bağlıdır.', explanationEn: 'Terminology is methodology-dependent.' },
    { prompt: 'Etiketi sonuçtan sonra seçmek neden zayıftır?', promptEn: 'Why is choosing the label after the outcome weak?', choices: [{ id: 'a', label: 'Geriye dönük uyarlama yaratabilir', labelEn: 'It can create hindsight fitting' }, { id: 'b', label: 'Spread büyür', labelEn: 'Spread widens' }, { id: 'c', label: 'Hacim kaybolur', labelEn: 'Volume disappears' }], correctId: 'a', explanation: 'Kriter önceden belli değilse etiket esnekleşir.', explanationEn: 'Without predefined criteria the label becomes flexible.' },
    { prompt: 'Grab otomatik işlem sinyali midir?', promptEn: 'Is a grab an automatic trade signal?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Bağlam ve risk gerekir.', explanationEn: 'Context and risk are still required.' },
  ], sources: [SMC_ICT_SOURCES.methodology],
});

const inducement = createFoundationLesson({
  id: 'lesson.smc.inducement.001', slug: 'inducement-ne-anlatir', conceptKey: 'smc.inducement', skillId: 'skill.smc-ict', competencyId: 'competency.inducement.advanced',
  title: 'Inducement etiketi ne anlatır, neyi kanıtlamaz?', titleEn: 'What does the inducement label describe—and what does it not prove?',
  objective: 'Inducement etiketinin neyi tarif ettiğini ve neden niyet kanıtı olmadığını öğren.', objectiveEn: 'Explain inducement in some SMC/ICT frameworks as a notable intermediate structure/liquidity reference while separating it from claims of intent.', minutes: 5,
  hook: 'Bir ara dip kırıldı diye “piyasa traderları kandırdı” diyebilir miyiz?', hookEn: 'If an intermediate low breaks, can we say “the market tricked traders”?',
  explanation: 'Inducement bazı yöntemlerde daha büyük yapı veya likidite alanı öncesindeki dikkat çekici ara seviyeye verilen addır. Bu yalnızca gözlemsel bir etikettir; grafikten bir aktörün insanları kasıtlı olarak kandırdığı sonucu çıkarılamaz.', explanationEn: 'In some frameworks, inducement labels an intermediate structure or liquidity reference that may attract attention before price moves toward a larger target or liquidity area. It is an observational framework; the chart does not prove that an actor intentionally deceived traders.',
  proExplanation: 'Because inducement can be assigned very flexibly, a useful methodology must specify which swing/reference qualifies, its relation to the larger dealing range, and what would falsify the interpretation.', proExplanationEn: 'Because inducement can be assigned very flexibly, a useful methodology must specify which swing/reference qualifies, its relation to the larger dealing range, and what would falsify the interpretation.',
  misconception: 'Her küçük swing kırılımını inducement veya kesin tuzak kanıtı sayma.', misconceptionEn: 'Common mistake: labeling every broken minor swing as inducement and treating it as certain proof of a “smart money trap.”',
  takeaway: 'Inducement bir yöntem etiketidir; niyet veya yön kanıtı değildir.', takeawayEn: 'Inducement can be a methodology label; it is not proof of intent, manipulation, or future direction.',
  prerequisiteConceptKeys: ['smc.methodology', 'market.structure.bos'], relatedConceptKeys: ['smc.liquidity_sweep', 'smc.dealing_range', 'market.structure.liquidity'],
  visualAlt: 'Büyük yapısal hedef öncesinde küçük ara swing seviyesini işaretleyip gözlem ile niyet iddiasını ayıran inducement görseli', visualAltEn: 'Inducement visual marking an intermediate swing before a larger structural reference while separating observation from intent claims',
  taskKind: 'chart_identification', taskAssetRef: 'edu://academy/smc-ict/inducement-001', taskPrompt: 'Inducement yorumunda hangi ifade daha güvenlidir?', taskPromptEn: 'Which statement is safer in an inducement interpretation?',
  taskChoices: [{ id: 'observation', label: 'Ara seviyeyi metodolojiye göre tanımlayıp niyet atfetmemek', labelEn: 'Define the intermediate level by methodology without assigning intent' }, { id: 'manipulation', label: 'Grafiğin manipülasyonu kesin kanıtladığını söylemek', labelEn: 'Say the chart proves manipulation' }, { id: 'every', label: 'Her küçük swing’i inducement saymak', labelEn: 'Call every minor swing inducement' }], taskCorrectIds: ['observation'],
  questions: [
    { prompt: 'Inducement grafikten kasıtlı kandırmayı kanıtlar mı?', promptEn: 'Does inducement prove intentional deception from the chart?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Niyet doğrudan gözlenmez.', explanationEn: 'Intent is not directly observable.' },
    { prompt: 'Inducement tanımı metodolojiye bağlı olabilir mi?', promptEn: 'Can inducement definitions be methodology-dependent?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece hissede', labelEn: 'Only in stocks' }], correctId: 'a', explanation: 'Hangi seviyenin seçildiği çerçeveye göre değişebilir.', explanationEn: 'Which reference qualifies can vary by framework.' },
    { prompt: 'İyi tanımda falsification önemli midir?', promptEn: 'Does a useful definition need falsification criteria?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece algoritmada', labelEn: 'Only in algorithms' }], correctId: 'a', explanation: 'Yorumun ne zaman geçersiz sayılacağı bilinmelidir.', explanationEn: 'You should know what would invalidate the interpretation.' },
  ], sources: [SMC_ICT_SOURCES.methodology, SMC_ICT_SOURCES.structure],
});

const displacement = createFoundationLesson({
  id: 'lesson.smc.displacement.001', slug: 'displacement-nasil-okunur', conceptKey: 'smc.displacement', skillId: 'skill.smc-ict', competencyId: 'competency.displacement.advanced',
  title: 'Displacement sadece büyük mum mudur?', titleEn: 'Is displacement just a large candle?',
  objective: 'Displacementı yalnız büyük mum değil, bağlam içindeki güçlü fiyat hareketi olarak okumayı öğren.', objectiveEn: 'Explain displacement as strong, rapid repricing in context rather than reducing it to candle size alone.', minutes: 5,
  hook: 'Her uzun gövdeli mum displacement sayılırsa haber mumuyla yapısal hareketi nasıl ayıracağız?', hookEn: 'If every large-bodied candle is displacement, how do we distinguish a news spike from a structural repricing move?',
  explanation: 'Displacement genellikle fiyatın hız, gövde genişlemesi ve yönlü ilerlemeyle bir yapıdan güçlü biçimde uzaklaşmasını tarif eder. Büyük mum tek başına yeterli değildir; önceki volatilite, kırılan yapı, devam davranışı ve zaman dilimi de önemlidir.', explanationEn: 'In SMC/ICT language, displacement commonly describes price moving away from an area with notable speed, range expansion, and directional repricing. A large candle alone is not enough; prior volatility, broken structure, follow-through, and timeframe context matter.',
  proExplanation: 'A reproducible definition can normalize candle/range expansion to recent volatility, require structural consequence, and specify follow-through. This reduces hindsight labeling of any visually large bar as displacement.', proExplanationEn: 'A reproducible definition can normalize range expansion to recent volatility, require structural consequence, and specify follow-through. This reduces hindsight labeling of any visually large bar as displacement.',
  misconception: 'Her büyük mumu displacement sayma.', misconceptionEn: 'Common mistake: calling every visually large candle displacement.',
  takeaway: 'Displacementı büyüklük, hız ve bağlamla birlikte değerlendir.', takeawayEn: 'Displacement = magnitude + speed + context + structural consequence; it is not a one-candle label.',
  prerequisiteConceptKeys: ['smc.methodology', 'market.structure.bos', 'risk.volatility'], relatedConceptKeys: ['market.structure.fvg', 'market.technical.momentum', 'smc.market_structure_shift'],
  visualAlt: 'Normal dalgalanma ile yapı kıran ve ardışık yönlü genişleme gösteren displacement hareketini yan yana karşılaştıran grafik', visualAltEn: 'Chart comparing ordinary volatility with displacement that breaks structure and shows directional expansion',
  taskKind: 'chart_identification', taskAssetRef: 'edu://academy/smc-ict/displacement-001', taskPrompt: 'Hangi gözlem displacement yorumunu güçlendirir?', taskPromptEn: 'Which observation strengthens a displacement interpretation?',
  taskChoices: [{ id: 'context', label: 'Yakın dönem volatilitesine göre genişleme ve anlamlı yapısal sonuç', labelEn: 'Expansion relative to recent volatility plus meaningful structural consequence' }, { id: 'size', label: 'Sadece tek mumun uzun görünmesi', labelEn: 'Only that one candle looks long' }, { id: 'color', label: 'Mumun yeşil olması', labelEn: 'The candle is green' }], taskCorrectIds: ['context'],
  questions: [
    { prompt: 'Her büyük mum displacement mıdır?', promptEn: 'Is every large candle displacement?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Bağlam ve yapısal etki gerekir.', explanationEn: 'Context and structural effect matter.' },
    { prompt: 'Yakın dönem volatilitesi önemli midir?', promptEn: 'Does recent volatility matter?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece aylıkta', labelEn: 'Only monthly' }], correctId: 'a', explanation: 'Büyüklük görecelidir.', explanationEn: 'Magnitude is relative.' },
    { prompt: 'Displacement tek başına giriş sinyali midir?', promptEn: 'Is displacement a standalone entry signal?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız yükselişte', labelEn: 'Only bullish' }], correctId: 'a', explanation: 'Bağlam, risk ve devam kanıtı gerekir.', explanationEn: 'Context, risk, and follow-through still matter.' },
  ], sources: [SMC_ICT_SOURCES.structure],
});

const fvg = createFoundationLesson({
  id: 'lesson.smc.fvg-context.001', slug: 'fvg-smc-baglaminda-nasil-okunur', conceptKey: 'market.structure.fvg', skillId: 'skill.smc-ict', competencyId: 'competency.fvg-context.advanced',
  title: 'FVG SMC bağlamında nasıl okunur?', titleEn: 'How is an FVG read in SMC context?',
  objective: 'FVG etiketinin hangi alanı tarif ettiğini ve neden geri dönüş garantisi olmadığını öğren.', objectiveEn: 'Explain an FVG as an imbalance area between consecutive candles during rapid repricing and distinguish it from a guaranteed-fill claim.', minutes: 5,
  hook: 'Grafikte bir FVG varsa fiyat oraya mutlaka geri dönmek zorunda mıdır?', hookEn: 'If an FVG exists on a chart, must price always return to fill it?',
  explanation: 'FVG çoğunlukla üç mumlu dizide ilk ve üçüncü mumun fitilleri arasında fiyatın sınırlı işlem gördüğü alanı tarif eder. Bu hızlı yeniden fiyatlamanın görsel izi olabilir; fiyatın mutlaka geri döneceği veya tepki vereceği anlamına gelmez.', explanationEn: 'In common SMC/ICT usage, a Fair Value Gap (FVG) often labels an area between the wicks of the first and third candles in a three-candle sequence where price traded sparsely. It can visualize rapid repricing, but it does not mean price must return or react there.',
  proExplanation: 'Definitions vary around wick/body treatment, minimum gap size, partial fills, consequent encroachment, and timeframe relevance. A useful rule should define these before evaluation and relate the FVG to displacement and structure.', proExplanationEn: 'Definitions vary around wick/body treatment, minimum gap size, partial fills, consequent encroachment, and timeframe relevance. A useful rule should define these before evaluation and relate the FVG to displacement and structure.',
  misconception: 'Her küçük üç mum boşluğunu önemli FVG sayma veya “hepsi dolar” kuralı kullanma.', misconceptionEn: 'Common mistake: treating every tiny three-candle gap as important or assuming all FVGs must fill.',
  takeaway: 'FVG bir alan etiketidir; dönüş veya tepki garantisi değildir.', takeawayEn: 'An FVG is an area label for rapid repricing, not a guarantee of return or reaction.',
  prerequisiteConceptKeys: ['smc.displacement'], relatedConceptKeys: ['market.structure.order_block', 'smc.mitigation', 'market.structure.bos'],
  visualAlt: 'Üç mum arasında ilk ve üçüncü mum fitilleriyle sınırlandırılmış FVG alanını ve fiyatın geri dönmeden devam edebileceğini gösteren grafik', visualAltEn: 'Chart marking an FVG between first- and third-candle wicks while showing that price may continue without returning',
  taskKind: 'chart_identification', taskAssetRef: 'edu://academy/smc-ict/fvg-context-001', taskPrompt: 'FVG hakkında hangi ifade daha doğrudur?', taskPromptEn: 'Which statement about an FVG is more accurate?',
  taskChoices: [{ id: 'area', label: 'Hızlı fiyatlamayı işaretleyen metodolojiye bağlı bir alan; dolması garanti değil', labelEn: 'A methodology-dependent area marking rapid repricing; a fill is not guaranteed' }, { id: 'mustfill', label: 'Fiyat mutlaka geri dönüp tamamen doldurur', labelEn: 'Price must always return and fully fill it' }, { id: 'signal', label: 'Tek başına al/sat sinyalidir', labelEn: 'It is a standalone buy/sell signal' }], taskCorrectIds: ['area'],
  questions: [
    { prompt: 'FVG her zaman dolar mı?', promptEn: 'Does every FVG always fill?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Aynı gün', labelEn: 'On the same day' }], correctId: 'a', explanation: 'Geri dönüş garanti değildir.', explanationEn: 'A return is not guaranteed.' },
    { prompt: 'FVG tanımı yöntemlere göre değişebilir mi?', promptEn: 'Can FVG definitions vary by methodology?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece kriptoda', labelEn: 'Only in crypto' }], correctId: 'a', explanation: 'Wick/body ve minimum boyut kriterleri değişebilir.', explanationEn: 'Wick/body and minimum-size criteria can vary.' },
    { prompt: 'FVG yorumunda displacement bağlamı yararlı mıdır?', promptEn: 'Is displacement context useful when reading an FVG?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'İlgisizdir', labelEn: 'It is unrelated' }], correctId: 'a', explanation: 'FVG hızlı yeniden fiyatlamayla birlikte daha anlamlı değerlendirilir.', explanationEn: 'An FVG is more meaningful when related to rapid repricing context.' },
  ], sources: [SMC_ICT_SOURCES.methodology, SMC_ICT_SOURCES.structure],
});

export const SMC_ICT_FOUNDATION_LESSONS = [methodology, sweep, grab, inducement, displacement, fvg] as const;
