import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { SMC_ICT_SOURCES } from './smcIctSources';

const orderBlock = createFoundationLesson({
  id: 'lesson.smc.order-block-context.001', slug: 'order-block-smc-baglaminda-nasil-tanimlanir', conceptKey: 'market.structure.order_block', skillId: 'skill.smc-ict', competencyId: 'competency.order-block-context.advanced',
  title: 'Order Block SMC bağlamında nasıl tanımlanır?', titleEn: 'How is an Order Block defined in SMC context?',
  objective: 'Order Block etiketinin yönteme bağlı kriterler gerektirdiğini ve her son ters renkli mumun otomatik Order Block olmadığını açıklar.', objectiveEn: 'Explain that an Order Block requires methodology-specific criteria and that not every last opposite-colored candle automatically qualifies.', minutes: 5,
  hook: 'Yükselişten önceki son kırmızı mumu işaretlemek tek başına Order Block tanımı için yeterli midir?', hookEn: 'Is marking the last red candle before a rally enough to define an Order Block?',
  explanation: 'SMC/ICT anlatımlarında Order Block çoğunlukla anlamlı bir yönlü hareket, displacement veya yapı değişimi öncesindeki belirli fiyat alanına verilen etikettir. Ancak hangi mumun veya aralığın seçileceği yönteme göre değişir. Sadece “son ters mum” kuralı bağlam olmadan çok fazla alan üretir.', explanationEn: 'In SMC/ICT frameworks, an Order Block commonly labels a particular price area preceding meaningful directional movement, displacement, or structural change. Which candle or range qualifies varies by methodology. A simple “last opposite candle” rule creates too many areas without context.',
  proExplanation: 'Operational definitions can specify displacement, structural consequence, candle range selection, body/wick treatment, invalidation, freshness, and whether later interaction changes the zone state. These criteria should be fixed before reviewing outcomes.', proExplanationEn: 'Operational definitions can specify displacement, structural consequence, candle range selection, body/wick treatment, invalidation, freshness, and whether later interaction changes zone state. These criteria should be fixed before reviewing outcomes.',
  misconception: 'Yaygın hata: Her güçlü hareketin öncesindeki son ters renkli mumu otomatik Order Block saymak.', misconceptionEn: 'Common mistake: automatically calling the last opposite-colored candle before every strong move an Order Block.',
  takeaway: 'Order Block etiketi bağlam ve açık kriter ister; alanın tepki vermesi garanti değildir.', takeawayEn: 'An Order Block label requires context and explicit criteria; a reaction is not guaranteed.',
  prerequisiteConceptKeys: ['smc.displacement', 'market.structure.fvg'], relatedConceptKeys: ['smc.mitigation', 'market.structure.bos', 'smc.methodology'],
  visualAlt: 'Güçlü displacement öncesindeki aday mum alanı ile bağlamsız son ters mumları karşılaştıran Order Block görseli', visualAltEn: 'Order Block visual comparing a candidate candle area before displacement with context-free last-opposite candles',
  taskKind: 'chart_identification', taskAssetRef: 'edu://academy/smc-ict/order-block-context-001', taskPrompt: 'Hangi kriter Order Block yorumunu daha güçlü yapar?', taskPromptEn: 'Which criterion makes an Order Block interpretation stronger?',
  taskChoices: [{ id: 'context', label: 'Displacement ve anlamlı yapısal sonuçla ilişkilendirmek', labelEn: 'Relate the area to displacement and meaningful structural consequence' }, { id: 'color', label: 'Sadece mum renginin ters olması', labelEn: 'Only that the candle color is opposite' }, { id: 'every', label: 'Her güçlü hareket öncesi mumu işaretlemek', labelEn: 'Mark every candle before a strong move' }], taskCorrectIds: ['context'],
  questions: [
    { prompt: 'Her son ters mum Order Block mıdır?', promptEn: 'Is every last opposite candle an Order Block?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Bağlam ve yöntem kriterleri gerekir.', explanationEn: 'Context and methodology criteria are required.' },
    { prompt: 'Order Block tanımları yöntemlere göre değişebilir mi?', promptEn: 'Can Order Block definitions vary by methodology?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece forexte', labelEn: 'Only in FX' }], correctId: 'a', explanation: 'Alan ve invalidation kriterleri farklılaşabilir.', explanationEn: 'Zone and invalidation criteria can differ.' },
    { prompt: 'Order Block tepki garantisi verir mi?', promptEn: 'Does an Order Block guarantee a reaction?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'İlk dokunuşta kesin', labelEn: 'Always on first touch' }], correctId: 'a', explanation: 'Bu bir metodoloji alanıdır, garanti değil.', explanationEn: 'It is a methodology-defined area, not a guarantee.' },
  ], sources: [SMC_ICT_SOURCES.methodology, SMC_ICT_SOURCES.structure],
});

const mitigation = createFoundationLesson({
  id: 'lesson.smc.mitigation.001', slug: 'mitigation-ne-anlatir', conceptKey: 'smc.mitigation', skillId: 'skill.smc-ict', competencyId: 'competency.mitigation.advanced',
  title: 'Mitigation ne anlatır?', titleEn: 'What does mitigation describe?',
  objective: 'Mitigationı bazı SMC/ICT yöntemlerinde önceden tanımlanmış bir fiyat alanına sonraki geri dönüş ve etkileşim olarak açıklar; tepki garantisinden ayırır.', objectiveEn: 'Explain mitigation in some SMC/ICT frameworks as a later return and interaction with a previously defined price area, not a guaranteed reaction.', minutes: 5,
  hook: 'Fiyat bir Order Block veya FVG alanına geri döndüğünde neden her temas aynı anlama gelmez?', hookEn: 'When price returns to an Order Block or FVG area, why does every touch not mean the same thing?',
  explanation: 'Mitigation terimi bazı yöntemlerde fiyatın daha önce tanımlanan bir Order Block, imbalance veya benzeri alana geri dönüp o alanla etkileşmesini tarif eder. Alanın nasıl tanımlandığı, daha önce test edilip edilmediği, ne kadarının ihlal edildiği ve sonraki yapı önemlidir. Geri dönüş tek başına tepki garantisi değildir.', explanationEn: 'In some frameworks, mitigation describes price returning to and interacting with a previously identified Order Block, imbalance, or similar area. The zone definition, prior tests, degree of violation, and subsequent structure matter. A revisit alone does not guarantee a reaction.',
  proExplanation: 'Methodologies vary on freshness, partial mitigation, full mitigation, invalidation, and whether a revisit changes the state of the zone. These rules should be explicit to avoid retroactive relabeling.', proExplanationEn: 'Methodologies vary on freshness, partial mitigation, full mitigation, invalidation, and whether a revisit changes zone state. These rules should be explicit to avoid retroactive relabeling.',
  misconception: 'Yaygın hata: Fiyat işaretli alana dokunduğu anda “mitigated, şimdi kesin döner” sonucuna atlamak.', misconceptionEn: 'Common mistake: assuming that once price touches a marked area it is “mitigated” and must reverse.',
  takeaway: 'Mitigation bir alan etkileşimi etiketidir; sonraki fiyat davranışı ayrıca doğrulanır.', takeawayEn: 'Mitigation labels an interaction with an area; subsequent price behavior still requires evaluation.',
  prerequisiteConceptKeys: ['market.structure.order_block'], relatedConceptKeys: ['market.structure.fvg', 'smc.displacement', 'smc.market_structure_shift'],
  visualAlt: 'Fiyatın işaretli alana ilk dönüşünü, kısmi teması ve alanın ihlal edilmesini üç ayrı senaryo olarak gösteren mitigation görseli', visualAltEn: 'Mitigation visual comparing a first revisit, partial interaction, and zone violation as separate scenarios',
  taskKind: 'chart_identification', taskAssetRef: 'edu://academy/smc-ict/mitigation-001', taskPrompt: 'Mitigation sonrası hangi yaklaşım daha doğrudur?', taskPromptEn: 'Which approach is more appropriate after a mitigation interaction?',
  taskChoices: [{ id: 'observe', label: 'Sonraki yapı ve fiyat davranışını ayrıca gözlemek', labelEn: 'Evaluate subsequent structure and price behavior separately' }, { id: 'guarantee', label: 'Temas olduğu için dönüşü kesin kabul etmek', labelEn: 'Assume reversal is certain because a touch occurred' }, { id: 'ignore', label: 'Alan invalidationını önemsememek', labelEn: 'Ignore zone invalidation' }], taskCorrectIds: ['observe'],
  questions: [
    { prompt: 'Mitigation temas sonrası dönüş garantisi midir?', promptEn: 'Does mitigation guarantee reversal after a touch?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'İlk temas her zaman', labelEn: 'Always on first touch' }], correctId: 'a', explanation: 'Sonraki davranış ayrıca değerlendirilir.', explanationEn: 'Subsequent behavior must still be evaluated.' },
    { prompt: 'Freshness tanımı yöntemlere göre değişebilir mi?', promptEn: 'Can freshness rules vary by methodology?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece hissede', labelEn: 'Only in stocks' }], correctId: 'a', explanation: 'Alan durum kuralları çerçeveye bağlı olabilir.', explanationEn: 'Zone-state rules can depend on the framework.' },
    { prompt: 'Invalidation önemli midir?', promptEn: 'Does invalidation matter?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece trendde', labelEn: 'Only in trends' }], correctId: 'a', explanation: 'Alan fikrinin ne zaman geçersiz olduğu tanımlanmalıdır.', explanationEn: 'The point at which the zone idea fails should be defined.' },
  ], sources: [SMC_ICT_SOURCES.methodology, SMC_ICT_SOURCES.structure],
});

const dealingRange = createFoundationLesson({
  id: 'lesson.smc.dealing-range.001', slug: 'dealing-range-ve-equilibrium', conceptKey: 'smc.dealing_range', skillId: 'skill.smc-ict', competencyId: 'competency.dealing-range.advanced',
  title: 'Dealing range ve equilibrium nasıl tanımlanır?', titleEn: 'How are a dealing range and equilibrium defined?',
  objective: 'Dealing range’i seçilmiş anlamlı low-high referansı ve equilibrium’u bu aralığın göreli orta noktası olarak açıklar; range seçiminin yorumu değiştirdiğini gösterir.', objectiveEn: 'Explain a dealing range as a selected meaningful low-high reference and equilibrium as its relative midpoint, showing how range selection changes interpretation.', minutes: 5,
  hook: 'Aynı fiyat neden bir grafikte “premium”, başka bir range seçince “discount” olabilir?', hookEn: 'How can the same price appear “premium” under one range and “discount” under another?',
  explanation: 'SMC/ICT kullanımında dealing range, analistin referans aldığı anlamlı bir low ile high arasındaki çalışma aralığıdır. Equilibrium genellikle bu aralığın yaklaşık orta noktasını ifade eder. Ancak hangi low-high çiftinin seçildiği yorumu doğrudan değiştirir; bu yüzden range seçim kuralı açık olmalıdır.', explanationEn: 'In SMC/ICT usage, a dealing range is the working interval between a meaningful reference low and high selected by the analyst. Equilibrium commonly refers to the approximate midpoint of that interval. Because the chosen low-high pair directly changes the interpretation, the range-selection rule must be explicit.',
  proExplanation: 'Range hierarchy can differ across timeframes. Internal ranges may coexist within broader external ranges, so premium/discount labels are only meaningful relative to a declared range and timeframe.', proExplanationEn: 'Range hierarchy can differ across timeframes. Internal ranges can exist within broader external ranges, so premium/discount labels are meaningful only relative to a declared range and timeframe.',
  misconception: 'Yaygın hata: Range’i sonuç belli olduktan sonra değiştirerek fiyatı istenen premium/discount tarafına taşımak.', misconceptionEn: 'Common mistake: changing the range after seeing the outcome to place price on the desired premium/discount side.',
  takeaway: 'Premium/discount yorumundan önce hangi range ve zaman dilimini kullandığını sabitle.', takeawayEn: 'Before using premium/discount, fix the range and timeframe you are referencing.',
  prerequisiteConceptKeys: ['smc.methodology', 'market.structure.bos'], relatedConceptKeys: ['smc.premium_discount', 'market.timeframe.alignment', 'smc.inducement'],
  visualAlt: 'Seçilmiş swing low ve swing high arasında dealing range, yüzde 50 equilibrium ve iç/dış range farkını gösteren görsel', visualAltEn: 'Visual showing a dealing range between selected swing low/high, 50% equilibrium, and internal versus external ranges',
  taskKind: 'chart_identification', taskAssetRef: 'edu://academy/smc-ict/dealing-range-001', taskPrompt: 'Premium/discount kullanmadan önce ne sabitlenmelidir?', taskPromptEn: 'What should be fixed before using premium/discount?',
  taskChoices: [{ id: 'range', label: 'Referans low-high range’i ve zaman dilimi', labelEn: 'The reference low-high range and timeframe' }, { id: 'outcome', label: 'Sonraki fiyat sonucu', labelEn: 'The later price outcome' }, { id: 'label', label: 'Sadece “premium” kelimesi', labelEn: 'Only the word “premium”' }], taskCorrectIds: ['range'],
  questions: [
    { prompt: 'Equilibrium genellikle neyi ifade eder?', promptEn: 'What does equilibrium commonly represent?', choices: [{ id: 'a', label: 'Seçilen range’in yaklaşık orta noktasını', labelEn: 'The approximate midpoint of the selected range' }, { id: 'b', label: 'Kesin piyasa değeri', labelEn: 'Exact market value' }, { id: 'c', label: 'Gelecek hedefi', labelEn: 'A future target' }], correctId: 'a', explanation: 'Bu göreli bir range referansıdır.', explanationEn: 'It is a relative range reference.' },
    { prompt: 'Range seçimi premium/discount sonucunu değiştirebilir mi?', promptEn: 'Can range selection change a premium/discount label?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece forexte', labelEn: 'Only in FX' }], correctId: 'a', explanation: 'Etiket seçilen referansa göredir.', explanationEn: 'The label is relative to the chosen reference.' },
    { prompt: 'Dealing range evrensel tek aralık mıdır?', promptEn: 'Is there one universal dealing range?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her grafikte bir tane', labelEn: 'One per chart' }], correctId: 'a', explanation: 'Zaman dilimi ve yapı hiyerarşisi farklı range’ler üretebilir.', explanationEn: 'Timeframe and structural hierarchy can produce different ranges.' },
  ], sources: [SMC_ICT_SOURCES.methodology, SMC_ICT_SOURCES.structure],
});

const premiumDiscount = createFoundationLesson({
  id: 'lesson.smc.premium-discount.001', slug: 'premium-discount-ne-anlatir', conceptKey: 'smc.premium_discount', skillId: 'skill.smc-ict', competencyId: 'competency.premium-discount.advanced',
  title: 'Premium ve discount “pahalı/ucuz” demek midir?', titleEn: 'Do premium and discount mean fundamentally expensive or cheap?',
  objective: 'Premium/discount etiketlerini seçilmiş dealing range içindeki göreli konum olarak açıklar; temel değerleme anlamından ayırır.', objectiveEn: 'Explain premium/discount as relative location within a selected dealing range and distinguish it from fundamental valuation.', minutes: 5,
  hook: 'Fiyat range’in üst yarısındaysa şirket veya varlık gerçekten “pahalı” mı olur?', hookEn: 'If price is in the upper half of a range, is the company or asset fundamentally “expensive”?',
  explanation: 'SMC/ICT dilinde premium çoğunlukla seçilmiş dealing range’in equilibrium üstündeki, discount ise altındaki göreli konumu anlatır. Bu ifadeler temel analizdeki içsel değer veya gerçek ucuz/pahalı değerlendirmesi değildir. Yalnız referans alınan fiyat aralığına göre konumu açıklar.', explanationEn: 'In SMC/ICT language, premium commonly describes location above equilibrium in a selected dealing range, while discount describes location below it. These are not statements of intrinsic value or fundamental cheapness/expensiveness; they describe relative position inside a chosen price range.',
  proExplanation: 'Premium/discount becomes unstable if the range definition changes frequently. It should be paired with a declared structural hierarchy and should not substitute for risk, timing, or independent evidence.', proExplanationEn: 'Premium/discount becomes unstable if the range definition changes frequently. It should be paired with a declared structural hierarchy and should not substitute for risk, timing, or independent evidence.',
  misconception: 'Yaygın hata: Discount bölgesini otomatik “alım ucuzluğu”, premium bölgesini otomatik “satış pahalılığı” saymak.', misconceptionEn: 'Common mistake: treating discount as automatic buying cheapness and premium as automatic selling expensiveness.',
  takeaway: 'Premium/discount göreli range konumudur; değerleme veya işlem emri değildir.', takeawayEn: 'Premium/discount is relative range location, not valuation or a trade instruction.',
  prerequisiteConceptKeys: ['smc.dealing_range'], relatedConceptKeys: ['fundamental.valuation_multiples', 'smc.confluence_limits', 'risk.position_sizing'],
  visualAlt: 'Dealing range’in üst yarısını premium, alt yarısını discount ve ortasını equilibrium olarak gösteren ancak al/sat oku içermeyen görsel', visualAltEn: 'Visual showing premium upper half, discount lower half, and equilibrium midpoint without buy/sell arrows',
  taskKind: 'chart_identification', taskAssetRef: 'edu://academy/smc-ict/premium-discount-001', taskPrompt: 'SMC bağlamında “discount” neyi anlatır?', taskPromptEn: 'What does “discount” describe in SMC context?',
  taskChoices: [{ id: 'relative', label: 'Seçilen range’in equilibrium altındaki göreli fiyat konumunu', labelEn: 'Relative price location below equilibrium in the selected range' }, { id: 'value', label: 'Varlığın kesin olarak temel değerinin altında olduğunu', labelEn: 'That the asset is certainly below intrinsic value' }, { id: 'buy', label: 'Otomatik al sinyalini', labelEn: 'An automatic buy signal' }], taskCorrectIds: ['relative'],
  questions: [
    { prompt: 'SMC premium/discount temel değerleme midir?', promptEn: 'Is SMC premium/discount fundamental valuation?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Bu göreli fiyat konumudur.', explanationEn: 'It is relative price location.' },
    { prompt: 'Discount otomatik al sinyali midir?', promptEn: 'Is discount an automatic buy signal?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece trendde', labelEn: 'Only in trends' }], correctId: 'a', explanation: 'Bağlam ve risk gerekir.', explanationEn: 'Context and risk are still required.' },
    { prompt: 'Etiket hangi referansa bağlıdır?', promptEn: 'What is the label relative to?', choices: [{ id: 'a', label: 'Seçilmiş dealing range’e', labelEn: 'The selected dealing range' }, { id: 'b', label: 'Şirket bilançosuna', labelEn: 'The company balance sheet' }, { id: 'c', label: 'Tek bir indikatöre', labelEn: 'One indicator' }], correctId: 'a', explanation: 'Premium/discount range içi göreli konumdur.', explanationEn: 'Premium/discount is relative position within a range.' },
  ], sources: [SMC_ICT_SOURCES.methodology],
});

const mss = createFoundationLesson({
  id: 'lesson.smc.mss.001', slug: 'mss-choch-ile-ayni-mi', conceptKey: 'smc.market_structure_shift', skillId: 'skill.smc-ict', competencyId: 'competency.mss.advanced',
  title: 'MSS ile CHoCH aynı şey midir?', titleEn: 'Are MSS and CHoCH the same thing?',
  objective: 'Market Structure Shift teriminin bazı yöntemlerde CHoCH ile örtüşebildiğini, bazı yöntemlerde displacement veya ek teyit istediğini açıklar.', objectiveEn: 'Explain that Market Structure Shift can overlap with CHoCH in some frameworks while others require displacement or additional confirmation.', minutes: 5,
  hook: 'Aynı yapı kırılımına bir eğitimci CHoCH, diğeri MSS diyorsa hangisi yanlış?', hookEn: 'If one educator calls the same structural break CHoCH and another calls it MSS, which one is wrong?',
  explanation: 'MSS (Market Structure Shift) SMC/ICT terminolojisinde mevcut yapının farklı bir yöne kaymaya başladığını anlatmak için kullanılabilir. Bazı yöntemlerde CHoCH ile çok benzer kullanılır; bazıları MSS için displacement, belirli swing kırılımı veya ek teyit ister. FINM8 bu terimleri evrensel eş anlamlı veya kesin trend dönüşü olarak sunmaz.', explanationEn: 'MSS (Market Structure Shift) can be used in SMC/ICT terminology to describe structure beginning to shift in another direction. Some frameworks use it similarly to CHoCH, while others require displacement, a particular swing break, or added confirmation. FINM8 does not present these terms as universally synonymous or as proof of a trend reversal.',
  proExplanation: 'A robust implementation should define the reference swing, close/wick criteria, required displacement, timeframe hierarchy, and continuation evidence. Without those, MSS risks becoming another hindsight label.', proExplanationEn: 'A robust implementation should define the reference swing, close/wick criteria, required displacement, timeframe hierarchy, and continuation evidence. Without those, MSS risks becoming another hindsight label.',
  misconception: 'Yaygın hata: İlk iç yapı kırılımını kesin MSS ve kesin trend dönüşü saymak.', misconceptionEn: 'Common mistake: treating the first internal structural break as a certain MSS and confirmed trend reversal.',
  takeaway: 'MSS tanımı yönteme bağlıdır; önce kriter, sonra etiket, sonra devam kanıtı.', takeawayEn: 'MSS is methodology-dependent: criteria first, label second, continuation evidence after.',
  prerequisiteConceptKeys: ['market.structure.choch', 'smc.displacement'], relatedConceptKeys: ['market.structure.bos', 'market.timeframe.alignment', 'smc.confluence_limits'],
  visualAlt: 'Aynı yapı değişiminde CHoCH ve MSS etiketlerinin farklı metodoloji kriterleriyle kullanılabileceğini gösteren karşılaştırmalı grafik', visualAltEn: 'Comparison chart showing CHoCH and MSS labels applied with different methodology criteria to the same structural change',
  taskKind: 'chart_identification', taskAssetRef: 'edu://academy/smc-ict/mss-001', taskPrompt: 'MSS kullanırken en önemli ilk adım nedir?', taskPromptEn: 'What is the most important first step when using MSS?',
  taskChoices: [{ id: 'define', label: 'Kullandığın MSS kriterlerini açıkça tanımlamak', labelEn: 'Explicitly define the MSS criteria you use' }, { id: 'certainty', label: 'İlk kırılımı kesin trend dönüşü saymak', labelEn: 'Treat the first break as a certain reversal' }, { id: 'rename', label: 'Her CHoCH’u otomatik MSS olarak yeniden adlandırmak', labelEn: 'Automatically rename every CHoCH as MSS' }], taskCorrectIds: ['define'],
  questions: [
    { prompt: 'MSS ve CHoCH tüm yöntemlerde aynı mı?', promptEn: 'Are MSS and CHoCH identical in all methodologies?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her grafikte', labelEn: 'On every chart' }], correctId: 'a', explanation: 'Kriterler kaynağa göre değişebilir.', explanationEn: 'Criteria can vary by source.' },
    { prompt: 'MSS kesin trend dönüşü müdür?', promptEn: 'Does MSS guarantee a trend reversal?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'İlk mumda', labelEn: 'On the first candle' }], correctId: 'a', explanation: 'Devam kanıtı ve daha geniş yapı önemlidir.', explanationEn: 'Follow-through and broader structure still matter.' },
    { prompt: 'Zaman dilimi hiyerarşisi önemli midir?', promptEn: 'Does timeframe hierarchy matter?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece scalpingde', labelEn: 'Only in scalping' }], correctId: 'a', explanation: 'İç yapı değişirken geniş yapı korunabilir.', explanationEn: 'Internal structure can change while broader structure remains intact.' },
  ], sources: [SMC_ICT_SOURCES.methodology, SMC_ICT_SOURCES.structure],
});

const confluenceLimits = createFoundationLesson({
  id: 'lesson.smc.confluence-limits.001', slug: 'smc-confluence-nasil-kullanilmali', conceptKey: 'smc.confluence_limits', skillId: 'skill.smc-ict', competencyId: 'competency.smc-confluence.advanced',
  title: 'SMC confluence: beş etiket gerçekten beş ayrı kanıt mı?', titleEn: 'SMC confluence: are five labels really five independent pieces of evidence?',
  objective: 'Aynı fiyat hareketinden türetilen SMC etiketlerini bağımsız kanıt gibi üst üste saymanın sahte güven yaratabileceğini açıklar.', objectiveEn: 'Explain how stacking SMC labels derived from the same price move can create false confidence when treated as independent evidence.', minutes: 5,
  hook: 'Sweep + displacement + FVG + Order Block + MSS aynı hareketten çıkıyorsa gerçekten beş bağımsız doğrulama mı var?', hookEn: 'If sweep + displacement + FVG + Order Block + MSS all come from the same move, are there really five independent confirmations?',
  explanation: 'Confluence, farklı kanıtların birlikte değerlendirilmesi demektir; fakat aynı fiyat hareketinden türeyen beş etiket beş bağımsız bilgi kaynağı değildir. SMC/ICT etiketleri birbirine nedensel veya yapısal olarak bağlı olabilir. Bu nedenle etiket sayısını güven puanına çevirmek yerine zaman dilimi, yapı, likidite, risk ve mümkünse bağımsız veri kaynaklarını ayırmak gerekir.', explanationEn: 'Confluence means evaluating multiple evidence sources together, but five labels derived from the same price move are not five independent information sources. SMC/ICT labels can be structurally related. Instead of converting label count into confidence, separate timeframe, structure, liquidity, risk, and—where available—independent evidence.',
  proExplanation: 'Correlated features create double-counting risk in both discretionary and systematic frameworks. Evidence should be grouped by source and mechanism, and invalidation should remain explicit even when several labels align.', proExplanationEn: 'Correlated features create double-counting risk in both discretionary and systematic frameworks. Evidence should be grouped by source and mechanism, and invalidation should remain explicit even when several labels align.',
  misconception: 'Yaygın hata: Aynı mum dizisinden çıkan her etiketi ayrı teyit sayıp güveni yapay biçimde yükseltmek.', misconceptionEn: 'Common mistake: counting each label from the same candle sequence as separate confirmation and artificially increasing confidence.',
  takeaway: 'Etiket sayma; kanıt kaynaklarını ve bağımsızlığını ayır, invalidationı koru.', takeawayEn: 'Do not count labels; separate evidence sources and independence, and preserve invalidation.',
  prerequisiteConceptKeys: ['smc.market_structure_shift', 'market.structure.order_block', 'smc.premium_discount'], relatedConceptKeys: ['market.technical.confluence', 'risk.position_sizing', 'quant.overfitting'],
  visualAlt: 'Aynı fiyat hareketinden çıkan beş SMC etiketini tek ortak kaynak kutusuna bağlayıp bağımsız risk/veri kaynaklarını ayrı gösteren confluence diyagramı', visualAltEn: 'Confluence diagram connecting five SMC labels to one shared price source while showing independent risk/data sources separately',
  taskKind: 'chart_identification', taskAssetRef: 'edu://academy/smc-ict/confluence-limits-001', taskPrompt: 'Hangi yaklaşım confluence’ı daha doğru kullanır?', taskPromptEn: 'Which approach uses confluence more appropriately?',
  taskChoices: [{ id: 'sources', label: 'Etiketlerin hangi ortak veya bağımsız kanıttan geldiğini ayırmak', labelEn: 'Separate which labels come from shared versus independent evidence' }, { id: 'count', label: 'Etiket sayısı arttıkça kesinlik yüzdesini artırmak', labelEn: 'Increase certainty as the number of labels rises' }, { id: 'ignore', label: 'Invalidationı görmezden gelmek', labelEn: 'Ignore invalidation' }], taskCorrectIds: ['sources'],
  questions: [
    { prompt: 'Aynı hareketten çıkan beş etiket beş bağımsız kanıt mıdır?', promptEn: 'Are five labels from the same move five independent pieces of evidence?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Aynı veri kaynağı tekrar sayılıyor olabilir.', explanationEn: 'The same data source may be counted repeatedly.' },
    { prompt: 'Confluence invalidation ihtiyacını kaldırır mı?', promptEn: 'Does confluence remove the need for invalidation?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Üç etiketten sonra', labelEn: 'After three labels' }], correctId: 'a', explanation: 'Risk sınırı her zaman açık kalmalıdır.', explanationEn: 'Risk boundaries should remain explicit.' },
    { prompt: 'Bağımsız kanıt neden önemlidir?', promptEn: 'Why does independent evidence matter?', choices: [{ id: 'a', label: 'Aynı bilgiyi tekrar sayma riskini azaltır', labelEn: 'It reduces the risk of double-counting the same information' }, { id: 'b', label: 'Garanti oluşturur', labelEn: 'It creates certainty' }, { id: 'c', label: 'Mum rengini değiştirir', labelEn: 'It changes candle color' }], correctId: 'a', explanation: 'Kaynak bağımsızlığı sahte confluence’ı azaltır.', explanationEn: 'Source independence reduces false confluence.' },
  ], sources: [SMC_ICT_SOURCES.methodology, SMC_ICT_SOURCES.structure],
});

export const SMC_ICT_EXPANSION_LESSONS = [orderBlock, mitigation, dealingRange, premiumDiscount, mss, confluenceLimits] as const;
