import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { STRATEGY_SOURCES } from './strategySources';

const hypothesis = createFoundationLesson({
  id: 'lesson.strategy.hypothesis.001', slug: 'strateji-hipotezi-nedir', conceptKey: 'strategy.hypothesis', skillId: 'skill.strategy-design', competencyId: 'competency.strategy-hypothesis.foundation',
  title: 'Strateji hipotezi nedir?', titleEn: 'What is a strategy hypothesis?',
  objective: 'Bir stratejinin neden çalışabileceğini ve hangi koşullarda bozulacağını önceden tanımlamayı öğren.', objectiveEn: 'State why a method might work, under what conditions it is expected to work, and what would challenge that rationale.', minutes: 5,
  hook: '“Bu formasyon güzel görünüyor” ile “bu yöntem neden avantaj üretmeli?” aynı cümle midir?', hookEn: 'Is “this pattern looks good” the same as “why should this method have an edge”?',
  explanation: 'Strateji hipotezi, yöntemin neden avantaj üretebileceğini test edilebilir biçimde açıklar. “X koşulunda Y davranışı görülebilir çünkü Z mekanizması var” gibi bir iddia kurar. Geçmişte güzel görünen örnekleri sonradan hikâyeye çevirmekten farklıdır.', explanationEn: 'A strategy hypothesis is the testable rationale behind a method. It states a causal claim such as “under condition X, behavior Y may occur because mechanism Z exists.” This is different from selecting attractive historical examples.',
  proExplanation: 'Hipotez falsifiable olmalı; yani hangi kanıtın onu zayıflatacağı tanımlanabilmelidir. Narrative fit tek başına ekonomik veya davranışsal mekanizma değildir.', proExplanationEn: 'A useful hypothesis should be falsifiable: evidence that would weaken it must be identifiable. Narrative fit alone is not an economic or behavioral mechanism.',
  misconception: 'İyi sonuçtan sonra geriye dönük hikâye yazmayı hipotez sanma.', misconceptionEn: 'Common mistake: writing a story after a good result and calling it a strategy hypothesis.',
  takeaway: 'Önce neden çalışmalı ve ne bozabilir; sonra kural.', takeawayEn: 'Ask why it should work and what can break it before writing rules.',
  prerequisiteConceptKeys: ['evidence.data_quality'], relatedConceptKeys: ['strategy.rules', 'strategy.regime_fit', 'behavior.confirmation_bias'],
  visualAlt: 'Hipotez, destekleyen kanıt, karşı kanıt ve test adımlarını aynı akışta gösteren sade strateji görseli', visualAltEn: 'Simple strategy visual linking hypothesis, supporting evidence, counter-evidence, and testing',
  taskPrompt: 'Hangisi daha iyi strateji hipotezidir?', taskPromptEn: 'Which is a better strategy hypothesis?',
  taskChoices: [{ id: 'testable', label: 'Belirli koşul, mekanizma ve bozulma kriteri olan test edilebilir iddia', labelEn: 'A testable claim with a condition, mechanism, and failure criterion' }, { id: 'story', label: '“Geçmişte iyi görünüyordu.”', labelEn: '“It looked good in the past.”' }, { id: 'certainty', label: '“Bu yöntem kesin çalışır.”', labelEn: '“This method always works.”' }], taskCorrectIds: ['testable'],
  questions: [
    { prompt: 'Strateji hipotezi ne olmalıdır?', promptEn: 'What should a strategy hypothesis be?', choices: [{ id: 'a', label: 'Test edilebilir ve yanlışlanabilir bir gerekçe', labelEn: 'A testable and falsifiable rationale' }, { id: 'b', label: 'Kesin gelecek tahmini', labelEn: 'A certain future prediction' }, { id: 'c', label: 'Sadece grafik adı', labelEn: 'Only a chart label' }], correctId: 'a', explanation: 'İyi hipotez destek ve karşı kanıtla sınanabilir.', explanationEn: 'A useful hypothesis can be challenged by evidence.' },
    { prompt: 'Geriye dönük hikâye hipotez midir?', promptEn: 'Is a post-hoc story a hypothesis?', choices: [{ id: 'a', label: 'Tek başına değil', labelEn: 'Not by itself' }, { id: 'b', label: 'Her zaman', labelEn: 'Always' }, { id: 'c', label: 'Sadece kâr ettiyse', labelEn: 'Only if profitable' }], correctId: 'a', explanation: 'Hipotez önceden sınanabilir mekanizma gerektirir.', explanationEn: 'A hypothesis requires a mechanism that can be tested in advance.' },
    { prompt: 'Karşı kanıt neden yazılır?', promptEn: 'Why define counter-evidence?', choices: [{ id: 'a', label: 'Hipotezin ne zaman zayıfladığını görebilmek için', labelEn: 'To see when the hypothesis weakens' }, { id: 'b', label: 'Tezi her koşulda savunmak için', labelEn: 'To defend the thesis at all costs' }, { id: 'c', label: 'Riski kaldırmak için', labelEn: 'To eliminate risk' }], correctId: 'a', explanation: 'Yanlışlanabilirlik confirmation bias riskini azaltır.', explanationEn: 'Falsifiability reduces confirmation-bias risk.' },
  ], sources: [STRATEGY_SOURCES.methodology],
});

const rules = createFoundationLesson({
  id: 'lesson.strategy.rules.001', slug: 'giris-cikis-invalidation-kurallari', conceptKey: 'strategy.rules', skillId: 'skill.strategy-design', competencyId: 'competency.strategy-rules.foundation',
  title: 'Giriş, çıkış ve invalidation neden ayrı kurallardır?', titleEn: 'Why are entry, exit, and invalidation separate rules?',
  objective: 'Giriş, geçersizlik ve çıkış kurallarının neden ayrı kararlar olduğunu öğren.', objectiveEn: 'Separate opportunity recognition, entry, invalidation, and exit decisions within a strategy.', minutes: 5,
  hook: 'İyi bir giriş kuralın varsa çıkış kuralına ihtiyacın kalmaz mı?', hookEn: 'If your entry rule is good, do you still need an exit rule?',
  explanation: 'Giriş, ne zaman risk alınacağını söyler. Invalidation, fikrin hangi durumda artık geçerli olmadığını tanımlar. Çıkış ise pozisyonun ne zaman azaltılacağını veya kapatılacağını belirler. Hepsini tek “sinyal” içinde bırakmak karar anında doğaçlamayı artırır.', explanationEn: 'Strategy rules answer different questions: entry defines when risk may be taken, invalidation defines when the idea is no longer valid, and exit defines when exposure is reduced or closed. Collapsing them into one “signal” encourages improvisation.',
  proExplanation: 'Risk stop ile thesis invalidation aynı seviyede olmak zorunda değildir. Time stop, volatility stop, target, trailing exit ve thesis exit farklı amaçlara hizmet eder.', proExplanationEn: 'A risk stop and thesis invalidation do not have to be identical. Time stops, volatility stops, targets, trailing exits, and thesis exits serve different purposes.',
  misconception: 'Girişten sonra çıkış ve invalidation kararını tamamen o anki hisse bırakma.', misconceptionEn: 'Common mistake: leaving exit and invalidation decisions entirely to emotion after entry.',
  takeaway: 'Giriş fırsatı, invalidation fikri, çıkış pozisyonu yönetir.', takeawayEn: 'Entry defines opportunity, invalidation defines the thesis, and exit manages exposure.',
  prerequisiteConceptKeys: ['strategy.hypothesis'], relatedConceptKeys: ['risk.stop_orders', 'behavior.precommitment', 'risk.position_sizing'],
  visualAlt: 'Giriş, risk, invalidation ve çıkış kapılarını sırayla gösteren sade strateji akışı', visualAltEn: 'Simple strategy flow showing entry, risk, invalidation, and exit gates',
  taskPrompt: 'Invalidation kuralı neyi cevaplar?', taskPromptEn: 'What does an invalidation rule answer?',
  taskChoices: [{ id: 'invalid', label: 'Fikrin hangi koşulda artık geçerli olmadığını', labelEn: 'When the thesis is no longer valid' }, { id: 'entry', label: 'Yalnız ilk fiyatı', labelEn: 'Only the entry price' }, { id: 'profit', label: 'Kesin kâr miktarını', labelEn: 'A guaranteed profit amount' }], taskCorrectIds: ['invalid'],
  questions: [
    { prompt: 'Giriş ve çıkış aynı soruyu mu cevaplar?', promptEn: 'Do entry and exit answer the same question?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Giriş risk alma koşulunu, çıkış pozisyon yönetimini tanımlar.', explanationEn: 'Entry defines when to take risk; exit defines exposure management.' },
    { prompt: 'Stop emri ile thesis invalidation aynı şey olmak zorunda mı?', promptEn: 'Must a stop order equal thesis invalidation?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece kriptoda', labelEn: 'Only in crypto' }], correctId: 'a', explanation: 'Operasyonel risk sınırı ile analitik yanlışlanma farklı amaç taşıyabilir.', explanationEn: 'Operational risk boundaries and analytical invalidation can serve different purposes.' },
    { prompt: 'Kuralların önceden yazılması neyi azaltır?', promptEn: 'What can predefined rules reduce?', choices: [{ id: 'a', label: 'Duygusal anda doğaçlamayı', labelEn: 'Improvisation under emotion' }, { id: 'b', label: 'Piyasa belirsizliğini tamamen', labelEn: 'All market uncertainty' }, { id: 'c', label: 'Veri ihtiyacını', labelEn: 'The need for data' }], correctId: 'a', explanation: 'Önceden tanım karar tutarlılığını destekler.', explanationEn: 'Predefinition supports consistency.' },
  ], sources: [STRATEGY_SOURCES.methodology, STRATEGY_SOURCES.risk],
});

const regimeFit = createFoundationLesson({
  id: 'lesson.strategy.regime-fit.001', slug: 'strateji-rejime-uyar-mi', conceptKey: 'strategy.regime_fit', skillId: 'skill.strategy-design', competencyId: 'competency.strategy-regime.foundation',
  title: 'Aynı strateji her piyasa rejiminde çalışmalı mı?', titleEn: 'Should the same strategy work in every market regime?',
  objective: 'Piyasa rejiminin aynı stratejinin performansını nasıl değiştirebildiğini öğren.', objectiveEn: 'Explain how trend, range, volatility, and liquidity regimes can change the behavior of the same strategy.', minutes: 5,
  hook: 'Trend takip sistemi yatay piyasada zorlanıyorsa sistem “bozulmuş” mudur?', hookEn: 'If a trend system struggles in a range, is the system necessarily “broken”?',
  explanation: 'Strateji performansı piyasa rejimine bağlı olabilir. Trend takibi yönlü piyasalarda, mean reversion ise bazı yatay koşullarda daha uygun davranabilir. Ama “yanlış rejimdi” açıklaması sonuçtan sonra uydurulan bahaneye dönüşmemelidir; rejim ölçütü önceden tanımlanmalıdır.', explanationEn: 'Strategy behavior can depend on market regime. Trend following may fit persistent directional markets, while mean reversion can be more compatible with some balanced regimes. But regime labels should not become post-hoc excuses; criteria need definition.',
  proExplanation: 'Regime features may include volatility level, autocorrelation, dispersion, liquidity, macro state, and trend strength. Regime detection itself is noisy and lagged, so hard switching can create additional errors.', proExplanationEn: 'Regime features can include volatility, autocorrelation, dispersion, liquidity, macro state, and trend strength. Regime detection is itself noisy and lagged, so hard switching adds risk.',
  misconception: 'Her kötü dönemi sonradan “yanlış rejimdi” diye açıklama.', misconceptionEn: 'Common mistake: explaining every bad period afterward as “the wrong regime.”',
  takeaway: 'Rejim uyumu önceden tanımlanır; sonuçtan sonra uydurulmaz.', takeawayEn: 'Strategy-regime fit should be measured, not invented after the outcome.',
  prerequisiteConceptKeys: ['strategy.trend_following', 'strategy.mean_reversion'], relatedConceptKeys: ['risk.volatility', 'market.structure.liquidity', 'strategy.review_discipline'],
  visualAlt: 'Aynı stratejinin trend ve range rejimlerinde farklı sonuç profilleri üretebildiğini gösteren iki panel', visualAltEn: 'Two panels showing the same strategy behaving differently in trend and range regimes',
  taskPrompt: 'Rejim analizinde en büyük hata hangisidir?', taskPromptEn: 'What is a major regime-analysis mistake?',
  taskChoices: [{ id: 'posthoc', label: 'Rejimi yalnız sonuç kötü olunca geriye dönük tanımlamak', labelEn: 'Defining the regime only after results are bad' }, { id: 'criteria', label: 'Ölçütleri önceden tanımlamak', labelEn: 'Define criteria in advance' }, { id: 'noise', label: 'Rejim ölçümünün gürültülü olabileceğini kabul etmek', labelEn: 'Accept that regime detection can be noisy' }], taskCorrectIds: ['posthoc'],
  questions: [
    { prompt: 'Strateji performansı rejime bağlı olabilir mi?', promptEn: 'Can strategy behavior depend on regime?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece tatillerde', labelEn: 'Only on holidays' }], correctId: 'a', explanation: 'Piyasa yapısı yöntemin avantaj ve risk profilini değiştirebilir.', explanationEn: 'Market structure can change a method’s opportunity and risk profile.' },
    { prompt: 'Rejim etiketi ne zaman tanımlanmalı?', promptEn: 'When should regime criteria be defined?', choices: [{ id: 'a', label: 'Mümkün olduğunca önceden ve ölçülebilir şekilde', labelEn: 'In advance and measurably where possible' }, { id: 'b', label: 'Yalnız kayıptan sonra', labelEn: 'Only after a loss' }, { id: 'c', label: 'Hiç tanımlanmamalı', labelEn: 'Never' }], correctId: 'a', explanation: 'Önceden tanım post-hoc açıklama riskini azaltır.', explanationEn: 'Predefinition reduces post-hoc explanations.' },
    { prompt: 'Rejim tespiti kusursuz mudur?', promptEn: 'Is regime detection perfect?', choices: [{ id: 'a', label: 'Hayır; gürültü ve gecikme taşır', labelEn: 'No; it contains noise and lag' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman kesin', labelEn: 'Always certain' }], correctId: 'a', explanation: 'Rejimin kendisi de belirsiz bir tahmindir.', explanationEn: 'The regime label is itself an uncertain estimate.' },
  ], sources: [STRATEGY_SOURCES.methodology, STRATEGY_SOURCES.risk],
});

const costsTurnover = createFoundationLesson({
  id: 'lesson.strategy.costs-turnover.001', slug: 'turnover-ve-maliyet', conceptKey: 'strategy.costs_turnover', skillId: 'skill.strategy-design', competencyId: 'competency.strategy-costs.foundation',
  title: 'İşlem maliyeti stratejiyi nasıl değiştirebilir?', titleEn: 'How can trading costs change a strategy?',
  objective: 'İşlem maliyetleri ve yüksek turnover’ın strateji avantajını nasıl azaltabildiğini öğren.', objectiveEn: 'Explain how spreads, fees, slippage, and turnover can erode a paper edge.', minutes: 5,
  hook: 'Brüt olarak iyi görünen iki stratejiden daha az işlem yapan neden daha iyi sonuç verebilir?', hookEn: 'Why might a lower-turnover strategy outperform another strategy with the same gross edge?',
  explanation: 'Her işlem spread, komisyon, slippage ve bazen finansman maliyeti taşır. Strateji çok sık işlem yapıyorsa küçük teorik avantaj, maliyetler tekrarlandıkça gerçek uygulamada kaybolabilir.', explanationEn: 'Strategy results are not only about directional calls. Each trade can incur spread, fees, slippage, and sometimes financing or taxes. As turnover rises, a small theoretical edge can disappear in implementation.',
  proExplanation: 'Capacity, market impact and liquidity make costs position size dependent. Backtest cost assumptions should be conservative and matched to venue, horizon, order type, and size.', proExplanationEn: 'Capacity, market impact, and liquidity make costs size-dependent. Cost assumptions should match venue, horizon, order type, and size.',
  misconception: 'Stratejiyi yalnız brüt performansla değerlendirip maliyeti sıfır sayma.', misconceptionEn: 'Common mistake: evaluating only gross historical results while assuming zero implementation cost.',
  takeaway: 'Gerçek avantaj, maliyetten sonra kalandır.', takeawayEn: 'An edge is what remains after implementation costs.',
  prerequisiteConceptKeys: ['market.microstructure.bid_ask', 'market.execution.slippage'], relatedConceptKeys: ['behavior.overtrading', 'strategy.momentum', 'risk.liquidity'],
  visualAlt: 'Brüt strateji avantajından spread, fee ve slippage çıkarılarak net sonuca ulaşıldığını gösteren görsel', visualAltEn: 'Visual subtracting spread, fees, and slippage from gross strategy edge to reach net results',
  taskPrompt: 'Yüksek turnover neden sorun olabilir?', taskPromptEn: 'Why can high turnover be a problem?',
  taskChoices: [{ id: 'cost', label: 'Maliyetleri tekrarlayarak net avantajı aşındırabilir', labelEn: 'Repeated costs can erode net edge' }, { id: 'free', label: 'Her işlemi ücretsiz yapar', labelEn: 'It makes every trade free' }, { id: 'guarantee', label: 'Win rate’i garanti eder', labelEn: 'It guarantees win rate' }], taskCorrectIds: ['cost'],
  questions: [
    { prompt: 'Net strateji sonucu neyi içermelidir?', promptEn: 'What should net strategy results include?', choices: [{ id: 'a', label: 'Gerçekçi işlem maliyetlerini', labelEn: 'Realistic implementation costs' }, { id: 'b', label: 'Yalnız brüt getiri', labelEn: 'Only gross return' }, { id: 'c', label: 'Sadece grafik rengi', labelEn: 'Only chart color' }], correctId: 'a', explanation: 'Uygulama maliyeti yatırımcıya kalan sonucu değiştirir.', explanationEn: 'Implementation costs change what remains to the user.' },
    { prompt: 'Slippage her stratejide aynı mıdır?', promptEn: 'Is slippage identical for every strategy?', choices: [{ id: 'a', label: 'Hayır; hız, likidite, boyut ve emir türüne bağlıdır', labelEn: 'No; it depends on speed, liquidity, size, and order type' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman sıfırdır', labelEn: 'It is always zero' }], correctId: 'a', explanation: 'Uygulama koşulları maliyeti değiştirir.', explanationEn: 'Execution conditions change costs.' },
    { prompt: 'Küçük brüt edge ve yüksek turnover birlikte ne yaratabilir?', promptEn: 'What can a small gross edge plus high turnover create?', choices: [{ id: 'a', label: 'Maliyet sonrası zayıf veya negatif net sonuç', labelEn: 'Weak or negative net results after costs' }, { id: 'b', label: 'Kesin kâr', labelEn: 'Certain profit' }, { id: 'c', label: 'Sıfır risk', labelEn: 'Zero risk' }], correctId: 'a', explanation: 'Maliyetler küçük avantajı aşabilir.', explanationEn: 'Costs can exceed a small gross advantage.' },
  ], sources: [STRATEGY_SOURCES.risk],
});

const strategyDiversification = createFoundationLesson({
  id: 'lesson.strategy.diversification.001', slug: 'strateji-cesitlendirmesi', conceptKey: 'strategy.diversification', skillId: 'skill.strategy-design', competencyId: 'competency.strategy-diversification.foundation',
  title: 'Birden fazla strateji gerçekten çeşitlendirme midir?', titleEn: 'Do multiple strategies automatically create diversification?',
  objective: 'Birden fazla stratejinin neden otomatik olarak çeşitlendirme anlamına gelmediğini öğren.', objectiveEn: 'Explain that differently named methods can share the same risk factor or regime dependence, so strategy diversification requires behavioral difference.', minutes: 5,
  hook: 'Trend, momentum ve breakout isimli üç sistem aynı anda aynı yönde kaybediyorsa gerçekten üç farklı risk mi taşıyorsun?', hookEn: 'If trend, momentum, and breakout systems all lose together, are you truly carrying three different risks?',
  explanation: 'Strateji sayısını artırmak tek başına çeşitlendirme değildir. Farklı isimli sistemler aynı yön, volatilite, likidite veya momentum faktörüne bağlıysa stres döneminde birlikte kaybedebilir. Önemli olan isimleri değil, risk davranışlarının gerçekten farklı olmasıdır.', explanationEn: 'Strategy diversification is not simply adding more method names. Different strategies can depend on the same direction, volatility, liquidity, or momentum factor and fail together. What matters is how differently their returns and risks behave.',
  proExplanation: 'Cross-strategy correlation, common factor beta, drawdown overlap and regime dependence can reveal hidden concentration. Correlations can increase during stress.', proExplanationEn: 'Cross-strategy correlation, common factor beta, drawdown overlap, and regime dependence can reveal hidden concentration. Correlations can rise under stress.',
  misconception: 'Farklı strateji adlarını otomatik çeşitlendirme sanma.', misconceptionEn: 'Common mistake: assuming three different strategy names automatically mean diversification.',
  takeaway: 'Strateji adlarını değil, ortak risk kaynaklarını say.', takeawayEn: 'Count common risk sources, not strategy names.',
  prerequisiteConceptKeys: ['portfolio.correlation', 'portfolio.risk_factors'], relatedConceptKeys: ['strategy.regime_fit', 'portfolio.diversification', 'portfolio.stress_testing'],
  visualAlt: 'Üç farklı strateji adının aynı ortak risk faktörüne bağlanabildiğini ve gerçek çeşitlendirmenin farklı davranış dalları gerektirdiğini gösteren görsel', visualAltEn: 'Visual showing three strategy names linked to one shared factor versus genuinely different behavior branches',
  taskPrompt: 'Gerçek strateji çeşitlendirmesi için neye bakılır?', taskPromptEn: 'What matters for real strategy diversification?',
  taskChoices: [{ id: 'behavior', label: 'Ortak risk faktörleri, korelasyon ve drawdown davranışı', labelEn: 'Shared risk factors, correlation, and drawdown behavior' }, { id: 'names', label: 'Sadece strateji isimlerinin farklı olmasına', labelEn: 'Only different strategy names' }, { id: 'count', label: 'Dosya sayısına', labelEn: 'Number of files' }], taskCorrectIds: ['behavior'],
  questions: [
    { prompt: 'Farklı isimli stratejiler aynı riski taşıyabilir mi?', promptEn: 'Can differently named strategies carry the same risk?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'İsim farklıysa imkânsız', labelEn: 'Impossible if names differ' }], correctId: 'a', explanation: 'Ortak faktör bağımlılığı gizli yoğunlaşma yaratabilir.', explanationEn: 'Shared factor exposure can create hidden concentration.' },
    { prompt: 'Stres döneminde korelasyon değişebilir mi?', promptEn: 'Can correlation change under stress?', choices: [{ id: 'a', label: 'Evet, artabilir', labelEn: 'Yes, it can rise' }, { id: 'b', label: 'Hayır, sabittir', labelEn: 'No, it is fixed' }, { id: 'c', label: 'Her zaman sıfırdır', labelEn: 'It is always zero' }], correctId: 'a', explanation: 'Kriz koşulları normal dönem ilişkilerini değiştirebilir.', explanationEn: 'Stress conditions can change normal relationships.' },
    { prompt: 'Çeşitlendirme neyi azaltmayı amaçlar?', promptEn: 'What does diversification aim to reduce?', choices: [{ id: 'a', label: 'Tek ortak risk kaynağına bağımlılığı', labelEn: 'Dependence on one common risk source' }, { id: 'b', label: 'Her türlü kaybı', labelEn: 'Every possible loss' }, { id: 'c', label: 'Veri ihtiyacını', labelEn: 'The need for data' }], correctId: 'a', explanation: 'Amaç riskleri farklılaştırmaktır, kaybı imkânsız kılmak değil.', explanationEn: 'The goal is to diversify risk, not make losses impossible.' },
  ], sources: [STRATEGY_SOURCES.risk],
});

const reviewDiscipline = createFoundationLesson({
  id: 'lesson.strategy.review-discipline.001', slug: 'stratejiyi-ne-zaman-review-etmeli', conceptKey: 'strategy.review_discipline', skillId: 'skill.strategy-design', competencyId: 'competency.strategy-review.foundation',
  title: 'Stratejiyi ne zaman değiştirmelisin?', titleEn: 'When should you change a strategy?',
  objective: 'Stratejiyi sonuçlara tepkiyle değil, planlı review süreciyle ne zaman değiştireceğini öğren.', objectiveEn: 'Explain how to review process drift, hypothesis weakening, cost changes, and regime behavior instead of reacting to one win or loss.', minutes: 5,
  hook: 'Üç kayıp sonrası kuralları hemen değiştirmek adaptasyon mudur, yoksa overreaction olabilir mi?', hookEn: 'Is changing rules after three losses adaptation, or could it be overreaction?',
  explanation: 'Strateji review’u P&L’ye duygusal tepki vermek değildir. Hipotez, uygulama disiplini, maliyetler ve piyasa koşulları planlı aralıklarla incelenir. Kötü sonuç tek başına stratejinin bozulduğunu, iyi sonuç da sürecin doğru olduğunu kanıtlamaz.', explanationEn: 'Strategy review is not an emotional reaction to P&L. It is a planned assessment of the hypothesis, execution discipline, costs, and market conditions. Poor results alone do not prove the strategy is broken; good results do not prove the process is sound.',
  proExplanation: 'Review cadence should match strategy horizon. Change control should separate parameter maintenance, hypothesis revision, risk override, and full retirement decisions.', proExplanationEn: 'Review cadence should match strategy horizon. Change control should separate parameter maintenance, hypothesis revision, risk overrides, and full retirement.',
  misconception: 'Her kısa kayıp serisinde stratejiyi değiştirme veya kazanç serisinde kuralları gevşetme.', misconceptionEn: 'Common mistake: changing a strategy after every short losing streak or loosening rules after a winning streak.',
  takeaway: 'Kuralı duygusal anda değil, belgeli review sürecinde değiştir.', takeawayEn: 'Change rules through a documented review process, not in an emotional moment.',
  prerequisiteConceptKeys: ['strategy.hypothesis', 'behavior.outcome_bias'], relatedConceptKeys: ['strategy.regime_fit', 'behavior.precommitment', 'evidence.freshness'],
  visualAlt: 'Sonuç, süreç, rejim ve maliyet kutularını ayrı kontrol edip ardından devam-değiştir-durdur kararına giden review akışı', visualAltEn: 'Review flow checking outcome, process, regime, and costs before continue-change-retire decisions',
  taskPrompt: 'Strateji değişikliği en sağlıklı ne zaman yapılır?', taskPromptEn: 'When is a strategy change healthiest?',
  taskChoices: [{ id: 'review', label: 'Önceden tanımlı, belgeli review sürecinde', labelEn: 'During a predefined, documented review process' }, { id: 'loss', label: 'Her tek kayıptan hemen sonra', labelEn: 'Immediately after every single loss' }, { id: 'emotion', label: 'En öfkeli anda', labelEn: 'At the most emotional moment' }], taskCorrectIds: ['review'],
  questions: [
    { prompt: 'Tek kötü sonuç stratejinin bozulduğunu kanıtlar mı?', promptEn: 'Does one bad outcome prove a strategy is broken?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Sonuç, süreç ve beklenen varyasyon birlikte değerlendirilir.', explanationEn: 'Outcome, process, and expected variation need joint review.' },
    { prompt: 'Review cadence neyle uyumlu olmalıdır?', promptEn: 'What should review cadence match?', choices: [{ id: 'a', label: 'Stratejinin zaman ufku ve veri sıklığıyla', labelEn: 'The strategy horizon and data frequency' }, { id: 'b', label: 'Sosyal medya temposuyla', labelEn: 'Social-media pace' }, { id: 'c', label: 'Sadece duyguyla', labelEn: 'Only emotion' }], correctId: 'a', explanation: 'Çok sık review kısa ufuk gürültüsüne tepki yaratabilir.', explanationEn: 'Over-frequent review can react to short-horizon noise.' },
    { prompt: 'İyi sonuç kötü süreci gizleyebilir mi?', promptEn: 'Can a good outcome hide a poor process?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'İmkânsız', labelEn: 'Impossible' }], correctId: 'a', explanation: 'Outcome bias nedeniyle süreç ayrıca denetlenmelidir.', explanationEn: 'Process must be reviewed separately because of outcome bias.' },
  ], sources: [STRATEGY_SOURCES.methodology, STRATEGY_SOURCES.risk],
});

export const STRATEGY_EXPANSION_LESSONS = [hypothesis, rules, regimeFit, costsTurnover, strategyDiversification, reviewDiscipline] as const;
