import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { STRATEGY_SOURCES } from './strategySources';

const horizonObjective = createFoundationLesson({
  id: 'lesson.strategy.horizon-objective.001', slug: 'strateji-amaci-ve-zaman-ufku', conceptKey: 'strategy.horizon_objective', skillId: 'skill.strategy-design', competencyId: 'competency.strategy-horizon.foundation',
  title: 'Strateji neyi çözmeye çalışır?', titleEn: 'What is a strategy trying to solve?',
  objective: 'İşlem veya yatırım yaklaşımını amaç, zaman ufku, karar sıklığı ve risk sınırıyla birlikte tanımlamanın neden gerekli olduğunu açıklar.', objectiveEn: 'Explain why an approach needs a defined objective, time horizon, decision frequency, and risk boundary.', minutes: 5,
  hook: 'Aynı grafiğe bakan iki kişi neden tamamen farklı ama kendi içinde tutarlı kararlar verebilir?', hookEn: 'Why can two people looking at the same chart make very different yet internally consistent decisions?',
  explanation: 'Strateji, tek bir giriş sinyali değil; belirli bir amaç için hangi veriye bakılacağını, ne zaman karar verileceğini, neyin geçersizlik sayılacağını ve riskin nasıl sınırlandırılacağını tanımlayan yöntemdir. Dakikalık işlem ile yıllık yatırım aynı zaman ufkunu ve aynı kanıtı kullanmaz.', explanationEn: 'A strategy is not one entry signal. It is a method defining what evidence matters, when decisions are made, what invalidates the idea, and how risk is bounded for a specific objective. A minute-level trade and a multi-year investment do not use the same horizon or evidence.',
  proExplanation: 'Horizon mismatch, farklı frekanstaki veri ve risk varsayımlarını karıştırır. Strategy mandate, holding period, rebalance/decision cadence ve loss tolerance birlikte yazılmalıdır.', proExplanationEn: 'Horizon mismatch mixes evidence and risk assumptions from different frequencies. A strategy mandate should specify holding period, decision cadence, and loss tolerance together.',
  misconception: 'Yaygın hata: “İyi strateji”yi her zaman diliminde ve her amaçta aynı şekilde çalışan tek formül sanmak.', misconceptionEn: 'Common mistake: treating a “good strategy” as one formula that works for every horizon and objective.',
  takeaway: 'Önce amaç ve zaman ufku; sonra yöntem ve kural.', takeawayEn: 'Define the objective and horizon before the method and rules.',
  prerequisiteConceptKeys: ['risk.basics', 'market.chart.timeframes'], relatedConceptKeys: ['strategy.swing_position', 'strategy.rules', 'portfolio.construction'],
  visualAlt: 'Kısa, orta ve uzun zaman ufuklarını farklı amaç ve karar sıklıklarıyla eşleyen sade strateji haritası', visualAltEn: 'Simple strategy map matching short, medium, and long horizons to different objectives and decision frequencies',
  taskPrompt: 'Bir stratejiyi tanımlarken hangisi önce netleşmelidir?', taskPromptEn: 'What should be clarified first when defining a strategy?',
  taskChoices: [{ id: 'objective', label: 'Amaç ve zaman ufku', labelEn: 'Objective and time horizon' }, { id: 'color', label: 'Grafik rengi', labelEn: 'Chart color' }, { id: 'logo', label: 'Platform logosu', labelEn: 'Platform logo' }], taskCorrectIds: ['objective'],
  questions: [
    { prompt: 'Strateji yalnız giriş sinyali midir?', promptEn: 'Is a strategy only an entry signal?', choices: [{ id: 'a', label: 'Hayır; amaç, kanıt, kurallar ve risk çerçevesidir', labelEn: 'No; it includes objective, evidence, rules, and risk' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız teknik analizde', labelEn: 'Only in technical analysis' }], correctId: 'a', explanation: 'Strateji karar sürecinin tamamını tanımlar.', explanationEn: 'A strategy defines the full decision process.' },
    { prompt: 'Zaman ufku neden önemlidir?', promptEn: 'Why does the time horizon matter?', choices: [{ id: 'a', label: 'İlgili veri, karar sıklığı ve riski değiştirir', labelEn: 'It changes relevant evidence, decision frequency, and risk' }, { id: 'b', label: 'Sadece grafik boyutunu değiştirir', labelEn: 'It only changes chart size' }, { id: 'c', label: 'Önemi yoktur', labelEn: 'It does not matter' }], correctId: 'a', explanation: 'Farklı ufuklar farklı bilgi ve risk varsayımları gerektirir.', explanationEn: 'Different horizons require different evidence and risk assumptions.' },
    { prompt: 'Horizon mismatch nedir?', promptEn: 'What is horizon mismatch?', choices: [{ id: 'a', label: 'Bir ufkun kanıtıyla başka ufkun kararını yönetmek', labelEn: 'Using evidence from one horizon to manage a decision on another' }, { id: 'b', label: 'Saat dilimi farkı', labelEn: 'A timezone difference' }, { id: 'c', label: 'Spread genişlemesi', labelEn: 'Spread widening' }], correctId: 'a', explanation: 'Zaman ufku karışıklığı stratejinin tutarlılığını bozar.', explanationEn: 'Mixing horizons undermines strategy consistency.' },
  ], sources: [STRATEGY_SOURCES.methodology],
});

const trendFollowing = createFoundationLesson({
  id: 'lesson.strategy.trend-following.001', slug: 'trend-following-nasil-dusunur', conceptKey: 'strategy.trend_following', skillId: 'skill.strategy-design', competencyId: 'competency.trend-following.foundation',
  title: 'Trend following nasıl düşünür?', titleEn: 'How does trend following think?',
  objective: 'Trend takip yaklaşımının yönü tahmin etmekten çok devam eden hareketi kurallı biçimde takip ettiğini ve yatay piyasalarda zorlanabileceğini açıklar.', objectiveEn: 'Explain that trend following follows persistent movement with rules rather than predicting direction, and can struggle in choppy markets.', minutes: 5,
  hook: 'Bir trend takip sistemi tepeyi veya dibi bilmek zorunda mıdır?', hookEn: 'Does a trend-following system need to know the exact top or bottom?',
  explanation: 'Trend following, fiyatın belirli ölçütlerle oluşmuş yönlü hareketinin devam edebileceği varsayımını kurallı biçimde takip eder. Amaç dönüşü önceden bilmek değil; trend oluştuğunda katılmak, trend bozulduğunda çıkmaktır. Bu nedenle geç giriş ve küçük sık kayıplar yaklaşımın doğal trade-off’u olabilir.', explanationEn: 'Trend following systematically participates in directional movement once it meets defined criteria. The goal is not to predict reversals but to join established trends and exit when they weaken. Late entries and repeated small losses can be natural trade-offs.',
  proExplanation: 'Trend systems typically exchange lower hit rate and whipsaw risk for occasional larger directional moves. Signal horizon, volatility scaling and exit rule materially shape the return profile.', proExplanationEn: 'Trend systems often trade a lower hit rate and whipsaw risk for occasional larger directional moves. Signal horizon, volatility scaling, and exits shape the return profile.',
  misconception: 'Yaygın hata: Trend following’i “fiyat yükseldi, o halde kesin yükselmeye devam eder” iddiası sanmak.', misconceptionEn: 'Common mistake: treating trend following as “price rose, therefore it must keep rising.”',
  takeaway: 'Trend following tahmin değil; devam eden hareketi kuralla takip etme yaklaşımıdır.', takeawayEn: 'Trend following is not certainty; it is rule-based participation in persistent movement.',
  prerequisiteConceptKeys: ['market.trend.basics'], relatedConceptKeys: ['strategy.regime_fit', 'market.technical.momentum', 'risk.stop_orders'],
  visualAlt: 'Yönlü trendde katılım ve yatay bölgede küçük whipsaw kayıplarını karşılaştıran sade strateji görseli', visualAltEn: 'Simple visual contrasting participation in a directional trend with whipsaw losses in a range',
  taskPrompt: 'Trend following’in temel trade-off’u hangisidir?', taskPromptEn: 'What is a key trend-following trade-off?',
  taskChoices: [{ id: 'whipsaw', label: 'Yatay piyasada sık küçük yanlış sinyaller karşılığında büyük trendleri yakalama ihtimali', labelEn: 'Frequent small whipsaws in exchange for participating in larger trends' }, { id: 'certainty', label: 'Her trendi tepe ve dipten bilmek', labelEn: 'Knowing every top and bottom' }, { id: 'free', label: 'İşlem maliyeti olmaması', labelEn: 'Having no trading costs' }], taskCorrectIds: ['whipsaw'],
  questions: [
    { prompt: 'Trend following neyi amaçlar?', promptEn: 'What does trend following aim to do?', choices: [{ id: 'a', label: 'Oluşmuş yönlü hareketi kuralla takip etmeyi', labelEn: 'Systematically follow established directional movement' }, { id: 'b', label: 'Her dönüşü önceden bilmeyi', labelEn: 'Predict every reversal' }, { id: 'c', label: 'Yalnız haber okumayı', labelEn: 'Only read news' }], correctId: 'a', explanation: 'Yaklaşım yönlü devamı takip eder, kesin tahmin iddiasında değildir.', explanationEn: 'The approach follows persistence without claiming certainty.' },
    { prompt: 'Hangi piyasa koşulu trend sistemini zorlayabilir?', promptEn: 'Which market condition can challenge a trend system?', choices: [{ id: 'a', label: 'Sık yön değiştiren yatay piyasa', labelEn: 'Choppy sideways markets' }, { id: 'b', label: 'Uzun ve temiz yönlü hareket', labelEn: 'A long clean directional move' }, { id: 'c', label: 'Hiç veri olmaması dışında her koşul aynıdır', labelEn: 'All conditions are identical' }], correctId: 'a', explanation: 'Whipsaw riski yatay ve gürültülü piyasalarda artar.', explanationEn: 'Whipsaw risk rises in choppy ranges.' },
    { prompt: 'Trend following düşük win rate ile çalışabilir mi?', promptEn: 'Can trend following work with a lower win rate?', choices: [{ id: 'a', label: 'Evet; kazanç/kayıp dağılımı ve risk de önemlidir', labelEn: 'Yes; payoff distribution and risk also matter' }, { id: 'b', label: 'Hayır, win rate her şeydir', labelEn: 'No, win rate is everything' }, { id: 'c', label: 'Sadece %100 win rate ile', labelEn: 'Only with a 100% win rate' }], correctId: 'a', explanation: 'Strateji kalitesi yalnız isabet oranıyla ölçülmez.', explanationEn: 'Strategy quality is not determined by hit rate alone.' },
  ], sources: [STRATEGY_SOURCES.methodology, STRATEGY_SOURCES.risk],
});

const meanReversion = createFoundationLesson({
  id: 'lesson.strategy.mean-reversion.001', slug: 'mean-reversion-ne-varsayar', conceptKey: 'strategy.mean_reversion', skillId: 'skill.strategy-design', competencyId: 'competency.mean-reversion.foundation',
  title: 'Mean reversion ne varsayar?', titleEn: 'What does mean reversion assume?',
  objective: 'Ortalamaya dönüş yaklaşımının aşırı sapmaların normale yaklaşabileceği varsayımına dayandığını ve güçlü trendlerde bu varsayımın tehlikeli olabileceğini açıklar.', objectiveEn: 'Explain that mean reversion assumes extreme deviations may normalize and that this can be dangerous during persistent trends.', minutes: 5,
  hook: 'Fiyat ortalamadan çok uzaklaştı diye mutlaka geri dönmek zorunda mıdır?', hookEn: 'Must price revert simply because it moved far from an average?',
  explanation: 'Mean reversion, belirli bir ölçüte göre aşırı sapmış fiyat veya spreadin zamanla daha normal bir seviyeye yaklaşabileceği fikrini kullanır. Ancak “uzaklaştı” tek başına dönüş garantisi değildir; yeni bir trend veya rejim değişimi eski ortalamayı geçersiz kılabilir.', explanationEn: 'Mean reversion uses the idea that an extreme deviation from a reference may normalize over time. But distance alone does not guarantee reversal; a new trend or regime shift can make the old reference irrelevant.',
  proExplanation: 'Reference window, stationarity assumption, entry threshold, stop/invalidation and holding period mean-reversion riskini belirler. Structural breaks are a central failure mode.', proExplanationEn: 'Reference window, stationarity assumptions, entry thresholds, invalidation, and holding period drive mean-reversion risk. Structural breaks are a central failure mode.',
  misconception: 'Yaygın hata: “Çok düştü, artık çıkmalı” veya “çok yükseldi, artık düşmeli” cümlesini tek başına strateji sanmak.', misconceptionEn: 'Common mistake: treating “it fell a lot so it must rise” or “it rose a lot so it must fall” as a complete strategy.',
  takeaway: 'Sapma dönüş ihtimali yaratabilir; dönüş zorunluluğu yaratmaz.', takeawayEn: 'Deviation can create a reversion hypothesis, not a reversion guarantee.',
  prerequisiteConceptKeys: ['market.technical.range'], relatedConceptKeys: ['strategy.regime_fit', 'market.technical.moving_average', 'risk.volatility'],
  visualAlt: 'Referans bant çevresinde geri dönen sapmalar ile trend halinde referanstan uzaklaşmaya devam eden fiyatı karşılaştıran görsel', visualAltEn: 'Visual contrasting deviations that revert around a reference with a trend that keeps moving away',
  taskPrompt: 'Mean reversion için en önemli risk hangisidir?', taskPromptEn: 'What is a key risk for mean reversion?',
  taskChoices: [{ id: 'break', label: 'Eski ortalamanın artık geçerli olmadığı rejim değişimi', labelEn: 'A regime change that makes the old reference invalid' }, { id: 'guarantee', label: 'Her sapmanın kesin dönmesi', labelEn: 'Every deviation reverting with certainty' }, { id: 'none', label: 'Risk taşımaması', labelEn: 'Having no risk' }], taskCorrectIds: ['break'],
  questions: [
    { prompt: 'Mean reversion neyi varsayar?', promptEn: 'What does mean reversion assume?', choices: [{ id: 'a', label: 'Bazı aşırı sapmaların referansa yaklaşabileceğini', labelEn: 'Some extreme deviations may move back toward a reference' }, { id: 'b', label: 'Her fiyatın kesin geri döneceğini', labelEn: 'Every price must revert' }, { id: 'c', label: 'Trendlerin hiç oluşmadığını', labelEn: 'Trends never exist' }], correctId: 'a', explanation: 'Yaklaşım olasılıksal bir normalleşme hipotezidir.', explanationEn: 'It is a probabilistic normalization hypothesis.' },
    { prompt: 'Güçlü trend mean reversion için neden risklidir?', promptEn: 'Why can a strong trend be risky for mean reversion?', choices: [{ id: 'a', label: 'Sapma büyümeye devam edebilir', labelEn: 'The deviation can keep expanding' }, { id: 'b', label: 'Fiyat hareket etmez', labelEn: 'Price stops moving' }, { id: 'c', label: 'Spread yok olur', labelEn: 'Spreads disappear' }], correctId: 'a', explanation: 'Trend eski referansın geçerliliğini zayıflatabilir.', explanationEn: 'A persistent trend can invalidate the old reference.' },
    { prompt: '“Çok düştü” tek başına yeterli midir?', promptEn: 'Is “it fell a lot” sufficient by itself?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman', labelEn: 'Always' }], correctId: 'a', explanation: 'Referans, rejim, risk ve invalidation gerekir.', explanationEn: 'Reference, regime, risk, and invalidation still matter.' },
  ], sources: [STRATEGY_SOURCES.methodology, STRATEGY_SOURCES.risk],
});

const breakoutStrategy = createFoundationLesson({
  id: 'lesson.strategy.breakout.001', slug: 'breakout-stratejisi-ne-yapar', conceptKey: 'strategy.breakout', skillId: 'skill.strategy-design', competencyId: 'competency.breakout-strategy.foundation',
  title: 'Breakout stratejisi neyi sistemleştirir?', titleEn: 'What does a breakout strategy systematize?',
  objective: 'Breakout kavramını tekrar etmeden, kırılım yaklaşımının giriş teyidi, başarısızlık koşulu, risk ve maliyet kurallarına nasıl dönüştürüldüğünü açıklar.', objectiveEn: 'Explain how a breakout concept becomes a method through entry confirmation, failure conditions, risk, and cost rules.', minutes: 5,
  hook: 'Bir seviye kırıldıktan sonra “breakout var” demek, strateji tanımlamak için yeterli midir?', hookEn: 'After a level breaks, is saying “there is a breakout” enough to define a strategy?',
  explanation: 'Breakout stratejisi, fiyatın tanımlı bir aralık veya seviyeden çıkışını bir karar kuralına dönüştürür. Strateji; neyin kırılım sayılacağını, girişin ne zaman yapılacağını, false breakout durumunda neyin geçersizlik olacağını ve riskin nasıl sınırlandırılacağını açıkça tanımlar.', explanationEn: 'A breakout strategy turns movement beyond a defined range or level into a decision rule. It specifies what counts as a break, when entry is allowed, what invalidates the setup if the break fails, and how risk is bounded.',
  proExplanation: 'Confirmation delay reduces false positives but can worsen entry price; early entry improves price but increases failure exposure. Gap/slippage and liquidity are material implementation costs.', proExplanationEn: 'Confirmation delay can reduce false positives but worsen entry price; early entry improves price but increases failure exposure. Gaps, slippage, and liquidity are material implementation costs.',
  misconception: 'Yaygın hata: Teknik olarak görülen her kırılımı aynı breakout stratejisinin otomatik işlemi saymak.', misconceptionEn: 'Common mistake: treating every visible break as an automatic trade under the same breakout strategy.',
  takeaway: 'Breakout bir olaydır; strateji o olay için giriş, invalidation ve risk kuralıdır.', takeawayEn: 'A breakout is an event; a strategy defines entry, invalidation, and risk around it.',
  prerequisiteConceptKeys: ['market.technical.breakout', 'market.technical.false_breakout'], relatedConceptKeys: ['strategy.rules', 'strategy.regime_fit', 'market.execution.slippage'],
  visualAlt: 'Aynı kırılım olayının teyit, giriş, invalidation ve risk kutularıyla bir strateji akışına dönüştüğünü gösteren görsel', visualAltEn: 'Visual showing a breakout event transformed into a strategy flow with confirmation, entry, invalidation, and risk',
  taskPrompt: 'Breakout olayını stratejiye dönüştüren unsur hangisidir?', taskPromptEn: 'What turns a breakout event into a strategy?',
  taskChoices: [{ id: 'rules', label: 'Önceden tanımlı giriş, invalidation ve risk kuralları', labelEn: 'Predefined entry, invalidation, and risk rules' }, { id: 'line', label: 'Grafikte tek çizgi', labelEn: 'One line on a chart' }, { id: 'certainty', label: 'Kırılımın kesin devam edeceği inancı', labelEn: 'Belief that every break must continue' }], taskCorrectIds: ['rules'],
  questions: [
    { prompt: 'Breakout ile breakout stratejisi aynı şey midir?', promptEn: 'Are a breakout and a breakout strategy the same thing?', choices: [{ id: 'a', label: 'Hayır; biri olay, diğeri kural setidir', labelEn: 'No; one is an event, the other a rule set' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece günlük grafikte aynıdır', labelEn: 'Only on daily charts' }], correctId: 'a', explanation: 'Strateji olay çevresinde uygulanacak karar kurallarını tanımlar.', explanationEn: 'The strategy defines decision rules around the event.' },
    { prompt: 'Daha fazla teyidin trade-off’u nedir?', promptEn: 'What is a trade-off of more confirmation?', choices: [{ id: 'a', label: 'False break riski azalabilir ama giriş fiyatı kötüleşebilir', labelEn: 'False-break risk may fall while entry price worsens' }, { id: 'b', label: 'Her zaman daha iyi fiyat verir', labelEn: 'It always gives a better price' }, { id: 'c', label: 'Maliyeti yok eder', labelEn: 'It removes costs' }], correctId: 'a', explanation: 'Teyit ile erken giriş arasında maliyet ve hata trade-off’u vardır.', explanationEn: 'Confirmation and early entry involve a timing trade-off.' },
    { prompt: 'Slippage breakout stratejisinde önemli olabilir mi?', promptEn: 'Can slippage matter in breakout strategies?', choices: [{ id: 'a', label: 'Evet, özellikle hızlı hareketlerde', labelEn: 'Yes, especially during fast moves' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece tahvillerde', labelEn: 'Only in bonds' }], correctId: 'a', explanation: 'Hızlı kırılımlar beklenen ve gerçekleşen fiyatı ayırabilir.', explanationEn: 'Fast breaks can separate expected and realized execution prices.' },
  ], sources: [STRATEGY_SOURCES.methodology, STRATEGY_SOURCES.risk],
});

const momentumStrategy = createFoundationLesson({
  id: 'lesson.strategy.momentum.001', slug: 'momentum-stratejisi-ne-yapar', conceptKey: 'strategy.momentum', skillId: 'skill.strategy-design', competencyId: 'competency.momentum-strategy.foundation',
  title: 'Momentum yaklaşımı neyi takip eder?', titleEn: 'What does a momentum approach follow?',
  objective: 'Momentum stratejisinin yalnız “hızlı yükselen şeyi almak” olmadığını; göreli veya mutlak performansı tanımlı pencere ve risk kurallarıyla kullandığını açıklar.', objectiveEn: 'Explain that momentum is not simply buying what rose fastest, but using defined relative or absolute performance measures with risk rules.', minutes: 5,
  hook: 'Son dönemin en güçlü varlığını almak tek başına momentum stratejisi midir?', hookEn: 'Is simply buying the strongest recent asset a complete momentum strategy?',
  explanation: 'Momentum yaklaşımı, güçlü veya zayıf performansın bir süre devam edebileceği hipotezini ölçülebilir kurallara dönüştürür. Bakılan dönem, karşılaştırma evreni, yeniden dengeleme sıklığı ve risk kontrolü sonucu ciddi biçimde değiştirebilir.', explanationEn: 'Momentum turns the hypothesis of performance persistence into measurable rules. Lookback window, comparison universe, rebalance frequency, and risk controls can materially change outcomes.',
  proExplanation: 'Cross-sectional momentum ranks assets relative to peers; time-series momentum compares an asset with its own historical signal. Momentum crash and crowded positioning are relevant tail risks.', proExplanationEn: 'Cross-sectional momentum ranks assets against peers; time-series momentum compares an asset with its own historical signal. Momentum crashes and crowded positioning are relevant tail risks.',
  misconception: 'Yaygın hata: Momentum yaklaşımını “en çok yükseleni ne olursa olsun kovalamak” olarak görmek.', misconceptionEn: 'Common mistake: treating momentum as blindly chasing whatever rose the most.',
  takeaway: 'Momentum, performans devamını ölçen kural setidir; fiyat kovalamak değildir.', takeawayEn: 'Momentum is a rules-based persistence approach, not blind price chasing.',
  prerequisiteConceptKeys: ['market.technical.momentum'], relatedConceptKeys: ['strategy.regime_fit', 'behavior.fomo', 'strategy.costs_turnover'],
  visualAlt: 'Farklı varlıkların performans sıralamasını ve seçimin lookback, rebalance ve risk filtresinden geçtiğini gösteren görsel', visualAltEn: 'Visual showing asset performance ranks filtered through lookback, rebalance, and risk rules',
  taskPrompt: 'Momentum stratejisini basit fiyat kovalamadan ayıran nedir?', taskPromptEn: 'What distinguishes a momentum strategy from simple price chasing?',
  taskChoices: [{ id: 'rules', label: 'Tanımlı ölçüm penceresi, evren, rebalance ve risk kuralları', labelEn: 'Defined measurement window, universe, rebalance, and risk rules' }, { id: 'emotion', label: 'FOMO ile hızlı karar', labelEn: 'A fast FOMO-driven decision' }, { id: 'highest', label: 'Daima en yüksek fiyatlı varlığı almak', labelEn: 'Always buy the highest-priced asset' }], taskCorrectIds: ['rules'],
  questions: [
    { prompt: 'Momentum hipotezi nedir?', promptEn: 'What is the momentum hypothesis?', choices: [{ id: 'a', label: 'Göreli veya mutlak performansın bir süre devam edebilmesi', labelEn: 'Relative or absolute performance may persist for a period' }, { id: 'b', label: 'Her yükselişin sonsuza kadar sürmesi', labelEn: 'Every rise continues forever' }, { id: 'c', label: 'Fiyatların sabit kalması', labelEn: 'Prices remain fixed' }], correctId: 'a', explanation: 'Momentum olasılıksal performans devamını ölçer.', explanationEn: 'Momentum measures probabilistic persistence.' },
    { prompt: 'Lookback süresi neden önemlidir?', promptEn: 'Why does lookback matter?', choices: [{ id: 'a', label: 'Hangi performansın “momentum” sayıldığını değiştirir', labelEn: 'It changes what performance counts as momentum' }, { id: 'b', label: 'Sadece ekran tasarımını değiştirir', labelEn: 'It only changes screen design' }, { id: 'c', label: 'Önemsizdir', labelEn: 'It does not matter' }], correctId: 'a', explanation: 'Farklı pencereler farklı sinyal ve turnover üretir.', explanationEn: 'Different windows produce different signals and turnover.' },
    { prompt: 'Momentum ile FOMO aynı şey midir?', promptEn: 'Are momentum and FOMO the same?', choices: [{ id: 'a', label: 'Hayır; biri kural tabanlı yöntem, diğeri davranışsal dürtü olabilir', labelEn: 'No; one can be a rules-based method, the other a behavioral impulse' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Her zaman aynıdır', labelEn: 'Always identical' }], correctId: 'a', explanation: 'Kural ve ölçüm, dürtüsel fiyat kovalamadan ayrılır.', explanationEn: 'Rules and measurement distinguish the method from impulsive chasing.' },
  ], sources: [STRATEGY_SOURCES.methodology, STRATEGY_SOURCES.risk],
});

const swingPosition = createFoundationLesson({
  id: 'lesson.strategy.swing-position.001', slug: 'swing-ve-position-farki', conceptKey: 'strategy.swing_position', skillId: 'skill.strategy-design', competencyId: 'competency.swing-position.foundation',
  title: 'Swing ile position yaklaşımı nasıl ayrılır?', titleEn: 'How do swing and position approaches differ?',
  objective: 'Swing ve position yaklaşımını yalnız gün sayısıyla değil; karar ufku, veri sıklığı, beklenen hareket ve risk yönetimiyle ayırır.', objectiveEn: 'Differentiate swing and position approaches by decision horizon, evidence frequency, expected move, and risk management—not just days held.', minutes: 5,
  hook: 'Bir işlemi 10 gün tutmak onu otomatik olarak swing trade yapar mı?', hookEn: 'Does holding a trade for 10 days automatically make it a swing trade?',
  explanation: 'Swing yaklaşımı genellikle orta vadeli fiyat hareketlerini hedeflerken position yaklaşımı daha uzun süren temel veya teknik temalara dayanabilir. Fark yalnız takvim değildir; kullanılan kanıtın sıklığı, invalidation noktası ve pozisyonun hangi dalgalanmayı tolere edeceği de değişir.', explanationEn: 'Swing approaches often target medium-term price moves, while position approaches can rely on longer-lived fundamental or technical themes. The distinction is not just calendar time; evidence frequency, invalidation, and tolerated volatility differ.',
  proExplanation: 'Holding-period choice affects transaction cost, overnight/event exposure, stop distance, position size, financing and opportunity cost. Strategy horizon must be internally consistent.', proExplanationEn: 'Holding period affects transaction costs, event exposure, stop distance, sizing, financing, and opportunity cost. Strategy horizon must be internally consistent.',
  misconception: 'Yaygın hata: Stratejiyi yalnız “kaç gün tuttum?” sorusuyla sınıflandırmak.', misconceptionEn: 'Common mistake: classifying a strategy only by the number of days held.',
  takeaway: 'Zaman ufku; veri, risk ve invalidation mantığını birlikte değiştirir.', takeawayEn: 'Horizon changes evidence, risk, and invalidation together.',
  prerequisiteConceptKeys: ['strategy.horizon_objective'], relatedConceptKeys: ['market.technical.multi_timeframe', 'fundamental.analysis_limits', 'risk.position_sizing'],
  visualAlt: 'Swing ve position yaklaşımını karar sıklığı, veri türü ve risk toleransı sütunlarında karşılaştıran görsel', visualAltEn: 'Visual comparing swing and position approaches across decision frequency, evidence type, and risk tolerance',
  taskPrompt: 'Swing ve position ayrımında hangisi önemlidir?', taskPromptEn: 'What matters when distinguishing swing and position approaches?',
  taskChoices: [{ id: 'framework', label: 'Zaman ufku ile birlikte veri, invalidation ve risk yapısı', labelEn: 'Horizon together with evidence, invalidation, and risk structure' }, { id: 'days', label: 'Yalnız gün sayısı', labelEn: 'Only the number of days' }, { id: 'name', label: 'Varlığın adı', labelEn: 'The asset name' }], taskCorrectIds: ['framework'],
  questions: [
    { prompt: 'Swing ve position farkı yalnız süre midir?', promptEn: 'Is the swing-versus-position distinction only about duration?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Sadece hafta sonu', labelEn: 'Only on weekends' }], correctId: 'a', explanation: 'Karar kanıtı, risk ve invalidation da farklılaşır.', explanationEn: 'Evidence, risk, and invalidation also differ.' },
    { prompt: 'Daha uzun holding period neyi artırabilir?', promptEn: 'What can a longer holding period increase?', choices: [{ id: 'a', label: 'Event ve overnight riskine maruziyeti', labelEn: 'Exposure to event and overnight risk' }, { id: 'b', label: 'Kesinlik seviyesini', labelEn: 'Certainty' }, { id: 'c', label: 'Garantili getiriyi', labelEn: 'Guaranteed return' }], correctId: 'a', explanation: 'Daha uzun ufuk farklı olaylara maruz kalma süresini artırabilir.', explanationEn: 'Longer horizons can increase exposure to intervening events.' },
    { prompt: 'Horizon ile pozisyon boyutu ilişkili olabilir mi?', promptEn: 'Can horizon affect position sizing?', choices: [{ id: 'a', label: 'Evet; stop mesafesi ve tolere edilen dalgalanma değişebilir', labelEn: 'Yes; stop distance and tolerated volatility can change' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Sadece logoda', labelEn: 'Only in branding' }], correctId: 'a', explanation: 'Risk mimarisi seçilen ufukla tutarlı olmalıdır.', explanationEn: 'Risk architecture should match the chosen horizon.' },
  ], sources: [STRATEGY_SOURCES.methodology, STRATEGY_SOURCES.risk],
});

export const STRATEGY_FOUNDATION_LESSONS = [horizonObjective, trendFollowing, meanReversion, breakoutStrategy, momentumStrategy, swingPosition] as const;
