import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { TECHNICAL_ANALYSIS_SOURCES } from './technicalAnalysisSources';

const rsi = createFoundationLesson({
  id: 'lesson.technical.rsi.001',
  slug: 'rsi-ne-anlatir-ne-anlatmaz',
  conceptKey: 'market.technical.rsi',
  skillId: 'skill.technical-analysis',
  competencyId: 'competency.interpret-rsi.foundation',
  title: 'RSI ne anlatır, ne anlatmaz?',
  titleEn: 'What does RSI tell you—and what does it not tell you?',
  objective: 'RSI’ın momentumu nasıl özetlediğini ve 70/30 eşiklerinin neden tek başına sinyal olmadığını öğren.',
  objectiveEn: 'Explain RSI as an oscillator summarizing the relative speed and magnitude of recent price changes, and separate overbought/oversold labels from automatic direction signals.',
  minutes: 5,
  hook: 'RSI 70’in üstüne çıktıysa fiyat mutlaka düşmek zorunda mıdır?',
  hookEn: 'If RSI moves above 70, must price fall?',
  explanation: 'RSI, belirli bir dönemdeki yükseliş ve düşüşlerin göreli gücünü 0–100 arasında özetler. Güçlü trendlerde uzun süre yüksek veya düşük kalabilir. Bu yüzden 70 veya 30 seviyesi tek başına dönüş emri değildir; trend ve fiyat yapısıyla birlikte okunur.',
  explanationEn: 'RSI summarizes the relative strength of recent gains and losses on a 0–100 scale. High readings can reflect dominant upward moves and low readings dominant downward moves. In strong trends, RSI can remain high or low for extended periods. Thresholds such as 70 or 30 are therefore not automatic reversal commands; they are interpreted with trend, structure, volatility, and timeframe.',
  proExplanation: 'RSI periodu, smoothing yaklaşımı ve kullanılan fiyat serisi sonucu etkiler. Divergence gözlemleri de tek başına yön teyidi değildir; price structure ve regime ile birlikte değerlendirilmelidir.',
  proExplanationEn: 'RSI period, smoothing method, and input price series affect the result. Divergence observations are not standalone direction confirmation and should be assessed with price structure and regime.',
  misconception: '“70 üzeri sat, 30 altı al” gibi bağlamsız RSI kuralı kullanma.',
  misconceptionEn: 'Common mistake: using a fixed context-free rule such as “RSI above 70 = sell, below 30 = buy.”',
  takeaway: 'RSI momentumu özetler; tek başına dönüş sinyali değildir.',
  takeawayEn: 'RSI summarizes momentum; it does not provide a standalone reversal or trade instruction.',
  prerequisiteConceptKeys: ['market.technical.momentum', 'market.chart.timeframes'],
  relatedConceptKeys: ['market.technical.indicator_limits', 'market.trend.basics', 'risk.volatility'],
  visualAlt: 'Fiyat trendi sürerken RSI çizgisinin 70 üzerinde kalabildiğini gösteren sade fiyat ve osilatör grafiği',
  visualAltEn: 'Simple price-and-oscillator chart showing RSI remaining above 70 while a trend continues',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://academy/technical/rsi-001',
  taskPrompt: 'RSI 74 ve fiyat ana yükseliş yapısını koruyor. En temkinli yorum hangisidir?',
  taskPromptEn: 'RSI is 74 while price still preserves its broader uptrend structure. Which interpretation is most careful?',
  taskChoices: [
    { id: 'context', label: 'Momentum güçlü; dönüş için ayrıca yapı ve fiyat davranışı gerekir', labelEn: 'Momentum is strong; reversal still needs structural and price-behavior evidence' },
    { id: 'sell', label: 'Fiyat kesin düşecek', labelEn: 'Price will definitely fall' },
    { id: 'ignore', label: 'RSI hiçbir bilgi taşımaz', labelEn: 'RSI carries no information at all' },
  ],
  taskCorrectIds: ['context'],
  questions: [
    { prompt: 'RSI temel olarak neyi özetler?', promptEn: 'What does RSI primarily summarize?', choices: [{ id: 'a', label: 'Son fiyat değişimlerinin göreli gücünü', labelEn: 'The relative strength of recent price changes' }, { id: 'b', label: 'Gelecek fiyatı kesin olarak', labelEn: 'Future price with certainty' }, { id: 'c', label: 'Şirket bilançosunu', labelEn: 'A company balance sheet' }], correctId: 'a', explanation: 'RSI geçmiş fiyat hareketlerinden üretilen bir momentum osilatörüdür.', explanationEn: 'RSI is a momentum oscillator derived from past price changes.' },
    { prompt: 'RSI 70 üzeri her zaman trend dönüşü müdür?', promptEn: 'Is RSI above 70 always a trend reversal?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız günlük grafikte', labelEn: 'Only on daily charts' }], correctId: 'a', explanation: 'Güçlü trendlerde RSI uzun süre yüksek kalabilir.', explanationEn: 'RSI can remain elevated during strong trends.' },
    { prompt: 'RSI yorumunda hangi bağlam önemlidir?', promptEn: 'What context matters when interpreting RSI?', choices: [{ id: 'a', label: 'Trend, yapı, volatilite ve zaman dilimi', labelEn: 'Trend, structure, volatility, and timeframe' }, { id: 'b', label: 'Yalnız ekran rengi', labelEn: 'Only screen color' }, { id: 'c', label: 'Yalnız sembol uzunluğu', labelEn: 'Only ticker length' }], correctId: 'a', explanation: 'Osilatör değeri fiyat bağlamından ayrı okunmamalıdır.', explanationEn: 'An oscillator reading should not be interpreted independently of price context.' },
  ],
  sources: [TECHNICAL_ANALYSIS_SOURCES.indicators, TECHNICAL_ANALYSIS_SOURCES.methodology],
});

const macd = createFoundationLesson({
  id: 'lesson.technical.macd.001',
  slug: 'macd-ne-gosterir',
  conceptKey: 'market.technical.macd',
  skillId: 'skill.technical-analysis',
  competencyId: 'competency.interpret-macd.foundation',
  title: 'MACD ne gösterir?',
  titleEn: 'What does MACD show?',
  objective: 'MACD’nin iki hareketli ortalama arasındaki ilişkiyi nasıl özetlediğini öğren.',
  objectiveEn: 'Explain MACD as a lagging trend/momentum indicator summarizing the relationship between two moving averages and changes in that relationship.',
  minutes: 5,
  hook: 'MACD çizgileri kesişti diye trend aynı anda değişmiş sayılır mı?',
  hookEn: 'Does a MACD crossover mean the trend changed at that exact moment?',
  explanation: 'MACD, iki farklı hızdaki hareketli ortalama arasındaki farktan üretilir. Sinyal çizgisi ve histogram bu ilişkinin değişimini görünür kılar. Kesişimler momentum değişimine işaret edebilir ama gösterge geçmiş fiyattan üretildiği için gecikmelidir.',
  explanationEn: 'MACD is commonly derived from the difference between two exponential moving averages with different speeds. A signal line and histogram make changes in that relationship more visible. Crossovers can indicate a change in momentum relationships, but because MACD is built from past prices it lags. Without price structure, timeframe, and volatility context, it is not standalone direction confirmation.',
  proExplanation: 'MACD parametreleri tepki hızını değiştirir. Trendli ve yatay rejimlerde sinyal davranışı farklı olabilir; sık kesişimler whipsaw üretebilir. Histogramın küçülmesi momentum farkının daraldığını gösterir ama tek başına dönüş kanıtı değildir.',
  proExplanationEn: 'MACD parameters change reaction speed. Signal behavior differs in trending and ranging regimes, and frequent crossovers can produce whipsaws. A shrinking histogram shows the momentum spread narrowing but does not by itself prove a reversal.',
  misconception: 'Her MACD kesişimini kesin işlem sinyali sayma.',
  misconceptionEn: 'Common mistake: treating every MACD crossover as an independent and certain trade signal.',
  takeaway: 'MACD geçmiş fiyat ilişkisini özetler; kesişim bağlam ister.',
  takeawayEn: 'MACD summarizes past price relationships; crossovers require context and are lagging.',
  prerequisiteConceptKeys: ['market.technical.moving_average', 'market.technical.momentum'],
  relatedConceptKeys: ['market.technical.indicator_limits', 'market.technical.range', 'market.trend.basics'],
  visualAlt: 'Fiyatın altında MACD çizgisi, sinyal çizgisi ve histogramın birlikte gösterildiği sade teknik analiz şeması',
  visualAltEn: 'Simple technical-analysis diagram showing price with MACD line, signal line, and histogram below',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://academy/technical/macd-001',
  taskPrompt: 'Yatay piyasada çok sık MACD kesişimi görülüyorsa hangi risk artar?',
  taskPromptEn: 'If MACD crossovers occur very frequently in a range, what risk increases?',
  taskChoices: [
    { id: 'whipsaw', label: 'Whipsaw ve sık yanlış teyit', labelEn: 'Whipsaw and frequent false confirmation' },
    { id: 'certainty', label: 'Kesin yön bilgisi', labelEn: 'Certain direction information' },
    { id: 'none', label: 'Gösterge artık gecikmez', labelEn: 'The indicator no longer lags' },
  ],
  taskCorrectIds: ['whipsaw'],
  questions: [
    { prompt: 'MACD hangi veri türünden türetilir?', promptEn: 'What type of data is MACD derived from?', choices: [{ id: 'a', label: 'Geçmiş fiyat ve hareketli ortalama ilişkilerinden', labelEn: 'Past price and moving-average relationships' }, { id: 'b', label: 'Gelecekteki kesin fiyatlardan', labelEn: 'Certain future prices' }, { id: 'c', label: 'Yalnız bilanço verisinden', labelEn: 'Only balance-sheet data' }], correctId: 'a', explanation: 'MACD geçmiş fiyat serisinden türetilen ortalama farklarını kullanır.', explanationEn: 'MACD uses moving-average differences derived from past prices.' },
    { prompt: 'MACD kesişimi tek başına trend dönüşünü kanıtlar mı?', promptEn: 'Does a MACD crossover alone prove a trend reversal?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız histogram pozitifse', labelEn: 'Only if the histogram is positive' }], correctId: 'a', explanation: 'Fiyat yapısı ve rejim ayrıca değerlendirilmelidir.', explanationEn: 'Price structure and market regime still need assessment.' },
    { prompt: 'MACD neden gecikmeli sayılır?', promptEn: 'Why is MACD considered lagging?', choices: [{ id: 'a', label: 'Geçmiş fiyatlardan hesaplandığı için', labelEn: 'Because it is calculated from past prices' }, { id: 'b', label: 'İnternete bağlı olmadığı için', labelEn: 'Because it is not connected to the internet' }, { id: 'c', label: 'Sadece günlük grafikte çalıştığı için', labelEn: 'Because it only works on daily charts' }], correctId: 'a', explanation: 'Hesaplama geçmiş veriyi işler; fiyat hareketinden sonra tepki verir.', explanationEn: 'The calculation processes historical data and reacts after price moves.' },
  ],
  sources: [TECHNICAL_ANALYSIS_SOURCES.indicators, TECHNICAL_ANALYSIS_SOURCES.methodology],
});

const multiTimeframe = createFoundationLesson({
  id: 'lesson.technical.multi-timeframe.001',
  slug: 'coklu-zaman-dilimi-nasil-kullanilir',
  conceptKey: 'market.technical.multi_timeframe',
  skillId: 'skill.technical-analysis',
  competencyId: 'competency.apply-multi-timeframe.foundation',
  title: 'Çoklu zaman dilimi nasıl kullanılır?',
  titleEn: 'How do you use multiple timeframes?',
  objective: 'Farklı zaman dilimlerinin aynı piyasayı neden farklı gösterdiğini ve rollerini ayırmayı öğren.',
  objectiveEn: 'Separate higher-timeframe context from lower-timeframe detail and avoid treating different structures across scales as contradictions.',
  minutes: 5,
  hook: 'Günlük grafik yükseliş, 15 dakikalık grafik düşüş gösteriyorsa hangisi doğrudur?',
  hookEn: 'If the daily chart trends up while the 15-minute chart trends down, which one is correct?',
  explanation: 'Farklı zaman dilimleri aynı fiyatı farklı ölçekte gösterir. Geniş zaman dilimi ana yapıyı, kısa zaman dilimi iç hareketleri gösterir. Günlük yükseliş içinde 15 dakikalık düşüş yalnız pullback olabilir. Her zaman dilimine ayrı rol vermek gerekir.',
  explanationEn: 'Different timeframes aggregate the same price series at different scales. Higher timeframes can show broader structure and context while lower timeframes show smaller movements inside that structure. A 15-minute decline can therefore be a pullback inside a daily uptrend. Multi-timeframe analysis means assigning each timeframe a role instead of copying one label across all of them.',
  proExplanation: 'Top-down analizde timeframe oranı ve seçilen execution horizon kullanım amacına göre değişir. Çok fazla zaman dilimi eklemek information overload ve contradictory labeling riski yaratabilir.',
  proExplanationEn: 'In top-down analysis, timeframe ratios and the chosen execution horizon depend on purpose. Adding too many timeframes can create information overload and contradictory labeling.',
  misconception: 'Kısa zaman dilimindeki her ters hareketi ana trend değişimi sayma.',
  misconceptionEn: 'Common mistake: treating every lower-timeframe counter-move as a higher-timeframe structural change or expecting every timeframe to show the same direction.',
  takeaway: 'Önce geniş bağlamı, sonra kısa zaman dilimindeki iç yapıyı oku.',
  takeawayEn: 'Timeframes are different scales; read broad context first, then internal structure.',
  prerequisiteConceptKeys: ['market.chart.timeframes', 'market.trend.basics'],
  relatedConceptKeys: ['market.technical.pullback', 'market.timeframe.alignment', 'market.structure.choch'],
  visualAlt: 'Aynı varlığın günlük, saatlik ve 15 dakikalık yapılarının iç içe gösterildiği sade çoklu zaman dilimi şeması',
  visualAltEn: 'Simple multi-timeframe diagram nesting daily, hourly, and 15-minute structures of the same asset',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://academy/technical/multi-timeframe-001',
  taskPrompt: '1D yükseliş yapısı korunurken 15m düşüyorsa en doğru ilk yorum hangisidir?',
  taskPromptEn: 'If the daily uptrend remains intact while the 15-minute chart declines, what is the best first interpretation?',
  taskChoices: [
    { id: 'scale', label: 'Kısa zaman diliminde karşı hareket olabilir; geniş yapıyı ayrıca kontrol et', labelEn: 'It may be a lower-timeframe counter-move; check the broader structure separately' },
    { id: 'reverse', label: 'Günlük trend kesin bitmiştir', labelEn: 'The daily trend has definitely ended' },
    { id: 'same', label: 'Tüm zaman dilimleri aynı görünmek zorundadır', labelEn: 'All timeframes must look the same' },
  ],
  taskCorrectIds: ['scale'],
  questions: [
    { prompt: 'Farklı zaman dilimleri neden farklı yapı gösterebilir?', promptEn: 'Why can different timeframes show different structures?', choices: [{ id: 'a', label: 'Aynı fiyatı farklı ölçeklerde topladıkları için', labelEn: 'Because they aggregate the same price at different scales' }, { id: 'b', label: 'Farklı varlıkları gösterdikleri için', labelEn: 'Because they show different assets' }, { id: 'c', label: 'Biri her zaman hatalı olduğu için', labelEn: 'Because one is always wrong' }], correctId: 'a', explanation: 'Ölçek değiştikçe görünen salınım yapısı değişebilir.', explanationEn: 'Visible swing structure can change as scale changes.' },
    { prompt: '15m düşüş, 1D yükseliş yapısını otomatik bozar mı?', promptEn: 'Does a 15-minute decline automatically invalidate a daily uptrend?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız hacim yüksekse', labelEn: 'Only if volume is high' }], correctId: 'a', explanation: 'Ana yapının kritik seviyeleri ayrı değerlendirilir.', explanationEn: 'Key levels of the broader structure are assessed separately.' },
    { prompt: 'Çoklu zaman dilimi analizinde ilk amaç nedir?', promptEn: 'What is the first goal of multi-timeframe analysis?', choices: [{ id: 'a', label: 'Her ölçeğin rolünü ve bağlamını ayırmak', labelEn: 'Separate each scale’s role and context' }, { id: 'b', label: 'En fazla grafik açmak', labelEn: 'Open as many charts as possible' }, { id: 'c', label: 'Her grafikten aynı sinyali almak', labelEn: 'Get the same signal from every chart' }], correctId: 'a', explanation: 'Amaç bilgi çoğaltmak değil, ölçekleri düzenli biçimde ilişkilendirmektir.', explanationEn: 'The goal is not to multiply information but to relate scales coherently.' },
  ],
  sources: [TECHNICAL_ANALYSIS_SOURCES.charting, TECHNICAL_ANALYSIS_SOURCES.methodology],
});

const patterns = createFoundationLesson({
  id: 'lesson.technical.patterns.001',
  slug: 'formasyonlar-neden-kesin-degildir',
  conceptKey: 'market.technical.patterns',
  skillId: 'skill.technical-analysis',
  competencyId: 'competency.interpret-patterns.foundation',
  title: 'Grafik formasyonları neden kesin değildir?',
  titleEn: 'Why are chart patterns not certain?',
  objective: 'Grafik formasyonlarının neden gözlem çerçevesi olduğunu ve sonucu garanti etmediğini öğren.',
  objectiveEn: 'Explain chart patterns as recurring price geometries and distinguish visual similarity from certain prediction or standalone trade signals.',
  minutes: 5,
  hook: 'Grafikte “üçgen” gördüğün anda yönü biliyor musun?',
  hookEn: 'Do you know the future direction the moment you see a “triangle” on a chart?',
  explanation: 'Formasyonlar, fiyatın oluşturduğu tekrar eden geometrik yapılara verilen isimlerdir. Üçgen, bayrak veya çift tepe gibi etiketler gözlemi düzenler. Aynı şekil farklı piyasa koşullarında farklı sonuçlanabilir; önceki trend, volatilite ve kırılım davranışıyla birlikte okunmalıdır.',
  explanationEn: 'Chart patterns are names for recurring geometric structures formed by price over time. Labels such as triangles, flags, head-and-shoulders, or double tops can organize observation. But the same shape can resolve differently across market regimes. Pattern boundaries, prior trend, volatility, volume, breakout behavior, and timeframe should be assessed together.',
  proExplanation: 'Pattern tanımları subjektif olabilir ve hindsight bias riski taşır. Sistematik kullanımda formasyon kriterleri önceden tanımlanmalı, örnek dışı test edilmeli ve işlem maliyetleriyle birlikte değerlendirilmelidir.',
  proExplanationEn: 'Pattern definitions can be subjective and prone to hindsight bias. Systematic use requires predefined criteria, out-of-sample testing, and evaluation with trading costs.',
  misconception: 'Formasyonu gördün diye beklenen hedefin kesin gerçekleşeceğini sanma.',
  misconceptionEn: 'Common mistake: assuming a projected target will automatically occur once a pattern is recognized.',
  takeaway: 'Formasyon gözlem çerçevesidir; sonuç garantisi değildir.',
  takeawayEn: 'A pattern is an observation framework; it does not guarantee an outcome and requires context.',
  prerequisiteConceptKeys: ['market.structure.support_resistance', 'market.technical.range'],
  relatedConceptKeys: ['market.technical.breakout', 'market.volume.basics', 'market.technical.indicator_limits'],
  visualAlt: 'Aynı üçgen benzeri fiyat yapısının yukarı, aşağı ve başarısız kırılım örnekleriyle karşılaştırıldığı sade grafik',
  visualAltEn: 'Simple chart comparing upward, downward, and failed resolutions of a similar triangle-like structure',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://academy/technical/patterns-001',
  taskPrompt: 'Aynı formasyon şekli iki farklı grafikte görülüyorsa ne varsayılmalıdır?',
  taskPromptEn: 'If the same pattern shape appears on two different charts, what should be assumed?',
  taskChoices: [
    { id: 'context', label: 'Sonuç aynı olmak zorunda değildir; bağlam ayrıca değerlendirilir', labelEn: 'The outcome does not have to match; context is assessed separately' },
    { id: 'same', label: 'İki grafik kesin aynı yönde gider', labelEn: 'Both charts will definitely move in the same direction' },
    { id: 'target', label: 'Hedef otomatik gerçekleşir', labelEn: 'The target is automatic' },
  ],
  taskCorrectIds: ['context'],
  questions: [
    { prompt: 'Grafik formasyonu en iyi nasıl tanımlanır?', promptEn: 'How is a chart pattern best described?', choices: [{ id: 'a', label: 'Tekrar eden fiyat geometrisini düzenleyen gözlem etiketi', labelEn: 'An observation label organizing recurring price geometry' }, { id: 'b', label: 'Kesin gelecek tahmini', labelEn: 'A certain future prediction' }, { id: 'c', label: 'Şirket değerlemesi', labelEn: 'A company valuation' }], correctId: 'a', explanation: 'Formasyon fiyat yapısını sınıflandırır; kesin sonuç vermez.', explanationEn: 'A pattern classifies price structure; it does not provide certainty.' },
    { prompt: 'Formasyon sonucunu hangi bağlam etkileyebilir?', promptEn: 'What context can affect a pattern’s outcome?', choices: [{ id: 'a', label: 'Trend, volatilite, hacim ve breakout davranışı', labelEn: 'Trend, volatility, volume, and breakout behavior' }, { id: 'b', label: 'Yalnız çizginin rengi', labelEn: 'Only line color' }, { id: 'c', label: 'Yalnız pattern adı', labelEn: 'Only the pattern name' }], correctId: 'a', explanation: 'Aynı geometrinin farklı bağlamlarda farklı sonucu olabilir.', explanationEn: 'The same geometry can resolve differently in different contexts.' },
    { prompt: 'Pattern hedefi garanti midir?', promptEn: 'Is a pattern target guaranteed?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız günlük grafikte', labelEn: 'Only on daily charts' }], correctId: 'a', explanation: 'Hedefler metodolojik projeksiyonlardır; kesin sonuç değildir.', explanationEn: 'Targets are methodological projections, not certain outcomes.' },
  ],
  sources: [TECHNICAL_ANALYSIS_SOURCES.charting, TECHNICAL_ANALYSIS_SOURCES.methodology],
});

const confluence = createFoundationLesson({
  id: 'lesson.technical.confluence.001',
  slug: 'confluence-nedir',
  conceptKey: 'market.technical.confluence',
  skillId: 'skill.technical-analysis',
  competencyId: 'competency.assess-confluence.foundation',
  title: 'Confluence nedir?',
  titleEn: 'What is confluence?',
  objective: 'Confluence’ın kanıt sayısı değil, kanıt çeşitliliği olduğunu öğren.',
  objectiveEn: 'Explain confluence as evaluating independent evidence that supports the same interpretation, while avoiding counting indicators derived from the same data as independent evidence.',
  minutes: 5,
  hook: 'RSI, MACD ve iki hareketli ortalama aynı şeyi söylüyorsa dört ayrı kanıtın mı var?',
  hookEn: 'If RSI, MACD, and two moving averages say the same thing, do you have four independent pieces of evidence?',
  explanation: 'Confluence, farklı kanıtların aynı yorumu desteklemesidir. RSI, MACD ve hareketli ortalama aynı fiyat verisinden türediği için tamamen bağımsız değildir. Fiyat yapısı, hacim veya farklı veri türleri birlikte değerlendirildiğinde kanıt çeşitliliği artar; kesinlik yine oluşmaz.',
  explanationEn: 'Confluence means multiple meaningful pieces of evidence supporting the same market interpretation. But evidence counts should not be inflated. RSI, MACD, and moving averages are all derived from the same price series, so they are not fully independent. Evidence diversity can improve when price structure, timeframe, volume, volatility, and different data types support one another. Multiple evidence does not create certainty; it helps assess robustness.',
  proExplanation: 'Feature redundancy ve correlated evidence, model confidence veya discretionary conviction’ın yapay biçimde yükselmesine neden olabilir. Kanıtları kaynak ve mekanizma bakımından gruplamak double-counting riskini azaltır.',
  proExplanationEn: 'Feature redundancy and correlated evidence can artificially inflate model confidence or discretionary conviction. Grouping evidence by source and mechanism reduces double-counting risk.',
  misconception: 'Aynı fiyat serisinden çıkan beş indikatörü beş bağımsız kanıt sayma.',
  misconceptionEn: 'Common mistake: counting five indicators derived from the same price series as five independent pieces of evidence.',
  takeaway: 'Confluence gösterge sayısı değil, kanıt çeşitliliğidir.',
  takeawayEn: 'Confluence is evidence diversity, not indicator count, and it does not create certainty.',
  prerequisiteConceptKeys: ['evidence.data_quality', 'market.technical.momentum'],
  relatedConceptKeys: ['market.technical.rsi', 'market.technical.macd', 'market.volume.basics'],
  visualAlt: 'Fiyat yapısı, hacim ve volatilite gibi farklı kaynakların ortak yoruma bağlandığı; benzer indikatörlerin aynı kaynak grubunda gösterildiği sade kanıt şeması',
  visualAltEn: 'Simple evidence diagram where price structure, volume, and volatility converge while similar indicators are grouped under the same source',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/technical/confluence-001',
  taskPrompt: 'Hangi kombinasyon daha çeşitli kanıt içerir?',
  taskPromptEn: 'Which combination contains more diverse evidence?',
  taskChoices: [
    { id: 'diverse', label: 'Fiyat yapısı + hacim + volatilite bağlamı', labelEn: 'Price structure + volume + volatility context' },
    { id: 'same', label: 'RSI + MACD + üç farklı hareketli ortalama', labelEn: 'RSI + MACD + three moving averages' },
    { id: 'none', label: 'Yalnız tek mum rengi', labelEn: 'Only one candle color' },
  ],
  taskCorrectIds: ['diverse'],
  questions: [
    { prompt: 'Confluence neyi ifade eder?', promptEn: 'What does confluence mean?', choices: [{ id: 'a', label: 'Farklı anlamlı kanıtların aynı yorumu desteklemesini', labelEn: 'Different meaningful evidence supporting the same interpretation' }, { id: 'b', label: 'En fazla indikatörü ekrana koymayı', labelEn: 'Putting the most indicators on screen' }, { id: 'c', label: 'Kesin sonuç elde etmeyi', labelEn: 'Obtaining certainty' }], correctId: 'a', explanation: 'Confluence’ın değeri kanıt çeşitliliğinden gelir.', explanationEn: 'The value of confluence comes from evidence diversity.' },
    { prompt: 'RSI ve MACD tamamen bağımsız kanıt mıdır?', promptEn: 'Are RSI and MACD fully independent evidence?', choices: [{ id: 'a', label: 'Hayır; ikisi de fiyat verisinden türetilir', labelEn: 'No; both are derived from price data' }, { id: 'b', label: 'Evet; her zaman tamamen bağımsızdır', labelEn: 'Yes; they are always fully independent' }, { id: 'c', label: 'Yalnız kriptoda bağımsızdır', labelEn: 'Only in crypto' }], correctId: 'a', explanation: 'Aynı temel veri kaynağı aralarında korelasyon yaratabilir.', explanationEn: 'The same underlying data source can create correlation between them.' },
    { prompt: 'Confluence kesinlik sağlar mı?', promptEn: 'Does confluence provide certainty?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Üçten fazla gösterge varsa', labelEn: 'If there are more than three indicators' }], correctId: 'a', explanation: 'Çoklu kanıt belirsizliği ortadan kaldırmaz.', explanationEn: 'Multiple evidence does not eliminate uncertainty.' },
  ],
  sources: [TECHNICAL_ANALYSIS_SOURCES.methodology, TECHNICAL_ANALYSIS_SOURCES.indicators],
});

const indicatorLimits = createFoundationLesson({
  id: 'lesson.technical.indicator-limits.001',
  slug: 'indikatorlerin-sinirlari',
  conceptKey: 'market.technical.indicator_limits',
  skillId: 'skill.technical-analysis',
  competencyId: 'competency.explain-indicator-limits.foundation',
  title: 'İndikatörlerin sınırları nelerdir?',
  titleEn: 'What are the limits of technical indicators?',
  objective: 'İndikatörlerin neden yeni bilgi yaratmaktan çok veriyi yeniden özetlediğini öğren.',
  objectiveEn: 'Explain that most technical indicators transform price/volume data and carry lag, parameter sensitivity, regime dependence, and overfitting risks.',
  minutes: 5,
  hook: 'Aynı grafiğe daha fazla indikatör eklemek analizi otomatik olarak daha doğru yapar mı?',
  hookEn: 'Does adding more indicators automatically make analysis more accurate?',
  explanation: 'İndikatörler çoğunlukla fiyat ve hacmi farklı biçimde özetler. Parametre değişince sonuç değişebilir; trendli piyasada işe yarayan yorum yatay piyasada zayıflayabilir. Geçmişe aşırı uyarlanmış ayarlar da gelecekte bozulabilir.',
  explanationEn: 'Technical indicators are usually calculated from price, volume, or transformations of them. They often summarize existing data in a different way rather than creating new information. Parameter changes can alter results; an interpretation that works in a trend may fail frequently in a range. Settings overfit to historical data can also weaken in the future. Indicators are observation tools and do not remove the need for context, risk assessment, and independent evidence.',
  proExplanation: 'Look-ahead bias, survivorship bias, parameter mining ve data-snooping, indikatör tabanlı stratejilerin geçmiş performansını olduğundan güçlü gösterebilir. Robustness farklı dönem, varlık ve maliyet varsayımlarında test edilmelidir.',
  proExplanationEn: 'Look-ahead bias, survivorship bias, parameter mining, and data snooping can make indicator-based historical performance look stronger than it is. Robustness should be tested across periods, assets, and cost assumptions.',
  misconception: 'Daha fazla indikatörü otomatik olarak daha fazla bilgi sanma.',
  misconceptionEn: 'Common mistake: assuming more indicators automatically provide more independent information and higher accuracy.',
  takeaway: 'İndikatör veriyi özetler; bağlam ve gecikme sınırları vardır.',
  takeawayEn: 'Indicators transform data; they have lag and context limits and do not create certainty.',
  prerequisiteConceptKeys: ['market.technical.rsi', 'market.technical.macd', 'market.technical.moving_average'],
  relatedConceptKeys: ['market.technical.confluence', 'evidence.data_quality', 'behavior.confirmation_bias'],
  visualAlt: 'Aynı fiyat serisinden RSI, MACD ve hareketli ortalama dallarının çıktığını; hepsinin ortak veri kaynağına bağlı olduğunu gösteren sade şema',
  visualAltEn: 'Simple diagram showing RSI, MACD, and moving averages branching from the same price series and sharing a common data source',
  taskKind: 'scenario_choice',
  taskAssetRef: 'edu://academy/technical/indicator-limits-001',
  taskPrompt: 'Bir strateji yalnız geçmiş veride mükemmel, farklı dönemde zayıf çalışıyorsa hangi risk düşünülmelidir?',
  taskPromptEn: 'If a strategy looks perfect only on historical data but weakens in another period, what risk should you consider?',
  taskChoices: [
    { id: 'overfit', label: 'Overfitting / parametre madenciliği', labelEn: 'Overfitting / parameter mining' },
    { id: 'certainty', label: 'Kesin gelecek tahmini', labelEn: 'Certain future prediction' },
    { id: 'none', label: 'Hiçbir risk yok', labelEn: 'There is no risk' },
  ],
  taskCorrectIds: ['overfit'],
  questions: [
    { prompt: 'Teknik indikatörlerin çoğu hangi veriyi işler?', promptEn: 'What data do most technical indicators process?', choices: [{ id: 'a', label: 'Fiyat, hacim veya bunların türevlerini', labelEn: 'Price, volume, or transformations of them' }, { id: 'b', label: 'Gelecekteki kesin fiyatı', labelEn: 'Certain future prices' }, { id: 'c', label: 'Yalnız şirket adresini', labelEn: 'Only a company address' }], correctId: 'a', explanation: 'İndikatörler çoğunlukla mevcut piyasa verisinin matematiksel dönüşümleridir.', explanationEn: 'Indicators are usually mathematical transformations of existing market data.' },
    { prompt: 'Parametre değiştirmek sonucu etkileyebilir mi?', promptEn: 'Can changing parameters affect indicator output?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır, asla', labelEn: 'No, never' }, { id: 'c', label: 'Yalnız hisse senedinde', labelEn: 'Only in stocks' }], correctId: 'a', explanation: 'Pencere ve smoothing gibi ayarlar tepki hızını ve sinyalleri değiştirebilir.', explanationEn: 'Window and smoothing settings can change response speed and signals.' },
    { prompt: 'Daha fazla indikatör otomatik daha fazla bağımsız bilgi midir?', promptEn: 'Do more indicators automatically mean more independent information?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız üçten fazlaysa', labelEn: 'Only if there are more than three' }], correctId: 'a', explanation: 'Birçok indikatör aynı temel veri kaynağından türediği için bilgi tekrarına yol açabilir.', explanationEn: 'Many indicators share the same underlying data source and can duplicate information.' },
  ],
  sources: [TECHNICAL_ANALYSIS_SOURCES.indicators, TECHNICAL_ANALYSIS_SOURCES.methodology],
});

export const TECHNICAL_ANALYSIS_EXPANSION_LESSONS = [
  rsi,
  macd,
  multiTimeframe,
  patterns,
  confluence,
  indicatorLimits,
] as const;
