import { createFoundationLesson } from '../wave1/foundationLessonFactory';
import { TECHNICAL_ANALYSIS_SOURCES } from './technicalAnalysisSources';

const breakout = createFoundationLesson({
  id: 'lesson.technical.breakout.001',
  slug: 'breakout-ne-zaman-anlamli',
  conceptKey: 'market.technical.breakout',
  skillId: 'skill.technical-analysis',
  competencyId: 'competency.assess-breakout.foundation',
  title: 'Breakout ne zaman daha anlamlıdır?',
  titleEn: 'When is a breakout more meaningful?',
  objective: 'Breakout ile kısa süreli seviye taşmasını ayırt etmeyi öğren.',
  objectiveEn: 'Explain a breakout as price moving beyond an important area and distinguish a brief overshoot from stronger confirmation.',
  minutes: 5,
  hook: 'Fiyat direncin bir an üstüne çıktı diye breakout kesinleşmiş midir?',
  hookEn: 'If price briefly moves above resistance, is the breakout confirmed?',
  explanation: 'Breakout, fiyatın önemli bir bölgenin dışına çıkmasıdır. Kısa bir fitil veya küçük taşma tek başına yeterli değildir. Kapanış, devam davranışı, zaman dilimi ve gerekiyorsa hacim birlikte değerlendirilir.',
  explanationEn: 'A breakout occurs when price moves beyond an important area that previously attracted reactions. A brief wick or small overshoot may not be enough. The area’s significance, close, follow-through, volume context, and timeframe are assessed together. A breakout is an observation, not a guarantee of future direction.',
  proExplanation: 'Breakout değerlendirmesinde volatility regime, liquidity conditions, range duration ve acceptance beyond the level gibi faktörler kanıt kalitesini değiştirebilir. Tek bir eşik evrensel değildir.',
  proExplanationEn: 'Volatility regime, liquidity conditions, range duration, and acceptance beyond the level can change breakout quality. No single threshold is universal.',
  misconception: 'Seviyenin üzerindeki her kısa taşmayı teyitli breakout sayma.',
  misconceptionEn: 'Common mistake: treating every wick or brief move beyond a level as a confirmed breakout.',
  takeaway: 'Kırılımı, seviye + kapanış + devam davranışıyla değerlendir.',
  takeawayEn: 'A breakout is not just crossing a level; it is assessed through context and behavior beyond an important area.',
  prerequisiteConceptKeys: ['market.structure.support_resistance', 'market.trend.basics'],
  relatedConceptKeys: ['market.technical.false_breakout', 'market.volume.basics', 'risk.volatility'],
  visualAlt: 'Direnç alanı üzerinde kısa fitil taşması ile kapanış ve devam gösteren breakout’u karşılaştıran sade grafik',
  visualAltEn: 'Simple chart comparing a brief wick above resistance with a breakout showing a close and follow-through',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://academy/technical/breakout-001',
  taskPrompt: 'Hangi örnek daha güçlü breakout kanıtı taşır?',
  taskPromptEn: 'Which example provides stronger breakout evidence?',
  taskChoices: [
    { id: 'accepted', label: 'Önemli bölge üzerinde kapanış ve devam davranışı', labelEn: 'A close above an important area with follow-through' },
    { id: 'wick', label: 'Bölge üzerindeki tek kısa fitil', labelEn: 'One brief wick above the area' },
    { id: 'middle', label: 'Aralığın ortasında rastgele hareket', labelEn: 'A random move in the middle of the range' },
  ],
  taskCorrectIds: ['accepted'],
  questions: [
    { prompt: 'Breakout değerlendirmesinde hangisi daha anlamlıdır?', promptEn: 'What is more meaningful when assessing a breakout?', choices: [{ id: 'a', label: 'Seviyenin önemi ve kırılım sonrası davranış', labelEn: 'The importance of the level and behavior after the break' }, { id: 'b', label: 'Yalnız mumun rengi', labelEn: 'Only candle color' }, { id: 'c', label: 'Yalnız grafiğin yakınlaştırma düzeyi', labelEn: 'Only chart zoom level' }], correctId: 'a', explanation: 'Kırılımın bağlamı ve kabul davranışı tek taşmadan daha güçlü kanıt sağlar.', explanationEn: 'Context and acceptance provide stronger evidence than a brief overshoot.' },
    { prompt: 'Tek fitil her zaman teyitli breakout mudur?', promptEn: 'Is one wick always a confirmed breakout?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız yüksek hacimde', labelEn: 'Only at high volume' }], correctId: 'a', explanation: 'Fitil geçici taşma olabilir; kapanış ve bağlam ayrıca değerlendirilir.', explanationEn: 'A wick can be temporary; close and context should also be assessed.' },
    { prompt: 'Breakout gelecek yönü garanti eder mi?', promptEn: 'Does a breakout guarantee future direction?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Her zaman evet', labelEn: 'Always yes' }, { id: 'c', label: 'Yalnız günlük grafikte', labelEn: 'Only on daily charts' }], correctId: 'a', explanation: 'Breakout piyasa gözlemidir, kesin sonuç değildir.', explanationEn: 'A breakout is a market observation, not certainty.' },
  ],
  sources: [TECHNICAL_ANALYSIS_SOURCES.charting, TECHNICAL_ANALYSIS_SOURCES.methodology],
});

const falseBreakout = createFoundationLesson({
  id: 'lesson.technical.false-breakout.001',
  slug: 'false-breakout-nasil-okunur',
  conceptKey: 'market.technical.false_breakout',
  skillId: 'skill.technical-analysis',
  competencyId: 'competency.recognize-false-breakout.foundation',
  title: 'False breakout nasıl okunur?',
  titleEn: 'How do you read a false breakout?',
  objective: 'False breakout ile sürdürülen kırılımı ayırt etmeyi öğren.',
  objectiveEn: 'Recognize a move beyond a level followed by a quick return into the prior area as false-breakout context.',
  minutes: 5,
  hook: 'Fiyat direnci kırdıktan hemen sonra tekrar aralığın içine dönerse ne olmuş olabilir?',
  hookEn: 'What may have happened if price breaks resistance and quickly returns inside the prior range?',
  explanation: 'False breakout, fiyatın seviyeyi aştıktan sonra hareketi sürdüremeyip eski bölgenin içine dönmesidir. Geri dönüşün hızı ve kapanış yeri önemlidir. Bu davranış kırılımın başarısız kaldığını gösterebilir ama ters yönü garanti etmez.',
  explanationEn: 'A false breakout occurs when price moves beyond an important level but fails to sustain that move and returns inside the prior area. The speed of the return, closing location, timeframe, and liquidity conditions matter. This can be evidence that the breakout failed, but it is not an automatic opposite-direction signal.',
  proExplanation: 'Failed auction, liquidity sweep ve stop-triggered excursion gibi açıklamalar kullanılan metodolojiye göre değişebilir. Etiket yerine gerçekleşen fiyat davranışı ve acceptance/rejection kanıtı önceliklendirilmelidir.',
  proExplanationEn: 'Interpretations such as failed auction, liquidity sweep, or stop-triggered excursion depend on methodology. Observable price behavior and acceptance/rejection should take priority over labels.',
  misconception: 'Her başarısız breakout’u otomatik ters yön sinyali sayma.',
  misconceptionEn: 'Common mistake: treating every failed breakout as a certain opposite-direction opportunity.',
  takeaway: 'False breakout, başarısız kırılımı gösterir; yeni yönü garanti etmez.',
  takeawayEn: 'A false breakout shows that the break was not sustained; it does not prove a new direction with certainty.',
  prerequisiteConceptKeys: ['market.technical.breakout'],
  relatedConceptKeys: ['market.structure.liquidity', 'market.technical.range', 'risk.volatility'],
  visualAlt: 'Direnç üstüne taşan fiyatın yeniden aralık içine dönmesini gösteren sade false-breakout şeması',
  visualAltEn: 'Simple false-breakout diagram showing price moving above resistance and returning inside the range',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://academy/technical/false-breakout-001',
  taskPrompt: 'Hangi davranış false breakout için daha güçlü kanıttır?',
  taskPromptEn: 'Which behavior is stronger evidence of a false breakout?',
  taskChoices: [
    { id: 'return', label: 'Kırılan bölgenin dışına çıkıp hızlı biçimde tekrar içine kapanmak', labelEn: 'Move beyond the area and quickly close back inside it' },
    { id: 'continue', label: 'Bölge dışında kalıp devam etmek', labelEn: 'Remain outside the area and continue' },
    { id: 'middle', label: 'Seviyeye hiç yaklaşmamak', labelEn: 'Never approach the level' },
  ],
  taskCorrectIds: ['return'],
  questions: [
    { prompt: 'False breakout en temel olarak neyi anlatır?', promptEn: 'What does a false breakout fundamentally describe?', choices: [{ id: 'a', label: 'Kırılımın sürdürülemeyip önceki alana geri dönmesini', labelEn: 'A break failing to sustain and returning to the prior area' }, { id: 'b', label: 'Kesin trend dönüşünü', labelEn: 'A certain trend reversal' }, { id: 'c', label: 'Yalnız hacim düşüşünü', labelEn: 'Only lower volume' }], correctId: 'a', explanation: 'Temel gözlem, fiyatın bölge dışındaki hareketi koruyamamasıdır.', explanationEn: 'The core observation is failure to maintain the move outside the area.' },
    { prompt: 'False breakout otomatik ters yön sinyali midir?', promptEn: 'Is a false breakout an automatic opposite-direction signal?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız 5 dakikalık grafikte', labelEn: 'Only on a 5-minute chart' }], correctId: 'a', explanation: 'Yeni yön için ek yapı ve devam kanıtı gerekir.', explanationEn: 'A new direction requires additional structural and follow-through evidence.' },
    { prompt: 'Hangi bilgi false breakout yorumuna yardımcı olur?', promptEn: 'What information helps interpret a false breakout?', choices: [{ id: 'a', label: 'Kapanış yeri ve geri dönüş davranışı', labelEn: 'Closing location and return behavior' }, { id: 'b', label: 'Yalnız sembol adı', labelEn: 'Only the ticker name' }, { id: 'c', label: 'Yalnız arka plan rengi', labelEn: 'Only background color' }], correctId: 'a', explanation: 'Acceptance/rejection davranışı kırılımın kalitesini anlamaya yardım eder.', explanationEn: 'Acceptance and rejection behavior help assess the quality of the break.' },
  ],
  sources: [TECHNICAL_ANALYSIS_SOURCES.charting, TECHNICAL_ANALYSIS_SOURCES.methodology],
});

const pullback = createFoundationLesson({
  id: 'lesson.technical.pullback.001',
  slug: 'pullback-trend-donusu-degildir',
  conceptKey: 'market.technical.pullback',
  skillId: 'skill.technical-analysis',
  competencyId: 'competency.distinguish-pullback.foundation',
  title: 'Pullback neden trend dönüşüyle aynı şey değildir?',
  titleEn: 'Why is a pullback not the same as a trend reversal?',
  objective: 'Pullback ile gerçek trend dönüşünü ayırt etmeyi öğren.',
  objectiveEn: 'Distinguish a temporary counter-direction move within an intact broader structure from a trend reversal.',
  minutes: 5,
  hook: 'Yükseliş trendinde fiyat birkaç mum düştü diye trend bitmiş midir?',
  hookEn: 'If price falls for a few candles during an uptrend, has the trend ended?',
  explanation: 'Pullback, ana trend yapısı korunurken oluşan geçici ters yönlü harekettir. Önemli tepe ve diplerin korunup korunmadığına, zaman dilimine ve geri çekilmenin derinliğine bakılır.',
  explanationEn: 'A pullback is a temporary move against the main direction while the broader structure remains intact. Protected swing levels, timeframe, and pullback depth matter. A short-term decline can occur while the broader uptrend structure remains intact.',
  proExplanation: 'Retracement depth tek başına trend durumu belirlemez. Volatility regime, structural invalidation, momentum decay ve multi-timeframe context birlikte değerlendirilmelidir.',
  proExplanationEn: 'Retracement depth alone does not define trend state. Volatility regime, structural invalidation, momentum decay, and multi-timeframe context should be assessed together.',
  misconception: 'Ana yapı bozulmadan oluşan her geri çekilmeyi trend dönüşü sayma.',
  misconceptionEn: 'Common mistake: treating every retracement as a trend reversal even when the main structure remains intact.',
  takeaway: 'Trend dönüşü için yalnız geri çekilme değil, yapısal bozulma da gerekir.',
  takeawayEn: 'A pullback is a temporary retracement within the main move; a reversal needs additional evidence that structure has actually changed.',
  prerequisiteConceptKeys: ['market.trend.basics', 'market.chart.timeframes'],
  relatedConceptKeys: ['market.structure.choch', 'market.technical.momentum', 'market.structure.support_resistance'],
  visualAlt: 'Yükseliş yapısı içinde daha yüksek dip korunurken oluşan geçici geri çekilmeyi gösteren sade grafik',
  visualAltEn: 'Simple chart showing a temporary pullback while a higher low remains protected in an uptrend',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://academy/technical/pullback-001',
  taskPrompt: 'Hangisi pullback ile daha uyumludur?',
  taskPromptEn: 'Which is more consistent with a pullback?',
  taskChoices: [
    { id: 'structure', label: 'Kısa düşüşe rağmen ana yükseliş yapısının korunması', labelEn: 'A short decline while the broader uptrend structure remains intact' },
    { id: 'broken', label: 'Ana yapıyı koruyan önemli seviyelerin kaybedilmesi ve yeni yönde devam', labelEn: 'Loss of key structural levels with follow-through in the new direction' },
    { id: 'guarantee', label: 'Tek kırmızı mum görülmesi', labelEn: 'Seeing one red candle' },
  ],
  taskCorrectIds: ['structure'],
  questions: [
    { prompt: 'Pullback neyi ifade eder?', promptEn: 'What does a pullback describe?', choices: [{ id: 'a', label: 'Ana yapı içinde geçici karşı yönlü hareketi', labelEn: 'A temporary counter-direction move within the main structure' }, { id: 'b', label: 'Her zaman kesin trend dönüşünü', labelEn: 'Always a certain trend reversal' }, { id: 'c', label: 'Yalnız yatay piyasayı', labelEn: 'Only a sideways market' }], correctId: 'a', explanation: 'Pullback, ana yapının korunabildiği geçici geri çekilmedir.', explanationEn: 'A pullback is a temporary retracement while the main structure can remain intact.' },
    { prompt: 'Pullback değerlendirmesinde zaman dilimi önemli midir?', promptEn: 'Does timeframe matter when assessing a pullback?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız haftalık grafikte', labelEn: 'Only on weekly charts' }], correctId: 'a', explanation: 'Kısa zaman dilimi geri çekilmesi geniş yapıda küçük dalga olabilir.', explanationEn: 'A lower-timeframe pullback can be a small wave in a broader structure.' },
    { prompt: 'Tek kırmızı mum trend dönüşünü kanıtlar mı?', promptEn: 'Does one red candle prove a trend reversal?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız hacim yüksekse', labelEn: 'Only if volume is high' }], correctId: 'a', explanation: 'Trend yapısı tek mumdan daha geniş fiyat davranışıyla değerlendirilir.', explanationEn: 'Trend structure is assessed using broader price behavior than one candle.' },
  ],
  sources: [TECHNICAL_ANALYSIS_SOURCES.charting, TECHNICAL_ANALYSIS_SOURCES.methodology],
});

const range = createFoundationLesson({
  id: 'lesson.technical.range.001',
  slug: 'range-konsolidasyon-nasil-okunur',
  conceptKey: 'market.technical.range',
  skillId: 'skill.technical-analysis',
  competencyId: 'competency.identify-range.foundation',
  title: 'Range ve konsolidasyon nasıl okunur?',
  titleEn: 'How do you read a range or consolidation?',
  objective: 'Range yapısını belirgin trendden ayırt etmeyi öğren.',
  objectiveEn: 'Recognize a range as repeated price movement between areas without clear directional progress.',
  minutes: 5,
  hook: 'Fiyat sürekli yukarı-aşağı gidiyor ama yeni bir yön kuramıyorsa piyasa ne yapıyor olabilir?',
  hookEn: 'If price keeps moving up and down without establishing a new direction, what may the market be doing?',
  explanation: 'Range, fiyatın belirgin trend kurmadan üst ve alt tepki bölgeleri arasında gidip gelmesidir. Orta bölge daha gürültülü olabilir. Sınırın aşılması ise tek başına yeni trendi garanti etmez.',
  explanationEn: 'A range or consolidation is a structure where price moves between upper and lower reaction areas without clear directional progress. Moves near the middle can be noisier. A move beyond either boundary does not by itself guarantee a new trend; breakout context still matters.',
  proExplanation: 'Range width, duration, volatility compression, volume distribution ve failed excursions yapının olgunluğunu değerlendirmeye yardım edebilir. Range sınırları tek fiyat yerine bölge olabilir.',
  proExplanationEn: 'Range width, duration, volatility compression, volume distribution, and failed excursions can help assess the structure. Range boundaries can be zones rather than exact prices.',
  misconception: 'Range’in ortasındaki küçük hareketlerden güçlü trend sonucu çıkarma.',
  misconceptionEn: 'Common mistake: trying to infer a clear trend direction from small movements in the middle of a range.',
  takeaway: 'Range’de önce sınırları, sonra kırılım davranışını izle.',
  takeawayEn: 'A range is a balance structure between boundaries; the boundaries and breakout behavior matter.',
  prerequisiteConceptKeys: ['market.structure.support_resistance', 'market.trend.basics'],
  relatedConceptKeys: ['market.technical.breakout', 'market.technical.false_breakout', 'risk.volatility'],
  visualAlt: 'Üst ve alt tepki bölgeleri arasında hareket eden fiyatın orta bölgede gürültülü kaldığını gösteren sade range grafiği',
  visualAltEn: 'Simple range chart showing price moving between upper and lower reaction areas with noisy movement in the middle',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://academy/technical/range-001',
  taskPrompt: 'Range yapısını hangi iki alan en iyi tanımlar?',
  taskPromptEn: 'Which two areas best define a range structure?',
  taskChoices: [
    { id: 'upper', label: 'Üst tepki bölgesi', labelEn: 'Upper reaction area' },
    { id: 'lower', label: 'Alt tepki bölgesi', labelEn: 'Lower reaction area' },
    { id: 'middle', label: 'Yalnız aralığın rastgele orta noktası', labelEn: 'Only a random middle point' },
  ],
  taskCorrectIds: ['upper', 'lower'],
  questions: [
    { prompt: 'Range yapısında fiyat en temel olarak nasıl davranır?', promptEn: 'How does price fundamentally behave in a range?', choices: [{ id: 'a', label: 'Üst ve alt bölgeler arasında belirgin yön ilerlemesi olmadan hareket eder', labelEn: 'Moves between upper and lower areas without clear directional progress' }, { id: 'b', label: 'Her mumda yeni tepe yapar', labelEn: 'Makes a new high every candle' }, { id: 'c', label: 'Hiç hareket etmez', labelEn: 'Does not move at all' }], correctId: 'a', explanation: 'Range iki tepki bölgesi arasında denge davranışıdır.', explanationEn: 'A range is balance behavior between two reaction areas.' },
    { prompt: 'Range sınırları her zaman tek kesin fiyat mıdır?', promptEn: 'Are range boundaries always one exact price?', choices: [{ id: 'a', label: 'Hayır, bölge olarak okunabilir', labelEn: 'No, they can be read as zones' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız forexte bölgedir', labelEn: 'Only in forex' }], correctId: 'a', explanation: 'Fiyat tepkileri aynı tek noktada olmak zorunda değildir.', explanationEn: 'Price reactions do not need to occur at one exact point.' },
    { prompt: 'Range sınırı aşılınca yeni trend kesinleşir mi?', promptEn: 'Does crossing a range boundary guarantee a new trend?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız üst sınırda', labelEn: 'Only at the upper boundary' }], correctId: 'a', explanation: 'Breakout’un devamı ve bağlamı ayrıca değerlendirilmelidir.', explanationEn: 'Breakout follow-through and context still need assessment.' },
  ],
  sources: [TECHNICAL_ANALYSIS_SOURCES.charting, TECHNICAL_ANALYSIS_SOURCES.methodology],
});

const momentum = createFoundationLesson({
  id: 'lesson.technical.momentum.001',
  slug: 'momentum-ne-anlatir',
  conceptKey: 'market.technical.momentum',
  skillId: 'skill.technical-analysis',
  competencyId: 'competency.explain-momentum.foundation',
  title: 'Momentum ne anlatır?',
  titleEn: 'What does momentum tell us?',
  objective: 'Momentumu yön tahmini değil, hareket gücü olarak okumayı öğren.',
  objectiveEn: 'Explain momentum as the speed and persistence of price movement rather than a direction guarantee.',
  minutes: 4,
  hook: 'Fiyat yükseliyor ama yükseliş hızı giderek zayıflıyorsa ne değişiyor olabilir?',
  hookEn: 'If price is still rising but the speed of the rise is fading, what may be changing?',
  explanation: 'Momentum, hareketin hızını ve devam gücünü anlatır. Fiyat yükselirken momentum zayıflayabilir; düşerken güçlenebilir. Tek başına yön tahmini değildir ve fiyat yapısıyla birlikte okunmalıdır.',
  explanationEn: 'Momentum helps describe how quickly and persistently price is moving. Momentum can weaken while price is still rising or strengthen during a decline. It does not predict direction by itself and should be interpreted with structure, timeframe, and volatility.',
  proExplanation: 'Rate of change, oscillator ve slope tabanlı momentum ölçümleri farklı pencere ve normalizasyonlara sahiptir. Divergence gözlemi de tek başına reversal sinyali değildir.',
  proExplanationEn: 'Rate-of-change, oscillator, and slope-based momentum measures use different windows and normalization. A divergence observation is not a standalone reversal signal.',
  misconception: 'Güçlü momentumu aynı yönde devam garantisi sanma.',
  misconceptionEn: 'Common mistake: interpreting strong momentum as certainty that price will continue in the same direction.',
  takeaway: 'Momentum gücü anlatır; yön garantisi vermez.',
  takeawayEn: 'Momentum describes speed and persistence; it does not guarantee the future.',
  prerequisiteConceptKeys: ['market.trend.basics', 'risk.volatility'],
  relatedConceptKeys: ['market.technical.pullback', 'market.technical.breakout', 'market.volume.basics'],
  visualAlt: 'Aynı yönde ilerleyen ancak eğimi giderek azalan iki fiyat hareketini karşılaştıran sade momentum şeması',
  visualAltEn: 'Simple momentum diagram comparing price moves in the same direction with different slopes and persistence',
  taskPrompt: 'Fiyat hâlâ yükselirken tepeye çıkışların hızı belirgin biçimde azalırsa ne söylenebilir?',
  taskPromptEn: 'If price is still rising but advances become clearly slower, what can be said?',
  taskChoices: [
    { id: 'weaker', label: 'Yükseliş momentumu zayıflıyor olabilir', labelEn: 'Upward momentum may be weakening' },
    { id: 'reversal', label: 'Kesin trend dönüşü olmuştur', labelEn: 'A reversal has definitely occurred' },
    { id: 'none', label: 'Momentumla hiçbir ilgisi yoktur', labelEn: 'It has nothing to do with momentum' },
  ],
  taskCorrectIds: ['weaker'],
  questions: [
    { prompt: 'Momentum neyi anlamaya yardım eder?', promptEn: 'What does momentum help describe?', choices: [{ id: 'a', label: 'Hareketin hız ve devam gücünü', labelEn: 'The speed and persistence of movement' }, { id: 'b', label: 'Kesin gelecek fiyatını', labelEn: 'The certain future price' }, { id: 'c', label: 'Şirketin bilançosunu', labelEn: 'A company’s balance sheet' }], correctId: 'a', explanation: 'Momentum hareketin hız ve süreklilik özellikleriyle ilgilidir.', explanationEn: 'Momentum concerns the speed and persistence of movement.' },
    { prompt: 'Fiyat yükselirken momentum zayıflayabilir mi?', promptEn: 'Can momentum weaken while price is still rising?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır', labelEn: 'No' }, { id: 'c', label: 'Yalnız emtiada', labelEn: 'Only in commodities' }], correctId: 'a', explanation: 'Fiyat ilerlemeye devam ederken hareket hızı ve gücü azalabilir.', explanationEn: 'Price can continue advancing while speed and strength diminish.' },
    { prompt: 'Momentum tek başına yön garantisi midir?', promptEn: 'Is momentum alone a direction guarantee?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız güçlü olduğunda', labelEn: 'Only when strong' }], correctId: 'a', explanation: 'Yapı ve bağlam olmadan momentum kesin sonuç vermez.', explanationEn: 'Momentum does not provide certainty without structure and context.' },
  ],
  sources: [TECHNICAL_ANALYSIS_SOURCES.charting, TECHNICAL_ANALYSIS_SOURCES.methodology],
});

const movingAverage = createFoundationLesson({
  id: 'lesson.technical.moving-average.001',
  slug: 'hareketli-ortalama-ne-yapar',
  conceptKey: 'market.technical.moving_average',
  skillId: 'skill.technical-analysis',
  competencyId: 'competency.explain-moving-average.foundation',
  title: 'Hareketli ortalama ne yapar, ne yapmaz?',
  titleEn: 'What does a moving average do—and what does it not do?',
  objective: 'Hareketli ortalamanın neyi sadeleştirdiğini ve neden gecikmeli olduğunu öğren.',
  objectiveEn: 'Explain a moving average as a lagging summary that smooths past prices.',
  minutes: 5,
  hook: 'Fiyat hareketli ortalamanın üstüne çıktı diye yükseliş kesinleşmiş midir?',
  hookEn: 'If price moves above a moving average, is an uptrend confirmed?',
  explanation: 'Hareketli ortalama geçmiş fiyatları tek çizgide yumuşatır. Uzun pencere daha yavaş, kısa pencere daha hızlı tepki verir. Yalnız geçmiş veriden üretildiği için gecikmelidir ve tek başına işlem sinyali değildir.',
  explanationEn: 'A moving average smooths short-term noise by averaging a chosen number of past price observations. Longer windows react more slowly; shorter windows follow price more closely. Because it is built from past data, it lags and is not automatically support, resistance, or a buy/sell signal.',
  proExplanation: 'SMA, EMA ve diğer ağırlıklandırmalar farklı tepki profillerine sahiptir. Crossover sonuçları trend, volatility regime ve işlem maliyetlerine duyarlıdır; parameter selection overfitting riski yaratabilir.',
  proExplanationEn: 'SMA, EMA, and other weighting schemes have different response profiles. Crossover results depend on trend, volatility regime, and costs; parameter selection can create overfitting risk.',
  misconception: 'Fiyatın ortalamayı geçmesini otomatik işlem sinyali sayma.',
  misconceptionEn: 'Common mistake: assuming a price crossing a moving average creates an automatic reliable trade signal.',
  takeaway: 'Hareketli ortalama geçmişi özetler; geleceği bilmez.',
  takeawayEn: 'A moving average smooths past price; it summarizes context but does not know the future.',
  prerequisiteConceptKeys: ['market.trend.basics', 'market.chart.timeframes'],
  relatedConceptKeys: ['market.technical.momentum', 'market.technical.pullback', 'market.technical.range'],
  visualAlt: 'Dalgalı fiyat çizgisi üzerinde daha yavaş hareket eden yumuşatılmış ortalama çizgisini gösteren sade grafik',
  visualAltEn: 'Simple chart showing a smoother, slower moving-average line over a noisier price line',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://academy/technical/moving-average-001',
  taskPrompt: 'Uzun periyotlu hareketli ortalama kısa periyotluya göre genellikle nasıl davranır?',
  taskPromptEn: 'How does a longer-window moving average generally behave compared with a shorter one?',
  taskChoices: [
    { id: 'slower', label: 'Daha yavaş tepki verir ve daha fazla yumuşatır', labelEn: 'It reacts more slowly and smooths more' },
    { id: 'faster', label: 'Her zaman daha hızlı tepki verir', labelEn: 'It always reacts faster' },
    { id: 'future', label: 'Gelecek fiyatı önceden gösterir', labelEn: 'It shows future price in advance' },
  ],
  taskCorrectIds: ['slower'],
  questions: [
    { prompt: 'Hareketli ortalama hangi veriden üretilir?', promptEn: 'What data is a moving average built from?', choices: [{ id: 'a', label: 'Geçmiş fiyat gözlemlerinden', labelEn: 'Past price observations' }, { id: 'b', label: 'Gelecekteki kesin fiyatlardan', labelEn: 'Certain future prices' }, { id: 'c', label: 'Yalnız haber başlıklarından', labelEn: 'Only news headlines' }], correctId: 'a', explanation: 'Hareketli ortalama geçmiş fiyat penceresinin özetidir.', explanationEn: 'A moving average summarizes a window of past prices.' },
    { prompt: 'Daha uzun ortalama penceresi genellikle ne yapar?', promptEn: 'What does a longer moving-average window generally do?', choices: [{ id: 'a', label: 'Daha fazla yumuşatır ve daha yavaş tepki verir', labelEn: 'Smooths more and reacts more slowly' }, { id: 'b', label: 'Geleceği daha kesin bilir', labelEn: 'Predicts the future more certainly' }, { id: 'c', label: 'Fiyatı sabitler', labelEn: 'Fixes the price' }], correctId: 'a', explanation: 'Daha fazla gözlem ortalamaya dahil edildiğinde kısa hareketlerin etkisi azalır.', explanationEn: 'Including more observations reduces the impact of short moves.' },
    { prompt: 'Fiyatın ortalamayı geçmesi tek başına kesin işlem sinyali midir?', promptEn: 'Is a price crossing a moving average by itself a certain trade signal?', choices: [{ id: 'a', label: 'Hayır', labelEn: 'No' }, { id: 'b', label: 'Evet', labelEn: 'Yes' }, { id: 'c', label: 'Yalnız EMA ise', labelEn: 'Only for an EMA' }], correctId: 'a', explanation: 'Trend, volatilite ve diğer bağlam ayrıca değerlendirilir.', explanationEn: 'Trend, volatility, and other context still need assessment.' },
  ],
  sources: [TECHNICAL_ANALYSIS_SOURCES.indicators, TECHNICAL_ANALYSIS_SOURCES.methodology],
});

export const TECHNICAL_ANALYSIS_FOUNDATION_LESSONS = [
  breakout,
  falseBreakout,
  pullback,
  range,
  momentum,
  movingAverage,
] as const;
