import {
  learningModuleSchema,
  learningPathSchema,
  lessonBlueprintSchema,
} from '../schemas';

const MODULES = {
  markets: 'module.wave1.market-foundations',
  charts: 'module.wave1.chart-literacy',
  risk: 'module.wave1.risk-management',
  behavior: 'module.wave1.behavior-evidence',
} as const;

export const WAVE1_LESSON_BLUEPRINTS = [
  {
    id: 'lesson.market.price-formation.001', moduleId: MODULES.markets, order: 1,
    conceptKey: 'market.basics.price_formation', title: { tr: 'Fiyat piyasada nasıl oluşur?' },
    learningObjective: { tr: 'Alıcı ve satıcı etkileşiminin fiyat oluşumundaki rolünü açıklar.' },
    learningStage: 'foundation', estimatedMinutes: 4, prerequisiteLessonIds: [],
    legacyRefs: ['course:2/module:Piyasa Türleri'], practiceKind: 'scenario_choice', requiresVisual: true,
    sourceIds: ['source.investor-gov.markets'], readiness: 'draft',
  },
  {
    id: 'lesson.market.instruments.001', moduleId: MODULES.markets, order: 2,
    conceptKey: 'market.basics.instruments', title: { tr: 'Hisse, tahvil, döviz ve emtia aynı şey değildir' },
    learningObjective: { tr: 'Temel piyasa araçlarının neyi temsil ettiğini ayırt eder.' },
    learningStage: 'foundation', estimatedMinutes: 5, prerequisiteLessonIds: ['lesson.market.price-formation.001'],
    legacyRefs: ['course:2/module:Piyasa Türleri'], practiceKind: 'scenario_choice', requiresVisual: true,
    sourceIds: ['source.investor-gov.products'], readiness: 'draft',
  },
  {
    id: 'lesson.market.liquidity.001', moduleId: MODULES.markets, order: 3,
    conceptKey: 'market.structure.liquidity', title: { tr: 'Likidite neden önemlidir?' },
    learningObjective: { tr: 'Likiditenin işlem kolaylığı, fiyat etkisi ve riskle ilişkisini açıklar.' },
    learningStage: 'foundation', estimatedMinutes: 4, prerequisiteLessonIds: ['lesson.market.price-formation.001'],
    legacyRefs: ['course:2/module:Likidite'], practiceKind: 'scenario_choice', requiresVisual: true,
    sourceIds: ['source.investor-gov.liquidity'], readiness: 'draft',
  },
  {
    id: 'lesson.market.bid-ask.001', moduleId: MODULES.markets, order: 4,
    conceptKey: 'market.microstructure.bid_ask', title: { tr: 'Bid, ask ve spread nedir?' },
    learningObjective: { tr: 'Alış ve satış fiyatı arasındaki farkı ve spread maliyetini tanır.' },
    learningStage: 'foundation', estimatedMinutes: 4, prerequisiteLessonIds: ['lesson.market.liquidity.001'],
    legacyRefs: ['course:2/module:Likidite'], practiceKind: 'scenario_choice', requiresVisual: true,
    sourceIds: ['source.investor-gov.bid-ask'], readiness: 'draft',
  },
  {
    id: 'lesson.market.order-types.001', moduleId: MODULES.markets, order: 5,
    conceptKey: 'market.execution.order_types', title: { tr: 'Piyasa, limit ve stop emirleri' },
    learningObjective: { tr: 'Emir türlerinin fiyat ve gerçekleşme açısından temel farklarını ayırt eder.' },
    learningStage: 'foundation', estimatedMinutes: 5, prerequisiteLessonIds: ['lesson.market.bid-ask.001'],
    legacyRefs: ['course:2/module:Emir Türleri'], practiceKind: 'scenario_choice', requiresVisual: false,
    sourceIds: ['source.investor-gov.order-types', 'source.finra.order-types'], readiness: 'draft',
  },
  {
    id: 'lesson.market.slippage.001', moduleId: MODULES.markets, order: 6,
    conceptKey: 'market.execution.slippage', title: { tr: 'Ekrandaki fiyat neden garanti değildir?' },
    learningObjective: { tr: 'Son fiyat ile gerçekleşme fiyatının neden farklılaşabileceğini açıklar.' },
    learningStage: 'foundation', estimatedMinutes: 4, prerequisiteLessonIds: ['lesson.market.order-types.001'],
    legacyRefs: ['course:2/module:Emir Türleri'], practiceKind: 'scenario_choice', requiresVisual: true,
    sourceIds: ['source.investor-gov.order-types'], readiness: 'draft',
  },
  {
    id: 'lesson.chart.candles.001', moduleId: MODULES.charts, order: 7,
    conceptKey: 'market.chart.candles', title: { tr: 'Bir mum bize ne söyler?' },
    learningObjective: { tr: 'Açılış, kapanış, en yüksek ve en düşük fiyatı mum üzerinde gösterir.' },
    learningStage: 'foundation', estimatedMinutes: 4, prerequisiteLessonIds: ['lesson.market.price-formation.001'],
    legacyRefs: ['course:5/module:Grafik Temelleri'], practiceKind: 'chart_identification', requiresVisual: true,
    sourceIds: ['source.cme.technical-analysis', 'source.finm8.methodology.chart-literacy'], readiness: 'draft',
  },
  {
    id: 'lesson.chart.timeframes.001', moduleId: MODULES.charts, order: 8,
    conceptKey: 'market.chart.timeframes', title: { tr: 'Zaman dilimi neyi değiştirir?' },
    learningObjective: { tr: 'Aynı piyasanın farklı zaman dilimlerinde farklı yapı gösterebileceğini açıklar.' },
    learningStage: 'foundation', estimatedMinutes: 4, prerequisiteLessonIds: ['lesson.chart.candles.001'],
    legacyRefs: ['course:5/module:Grafik Temelleri'], practiceKind: 'chart_identification', requiresVisual: true,
    sourceIds: ['source.cme.technical-analysis', 'source.finm8.methodology.timeframes'], readiness: 'draft',
  },
  {
    id: 'lesson.chart.trend.001', moduleId: MODULES.charts, order: 9,
    conceptKey: 'market.trend.basics', title: { tr: 'Trend: yön mü, yapı mı?' },
    learningObjective: { tr: 'Yükseliş, düşüş ve yatay yapı arasındaki temel farkı tanır.' },
    learningStage: 'foundation', estimatedMinutes: 5, prerequisiteLessonIds: ['lesson.chart.timeframes.001'],
    legacyRefs: ['course:5/module:Trend Analizi'], practiceKind: 'chart_identification', requiresVisual: true,
    sourceIds: ['source.cme.technical-analysis', 'source.finm8.methodology.trend'], readiness: 'draft',
  },
  {
    id: 'lesson.chart.support-resistance.001', moduleId: MODULES.charts, order: 10,
    conceptKey: 'market.structure.support_resistance', title: { tr: 'Destek ve direnç çizgi değil bölgedir' },
    learningObjective: { tr: 'Tek fiyat çizgisi yerine tepki bölgesi düşünmenin nedenini açıklar.' },
    learningStage: 'foundation', estimatedMinutes: 5, prerequisiteLessonIds: ['lesson.chart.trend.001'],
    legacyRefs: ['course:5/module:Destek ve Direnç'], practiceKind: 'chart_identification', requiresVisual: true,
    sourceIds: ['source.cme.technical-analysis', 'source.finm8.methodology.support-resistance'], readiness: 'draft',
  },
  {
    id: 'lesson.market-structure.bos.001', moduleId: MODULES.charts, order: 11,
    conceptKey: 'market.structure.bos', title: { tr: 'BOS: Yapı ne zaman gerçekten kırılır?' },
    learningObjective: { tr: 'Yapı kırılımını sıradan fiyat taşmasından ayırır.' },
    learningStage: 'foundation', estimatedMinutes: 3, prerequisiteLessonIds: ['lesson.chart.support-resistance.001'],
    legacyRefs: ['course:5/module:Destek ve Direnç'], practiceKind: 'chart_identification', requiresVisual: true,
    sourceIds: ['source.finm8.methodology.market-structure'], readiness: 'draft',
  },
  {
    id: 'lesson.market-structure.choch.001', moduleId: MODULES.charts, order: 12,
    conceptKey: 'market.structure.choch', title: { tr: 'CHoCH: Değişim ihtimali nasıl okunur?' },
    learningObjective: { tr: 'Karakter değişimini kesin dönüş iddiasından ayırır.' },
    learningStage: 'intermediate', estimatedMinutes: 5, prerequisiteLessonIds: ['lesson.market-structure.bos.001'],
    legacyRefs: ['course:5/module:Trend Analizi'], practiceKind: 'chart_identification', requiresVisual: true,
    sourceIds: ['source.cme.technical-analysis', 'source.finm8.methodology.market-structure'], readiness: 'draft',
  },
  {
    id: 'lesson.risk.uncertainty.001', moduleId: MODULES.risk, order: 13,
    conceptKey: 'risk.basics', title: { tr: 'Risk, belirsizlik ve kayıp aynı şey mi?' },
    learningObjective: { tr: 'Risk olasılığı, belirsizlik ve gerçekleşmiş kaybı ayırt eder.' },
    learningStage: 'foundation', estimatedMinutes: 4, prerequisiteLessonIds: [],
    legacyRefs: ['course:7/module:Risk Kavramı'], practiceKind: 'scenario_choice', requiresVisual: false,
    sourceIds: ['source.investor-gov.risk', 'source.finra.risk'], readiness: 'draft',
  },
  {
    id: 'lesson.risk.volatility.001', moduleId: MODULES.risk, order: 14,
    conceptKey: 'risk.volatility', title: { tr: 'Volatilite fırsat değil önce risktir' },
    learningObjective: { tr: 'Fiyat hareket genişliğinin pozisyon riskini nasıl etkilediğini açıklar.' },
    learningStage: 'foundation', estimatedMinutes: 4, prerequisiteLessonIds: ['lesson.risk.uncertainty.001'],
    legacyRefs: ['course:7/module:Risk Kavramı'], practiceKind: 'scenario_choice', requiresVisual: true,
    sourceIds: ['source.investor-gov.risk', 'source.finm8.methodology.risk'], readiness: 'draft',
  },
  {
    id: 'lesson.risk.position-sizing.001', moduleId: MODULES.risk, order: 15,
    conceptKey: 'risk.position_sizing', title: { tr: 'Pozisyon büyüklüğü neden sonuçtan önce gelir?' },
    learningObjective: { tr: 'Pozisyon büyüklüğünün kayıp etkisini nasıl belirlediğini açıklar.' },
    learningStage: 'foundation', estimatedMinutes: 5, prerequisiteLessonIds: ['lesson.risk.volatility.001'],
    legacyRefs: ['course:7/module:Pozisyon Boyutu'], practiceKind: 'scenario_choice', requiresVisual: false,
    sourceIds: ['source.finra.risk', 'source.finm8.methodology.risk'], readiness: 'draft',
  },
  {
    id: 'lesson.risk.reward.001', moduleId: MODULES.risk, order: 16,
    conceptKey: 'risk.risk_reward', title: { tr: 'Risk/getiri oranı tek başına yeterli mi?' },
    learningObjective: { tr: 'Risk/getiri oranını olasılık ve gerçekleşme belirsizliğiyle birlikte yorumlar.' },
    learningStage: 'intermediate', estimatedMinutes: 5, prerequisiteLessonIds: ['lesson.risk.position-sizing.001'],
    legacyRefs: ['course:7/module:Risk/Ödül Oranı'], practiceKind: 'scenario_choice', requiresVisual: false,
    sourceIds: ['source.finra.risk', 'source.finm8.methodology.risk'], readiness: 'draft',
  },
  {
    id: 'lesson.risk.stop-orders.001', moduleId: MODULES.risk, order: 17,
    conceptKey: 'risk.stop_orders', title: { tr: 'Stop emri garanti midir?' },
    learningObjective: { tr: 'Stop emrinin tetiklenme ve gerçekleşme sınırlamalarını açıklar.' },
    learningStage: 'intermediate', estimatedMinutes: 5, prerequisiteLessonIds: ['lesson.market.order-types.001'],
    legacyRefs: ['course:7/module:Stop-Loss ve Take-Profit'], practiceKind: 'scenario_choice', requiresVisual: false,
    sourceIds: ['source.investor-gov.order-types', 'source.finm8.methodology.risk'], readiness: 'draft',
  },
  {
    id: 'lesson.portfolio.diversification.001', moduleId: MODULES.risk, order: 18,
    conceptKey: 'portfolio.diversification', title: { tr: 'Çok varlık her zaman çeşitlendirme değildir' },
    learningObjective: { tr: 'Varlık sayısı ile gerçek risk çeşitlendirmesi arasındaki farkı açıklar.' },
    learningStage: 'foundation', estimatedMinutes: 5, prerequisiteLessonIds: ['lesson.risk.uncertainty.001'],
    legacyRefs: ['course:7/module:Portföy Riskleri'], practiceKind: 'scenario_choice', requiresVisual: true,
    sourceIds: ['source.investor-gov.diversification', 'source.investor-gov.risk'], readiness: 'draft',
  },
  {
    id: 'lesson.behavior.fomo.001', moduleId: MODULES.behavior, order: 19,
    conceptKey: 'behavior.fomo', title: { tr: 'FOMO kararını nasıl bozar?' },
    learningObjective: { tr: 'Fırsatı kaçırma korkusunun karar sürecindeki işaretlerini tanır.' },
    learningStage: 'foundation', estimatedMinutes: 4, prerequisiteLessonIds: [],
    legacyRefs: ['course:8/module:Psikolojik Engeller'], practiceKind: 'reflection', requiresVisual: false,
    sourceIds: ['source.finm8.methodology.behavior'], readiness: 'planned',
  },
  {
    id: 'lesson.behavior.overtrading.001', moduleId: MODULES.behavior, order: 20,
    conceptKey: 'behavior.overtrading', title: { tr: 'Aşırı işlem nasıl fark edilir?' },
    learningObjective: { tr: 'Plan dışı işlem sıklığı ve dürtüsel karar işaretlerini tanır.' },
    learningStage: 'foundation', estimatedMinutes: 4, prerequisiteLessonIds: ['lesson.behavior.fomo.001'],
    legacyRefs: ['course:8/module:Psikolojik Engeller'], practiceKind: 'reflection', requiresVisual: false,
    sourceIds: ['source.finm8.methodology.behavior'], readiness: 'planned',
  },
  {
    id: 'lesson.behavior.confirmation-bias.001', moduleId: MODULES.behavior, order: 21,
    conceptKey: 'behavior.confirmation_bias', title: { tr: 'Sadece haklı çıkaran kanıtı mı görüyorsun?' },
    learningObjective: { tr: 'Onaylama yanlılığını ve karşı kanıt arama ihtiyacını açıklar.' },
    learningStage: 'foundation', estimatedMinutes: 4, prerequisiteLessonIds: ['lesson.behavior.fomo.001'],
    legacyRefs: ['course:8/module:Bilişsel Hatalar'], practiceKind: 'scenario_choice', requiresVisual: false,
    sourceIds: ['source.finm8.methodology.behavior'], readiness: 'planned',
  },
  {
    id: 'lesson.evidence.data-quality.001', moduleId: MODULES.behavior, order: 22,
    conceptKey: 'evidence.data_quality', title: { tr: 'Her veri aynı kalitede değildir' },
    learningObjective: { tr: 'Eksik, tutarsız ve doğrulanmamış veriyi güvenilir kanıttan ayırır.' },
    learningStage: 'foundation', estimatedMinutes: 5, prerequisiteLessonIds: [],
    legacyRefs: [], practiceKind: 'scenario_choice', requiresVisual: false,
    sourceIds: ['source.finm8.methodology.evidence'], readiness: 'planned',
  },
  {
    id: 'lesson.evidence.freshness.001', moduleId: MODULES.behavior, order: 23,
    conceptKey: 'evidence.freshness', title: { tr: 'Doğru veri ne zaman eskir?' },
    learningObjective: { tr: 'Veri güncelliğini piyasa ve zaman dilimi bağlamında değerlendirir.' },
    learningStage: 'intermediate', estimatedMinutes: 4, prerequisiteLessonIds: ['lesson.evidence.data-quality.001'],
    legacyRefs: [], practiceKind: 'scenario_choice', requiresVisual: false,
    sourceIds: ['source.finm8.methodology.evidence'], readiness: 'planned',
  },
  {
    id: 'lesson.behavior.decision-journal.001', moduleId: MODULES.behavior, order: 24,
    conceptKey: 'behavior.decision_journal', title: { tr: 'Sonucu değil karar kalitesini kaydet' },
    learningObjective: { tr: 'Bir karar günlüğünde gözlem, yorum ve sonucu ayrı kaydeder.' },
    learningStage: 'foundation', estimatedMinutes: 5, prerequisiteLessonIds: ['lesson.behavior.confirmation-bias.001'],
    legacyRefs: ['course:8/module:Günlük Tutma'], practiceKind: 'reflection', requiresVisual: false,
    sourceIds: ['source.finm8.methodology.behavior'], readiness: 'planned',
  },
].map((blueprint) => lessonBlueprintSchema.parse(blueprint));

export const WAVE1_MODULES = [
  { id: MODULES.markets, title: { tr: 'Piyasa Temelleri' }, description: { tr: 'Fiyat, araçlar, likidite ve emirlerin çalışma mantığı.' }, order: 1, lessonIds: WAVE1_LESSON_BLUEPRINTS.slice(0, 6).map((item) => item.id), prerequisiteModuleIds: [] },
  { id: MODULES.charts, title: { tr: 'Grafik Okuryazarlığı' }, description: { tr: 'Mum, zaman dilimi, trend ve piyasa yapısını okuma.' }, order: 2, lessonIds: WAVE1_LESSON_BLUEPRINTS.slice(6, 12).map((item) => item.id), prerequisiteModuleIds: [MODULES.markets] },
  { id: MODULES.risk, title: { tr: 'Risk Yönetimi' }, description: { tr: 'Belirsizlik, volatilite, boyutlandırma ve çeşitlendirme.' }, order: 3, lessonIds: WAVE1_LESSON_BLUEPRINTS.slice(12, 18).map((item) => item.id), prerequisiteModuleIds: [MODULES.markets] },
  { id: MODULES.behavior, title: { tr: 'Davranış ve Kanıt' }, description: { tr: 'Karar hatalarını ve kanıt kalitesini fark etme.' }, order: 4, lessonIds: WAVE1_LESSON_BLUEPRINTS.slice(18, 24).map((item) => item.id), prerequisiteModuleIds: [] },
].map((module) => learningModuleSchema.parse(module));

export const WAVE1_MARKET_LITERACY_PATH = learningPathSchema.parse({
  id: 'path.market-literacy.tr.wave1',
  slug: 'piyasa-okuryazarligi',
  title: { tr: 'Piyasa Okuryazarlığı' },
  description: { tr: 'Piyasayı, grafiği, riski ve kendi kararlarını birlikte okumayı öğren.' },
  startingStage: 'foundation',
  goals: ['financial_literacy', 'trading', 'risk_management', 'data_literacy'],
  status: 'draft',
  moduleIds: WAVE1_MODULES.map((module) => module.id),
  estimatedMinutes: WAVE1_LESSON_BLUEPRINTS.reduce((sum, lesson) => sum + lesson.estimatedMinutes, 0),
});

export const WAVE1_CONTENT_SUMMARY = {
  lessonCount: WAVE1_LESSON_BLUEPRINTS.length,
  moduleCount: WAVE1_MODULES.length,
  estimatedMinutes: WAVE1_MARKET_LITERACY_PATH.estimatedMinutes,
  draftCount: WAVE1_LESSON_BLUEPRINTS.filter((item) => item.readiness === 'draft').length,
  plannedCount: WAVE1_LESSON_BLUEPRINTS.filter((item) => item.readiness === 'planned').length,
} as const;
