import type { ContentSource } from '../../types';
import { createFoundationLesson } from '../wave1/foundationLessonFactory';

const reviewedAt = '2026-09-09T12:00:00+03:00';

const BEGINNER_PRELUDE_SOURCES: Readonly<Record<string, ContentSource>> = {
  investing: {
    id: 'source.investorgov.introduction-investing',
    title: 'Introduction to Investing',
    publisher: 'Investor.gov — U.S. Securities and Exchange Commission',
    url: 'https://www.investor.gov/introduction-investing',
    reviewedAt,
  },
  frequentTrading: {
    id: 'source.investorgov.build-wealth-over-time',
    title: 'Build Wealth Over Time Through Saving and Investing',
    publisher: 'Investor.gov — U.S. Securities and Exchange Commission',
    url: 'https://www.investor.gov/build-wealth-over-time-through-saving-and-investing',
    reviewedAt,
  },
  allocation: {
    id: 'source.investorgov.asset-allocation',
    title: 'Asset Allocation and Diversification',
    publisher: 'Investor.gov — U.S. Securities and Exchange Commission',
    url: 'https://www.investor.gov/introduction-investing/getting-started/asset-allocation',
    reviewedAt,
  },
  riskTolerance: {
    id: 'source.investorgov.risk-tolerance',
    title: 'Gauge Your Risk Tolerance',
    publisher: 'Investor.gov — U.S. Securities and Exchange Commission',
    url: 'https://www.investor.gov/introduction-investing/investing-basics/save-and-invest/gauge-your-risk-tolerance',
    reviewedAt,
  },
};

const investingVsTrading = createFoundationLesson({
  id: 'lesson.foundation.investing-vs-trading.001',
  slug: 'yatirim-ve-kisa-vadeli-al-sat-farki',
  conceptKey: 'strategy.horizon_objective',
  skillId: 'skill.strategy-design',
  competencyId: 'competency.distinguish-investing-trading.foundation',
  title: 'Yatırım ile kısa vadeli al-sat aynı şey mi?',
  titleEn: 'Are investing and short-term trading the same thing?',
  objective: 'Yatırım ve kısa vadeli al-satın amaç, süre ve karar mantığını ayırt eder.',
  objectiveEn: 'Distinguish investing from short-term trading by objective, horizon, and decision process.',
  minutes: 4,
  hook: 'Aynı varlığı alan iki kişi neden bambaşka kararlar verebilir?',
  hookEn: 'Why can two people buying the same asset make very different decisions?',
  explanation: 'Yatırım genellikle daha uzun bir hedef ve zaman ufkuna dayanır. Kısa vadeli al-sat ise daha sık karar, gerçekleşme ve maliyet takibi gerektirir. İkisinde de risk vardır; yöntem, kanıt ve bekleme süresi aynı değildir.',
  explanationEn: 'Investing usually serves a longer-term goal and horizon. Short-term trading requires more frequent decisions and closer attention to execution and costs. Both involve risk, but their evidence, rules, and holding periods are not the same.',
  proExplanation: 'Ufuk değiştikçe ilgili veri, karar sıklığı, işlem maliyeti ve risk yönetimi de değişir. Bir yöntemin başka bir zaman ufkuna aynen taşınması tutarsız kararlar üretebilir.',
  proExplanationEn: 'As horizon changes, relevant evidence, decision frequency, transaction costs, and risk management change too. Applying one method unchanged to another horizon can create inconsistent decisions.',
  misconception: 'Yaygın hata: Her fiyat hareketini yatırım, her uzun tutmayı da iyi yatırım sanmak.',
  misconceptionEn: 'Common mistake: calling every price bet an investment or assuming a long holding period automatically makes a decision sound.',
  takeaway: 'Önce amacını ve ufkunu bil; sonra yöntemi seç.',
  takeawayEn: 'Know your objective and horizon before choosing the method.',
  prerequisiteConceptKeys: [],
  relatedConceptKeys: ['risk.basics', 'quant.transaction_costs', 'behavior.fomo'],
  visualAlt: 'Aynı varlığı uzun vadeli hedef ve kısa vadeli al-sat yaklaşımıyla karşılaştıran iki yol',
  visualAltEn: 'Two paths comparing the same asset under a long-term investing goal and a short-term trading approach',
  taskPrompt: 'Hangi örnek iki yaklaşım arasındaki farkı en iyi gösterir?',
  taskPromptEn: 'Which example best shows the difference between the two approaches?',
  taskChoices: [
    { id: 'horizon', label: 'Aynı varlık için amaç, zaman ufku ve karar kuralları farklı olabilir', labelEn: 'The same asset can involve different objectives, horizons, and decision rules' },
    { id: 'same', label: 'Aynı varlığı alan herkes aynı yöntemi kullanır', labelEn: 'Everyone buying the same asset uses the same method' },
    { id: 'riskless', label: 'Uzun süre tutulan her varlık risksiz olur', labelEn: 'Any asset held for a long time becomes risk-free' },
  ],
  taskCorrectIds: ['horizon'],
  questions: [
    {
      prompt: 'Yatırım ile kısa vadeli al-sat arasındaki temel farklardan biri nedir?',
      promptEn: 'What is one core difference between investing and short-term trading?',
      choices: [
        { id: 'objective-horizon', label: 'Amaç, zaman ufku ve karar sıklığı farklı olabilir', labelEn: 'Their objective, horizon, and decision frequency can differ' },
        { id: 'asset-name', label: 'Farkı yalnız varlığın adı belirler', labelEn: 'Only the asset name determines the difference' },
        { id: 'no-risk', label: 'Yatırımda hiç risk yoktur', labelEn: 'Investing has no risk' },
      ],
      correctId: 'objective-horizon',
      explanation: 'Aynı varlık, farklı amaç ve zaman ufuklarında farklı karar süreçleri gerektirebilir.',
      explanationEn: 'The same asset can require different decision processes when the objective and time horizon change.',
    },
    {
      prompt: 'Kısa vadeli al-satta hangi unsur daha sık gündeme gelir?',
      promptEn: 'Which factor tends to matter more often in short-term trading?',
      choices: [
        { id: 'execution-costs', label: 'Gerçekleşme, işlem maliyeti ve daha sık karar verme', labelEn: 'Execution, transaction costs, and more frequent decisions' },
        { id: 'ignore-price', label: 'Fiyatı ve işlemi tamamen görmezden gelmek', labelEn: 'Ignoring price and execution completely' },
        { id: 'guarantee', label: 'Kısa sürede sonucu garanti etmek', labelEn: 'Guaranteeing the outcome over a short period' },
      ],
      correctId: 'execution-costs',
      explanation: 'Karar ve işlem sıklığı arttıkça gerçekleşme ve maliyetlerin etkisi daha görünür olur.',
      explanationEn: 'As decision and trading frequency rise, execution and transaction costs become more visible.',
    },
    {
      prompt: 'Bir varlığı uzun süre tutmak tek başına neyi kanıtlar?',
      promptEn: 'What does holding an asset for a long time prove by itself?',
      choices: [
        { id: 'nothing-alone', label: 'Kararın iyi veya risksiz olduğunu tek başına kanıtlamaz', labelEn: 'It does not by itself prove the decision is sound or risk-free' },
        { id: 'safe', label: 'Varlığın artık kayıp riski taşımadığını', labelEn: 'That the asset can no longer lose value' },
        { id: 'profit', label: 'Kazancın kesin olduğunu', labelEn: 'That a profit is guaranteed' },
      ],
      correctId: 'nothing-alone',
      explanation: 'Zaman ufku önemlidir ama ürünün riski, hedef ve karar kalitesi ayrıca değerlendirilir.',
      explanationEn: 'Time horizon matters, but product risk, the objective, and decision quality still need separate evaluation.',
    },
  ],
  sources: [BEGINNER_PRELUDE_SOURCES.investing, BEGINNER_PRELUDE_SOURCES.frequentTrading],
});

const goalHorizonRisk = createFoundationLesson({
  id: 'lesson.foundation.goal-horizon-risk.001',
  slug: 'hedef-zaman-ufku-risk-toleransi',
  conceptKey: 'risk.basics',
  skillId: 'skill.risk-management',
  competencyId: 'competency.connect-goal-horizon-risk.foundation',
  title: 'Hedefin, zamanın ve taşıyabileceğin risk neden önce gelir?',
  titleEn: 'Why do your goal, time horizon, and risk tolerance come first?',
  objective: 'Hedef, zaman ufku ve risk toleransının yatırım kararını nasıl şekillendirdiğini açıklar.',
  objectiveEn: 'Explain how goals, time horizon, and risk tolerance shape an investment decision.',
  minutes: 4,
  hook: 'Aynı ürün neden iki kişi için farklı derecede uygun olabilir?',
  hookEn: 'Why can the same product fit two people very differently?',
  explanation: 'Karar, yalnız ürünün riskine değil, paraya ne zaman ihtiyaç duyduğuna ve kaybı ne kadar taşıyabildiğine de bağlıdır. Kısa ufuk, toparlanma için daha az zaman bırakabilir; hedef ve risk toleransı birlikte düşünülmelidir.',
  explanationEn: 'A decision depends not only on product risk, but also on when you need the money and how much loss you can tolerate. A shorter horizon can leave less time to recover, so goals, horizon, and risk tolerance belong together.',
  proExplanation: 'Risk toleransı hem kaybı finansal olarak taşıma kapasitesini hem de belirsizliğe dayanma isteğini düşünmeyi gerektirir. Uygunluk kişiye, hedefe ve zamana bağlıdır.',
  proExplanationEn: 'Risk tolerance involves both the ability and willingness to accept investment loss and uncertainty. Suitability depends on the person, objective, and time horizon.',
  misconception: 'Yaygın hata: Sadece yüksek getiri ihtimaline bakıp paraya ne zaman ihtiyaç duyacağını unutmak.',
  misconceptionEn: 'Common mistake: focusing only on possible return while ignoring when the money will be needed.',
  takeaway: 'Hedef, ufuk ve risk toleransı birlikte düşünülür.',
  takeawayEn: 'Consider the goal, horizon, and risk tolerance together.',
  prerequisiteConceptKeys: [],
  relatedConceptKeys: ['portfolio.construction', 'portfolio.diversification', 'risk.volatility'],
  visualAlt: 'Hedef, zaman ufku ve risk toleransının tek bir karar çerçevesinde birleştiğini gösteren üç adımlı şema',
  visualAltEn: 'Three-step diagram showing goal, time horizon, and risk tolerance combining into one decision framework',
  taskPrompt: 'Yakında ihtiyaç duyacağın para için hangi soru önce sorulmalıdır?',
  taskPromptEn: 'What should you ask first about money you may need soon?',
  taskChoices: [
    { id: 'need-date', label: 'Paraya ne zaman ihtiyaç duyacağım ve kaybı taşıyabilir miyim?', labelEn: 'When will I need the money, and can I tolerate a loss?' },
    { id: 'highest-return', label: 'En yüksek geçmiş getiri hangi üründe?', labelEn: 'Which product had the highest past return?' },
    { id: 'popularity', label: 'Sosyal medyada en çok hangi ürün konuşuluyor?', labelEn: 'Which product is most discussed on social media?' },
  ],
  taskCorrectIds: ['need-date'],
  questions: [
    {
      prompt: 'Zaman ufku neyi anlatır?',
      promptEn: 'What does time horizon describe?',
      choices: [
        { id: 'time-to-goal', label: 'Finansal hedefe kadar paranın ne kadar süre çalışacağını', labelEn: 'How long the money can remain invested before the financial goal' },
        { id: 'chart-color', label: 'Grafiğin hangi renkte olduğunu', labelEn: 'What color the chart uses' },
        { id: 'guaranteed-return', label: 'Kesin getiri oranını', labelEn: 'A guaranteed return rate' },
      ],
      correctId: 'time-to-goal',
      explanation: 'Zaman ufku, hedefe ulaşmak için yatırımın aylar, yıllar veya daha uzun süre tutulabileceği dönemi anlatır.',
      explanationEn: 'Time horizon is the period—months, years, or longer—available before the financial goal requires the money.',
    },
    {
      prompt: 'Risk toleransı neyi kapsar?',
      promptEn: 'What does risk tolerance include?',
      choices: [
        { id: 'ability-willingness', label: 'Kaybı taşıma gücü ve risk kabul etme isteğini', labelEn: 'The ability and willingness to accept investment loss' },
        { id: 'only-profit', label: 'Yalnız ne kadar kazanmak istediğini', labelEn: 'Only how much profit you want' },
        { id: 'ticker', label: 'Ürünün sembolünü', labelEn: 'The product ticker' },
      ],
      correctId: 'ability-willingness',
      explanation: 'Risk toleransı yalnız heyecan tercihi değil, kaybı taşıma gücü ve isteğiyle ilgilidir.',
      explanationEn: 'Risk tolerance concerns both the ability and willingness to accept investment losses, not simply a preference for excitement.',
    },
    {
      prompt: 'Kısa zaman ufku neden karar çerçevesini değiştirebilir?',
      promptEn: 'Why can a short time horizon change the decision framework?',
      choices: [
        { id: 'less-recovery-time', label: 'Kayıp sonrası toparlanmayı beklemek için daha az zaman bırakabilir', labelEn: 'It can leave less time to wait for recovery after a loss' },
        { id: 'removes-risk', label: 'Bütün yatırım riskini ortadan kaldırır', labelEn: 'It removes all investment risk' },
        { id: 'same-for-all', label: 'Herkes için aynı ürünü uygun yapar', labelEn: 'It makes the same product suitable for everyone' },
      ],
      correctId: 'less-recovery-time',
      explanation: 'Paraya daha erken ihtiyaç duyulacaksa büyük dalgalanmaları bekleyerek atlatmak için daha az zaman olabilir.',
      explanationEn: 'If the money is needed sooner, there may be less time to wait through large market fluctuations.',
    },
  ],
  sources: [BEGINNER_PRELUDE_SOURCES.allocation, BEGINNER_PRELUDE_SOURCES.riskTolerance],
});

export const BEGINNER_PRELUDE_LESSONS = [investingVsTrading, goalHorizonRisk] as const;
