import { bosMicroLesson } from '../bosLesson';
import type { MicroLesson } from '../../types';
import { CHART_LITERACY_SOURCES } from './chartLiteracySources';
import { createFoundationLesson } from './foundationLessonFactory';

const candles = createFoundationLesson({
  id: 'lesson.chart.candles.001',
  slug: 'bir-mum-bize-ne-soyler',
  conceptKey: 'market.chart.candles',
  skillId: 'skill.chart-literacy',
  competencyId: 'competency.read-ohlc-candle.foundation',
  title: 'Bir mum bize ne söyler?',
  objective: 'Açılış, kapanış, en yüksek ve en düşük fiyatı mum üzerinde gösterir.',
  minutes: 4,
  hook: 'Tek bir mumun gövdesi ve fitilleri hangi dört fiyatı saklıyor?',
  explanation: 'Her mum seçilen zaman aralığındaki açılış, en yüksek, en düşük ve kapanış fiyatını özetler. Gövde açılış ile kapanış arasını, fitiller ise dönem içindeki uçları gösterir. Mum yalnızca kendi zaman aralığını anlatır; tek başına sonraki hareketi garanti etmez.',
  proExplanation: 'OHLC yapısı aynı veriyi taşır; renk yalnız kapanışın açılışa göre yönünü kodlar. Önceki kapanışa göre değişim ile mumun kendi gövde yönü aynı kavram değildir.',
  misconception: 'Yaygın hata: Uzun yeşil bir mumun sonraki mumun da kesin yükseleceğini gösterdiğini düşünmek.',
  takeaway: 'Mum dört fiyatı özetler; tahmin değil, seçilen dönemin kaydıdır.',
  prerequisiteConceptKeys: ['market.basics.price_formation'],
  relatedConceptKeys: ['market.chart.timeframes', 'market.trend.basics'],
  visualAlt: 'Açılış, kapanış, en yüksek ve en düşük etiketli bir mum şeması',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://charts/candle-ohlc-001',
  taskPrompt: 'Şematik mumda dönem içindeki en yüksek ve en düşük fiyatı gösteren parçaları seç.',
  taskChoices: [
    { id: 'upper-wick', label: 'Üst fitilin ucu: en yüksek' },
    { id: 'lower-wick', label: 'Alt fitilin ucu: en düşük' },
    { id: 'body-color', label: 'Yalnız gövdenin rengi' },
    { id: 'next-candle', label: 'Henüz oluşmamış sonraki mum' },
  ],
  taskCorrectIds: ['upper-wick', 'lower-wick'],
  questions: [
    { prompt: 'Bir mum hangi dört temel fiyatı özetler?', choices: [{ id: 'a', label: 'Açılış, en yüksek, en düşük, kapanış' }, { id: 'b', label: 'Hedef, stop, komisyon, vergi' }, { id: 'c', label: 'Bid, ask, hacim, haber' }], correctId: 'a', explanation: 'Standart mum seçilen dönem için OHLC verisini gösterir.' },
    { prompt: 'Mum gövdesi neyi gösterir?', choices: [{ id: 'a', label: 'Açılış ile kapanış arasını' }, { id: 'b', label: 'Yalnız en yüksek fiyatı' }, { id: 'c', label: 'Gelecekteki fiyat aralığını' }], correctId: 'a', explanation: 'Gövde açılış ve kapanış arasındaki fiyat farkını görselleştirir.' },
    { prompt: 'Tek bir mum için en doğru yorum hangisidir?', choices: [{ id: 'a', label: 'Seçilen dönemi özetler, geleceği garanti etmez' }, { id: 'b', label: 'Bir sonraki yönü kesin gösterir' }, { id: 'c', label: 'Her piyasada aynı süreyi temsil eder' }], correctId: 'a', explanation: 'Mum geçmiş dönem verisidir ve anlamı seçilen zaman aralığına bağlıdır.' },
  ],
  sources: [CHART_LITERACY_SOURCES.cmeTechnicalAnalysis, CHART_LITERACY_SOURCES.chartLiteracy],
});

const timeframes = createFoundationLesson({
  id: 'lesson.chart.timeframes.001',
  slug: 'zaman-dilimi-neyi-degistirir',
  conceptKey: 'market.chart.timeframes',
  skillId: 'skill.chart-literacy',
  competencyId: 'competency.explain-timeframe-semantics.foundation',
  title: 'Zaman dilimi neyi değiştirir?',
  objective: 'Aynı piyasanın farklı zaman dilimlerinde farklı yapı gösterebileceğini açıklar.',
  minutes: 4,
  hook: 'Aynı varlık 15 dakikada düşerken günlük grafikte yükseliş yapısında olabilir mi?',
  explanation: 'Zaman dilimi, her mumun kapsadığı süreyi ve görünür yapının ölçeğini değiştirir. Kısa zaman dilimindeki geri çekilme daha geniş zaman diliminde küçük bir dalga olabilir. Bu nedenle yön veya yapı yorumu hangi zaman dilimine ait olduğu belirtilmeden eksiktir.',
  proExplanation: 'Detection her timeframe içinde bağımsız değerlendirilmelidir. Üst zaman dilimi otomatik olarak doğru veya üstün kabul edilmez; alignment ve conflict ayrı bağlam verileridir.',
  misconception: 'Yaygın hata: Bir zaman dilimindeki trend etiketini tüm zaman dilimlerine kopyalamak.',
  takeaway: 'Her yapı bir zaman dilimine aittir; farklı ölçekler çelişebilir.',
  prerequisiteConceptKeys: ['market.chart.candles'],
  relatedConceptKeys: ['market.timeframe.alignment', 'market.trend.basics'],
  visualAlt: 'Aynı fiyat hareketinin 15 dakika, 1 saat ve günlük mumlarla farklı görünümü',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://charts/timeframes-001',
  taskPrompt: '15 dakikalık düşüşe rağmen günlük yükseliş yapısı korunuyorsa hangi iki ifade birlikte doğru olabilir?',
  taskChoices: [
    { id: 'short-pullback', label: '15 dakikada kısa vadeli geri çekilme var' },
    { id: 'daily-up', label: 'Günlük yükseliş yapısı henüz bozulmamış olabilir' },
    { id: 'one-truth', label: 'Yalnız bir zaman dilimi gerçek olabilir' },
    { id: 'guarantee', label: 'Günlük yapı sonraki hareketi garanti eder' },
  ],
  taskCorrectIds: ['short-pullback', 'daily-up'],
  questions: [
    { prompt: 'Zaman dilimi en temel olarak neyi belirler?', choices: [{ id: 'a', label: 'Her mumun kapsadığı süreyi' }, { id: 'b', label: 'Varlığın gerçek değerini' }, { id: 'c', label: 'İşlemin kesin sonucunu' }], correctId: 'a', explanation: 'Örneğin 1 saatlik mum bir saatlik fiyat verisini özetler.' },
    { prompt: 'Farklı zaman dilimleri neden farklı yapı gösterebilir?', choices: [{ id: 'a', label: 'Aynı hareketi farklı ölçeklerde topladıkları için' }, { id: 'b', label: 'Biri her zaman yanlış olduğu için' }, { id: 'c', label: 'Fiyat verisi tamamen farklı olduğu için' }], correctId: 'a', explanation: 'Veri aynı piyasadan gelir; örnekleme ve yapısal ölçek farklıdır.' },
    { prompt: 'Bir trend ifadesinde hangi bilgi mutlaka olmalıdır?', choices: [{ id: 'a', label: 'Ait olduğu zaman dilimi' }, { id: 'b', label: 'Yalnız mum rengi' }, { id: 'c', label: 'Kesin hedef fiyat' }], correctId: 'a', explanation: 'Trend ve yapı timeframe belirtilmeden bağlamsız kalır.' },
  ],
  sources: [CHART_LITERACY_SOURCES.cmeTechnicalAnalysis, CHART_LITERACY_SOURCES.timeframes],
});

const trend = createFoundationLesson({
  id: 'lesson.chart.trend.001',
  slug: 'trend-yon-mu-yapi-mi',
  conceptKey: 'market.trend.basics',
  skillId: 'skill.chart-literacy',
  competencyId: 'competency.classify-trend-structure.foundation',
  title: 'Trend: yön mü, yapı mı?',
  objective: 'Yükseliş, düşüş ve yatay yapı arasındaki temel farkı tanır.',
  minutes: 5,
  hook: 'Fiyat bugün yükseldi diye piyasa mutlaka yükseliş trendinde midir?',
  explanation: 'Trend tek bir mumun rengi değil, fiyat salınımlarının zaman içindeki yapısıdır. Genel olarak daha yüksek tepeler ve dipler yükseliş; daha düşük tepeler ve dipler düşüş yapısını destekler. Belirgin ilerleme yoksa piyasa yatay veya geçiş yapısında olabilir.',
  proExplanation: 'Trend sınıflaması swing dizisi, seçilen pivot ölçeği ve timeframe’e bağlıdır. Tek indikatör veya tek günlük getiri, yapısal trendin yerine geçmez.',
  misconception: 'Yaygın hata: Son mum yeşilse yükseliş trendi, kırmızıysa düşüş trendi demek.',
  takeaway: 'Trend bir anlık yön değil, seçilen zaman dilimindeki salınım dizisidir.',
  prerequisiteConceptKeys: ['market.chart.timeframes'],
  relatedConceptKeys: ['market.structure.support_resistance', 'market.structure.bos'],
  visualAlt: 'Yükselen, düşen ve yatay salınım dizilerini karşılaştıran üç grafik',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://charts/trend-structure-001',
  taskPrompt: 'Yükseliş yapısını destekleyen iki temel salınım özelliğini seç.',
  taskChoices: [
    { id: 'higher-highs', label: 'Daha yüksek tepeler' },
    { id: 'higher-lows', label: 'Daha yüksek dipler' },
    { id: 'one-green', label: 'Tek bir yeşil mum' },
    { id: 'fixed-target', label: 'Sabit hedef fiyat' },
  ],
  taskCorrectIds: ['higher-highs', 'higher-lows'],
  questions: [
    { prompt: 'Yükseliş yapısını en iyi hangi dizi destekler?', choices: [{ id: 'a', label: 'Daha yüksek tepeler ve daha yüksek dipler' }, { id: 'b', label: 'Tek bir uzun yeşil mum' }, { id: 'c', label: 'Her gün aynı kapanış' }], correctId: 'a', explanation: 'Trend salınımların devam eden yapısıyla değerlendirilir.' },
    { prompt: 'Trend neden zaman dilimiyle birlikte belirtilmelidir?', choices: [{ id: 'a', label: 'Yapı ölçeğe göre değişebildiği için' }, { id: 'b', label: 'Mum renkleri değiştiği için' }, { id: 'c', label: 'Komisyon değiştiği için' }], correctId: 'a', explanation: 'Kısa ve uzun zaman dilimleri farklı salınım yapıları gösterebilir.' },
    { prompt: 'Yatay yapı neyi anlatabilir?', choices: [{ id: 'a', label: 'Belirgin yönlü ilerlemenin zayıf olduğunu' }, { id: 'b', label: 'Fiyatın artık değişmeyeceğini' }, { id: 'c', label: 'Kesin dönüş başladığını' }], correctId: 'a', explanation: 'Yatay yapı, yönlü salınım dizisinin belirgin olmadığını gösterir.' },
  ],
  sources: [CHART_LITERACY_SOURCES.cmeTechnicalAnalysis, CHART_LITERACY_SOURCES.trend],
});

const supportResistance = createFoundationLesson({
  id: 'lesson.chart.support-resistance.001',
  slug: 'destek-direnc-bolgedir',
  conceptKey: 'market.structure.support_resistance',
  skillId: 'skill.chart-literacy',
  competencyId: 'competency.identify-reaction-zones.foundation',
  title: 'Destek ve direnç neden bölge olarak okunur?',
  objective: 'Destek ve direnci tek kesin fiyat yerine tepki alanı olarak değerlendirmenin nedenini açıklar.',
  minutes: 5,
  hook: 'Fiyat aynı seviyeye her gelişinde tam olarak tek kuruştan mı döner?',
  explanation: 'Destek ve direnç, geçmişte alıcı veya satıcı tepkisinin yoğunlaştığı fiyatları veya alanları tanımlar. Tepkiler her zaman tek bir kusursuz fiyatta oluşmadığı için çoğu durumda bölge yaklaşımı daha gerçekçidir. Bölge tepki ihtimalini gösterir; tutmayı veya kırılmayı garanti etmez.',
  proExplanation: 'Bölge genişliği volatilite, wick dağılımı, kapanış kümeleri ve test sayısıyla değerlendirilir. Çok test edilmiş seviye otomatik olarak daha güçlü kabul edilmez; likidite tüketimi ve bağlam önemlidir.',
  misconception: 'Yaygın hata: Çizilen seviyenin fiyatı kesin durduracağını varsaymak.',
  takeaway: 'Destek ve direnç kesin duvar değildir; tek fiyat veya bölge olarak çizilse de geçmiş tepkiyi gösteren bağlamsal referanslardır.',
  prerequisiteConceptKeys: ['market.trend.basics'],
  relatedConceptKeys: ['market.structure.bos', 'market.structure.liquidity'],
  visualAlt: 'Birden fazla fitil ve kapanışı kapsayan destek ve direnç bölgeleri',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://charts/support-resistance-zone-001',
  taskPrompt: 'Bir tepki bölgesini değerlendirirken en anlamlı iki kanıtı seç.',
  taskChoices: [
    { id: 'reactions', label: 'Aynı alanda görülen birden fazla anlamlı tepki' },
    { id: 'closes-wicks', label: 'Kapanış ve fitillerin oluşturduğu fiyat aralığı' },
    { id: 'pixel-line', label: 'Tek bir piksel kalınlığında kesin çizgi' },
    { id: 'guarantee', label: 'Bölgenin mutlaka tutacağı varsayımı' },
  ],
  taskCorrectIds: ['reactions', 'closes-wicks'],
  questions: [
    { prompt: 'Destek veya direnç neden bölge olarak ele alınır?', choices: [{ id: 'a', label: 'Tepkiler çoğu zaman bir fiyat aralığında oluştuğu için' }, { id: 'b', label: 'Grafikte çizgi çizilemediği için' }, { id: 'c', label: 'Fiyat hiç değişmediği için' }], correctId: 'a', explanation: 'Emir ve tepkiler tek bir kusursuz fiyata sıkışmak zorunda değildir.' },
    { prompt: 'Bir direnç bölgesi neyi garanti eder?', choices: [{ id: 'a', label: 'Hiçbir sonucu garanti etmez' }, { id: 'b', label: 'Kesin düşüşü' }, { id: 'c', label: 'Kesin kırılımı' }], correctId: 'a', explanation: 'Bölge geçmiş tepkiyi gösterir; gelecek sonuç bağlama bağlıdır.' },
    { prompt: 'Bölge kırılımında hangisi daha anlamlıdır?', choices: [{ id: 'a', label: 'Seviye, kapanış ve bağlamı birlikte değerlendirmek' }, { id: 'b', label: 'Yalnız anlık fitile bakmak' }, { id: 'c', label: 'Çizginin rengini değiştirmek' }], correctId: 'a', explanation: 'Tek taşma yerine yapısal seviye ve teyit birlikte okunur.' },
  ],
  sources: [CHART_LITERACY_SOURCES.cmeTechnicalAnalysis, CHART_LITERACY_SOURCES.supportResistance],
});

const choch = createFoundationLesson({
  id: 'lesson.market-structure.choch.001',
  slug: 'choch-degisim-ihtimali',
  conceptKey: 'market.structure.choch',
  skillId: 'skill.market-structure',
  competencyId: 'competency.identify-choch.intermediate',
  title: 'CHoCH: Değişim ihtimali nasıl okunur?',
  objective: 'Karakter değişimini kesin trend dönüşü iddiasından ayırır.',
  minutes: 5,
  learningStage: 'intermediate',
  hook: 'Mevcut salınım düzeninin ilk kez bozulması kesin trend dönüşü müdür?',
  explanation: 'CHoCH, mevcut piyasa davranışında olası bir karakter değişimine işaret eden yapısal gözlemdir. Örneğin yükseliş dizisinde korunan anlamlı bir dibin kaybedilmesi değişim ihtimalini artırabilir. Bu, yeni yönün kesinleştiği anlamına gelmez. CHoCH etiketi ve eşikleri kullanılan metodolojiye göre değişebilir.',
  proExplanation: 'CHoCH değerlendirmesi karşı-trend yapısal ihlal, swing önemi, kapanış teyidi, displacement ve timeframe bağlamını birlikte kullanır. Devam teyidi gelmeden reversal olarak etiketlenmemelidir.',
  misconception: 'Yaygın hata: İlk karşı yönlü kırılımı kesin trend dönüşü veya otomatik işlem sinyali saymak.',
  takeaway: 'CHoCH kesin dönüş değil, mevcut yapının değişebileceğine dair izlenmesi gereken kanıttır.',
  prerequisiteConceptKeys: ['market.structure.bos'],
  relatedConceptKeys: ['market.trend.basics', 'market.timeframe.alignment'],
  visualAlt: 'Yükseliş dizisinde korunan dibin kaybını ve olası karakter değişimini gösteren grafik',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://charts/choch-001',
  taskPrompt: 'Olası CHoCH değerlendirmesinde gerekli iki kanıtı seç.',
  taskChoices: [
    { id: 'protected-swing', label: 'Mevcut yapıda korunan anlamlı salınım seviyesi' },
    { id: 'counter-close', label: 'Karşı yönde yapısal kapanış teyidi' },
    { id: 'one-wick', label: 'Rastgele tek fitil' },
    { id: 'certainty', label: 'Kesin dönüş varsayımı' },
  ],
  taskCorrectIds: ['protected-swing', 'counter-close'],
  questions: [
    { prompt: 'CHoCH en doğru neyi ifade eder?', choices: [{ id: 'a', label: 'Olası karakter değişimine dair yapısal gözlemi' }, { id: 'b', label: 'Kesin trend dönüşünü' }, { id: 'c', label: 'Otomatik alım veya satım emrini' }], correctId: 'a', explanation: 'CHoCH değişim ihtimalini gösterir; kesinlik veya talimat değildir.' },
    { prompt: 'Yükseliş yapısında hangi olay olası CHoCH için anlamlı olabilir?', choices: [{ id: 'a', label: 'Korunan anlamlı dibin karşı yönlü kaybı' }, { id: 'b', label: 'Tek bir küçük yeşil mum' }, { id: 'c', label: 'Spreadin daralması tek başına' }], correctId: 'a', explanation: 'Mevcut yapıyı koruyan swing seviyesinin ihlali karakter değişimi kanıtıdır.' },
    { prompt: 'CHoCH görüldükten sonra en sağlıklı yaklaşım hangisidir?', choices: [{ id: 'a', label: 'Devam teyidi ve diğer bağlam kanıtlarını izlemek' }, { id: 'b', label: 'Dönüşü kesin kabul etmek' }, { id: 'c', label: 'Risk değerlendirmesini bırakmak' }], correctId: 'a', explanation: 'Yeni yön için ek yapı, zaman dilimi ve risk kanıtı gerekir.' },
  ],
  sources: [CHART_LITERACY_SOURCES.cmeTechnicalAnalysis, CHART_LITERACY_SOURCES.marketStructure],
});

export const WAVE1_CHART_LITERACY_LESSONS: readonly MicroLesson[] = [
  candles,
  timeframes,
  trend,
  supportResistance,
  bosMicroLesson,
  choch,
];
