import { bosMicroLesson } from '../bosLesson';
import type { MicroLesson } from '../../types';
import { CHART_LITERACY_SOURCES } from './chartLiteracySources';
import { createFoundationLesson } from './foundationLessonFactory';

const candles = createFoundationLesson({
  id: 'lesson.chart.candles.001',
  slug: 'bir-mum-bize-ne-soyler',
  conceptKey: 'market.chart.candles',
  skillId: 'skill.chart-literacy',
  competencyId: 'competency.read-ohlc-candle.foundation',
  title: 'Bir mum bize ne söyler?',
  titleEn: 'What does a candlestick tell us?',
  objective: 'Açılış, kapanış, en yüksek ve en düşük fiyatı mum üzerinde gösterir.',
  objectiveEn: 'Identify the open, close, high, and low on a candlestick.',
  minutes: 4,
  hook: 'Tek bir mumun gövdesi ve fitilleri hangi dört fiyatı saklıyor?',
  hookEn: 'Which four prices are contained in a single candle’s body and wicks?',
  explanation: 'Her mum seçilen zaman aralığındaki açılış, en yüksek, en düşük ve kapanış fiyatını özetler. Gövde açılış ile kapanış arasını, fitiller ise dönem içindeki uçları gösterir. Mum yalnızca kendi zaman aralığını anlatır; tek başına sonraki hareketi garanti etmez.',
  explanationEn: 'Each candlestick summarizes the open, high, low, and close for the selected period. The body shows the range between the open and close, while the wicks show the extremes reached during that period. A candle describes only its own timeframe; it does not guarantee the next move.',
  proExplanation: 'OHLC yapısı aynı veriyi taşır; renk yalnız kapanışın açılışa göre yönünü kodlar. Önceki kapanışa göre değişim ile mumun kendi gövde yönü aynı kavram değildir.',
  proExplanationEn: 'OHLC carries the same data; color only encodes the close relative to that candle’s open. Change from the previous close and the candle’s own body direction are not the same concept.',
  misconception: 'Yaygın hata: Uzun yeşil bir mumun sonraki mumun da kesin yükseleceğini gösterdiğini düşünmek.',
  misconceptionEn: 'Common mistake: assuming a long green candle means the next candle will certainly rise too.',
  takeaway: 'Mum dört fiyatı özetler; tahmin değil, seçilen dönemin kaydıdır.',
  takeawayEn: 'A candlestick summarizes four prices; it is a record of the selected period, not a prediction.',
  prerequisiteConceptKeys: ['market.basics.price_formation'],
  relatedConceptKeys: ['market.chart.timeframes', 'market.trend.basics'],
  visualAlt: 'Açılış, kapanış, en yüksek ve en düşük etiketli bir mum şeması',
  visualAltEn: 'Candlestick diagram labelled with open, close, high, and low',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://charts/candle-ohlc-001',
  taskPrompt: 'Şematik mumda dönem içindeki en yüksek ve en düşük fiyatı gösteren parçaları seç.',
  taskPromptEn: 'Select the parts of the schematic candle that show the period’s high and low.',
  taskChoices: [
    { id: 'upper-wick', label: 'Üst fitilin ucu: en yüksek', labelEn: 'Tip of the upper wick: high' },
    { id: 'lower-wick', label: 'Alt fitilin ucu: en düşük', labelEn: 'Tip of the lower wick: low' },
    { id: 'body-color', label: 'Yalnız gövdenin rengi', labelEn: 'The body color only' },
    { id: 'next-candle', label: 'Henüz oluşmamış sonraki mum', labelEn: 'The next candle, which has not formed yet' },
  ],
  taskCorrectIds: ['upper-wick', 'lower-wick'],
  questions: [
    { prompt: 'Bir mum hangi dört temel fiyatı özetler?', promptEn: 'Which four basic prices does a candlestick summarize?', choices: [{ id: 'a', label: 'Açılış, en yüksek, en düşük, kapanış', labelEn: 'Open, high, low, close' }, { id: 'b', label: 'Hedef, stop, komisyon, vergi', labelEn: 'Target, stop, commission, tax' }, { id: 'c', label: 'Bid, ask, hacim, haber', labelEn: 'Bid, ask, volume, news' }], correctId: 'a', explanation: 'Standart mum seçilen dönem için OHLC verisini gösterir.', explanationEn: 'A standard candle shows OHLC data for the selected period.' },
    { prompt: 'Mum gövdesi neyi gösterir?', promptEn: 'What does a candle’s body show?', choices: [{ id: 'a', label: 'Açılış ile kapanış arasını', labelEn: 'The range between open and close' }, { id: 'b', label: 'Yalnız en yüksek fiyatı', labelEn: 'Only the highest price' }, { id: 'c', label: 'Gelecekteki fiyat aralığını', labelEn: 'The future price range' }], correctId: 'a', explanation: 'Gövde açılış ve kapanış arasındaki fiyat farkını görselleştirir.', explanationEn: 'The body visualizes the price difference between open and close.' },
    { prompt: 'Tek bir mum için en doğru yorum hangisidir?', promptEn: 'Which is the most accurate interpretation of a single candle?', choices: [{ id: 'a', label: 'Seçilen dönemi özetler, geleceği garanti etmez', labelEn: 'It summarizes the selected period and does not guarantee the future' }, { id: 'b', label: 'Bir sonraki yönü kesin gösterir', labelEn: 'It shows the next direction with certainty' }, { id: 'c', label: 'Her piyasada aynı süreyi temsil eder', labelEn: 'It represents the same duration in every market' }], correctId: 'a', explanation: 'Mum geçmiş dönem verisidir ve anlamı seçilen zaman aralığına bağlıdır.', explanationEn: 'A candle is historical period data, and its meaning depends on the selected timeframe.' },
  ],
  sources: [CHART_LITERACY_SOURCES.cmeTechnicalAnalysis, CHART_LITERACY_SOURCES.chartLiteracy],
});

const timeframes = createFoundationLesson({
  id: 'lesson.chart.timeframes.001',
  slug: 'zaman-dilimi-neyi-degistirir',
  conceptKey: 'market.chart.timeframes',
  skillId: 'skill.chart-literacy',
  competencyId: 'competency.explain-timeframe-semantics.foundation',
  title: 'Zaman dilimi neyi değiştirir?',
  titleEn: 'What does a timeframe change?',
  objective: 'Aynı piyasanın farklı zaman dilimlerinde farklı yapı gösterebileceğini açıklar.',
  objectiveEn: 'Explain why the same market can show different structures across timeframes.',
  minutes: 4,
  hook: 'Aynı varlık 15 dakikada düşerken günlük grafikte yükseliş yapısında olabilir mi?',
  hookEn: 'Can the same asset fall on a 15-minute chart while its daily chart remains in an upward structure?',
  explanation: 'Zaman dilimi, her mumun kapsadığı süreyi ve görünür yapının ölçeğini değiştirir. Kısa zaman dilimindeki geri çekilme daha geniş zaman diliminde küçük bir dalga olabilir. Bu nedenle yön veya yapı yorumu hangi zaman dilimine ait olduğu belirtilmeden eksiktir.',
  explanationEn: 'A timeframe changes the duration represented by each candle and the scale of the visible structure. A pullback on a short timeframe can be a small wave on a broader one. For that reason, a view on direction or structure is incomplete without naming its timeframe.',
  proExplanation: 'Detection her timeframe içinde bağımsız değerlendirilmelidir. Üst zaman dilimi otomatik olarak doğru veya üstün kabul edilmez; alignment ve conflict ayrı bağlam verileridir.',
  proExplanationEn: 'Detection should be assessed independently within each timeframe. A higher timeframe is not automatically correct or superior; alignment and conflict are separate context signals.',
  misconception: 'Yaygın hata: Bir zaman dilimindeki trend etiketini tüm zaman dilimlerine kopyalamak.',
  misconceptionEn: 'Common mistake: copying a trend label from one timeframe to all others.',
  takeaway: 'Her yapı bir zaman dilimine aittir; farklı ölçekler çelişebilir.',
  takeawayEn: 'Every structure belongs to a timeframe; different scales can conflict.',
  prerequisiteConceptKeys: ['market.chart.candles'],
  relatedConceptKeys: ['market.timeframe.alignment', 'market.trend.basics'],
  visualAlt: 'Aynı fiyat hareketinin 15 dakika, 1 saat ve günlük mumlarla farklı görünümü',
  visualAltEn: 'The same price movement shown with 15-minute, one-hour, and daily candles',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://charts/timeframes-001',
  taskPrompt: '15 dakikalık düşüşe rağmen günlük yükseliş yapısı korunuyorsa hangi iki ifade birlikte doğru olabilir?',
  taskPromptEn: 'If the daily upward structure remains intact despite a 15-minute decline, which two statements can both be true?',
  taskChoices: [
    { id: 'short-pullback', label: '15 dakikada kısa vadeli geri çekilme var', labelEn: 'There is a short-term pullback on the 15-minute chart' },
    { id: 'daily-up', label: 'Günlük yükseliş yapısı henüz bozulmamış olabilir', labelEn: 'The daily upward structure may not be broken yet' },
    { id: 'one-truth', label: 'Yalnız bir zaman dilimi gerçek olabilir', labelEn: 'Only one timeframe can be true' },
    { id: 'guarantee', label: 'Günlük yapı sonraki hareketi garanti eder', labelEn: 'The daily structure guarantees the next move' },
  ],
  taskCorrectIds: ['short-pullback', 'daily-up'],
  questions: [
    { prompt: 'Zaman dilimi en temel olarak neyi belirler?', promptEn: 'What does a timeframe determine most fundamentally?', choices: [{ id: 'a', label: 'Her mumun kapsadığı süreyi', labelEn: 'The duration covered by each candle' }, { id: 'b', label: 'Varlığın gerçek değerini', labelEn: 'The asset’s true value' }, { id: 'c', label: 'İşlemin kesin sonucunu', labelEn: 'The certain result of a trade' }], correctId: 'a', explanation: 'Örneğin 1 saatlik mum bir saatlik fiyat verisini özetler.', explanationEn: 'For example, a one-hour candle summarizes one hour of price data.' },
    { prompt: 'Farklı zaman dilimleri neden farklı yapı gösterebilir?', promptEn: 'Why can different timeframes show different structures?', choices: [{ id: 'a', label: 'Aynı hareketi farklı ölçeklerde topladıkları için', labelEn: 'Because they aggregate the same movement at different scales' }, { id: 'b', label: 'Biri her zaman yanlış olduğu için', labelEn: 'Because one is always wrong' }, { id: 'c', label: 'Fiyat verisi tamamen farklı olduğu için', labelEn: 'Because the price data is entirely different' }], correctId: 'a', explanation: 'Veri aynı piyasadan gelir; örnekleme ve yapısal ölçek farklıdır.', explanationEn: 'The data comes from the same market; the sampling and structural scale differ.' },
    { prompt: 'Bir trend ifadesinde hangi bilgi mutlaka olmalıdır?', promptEn: 'What information must be included in a trend statement?', choices: [{ id: 'a', label: 'Ait olduğu zaman dilimi', labelEn: 'The timeframe it belongs to' }, { id: 'b', label: 'Yalnız mum rengi', labelEn: 'Only the candle color' }, { id: 'c', label: 'Kesin hedef fiyat', labelEn: 'A certain target price' }], correctId: 'a', explanation: 'Trend ve yapı timeframe belirtilmeden bağlamsız kalır.', explanationEn: 'Trend and structure lack context without a stated timeframe.' },
  ],
  sources: [CHART_LITERACY_SOURCES.cmeTechnicalAnalysis, CHART_LITERACY_SOURCES.timeframes],
});

const trend = createFoundationLesson({
  id: 'lesson.chart.trend.001',
  slug: 'trend-yon-mu-yapi-mi',
  conceptKey: 'market.trend.basics',
  skillId: 'skill.chart-literacy',
  competencyId: 'competency.classify-trend-structure.foundation',
  title: 'Trend: yön mü, yapı mı?',
  titleEn: 'Trend: direction or structure?',
  objective: 'Yükseliş, düşüş ve yatay yapı arasındaki temel farkı tanır.',
  objectiveEn: 'Recognize the basic difference between upward, downward, and sideways structures.',
  minutes: 5,
  hook: 'Fiyat bugün yükseldi diye piyasa mutlaka yükseliş trendinde midir?',
  hookEn: 'Does a market have to be in an uptrend just because price rose today?',
  explanation: 'Trend tek bir mumun rengi değil, fiyat salınımlarının zaman içindeki yapısıdır. Genel olarak daha yüksek tepeler ve dipler yükseliş; daha düşük tepeler ve dipler düşüş yapısını destekler. Belirgin ilerleme yoksa piyasa yatay veya geçiş yapısında olabilir.',
  explanationEn: 'A trend is not the color of one candle; it is the structure of price swings over time. In general, higher highs and higher lows support an upward structure, while lower highs and lower lows support a downward structure. Without clear directional progress, the market may be sideways or in transition.',
  proExplanation: 'Trend sınıflaması swing dizisi, seçilen pivot ölçeği ve timeframe’e bağlıdır. Tek indikatör veya tek günlük getiri, yapısal trendin yerine geçmez.',
  proExplanationEn: 'Trend classification depends on the swing sequence, the chosen pivot scale, and the timeframe. A single indicator or one day’s return does not replace structural trend analysis.',
  traderTip: 'Ana trendi önce daha geniş bir zaman diliminde okumak, kısa vadeli gürültü ile ana yapıyı karıştırmayı azaltabilir; daha kısa zaman dilimini detay için kullan. Yükseliş yapısı korunurken sırf fiyat çok yükseldi diye düşüş yönüne geçmek ana yapıya karşı pozisyon almaktır ve ek teyit ile daha sıkı risk kontrolü gerektirir. Üst zaman dilimi otomatik olarak daha doğru değildir.',
  traderTipEn: 'Reading the main trend on a broader timeframe first can reduce confusion between short-term noise and the main structure; use the shorter timeframe for detail. Moving short simply because price has risen a lot while the upward structure remains intact means positioning against the main structure and calls for extra confirmation and tighter risk control. A higher timeframe is not automatically more correct.',
  misconception: 'Yaygın hata: Son mum yeşilse yükseliş trendi, kırmızıysa düşüş trendi demek.',
  misconceptionEn: 'Common mistake: calling the market an uptrend because the last candle is green, or a downtrend because it is red.',
  takeaway: 'Trend bir anlık yön değil, seçilen zaman dilimindeki salınım dizisidir.',
  takeawayEn: 'A trend is not a momentary direction; it is a sequence of swings within a selected timeframe.',
  prerequisiteConceptKeys: ['market.chart.timeframes'],
  relatedConceptKeys: ['market.structure.support_resistance', 'market.structure.bos'],
  visualAlt: 'Yükselen, düşen ve yatay salınım dizilerini karşılaştıran üç grafik',
  visualAltEn: 'Three charts comparing upward, downward, and sideways swing sequences',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://charts/trend-structure-001',
  taskPrompt: 'Yükseliş yapısını destekleyen iki temel salınım özelliğini seç.',
  taskPromptEn: 'Select the two basic swing characteristics that support an upward structure.',
  taskChoices: [
    { id: 'higher-highs', label: 'Daha yüksek tepeler', labelEn: 'Higher highs' },
    { id: 'higher-lows', label: 'Daha yüksek dipler', labelEn: 'Higher lows' },
    { id: 'one-green', label: 'Tek bir yeşil mum', labelEn: 'One green candle' },
    { id: 'fixed-target', label: 'Sabit hedef fiyat', labelEn: 'A fixed target price' },
  ],
  taskCorrectIds: ['higher-highs', 'higher-lows'],
  questions: [
    { prompt: 'Yükseliş yapısını en iyi hangi dizi destekler?', promptEn: 'Which sequence best supports an upward structure?', choices: [{ id: 'a', label: 'Daha yüksek tepeler ve daha yüksek dipler', labelEn: 'Higher highs and higher lows' }, { id: 'b', label: 'Tek bir uzun yeşil mum', labelEn: 'One long green candle' }, { id: 'c', label: 'Her gün aynı kapanış', labelEn: 'The same close every day' }], correctId: 'a', explanation: 'Trend salınımların devam eden yapısıyla değerlendirilir.', explanationEn: 'A trend is assessed through the continuing structure of swings.' },
    { prompt: 'Trend neden zaman dilimiyle birlikte belirtilmelidir?', promptEn: 'Why should a trend be stated together with its timeframe?', choices: [{ id: 'a', label: 'Yapı ölçeğe göre değişebildiği için', labelEn: 'Because structure can change by scale' }, { id: 'b', label: 'Mum renkleri değiştiği için', labelEn: 'Because candle colors change' }, { id: 'c', label: 'Komisyon değiştiği için', labelEn: 'Because commission changes' }], correctId: 'a', explanation: 'Kısa ve uzun zaman dilimleri farklı salınım yapıları gösterebilir.', explanationEn: 'Short and long timeframes can show different swing structures.' },
    { prompt: 'Yatay yapı neyi anlatabilir?', promptEn: 'What can a sideways structure indicate?', choices: [{ id: 'a', label: 'Belirgin yönlü ilerlemenin zayıf olduğunu', labelEn: 'That clear directional progress is weak' }, { id: 'b', label: 'Fiyatın artık değişmeyeceğini', labelEn: 'That price will no longer change' }, { id: 'c', label: 'Kesin dönüş başladığını', labelEn: 'That a reversal has certainly begun' }], correctId: 'a', explanation: 'Yatay yapı, yönlü salınım dizisinin belirgin olmadığını gösterir.', explanationEn: 'A sideways structure shows that a directional swing sequence is not clear.' },
  ],
  sources: [CHART_LITERACY_SOURCES.cmeTechnicalAnalysis, CHART_LITERACY_SOURCES.trend, CHART_LITERACY_SOURCES.timeframes],
});

const supportResistance = createFoundationLesson({
  id: 'lesson.chart.support-resistance.001',
  slug: 'destek-direnc-bolgedir',
  conceptKey: 'market.structure.support_resistance',
  skillId: 'skill.chart-literacy',
  competencyId: 'competency.identify-reaction-zones.foundation',
  title: 'Destek ve direnç neden bölge olarak okunur?',
  titleEn: 'Why are support and resistance read as zones?',
  objective: 'Destek ve direnci tek kesin fiyat yerine tepki alanı olarak değerlendirmenin nedenini açıklar.',
  objectiveEn: 'Explain why support and resistance are often assessed as reaction areas rather than one exact price.',
  minutes: 5,
  hook: 'Fiyat aynı seviyeye her gelişinde tam olarak tek kuruştan mı döner?',
  hookEn: 'Does price reverse at exactly the same cent every time it returns to a level?',
  explanation: 'Destek ve direnç, geçmişte alıcı veya satıcı tepkisinin yoğunlaştığı fiyatları veya alanları tanımlar. Tepkiler her zaman tek bir kusursuz fiyatta oluşmadığı için çoğu durumda bölge yaklaşımı daha gerçekçidir. Bölge tepki ihtimalini gösterir; tutmayı veya kırılmayı garanti etmez.',
  explanationEn: 'Support and resistance describe prices or areas where buyer or seller reactions have concentrated in the past. Because reactions do not always occur at one perfect price, a zone is often a more realistic model. A zone shows the possibility of a reaction; it does not guarantee a hold or a break.',
  proExplanation: 'Bölge genişliği volatilite, wick dağılımı, kapanış kümeleri ve test sayısıyla değerlendirilir. Çok test edilmiş seviye otomatik olarak daha güçlü kabul edilmez; likidite tüketimi ve bağlam önemlidir.',
  proExplanationEn: 'Zone width can be assessed through volatility, wick distribution, clusters of closes, and number of tests. A heavily tested level is not automatically stronger; liquidity consumption and context matter.',
  traderTip: 'Önce daha geniş zaman diliminde belirgin tepki alanlarını işaretleyip, sonra daha kısa zaman diliminde bölgeyi hassaslaştırmak grafikteki gürültüyü azaltabilir. Bölgeyi tek bir fiyata sıkıştırma ve test sayısını tek başına güç kanıtı sayma. Üst zaman dilimindeki bölge de fiyatı durdurmayı garanti etmez.',
  traderTipEn: 'Marking clear reaction areas on a broader timeframe first and then refining the zone on a shorter timeframe can reduce chart noise. Do not compress the zone into one exact price or treat the number of tests alone as proof of strength. A higher-timeframe zone still does not guarantee that price will stop there.',
  misconception: 'Yaygın hata: Çizilen seviyenin fiyatı kesin durduracağını varsaymak.',
  misconceptionEn: 'Common mistake: assuming a drawn level will stop price with certainty.',
  takeaway: 'Destek ve direnç kesin duvar değildir; tek fiyat veya bölge olarak çizilse de geçmiş tepkiyi gösteren bağlamsal referanslardır.',
  takeawayEn: 'Support and resistance are not certain walls; whether drawn as a price or a zone, they are contextual references to past reactions.',
  prerequisiteConceptKeys: ['market.trend.basics'],
  relatedConceptKeys: ['market.structure.bos', 'market.structure.liquidity'],
  visualAlt: 'Birden fazla fitil ve kapanışı kapsayan destek ve direnç bölgeleri',
  visualAltEn: 'Support and resistance zones covering multiple wicks and closes',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://charts/support-resistance-zone-001',
  taskPrompt: 'Bir tepki bölgesini değerlendirirken en anlamlı iki kanıtı seç.',
  taskPromptEn: 'Select the two most meaningful pieces of evidence when assessing a reaction zone.',
  taskChoices: [
    { id: 'reactions', label: 'Aynı alanda görülen birden fazla anlamlı tepki', labelEn: 'Multiple meaningful reactions in the same area' },
    { id: 'closes-wicks', label: 'Kapanış ve fitillerin oluşturduğu fiyat aralığı', labelEn: 'The price range formed by closes and wicks' },
    { id: 'pixel-line', label: 'Tek bir piksel kalınlığında kesin çizgi', labelEn: 'A certain line one pixel thick' },
    { id: 'guarantee', label: 'Bölgenin mutlaka tutacağı varsayımı', labelEn: 'Assuming the zone must hold' },
  ],
  taskCorrectIds: ['reactions', 'closes-wicks'],
  questions: [
    { prompt: 'Destek veya direnç neden bölge olarak ele alınır?', promptEn: 'Why are support and resistance treated as zones?', choices: [{ id: 'a', label: 'Tepkiler çoğu zaman bir fiyat aralığında oluştuğu için', labelEn: 'Because reactions often form across a price range' }, { id: 'b', label: 'Grafikte çizgi çizilemediği için', labelEn: 'Because a chart cannot contain lines' }, { id: 'c', label: 'Fiyat hiç değişmediği için', labelEn: 'Because price never changes' }], correctId: 'a', explanation: 'Emir ve tepkiler tek bir kusursuz fiyata sıkışmak zorunda değildir.', explanationEn: 'Orders and reactions do not have to cluster at one perfect price.' },
    { prompt: 'Bir direnç bölgesi neyi garanti eder?', promptEn: 'What does a resistance zone guarantee?', choices: [{ id: 'a', label: 'Hiçbir sonucu garanti etmez', labelEn: 'It guarantees no outcome' }, { id: 'b', label: 'Kesin düşüşü', labelEn: 'A certain decline' }, { id: 'c', label: 'Kesin kırılımı', labelEn: 'A certain breakout' }], correctId: 'a', explanation: 'Bölge geçmiş tepkiyi gösterir; gelecek sonuç bağlama bağlıdır.', explanationEn: 'A zone shows past reaction; the future outcome depends on context.' },
    { prompt: 'Bölge kırılımında hangisi daha anlamlıdır?', promptEn: 'What is more meaningful when a zone is crossed?', choices: [{ id: 'a', label: 'Seviye, kapanış ve bağlamı birlikte değerlendirmek', labelEn: 'Assessing the level, the close, and the context together' }, { id: 'b', label: 'Yalnız anlık fitile bakmak', labelEn: 'Looking only at an instant wick' }, { id: 'c', label: 'Çizginin rengini değiştirmek', labelEn: 'Changing the color of the line' }], correctId: 'a', explanation: 'Tek taşma yerine yapısal seviye ve teyit birlikte okunur.', explanationEn: 'Rather than one overshoot, the structural level and confirmation should be read together.' },
  ],
  sources: [CHART_LITERACY_SOURCES.cmeTechnicalAnalysis, CHART_LITERACY_SOURCES.supportResistance, CHART_LITERACY_SOURCES.timeframes],
});

const choch = createFoundationLesson({
  id: 'lesson.market-structure.choch.001',
  slug: 'choch-degisim-ihtimali',
  conceptKey: 'market.structure.choch',
  skillId: 'skill.market-structure',
  competencyId: 'competency.identify-choch.intermediate',
  title: 'CHoCH: Değişim ihtimali nasıl okunur?',
  titleEn: 'CHoCH: How do we read the possibility of change?',
  objective: 'Karakter değişimini kesin trend dönüşü iddiasından ayırır.',
  objectiveEn: 'Distinguish a change of character from a claim of certain trend reversal.',
  minutes: 5,
  learningStage: 'intermediate',
  hook: 'Mevcut salınım düzeninin ilk kez bozulması kesin trend dönüşü müdür?',
  hookEn: 'Does the first break in an existing swing pattern mean a trend reversal is certain?',
  explanation: 'CHoCH, mevcut piyasa davranışında olası bir karakter değişimine işaret eden yapısal gözlemdir. Örneğin yükseliş dizisinde korunan anlamlı bir dibin kaybedilmesi değişim ihtimalini artırabilir. Bu, yeni yönün kesinleştiği anlamına gelmez. CHoCH etiketi ve eşikleri kullanılan metodolojiye göre değişebilir.',
  explanationEn: 'CHoCH is a structural observation that points to a possible change in current market behavior. For example, losing a meaningful protected low in an upward sequence can increase the possibility of change. It does not mean the new direction is confirmed. CHoCH labels and thresholds can vary by methodology.',
  proExplanation: 'CHoCH değerlendirmesi karşı-trend yapısal ihlal, swing önemi, kapanış teyidi, displacement ve timeframe bağlamını birlikte kullanır. Devam teyidi gelmeden reversal olarak etiketlenmemelidir.',
  proExplanationEn: 'CHoCH assessment combines a counter-trend structural violation, swing significance, close confirmation, displacement, and timeframe context. It should not be labelled a reversal before continuation confirmation arrives.',
  misconception: 'Yaygın hata: İlk karşı yönlü kırılımı kesin trend dönüşü veya otomatik işlem sinyali saymak.',
  misconceptionEn: 'Common mistake: treating the first counter-direction break as a certain trend reversal or an automatic trade signal.',
  takeaway: 'CHoCH kesin dönüş değil, mevcut yapının değişebileceğine dair izlenmesi gereken kanıttır.',
  takeawayEn: 'CHoCH is not a certain reversal; it is evidence that the current structure may be changing and deserves observation.',
  prerequisiteConceptKeys: ['market.structure.bos'],
  relatedConceptKeys: ['market.trend.basics', 'market.timeframe.alignment'],
  visualAlt: 'Yükseliş dizisinde korunan dibin kaybını ve olası karakter değişimini gösteren grafik',
  visualAltEn: 'Chart showing loss of a protected low in an upward sequence and a possible change of character',
  taskKind: 'chart_identification',
  taskAssetRef: 'edu://charts/choch-001',
  taskPrompt: 'Olası CHoCH değerlendirmesinde gerekli iki kanıtı seç.',
  taskPromptEn: 'Select the two pieces of evidence needed when assessing a possible CHoCH.',
  taskChoices: [
    { id: 'protected-swing', label: 'Mevcut yapıda korunan anlamlı salınım seviyesi', labelEn: 'A meaningful swing level protected by the current structure' },
    { id: 'counter-close', label: 'Karşı yönde yapısal kapanış teyidi', labelEn: 'A structural close confirmation in the opposing direction' },
    { id: 'one-wick', label: 'Rastgele tek fitil', labelEn: 'One random wick' },
    { id: 'certainty', label: 'Kesin dönüş varsayımı', labelEn: 'An assumption of certain reversal' },
  ],
  taskCorrectIds: ['protected-swing', 'counter-close'],
  questions: [
    { prompt: 'CHoCH en doğru neyi ifade eder?', promptEn: 'What does CHoCH describe most accurately?', choices: [{ id: 'a', label: 'Olası karakter değişimine dair yapısal gözlemi', labelEn: 'A structural observation of a possible change of character' }, { id: 'b', label: 'Kesin trend dönüşünü', labelEn: 'A certain trend reversal' }, { id: 'c', label: 'Otomatik alım veya satım emrini', labelEn: 'An automatic buy or sell order' }], correctId: 'a', explanation: 'CHoCH değişim ihtimalini gösterir; kesinlik veya talimat değildir.', explanationEn: 'CHoCH shows the possibility of change; it is neither certainty nor an instruction.' },
    { prompt: 'Yükseliş yapısında hangi olay olası CHoCH için anlamlı olabilir?', promptEn: 'In an upward structure, which event can be meaningful for a possible CHoCH?', choices: [{ id: 'a', label: 'Korunan anlamlı dibin karşı yönlü kaybı', labelEn: 'A counter-direction loss of a meaningful protected low' }, { id: 'b', label: 'Tek bir küçük yeşil mum', labelEn: 'One small green candle' }, { id: 'c', label: 'Spreadin daralması tek başına', labelEn: 'A narrower spread by itself' }], correctId: 'a', explanation: 'Mevcut yapıyı koruyan swing seviyesinin ihlali karakter değişimi kanıtıdır.', explanationEn: 'Violation of the swing level protecting the current structure is evidence of a change of character.' },
    { prompt: 'CHoCH görüldükten sonra en sağlıklı yaklaşım hangisidir?', promptEn: 'What is the healthiest approach after observing a CHoCH?', choices: [{ id: 'a', label: 'Devam teyidi ve diğer bağlam kanıtlarını izlemek', labelEn: 'Monitor continuation confirmation and other context evidence' }, { id: 'b', label: 'Dönüşü kesin kabul etmek', labelEn: 'Treat the reversal as certain' }, { id: 'c', label: 'Risk değerlendirmesini bırakmak', labelEn: 'Stop assessing risk' }], correctId: 'a', explanation: 'Yeni yön için ek yapı, zaman dilimi ve risk kanıtı gerekir.', explanationEn: 'A new direction needs additional structural, timeframe, and risk evidence.' },
  ],
  sources: [CHART_LITERACY_SOURCES.cmeTechnicalAnalysis, CHART_LITERACY_SOURCES.marketStructure],
});

export const WAVE1_CHART_LITERACY_LESSONS: readonly MicroLesson[] = [
  candles,
  timeframes,
  trend,
  supportResistance,
  bosMicroLesson,
  choch,
];
