import { createFoundationLesson } from './foundationLessonFactory';
import { WAVE1_SOURCES } from './sources';

const priceFormation = createFoundationLesson({
  id: 'lesson.market.price-formation.001',
  slug: 'fiyat-piyasada-nasil-olusur',
  conceptKey: 'market.basics.price_formation',
  skillId: 'skill.market-foundations',
  competencyId: 'competency.explain-price-formation.foundation',
  title: 'Fiyat piyasada nasıl oluşur?',
  titleEn: 'How is price formed in the market?',
  objective: 'Alıcı ve satıcı etkileşiminin fiyat oluşumundaki rolünü açıklar.',
  objectiveEn: 'Explain the role of buyer and seller interaction in price formation.',
  minutes: 4,
  hook: 'Ekrandaki fiyatı kim belirliyor: şirket, borsa, yoksa yatırımcılar mı?',
  hookEn: 'Who sets the price on screen: the company, the exchange, or investors?',
  explanation: 'Piyasa fiyatı, alıcıların ödemeye razı olduğu fiyatlarla satıcıların kabul ettiği fiyatların eşleşmesiyle oluşur. Yeni emirler ve yeni bilgiler geldikçe bu denge değişir. Son işlem fiyatı yalnızca gerçekleşmiş son eşleşmeyi gösterir; gelecekteki fiyatı garanti etmez.',
  explanationEn: 'Market price forms when the prices buyers are willing to pay match the prices sellers are willing to accept. As new orders and new information arrive, that balance changes. The last traded price only shows the most recent completed match; it does not guarantee a future price.',
  proExplanation: 'Fiyat keşfi, emir defterindeki arz ve talebin zaman önceliği ve fiyat önceliği altında eşleşmesiyle gerçekleşir. Görülen son fiyat, mevcut likidite dağılımının tamamını temsil etmez.',
  proExplanationEn: 'Price discovery happens as supply and demand in the order book match under price priority and time priority. The visible last price does not represent the full current liquidity distribution.',
  misconception: 'Yaygın hata: Fiyatı tek bir kurumun sabit biçimde belirlediğini düşünmek.',
  misconceptionEn: 'Common mistake: thinking a single institution fixes the price in a static way.',
  takeaway: 'Piyasa fiyatı sabit bir etiket değil, alıcı ve satıcıların sürekli değişen eşleşmesidir.',
  takeawayEn: 'Market price is not a fixed label; it is the constantly changing match between buyers and sellers.',
  prerequisiteConceptKeys: [],
  relatedConceptKeys: ['market.structure.liquidity', 'market.microstructure.bid_ask'],
  visualAlt: 'Farklı alış ve satış tekliflerinin eşleşerek son fiyatı oluşturduğu şema',
  visualAltEn: 'Diagram showing different buy and sell offers matching to form the last price',
  taskPrompt: 'Hangi durum fiyat keşfini en doğru anlatır?',
  taskPromptEn: 'Which situation best describes price discovery?',
  taskChoices: [
    { id: 'match', label: 'Alış ve satış emirlerinin ortak bir fiyatta eşleşmesi', labelEn: 'Buy and sell orders matching at a shared price' },
    { id: 'company', label: 'Şirketin her dakika yeni bir fiyat açıklaması', labelEn: 'The company announcing a new price every minute' },
    { id: 'last', label: 'Dünkü kapanışın bugünkü fiyatı garanti etmesi', labelEn: "Yesterday's close guaranteeing today's price" },
  ],
  taskCorrectIds: ['match'],
  questions: [
    { prompt: 'Piyasa fiyatının temel oluşum mekanizması nedir?', promptEn: 'What is the basic mechanism of market price formation?', choices: [{ id: 'a', label: 'Alıcı ve satıcı emirlerinin eşleşmesi', labelEn: 'Matching buyer and seller orders' }, { id: 'b', label: 'Sabit devlet tarifesi', labelEn: 'A fixed government tariff' }, { id: 'c', label: 'Yalnız şirket yönetiminin kararı', labelEn: "Only the company's management decision" }], correctId: 'a', explanation: 'İşlem fiyatı, uyumlu alış ve satış emirlerinin eşleşmesiyle oluşur.', explanationEn: 'The transaction price forms when compatible buy and sell orders match.' },
    { prompt: 'Son işlem fiyatı neyi gösterir?', promptEn: 'What does the last traded price show?', choices: [{ id: 'a', label: 'Gelecekteki kesin fiyatı', labelEn: 'The certain future price' }, { id: 'b', label: 'Gerçekleşmiş son eşleşmenin fiyatını', labelEn: 'The price of the latest completed match' }, { id: 'c', label: 'Tüm yatırımcıların ortak tahminini', labelEn: "All investors' shared forecast" }], correctId: 'b', explanation: 'Son fiyat geçmişte gerçekleşen en son işlemdir; sonraki işlemi garanti etmez.', explanationEn: 'The last price is the most recent completed trade; it does not guarantee the next trade.' },
    { prompt: 'Yeni bilgi ve emirler geldiğinde ne olabilir?', promptEn: 'What can happen when new information and orders arrive?', choices: [{ id: 'a', label: 'Alış-satış dengesi ve fiyat değişebilir', labelEn: 'The buy-sell balance and price can change' }, { id: 'b', label: 'Fiyat hiçbir zaman değişmez', labelEn: 'Price never changes' }, { id: 'c', label: 'Sadece işlem adedi değişir', labelEn: 'Only the trade count changes' }], correctId: 'a', explanation: 'Yeni bilgi, alıcı ve satıcıların fiyat tercihlerini değiştirebilir.', explanationEn: 'New information can change the price preferences of buyers and sellers.' },
  ],
  sources: [WAVE1_SOURCES.markets],
});

const instruments = createFoundationLesson({
  id: 'lesson.market.instruments.001',
  slug: 'piyasa-araclari-ayni-degildir',
  conceptKey: 'market.basics.instruments',
  skillId: 'skill.market-foundations',
  competencyId: 'competency.distinguish-market-instruments.foundation',
  title: 'Hisse, tahvil, döviz ve emtia aynı şey değildir',
  titleEn: 'Stocks, bonds, currencies, and commodities are not the same',
  objective: 'Temel piyasa araçlarının neyi temsil ettiğini ayırt eder.',
  objectiveEn: 'Distinguish what the main market instruments represent.',
  minutes: 5,
  hook: 'Altın, bir şirket hissesi ve devlet tahvili aynı riskle mi hareket eder?',
  hookEn: 'Do gold, a company share, and a government bond move with the same risk?',
  explanation: 'Hisse bir şirkette ortaklık payını, tahvil bir borç ilişkisini, döviz bir para biriminin diğerine göre değerini, emtia ise altın veya petrol gibi bir malı temsil eder. Getiri kaynakları, riskleri, işlem saatleri ve fiyatlarını etkileyen veriler farklıdır.',
  explanationEn: 'A stock represents ownership in a company, a bond represents a lending relationship, foreign exchange represents one currency relative to another, and a commodity represents a good such as gold or oil. Their return drivers, risks, trading hours, and relevant data can differ.',
  proExplanation: 'Varlık sınıfları nakit akışı hakkı, vade, kredi riski, para politikası duyarlılığı ve taşıma maliyeti açısından ayrışır. Aynı analiz çerçevesi her araca değişmeden uygulanamaz.',
  proExplanationEn: 'Asset classes differ by cash-flow rights, maturity, credit risk, sensitivity to monetary policy, and carrying costs. The same analysis framework cannot be applied unchanged to every instrument.',
  misconception: 'Yaygın hata: Grafiği olan her ürünü aynı analiz ve risk kurallarıyla değerlendirmek.',
  misconceptionEn: 'Common mistake: treating every charted product with the same analysis and risk rules.',
  takeaway: 'Önce neye sahip olduğunu bil; araç türü, hangi riskleri taşıdığını değiştirir.',
  takeawayEn: 'Know what you own first; the instrument type changes the risks you carry.',
  prerequisiteConceptKeys: ['market.basics.price_formation'],
  relatedConceptKeys: ['portfolio.diversification', 'risk.basics'],
  visualAlt: 'Hisse, tahvil, döviz ve emtianın temsil ettiği hakları karşılaştıran kartlar',
  visualAltEn: 'Cards comparing the rights represented by stocks, bonds, currencies, and commodities',
  taskPrompt: 'Hangisi bir şirkette ortaklık payını temsil eder?',
  taskPromptEn: 'Which one represents ownership in a company?',
  taskChoices: [{ id: 'stock', label: 'Hisse senedi', labelEn: 'Stock' }, { id: 'bond', label: 'Tahvil', labelEn: 'Bond' }, { id: 'fx', label: 'Döviz çifti', labelEn: 'Currency pair' }],
  taskCorrectIds: ['stock'],
  questions: [
    { prompt: 'Tahvil en temel hâliyle neyi temsil eder?', promptEn: 'At the most basic level, what does a bond represent?', choices: [{ id: 'a', label: 'Borç ilişkisini', labelEn: 'A lending relationship' }, { id: 'b', label: 'Şirkette oy hakkını her zaman', labelEn: 'Always voting rights in a company' }, { id: 'c', label: 'Fiziksel emtiayı', labelEn: 'A physical commodity' }], correctId: 'a', explanation: 'Tahvil, ihraççı ile yatırımcı arasında borçlanma ilişkisidir.', explanationEn: 'A bond is a borrowing relationship between the issuer and the investor.' },
    { prompt: 'Döviz çiftinin fiyatı neyi gösterir?', promptEn: 'What does the price of a currency pair show?', choices: [{ id: 'a', label: 'Bir şirketin kârını', labelEn: "A company's profit" }, { id: 'b', label: 'Bir para biriminin diğerine göre değerini', labelEn: 'The value of one currency relative to another' }, { id: 'c', label: 'Tahvil kuponunu', labelEn: 'A bond coupon' }], correctId: 'b', explanation: 'Döviz çifti iki para birimi arasındaki göreli değeri ifade eder.', explanationEn: 'A currency pair expresses the relative value between two currencies.' },
    { prompt: 'Farklı araç türlerinde neden aynı analiz körlemesine kullanılmamalı?', promptEn: 'Why should the same analysis not be applied blindly to different instrument types?', choices: [{ id: 'a', label: 'Risk ve fiyat sürücüleri farklı olduğu için', labelEn: 'Because risks and price drivers differ' }, { id: 'b', label: 'Grafikleri olmadığı için', labelEn: 'Because they have no charts' }, { id: 'c', label: 'Hepsinin fiyatı sabit olduğu için', labelEn: 'Because all prices are fixed' }], correctId: 'a', explanation: 'Araçların ekonomik yapısı, riskleri ve fiyat sürücüleri farklıdır.', explanationEn: 'Instruments have different economic structures, risks, and price drivers.' },
  ],
  sources: [WAVE1_SOURCES.products],
});

const liquidity = createFoundationLesson({
  id: 'lesson.market.liquidity.001',
  slug: 'likidite-neden-onemlidir',
  conceptKey: 'market.structure.liquidity',
  skillId: 'skill.market-foundations',
  competencyId: 'competency.explain-liquidity.foundation',
  title: 'Likidite neden önemlidir?',
  titleEn: 'Why does liquidity matter?',
  objective: 'Likiditenin işlem kolaylığı, fiyat etkisi ve riskle ilişkisini açıklar.',
  objectiveEn: 'Explain how liquidity relates to ease of trading, price impact, and risk.',
  minutes: 4,
  hook: 'Bir varlığı ekrandaki fiyattan hemen satabileceğinden emin misin?',
  hookEn: 'Are you sure you can immediately sell an asset at the price shown on screen?',
  explanation: 'Likidite, bir varlığın önemli fiyat etkisi yaratmadan ne kadar kolay ve hızlı alınıp satılabildiğini anlatır. Düşük likiditede karşı taraf bulmak zorlaşabilir, spread genişleyebilir ve gerçekleşme fiyatı beklenenden uzaklaşabilir.',
  explanationEn: 'Liquidity describes how easily and quickly an asset can be bought or sold without creating a significant price impact. In low liquidity, finding the other side can be harder, spreads can widen, and the execution price can move away from expectations.',
  proExplanation: 'Likidite yalnız hacim değildir; emir defteri derinliği, spread, piyasa etkisi ve farklı büyüklüklerde gerçekleşebilirlik birlikte değerlendirilir.',
  proExplanationEn: 'Liquidity is not just volume; order book depth, spread, market impact, and executability at different sizes are assessed together.',
  misconception: 'Yaygın hata: İşlem hacmi görülen her piyasanın her anda likit olduğunu varsaymak.',
  misconceptionEn: 'Common mistake: assuming every market with visible trading volume is liquid at every moment.',
  takeaway: 'Likidite, işlem yapabilmekten çok istediğin büyüklüğü beklediğin fiyata yakın gerçekleştirebilme meselesidir.',
  takeawayEn: 'Liquidity is less about whether trading is possible and more about executing the size you want near the price you expect.',
  prerequisiteConceptKeys: ['market.basics.price_formation'],
  relatedConceptKeys: ['market.microstructure.bid_ask', 'market.execution.slippage'],
  visualAlt: 'Derin ve sığ iki emir defterinin fiyat etkisini karşılaştıran şema',
  visualAltEn: 'Diagram comparing price impact in a deep order book and a shallow order book',
  taskPrompt: 'Hangisi düşük likiditeye en güçlü işarettir?',
  taskPromptEn: 'Which is the strongest sign of low liquidity?',
  taskChoices: [{ id: 'wide', label: 'Geniş spread ve sığ emir defteri', labelEn: 'Wide spread and a shallow order book' }, { id: 'tight', label: 'Dar spread ve çok sayıda karşı emir', labelEn: 'Tight spread and many opposing orders' }, { id: 'logo', label: 'Varlığın tanınmış bir logosunun olması', labelEn: 'The asset having a recognizable logo' }],
  taskCorrectIds: ['wide'],
  questions: [
    { prompt: 'Likidite en çok neyi ifade eder?', promptEn: 'What does liquidity mainly describe?', choices: [{ id: 'a', label: 'Kolay ve sınırlı fiyat etkisiyle alım-satımı', labelEn: 'Buying and selling with ease and limited price impact' }, { id: 'b', label: 'Fiyatın her zaman yükselmesini', labelEn: 'Price always rising' }, { id: 'c', label: 'Şirketin kârını', labelEn: "A company's profit" }], correctId: 'a', explanation: 'Likidite işlem kolaylığı ve işlem sırasında oluşan fiyat etkisiyle ilgilidir.', explanationEn: 'Liquidity is about ease of trading and the price impact created during trading.' },
    { prompt: 'Düşük likiditede hangi risk artabilir?', promptEn: 'Which risk can increase in low liquidity?', choices: [{ id: 'a', label: 'Beklenen fiyattan uzak gerçekleşme', labelEn: 'Execution far from the expected price' }, { id: 'b', label: 'Fiyatın sabit kalması', labelEn: 'Price staying fixed' }, { id: 'c', label: 'Her emrin ücretsiz olması', labelEn: 'Every order becoming free' }], correctId: 'a', explanation: 'Sığ piyasada emir, mevcut fiyat seviyelerini tüketerek daha kötü fiyatlardan gerçekleşebilir.', explanationEn: 'In a shallow market, an order can consume available levels and execute at worse prices.' },
    { prompt: 'Likidite sadece işlem hacmi midir?', promptEn: 'Is liquidity only trading volume?', choices: [{ id: 'a', label: 'Evet', labelEn: 'Yes' }, { id: 'b', label: 'Hayır; spread, derinlik ve fiyat etkisi de önemlidir', labelEn: 'No; spread, depth, and price impact matter too' }, { id: 'c', label: 'Sadece piyasa saatidir', labelEn: 'It is only market hours' }], correctId: 'b', explanation: 'Hacim tek başına gerçekleşme kalitesini ve derinliği göstermez.', explanationEn: 'Volume alone does not show execution quality or depth.' },
  ],
  sources: [WAVE1_SOURCES.liquidity],
});

const bidAsk = createFoundationLesson({
  id: 'lesson.market.bid-ask.001',
  slug: 'bid-ask-spread-nedir',
  conceptKey: 'market.microstructure.bid_ask',
  skillId: 'skill.market-foundations',
  competencyId: 'competency.read-bid-ask.foundation',
  title: 'Bid, ask ve spread nedir?',
  titleEn: 'What are bid, ask, and spread?',
  objective: 'Alış ve satış fiyatı arasındaki farkı ve spread maliyetini tanır.',
  objectiveEn: 'Recognize the difference between buy and sell quotes and the cost represented by spread.',
  minutes: 4,
  hook: 'Bir varlığı aldığın anda neden küçük bir eksi görebilirsin?',
  hookEn: 'Why might you see a small loss right after buying an asset?',
  explanation: 'Bid, alıcının ödemeye hazır olduğu en yüksek fiyatı; ask, satıcının kabul ettiği en düşük fiyatı gösterir. Ask ile bid arasındaki fark spread’dir. Piyasa emriyle alım genellikle ask tarafına, satım bid tarafına yakın gerçekleşir.',
  explanationEn: 'Bid shows the highest price a buyer is currently willing to pay; ask shows the lowest price a seller is willing to accept. The difference between ask and bid is the spread. A market buy usually executes near the ask side, while a market sell usually executes near the bid side.',
  proExplanation: 'Spread, anlık likidite ve işlem maliyetinin görünür parçalarından biridir. Emir büyüklüğü mevcut derinliği aşarsa gerçekleşen ortalama fiyat en iyi bid/ask seviyesinden uzaklaşabilir.',
  proExplanationEn: 'Spread is one visible part of current liquidity and transaction cost. If order size exceeds available depth, the average execution price can move away from the best bid or ask.',
  misconception: 'Yaygın hata: Son işlem fiyatının hem anlık alış hem satış fiyatı olduğunu düşünmek.',
  misconceptionEn: 'Common mistake: thinking the last traded price is both the current buying and selling price.',
  takeaway: 'Bid ve ask iki farklı taraftır; aralarındaki spread işlemin görünür maliyetlerinden biridir.',
  takeawayEn: 'Bid and ask are two different sides; the spread between them is one visible cost of trading.',
  prerequisiteConceptKeys: ['market.structure.liquidity'],
  relatedConceptKeys: ['market.execution.order_types', 'market.execution.slippage'],
  visualAlt: 'Bid 99, ask 101 ve aradaki 2 birim spreadi gösteren emir ekranı',
  visualAltEn: 'Order screen showing bid 99, ask 101, and the 2-point spread between them',
  taskPrompt: 'Bid 99 ve ask 101 ise spread kaçtır?',
  taskPromptEn: 'If bid is 99 and ask is 101, what is the spread?',
  taskChoices: [{ id: 'two', label: '2', labelEn: '2' }, { id: 'one', label: '1', labelEn: '1' }, { id: 'twohundred', label: '200', labelEn: '200' }],
  taskCorrectIds: ['two'],
  questions: [
    { prompt: 'Bid neyi gösterir?', promptEn: 'What does bid show?', choices: [{ id: 'a', label: 'Alıcının ödemeye hazır olduğu en yüksek fiyatı', labelEn: 'The highest price a buyer is willing to pay' }, { id: 'b', label: 'Satıcının istediği en düşük fiyatı', labelEn: 'The lowest price a seller wants' }, { id: 'c', label: 'Dünkü kapanışı', labelEn: "Yesterday's close" }], correctId: 'a', explanation: 'Bid, mevcut en iyi alış teklifidir.', explanationEn: 'Bid is the current best buy offer.' },
    { prompt: 'Ask neyi gösterir?', promptEn: 'What does ask show?', choices: [{ id: 'a', label: 'En iyi alış teklifini', labelEn: 'The best buy offer' }, { id: 'b', label: 'Satıcının kabul ettiği en düşük fiyatı', labelEn: 'The lowest price a seller is willing to accept' }, { id: 'c', label: 'Ortalama hacmi', labelEn: 'Average volume' }], correctId: 'b', explanation: 'Ask, mevcut en iyi satış teklifidir.', explanationEn: 'Ask is the current best sell offer.' },
    { prompt: 'Spread nedir?', promptEn: 'What is spread?', choices: [{ id: 'a', label: 'Ask ile bid arasındaki fark', labelEn: 'The difference between ask and bid' }, { id: 'b', label: 'Günlük en yüksek ile en düşük farkı her zaman', labelEn: 'Always the daily high-low range' }, { id: 'c', label: 'Yalnız komisyon', labelEn: 'Only commission' }], correctId: 'a', explanation: 'Spread mevcut en iyi satış ve alış teklifleri arasındaki farktır.', explanationEn: 'Spread is the difference between the current best sell and buy offers.' },
  ],
  sources: [WAVE1_SOURCES.bidAsk],
});

const orderTypes = createFoundationLesson({
  id: 'lesson.market.order-types.001',
  slug: 'piyasa-limit-stop-emirleri',
  conceptKey: 'market.execution.order_types',
  skillId: 'skill.market-foundations',
  competencyId: 'competency.distinguish-order-types.foundation',
  title: 'Piyasa, limit ve stop emirleri',
  titleEn: 'Market, limit, and stop orders',
  objective: 'Emir türlerinin fiyat ve gerçekleşme açısından temel farklarını ayırt eder.',
  objectiveEn: 'Distinguish the basic differences between order types in price control and execution.',
  minutes: 5,
  hook: 'Hız mı daha önemli, fiyat kontrolü mü? Aynı emir ikisini birden garanti etmez.',
  hookEn: 'Which matters more: speed or price control? The same order does not guarantee both.',
  explanation: 'Piyasa emri hızlı gerçekleşmeyi amaçlar fakat fiyatı garanti etmez. Limit emri belirlenen fiyat veya daha iyisinde gerçekleşebilir fakat hiç gerçekleşmeyebilir. Stop emri stop fiyatına ulaşıldığında tetiklenir ve çoğu standart yapıda piyasa emrine dönüşür.',
  explanationEn: 'A market order aims for fast execution but does not guarantee price. A limit order can execute at the set price or better, but it may not execute at all. A stop order is triggered when the stop price is reached and, in many standard forms, becomes a market order.',
  proExplanation: 'Emir türü seçimi execution certainty ile price certainty arasında bir tercihtir. Stop-limit gibi varyantlarda tetiklenme sonrası limit kontrolü bulunur ancak gerçekleşmeme riski artar.',
  proExplanationEn: 'Choosing an order type is a tradeoff between execution certainty and price certainty. Variants such as stop-limit add limit control after triggering, but increase non-execution risk.',
  misconception: 'Yaygın hata: Stop fiyatının kesin gerçekleşme fiyatı olduğunu düşünmek.',
  misconceptionEn: 'Common mistake: thinking the stop price is the guaranteed execution price.',
  takeaway: 'Piyasa emri fiyatı, limit emri gerçekleşmeyi garanti etmez; stop fiyatı da çoğu zaman yalnızca tetikleyicidir.',
  takeawayEn: 'A market order does not guarantee price, a limit order does not guarantee execution, and a stop price is often only a trigger.',
  prerequisiteConceptKeys: ['market.microstructure.bid_ask'],
  relatedConceptKeys: ['market.execution.slippage', 'risk.stop_orders'],
  taskPrompt: 'Belirli bir fiyattan daha pahalı almamak isteyen kişi hangi temel emir türünü düşünür?',
  taskPromptEn: 'Which basic order type would someone consider if they do not want to buy above a set price?',
  taskChoices: [{ id: 'limit', label: 'Limit emir', labelEn: 'Limit order' }, { id: 'market', label: 'Piyasa emri', labelEn: 'Market order' }, { id: 'none', label: 'Emir türü fark etmez', labelEn: 'Order type does not matter' }],
  taskCorrectIds: ['limit'],
  questions: [
    { prompt: 'Piyasa emri neyi garanti etmez?', promptEn: 'What does a market order not guarantee?', choices: [{ id: 'a', label: 'Gerçekleşme fiyatını', labelEn: 'The execution price' }, { id: 'b', label: 'Emrin sisteme iletilmesini', labelEn: 'That the order is sent to the system' }, { id: 'c', label: 'Bir emir türü olmasını', labelEn: 'That it is an order type' }], correctId: 'a', explanation: 'Piyasa emri gerçekleşmeyi hedefler, ancak görülen son fiyatı garanti etmez.', explanationEn: 'A market order targets execution, but it does not guarantee the last price seen on screen.' },
    { prompt: 'Limit emrinin temel riski nedir?', promptEn: 'What is the main risk of a limit order?', choices: [{ id: 'a', label: 'Belirlenen koşul oluşmazsa gerçekleşmemesi', labelEn: 'It may not execute if the condition is not met' }, { id: 'b', label: 'Her fiyattan gerçekleşmesi', labelEn: 'It executes at any price' }, { id: 'c', label: 'Stop emrine dönüşmesi', labelEn: 'It turns into a stop order' }], correctId: 'a', explanation: 'Piyasa limit seviyesine gelmezse veya yeterli karşı emir yoksa emir gerçekleşmeyebilir.', explanationEn: 'If the market does not reach the limit level or there is not enough opposing interest, the order may not execute.' },
    { prompt: 'Standart stop emri stop fiyatına ulaşıldığında genellikle ne olur?', promptEn: 'What usually happens when a standard stop order reaches its stop price?', choices: [{ id: 'a', label: 'Piyasa emrine dönüşür', labelEn: 'It becomes a market order' }, { id: 'b', label: 'Kesin stop fiyatından tamamlanır', labelEn: 'It completes at the exact stop price' }, { id: 'c', label: 'Her zaman iptal olur', labelEn: 'It is always canceled' }], correctId: 'a', explanation: 'Stop fiyatı tetikleyicidir; gerçekleşme fiyatı piyasa koşullarına bağlıdır.', explanationEn: 'The stop price is a trigger; the execution price depends on market conditions.' },
  ],
  sources: [WAVE1_SOURCES.investorOrders, WAVE1_SOURCES.finraOrders],
});

const slippage = createFoundationLesson({
  id: 'lesson.market.slippage.001',
  slug: 'gerceklesme-fiyati-kayma',
  conceptKey: 'market.execution.slippage',
  skillId: 'skill.market-foundations',
  competencyId: 'competency.explain-slippage.foundation',
  title: 'Ekrandaki fiyat neden garanti değildir?',
  titleEn: 'Why is the price on screen not guaranteed?',
  objective: 'Son fiyat ile gerçekleşme fiyatının neden farklılaşabileceğini açıklar.',
  objectiveEn: 'Explain why the last price and the execution price can differ.',
  minutes: 4,
  hook: 'Emri verdiğin anda gördüğün fiyatla işlem neden farklı bir fiyattan gerçekleşebilir?',
  hookEn: 'Why can your trade execute at a different price than the one you saw when placing the order?',
  explanation: 'Ekrandaki son fiyat geçmişte gerçekleşmiş bir işlemdir. Emir piyasaya ulaşana kadar fiyat değişebilir veya istediğin büyüklüğü karşılayacak yeterli emir bulunmayabilir. Gerçekleşen ortalama fiyat ile beklenen fiyat arasındaki fark kayma olarak adlandırılır.',
  explanationEn: 'The last price on screen is a trade that already happened. Before your order reaches the market, price can change or there may not be enough orders to fill your desired size. The difference between the average execution price and the expected price is called slippage.',
  proExplanation: 'Slippage; volatilite, gecikme, spread, emir büyüklüğü ve emir defteri derinliğinin ortak sonucudur. Büyük piyasa emirleri birden fazla fiyat seviyesini tüketebilir.',
  proExplanationEn: 'Slippage is the combined result of volatility, latency, spread, order size, and order book depth. Large market orders can consume multiple price levels.',
  misconception: 'Yaygın hata: Emir düğmesine basıldığı anda ekrandaki son fiyatın kilitlendiğini düşünmek.',
  misconceptionEn: 'Common mistake: thinking the last price on screen is locked the moment the order button is pressed.',
  takeaway: 'Görülen fiyat bir referanstır; gerçekleşme, emir türü ve mevcut likiditeye bağlıdır.',
  takeawayEn: 'The displayed price is a reference; execution depends on order type and current liquidity.',
  prerequisiteConceptKeys: ['market.execution.order_types', 'market.structure.liquidity'],
  relatedConceptKeys: ['market.microstructure.bid_ask', 'risk.volatility'],
  visualAlt: 'Bir piyasa emrinin farklı fiyat seviyelerinde parçalı gerçekleşmesini gösteren şema',
  visualAltEn: 'Diagram showing a market order filling across different price levels',
  taskPrompt: 'Kayma riskini hangi durumda daha yüksek beklersin?',
  taskPromptEn: 'In which situation would you expect higher slippage risk?',
  taskChoices: [
    { id: 'thin', label: 'Sığ ve hızlı hareket eden piyasada büyük piyasa emri', labelEn: 'A large market order in a shallow, fast-moving market' },
    { id: 'deep', label: 'Derin piyasada küçük limit emir', labelEn: 'A small limit order in a deep market' },
    { id: 'closed', label: 'Hiç emir gönderilmemesi', labelEn: 'Not sending any order' },
  ],
  taskCorrectIds: ['thin'],
  questions: [
    { prompt: 'Son işlem fiyatı neden gerçekleşme garantisi değildir?', promptEn: 'Why is the last traded price not an execution guarantee?', choices: [{ id: 'a', label: 'Geçmişteki son eşleşmeyi gösterdiği için', labelEn: 'Because it shows the last completed match in the past' }, { id: 'b', label: 'Her zaman yanlış olduğu için', labelEn: 'Because it is always wrong' }, { id: 'c', label: 'Yalnız grafik rengi olduğu için', labelEn: 'Because it is only a chart color' }], correctId: 'a', explanation: 'Yeni emir gerçekleşene kadar piyasa koşulları değişebilir.', explanationEn: 'Market conditions can change before a new order executes.' },
    { prompt: 'Kaymayı hangi etken artırabilir?', promptEn: 'Which factor can increase slippage?', choices: [{ id: 'a', label: 'Düşük likidite ve yüksek volatilite', labelEn: 'Low liquidity and high volatility' }, { id: 'b', label: 'Yeterli derinlik ve küçük emir', labelEn: 'Enough depth and a small order' }, { id: 'c', label: 'Emir göndermemek', labelEn: 'Not sending an order' }], correctId: 'a', explanation: 'Sığ ve hızlı piyasada beklenen fiyatın çevresinde yeterli karşı emir bulunmayabilir.', explanationEn: 'In a shallow and fast market, there may not be enough opposing orders near the expected price.' },
    { prompt: 'Fiyat kontrolü için limit emir kullanmanın karşılığı nedir?', promptEn: 'What is the tradeoff of using a limit order for price control?', choices: [{ id: 'a', label: 'Emrin gerçekleşmeyebilmesi', labelEn: 'The order may not execute' }, { id: 'b', label: 'Kesin kâr', labelEn: 'Guaranteed profit' }, { id: 'c', label: 'Sıfır risk', labelEn: 'Zero risk' }], correctId: 'a', explanation: 'Limit koşulu sağlanmazsa emir açık kalabilir veya hiç gerçekleşmeyebilir.', explanationEn: 'If the limit condition is not met, the order can remain open or not execute at all.' },
  ],
  sources: [WAVE1_SOURCES.investorOrders, WAVE1_SOURCES.finraOrders],
});

export const WAVE1_MARKET_FOUNDATION_LESSONS = [
  priceFormation,
  instruments,
  liquidity,
  bidAsk,
  orderTypes,
  slippage,
] as const;
