import { Course } from '../../types/course';

export const mockCourses: Course[] = [
  {
    id: 1,
    category: 'Personal Finance',
    level: 'Beginner',
    duration: '8',
    lessons: 12,
    rating: 4.7,
    enrolled: 1250,
    progress: 85,
    hasQuiz: true,
    contentTypes: ['video', 'quiz', 'slides'],
    lastUpdated: '2024-01-15',
    tags: ['bütçe', 'tasarruf', 'borç', 'yatırım'],
    title: {
      tr: 'Kişisel Finans',
      en: 'Personal Finance',
      es: 'Finanzas Personales',
      fr: 'Finance Personnelle',
      ru: 'Личные финансы',
      de: 'Persönliche Finanzen',
      pt: 'Finanças Pessoais',
    },
    description: {
      tr: 'Bütçe yönetimi, tasarruf stratejileri, borç yönetimi ve temel yatırım ürünleri hakkında kapsamlı bir eğitim.',
      en: 'Comprehensive training on budget management, savings strategies, debt management, and basic investment products.',
      es: 'Formación integral sobre gestión presupuestaria, estrategias de ahorro, gestión de deudas y productos de inversión básicos.',
      fr: 'Formation complète sur la gestion budgétaire, les stratégies d\'épargne, la gestion de la dette et les produits d\'investissement de base.',
      ru: 'Комплексное обучение управлению бюджетом, стратегиям сбережений, управлению долгами и базовым инвестиционным продуктам.',
      de: 'Umfassende Schulung zu Budgetmanagement, Sparstrategien, Schuldenmanagement und grundlegenden Anlageprodukten.',
      pt: 'Treinamento abrangente sobre gestão de orçamento, estratégias de poupança, gestão de dívidas e produtos de investimento básicos.',
    },
    outcomes: {
      tr: [
        'Bütçe oluşturma ve takip etme becerisi',
        'Tasarruf hedefleri belirleme',
        'Borç yönetimi stratejileri',
        'Acil durum fonu oluşturma',
        'Temel yatırım ürünlerini anlama',
      ],
      en: [
        'Ability to create and track budgets',
        'Setting savings goals',
        'Debt management strategies',
        'Building an emergency fund',
        'Understanding basic investment products',
      ],
      es: [
        'Capacidad para crear y hacer seguimiento de presupuestos',
        'Establecer objetivos de ahorro',
        'Estrategias de gestión de deudas',
        'Construir un fondo de emergencia',
        'Comprender productos de inversión básicos',
      ],
      fr: [
        'Capacité à créer et suivre des budgets',
        'Fixer des objectifs d\'épargne',
        'Stratégies de gestion de la dette',
        'Construire un fonds d\'urgence',
        'Comprendre les produits d\'investissement de base',
      ],
      ru: [
        'Способность создавать и отслеживать бюджеты',
        'Постановка целей по сбережениям',
        'Стратегии управления долгами',
        'Создание резервного фонда',
        'Понимание базовых инвестиционных продуктов',
      ],
      de: [
        'Fähigkeit, Budgets zu erstellen und zu verfolgen',
        'Sparziele setzen',
        'Strategien zur Schuldenverwaltung',
        'Aufbau eines Notfallfonds',
        'Grundlegende Anlageprodukte verstehen',
      ],
      pt: [
        'Capacidade de criar e acompanhar orçamentos',
        'Definir metas de poupança',
        'Estratégias de gestão de dívidas',
        'Construir um fundo de emergência',
        'Compreender produtos de investimento básicos',
      ],
    },
    modules: [
      {
        title: {
          tr: 'Bütçe Yönetimi',
          en: 'Budget Management',
          es: 'Gestión Presupuestaria',
          fr: 'Gestion Budgétaire',
          ru: 'Управление бюджетом',
          de: 'Budgetmanagement',
          pt: 'Gestão de Orçamento',
        },
        lessons: ['Bütçe nedir?', 'Gelir-gider analizi', 'Bütçe oluşturma'],
        duration: '2',
      },
      {
        title: {
          tr: 'Tasarruf Stratejileri',
          en: 'Savings Strategies',
          es: 'Estrategias de Ahorro',
          fr: 'Stratégies d\'Épargne',
          ru: 'Стратегии сбережений',
          de: 'Sparstrategien',
          pt: 'Estratégias de Poupança',
        },
        lessons: ['Tasarruf hedefleri', 'Otomatik tasarruf', 'Tasarruf araçları'],
        duration: '2',
      },
      {
        title: {
          tr: 'Borç Yönetimi',
          en: 'Debt Management',
          es: 'Gestión de Deudas',
          fr: 'Gestion de la Dette',
          ru: 'Управление долгами',
          de: 'Schuldenmanagement',
          pt: 'Gestão de Dívidas',
        },
        lessons: ['Borç türleri', 'Borç ödeme stratejileri', 'Kredi skoru'],
        duration: '2',
      },
      {
        title: {
          tr: 'Acil Durum Fonu',
          en: 'Emergency Fund',
          es: 'Fondo de Emergencia',
          fr: 'Fonds d\'Urgence',
          ru: 'Резервный фонд',
          de: 'Notfallfonds',
          pt: 'Fundo de Emergência',
        },
        lessons: ['Acil durum fonu nedir?', 'Ne kadar biriktirmeli?', 'Nerede tutmalı?'],
        duration: '1',
      },
      {
        title: {
          tr: 'Temel Yatırım Ürünleri',
          en: 'Basic Investment Products',
          es: 'Productos de Inversión Básicos',
          fr: 'Produits d\'Investissement de Base',
          ru: 'Базовые инвестиционные продукты',
          de: 'Grundlegende Anlageprodukte',
          pt: 'Produtos de Investimento Básicos',
        },
        lessons: ['Mevduat', 'Yatırım fonları', 'Borsa temelleri'],
        duration: '1',
      },
    ],
    prerequisites: {
      tr: ['Temel matematik bilgisi', 'Finansal okuryazarlık isteği'],
      en: ['Basic math knowledge', 'Desire for financial literacy'],
      es: ['Conocimientos básicos de matemáticas', 'Deseo de alfabetización financiera'],
      fr: ['Connaissances de base en mathématiques', 'Désir d\'alphabétisation financière'],
      ru: ['Базовые знания математики', 'Желание финансовой грамотности'],
      de: ['Grundkenntnisse in Mathematik', 'Wunsch nach Finanzkompetenz'],
      pt: ['Conhecimentos básicos de matemática', 'Desejo de alfabetização financeira'],
    },
    skillsGained: {
      tr: [
        'Bütçe planlama',
        'Tasarruf yönetimi',
        'Borç analizi',
        'Finansal planlama',
        'Yatırım temelleri',
      ],
      en: [
        'Budget planning',
        'Savings management',
        'Debt analysis',
        'Financial planning',
        'Investment basics',
      ],
      es: [
        'Planificación presupuestaria',
        'Gestión de ahorros',
        'Análisis de deudas',
        'Planificación financiera',
        'Conceptos básicos de inversión',
      ],
      fr: [
        'Planification budgétaire',
        'Gestion de l\'épargne',
        'Analyse de la dette',
        'Planification financière',
        'Bases de l\'investissement',
      ],
      ru: [
        'Планирование бюджета',
        'Управление сбережениями',
        'Анализ долгов',
        'Финансовое планирование',
        'Основы инвестирования',
      ],
      de: [
        'Budgetplanung',
        'Sparverwaltung',
        'Schuldenanalyse',
        'Finanzplanung',
        'Grundlagen der Investition',
      ],
      pt: [
        'Planejamento orçamentário',
        'Gestão de poupança',
        'Análise de dívidas',
        'Planejamento financeiro',
        'Noções básicas de investimento',
      ],
    },
  },
  {
    id: 2,
    category: 'Financial Markets',
    level: 'Intermediate',
    duration: '12',
    lessons: 18,
    rating: 4.8,
    enrolled: 2100,
    progress: 90,
    hasQuiz: true,
    contentTypes: ['video', 'quiz', 'interactive'],
    lastUpdated: '2024-02-01',
    tags: ['piyasalar', 'borsa', 'forex', 'likidite'],
    title: {
      tr: 'Finansal Piyasalar',
      en: 'Financial Markets',
      es: 'Mercados Financieros',
      fr: 'Marchés Financiers',
      ru: 'Финансовые рынки',
      de: 'Finanzmärkte',
      pt: 'Mercados Financeiros',
    },
    description: {
      tr: 'Piyasa türleri, organize ve tezgâhüstü piyasalar, likidite kavramları ve emir türleri hakkında detaylı bilgi.',
      en: 'Detailed information on market types, organized and over-the-counter markets, liquidity concepts, and order types.',
      es: 'Información detallada sobre tipos de mercados, mercados organizados y extrabursátiles, conceptos de liquidez y tipos de órdenes.',
      fr: 'Informations détaillées sur les types de marchés, les marchés organisés et de gré à gré, les concepts de liquidité et les types d\'ordres.',
      ru: 'Подробная информация о типах рынков, организованных и внебиржевых рынках, концепциях ликвидности и типах ордеров.',
      de: 'Detaillierte Informationen zu Markttypen, organisierten und OTC-Märkten, Liquiditätskonzepten und Auftragsarten.',
      pt: 'Informações detalhadas sobre tipos de mercados, mercados organizados e de balcão, conceitos de liquidez e tipos de ordens.',
    },
    outcomes: {
      tr: [
        'Piyasa türlerini anlama',
        'Organize ve OTC piyasaları ayırt etme',
        'Likidite kavramını kavrama',
        'Farklı emir türlerini kullanma',
        'Piyasa saatlerini takip etme',
      ],
      en: [
        'Understanding market types',
        'Distinguishing organized and OTC markets',
        'Grasping liquidity concepts',
        'Using different order types',
        'Tracking market hours',
      ],
      es: [
        'Comprender los tipos de mercados',
        'Distinguir mercados organizados y extrabursátiles',
        'Aprender conceptos de liquidez',
        'Usar diferentes tipos de órdenes',
        'Seguir los horarios del mercado',
      ],
      fr: [
        'Comprendre les types de marchés',
        'Distinguer les marchés organisés et de gré à gré',
        'Saisir les concepts de liquidité',
        'Utiliser différents types d\'ordres',
        'Suivre les heures de marché',
      ],
      ru: [
        'Понимание типов рынков',
        'Различение организованных и внебиржевых рынков',
        'Понимание концепций ликвидности',
        'Использование различных типов ордеров',
        'Отслеживание рыночных часов',
      ],
      de: [
        'Verstehen von Markttypen',
        'Unterscheidung zwischen organisierten und OTC-Märkten',
        'Erfassen von Liquiditätskonzepten',
        'Verwenden verschiedener Auftragsarten',
        'Verfolgen der Marktzeiten',
      ],
      pt: [
        'Compreender tipos de mercados',
        'Distinguir mercados organizados e de balcão',
        'Apreender conceitos de liquidez',
        'Usar diferentes tipos de ordens',
        'Acompanhar horários do mercado',
      ],
    },
    modules: [
      {
        title: {
          tr: 'Piyasa Türleri',
          en: 'Market Types',
          es: 'Tipos de Mercados',
          fr: 'Types de Marchés',
          ru: 'Типы рынков',
          de: 'Markttypen',
          pt: 'Tipos de Mercados',
        },
        lessons: ['Hisse senedi piyasası', 'Tahvil piyasası', 'Forex piyasası', 'Emtia piyasası'],
        duration: '3',
      },
      {
        title: {
          tr: 'Organize ve OTC Piyasalar',
          en: 'Organized and OTC Markets',
          es: 'Mercados Organizados y Extrabursátiles',
          fr: 'Marchés Organisés et de Gré à Gré',
          ru: 'Организованные и внебиржевые рынки',
          de: 'Organisierte und OTC-Märkte',
          pt: 'Mercados Organizados e de Balcão',
        },
        lessons: ['Borsa nedir?', 'OTC piyasalar', 'Karşılaştırma'],
        duration: '2',
      },
      {
        title: {
          tr: 'Likidite',
          en: 'Liquidity',
          es: 'Liquidez',
          fr: 'Liquidité',
          ru: 'Ликвидность',
          de: 'Liquidität',
          pt: 'Liquidez',
        },
        lessons: ['Likidite nedir?', 'Likidite önemi', 'Likidite riski'],
        duration: '2',
      },
      {
        title: {
          tr: 'Emir Türleri',
          en: 'Order Types',
          es: 'Tipos de Órdenes',
          fr: 'Types d\'Ordres',
          ru: 'Типы ордеров',
          de: 'Auftragsarten',
          pt: 'Tipos de Ordens',
        },
        lessons: ['Market order', 'Limit order', 'Stop order', 'Diğer emir türleri'],
        duration: '3',
      },
      {
        title: {
          tr: 'Piyasa Saatleri',
          en: 'Market Hours',
          es: 'Horarios del Mercado',
          fr: 'Heures de Marché',
          ru: 'Рыночные часы',
          de: 'Marktzeiten',
          pt: 'Horários do Mercado',
        },
        lessons: ['Açılış/kapanış saatleri', 'Farklı piyasalar', 'Hafta sonu işlemleri'],
        duration: '2',
      },
    ],
    prerequisites: {
      tr: ['Temel finans bilgisi', 'Kişisel Finans kursu önerilir'],
      en: ['Basic finance knowledge', 'Personal Finance course recommended'],
      es: ['Conocimientos básicos de finanzas', 'Se recomienda el curso de Finanzas Personales'],
      fr: ['Connaissances de base en finance', 'Cours de Finance Personnelle recommandé'],
      ru: ['Базовые знания финансов', 'Рекомендуется курс Личных финансов'],
      de: ['Grundkenntnisse in Finanzen', 'Kurs Persönliche Finanzen empfohlen'],
      pt: ['Conhecimentos básicos de finanças', 'Curso de Finanças Pessoais recomendado'],
    },
    skillsGained: {
      tr: [
        'Piyasa analizi',
        'Emir yönetimi',
        'Likidite değerlendirmesi',
        'Piyasa saatleri takibi',
        'Piyasa türleri bilgisi',
      ],
      en: [
        'Market analysis',
        'Order management',
        'Liquidity assessment',
        'Market hours tracking',
        'Market types knowledge',
      ],
      es: [
        'Análisis de mercado',
        'Gestión de órdenes',
        'Evaluación de liquidez',
        'Seguimiento de horarios',
        'Conocimiento de tipos de mercado',
      ],
      fr: [
        'Analyse de marché',
        'Gestion des ordres',
        'Évaluation de la liquidité',
        'Suivi des heures de marché',
        'Connaissance des types de marché',
      ],
      ru: [
        'Анализ рынка',
        'Управление ордерами',
        'Оценка ликвидности',
        'Отслеживание рыночных часов',
        'Знание типов рынков',
      ],
      de: [
        'Marktanalyse',
        'Auftragsverwaltung',
        'Liquiditätsbewertung',
        'Verfolgung der Marktzeiten',
        'Kenntnisse über Markttypen',
      ],
      pt: [
        'Análise de mercado',
        'Gestão de ordens',
        'Avaliação de liquidez',
        'Acompanhamento de horários',
        'Conhecimento de tipos de mercado',
      ],
    },
  },
  {
    id: 3,
    category: 'Economics',
    level: 'Beginner',
    duration: '10',
    lessons: 15,
    rating: 4.6,
    enrolled: 1800,
    progress: 80,
    hasQuiz: true,
    contentTypes: ['video', 'quiz', 'slides'],
    lastUpdated: '2024-01-20',
    tags: ['ekonomi', 'arz-talep', 'enflasyon', 'faiz'],
    title: {
      tr: 'Temel Ekonomi',
      en: 'Basic Economics',
      es: 'Economía Básica',
      fr: 'Économie de Base',
      ru: 'Основы экономики',
      de: 'Grundlagen der Wirtschaft',
      pt: 'Economia Básica',
    },
    description: {
      tr: 'Arz-talep dengesi, enflasyon, büyüme, faiz oranları ve para politikası temelleri.',
      en: 'Supply-demand balance, inflation, growth, interest rates, and monetary policy fundamentals.',
      es: 'Equilibrio oferta-demanda, inflación, crecimiento, tasas de interés y fundamentos de política monetaria.',
      fr: 'Équilibre offre-demande, inflation, croissance, taux d\'intérêt et fondamentaux de la politique monétaire.',
      ru: 'Баланс спроса и предложения, инфляция, рост, процентные ставки и основы денежно-кредитной политики.',
      de: 'Angebots-Nachfrage-Gleichgewicht, Inflation, Wachstum, Zinssätze und Grundlagen der Geldpolitik.',
      pt: 'Equilíbrio oferta-demanda, inflação, crescimento, taxas de juros e fundamentos da política monetária.',
    },
    outcomes: {
      tr: [
        'Arz-talep kavramını anlama',
        'Enflasyon etkilerini kavrama',
        'Ekonomik büyüme faktörlerini öğrenme',
        'Faiz oranlarının etkisini anlama',
        'Para politikası temelleri',
      ],
      en: [
        'Understanding supply-demand concepts',
        'Grasping inflation effects',
        'Learning economic growth factors',
        'Understanding interest rate impacts',
        'Monetary policy fundamentals',
      ],
      es: [
        'Comprender conceptos de oferta-demanda',
        'Aprender efectos de la inflación',
        'Aprender factores de crecimiento económico',
        'Comprender impactos de las tasas de interés',
        'Fundamentos de política monetaria',
      ],
      fr: [
        'Comprendre les concepts d\'offre-demande',
        'Saisir les effets de l\'inflation',
        'Apprendre les facteurs de croissance économique',
        'Comprendre les impacts des taux d\'intérêt',
        'Fondamentaux de la politique monétaire',
      ],
      ru: [
        'Понимание концепций спроса и предложения',
        'Понимание эффектов инфляции',
        'Изучение факторов экономического роста',
        'Понимание влияния процентных ставок',
        'Основы денежно-кредитной политики',
      ],
      de: [
        'Verstehen von Angebots-Nachfrage-Konzepten',
        'Erfassen von Inflationswirkungen',
        'Lernen von Wirtschaftswachstumsfaktoren',
        'Verstehen von Zinssatzauswirkungen',
        'Grundlagen der Geldpolitik',
      ],
      pt: [
        'Compreender conceitos de oferta-demanda',
        'Apreender efeitos da inflação',
        'Aprender fatores de crescimento econômico',
        'Compreender impactos das taxas de juros',
        'Fundamentos da política monetária',
      ],
    },
    modules: [
      {
        title: {
          tr: 'Arz ve Talep',
          en: 'Supply and Demand',
          es: 'Oferta y Demanda',
          fr: 'Offre et Demande',
          ru: 'Спрос и предложение',
          de: 'Angebot und Nachfrage',
          pt: 'Oferta e Demanda',
        },
        lessons: ['Arz nedir?', 'Talep nedir?', 'Denge fiyatı', 'Arz-talep grafikleri'],
        duration: '3',
      },
      {
        title: {
          tr: 'Enflasyon',
          en: 'Inflation',
          es: 'Inflación',
          fr: 'Inflation',
          ru: 'Инфляция',
          de: 'Inflation',
          pt: 'Inflação',
        },
        lessons: ['Enflasyon nedir?', 'Enflasyon türleri', 'Enflasyon etkileri', 'Enflasyon ölçümü'],
        duration: '2',
      },
      {
        title: {
          tr: 'Ekonomik Büyüme',
          en: 'Economic Growth',
          es: 'Crecimiento Económico',
          fr: 'Croissance Économique',
          ru: 'Экономический рост',
          de: 'Wirtschaftswachstum',
          pt: 'Crescimento Econômico',
        },
        lessons: ['Büyüme nedir?', 'Büyüme faktörleri', 'GSYİH kavramı'],
        duration: '2',
      },
      {
        title: {
          tr: 'Faiz Oranları',
          en: 'Interest Rates',
          es: 'Tasas de Interés',
          fr: 'Taux d\'Intérêt',
          ru: 'Процентные ставки',
          de: 'Zinssätze',
          pt: 'Taxas de Juros',
        },
        lessons: ['Faiz nedir?', 'Faiz türleri', 'Faiz etkileri', 'Merkez bankası faizleri'],
        duration: '3',
      },
      {
        title: {
          tr: 'Para Politikası',
          en: 'Monetary Policy',
          es: 'Política Monetaria',
          fr: 'Politique Monétaire',
          ru: 'Денежно-кредитная политика',
          de: 'Geldpolitik',
          pt: 'Política Monetária',
        },
        lessons: ['Para politikası nedir?', 'Araçlar', 'Etkileri'],
        duration: '2',
      },
    ],
    prerequisites: {
      tr: ['Temel matematik', 'Güncel olayları takip etme isteği'],
      en: ['Basic math', 'Desire to follow current events'],
      es: ['Matemáticas básicas', 'Deseo de seguir eventos actuales'],
      fr: ['Mathématiques de base', 'Désir de suivre l\'actualité'],
      ru: ['Базовая математика', 'Желание следить за текущими событиями'],
      de: ['Grundlegende Mathematik', 'Wunsch, aktuelle Ereignisse zu verfolgen'],
      pt: ['Matemática básica', 'Desejo de acompanhar eventos atuais'],
    },
    skillsGained: {
      tr: [
        'Ekonomik analiz',
        'Arz-talep analizi',
        'Enflasyon takibi',
        'Faiz oranı değerlendirmesi',
        'Para politikası anlayışı',
      ],
      en: [
        'Economic analysis',
        'Supply-demand analysis',
        'Inflation tracking',
        'Interest rate assessment',
        'Monetary policy understanding',
      ],
      es: [
        'Análisis económico',
        'Análisis de oferta-demanda',
        'Seguimiento de inflación',
        'Evaluación de tasas de interés',
        'Comprensión de política monetaria',
      ],
      fr: [
        'Analyse économique',
        'Analyse offre-demande',
        'Suivi de l\'inflation',
        'Évaluation des taux d\'intérêt',
        'Compréhension de la politique monétaire',
      ],
      ru: [
        'Экономический анализ',
        'Анализ спроса и предложения',
        'Отслеживание инфляции',
        'Оценка процентных ставок',
        'Понимание денежно-кредитной политики',
      ],
      de: [
        'Wirtschaftsanalyse',
        'Angebots-Nachfrage-Analyse',
        'Inflationsverfolgung',
        'Zinssatzbewertung',
        'Verständnis der Geldpolitik',
      ],
      pt: [
        'Análise econômica',
        'Análise de oferta-demanda',
        'Acompanhamento da inflação',
        'Avaliação das taxas de juros',
        'Compreensão da política monetária',
      ],
    },
  },
  {
    id: 4,
    category: 'Fundamental Analysis',
    level: 'Intermediate',
    duration: '15',
    lessons: 20,
    rating: 4.9,
    enrolled: 1650,
    progress: 75,
    hasQuiz: true,
    contentTypes: ['video', 'quiz', 'case-study'],
    lastUpdated: '2024-02-10',
    tags: ['temel analiz', 'bilanço', 'gelir tablosu', 'değerleme'],
    title: {
      tr: 'Temel Analiz',
      en: 'Fundamental Analysis',
      es: 'Análisis Fundamental',
      fr: 'Analyse Fondamentale',
      ru: 'Фундаментальный анализ',
      de: 'Fundamentalanalyse',
      pt: 'Análise Fundamental',
    },
    description: {
      tr: 'Bilanço, gelir tablosu, nakit akımı analizi, finansal oranlar ve değerleme yöntemleri.',
      en: 'Balance sheet, income statement, cash flow analysis, financial ratios, and valuation methods.',
      es: 'Balance general, estado de resultados, análisis de flujo de efectivo, ratios financieros y métodos de valoración.',
      fr: 'Bilan, compte de résultat, analyse des flux de trésorerie, ratios financiers et méthodes d\'évaluation.',
      ru: 'Балансовый отчет, отчет о прибылях и убытках, анализ денежных потоков, финансовые коэффициенты и методы оценки.',
      de: 'Bilanz, Gewinn- und Verlustrechnung, Cashflow-Analyse, Finanzkennzahlen und Bewertungsmethoden.',
      pt: 'Balanço patrimonial, demonstração de resultados, análise de fluxo de caixa, índices financeiros e métodos de avaliação.',
    },
    outcomes: {
      tr: [
        'Finansal tabloları okuma',
        'Oran analizi yapma',
        'Nakit akımı değerlendirmesi',
        'Değerleme yöntemlerini uygulama',
        'Şirket analizi yapma',
      ],
      en: [
        'Reading financial statements',
        'Performing ratio analysis',
        'Cash flow assessment',
        'Applying valuation methods',
        'Conducting company analysis',
      ],
      es: [
        'Leer estados financieros',
        'Realizar análisis de ratios',
        'Evaluar flujo de efectivo',
        'Aplicar métodos de valoración',
        'Realizar análisis de empresas',
      ],
      fr: [
        'Lire les états financiers',
        'Effectuer une analyse des ratios',
        'Évaluer les flux de trésorerie',
        'Appliquer les méthodes d\'évaluation',
        'Effectuer une analyse d\'entreprise',
      ],
      ru: [
        'Чтение финансовой отчетности',
        'Проведение анализа коэффициентов',
        'Оценка денежных потоков',
        'Применение методов оценки',
        'Проведение анализа компании',
      ],
      de: [
        'Finanzberichte lesen',
        'Durchführung von Kennzahlenanalyse',
        'Cashflow-Bewertung',
        'Anwenden von Bewertungsmethoden',
        'Durchführung von Unternehmensanalyse',
      ],
      pt: [
        'Ler demonstrações financeiras',
        'Realizar análise de índices',
        'Avaliar fluxo de caixa',
        'Aplicar métodos de avaliação',
        'Realizar análise de empresas',
      ],
    },
    modules: [
      {
        title: {
          tr: 'Bilanço Analizi',
          en: 'Balance Sheet Analysis',
          es: 'Análisis de Balance General',
          fr: 'Analyse du Bilan',
          ru: 'Анализ баланса',
          de: 'Bilanzanalyse',
          pt: 'Análise de Balanço Patrimonial',
        },
        lessons: ['Bilanço nedir?', 'Varlıklar', 'Yükümlülükler', 'Özsermaye'],
        duration: '3',
      },
      {
        title: {
          tr: 'Gelir Tablosu',
          en: 'Income Statement',
          es: 'Estado de Resultados',
          fr: 'Compte de Résultat',
          ru: 'Отчет о прибылях и убытках',
          de: 'Gewinn- und Verlustrechnung',
          pt: 'Demonstração de Resultados',
        },
        lessons: ['Gelir tablosu nedir?', 'Gelirler', 'Giderler', 'Net kar'],
        duration: '3',
      },
      {
        title: {
          tr: 'Nakit Akımı',
          en: 'Cash Flow',
          es: 'Flujo de Efectivo',
          fr: 'Flux de Trésorerie',
          ru: 'Денежный поток',
          de: 'Cashflow',
          pt: 'Fluxo de Caixa',
        },
        lessons: ['Nakit akımı nedir?', 'İşletme faaliyetleri', 'Yatırım faaliyetleri', 'Finansman faaliyetleri'],
        duration: '3',
      },
      {
        title: {
          tr: 'Finansal Oranlar',
          en: 'Financial Ratios',
          es: 'Ratios Financieros',
          fr: 'Ratios Financiers',
          ru: 'Финансовые коэффициенты',
          de: 'Finanzkennzahlen',
          pt: 'Índices Financeiros',
        },
        lessons: ['Likidite oranları', 'Kârlılık oranları', 'Borç oranları', 'Verimlilik oranları'],
        duration: '4',
      },
      {
        title: {
          tr: 'Değerleme',
          en: 'Valuation',
          es: 'Valoración',
          fr: 'Évaluation',
          ru: 'Оценка',
          de: 'Bewertung',
          pt: 'Avaliação',
        },
        lessons: ['Değerleme nedir?', 'DCF yöntemi', 'Karşılaştırmalı değerleme', 'Varlık bazlı değerleme'],
        duration: '4',
      },
    ],
    prerequisites: {
      tr: ['Temel Ekonomi kursu', 'Temel matematik ve istatistik'],
      en: ['Basic Economics course', 'Basic math and statistics'],
      es: ['Curso de Economía Básica', 'Matemáticas y estadística básicas'],
      fr: ['Cours d\'Économie de Base', 'Mathématiques et statistiques de base'],
      ru: ['Курс Основы экономики', 'Базовая математика и статистика'],
      de: ['Kurs Grundlagen der Wirtschaft', 'Grundlegende Mathematik und Statistik'],
      pt: ['Curso de Economia Básica', 'Matemática e estatística básicas'],
    },
    skillsGained: {
      tr: [
        'Finansal tablo okuma',
        'Oran hesaplama',
        'Nakit akımı analizi',
        'Değerleme yapma',
        'Şirket değerlendirmesi',
      ],
      en: [
        'Reading financial statements',
        'Calculating ratios',
        'Cash flow analysis',
        'Performing valuation',
        'Company assessment',
      ],
      es: [
        'Leer estados financieros',
        'Calcular ratios',
        'Análisis de flujo de efectivo',
        'Realizar valoración',
        'Evaluación de empresas',
      ],
      fr: [
        'Lire les états financiers',
        'Calculer les ratios',
        'Analyse des flux de trésorerie',
        'Effectuer une évaluation',
        'Évaluation d\'entreprise',
      ],
      ru: [
        'Чтение финансовой отчетности',
        'Расчет коэффициентов',
        'Анализ денежных потоков',
        'Проведение оценки',
        'Оценка компании',
      ],
      de: [
        'Finanzberichte lesen',
        'Kennzahlen berechnen',
        'Cashflow-Analyse',
        'Bewertung durchführen',
        'Unternehmensbewertung',
      ],
      pt: [
        'Ler demonstrações financeiras',
        'Calcular índices',
        'Análise de fluxo de caixa',
        'Realizar avaliação',
        'Avaliação de empresas',
      ],
    },
  },
  {
    id: 5,
    category: 'Technical Analysis',
    level: 'Advanced',
    duration: '18',
    lessons: 25,
    rating: 4.8,
    enrolled: 2400,
    progress: 70,
    hasQuiz: true,
    contentTypes: ['video', 'quiz', 'interactive', 'charts'],
    lastUpdated: '2024-02-15',
    tags: ['teknik analiz', 'grafik', 'formasyon', 'indikatör'],
    title: {
      tr: 'Teknik Analiz',
      en: 'Technical Analysis',
      es: 'Análisis Técnico',
      fr: 'Analyse Technique',
      ru: 'Технический анализ',
      de: 'Technische Analyse',
      pt: 'Análise Técnica',
    },
    description: {
      tr: 'Trend analizi, destek-direnç seviyeleri, grafik formasyonları, teknik indikatörler ve zamanlama stratejileri.',
      en: 'Trend analysis, support-resistance levels, chart patterns, technical indicators, and timing strategies.',
      es: 'Análisis de tendencias, niveles de soporte-resistencia, patrones de gráficos, indicadores técnicos y estrategias de timing.',
      fr: 'Analyse des tendances, niveaux de support-résistance, motifs graphiques, indicateurs techniques et stratégies de timing.',
      ru: 'Анализ трендов, уровни поддержки-сопротивления, графические паттерны, технические индикаторы и стратегии выбора времени.',
      de: 'Trendanalyse, Support-Widerstands-Niveaus, Chartmuster, technische Indikatoren und Timing-Strategien.',
      pt: 'Análise de tendências, níveis de suporte-resistência, padrões de gráficos, indicadores técnicos e estratégias de timing.',
    },
    outcomes: {
      tr: [
        'Grafik okuma becerisi',
        'Trend belirleme',
        'Destek-direnç seviyeleri çizme',
        'Formasyon tanıma',
        'İndikatör kullanma',
      ],
      en: [
        'Chart reading skills',
        'Trend identification',
        'Drawing support-resistance levels',
        'Pattern recognition',
        'Using indicators',
      ],
      es: [
        'Habilidades de lectura de gráficos',
        'Identificación de tendencias',
        'Dibujar niveles de soporte-resistencia',
        'Reconocimiento de patrones',
        'Usar indicadores',
      ],
      fr: [
        'Compétences en lecture de graphiques',
        'Identification des tendances',
        'Dessiner les niveaux de support-résistance',
        'Reconnaissance des motifs',
        'Utiliser les indicateurs',
      ],
      ru: [
        'Навыки чтения графиков',
        'Идентификация трендов',
        'Построение уровней поддержки-сопротивления',
        'Распознавание паттернов',
        'Использование индикаторов',
      ],
      de: [
        'Chart-Lesefähigkeiten',
        'Trendidentifikation',
        'Zeichnen von Support-Widerstands-Niveaus',
        'Mustererkennung',
        'Verwenden von Indikatoren',
      ],
      pt: [
        'Habilidades de leitura de gráficos',
        'Identificação de tendências',
        'Desenhar níveis de suporte-resistência',
        'Reconhecimento de padrões',
        'Usar indicadores',
      ],
    },
    modules: [
      {
        title: {
          tr: 'Grafik Temelleri',
          en: 'Chart Basics',
          es: 'Conceptos Básicos de Gráficos',
          fr: 'Bases des Graphiques',
          ru: 'Основы графиков',
          de: 'Grundlagen der Charts',
          pt: 'Conceitos Básicos de Gráficos',
        },
        lessons: ['Mum grafikleri', 'Çizgi grafikleri', 'Bar grafikleri', 'Grafik türleri'],
        duration: '3',
      },
      {
        title: {
          tr: 'Trend Analizi',
          en: 'Trend Analysis',
          es: 'Análisis de Tendencias',
          fr: 'Analyse des Tendances',
          ru: 'Анализ трендов',
          de: 'Trendanalyse',
          pt: 'Análise de Tendências',
        },
        lessons: ['Yükseliş trendi', 'Düşüş trendi', 'Yatay trend', 'Trend çizgileri'],
        duration: '4',
      },
      {
        title: {
          tr: 'Destek ve Direnç',
          en: 'Support and Resistance',
          es: 'Soporte y Resistencia',
          fr: 'Support et Résistance',
          ru: 'Поддержка и сопротивление',
          de: 'Support und Widerstand',
          pt: 'Suporte e Resistência',
        },
        lessons: ['Destek nedir?', 'Direnç nedir?', 'Seviye belirleme', 'Kırılma'],
        duration: '3',
      },
      {
        title: {
          tr: 'Grafik Formasyonları',
          en: 'Chart Patterns',
          es: 'Patrones de Gráficos',
          fr: 'Motifs Graphiques',
          ru: 'Графические паттерны',
          de: 'Chartmuster',
          pt: 'Padrões de Gráficos',
        },
        lessons: ['Baş-yarı formasyonu', 'Çift tepe/çift dip', 'Üçgen formasyonları', 'Bayrak ve flama'],
        duration: '5',
      },
      {
        title: {
          tr: 'Teknik İndikatörler',
          en: 'Technical Indicators',
          es: 'Indicadores Técnicos',
          fr: 'Indicateurs Techniques',
          ru: 'Технические индикаторы',
          de: 'Technische Indikatoren',
          pt: 'Indicadores Técnicos',
        },
        lessons: ['MA (Moving Average)', 'RSI', 'MACD', 'Bollinger Bands', 'Stochastic'],
        duration: '6',
      },
      {
        title: {
          tr: 'Zamanlama Stratejileri',
          en: 'Timing Strategies',
          es: 'Estrategias de Timing',
          fr: 'Stratégies de Timing',
          ru: 'Стратегии выбора времени',
          de: 'Timing-Strategien',
          pt: 'Estratégias de Timing',
        },
        lessons: ['Giriş zamanlaması', 'Çıkış zamanlaması', 'Stop-loss', 'Take-profit'],
        duration: '4',
      },
    ],
    prerequisites: {
      tr: ['Finansal Piyasalar kursu', 'Temel grafik okuma bilgisi'],
      en: ['Financial Markets course', 'Basic chart reading knowledge'],
      es: ['Curso de Mercados Financieros', 'Conocimientos básicos de lectura de gráficos'],
      fr: ['Cours de Marchés Financiers', 'Connaissances de base en lecture de graphiques'],
      ru: ['Курс Финансовые рынки', 'Базовые знания чтения графиков'],
      de: ['Kurs Finanzmärkte', 'Grundkenntnisse im Chart-Lesen'],
      pt: ['Curso de Mercados Financeiros', 'Conhecimentos básicos de leitura de gráficos'],
    },
    skillsGained: {
      tr: [
        'Grafik analizi',
        'Trend belirleme',
        'Formasyon tanıma',
        'İndikatör yorumlama',
        'Zamanlama stratejileri',
      ],
      en: [
        'Chart analysis',
        'Trend identification',
        'Pattern recognition',
        'Indicator interpretation',
        'Timing strategies',
      ],
      es: [
        'Análisis de gráficos',
        'Identificación de tendencias',
        'Reconocimiento de patrones',
        'Interpretación de indicadores',
        'Estrategias de timing',
      ],
      fr: [
        'Analyse graphique',
        'Identification des tendances',
        'Reconnaissance des motifs',
        'Interprétation des indicateurs',
        'Stratégies de timing',
      ],
      ru: [
        'Анализ графиков',
        'Идентификация трендов',
        'Распознавание паттернов',
        'Интерпретация индикаторов',
        'Стратегии выбора времени',
      ],
      de: [
        'Chart-Analyse',
        'Trendidentifikation',
        'Mustererkennung',
        'Indikatorinterpretation',
        'Timing-Strategien',
      ],
      pt: [
        'Análise de gráficos',
        'Identificação de tendências',
        'Reconhecimento de padrões',
        'Interpretação de indicadores',
        'Estratégias de timing',
      ],
    },
  },
  {
    id: 6,
    category: 'Derivatives',
    level: 'Advanced',
    duration: '14',
    lessons: 22,
    rating: 4.7,
    enrolled: 1100,
    progress: 65,
    hasQuiz: true,
    contentTypes: ['video', 'quiz', 'interactive'],
    lastUpdated: '2024-02-05',
    tags: ['türev', 'vadeli', 'opsiyon', 'kaldıraç'],
    title: {
      tr: 'Türev Piyasalar',
      en: 'Derivatives Markets',
      es: 'Mercados de Derivados',
      fr: 'Marchés Dérivés',
      ru: 'Рынки деривативов',
      de: 'Derivatemärkte',
      pt: 'Mercados de Derivativos',
    },
    description: {
      tr: 'Vadeli işlemler, opsiyonlar, kaldıraç kavramları, risk yönetimi ve türev ürünlerin kullanım alanları.',
      en: 'Futures, options, leverage concepts, risk management, and use cases of derivative products.',
      es: 'Futuros, opciones, conceptos de apalancamiento, gestión de riesgos y casos de uso de productos derivados.',
      fr: 'Contrats à terme, options, concepts de levier, gestion des risques et cas d\'utilisation des produits dérivés.',
      ru: 'Фьючерсы, опционы, концепции кредитного плеча, управление рисками и случаи использования производных продуктов.',
      de: 'Futures, Optionen, Hebelkonzepte, Risikomanagement und Anwendungsfälle von Derivaten.',
      pt: 'Futuros, opções, conceitos de alavancagem, gestão de riscos e casos de uso de produtos derivativos.',
    },
    outcomes: {
      tr: [
        'Türev ürünleri anlama',
        'Vadeli işlem kavramı',
        'Opsiyon stratejileri',
        'Kaldıraç kullanımı',
        'Risk yönetimi',
      ],
      en: [
        'Understanding derivative products',
        'Futures concepts',
        'Options strategies',
        'Leverage usage',
        'Risk management',
      ],
      es: [
        'Comprender productos derivados',
        'Conceptos de futuros',
        'Estrategias de opciones',
        'Uso de apalancamiento',
        'Gestión de riesgos',
      ],
      fr: [
        'Comprendre les produits dérivés',
        'Concepts de contrats à terme',
        'Stratégies d\'options',
        'Utilisation du levier',
        'Gestion des risques',
      ],
      ru: [
        'Понимание производных продуктов',
        'Концепции фьючерсов',
        'Стратегии опционов',
        'Использование кредитного плеча',
        'Управление рисками',
      ],
      de: [
        'Verstehen von Derivaten',
        'Futures-Konzepte',
        'Optionsstrategien',
        'Hebelverwendung',
        'Risikomanagement',
      ],
      pt: [
        'Compreender produtos derivativos',
        'Conceitos de futuros',
        'Estratégias de opções',
        'Uso de alavancagem',
        'Gestão de riscos',
      ],
    },
    modules: [
      {
        title: {
          tr: 'Türev Ürünlere Giriş',
          en: 'Introduction to Derivatives',
          es: 'Introducción a los Derivados',
          fr: 'Introduction aux Dérivés',
          ru: 'Введение в деривативы',
          de: 'Einführung in Derivate',
          pt: 'Introdução aos Derivativos',
        },
        lessons: ['Türev nedir?', 'Türev türleri', 'Kullanım alanları'],
        duration: '2',
      },
      {
        title: {
          tr: 'Vadeli İşlemler',
          en: 'Futures',
          es: 'Futuros',
          fr: 'Contrats à Terme',
          ru: 'Фьючерсы',
          de: 'Futures',
          pt: 'Futuros',
        },
        lessons: ['Vadeli işlem nedir?', 'Fiyat belirleme', 'Teminat', 'Kapatma'],
        duration: '4',
      },
      {
        title: {
          tr: 'Opsiyonlar',
          en: 'Options',
          es: 'Opciones',
          fr: 'Options',
          ru: 'Опционы',
          de: 'Optionen',
          pt: 'Opções',
        },
        lessons: ['Opsiyon nedir?', 'Call opsiyon', 'Put opsiyon', 'Opsiyon stratejileri'],
        duration: '5',
      },
      {
        title: {
          tr: 'Kaldıraç',
          en: 'Leverage',
          es: 'Apalancamiento',
          fr: 'Effet de Levier',
          ru: 'Кредитное плечо',
          de: 'Hebel',
          pt: 'Alavancagem',
        },
        lessons: ['Kaldıraç nedir?', 'Kaldıraç hesaplama', 'Risk ve fırsat', 'Kaldıraç yönetimi'],
        duration: '3',
      },
      {
        title: {
          tr: 'Türev Riskleri',
          en: 'Derivatives Risks',
          es: 'Riesgos de Derivados',
          fr: 'Risques des Dérivés',
          ru: 'Риски деривативов',
          de: 'Risiken von Derivaten',
          pt: 'Riscos de Derivativos',
        },
        lessons: ['Piyasa riski', 'Kredi riski', 'Likidite riski', 'Operasyonel risk'],
        duration: '4',
      },
      {
        title: {
          tr: 'Hedging Stratejileri',
          en: 'Hedging Strategies',
          es: 'Estrategias de Cobertura',
          fr: 'Stratégies de Couverture',
          ru: 'Стратегии хеджирования',
          de: 'Absicherungsstrategien',
          pt: 'Estratégias de Hedge',
        },
        lessons: ['Hedging nedir?', 'Hedging türleri', 'Uygulama örnekleri'],
        duration: '4',
      },
    ],
    prerequisites: {
      tr: ['Finansal Piyasalar kursu', 'Temel Analiz kursu önerilir'],
      en: ['Financial Markets course', 'Fundamental Analysis course recommended'],
      es: ['Curso de Mercados Financieros', 'Se recomienda el curso de Análisis Fundamental'],
      fr: ['Cours de Marchés Financiers', 'Cours d\'Analyse Fondamentale recommandé'],
      ru: ['Курс Финансовые рынки', 'Рекомендуется курс Фундаментального анализа'],
      de: ['Kurs Finanzmärkte', 'Kurs Fundamentalanalyse empfohlen'],
      pt: ['Curso de Mercados Financeiros', 'Curso de Análise Fundamental recomendado'],
    },
    skillsGained: {
      tr: [
        'Türev ürün bilgisi',
        'Vadeli işlem işlemleri',
        'Opsiyon stratejileri',
        'Kaldıraç yönetimi',
        'Hedging teknikleri',
      ],
      en: [
        'Derivative product knowledge',
        'Futures trading',
        'Options strategies',
        'Leverage management',
        'Hedging techniques',
      ],
      es: [
        'Conocimiento de productos derivados',
        'Operaciones con futuros',
        'Estrategias de opciones',
        'Gestión de apalancamiento',
        'Técnicas de cobertura',
      ],
      fr: [
        'Connaissances des produits dérivés',
        'Trading de contrats à terme',
        'Stratégies d\'options',
        'Gestion du levier',
        'Techniques de couverture',
      ],
      ru: [
        'Знание производных продуктов',
        'Торговля фьючерсами',
        'Стратегии опционов',
        'Управление кредитным плечом',
        'Техники хеджирования',
      ],
      de: [
        'Kenntnisse über Derivate',
        'Futures-Handel',
        'Optionsstrategien',
        'Hebelverwaltung',
        'Absicherungstechniken',
      ],
      pt: [
        'Conhecimento de produtos derivativos',
        'Negociação de futuros',
        'Estratégias de opções',
        'Gestão de alavancagem',
        'Técnicas de hedge',
      ],
    },
  },
  {
    id: 7,
    category: 'Risk Management',
    level: 'Intermediate',
    duration: '10',
    lessons: 16,
    rating: 4.9,
    enrolled: 1950,
    progress: 88,
    hasQuiz: true,
    contentTypes: ['video', 'quiz', 'case-study'],
    lastUpdated: '2024-01-25',
    tags: ['risk', 'pozisyon', 'stop-loss', 'portföy'],
    title: {
      tr: 'Risk Yönetimi',
      en: 'Risk Management',
      es: 'Gestión de Riesgos',
      fr: 'Gestion des Risques',
      ru: 'Управление рисками',
      de: 'Risikomanagement',
      pt: 'Gestão de Riscos',
    },
    description: {
      tr: 'Pozisyon boyutu belirleme, kaldıraç yönetimi, portföy riskleri, koruma stratejileri ve risk ölçümü.',
      en: 'Position sizing, leverage management, portfolio risks, protection strategies, and risk measurement.',
      es: 'Tamaño de posición, gestión de apalancamiento, riesgos de cartera, estrategias de protección y medición de riesgos.',
      fr: 'Dimensionnement des positions, gestion du levier, risques de portefeuille, stratégies de protection et mesure des risques.',
      ru: 'Определение размера позиции, управление кредитным плечом, риски портфеля, стратегии защиты и измерение рисков.',
      de: 'Positionsgröße, Hebelverwaltung, Portfoliorisiken, Schutzstrategien und Risikomessung.',
      pt: 'Dimensionamento de posição, gestão de alavancagem, riscos de portfólio, estratégias de proteção e medição de riscos.',
    },
    outcomes: {
      tr: [
        'Pozisyon boyutu hesaplama',
        'Risk/ödül oranı belirleme',
        'Stop-loss kullanımı',
        'Portföy çeşitlendirme',
        'Risk ölçümü',
      ],
      en: [
        'Calculating position size',
        'Determining risk/reward ratio',
        'Using stop-loss',
        'Portfolio diversification',
        'Risk measurement',
      ],
      es: [
        'Calcular tamaño de posición',
        'Determinar relación riesgo/recompensa',
        'Usar stop-loss',
        'Diversificación de cartera',
        'Medición de riesgos',
      ],
      fr: [
        'Calculer la taille de position',
        'Déterminer le ratio risque/récompense',
        'Utiliser le stop-loss',
        'Diversification du portefeuille',
        'Mesure des risques',
      ],
      ru: [
        'Расчет размера позиции',
        'Определение соотношения риск/вознаграждение',
        'Использование стоп-лосса',
        'Диверсификация портфеля',
        'Измерение рисков',
      ],
      de: [
        'Berechnung der Positionsgröße',
        'Bestimmung des Risiko/Ertrags-Verhältnisses',
        'Verwenden von Stop-Loss',
        'Portfoliodiversifizierung',
        'Risikomessung',
      ],
      pt: [
        'Calcular tamanho de posição',
        'Determinar relação risco/recompensa',
        'Usar stop-loss',
        'Diversificação de portfólio',
        'Medição de riscos',
      ],
    },
    modules: [
      {
        title: {
          tr: 'Risk Kavramı',
          en: 'Risk Concepts',
          es: 'Conceptos de Riesgo',
          fr: 'Concepts de Risque',
          ru: 'Концепции риска',
          de: 'Risikokonzepte',
          pt: 'Conceitos de Risco',
        },
        lessons: ['Risk nedir?', 'Risk türleri', 'Risk ölçümü'],
        duration: '2',
      },
      {
        title: {
          tr: 'Pozisyon Boyutu',
          en: 'Position Sizing',
          es: 'Tamaño de Posición',
          fr: 'Dimensionnement des Positions',
          ru: 'Размер позиции',
          de: 'Positionsgröße',
          pt: 'Dimensionamento de Posição',
        },
        lessons: ['Pozisyon boyutu nedir?', 'Hesaplama yöntemleri', 'Örnekler'],
        duration: '3',
      },
      {
        title: {
          tr: 'Risk/Ödül Oranı',
          en: 'Risk/Reward Ratio',
          es: 'Relación Riesgo/Recompensa',
          fr: 'Ratio Risque/Récompense',
          ru: 'Соотношение риск/вознаграждение',
          de: 'Risiko/Ertrags-Verhältnis',
          pt: 'Relação Risco/Recompensa',
        },
        lessons: ['Risk/ödül nedir?', 'Hesaplama', 'Stratejik kullanım'],
        duration: '2',
      },
      {
        title: {
          tr: 'Stop-Loss ve Take-Profit',
          en: 'Stop-Loss and Take-Profit',
          es: 'Stop-Loss y Take-Profit',
          fr: 'Stop-Loss et Take-Profit',
          ru: 'Стоп-лосс и тейк-профит',
          de: 'Stop-Loss und Take-Profit',
          pt: 'Stop-Loss e Take-Profit',
        },
        lessons: ['Stop-loss nedir?', 'Take-profit nedir?', 'Yerleştirme stratejileri'],
        duration: '3',
      },
      {
        title: {
          tr: 'Portföy Riskleri',
          en: 'Portfolio Risks',
          es: 'Riesgos de Cartera',
          fr: 'Risques de Portefeuille',
          ru: 'Риски портфеля',
          de: 'Portfoliorisiken',
          pt: 'Riscos de Portfólio',
        },
        lessons: ['Portföy riski', 'Korelasyon', 'Çeşitlendirme', 'Risk dağılımı'],
        duration: '3',
      },
      {
        title: {
          tr: 'Koruma Stratejileri',
          en: 'Protection Strategies',
          es: 'Estrategias de Protección',
          fr: 'Stratégies de Protection',
          ru: 'Стратегии защиты',
          de: 'Schutzstrategien',
          pt: 'Estratégias de Proteção',
        },
        lessons: ['Hedging', 'Insurance', 'Diversification', 'Risk limitleri'],
        duration: '3',
      },
    ],
    prerequisites: {
      tr: ['Finansal Piyasalar kursu', 'Temel matematik'],
      en: ['Financial Markets course', 'Basic math'],
      es: ['Curso de Mercados Financieros', 'Matemáticas básicas'],
      fr: ['Cours de Marchés Financiers', 'Mathématiques de base'],
      ru: ['Курс Финансовые рынки', 'Базовая математика'],
      de: ['Kurs Finanzmärkte', 'Grundlegende Mathematik'],
      pt: ['Curso de Mercados Financeiros', 'Matemática básica'],
    },
    skillsGained: {
      tr: [
        'Risk analizi',
        'Pozisyon yönetimi',
        'Stop-loss kullanımı',
        'Portföy optimizasyonu',
        'Risk ölçümü',
      ],
      en: [
        'Risk analysis',
        'Position management',
        'Stop-loss usage',
        'Portfolio optimization',
        'Risk measurement',
      ],
      es: [
        'Análisis de riesgos',
        'Gestión de posiciones',
        'Uso de stop-loss',
        'Optimización de cartera',
        'Medición de riesgos',
      ],
      fr: [
        'Analyse des risques',
        'Gestion des positions',
        'Utilisation du stop-loss',
        'Optimisation du portefeuille',
        'Mesure des risques',
      ],
      ru: [
        'Анализ рисков',
        'Управление позициями',
        'Использование стоп-лосса',
        'Оптимизация портфеля',
        'Измерение рисков',
      ],
      de: [
        'Risikoanalyse',
        'Positionsverwaltung',
        'Stop-Loss-Verwendung',
        'Portfoliooptimierung',
        'Risikomessung',
      ],
      pt: [
        'Análise de riscos',
        'Gestão de posições',
        'Uso de stop-loss',
        'Otimização de portfólio',
        'Medição de riscos',
      ],
    },
  },
  {
    id: 8,
    category: 'Trading Psychology',
    level: 'Intermediate',
    duration: '8',
    lessons: 14,
    rating: 4.8,
    enrolled: 1750,
    progress: 82,
    hasQuiz: true,
    contentTypes: ['video', 'quiz', 'interactive'],
    lastUpdated: '2024-01-30',
    tags: ['psikoloji', 'disiplin', 'duygu', 'planlama'],
    title: {
      tr: 'İşlem Psikolojisi',
      en: 'Trading Psychology',
      es: 'Psicología del Trading',
      fr: 'Psychologie du Trading',
      ru: 'Психология торговли',
      de: 'Trading-Psychologie',
      pt: 'Psicologia do Trading',
    },
    description: {
      tr: 'Duygusal disiplin, bilişsel hatalar, planlı işlem, günlük tutma ve psikolojik engellerin aşılması.',
      en: 'Emotional discipline, cognitive biases, planned trading, journaling, and overcoming psychological barriers.',
      es: 'Disciplina emocional, sesgos cognitivos, trading planificado, registro de operaciones y superación de barreras psicológicas.',
      fr: 'Discipline émotionnelle, biais cognitifs, trading planifié, tenue de journal et surmonter les barrières psychologiques.',
      ru: 'Эмоциональная дисциплина, когнитивные искажения, плановая торговля, ведение журнала и преодоление психологических барьеров.',
      de: 'Emotionale Disziplin, kognitive Verzerrungen, geplantes Trading, Journaling und Überwindung psychologischer Barrieren.',
      pt: 'Disciplina emocional, vieses cognitivos, trading planejado, registro de operações e superação de barreiras psicológicas.',
    },
    outcomes: {
      tr: [
        'Duygusal kontrol',
        'Bilişsel hataları tanıma',
        'İşlem planı oluşturma',
        'Günlük tutma',
        'Psikolojik engelleri aşma',
      ],
      en: [
        'Emotional control',
        'Recognizing cognitive biases',
        'Creating trading plan',
        'Journaling',
        'Overcoming psychological barriers',
      ],
      es: [
        'Control emocional',
        'Reconocer sesgos cognitivos',
        'Crear plan de trading',
        'Registro de operaciones',
        'Superar barreras psicológicas',
      ],
      fr: [
        'Contrôle émotionnel',
        'Reconnaître les biais cognitifs',
        'Créer un plan de trading',
        'Tenue de journal',
        'Surmonter les barrières psychologiques',
      ],
      ru: [
        'Эмоциональный контроль',
        'Распознавание когнитивных искажений',
        'Создание торгового плана',
        'Ведение журнала',
        'Преодоление психологических барьеров',
      ],
      de: [
        'Emotionale Kontrolle',
        'Erkennen kognitiver Verzerrungen',
        'Erstellen eines Trading-Plans',
        'Journaling',
        'Überwindung psychologischer Barrieren',
      ],
      pt: [
        'Controle emocional',
        'Reconhecer vieses cognitivos',
        'Criar plano de trading',
        'Registro de operações',
        'Superar barreiras psicológicas',
      ],
    },
    modules: [
      {
        title: {
          tr: 'Duygusal Disiplin',
          en: 'Emotional Discipline',
          es: 'Disciplina Emocional',
          fr: 'Discipline Émotionnelle',
          ru: 'Эмоциональная дисциплина',
          de: 'Emotionale Disziplin',
          pt: 'Disciplina Emocional',
        },
        lessons: ['Duygular ve işlem', 'Kontrol teknikleri', 'Stres yönetimi'],
        duration: '2',
      },
      {
        title: {
          tr: 'Bilişsel Hatalar',
          en: 'Cognitive Biases',
          es: 'Sesgos Cognitivos',
          fr: 'Biais Cognitifs',
          ru: 'Когнитивные искажения',
          de: 'Kognitive Verzerrungen',
          pt: 'Vieses Cognitivos',
        },
        lessons: ['Onay yanlılığı', 'Kayıp korkusu', 'Aşırı güven', 'Diğer hatalar'],
        duration: '3',
      },
      {
        title: {
          tr: 'İşlem Planı',
          en: 'Trading Plan',
          es: 'Plan de Trading',
          fr: 'Plan de Trading',
          ru: 'Торговый план',
          de: 'Trading-Plan',
          pt: 'Plano de Trading',
        },
        lessons: ['Plan nedir?', 'Plan oluşturma', 'Plan uygulama', 'Plan güncelleme'],
        duration: '3',
      },
      {
        title: {
          tr: 'Günlük Tutma',
          en: 'Journaling',
          es: 'Registro de Operaciones',
          fr: 'Tenue de Journal',
          ru: 'Ведение журнала',
          de: 'Journaling',
          pt: 'Registro de Operações',
        },
        lessons: ['Günlük nedir?', 'Ne kaydedilmeli?', 'Analiz yöntemleri'],
        duration: '2',
      },
      {
        title: {
          tr: 'Psikolojik Engeller',
          en: 'Psychological Barriers',
          es: 'Barreras Psicológicas',
          fr: 'Barrières Psychologiques',
          ru: 'Психологические барьеры',
          de: 'Psychologische Barrieren',
          pt: 'Barreiras Psicológicas',
        },
        lessons: ['Korku', 'Açgözlülük', 'Sabırsızlık', 'Aşırı işlem'],
        duration: '4',
      },
    ],
    prerequisites: {
      tr: ['Temel işlem bilgisi', 'Kendini tanıma isteği'],
      en: ['Basic trading knowledge', 'Desire for self-awareness'],
      es: ['Conocimientos básicos de trading', 'Deseo de autoconocimiento'],
      fr: ['Connaissances de base en trading', 'Désir de conscience de soi'],
      ru: ['Базовые знания торговли', 'Желание самосознания'],
      de: ['Grundkenntnisse im Trading', 'Wunsch nach Selbstbewusstsein'],
      pt: ['Conhecimentos básicos de trading', 'Desejo de autoconhecimento'],
    },
    skillsGained: {
      tr: [
        'Duygusal kontrol',
        'Bilişsel farkındalık',
        'Planlı işlem',
        'Günlük tutma',
        'Psikolojik dayanıklılık',
      ],
      en: [
        'Emotional control',
        'Cognitive awareness',
        'Planned trading',
        'Journaling',
        'Psychological resilience',
      ],
      es: [
        'Control emocional',
        'Conciencia cognitiva',
        'Trading planificado',
        'Registro de operaciones',
        'Resiliencia psicológica',
      ],
      fr: [
        'Contrôle émotionnel',
        'Conscience cognitive',
        'Trading planifié',
        'Tenue de journal',
        'Résilience psychologique',
      ],
      ru: [
        'Эмоциональный контроль',
        'Когнитивная осознанность',
        'Плановая торговля',
        'Ведение журнала',
        'Психологическая устойчивость',
      ],
      de: [
        'Emotionale Kontrolle',
        'Kognitive Bewusstheit',
        'Geplantes Trading',
        'Journaling',
        'Psychologische Widerstandsfähigkeit',
      ],
      pt: [
        'Controle emocional',
        'Consciência cognitiva',
        'Trading planejado',
        'Registro de operações',
        'Resiliência psicológica',
      ],
    },
  },
  {
    id: 9,
    category: 'Algorithmic Trading',
    level: 'Advanced',
    duration: '20',
    lessons: 28,
    rating: 4.6,
    enrolled: 850,
    progress: 60,
    hasQuiz: true,
    contentTypes: ['video', 'quiz', 'code', 'interactive'],
    lastUpdated: '2024-02-20',
    tags: ['algoritma', 'otomasyon', 'backtest', 'python'],
    title: {
      tr: 'Algoritmik İşlemler',
      en: 'Algorithmic Trading',
      es: 'Trading Algorítmico',
      fr: 'Trading Algorithmique',
      ru: 'Алгоритмическая торговля',
      de: 'Algorithmisches Trading',
      pt: 'Trading Algorítmico',
    },
    description: {
      tr: 'Strateji otomasyonu, backtest yöntemleri, risk parametreleri, basit algoritmalar ve programlama temelleri.',
      en: 'Strategy automation, backtesting methods, risk parameters, simple algorithms, and programming fundamentals.',
      es: 'Automatización de estrategias, métodos de backtesting, parámetros de riesgo, algoritmos simples y fundamentos de programación.',
      fr: 'Automatisation des stratégies, méthodes de backtesting, paramètres de risque, algorithmes simples et fondamentaux de programmation.',
      ru: 'Автоматизация стратегий, методы бэктестинга, параметры риска, простые алгоритмы и основы программирования.',
      de: 'Strategieautomatisierung, Backtesting-Methoden, Risikoparameter, einfache Algorithmen und Programmiergrundlagen.',
      pt: 'Automação de estratégias, métodos de backtesting, parâmetros de risco, algoritmos simples e fundamentos de programação.',
    },
    outcomes: {
      tr: [
        'Algoritma tasarlama',
        'Backtest yapma',
        'Strateji otomasyonu',
        'Risk parametreleri',
        'Programlama temelleri',
      ],
      en: [
        'Designing algorithms',
        'Performing backtests',
        'Strategy automation',
        'Risk parameters',
        'Programming fundamentals',
      ],
      es: [
        'Diseñar algoritmos',
        'Realizar backtests',
        'Automatización de estrategias',
        'Parámetros de riesgo',
        'Fundamentos de programación',
      ],
      fr: [
        'Concevoir des algorithmes',
        'Effectuer des backtests',
        'Automatisation des stratégies',
        'Paramètres de risque',
        'Fondamentaux de programmation',
      ],
      ru: [
        'Проектирование алгоритмов',
        'Проведение бэктестов',
        'Автоматизация стратегий',
        'Параметры риска',
        'Основы программирования',
      ],
      de: [
        'Entwerfen von Algorithmen',
        'Durchführen von Backtests',
        'Strategieautomatisierung',
        'Risikoparameter',
        'Programmiergrundlagen',
      ],
      pt: [
        'Projetar algoritmos',
        'Realizar backtests',
        'Automação de estratégias',
        'Parâmetros de risco',
        'Fundamentos de programação',
      ],
    },
    modules: [
      {
        title: {
          tr: 'Algoritmik İşleme Giriş',
          en: 'Introduction to Algorithmic Trading',
          es: 'Introducción al Trading Algorítmico',
          fr: 'Introduction au Trading Algorithmique',
          ru: 'Введение в алгоритмическую торговлю',
          de: 'Einführung in das Algorithmische Trading',
          pt: 'Introdução ao Trading Algorítmico',
        },
        lessons: ['Algoritmik işlem nedir?', 'Avantajlar', 'Dezavantajlar', 'Kullanım alanları'],
        duration: '3',
      },
      {
        title: {
          tr: 'Programlama Temelleri',
          en: 'Programming Fundamentals',
          es: 'Fundamentos de Programación',
          fr: 'Fondamentaux de Programmation',
          ru: 'Основы программирования',
          de: 'Programmiergrundlagen',
          pt: 'Fundamentos de Programação',
        },
        lessons: ['Python temelleri', 'Veri yapıları', 'Fonksiyonlar', 'Kütüphaneler'],
        duration: '4',
      },
      {
        title: {
          tr: 'Strateji Geliştirme',
          en: 'Strategy Development',
          es: 'Desarrollo de Estrategias',
          fr: 'Développement de Stratégies',
          ru: 'Разработка стратегий',
          de: 'Strategieentwicklung',
          pt: 'Desenvolvimento de Estratégias',
        },
        lessons: ['Strateji tasarımı', 'Sinyal üretimi', 'Giriş/çıkış kuralları'],
        duration: '4',
      },
      {
        title: {
          tr: 'Backtesting',
          en: 'Backtesting',
          es: 'Backtesting',
          fr: 'Backtesting',
          ru: 'Бэктестинг',
          de: 'Backtesting',
          pt: 'Backtesting',
        },
        lessons: ['Backtest nedir?', 'Veri hazırlama', 'Backtest yapma', 'Sonuç analizi'],
        duration: '5',
      },
      {
        title: {
          tr: 'Risk Parametreleri',
          en: 'Risk Parameters',
          es: 'Parámetros de Riesgo',
          fr: 'Paramètres de Risque',
          ru: 'Параметры риска',
          de: 'Risikoparameter',
          pt: 'Parâmetros de Risco',
        },
        lessons: ['Pozisyon boyutu', 'Stop-loss', 'Take-profit', 'Risk limitleri'],
        duration: '4',
      },
      {
        title: {
          tr: 'Otomasyon ve Deployment',
          en: 'Automation and Deployment',
          es: 'Automatización y Despliegue',
          fr: 'Automatisation et Déploiement',
          ru: 'Автоматизация и развертывание',
          de: 'Automatisierung und Bereitstellung',
          pt: 'Automação e Implantação',
        },
        lessons: ['API entegrasyonu', 'Otomatik işlem', 'Monitoring', 'Bakım'],
        duration: '5',
      },
    ],
    prerequisites: {
      tr: ['Teknik Analiz kursu', 'Temel programlama bilgisi', 'Python önerilir'],
      en: ['Technical Analysis course', 'Basic programming knowledge', 'Python recommended'],
      es: ['Curso de Análisis Técnico', 'Conocimientos básicos de programación', 'Se recomienda Python'],
      fr: ['Cours d\'Analyse Technique', 'Connaissances de base en programmation', 'Python recommandé'],
      ru: ['Курс Технический анализ', 'Базовые знания программирования', 'Рекомендуется Python'],
      de: ['Kurs Technische Analyse', 'Grundkenntnisse in Programmierung', 'Python empfohlen'],
      pt: ['Curso de Análise Técnica', 'Conhecimentos básicos de programação', 'Python recomendado'],
    },
    skillsGained: {
      tr: [
        'Algoritma tasarımı',
        'Backtest yapma',
        'Python programlama',
        'Strateji otomasyonu',
        'Risk yönetimi',
      ],
      en: [
        'Algorithm design',
        'Performing backtests',
        'Python programming',
        'Strategy automation',
        'Risk management',
      ],
      es: [
        'Diseño de algoritmos',
        'Realizar backtests',
        'Programación en Python',
        'Automatización de estrategias',
        'Gestión de riesgos',
      ],
      fr: [
        'Conception d\'algorithmes',
        'Effectuer des backtests',
        'Programmation Python',
        'Automatisation des stratégies',
        'Gestion des risques',
      ],
      ru: [
        'Проектирование алгоритмов',
        'Проведение бэктестов',
        'Программирование на Python',
        'Автоматизация стратегий',
        'Управление рисками',
      ],
      de: [
        'Algorithmusentwurf',
        'Durchführen von Backtests',
        'Python-Programmierung',
        'Strategieautomatisierung',
        'Risikomanagement',
      ],
      pt: [
        'Design de algoritmos',
        'Realizar backtests',
        'Programação Python',
        'Automação de estratégias',
        'Gestão de riscos',
      ],
    },
  },
];
