import { chromium } from 'playwright-core';
const baseUrl = 'http://127.0.0.1:4173/';
const viewports = [{ name: 'mobile-360', width: 360, height: 800, minVisualWidth: 220 }, { name: 'mobile-390', width: 390, height: 844, minVisualWidth: 240 }, { name: 'desktop', width: 1440, height: 900, minVisualWidth: 300 }];
const lessons = [{ key: 'zones', title: 'Fiyat neden bazı bölgelerde tekrar durur' }];
const legacySelectors = ['[aria-label="chart-zone-single-line"]','[aria-label="chart-zone-reaction-area"]','[aria-label="chart-zone-hard-wall"]'];
async function openLesson(page, title) { await page.goto(baseUrl, { waitUntil: 'networkidle' }); await page.getByText('Öğrenmeye Başla', { exact: true }).waitFor({ timeout: 10000 }); await page.getByRole('button', { name: /Grafikleri Korkmadan Oku/i }).first().click(); await page.getByText('BAŞLANGIÇ · 4 KISA DERS', { exact: true }).waitFor(); await page.getByRole('button', { name: new RegExp(title, 'i') }).click(); await page.getByText(/Adım 1\//).waitFor(); }
async function largestImage(page) { const images = page.locator('[role="img"]'); let largest; for (let i = 0; i < await images.count(); i += 1) { const image = images.nth(i); if (!(await image.isVisible())) continue; const box = await image.boundingBox(); if (box && (!largest || box.width * box.height > largest.width * largest.height)) largest = box; } return largest; }
async function noOverflow(page, label) { const d = await page.evaluate(() => ({ viewport: document.documentElement.clientWidth, page: document.documentElement.scrollWidth })); if (d.page > d.viewport + 1) throw new Error(`${label}: horizontal overflow ${d.page}px > ${d.viewport}px`); }
function assertLandscape(box, label) { const ratio = box.width / box.height; if (ratio < 1.47 || ratio > 1.53) throw new Error(`${label}: chart artwork distorted at ${ratio.toFixed(2)}:1; expected 3:2`); }
const browser = await chromium.launch({ executablePath: process.env.CHROME_BIN, headless: true });
try { for (const viewport of viewports) { for (const lesson of lessons) { const page = await browser.newPage({ viewport: { width: viewport.width, height: viewport.height } }); const diagnostics = []; page.on('pageerror', (error) => diagnostics.push(`[pageerror] ${error.stack || error.message}`)); page.on('requestfailed', (request) => diagnostics.push(`[requestfailed] ${request.url()} :: ${request.failure()?.errorText || 'unknown'}`)); await openLesson(page, lesson.title); const first = await page.getByText(/Adım 1\//).innerText(); const total = Number(first.match(/\/(\d+)/)?.[1] ?? 1); for (let step = 1; step <= total; step += 1) { const label = `${lesson.key}-${viewport.name}-step-${step}`; await noOverflow(page, label); const visual = await largestImage(page); if (!visual) throw new Error(`${label}: no visible chart teaching visual found`); if (visual.width < viewport.minVisualWidth) throw new Error(`${label}: visual too small at ${visual.width.toFixed(1)}px`); if (visual.width > (viewport.width < 500 ? 360 : 620) + 1) throw new Error(`${label}: visual too wide at ${visual.width.toFixed(1)}px`); if (visual.x < -1 || visual.x + visual.width > viewport.width + 1) throw new Error(`${label}: visual escapes viewport`); if (visual.height > viewport.height * 0.72) throw new Error(`${label}: visual too tall at ${visual.height.toFixed(1)}px`); assertLandscape(visual, label); const legacy = page.locator(legacySelectors.join(', ')); if (await legacy.count()) throw new Error(`${label}: legacy card-based chart composition must not replace the 3:2 SVG teaching scene`); if (step === 2 || step === 3 || step === total) await page.screenshot({ path: `visual-qa/${label}.png`, fullPage: true }); if (step < total) { await page.getByRole('button', { name: /Sonraki adıma geç/i }).click(); await page.getByText(new RegExp(`Adım ${step + 1}\\/${total}`)).waitFor(); } } if (diagnostics.length) throw new Error(`${viewport.name}/${lesson.key} diagnostics:\n${diagnostics.join('\n')}`); await page.close(); console.log(`${viewport.name}/${lesson.key}: ${total}/${total} minimal 3:2 chart steps PASS`); } } } finally { await browser.close(); }
