import React from 'react';
import { StyleSheet, View } from 'react-native';
import { defaultLearningTheme, type LearningTheme } from '../../theme/learningTheme';

type Topic = 'probability' | 'expectancy' | 'winratePayoff' | 'backtest' | 'outOfSample' | 'costs' | 'overfitting' | 'lookahead' | 'survivorship' | 'leakage' | 'robustness' | 'automation';
export interface AcademyQuantPremiumHookVisualProps { assetRef:string; alt:string; theme?:LearningTheme; }

function topicFor(assetRef:string):Topic|undefined {
  if(assetRef.includes('olaslikla-dusunmek')) return 'probability';
  if(assetRef.includes('expectancy-nedir')) return 'expectancy';
  if(assetRef.includes('win-rate-payoff-dengesi')) return 'winratePayoff';
  if(assetRef.includes('backtest-ne-soyler')) return 'backtest';
  if(assetRef.includes('orneklem-ve-out-of-sample')) return 'outOfSample';
  if(assetRef.includes('backtestte-islem-maliyetleri')) return 'costs';
  if(assetRef.includes('overfitting-nedir')) return 'overfitting';
  if(assetRef.includes('look-ahead-bias-nedir')) return 'lookahead';
  if(assetRef.includes('survivorship-bias-nedir')) return 'survivorship';
  if(assetRef.includes('data-leakage-nedir')) return 'leakage';
  if(assetRef.includes('robustness-nasil-test-edilir')) return 'robustness';
  if(assetRef.includes('otomasyonun-sinirlari')) return 'automation';
  return undefined;
}
export function isAcademyQuantPremiumHookAsset(assetRef:string):boolean { return Boolean(topicFor(assetRef)); }

export function AcademyQuantPremiumHookVisual({assetRef,alt,theme=defaultLearningTheme}:AcademyQuantPremiumHookVisualProps){
  const topic=topicFor(assetRef); if(!topic) return null; const s=createStyles(theme);
  return <View style={s.shell} accessibilityRole="image" accessibilityLabel={alt}>
    <View style={s.gridH1}/><View style={s.gridH2}/><View style={s.gridV1}/><View style={s.gridV2}/>
    {topic==='probability'?<Probability s={s}/>:null}
    {topic==='expectancy'?<Expectancy s={s}/>:null}
    {topic==='winratePayoff'?<WinPayoff s={s}/>:null}
    {topic==='backtest'?<Backtest s={s}/>:null}
    {topic==='outOfSample'?<OutOfSample s={s}/>:null}
    {topic==='costs'?<Costs s={s}/>:null}
    {topic==='overfitting'?<Overfit s={s}/>:null}
    {topic==='lookahead'?<Lookahead s={s}/>:null}
    {topic==='survivorship'?<Survivorship s={s}/>:null}
    {topic==='leakage'?<Leakage s={s}/>:null}
    {topic==='robustness'?<Robustness s={s}/>:null}
    {topic==='automation'?<Automation s={s}/>:null}
  </View>;
}

type S=ReturnType<typeof createStyles>;
function Probability({s}:{s:S}){return <View style={s.stage}><View style={s.dist}>{[36,58,92,132,102,74,48].map((h,i)=><View key={i} style={[s.distBar,{height:h},i===3&&s.distPeak]}/>)}</View><View style={s.probabilityHalo}/></View>}
function Expectancy({s}:{s:S}){return <View style={s.stage}><View style={s.scaleBeam}/><View style={s.scaleStem}/><View style={[s.scalePan,s.scaleLeft]}><View style={[s.weight,{width:76,height:48}]}/><View style={[s.weight,s.weightAccent,{width:46,height:30}]}/></View><View style={[s.scalePan,s.scaleRight]}><View style={[s.weight,s.weightWarn,{width:64,height:58}]}/></View><View style={s.scaleBase}/></View>}
function WinPayoff({s}:{s:S}){return <View style={s.stage}><View style={s.comparePanel}><View style={s.winDots}>{[0,1,2,3,4,5,6,7].map(i=><View key={i} style={[s.smallDot,i<6?s.smallDotGood:s.smallDotWarn]}/>)}</View><View style={[s.payoffBar,{width:'34%'}]}/><View style={[s.lossBar,{width:'82%'}]}/></View><View style={s.compareDivider}/><View style={[s.comparePanel,{right:0,left:'51%'}]}><View style={s.winDots}>{[0,1,2,3,4,5,6,7].map(i=><View key={i} style={[s.smallDot,i<3?s.smallDotGood:s.smallDotMuted]}/>)}</View><View style={[s.payoffBar,{width:'84%'}]}/><View style={[s.lossBar,{width:'32%'}]}/></View></View>}
function Backtest({s}:{s:S}){return <View style={s.stage}><View style={s.flowRow}><FlowNode s={s} kind="data"/><FlowArrow s={s}/><FlowNode s={s} kind="rules"/><FlowArrow s={s}/><FlowNode s={s} kind="sim"/><FlowArrow s={s}/><FlowNode s={s} kind="report" accent/></View></View>}
function FlowArrow({s}:{s:S}){return <View style={s.flowArrow}><View style={s.flowArrowHead}/></View>}
function FlowNode({s,kind,accent=false}:{s:S;kind:'data'|'rules'|'sim'|'report';accent?:boolean}){return <View style={[s.flowNode,accent&&s.flowNodeAccent]}>{kind==='data'?<View style={s.dataStack}><View style={s.dataLayer}/><View style={s.dataLayer}/><View style={s.dataLayer}/></View>:null}{kind==='rules'?<View style={s.ruleGlyph}><View style={s.ruleLine}/><View style={s.ruleLine}/><View style={s.ruleLine}/></View>:null}{kind==='sim'?<View style={s.simGlyph}><View style={s.simDot}/><View style={[s.simDot,{left:18,top:7}]}/><View style={[s.simDot,{left:34,top:20}]}/></View>:null}{kind==='report'?<View style={s.reportGlyph}><View style={[s.reportBar,{height:18}]}/><View style={[s.reportBar,{height:34}]}/><View style={[s.reportBar,{height:25}]}/></View>:null}</View>}
function OutOfSample({s}:{s:S}){return <View style={s.stage}><View style={s.sampleLeft}>{[0,1,2,3].map(i=><View key={i} style={[s.sampleCurve,{top:38+i*31,width:`${56+i*7}%` as `${number}%`}]}/>)}</View><View style={s.sampleWall}/><View style={s.sampleRight}><View style={s.lockRing}><View style={s.lockBody}/></View></View></View>}
function Costs({s}:{s:S}){return <View style={s.stage}><View style={s.costTrack}><View style={[s.costGross,{width:'92%'}]}/></View><View style={s.minusTickOne}/><View style={s.minusTickTwo}/><View style={s.minusTickThree}/><View style={s.costNet}/></View>}
function Overfit({s}:{s:S}){return <View style={s.stage}><View style={s.overfitLeft}><View style={s.overfitSmooth}/><View style={s.overfitJagged}><View style={[s.jag,{left:'6%',top:'57%',width:'18%',transform:[{rotate:'-38deg'}]}]}/><View style={[s.jag,{left:'20%',top:'34%',width:'20%',transform:[{rotate:'43deg'}]}]}/><View style={[s.jag,{left:'36%',top:'52%',width:'21%',transform:[{rotate:'-44deg'}]}]}/><View style={[s.jag,{left:'53%',top:'28%',width:'20%',transform:[{rotate:'42deg'}]}]}/><View style={[s.jag,{left:'69%',top:'45%',width:'20%',transform:[{rotate:'-37deg'}]}]}/></View></View><View style={s.overfitDivider}/><View style={s.overfitRight}><View style={s.testFall}/><View style={s.testNoise}/></View></View>}
function Lookahead({s}:{s:S}){return <View style={s.stage}><View style={s.timeLine}/><View style={s.decisionDot}/><View style={s.futureZone}/><View style={s.forbiddenArrow}/><View style={s.forbiddenSlash}/></View>}
function Survivorship({s}:{s:S}){return <View style={s.stage}><View style={s.assetGrid}>{Array.from({length:15}).map((_,i)=><View key={i} style={[s.assetCell,(i===2||i===6||i===11||i===13)&&s.assetDead]}>{(i===2||i===6||i===11||i===13)?<View style={s.deadSlash}/>:<View style={s.assetInner}/>}</View>)}</View></View>}
function Leakage({s}:{s:S}){return <View style={s.stage}><View style={s.tank}><View style={s.tankFill}/></View><View style={s.leakArrow}/><View style={s.blockGate}><View style={s.gateSlash}/></View><View style={[s.tank,s.tankRight]}><View style={[s.tankFill,s.tankFillMuted]}/></View></View>}
function Robustness({s}:{s:S}){return <View style={s.stage}><View style={s.robustLeft}><View style={[s.terrainBar,{height:20}]}/><View style={[s.terrainBar,{height:30}]}/><View style={[s.terrainBar,{height:128}]}/><View style={[s.terrainBar,{height:28}]}/><View style={[s.terrainBar,{height:18}]}/></View><View style={s.robustDivider}/><View style={s.robustRight}><View style={[s.terrainBar,s.terrainGood,{height:68}]}/><View style={[s.terrainBar,s.terrainGood,{height:82}]}/><View style={[s.terrainBar,s.terrainGood,{height:88}]}/><View style={[s.terrainBar,s.terrainGood,{height:80}]}/><View style={[s.terrainBar,s.terrainGood,{height:70}]}/></View></View>}
function Automation({s}:{s:S}){return <View style={s.stage}><View style={s.pipeline}><FlowNode s={s} kind="data"/><FlowArrow s={s}/><FlowNode s={s} kind="sim"/><FlowArrow s={s}/><FlowNode s={s} kind="report" accent/></View><View style={s.guardRail}><View style={s.guardDot}/><View style={s.guardDot}/><View style={s.killSwitch}><View style={s.killInner}/></View></View></View>}

const createStyles=(theme:LearningTheme)=>StyleSheet.create({
 shell:{width:'100%',minHeight:300,overflow:'hidden',borderRadius:22,borderWidth:1,borderColor:'#244B61',backgroundColor:'#071521',padding:16,position:'relative'},stage:{flex:1,minHeight:266,position:'relative',overflow:'hidden',borderRadius:18,backgroundColor:'#091B29',borderWidth:1,borderColor:'#1D4054'},gridH1:{position:'absolute',left:16,right:16,top:'34%',height:1,backgroundColor:'#102E40'},gridH2:{position:'absolute',left:16,right:16,top:'67%',height:1,backgroundColor:'#102E40'},gridV1:{position:'absolute',top:16,bottom:16,left:'36%',width:1,backgroundColor:'#102E40'},gridV2:{position:'absolute',top:16,bottom:16,left:'69%',width:1,backgroundColor:'#102E40'},
 dist:{position:'absolute',left:'9%',right:'9%',bottom:36,height:170,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',gap:8},distBar:{flex:1,maxWidth:34,borderTopLeftRadius:9,borderTopRightRadius:9,backgroundColor:'#557385'},distPeak:{backgroundColor:'#51D2C0'},probabilityHalo:{position:'absolute',width:78,height:78,borderRadius:39,borderWidth:2,borderColor:'#4AC7B6',left:'44%',top:'28%',opacity:.34},
 scaleBeam:{position:'absolute',left:'18%',right:'18%',top:'36%',height:5,borderRadius:3,backgroundColor:'#658294',transform:[{rotate:'4deg'}]},scaleStem:{position:'absolute',width:5,height:96,left:'49%',top:'37%',backgroundColor:'#658294'},scaleBase:{position:'absolute',width:98,height:8,borderRadius:4,left:'37%',bottom:38,backgroundColor:'#496577'},scalePan:{position:'absolute',top:'43%',width:116,minHeight:94,borderRadius:18,borderWidth:1,borderColor:'#35586D',backgroundColor:'#102638',padding:12,justifyContent:'flex-end',gap:7},scaleLeft:{left:'8%'},scaleRight:{right:'8%'},weight:{borderRadius:9,backgroundColor:'#718E9E'},weightAccent:{backgroundColor:'#4FCDBB'},weightWarn:{backgroundColor:'#9B704E'},
 comparePanel:{position:'absolute',left:0,top:0,bottom:0,width:'49%',padding:18,justifyContent:'center',gap:16},compareDivider:{position:'absolute',left:'50%',top:20,bottom:20,width:1,backgroundColor:'#294B60'},winDots:{flexDirection:'row',flexWrap:'wrap',gap:8},smallDot:{width:20,height:20,borderRadius:10},smallDotGood:{backgroundColor:'#50D1BF'},smallDotWarn:{backgroundColor:'#AA7650'},smallDotMuted:{backgroundColor:'#466274'},payoffBar:{height:15,borderRadius:8,backgroundColor:'#50D1BF'},lossBar:{height:15,borderRadius:8,backgroundColor:'#9A6A48'},
 flowRow:{flex:1,flexDirection:'row',alignItems:'center',justifyContent:'space-around',paddingHorizontal:12,gap:6},flowNode:{width:58,height:78,borderRadius:18,borderWidth:1,borderColor:'#35586D',backgroundColor:'#11283A',alignItems:'center',justifyContent:'center'},flowNodeAccent:{borderColor:'#2D8378',backgroundColor:'#0E3838'},flowArrow:{width:24,height:3,borderRadius:2,backgroundColor:'#4ECFBD',position:'relative'},flowArrowHead:{position:'absolute',right:-1,top:-4,width:10,height:10,borderTopWidth:3,borderRightWidth:3,borderColor:'#4ECFBD',transform:[{rotate:'45deg'}]},dataStack:{gap:4},dataLayer:{width:28,height:7,borderRadius:4,backgroundColor:'#7895A4'},ruleGlyph:{gap:5},ruleLine:{width:30,height:5,borderRadius:3,backgroundColor:'#7895A4'},simGlyph:{width:44,height:38,position:'relative'},simDot:{position:'absolute',width:10,height:10,borderRadius:5,backgroundColor:'#5CD7C6',left:2,top:19},reportGlyph:{height:42,flexDirection:'row',alignItems:'flex-end',gap:4},reportBar:{width:7,borderRadius:4,backgroundColor:'#5CD7C6'},
 sampleLeft:{position:'absolute',left:'7%',top:'13%',bottom:'13%',width:'58%',borderRadius:17,borderWidth:1,borderColor:'#36576A',backgroundColor:'#102638',padding:15},sampleRight:{position:'absolute',right:'7%',top:'13%',bottom:'13%',width:'25%',borderRadius:17,borderWidth:1,borderColor:'#2E786F',backgroundColor:'#0E3435',alignItems:'center',justifyContent:'center'},sampleWall:{position:'absolute',left:'68%',top:'10%',bottom:'10%',width:4,borderRadius:2,backgroundColor:'#9B704E'},sampleCurve:{position:'absolute',left:'12%',height:5,borderRadius:3,backgroundColor:'#688697',transform:[{rotate:'-8deg'}]},lockRing:{width:56,height:56,borderRadius:28,borderWidth:4,borderColor:'#58D4C3',alignItems:'center',justifyContent:'flex-end'},lockBody:{width:38,height:28,borderRadius:7,backgroundColor:'#58D4C3',marginBottom:-10},
 costTrack:{position:'absolute',left:'8%',right:'8%',top:'28%',height:34,borderRadius:17,backgroundColor:'#183044',overflow:'hidden'},costGross:{height:'100%',backgroundColor:'#4ED0BE'},minusTickOne:{position:'absolute',width:4,height:72,left:'62%',top:'22%',backgroundColor:'#986D4C'},minusTickTwo:{position:'absolute',width:4,height:72,left:'72%',top:'22%',backgroundColor:'#986D4C'},minusTickThree:{position:'absolute',width:4,height:72,left:'80%',top:'22%',backgroundColor:'#986D4C'},costNet:{position:'absolute',left:'8%',width:'52%',top:'62%',height:24,borderRadius:12,backgroundColor:'#4C7888'},
 overfitLeft:{position:'absolute',left:'5%',top:'10%',bottom:'10%',width:'43%',borderRadius:16,borderWidth:1,borderColor:'#35566A',backgroundColor:'#102638'},overfitRight:{position:'absolute',right:'5%',top:'10%',bottom:'10%',width:'43%',borderRadius:16,borderWidth:1,borderColor:'#795C42',backgroundColor:'#231C18'},overfitDivider:{position:'absolute',left:'50%',top:20,bottom:20,width:1,backgroundColor:'#315063'},overfitSmooth:{position:'absolute',left:'12%',right:'12%',bottom:'25%',height:6,borderRadius:3,backgroundColor:'#4FCFBD',transform:[{rotate:'-20deg'}]},overfitJagged:{...StyleSheet.absoluteFillObject},jag:{position:'absolute',height:5,borderRadius:3,backgroundColor:'#67CFC2'},testFall:{position:'absolute',left:'12%',top:'30%',width:'72%',height:6,borderRadius:3,backgroundColor:'#A47350',transform:[{rotate:'28deg'}]},testNoise:{position:'absolute',left:'20%',right:'20%',bottom:'24%',height:12,borderRadius:6,backgroundColor:'#5C4B3D'},
 timeLine:{position:'absolute',left:'9%',right:'9%',top:'55%',height:4,borderRadius:2,backgroundColor:'#607C8D'},decisionDot:{position:'absolute',width:22,height:22,borderRadius:11,backgroundColor:'#53D2C1',left:'34%',top:'51%'},futureZone:{position:'absolute',right:'8%',top:'18%',bottom:'18%',width:'38%',borderRadius:16,borderWidth:1,borderColor:'#8A6548',backgroundColor:'rgba(130,90,56,0.13)'},forbiddenArrow:{position:'absolute',right:'35%',top:'42%',width:'26%',height:5,borderRadius:3,backgroundColor:'#B77D55',transform:[{rotate:'180deg'}]},forbiddenSlash:{position:'absolute',width:82,height:5,borderRadius:3,backgroundColor:'#C68960',right:'28%',top:'40%',transform:[{rotate:'45deg'}]},
 assetGrid:{position:'absolute',left:'10%',right:'10%',top:'14%',bottom:'14%',flexDirection:'row',flexWrap:'wrap',gap:12,justifyContent:'center',alignContent:'center'},assetCell:{width:50,height:50,borderRadius:16,borderWidth:1,borderColor:'#35566B',backgroundColor:'#132B3D',alignItems:'center',justifyContent:'center'},assetDead:{borderColor:'#725942',backgroundColor:'#261F1A'},assetInner:{width:15,height:15,borderRadius:8,backgroundColor:'#5ACFBE'},deadSlash:{width:28,height:4,borderRadius:2,backgroundColor:'#A97854',transform:[{rotate:'-45deg'}]},
 tank:{position:'absolute',left:'8%',top:'23%',width:'30%',height:'54%',borderRadius:18,borderWidth:1,borderColor:'#2F786F',backgroundColor:'#0E3334',overflow:'hidden'},tankRight:{left:undefined,right:'8%',borderColor:'#3C586B',backgroundColor:'#102638'},tankFill:{position:'absolute',left:0,right:0,bottom:0,height:'65%',backgroundColor:'#2D8177'},tankFillMuted:{backgroundColor:'#436274'},leakArrow:{position:'absolute',left:'37%',top:'49%',width:'27%',height:5,borderRadius:3,backgroundColor:'#A97854'},blockGate:{position:'absolute',left:'48%',top:'36%',width:52,height:72,borderRadius:14,borderWidth:2,borderColor:'#A97854',backgroundColor:'#231C18',alignItems:'center',justifyContent:'center'},gateSlash:{width:48,height:5,borderRadius:3,backgroundColor:'#B88159',transform:[{rotate:'45deg'}]},
 robustLeft:{position:'absolute',left:'6%',bottom:'13%',width:'41%',height:'72%',flexDirection:'row',alignItems:'flex-end',justifyContent:'space-around'},robustRight:{position:'absolute',right:'6%',bottom:'13%',width:'41%',height:'72%',flexDirection:'row',alignItems:'flex-end',justifyContent:'space-around'},robustDivider:{position:'absolute',left:'50%',top:20,bottom:20,width:1,backgroundColor:'#315063'},terrainBar:{width:20,borderTopLeftRadius:8,borderTopRightRadius:8,backgroundColor:'#8C6548'},terrainGood:{backgroundColor:'#4DCBBA'},
 pipeline:{position:'absolute',left:'8%',right:'8%',top:'24%',height:82,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},guardRail:{position:'absolute',left:'12%',right:'12%',bottom:'18%',height:56,borderRadius:18,borderWidth:1,borderColor:'#2F756D',backgroundColor:'#0E3234',flexDirection:'row',alignItems:'center',justifyContent:'space-around'},guardDot:{width:16,height:16,borderRadius:8,backgroundColor:'#58D1C0'},killSwitch:{width:42,height:42,borderRadius:21,borderWidth:2,borderColor:'#9B704E',alignItems:'center',justifyContent:'center'},killInner:{width:16,height:16,borderRadius:8,backgroundColor:'#9B704E'},
});
