import React from 'react';
import { Image, Platform, StyleSheet, Text, useWindowDimensions, View, type ImageSourcePropType } from 'react-native';
import type { LearningLanguage } from '../../domain/learning/presentation';
import { defaultLearningTheme, type LearningTheme } from '../../theme/learningTheme';
import type { LessonSupportingVisualRole } from './LessonSupportingVisual';

type Topic = 'risk' | 'volatility' | 'size' | 'reward' | 'stop' | 'diversification';
type Props = { assetRef: string; alt: string; language: LearningLanguage; role: LessonSupportingVisualRole; theme?: LearningTheme };
type ArtworkSet = Record<LessonSupportingVisualRole, ImageSourcePropType>;
const artwork: Record<Topic, ArtworkSet> = {
  risk: { hook: require('../../../assets/learning/beginner/risk/risk-uncertainty-hook.svg'), concept: require('../../../assets/learning/beginner/risk/risk-uncertainty-concept.svg'), practice: require('../../../assets/learning/beginner/risk/risk-uncertainty-practice.svg'), misconception: require('../../../assets/learning/beginner/risk/risk-uncertainty-misconception.svg'), risk: require('../../../assets/learning/beginner/risk/risk-uncertainty-misconception.svg'), summary: require('../../../assets/learning/beginner/risk/risk-uncertainty-summary.svg') },
  volatility: { hook: require('../../../assets/learning/beginner/risk/volatility-risk-hook.svg'), concept: require('../../../assets/learning/beginner/risk/volatility-risk-concept.svg'), practice: require('../../../assets/learning/beginner/risk/volatility-risk-practice.svg'), misconception: require('../../../assets/learning/beginner/risk/volatility-risk-misconception.svg'), risk: require('../../../assets/learning/beginner/risk/volatility-risk-misconception.svg'), summary: require('../../../assets/learning/beginner/risk/volatility-risk-summary.svg') },
  size: { hook: require('../../../assets/learning/beginner/risk/position-size-hook.svg'), concept: require('../../../assets/learning/beginner/risk/position-size-concept.svg'), practice: require('../../../assets/learning/beginner/risk/position-size-practice.svg'), misconception: require('../../../assets/learning/beginner/risk/position-size-misconception.svg'), risk: require('../../../assets/learning/beginner/risk/position-size-misconception.svg'), summary: require('../../../assets/learning/beginner/risk/position-size-summary.svg') },
  reward: { hook: require('../../../assets/learning/beginner/risk/risk-reward-hook.svg'), concept: require('../../../assets/learning/beginner/risk/risk-reward-concept.svg'), practice: require('../../../assets/learning/beginner/risk/risk-reward-practice.svg'), misconception: require('../../../assets/learning/beginner/risk/risk-reward-misconception.svg'), risk: require('../../../assets/learning/beginner/risk/risk-reward-misconception.svg'), summary: require('../../../assets/learning/beginner/risk/risk-reward-summary.svg') },
  stop: { hook: require('../../../assets/learning/beginner/risk/stop-risk-hook.svg'), concept: require('../../../assets/learning/beginner/risk/stop-risk-concept.svg'), practice: require('../../../assets/learning/beginner/risk/stop-risk-practice.svg'), misconception: require('../../../assets/learning/beginner/risk/stop-risk-misconception.svg'), risk: require('../../../assets/learning/beginner/risk/stop-risk-misconception.svg'), summary: require('../../../assets/learning/beginner/risk/stop-risk-summary.svg') },
  diversification: { hook: require('../../../assets/learning/beginner/risk/diversification-hook.svg'), concept: require('../../../assets/learning/beginner/risk/diversification-concept.svg'), practice: require('../../../assets/learning/beginner/risk/diversification-practice.svg'), misconception: require('../../../assets/learning/beginner/risk/diversification-misconception.svg'), risk: require('../../../assets/learning/beginner/risk/diversification-misconception.svg'), summary: require('../../../assets/learning/beginner/risk/diversification-summary.svg') },
};
function topicForAsset(assetRef: string): Topic | undefined { if (assetRef.includes('risk-belirsizlik-kayip')) return 'risk'; if (assetRef.includes('volatilite-once-risktir')) return 'volatility'; if (assetRef.includes('pozisyon-buyuklugu-once-gelir')) return 'size'; if (assetRef.includes('risk-getiri-tek-basina-yetmez')) return 'reward'; if (assetRef.includes('stop-emri-garanti-midir')) return 'stop'; if (assetRef.includes('cok-varlik-cesitlendirme-degildir')) return 'diversification'; return undefined; }
export function isBeginnerRiskStoryAsset(assetRef: string): boolean { return Boolean(topicForAsset(assetRef)); }
export function BeginnerRiskStoryVisual({ assetRef, alt, language, role, theme = defaultLearningTheme }: Props) { const topic = topicForAsset(assetRef); if (!topic) return null; const { width } = useWindowDimensions(); const compact = width < 520; const styles = createStyles(theme, compact); if (Platform.OS === 'web') return <View style={styles.shell} accessibilityRole="image" accessibilityLabel={alt}><Image source={artwork[topic][role]} style={styles.artwork} resizeMode="contain" accessible={false} /></View>; return <View style={styles.shell} accessibilityRole="image" accessibilityLabel={alt}><NativeRiskScene topic={topic} role={role} language={language} styles={styles} /></View>; }
function NativeRiskScene({ topic, role, language, styles }: { topic: Topic; role: LessonSupportingVisualRole; language: LearningLanguage; styles: ReturnType<typeof createStyles> }) { const tr = language === 'tr'; const warning = role === 'misconception' || role === 'risk'; if (topic === 'reward') return <View style={styles.horizontal}><View style={[styles.circle, styles.lossCircle]}><Text style={styles.number}>1</Text></View><Text style={styles.symbol}>:</Text><View style={[styles.circle, styles.goodCircle]}><Text style={styles.number}>3</Text></View>{warning ? <Text style={styles.question}>?</Text> : null}</View>; if (topic === 'stop') return <View style={styles.stage}><View style={styles.stopLine} /><NativeBars values={[70, 62, 55, 47, 33, 27]} warning styles={styles} /><View style={styles.fillDot} /></View>; if (topic === 'diversification') return <View style={styles.horizontal}><View style={styles.sourceDot} /><View style={styles.branchStem} /><View style={styles.outcomeStack}><View style={[styles.smallDot, styles.goodCircle]} /><View style={styles.smallDot} /><View style={[styles.smallDot, styles.lossCircle]} /></View></View>; if (topic === 'volatility') return <View style={styles.stage}><NativeBars values={warning ? [30, 75, 20, 82, 28, 70] : [35, 48, 32, 54, 38, 50]} warning={warning} styles={styles} /></View>; if (topic === 'size') return <View style={styles.horizontal}><View style={styles.smallExposure} /><View style={styles.largeExposure} /><Text style={styles.micro}>{tr ? 'MİKTAR → ETKİ' : 'SIZE → IMPACT'}</Text></View>; return <View style={styles.horizontal}><View style={styles.sourceDot} /><Text style={styles.symbol}>→</Text><Text style={styles.question}>?</Text></View>; }
function NativeBars({ values, warning = false, styles }: { values: number[]; warning?: boolean; styles: ReturnType<typeof createStyles> }) { return <View style={styles.bars}>{values.map((height, index) => <View key={`${height}.${index}`} style={styles.barSlot}><View style={[styles.bar, { height }, warning && styles.warningBar]} /></View>)}</View>; }
const createStyles = (theme: LearningTheme, compact: boolean) => StyleSheet.create({ shell: { width: '100%', maxWidth: 620, aspectRatio: 1.5, alignSelf: 'center', borderRadius: compact ? 16 : 18, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: '#071522', overflow: 'hidden', alignItems: 'center', justifyContent: 'center' }, artwork: { width: '100%', height: '100%' }, stage: { width: '88%', height: '76%', position: 'relative', alignItems: 'center', justifyContent: 'center' }, horizontal: { width: '84%', height: '70%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: compact ? 16 : 24, position: 'relative' }, circle: { width: compact ? 86 : 112, height: compact ? 86 : 112, borderRadius: 999, borderWidth: 3, alignItems: 'center', justifyContent: 'center' }, goodCircle: { backgroundColor: '#0D3437', borderColor: '#55CDBF' }, lossCircle: { backgroundColor: '#241D22', borderColor: '#A76561' }, number: { color: '#DCE8EC', fontSize: compact ? 32 : 42, fontWeight: '900' }, symbol: { color: '#91A7B4', fontSize: compact ? 30 : 40, fontWeight: '900' }, question: { color: '#DCE8EC', fontSize: compact ? 40 : 52, fontWeight: '900' }, stopLine: { position: 'absolute', left: '5%', right: '40%', top: '56%', height: 4, borderRadius: 4, backgroundColor: '#A76561' }, fillDot: { position: 'absolute', left: '60%', top: '59%', width: 18, height: 18, borderRadius: 99, backgroundColor: '#DCE8EC' }, bars: { width: '100%', height: '72%', flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-around', gap: 6 }, barSlot: { flex: 1, alignItems: 'center', justifyContent: 'flex-end' }, bar: { width: '68%', minWidth: 8, maxWidth: 24, borderRadius: 5, backgroundColor: '#55CDBF' }, warningBar: { backgroundColor: '#A76561' }, sourceDot: { width: compact ? 70 : 90, height: compact ? 70 : 90, borderRadius: 999, backgroundColor: '#102431', borderWidth: 3, borderColor: '#6F8796' }, branchStem: { width: compact ? 70 : 100, height: 4, backgroundColor: '#4E8990' }, outcomeStack: { gap: 12 }, smallDot: { width: compact ? 44 : 56, height: compact ? 44 : 56, borderRadius: 999, backgroundColor: '#102431', borderWidth: 2, borderColor: '#6F8796' }, smallExposure: { width: '20%', height: '32%', borderRadius: 12, backgroundColor: '#55CDBF' }, largeExposure: { width: '38%', height: '66%', borderRadius: 12, backgroundColor: '#A76561' }, micro: { color: '#91A7B4', fontSize: compact ? 9 : 11, fontWeight: '800' } });
